### PR TITLE
fix(Core): Crashfix.

### LINKED ISSUE #14534: [server] world server crash 20230106
### Current Behaviour

crash log:

https://gist.github.com/mpfans/ead1c7f11d6e78009fbbb89a0a4e40a5

### Expected Blizzlike Behaviour

none

### Source

_No response_

### Steps to reproduce the problem

none

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/8d2dda24ed85e835953156d1df429567bfc6fea8

### Operating system

Ubuntu20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes#14534

 

## Issues Addressed:

- Closes #14534

## Tests Performed:

- Not tested.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
@mpfans Please, test it.

**Review by Nefertumm — APPROVED** [review]

File: src/server/game/Movement/Spline/MovementPacketBuilder.cpp [hunk 1]
```diff
@@ -191,7 +191,10 @@ namespace Movement
 
             uint32 nodes = move_spline.getPath().size();
             data << nodes;
-            data.append<Vector3>(&move_spline.getPath()[0], nodes);
+            if (nodes > 0)
```
Comment (Kitzunu) [inline src/server/game/Movement/Spline/MovementPacketBuilder.cpp:194]: this can't be if (nodes) ?

Comment (UltraNix) [reply src/server/game/Movement/Spline/MovementPacketBuilder.cpp:194]: Of course it can be.

Comment (Kitzunu) [reply src/server/game/Movement/Spline/MovementPacketBuilder.cpp:194]: so why not?

Comment (UltraNix) [reply src/server/game/Movement/Spline/MovementPacketBuilder.cpp:194]: Really? It changes anything?

Comment (Kitzunu) [reply src/server/game/Movement/Spline/MovementPacketBuilder.cpp:194]: ofc it doesnt change anything, but as far as I can see and remember that is how most of such checks are made. No reason to provide extra things that doesn't do anything?

Comment (FrancescoBorzi) [reply src/server/game/Movement/Spline/MovementPacketBuilder.cpp:194]: I'd keep it `nodes > 0`

**Comment by mpfans** [comment]
image
This is the running time of the previous crashes. I think the crash has been fixed

File: src/server/game/Movement/Spline/MovementPacketBuilder.cpp (hunk 1 above)
Comment (Nyeriah) [reply src/server/game/Movement/Spline/MovementPacketBuilder.cpp:194]: It's an uint32 so it will never be < 0

Comment (UltraNix) [reply src/server/game/Movement/Spline/MovementPacketBuilder.cpp:194]: But it can be 0...

Comment (Nyeriah) [reply src/server/game/Movement/Spline/MovementPacketBuilder.cpp:194]: I’m not sure if I am following. If it’s 0, it will return false with the changes @Kitzunu suggested. Yes, it’s the same as it does currently, but the other approach is more readable as the value can never be negative, due to unsigned variable

Comment (Nefertumm) [reply src/server/game/Movement/Spline/MovementPacketBuilder.cpp:194]: I'll change it, it's pointless to have the PR waiting for this.
