### PR TITLE
fix(DB/Quest): Rigglefuzz in badlands has a bugged question mark for engineers.

### LINKED ISSUE #6649: Rigglefuzz Goblin NPC in badlands has a bugged question mark for engineers
**CURRENT BEHAVIOUR:**

The goblin gives you a ready to complete quest with a recipe reward for engineers, but after that, the question mark remains active over his head, besides that he have 3 normal quests more to give you.

WoWScrnShot_063021_051439
WoWScrnShot_063021_051451
WoWScrnShot_063021_051459

For non engineers characters, is displayed correctly:

WoWScrnShot_063021_051631

**EXPECTED BLIZZLIKE BEHAVIOUR:**

After accepting the first offering, it should display the normal exclamation mark for the players on the level range, and no the question mark.

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. Make an engineer character.
2. Go to badlands and find the greedy goblin (NPC info in the screenshot) 
3. Accept the recipe offering and see what happens next.

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 

(AC HASH/COMMIT: 53ab534) :

**OPERATING SYSTEM:**

Windows 10 21H1

**MODULES:**

No.

**CUSTOMIZATIONS:**

None.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99559551-rigglefuzz-goblin-npc-in-badlands-has-a-bugged-question-mark-for-engineers?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Zenslash**
## Changes Proposed:
-  Now after completing engineers quest it display the normal exclamation mark for the players on the level range

## Issues Addressed:
- Closes #6649 

## Tests Performed:
- Tested on local server

## How to Test the Changes:

1. Make an engineer character.
2. ```.go creature 6862```
3. Take ```Flash Bomb Recipe``` quest and complete it
4.  Observe

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1625244599291561100.sql [hunk 1]
```diff
@@ -0,0 +1,3 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1625244599291561100');
+
+UPDATE `quest_template` SET `QuestType` = 2 WHERE (`ID` = 1559);
```
Comment (FrancescoBorzi) [inline data/sql/updates/pending_db_world/rev_1625244599291561100.sql:3]: don't forget to add a new empty line at the end of file:

image

Comment (Zenslash) [reply data/sql/updates/pending_db_world/rev_1625244599291561100.sql]: @FrancescoBorzi Thanks, already fixed it

**Review by FrancescoBorzi — APPROVED** [review]
