### PR TITLE
fix(Core): Activate creatures and objects during opening cinematics

### LINKED ISSUE #4039: No NPCs during character creation cinematic intro video and other flyby
##### SMALL DESCRIPTION:

The cinematic video after the character creation doesn't show the NPCs during the flyby transition since the objects are not in sync with the camera. 

The fix is available here: https://github.com/TrinityCore/TrinityCore/commit/87b4533046d337fe05d7891c3632d34f8811b73e  we should be able to easily import it

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You should be able to see the creatures

##### CURRENT BEHAVIOUR:

No NPCs and objects during the video

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a new character
2. Watch the video

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/38bf355bf479

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/95449575-no-npcs-during-character-creation-cinematic-intro-video-and-other-flyby?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Si1ker**
This change will result in the capability to see NPCs/GOs during character intro cinematic
### Warning:
* Requires re-running map extractor to extract camera m2 files from data

## Changes Proposed:
-  **Port:** TrinityCore/TrinityCore@87b4533
-  **Adapt:** Porting adapted to AC structure
- **Standardize:** Small cleanup from the original port and add brackets

## Issues Addressed:
- Closes #4039 

## Tests Performed:
- N/A

## How to Test the Changes:

- Create any new character
- Watch the whole cinematic
- The NPCs/GOs should be shown in the cinematic

## Known Issues and TODO List:

- N/A

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

File: src/server/game/Entities/Player/Player.h [hunk 1]
```diff
@@ -2642,6 +2642,17 @@ class Player : public Unit, public GridObject<Player>
 
     static std::unordered_map<int, bgZoneRef> bgZoneIdToFillWorldStates; // zoneId -> FillInitialWorldStates
 
+    // Cinematic camera data and remote sight functions
+    uint32 GetActiveCinematicCamera() const { return m_activeCinematicCameraId; }
+    void SetActiveCinematicCamera(uint32 cinematicCameraId = 0) { m_activeCinematicCameraId = cinematicCameraId; }
+    bool IsOnCinematic() const { return (m_cinematicCamera != nullptr); }
```
Comment (FrancescoBorzi) [inline src/server/game/Entities/Player/Player.h:2648]: please add `[[nodiscard]]` to all getter methods that have no side effects

File: src/server/shared/DataStores/DBCStructure.h [hunk 2]
```diff
@@ -672,25 +672,23 @@ struct ChrRacesEntry
...
-*/
 
 struct CinematicSequencesEntry
 {
     uint32      Id;                                         // 0 index
     //uint32      unk1;                                     // 1 always 0
-    //uint32      cinematicCamera;                          // 2 id in CinematicCamera.dbc
-    // 3-9 always 0
+    uint32      cinematicCamera;                            // 2 id in CinematicCamera.dbc
+                                                            // 3-9 always 0
```
Comment (Kitzunu) [inline src/server/shared/DataStores/DBCStructure.h:691]: ?

Comment (Si1ker) [reply src/server/shared/DataStores/DBCStructure.h:691]: ?

File: src/server/game/Entities/Player/Player.h (hunk 1 above)
Comment (Si1ker) [reply src/server/game/Entities/Player/Player.h]: @FrancescoBorzi  added !

File: src/server/shared/DataStores/DBCStructure.h (hunk 2 above)
Comment (Kitzunu) [reply src/server/shared/DataStores/DBCStructure.h:691]: Why add two spaces on line 690 instead of using tabs?

**Comment by Yehonal** [comment]
Tabs? Evil

Il ven 25 dic 2020, 18:34 Kitzunu <notifications@github.com> ha scritto:

**Comment by Kitzunu** [comment]
Anyhow the two spaces make no sense, I think my tabs are put to four spaces, but anyhow. they serve no purpose what I can see

**Comment by Yehonal** [comment]
Yep, we're using the 4 spaces. Indeed

Il ven 25 dic 2020, 19:11 Kitzunu <notifications@github.com> ha scritto:

**Comment by Kitzunu** [comment]
Yea I just confirmed I use that :P

**Comment by FrancescoBorzi** [comment]
```
Player.h:2647:7: fatal error: attribute 'nodiscard' cannot be applied to functions without return value [-Wignored-attributes]
    [[nodiscard]] void SetActiveCinematicCamera(uint32 cinematicCameraId = 0) { m_activeCinematicCameraId = cinematicCameraId; }
```

@Si1ker the attribute `[[nodiscard]]` is meant to be used on getter methods (typically named e.g. `GetSomeAttr()` or `IsSomeAttr()` pr `hasSomeAttr()`, etc...) that cause NO SIDE EFFECTS (i.e. they just give you a value without performing any other action). Its purpose is to make sure that you only call such methods when you really need their returned values.
So if you call such methods and do not use their return values, they will give you a warning. This will be useful to make sure that these methods aren't called without reason :)

Because of that, it does not make sense to use `[[nodiscard]]` on methods that don't return any value at all (i.e. `void` functions). I hope it's clear :)

**Comment by FrancescoBorzi** [comment]
@Si1ker build still failing:

```
src/server/game/Maps/Map.cpp:2298:28: fatal error: no matching constructor for initialization of 'acore::VisibleNotifier'
    acore::VisibleNotifier notifier(*player);
```

File: src/server/game/Entities/Object/Object.cpp [hunk 3]
```diff
@@ -1529,13 +1529,32 @@ bool Position::IsPositionValid() const
...
         return IsInWintergrasp() ? VISIBILITY_DIST_WINTERGRASP : GetMap()->GetVisibilityRange();
+    }
     else if (ToCreature())
+    {
         return ToCreature()->m_SightDistance;
+    }
     else if (GetTypeId() == TYPEID_GAMEOBJECT && ToGameObject()->IsTransport())
-        return GetMap()->GetVisibilityRange();
+    {
+        if (isActiveObject())
```
Comment (Kitzunu) [inline src/server/game/Entities/Object/Object.cpp:1545]: You can add if isActiveObject() to the else if above else if (GetTypeId() == TYPEID_GAMEOBJECT && ToGameObject()->IsTransport() && isActiveObject())

This way you don't need two else return 0.0f

Comment (Yehonal) [reply src/server/game/Entities/Object/Object.cpp:1545]: indeed

File: src/server/game/Maps/Map.h [hunk 4]
```diff
@@ -408,8 +408,8 @@ class Map : public GridRefManager<NGridType>
     void AddObjectToSwitchList(WorldObject* obj, bool on);
     virtual void DelayedUpdate(const uint32 diff);
 
-    //void UpdateObjectVisibility(WorldObject* obj, Cell cell, CellCoord cellpair);
-    //void UpdateObjectsVisibilityFor(Player* player, Cell cell, CellCoord cellpair);
+    void UpdateObjectVisibility(WorldObject* obj, Cell cell, CellCoord cellpair);
```
Comment (Yehonal) [inline src/server/game/Maps/Map.h:411]: I doubt this PR will ever work with just a "copy/paste" since the **UpdateObjectVisibility** and **UpdateObjectsVisibilityFor** are not used within our code.

You should check where TC uses those function but also please, double check the PR code to spot other similar issues if any

**Review by Yehonal — APPROVED** [review]

**Review by Yehonal — CHANGES_REQUESTED** [review]
Approved by mistake

File: src/server/game/Entities/Object/Object.cpp (hunk 3 above)
Comment (Helias) [reply src/server/game/Entities/Object/Object.cpp]: done

File: src/server/game/Maps/Map.h (hunk 4 above)
Comment (Helias) [reply src/server/game/Maps/Map.h:410]: I think it's not related, it works locally ;-)

**Comment by Helias** [comment]
Tested, it works

**Review by Helias — APPROVED** [review]

**Comment by Kitzunu** [comment]
Why merge this? GCC without modules is failing. Please fix it.

**Comment by yuanf225** [comment]
微信截图_20210202111940
there is an error here at compile time

**Comment by Kitzunu** [comment]
You're most likely using an outdated compiler.

All builds pass on latest master branch, look at the CI's and you will know what is supported :)

**Comment by yuanf225** [comment]
okay，let me update my compiler thanks!
