### PR TITLE
fix(Core/Combat): Pets should put their owners in combat only on init…

### LINKED ISSUE #14498: Hunter's Pet Combat Bug
Original Issue: https://github.com/chromiecraft/chromiecraft/issues/4490

### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

https://github.com/azerothcore/azerothcore-wotlk/issues/10683
https://github.com/chromiecraft/chromiecraft/issues/2928

Upon entering a PvP fight and the pet hits a target or receives a dot/debuff I cannot reset my combat state. Even using Feign Death drops combat, then immediately re-enters. Even if doing so twice, and even if using shadowmeld with pet on passive. Any dot on the pet also keeps the player in combat until the ENTIRE duration is gone. Even if it's a debuff from say a shadow priest adding shadow dmg etc. This happens with multiple hunter pets.  Feign Death is properly dropping combat sometimes and immediately re-entering it, but the pet seems to continuously be in a state of combat for a long period of time as well, ie 10-14 seconds. Using Shadowmeld will drop combat, but instantly re-enter because of how the pet is linked to the hunter and some weird combat bugged state. If a player puts a debuff or dot on the pet, both the hunter and pet will be stuck in combat until it's dispelled and time passes or the duration finishes. This is insanely huge for PvP. Please address this issue. It's insanely frustrating. I have had 0 problems exiting combat with Feign Death and Shadowmeld after a fight without an active pet, so it's definitely tied to pets, and how they link up with player combat states.

### Expected Blizzlike Behaviour

**In PvP, a player will leave combat if they have not attacked or been attacked for 5 seconds**, or all the enemy characters that have attacked you are killed.

Under most circumstances in PvE, once all monsters have lost interest in you, you will be removed from combat. 

[Hunters](https://wowwiki-archive.fandom.com/wiki/Hunter)

    [Feign Death](https://wowwiki-archive.fandom.com/wiki/Feign_Death), on a 25-30-second cooldown, **removes the hunter from combat. In PvP**, this is usually used to remove the hunter as a target and cancelling all incoming spellcasts. In PvE, it will cause mobs to forget about the hunter.

### Source

https://wowwiki-archive.fandom.com/wiki/Combat

### Steps to reproduce the problem

1. Enter a PvP state of combat with another player.
2. Attack said target with attacks and the pet.
3. Have the opponent dot the pet and or player.
4. after killing opponent, attempt to Feign Death or Shadowmeld.
5. Notice that combat drops(sometimes) and immediately re-enters within .1 seconds.
6. Die IRL in agony.

### Extra Notes

I tested it on my local server in Warsong Gulch.

Related issue: https://github.com/azerothcore/azerothcore-wotlk/issues/10683

### AC rev. hash/commit

3ad652d8ab96 2023-01-03

### Operating system

Ubuntu 20.04 - Windows 10 x64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…ial attack.

Fixes #14498

## Issues Addressed:

- Closes #14498
- Closes https://github.com/chromiecraft/chromiecraft/issues/2928
- Closes https://github.com/chromiecraft/chromiecraft/issues/2934
- Closes https://github.com/chromiecraft/chromiecraft/issues/4490

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

Enter a PvP state of combat with another player.
Attack said target with attacks and the pet.
Have the opponent dot the pet and or player.
after killing opponent, attempt to Feign Death or Shadowmeld.
Notice that combat drops properly

Create a hunter and summon your pet
Engage higher level mob (I tested in Blasted Lands) with hunter and pet
After mob is dead, count the seconds it takes to leave combat

Create a hunter with pet
Enter BG
Attack a player with both pet and your character
Call pet back and Feign Death

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by IntelligentQuantum — APPROVED** [review]

File: src/server/game/Entities/Unit/Unit.cpp [hunk 1]
```diff
@@ -13585,14 +13585,19 @@ void Unit::CombatStart(Unit* victim, bool initialAggro)
...
         }
 
+        bool alreadyInCombat = HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IN_COMBAT);
+
         SetInCombatWith(victim);
         victim->SetInCombatWith(this);
 
         // Xinef: If pet started combat - put owner in combat
-        if (Unit* owner = GetOwner())
+        if (!alreadyInCombat && HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IN_COMBAT))
```
Comment (Kitzunu) [inline src/server/game/Entities/Unit/Unit.cpp:13594]: Could use IsInCombat()

File: src/server/game/Entities/Unit/Unit.cpp [hunk 2]
```diff
@@ -13585,14 +13585,19 @@ void Unit::CombatStart(Unit* victim, bool initialAggro)
             }
         }
 
+        bool alreadyInCombat = HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IN_COMBAT);
```
Comment (Kitzunu) [inline src/server/game/Entities/Unit/Unit.cpp:13588]:
```suggestion
        bool alreadyInCombat = HasUnitFlag(UNIT_FLAG_IN_COMBAT);
```

**Comment by UltraNix** [comment]
@Kitzunu Done.

**Review by Kitzunu — APPROVED** [review]
