### PR TITLE
fix(DB/Creatures): Corrupted Blue Whelp should stop respawning if Bro…

### LINKED ISSUE #11123: [BWL] Whelps near Broodlord Lashlayer should stop spawning when he is dead.
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [x] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

The whelps keep spawning after his dead. 

### Expected Blizzlike Behaviour

The whelps should no longer spawn after he is dead.

### Extra Notes

Corrupted blue whelp 
image

Corrupted bronze whelp 
image

corrupted red whelp 
image

corrup;ted green whelp 
image

### AC rev. hash/commit

77f13636b75f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…odlord Lashlayer is dead.

Fixes #11123

## Issues Addressed:

- Closes #11123

## Tests Performed:

- Not tested.

## How to Test the Changes:

`.go creature 2000035`
Kill it
Wait 30 sec until it respawns
Kill it again
Kill Broodlord Lashlayer
See that whelp does not respawn anymore.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Lynethris** [comment]
Tested and work.

7min after Brood is killed:
WoWScrnShot_032622_132750

File: data/sql/updates/pending_db_world/rev_1648294393927803100.sql [hunk 1]
```diff
@@ -0,0 +1,45 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1648294393927803100');
+
+DELETE FROM `linked_respawn` WHERE `guid` BETWEEN 2000009 AND 2000049;
+INSERT INTO `linked_respawn` VALUES
```
Comment (Nefertumm) [inline data/sql/updates/pending_db_world/rev_1648294393927803100.sql:4]:
```suggestion
INSERT INTO `linked_respawn` (`guid`, `linkedGuid`, `linkType`) VALUES
```

**Review by Nefertumm — APPROVED** [review]
