### PR TITLE
fix(DB/Spell): Valentine event buffs grouping

### LINKED ISSUE #18285: (Event/LoveisintheAir): Colognes and Perfumes stack.
### Current Behaviour

Currently the various colognes and perfumes offered by the Love is in the Air vendors all stack.

### Expected Blizzlike Behaviour

They should all overwrite one another.

### Source

Wrath Classic

### Steps to reproduce the problem

1. `.event start 8`
2. `.additem 49856`, `.additem 49857`
3. Use the two perfumes.
4. Observe both perfumes are active.

### Extra Notes

Originally reported at https://github.com/chromiecraft/chromiecraft/issues/6631.

### AC rev. hash/commit

e2f1648941ad48cccaef777ca2ecf63806b629e1

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

### PR DESCRIPTION
**Pull request by kasvati**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #18285 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Obtain following items **49856, 49857, 49858, 49859, 49861, 49860** (itemId's)
2. Use them simultaneously
3. Effects should not stack anymore

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
https://www.azerothcore.org/wiki/sql-standards

File: data/sql/updates/pending_db_world/rev_1707833862449013500.sql [hunk 1]
```diff
@@ -0,0 +1,8 @@
+-- disables buff stacking for items 49856, 49857, 49858, 49859, 49861, 49860
+INSERT INTO `spell_group` VALUES
```
Comment (heyitsbench) [inline data/sql/updates/pending_db_world/rev_1707833862449013500.sql:2]: You can put the column names back, otherwise all's good to me.

**Comment by kasvati** [comment]
didn't know about the standards it should be correct now

**Comment by avarishd** [comment]
We always delete before inserting.

File: data/sql/updates/pending_db_world/rev_1707833862449013500.sql [hunk 2]
```diff
@@ -0,0 +1,8 @@
+-- disables buff stacking for items 49856, 49857, 49858, 49859, 49861, 49860
+INSERT INTO `spell_group` (`id`, `spell_id`, `special_flag`) VALUES
```
Comment (elthehablo) [inline data/sql/updates/pending_db_world/rev_1707833862449013500.sql:2]: when you do an insert, it is important to do a downquery as well by deleting the entries before the insert.

so here you would want a DELETE FROM `spell_group` with id 2 and spell_ids in there as well

File: data/sql/updates/pending_db_world/rev_1707833862449013500.sql [hunk 3]
```diff
@@ -0,0 +1,8 @@
...
+(2, 70233, 16),
+(2, 70234, 16),
+(2, 70235, 16),
+(2, 70242, 16),
+(2, 70243, 16),
+(2, 70244, 16);
```
Comment (elthehablo) [inline data/sql/updates/pending_db_world/rev_1707833862449013500.sql:8]: I think it's fine to use id 1 instead of 2. but according to the wiki you should use a lowest available id above 1000 if the spell won't be used in core code

**Comment by elthehablo** [comment]
Aside from that, the changes seem to work nicely after testing. Thanks for the PR <3

**Comment by kasvati** [comment]
Made rest of the changes and changed id to 1035 which is the lowest available above 1000.

**Review by elthehablo — APPROVED** [review]
