### PR TITLE
fix(DB/Gameobject): Recalculate quaternion rotation values from orientation

### LINKED ISSUE #9000: Halls of Stone - Door to last boss is open.
### Current Behaviour

The door that closes the route to last boss is turned by a quarter. Therefor u can just walk past it straight to the last boss and not complete the Brann escort event.

Image

### Expected Behaviour

The door should seal of the area and only be opened by Brann when the escort event is complete and someone from the party talked to Brann to open the door.

[](url)https://youtu.be/WwXJ5vyHyjY?si=nnOu5qFPzY1iW5I6&t=1087

### Source

[](url)https://youtu.be/WwXJ5vyHyjY?si=nnOu5qFPzY1iW5I6&t=1087

### Steps to reproduce the problem

The door was already opened at the start of the dungeon.

### Extra Notes

_No response_

### Customizations

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/871163b1cc22d246b4f6bec09a31116e1a0e5dcf

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-chromiecraft-smartstone](https://github.com/chromiecraft/mod-chromiecraft-smartstone)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-evade-logging](https://github.com/heyitsbench/mod-evade-logging)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-quests](https://github.com/azerothcore/mod-pvp-quests)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by blinkysc**
## Changes Proposed:
This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

Previously, the core had a hack that computed rotation from orientation at runtime when rotation2 and rotation3 were both 0. After removing that hack (using quaternions properly), gameobjects with placeholder (0,0,0,0) rotation would appear wrong.

This SQL recalculates quaternion rotation values (rotation2, rotation3) from orientation for all gameobjects with Z-axis-only rotation (rotation0=0, rotation1=0). This fixes the 90-degree rotation offset caused by removing the orientation->quaternion hackfix in #24602.

### AI-assisted Pull Requests

- [x] AI tools (e.g. ChatGPT, Claude, or similar) were used entirely or partially in preparing this pull request. Please specify which tools were used, if any.

Claude Code with AzerothMCP

## SOURCE:
The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [x] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

- Closes https://github.com/chromiecraft/chromiecraft/issues/9000
Reference: TrinityCore commit 02cef6f034 (cmangos/mangos-wotlk@2bcbc0f)

## Tests Performed:
This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [x] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Apply the SQL update
2. Restart worldserver
3. Check gameobjects that previously appeared rotated 90 degrees off

### CODE REVIEW

**Comment by sudlud** [comment]
please either limit this to entries with `VerifiedBuild` not set or do it in the core (?) when loading the entries

**Comment by Nyeriah** [comment]
> please either limit this to entries with `VerifiedBuild` not set or do it in the core (?) when loading the entries

Why? Isn't this a cherry-pick?

**Comment by blinkysc** [comment]
Think it's supposed to be all but trying to check real quick

**Comment by Nyeriah** [comment]
Limiting this to verifiedbuild rows defeats the point of the PR since those are the ones we are having issues with, as for handling it in the core I'm not sure if storing transitory data is the best design, but I am willing to concede on that

**Comment by Nyeriah** [comment]
Also please fix the commit cherry-pick references, for proper author crediting

**Comment by Rorschach91** [comment]
I tested it by checking the Violet Hold door, the Halls of Stone door, and Gundrak’s bridge and doors. Everything seems to be working well.

**Comment by blinkysc** [comment]
> I tested it by checking the Violet Hold door, the Halls of Stone door, and Gundrak’s bridge and doors. Everything seems to be working well.

Updated to be non verified, battlefield for wintergrasp and some transport values. So deserves second check.

**Comment by blinkysc** [comment]
SQL linter is false positive as well

File: src/server/game/Entities/GameObject/GameObject.h [hunk 1]
```diff
@@ -394,7 +394,7 @@ class GameObject : public WorldObject, public GridObject<GameObject>, public Mov
     bool m_allowModifyDestructibleBuilding;
 
     int64 m_packedRotation;
-    G3D::Quat m_localRotation;
+    G3D::Quat m_worldRotation;
```
Comment (sudlud) [inline src/server/game/Entities/GameObject/GameObject.h]:
```suggestion
    G3D::Quat WorldRotation;
```

**Review by sudlud — APPROVED** [review]
