### PR TITLE
fix(DB/smart_scripts): Add abilities to Arcanist Torseldori and Bloodmage

### LINKED ISSUE #4037: [NPC] Thrallmar Bloodmages incorrect behavior when fighting
##### CURRENT BEHAVIOUR:

[Arcanist Torseldori](https://www.wowhead.com/npc=19257/arcanist-torseldori) (creature entry 19257) and [Bloodmages](https://www.wowhead.com/?npc=19258) outside of Thrallmar uses melee when fighting against the Infernal Invaders.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They should be casting spells (comment section on wowhead suggests a special version of blizzard).

##### STEPS TO REPRODUCE THE PROBLEM:

1. gm command ".tele Thrallmar"
2. go outside the gates to Supply Caravan
3. wait for infernals to spawn
3. observe fight

##### EXTRA NOTES:

WoWScrnShot_122320_113052

##### AC HASH/COMMIT:

[1f5babf](https://github.com/azerothcore/azerothcore-wotlk/commit/1f5babf0a65c346d7876c4f4813a3dda5e8200f7)

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

AH Bot, Autobalance, Transmog

##### OTHER CUSTOMIZATIONS:

N/A

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/95449577-npc-thrallmar-bloodmages-incorrect-behavior-when-fighting?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Si1ker**
Co-Authored-By: r0m1ntik <r0m1ntik@users.noreply.github.com>
Imported from https://github.com/azerothcore/azerothcore-wotlk/issues/4037#issuecomment-750945759

## Changes Proposed:
-  Update AIName to 'SmartAI'
-  Add 'smart_scripts' to [Arcanist Torseldori](https://www.wowhead.com/npc=19257/arcanist-torseldori) and [Bloodmage](https://www.wowhead.com/npc=19258/bloodmage)

## Issues Addressed:
- Closes #4037 

## Tests Performed:
- **SQL Queries applied:** /* Affected rows: 9  Found rows: 0  Warnings: 0  Duration for 5 queries: 0.016 sec. */
- **Tested in-game as the pictures below can confirm:**
image
image

## How to Test the Changes:

.go xyz 55.249 2540.771 64.492 530 5.739
(wait for infernals to spawn and watch the fight)

## Known Issues and TODO List:

- N/A

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1608949912835926000.sql [hunk 1]
```diff
@@ -0,0 +1,19 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1608949912835926000');
+
+UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` IN (19257, 19258);
+
+-- Arcanist Torseldori
+DELETE FROM `smart_scripts` WHERE `entryorguid` = 19257;
```
Comment (FrancescoBorzi) [inline data/sql/updates/pending_db_world/rev_1608949912835926000.sql:6]: ALWAYS specify the `source_type` as well when deleting `smart_scripts`, otherwise you will delete also the `entryorguid` of other types, which is not intended :)

File: data/sql/updates/pending_db_world/rev_1608949912835926000.sql [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+(19257, 0, 0, 0, 4, 0, 100, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Arcanist Torseldori - On aggro - say text'),
+(19257, 0, 1, 0, 0, 0, 100, 0, 1000, 1000, 3000, 4000, 0, 11, 15530, 64, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Arcanist Torseldori - IC - Cast spell Frostbolt'),
+(19257, 0, 2, 0, 0, 0, 100, 0, 4000, 10000, 10000, 14000, 0, 11, 12674, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Arcanist Torseldori - IC - Cast spell Frost Nova'),
+(19257, 0, 3, 0, 0, 0, 100, 0, 10000, 15000, 13000, 24000, 0, 11, 33634, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Arcanist Torseldori - IC - Cast spell Frost Blizzard');
+
+-- Bloodmage
+DELETE FROM `smart_scripts` WHERE `entryorguid` = 19258;
```
Comment (FrancescoBorzi) [inline data/sql/updates/pending_db_world/rev_1608949912835926000.sql:14]: same as above

**Review by FrancescoBorzi — CHANGES_REQUESTED** [review]

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by wizzymore** [comment]
Tested and works 😄

**Comment by pklloveyou** [comment]
Tested
