### PR TITLE
Fix(Scripts/DireMaul): Rewrite Isalien fight

### LINKED ISSUE #9110: Boss of D2 set questline Isalien issues
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

[Isalien](https://wowgaming.altervista.org/aowow/?npc=16097) summoned by [Brazier of Beckoning](https://wowgaming.altervista.org/aowow/?item=22050). Current state;

1. After summon Isalien is instantly start attacking random player in 50y range
2. Despawn timer of Isalien about 30 seconds
3. Isalien call [Empyrean](https://wowgaming.altervista.org/aowow/?npc=16098) on agro
4. Isalien missing on death yell
5. Pet doesn't disapear after wipe

https://user-images.githubusercontent.com/85256266/141104244-d1b4ca86-2f22-46e7-9a95-f18178075081.mp4

### Expected Blizzlike Behaviour

1. Isalien should not attack after summon. Only if someone in agro range.
2. Isalien remain until defeated. There is no need to resummon him upon wiping, or even if the brazier holder leaves the instance or group. Only one Isalien per instance.
3. Isalien should call Empyrean about 8 seconds after summon
4. Isalien should have on death yell
5. I guess pet should disapear to prevent situation on my video

### Source

Wowwiki [Isalien](https://wowwiki-archive.fandom.com/wiki/Isalien)
>Isalien will summon a fairly strong pet (Empyrean, a hippogryph) about 10 seconds into the fight. When she does, everyone but the MT should concentrate on it until dead. Her skills include: Root, Starshards, Heal
Her primary damage is spell damage. She can be disarmed, and should be when possible. But the key to defeating this encounter is to interrupt her heal spells, but it is possible to drain her mana through the various abilities different classes have, or to simply force her to heal herself. Once you kill the pet and learn to time the heal interrupts, she goes down easily.

Wowhead [Isalien](https://www.wowhead.com/npc=16097/isalien)

https://youtu.be/9GqtR_lskT0?t=52

### Steps to reproduce the problem

.go c id 11492 - teleport to Alzzin the Wildshaper 
.cast 27190

### Extra Notes

There is 2 triggers of Isalien.
WoWScrnShot_111021_135014

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/12e92b58082dfda8b73b50aa97b98b9479bb7629

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by Nefertumm**
## Changes Proposed:
-  Move SAI to cpp
-  Add movement before cast Regrowth.

## Issues Addressed:

- Closes #9110

## Tests Performed:

-  Tested in-game.

## How to Test the Changes:

1.  .go c id 11492 - teleport to Alzzin the Wildshaper
2.  .cast 27190

## Known Issues and TODO List:

- [ ]  Timers?

### CODE REVIEW

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by IntelligentQuantum** [comment]
works fine for me.

File: src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp [hunk 1]
```diff
@@ -64,6 +64,9 @@ class instance_dire_maul : public InstanceMapScript
                     }
                     HighborneSummoners.push_back(creature->GetGUID());
                     break;
+                case NPC_ISALIEN:
```
Comment (Nyeriah) [inline src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:67]: where is this guid used? if it's not used anywhere there's no need to declare it

**Comment by Nefertumm** [comment]
Done @Nyeriah
