### PR TITLE
fix(Core/Creature): Move hardcoded text/gossips to DB - boss_ignis

### LINKED ISSUE #4156: Core/Creature: hardcoded text in boss_ignis
##### CURRENT BEHAVIOUR:

https://github.com/azerothcore/azerothcore-wotlk/blob/79aa5606547d898542557a01a2150f76e477e9e9/src/server/scripts/Northrend/Ulduar/Ulduar/boss_ignis.cpp#L46-L55

Need to convert to DB so locales can make use of it

AC HASH/COMMIT: 79aa560
OPERATING SYSTEM: w10

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/95701918-core-creature-hardcoded-text-in-boss_ignis?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by avarishd**
Part of https://github.com/azerothcore/azerothcore-wotlk/projects/15 Going trough the entirety of Ulduar
All of the creature_text is already in DB
## Changes Proposed:
-  Added the missing (wasn't being used before) SAY_SUMMON, source TC & [YT](https://www.youtube.com/watch?v=PYlfUoY9I3Y)

## Issues Addressed:

- Closes #4156
## Tests Performed:

- Tested in-game with sound

## How to Test the Changes:

1. .go c 136371
2. Pull (with sound enabled)

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/scripts/Northrend/Ulduar/Ulduar/boss_ignis.cpp [hunk 1]
```diff
@@ -296,24 +286,15 @@ class boss_ignis : public CreatureScript
             me->setActive(false);
         }
 
-        void KilledUnit(Unit*  /*victim*/) override
+        void KilledUnit(Unit* who) override
```
Comment (Kitzunu) [inline src/server/scripts/Northrend/Ulduar/Ulduar/boss_ignis.cpp:289]:
```suggestion
        void KilledUnit(Unit* victim) override
```

**Review by Kitzunu — CHANGES_REQUESTED** [review]

File: src/server/scripts/Northrend/Ulduar/Ulduar/boss_ignis.cpp [hunk 2]
```diff
@@ -57,26 +57,17 @@
...
-#define SOUND_AGGRO                     15564
-#define SOUND_ACTIVATE_CONSTRUCT        15565
-#define SOUND_SLAG_POT                  15566
-#define SOUND_SCORCH_1                  15567
-#define SOUND_SCORCH_2                  15568
-#define SOUND_SLAY_1                    15569
-#define SOUND_SLAY_2                    15570
-#define SOUND_BERSERK                   15571
-#define SOUND_DEATH                     15572
+enum IgnisText
```
Comment (Kitzunu) [inline src/server/scripts/Northrend/Ulduar/Ulduar/boss_ignis.cpp:60]:
```suggestion
enum Text
```

File: src/server/scripts/Northrend/Ulduar/Ulduar/boss_ignis.cpp [hunk 3]
```diff
@@ -57,26 +57,17 @@
...
+{
+    SAY_AGGRO       = 0,
+    SAY_SUMMON      = 1,
+    SAY_SLAG_POT    = 2,
+    SAY_SCORCH      = 3,
+    SAY_SLAY        = 4,
+    SAY_BERSERK     = 5,
+    SAY_DEATH       = 6,
+    SAY_EMOTE_JETS  = 7,
```
Comment (Kitzunu) [inline src/server/scripts/Northrend/Ulduar/Ulduar/boss_ignis.cpp:69]: Just EMOTE_

**Review by Kitzunu — APPROVED** [review]
