### PR TITLE
fix(DB/Loot): Corrected skinning loot for Scorpid Workers.

### LINKED ISSUE #10447: Skinning Scorpid Workers in Valley of Trials
https://github.com/chromiecraft/chromiecraft/issues/2902

### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The Scorpid Workers which are spawning in the Valley of Trials are dropping higher lever skinables like Medium Leather, hides, or Red whelp scales.
WoWScrnShot_012922_180802
WoWScrnShot_012922_180820
WoWScrnShot_012922_180833

### Expected Blizzlike Behaviour

The skinning drop should be changed according to the NPC level. 

### Source

- https://www.wowhead.com/npc=3124/scorpid-worker
- Medium Leather, [(https://www.wowhead.com/item=2319/medium-leather)](url)
- Medium Hide, [(https://www.wowhead.com/item=4232/medium-hide)](url)
- Light Hide [(https://www.wowhead.com/item=783/light-hide)](url)
- Light Leather.  [https://www.wowhead.com/item=2318/light-leather](url)
- Red whelp scale [https://www.wowhead.com/item=7287/red-whelp-scale](url)

### Steps to reproduce the problem

1. Check the drop list of the Scorpid Worker
2. Skin the Scorpid 

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3774fd9ac8241994396426e6c5f9246ce56400b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #10447

## Issues Addressed:

- Closes #10447
- Closes https://github.com/chromiecraft/chromiecraft/issues/2902

## Tests Performed:

- Not tested.

## How to Test the Changes:

Check the drop list of the Scorpid Worker
Skin the Scorpid

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1644769898514768700.sql [hunk 1]
```diff
@@ -0,0 +1,7 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1644769898514768700');
+
+UPDATE `creature_template` SET `skinloot`=3124 WHERE `entry`=3124;
+DELETE FROM `skinning_loot_template` WHERE `entry`=3124;
+INSERT INTO `skinning_loot_template` VALUES
+(3124,2318,0,10,0,1,1,1,1,'Light Leather');
+(3124,2934,0,88,0,1,1,1,1,'Ruined Leather Scraps');
```
Comment (acidmanifesto) [inline data/sql/updates/pending_db_world/rev_1644769898514768700.sql:7]: you have two semi ; where as you only need one.

**Review by acidmanifesto — CHANGES_REQUESTED** [review]

File: data/sql/updates/pending_db_world/rev_1644769898514768700.sql (hunk 1 above)
Comment (FrancescoBorzi) [reply data/sql/updates/pending_db_world/rev_1644769898514768700.sql:7]: @UltraNix build failing

**Review by acidmanifesto — APPROVED** [review]
