### PR TITLE
fix(Core/WorldSession): incorrect fmt formatting

### LINKED ISSUE #20006: SendAreaTriggerMessage not fmt formatted
### Current Behaviour

wrong format error message when trying to enter an instance "You must be at least level {} to enter."

area_trigger

### Expected Blizzlike Behaviour

{} should be 70 in this case

### Source

https://github.com/azerothcore/azerothcore-wotlk/blob/a196f7f28aa263dc7f9c532e15839f3b409fb68f/src/server/game/Handlers/MiscHandler.cpp#L691

likely this as well 

https://github.com/azerothcore/azerothcore-wotlk/blob/a196f7f28aa263dc7f9c532e15839f3b409fb68f/src/server/game/Handlers/MiscHandler.cpp#L708

### Steps to reproduce the problem

level <70
1. `.go xyz 3088 1375 185 530 4.6`
2. try to enter

### Extra Notes

_No response_

### AC rev. hash/commit

a196f7f28aa2

### Operating system

ubuntu 24.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by Exitare**
## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #20006

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. #20006 

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/game/Server/WorldSession.h [hunk 1]
```diff
@@ -348,8 +348,56 @@ class WorldSession
     void SendPacket(WorldPacket const* packet);
     void SendPetNameInvalid(uint32 error, std::string const& name, DeclinedName* declinedName);
     void SendPartyResult(PartyOperation operation, std::string const& member, PartyResult res, uint32 val = 0);
-    void SendAreaTriggerMessage(const char* Text, ...) ATTR_PRINTF(2, 3);
-    void SendAreaTriggerMessage(uint32 entry, ...);
+
+    template<typename... Args>
+    void SendAreaTriggerMessage(char const* Text, Args&&... args)
+    {
+        char szStr[1024];
```
Comment (sogladev) [inline src/server/game/Server/WorldSession.h:355]: Is a fixed size buffer required? If not, this can be simplified:
```
    void SendAreaTriggerMessage(char const* Text, Args&&... args)
    {
        // Use Acore::StringFormat to generate the formatted string
        std::string formattedStr = Acore::StringFormat(Text, std::forward<Args>(args)...);
        uint32 length = formattedStr.size() + 1;
        ...

    }
```

Comment (Exitare) [reply src/server/game/Server/WorldSession.h:355]: The old code had this fixed buffer.

```
va_list ap;
char szStr [1024];
szStr[0] = '\0';
```

I tried to be a close to the old code as possible. But if we can get rid of it, i will simplify it. Thanks for the feedback :)

**Comment by sudlud** [comment]
Please merge master for CI codecheck fix

**Review by Kitzunu — APPROVED** [review]

File: src/server/game/Server/WorldSession.h [hunk 2]
```diff
@@ -348,8 +348,40 @@ class WorldSession
...
+            std::string formattedStr = Acore::StringFormat(format, std::forward<Args>(args)...);
+            uint32 length = formattedStr.size() + 1;
+
+            // Create the packet and send it
+            WorldPacket data(SMSG_AREA_TRIGGER_MESSAGE, 4 + length);
+            data << length;
+            data << formattedStr;
+            SendPacket(&data);
+        }
+    }
```
Comment (Kitzunu) [inline src/server/game/Server/WorldSession.h:383]: Actually, I would like as little code in headerfiles as possible. So I would do something like this in the headerfile
```cpp
void SendAreaTriggerMessage(std::string_view str);

template<typename... Args>
void SendAreaTriggerMessage(char const* fmt, Args&&... args)
{
    if (HasSession())
        SendAreaTriggerMessage(Acore::StringFormat(fmt, std::forward<Args>(args)...));
}
template<typename... Args>
void SendAreaTriggerMessage(uint32 strId, Args&&... args)
{
    if (HasSession())
        SendAreaTriggerMessage(Acore::StringFormat(GetAcoreString(strId), std::forward<Args>(args)...));
}
```
and in the the cpp file I would move what you got now. so
```cpp
void WorldSession::SendAreaTriggerMessage(std::string_view str)
{
    std::vector<std::string_view> lines = Acore::Tokenize(str, '\n', true);
    for (std::string_view line : lines)
    {
        uint32 length = line.size() + 1;
        WorldPacket data(SMSG_AREA_TRIGGER_MESSAGE, 4 + length);
        data << length;
        data << line.data();
        SendPacket(&data);
    }
}

Comment (Exitare) [reply src/server/game/Server/WorldSession.h:383]: Thanks. I was also a little bit at odds with the implementation in the h file.

File: src/server/game/Server/WorldSession.h [hunk 3]
```diff
@@ -348,8 +348,22 @@ class WorldSession
...
+    template<typename... Args>
+    void SendAreaTriggerMessage(char const* fmt, Args&&... args)
+    {
+        if (!m_playerLoading)
+            SendAreaTriggerMessage(Acore::StringFormat(fmt, std::forward<Args>(args)...));
+    }
+    template<typename... Args>
+    void SendAreaTriggerMessage(uint32 strId, Args&&... args)
+    {
+        if (!m_playerLoading)
```
Comment (Kitzunu) [inline src/server/game/Server/WorldSession.h:363]: Why not hassession

Comment (Exitare) [reply src/server/game/Server/WorldSession.h:363]: @Kitzunu, HasSession() is available via the ChatHandler. I can use that if it's requested. 
I went with a variable that is available in the WorldSession itself.

Comment (Kitzunu) [reply src/server/game/Server/WorldSession.h:363]: true, my bad

**Review by Kitzunu — APPROVED** [review]

**Comment by Kitzunu** [comment]
Did you test it again after my changes? if so we can merge it

**Comment by Exitare** [comment]
Yes, i tested it yesterday evening again, after all the requested changes.
