### PR TITLE
fix(DB/Spell): fix item "Blessed Medallion of Karabor"

### LINKED ISSUE #20908: [Black Temple Entrance] Item: Blessed Medallion of Karabor teleports to the wrong location
Issue linked from CC: https://github.com/chromiecraft/chromiecraft/issues/7613

Triage Notes: As the author I didn't find any mentioned of saying that this was changed in wotlk. So i will pressumed it just a bug.

Original Post Below: 

---

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

[Blessed Medallion of Karabor](https://wowgaming.altervista.org/aowow/?item=32757) teleport the caster in front of BT entrance

### Expected Blizzlike Behaviour

[Blessed Medallion of Karabor](https://wowgaming.altervista.org/aowow/?item=32757) should teleport the caster in front of [Xi'ri](https://wowgaming.altervista.org/aowow/?npc=18528)

### Source

[TBC Classic](https://youtu.be/APsUnpjBblw?t=1418) at 23:40 , you can see the warlock using his [Blessed Medallion of Karabor](https://wowgaming.altervista.org/aowow/?item=32757) and it shows the teleport location.

[TBC Classic](https://youtu.be/zP8DBD_CUqM?t=1596) at 26:37 , the raid uses [Blessed Medallion of Karabor](https://wowgaming.altervista.org/aowow/?item=32757) and all of them teleported near [Xi'ri](https://wowgaming.altervista.org/aowow/?npc=18528)

### Steps to reproduce the problem

1. .add 32757
2. equip and use [Blessed Medallion of Karabor](https://wowgaming.altervista.org/aowow/?item=32757)

### Extra Notes

I am not sure if there was a change from 3.3.5a to classic? i didn't find anything that says the teleport location has been changed between versions.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c3c75122162c56ae3d73386206077ec23b7683e

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by Exitare**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #20908
- Closes https://github.com/chromiecraft/chromiecraft/issues/7613
## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by TheSCREWEDSoftware** [comment]
@Exitare did you sniff these values or you went the place and grab the `.gps` values?

**Comment by Exitare** [comment]
I do not have an sniff. I watched the provided videos and used .gps.
Its not perfect but its the correct place with the correct orientation now. If a sniff is required we might have to find one as I don't have the seems to create one.

**Comment by Grimdhex** [comment]
It's more a question for AC staff. I think that we can merge this and with the label we will know that something that we can update later. 

Otherwise I think that we will wait a lot of time. Not enough people to gatherer all the sniffs.

**Comment by Exitare** [comment]
Sure, no problem. Just wanted to be as informative as possible about what I have and don't have :)

File: data/sql/updates/pending_db_world/rev_1734414765273447900.sql [hunk 1]
```diff
@@ -0,0 +1,5 @@
+--
+DELETE FROM `spell_target_position` WHERE `ID` = '41234' AND `EffectIndex` = '0';
+
+INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`)
+VALUES ('41234', '0', '0', '-3560.6572', '582.82887', '10.987', '4.768543');
```
Comment (Kitzunu) [inline data/sql/updates/pending_db_world/rev_1734414765273447900.sql:5]: dont use quotes around the values unless it is a string

**Comment by Exitare** [comment]
Can this be merged? @Nyeriah

**Review by Nyeriah — APPROVED** [review]

**Comment by heyitsbench** [comment]
This PR has the incorrect map ID set, sending players into the Great Sea.

**Comment by Kitzunu** [comment]
Awesome...

**Comment by TheSCREWEDSoftware** [comment]
This wasn't testes :/?
