### PR TITLE
Fix(Core/MC): Golemagg

### LINKED ISSUE #9119: [Molten Core] Golemagg Issues
### Current Behaviour

- [x] Golemagg's Trust isn't active on adds when they are close to boss
- [x] Magmasplash is not being used on tanks
- [x] Golemagg is using Enrage (Not listed on wowhead)
- [x] Earthquake at 10% is not happening, or not doing AOE damage.
- [ ] When Golemagg dies, the Adds die

### Expected Blizzlike Behaviour

- [ ] Golemagg's trust needs to be active on adds when tanked too closely
- [ ] Magmasplash should be used on the tanks
- [ ] Golemagg should not use enrage
- [ ] Earthquake needs to happen at 10% and should deal area damage (this is the enrage)
- [ ] When golemagg dies, adds should despawn so no loot is there.

### Source

https://classic.wowhead.com/guides/golemagg-the-incinerator-molten-core-strategy

### Steps to reproduce the problem

Go to MC
Golemagg

### AC rev. hash/commit

009a52d1f13c

### Operating system

Win64

### Custom changes or Modules

Eluna

### PR DESCRIPTION
**Pull request by Nefertumm**
## Changes Proposed:
-  Re-add previously deleted auras (this is because a known bug with implicit target auras and we should delete them again when that bug is fixed, as the auras should be in creature_template_addon and not hardcoded)
-  Update encounter states during the fight
-  Use the new method for random targets.

## Issues Addressed:

- Closes #9119 

## Tests Performed:

- Built and tested in-game.

## How to Test the Changes:

Fight Golemagg in MC, and see the issue addressed. 

## Known Issues and TODO List:

- [ ]  Remove the hardcoded cast auras from the code and use them in creature_template_addon (they are already there, just not working because of the bug)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_golemagg.cpp [hunk 1]
```diff
@@ -58,13 +60,27 @@ class boss_golemagg : public CreatureScript
...
             pyroblastTimer = urand(3000, 7000);
             enraged = false;
+            DoCastSelf(SPELL_MAGMASPLASH);
+            DoCastSelf(SPELL_GOLEMAGG_TRUST_AURA);
+            DoCastSelf(SPELL_DOUBLE_ATTACK);
+
+            instance->SetBossState(DATA_GOLEMAGG, FAIL);
+        }
+
+        void JustDied(Unit* /*killer*/) override
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_golemagg.cpp:70]: were the states not updating correctly before? because without the override, they should update by default

File: src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_golemagg.cpp [hunk 2]
```diff
@@ -58,13 +60,27 @@ class boss_golemagg : public CreatureScript
             earthquakeTimer = 0;
             pyroblastTimer = urand(3000, 7000);
             enraged = false;
+            DoCastSelf(SPELL_MAGMASPLASH);
+            DoCastSelf(SPELL_GOLEMAGG_TRUST_AURA);
+            DoCastSelf(SPELL_DOUBLE_ATTACK);
+
+            instance->SetBossState(DATA_GOLEMAGG, FAIL);
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_golemagg.cpp:67]: keep in mind Reset() is also called when the mob has just spawned, so this will default his boss state to FAIL

File: src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_golemagg.cpp (hunk 1 above)
Comment (Nefertumm) [reply src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_golemagg.cpp:70]: Without this changes there were no updates before.

File: src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_golemagg.cpp (hunk 2 above)
Comment (Nefertumm) [reply src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_golemagg.cpp:67]: Good to know!

File: src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_golemagg.cpp (hunk 1 above)
Comment (Kitzunu) [reply src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_golemagg.cpp:68]: sounds to me like a bug with BossAI and should perhaps be tackled there instead of inside every script?

Comment (Nefertumm) [reply src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_golemagg.cpp:68]: Idk why though, I've just checked BossAI and it must update the BossState. But adding this appears to solve the issue, unless there is another way

Comment (Nefertumm) [reply src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_golemagg.cpp:68]: @Kitzunu perhaps, it should be checked by someone

Comment (Nyeriah) [reply src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_golemagg.cpp:68]: how did you check that the states were not updating?

Comment (Nefertumm) [reply src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_golemagg.cpp:68]: Because this script was never executed (i put a breakpoint using debug to see if that script was working or not) https://github.com/azerothcore/azerothcore-wotlk/blob/707b6d1234e644391dd4589991f1031b0b46f54b/src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/instance_molten_core.cpp#L268

Comment (Nyeriah) [reply src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_golemagg.cpp:68]: I just tried and it's working for me without the override. Had you killed him before you tried debugging it? If it's set to DONE the state doesn't get updated again

https://user-images.githubusercontent.com/47818697/142301572-c0c85bf0-6cc8-4557-b485-918eefacdde3.mp4

Comment (Nefertumm) [reply src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_golemagg.cpp:68]: Odd, I tried multiple times and it didn't get executed, and it seems it happened to the report author too. I'll try again when I come back home.

Comment (Nefertumm) [reply src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_golemagg.cpp:68]: Yep, I tried again and now it worked for me. I'm reverting the setboss changes.

**Comment by claudiodfc** [comment]
## Test results:
- ❌ Golemagg's trust needs to be active on adds when tanked too closely
- ❌ Magmasplash should be used on the tanks
- ✔ Golemagg should not use enrage
- ✔ Earthquake needs to happen at 10% and should deal area damage (this is the enrage)
- ✔ When golemagg dies, adds should despawn so no loot is there.

### Notes
Used GM God but checked for spells casted and affected.
Core Rager's as using Trash. Typing this because I'm unsure if it's Blizzlike or not.

**Comment by Nefertumm** [comment]
Can't reproduce the errors you have.
https://www.youtube.com/watch?v=OCOFPr9D9rM

**Comment by Nyeriah** [comment]
Seems to be working as expected.
Skärmbild 2021-11-22 142606

**Review by Nyeriah — APPROVED** [review]

**Comment by claudiodfc** [comment]
My bad again 😅
