### PR TITLE
fix(Core/Mail): Pending auction sale mail should be destroyed as soon…

### LINKED ISSUE #5920: Amount Pending Mails from AH should be automatically deleted on arrival of the money [$35]
Original report: https://github.com/chromiecraft/chromiecraft/issues/436 by @j-hdt

Additional information from @necropola:
>The **Money Mail**  is delayed (I've tested it) by `MailDeliveryDelay` from `worldserver.conf` (default: 3600 seconds = 1 hour, ChromieCraft: 150 seconds) and the **Amount Pending Mail** arrives immediately on sale of an item. I've also verified that  the **Amount Pending Mail** has exactly the expiration time that the **Money Mail** is delayed for. 
>
>The **Amount Pending Mail** stays in your Mailbox for quite a while after it has expired, because the cleanup job which deletes or returns expired mails does only run **every 6 hours**. It would probably be better (less irritating), if the cleanup job would run more often or at least at a configurable (`worldserver.conf`) frequency instead of being hardcoded:
https://github.com/azerothcore/azerothcore-wotlk/blob/b2ab5dba79c180608323c5ca02b9f815b6d35833/src/server/game/World/World.cpp#L2246-L2250
> In fact it looks like Blizzard intended the **Amount Pending Mails** to be automatically deleted on arrival of the money: https://www.bluetracker.gg/wow/topic/us-en/1777876864-auction-house-sale-pending-notice/
>
> Also, the **Estimated Delivery Time**  is always `00:00` which probably isn't correct, too.
>
>image

#### WHAT CLIENT DO YOU PLAY ON?
- [x] enGB
- [ ] enUS
- [ ] other (specify)

##### FACTION
- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:
- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:
When an auction you inserted into the auction house is bought, you receive a in-game mail. One hour later you receive the gold reduced by the costs. The notification mail for the sell does not disappear.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
when receiving the mail containing the gold, the notification mail should disappear from the inbox.

##### STEPS TO REPRODUCE THE PROBLEM:
 - Which commands to use? Which NPC to teleport to?
 - Do we need to have debug flags on Cmake?
 - Do we need to look at the console while the bug happens?
 - Other steps
 - Use the ingame commands to identify the unique GUID of an ore/herb/npc:    .npc info  /  .gobject near
-->

1. insert auction into auction house
2. buy item from a different account
3. see the first mail arrive
4. one hour later when the gold arrives, the first mail should disappear

##### EXTRA NOTES:
There might be different behavior if you are online during the sell or the 1h period - or open the mail.
but in general those notification mails could be flagged with a 1h disappearing timer instead of 30 days.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
There is a **[$35 open bounty](https://www.bountysource.com/issues/98542579-amount-pending-mails-from-ah-should-be-automatically-deleted-on-arrival-of-the-money?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
## Changes Proposed:
-  Fixed body message in case of pending sale auction mail
-  Added code that ensures pending sale mail is deleted with its expiration time.

P.S. https://github.com/azerothcore/azerothcore-wotlk/pull/3420 This commit introduced many bugs with mails (not loading items on player login - only items with delivery timer > present timer, visual bugs in mailbox, "You inbox is full" message and more. I really don't know why this commit has been even made).

## Issues Addressed:

- Closes #5920

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

Follow #5920.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
> P.S. #3420 This commit introduced many bugs with mails (not loading items on player login - only items with delivery timer > present timer, visual bugs in mailbox, "You inbox is full" message and more. I really don't know why this commit has been even made).

cc @peti446

**Comment by UltraNix** [comment]
This comment has no impact on the PR.
I just write that to underline that @peti446 commit introduced many bugs - some of them are fixed by this PR.

**Comment by tkn963** [comment]
It appears to be working as it should. I had one strange thing happening where the estimated time etc did not match up. It said '1 sec' in the mailbox for almost 2 full minutes before it actually changed to what it should've been. This might be unrelated and just how 'slow' the mail-system updates. Other than this, it seems to be okay.

https://imgur.com/a/EGpPpcg

**Comment by UltraNix** [comment]
It's not related to this one.

**Comment by tkn963** [comment]
> 
> 
> It's not related to this one.

I know, that's why I mentioned that. Either way, I tested it and it works as it should afaik

File: data/sql/updates/pending_db_characters/rev_1621780938723425400.sql [hunk 1]
```diff
@@ -0,0 +1,4 @@
+INSERT INTO `version_db_characters` (`sql_rev`) VALUES ('1621780938723425400');
+
+ALTER TABLE `mail` 
+ADD COLUMN `auctionId` INT(11) DEFAULT 0 NOT NULL AFTER `checked`;
```
Comment (Helias) [inline data/sql/updates/pending_db_characters/rev_1621780938723425400.sql:4]: do not put the length to the INT type, it will be deprecated soon in the next mysql version

File: src/server/game/AuctionHouse/AuctionHouseMgr.cpp [hunk 2]
```diff
@@ -153,9 +153,16 @@ void AuctionHouseMgr::SendAuctionSalePendingMail(AuctionEntry* auction, SQLTrans
     if (owner || owner_accId)
     {
         sScriptMgr->OnBeforeAuctionHouseMgrSendAuctionSalePendingMail(this, auction, owner, owner_accId, sendMail);
+
+        uint32 deliveryDelay = sWorld->getIntConfig(CONFIG_MAIL_DELIVERY_DELAY);
```
Comment (Helias) [inline src/server/game/AuctionHouse/AuctionHouseMgr.cpp:157]: I think that you can set `auto` instead of uint32, because the function `getIntConfig()` already return an uint32 by default

File: src/server/game/Entities/Player/Player.cpp [hunk 3]
```diff
@@ -19309,27 +19309,33 @@ void Player::_LoadMail()
...
 
+    std::set<uint32> pendingAuctions;
+    std::unordered_map<uint32, Mail*> pendingAuctionMails;
+
     mMitems.clear();
 
     //Now load the new ones
     m_mailCache.clear();
+
+    SQLTransaction pendingAuctionsTrans = CharacterDatabase.BeginTransaction();
```
Comment (Helias) [inline src/server/game/Entities/Player/Player.cpp:19334]: same here, you should be able to use `auto`

File: data/sql/updates/pending_db_characters/rev_1621780938723425400.sql (hunk 1 above)
Comment (Kitzunu) [reply data/sql/updates/pending_db_characters/rev_1621780938723425400.sql:4]: good catch

File: src/server/game/Entities/Player/Player.cpp (hunk 3 above)
Comment (UltraNix) [reply src/server/game/Entities/Player/Player.cpp:19334]: No - stop using `auto` with no reason.

Comment (Helias) [reply src/server/game/Entities/Player/Player.cpp:19334]: the reason is to infer the type, this can have different advantages, one of this is to change only one line of code if you need to change the return type of the function

here a real example in azerothcore

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@UltraNix can you please fix the conflicts?
