### PR TITLE
fix(Scripts/SethekkHalls): Talon King Ikiss

### LINKED ISSUE #15466: [Sethek Halls] Ikiss abilities
https://github.com/chromiecraft/chromiecraft/issues/5207
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

casts his combo of blink, immunity and arcane explosion once after 35s
https://github.com/azerothcore/azerothcore-wotlk/blob/465c5b12e40881079c596f58186682c95050ecf1/src/server/scripts/Outland/Auchindoun/SethekkHalls/boss_talon_king_ikiss.cpp#L77

and casts sheep on the highest threat holder in normal mode
https://github.com/azerothcore/azerothcore-wotlk/blob/465c5b12e40881079c596f58186682c95050ecf1/src/server/scripts/Outland/Auchindoun/SethekkHalls/boss_talon_king_ikiss.cpp#L95

and doesnt reset aggro after finishing the explosion

### Expected Blizzlike Behaviour

Should cast his combo at 80%, 50% and 25%.
Further, after finishing the explosion, he should reset aggro.
and cast sheep randomly also in normal mode

### Source

https://youtu.be/bVOcDgwtb8I?t=646
https://youtu.be/2woCE4u49DM?t=1282
https://wowwiki-archive.fandom.com/wiki/Talon_King_Ikiss
> Blink - often to someone (even if they are out of LoS) — He casts this spell at 80% HP and again at 50% HP and once more at 25% HP. Right after he Blinks he casts Arcane Explosion

### Steps to reproduce the problem

.go c 138719

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ff0c607ecec81e9793d521cc1adfe3883e20ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Talon King Ikiss should cast his combo at 80%, 50% and 25%. After finishing the explosion, Talon King Ikiss should reset aggro. Talon King Ikiss cast sheep randomly also in normal mode. Fixes #15466

## Issues Addressed:

- Closes #15466
- Closes https://github.com/chromiecraft/chromiecraft/issues/5207

## Tests Performed:

- Not tested.

## How to Test the Changes:

`.go c 138719`

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
@Tereneckla Please, test it.

**Comment by Tereneckla** [comment]
Almost perfect

Bubble should happen with the teleport instead of at the start of the cast

**Comment by Nyeriah** [comment]
Could use ScheduleHealthCheckEvents()

https://github.com/Nyeriah/azerothcore-wotlk/blob/master/src/server/scripts/Outland/TempestKeep/Mechanar/boss_pathaleon_the_calculator.cpp#L60-L65

File: src/server/scripts/Outland/Auchindoun/SethekkHalls/boss_talon_king_ikiss.cpp [hunk 1]
```diff
@@ -119,6 +108,60 @@ struct boss_talon_king_ikiss : public BossAI
...
+            DoCastAOE(SPELL_BLINK);
+            Talk(EMOTE_ARCANE_EXP);
+
+            scheduler.Schedule(1s, [this](TaskContext)
+            {
+                DoCastAOE(SPELL_ARCANE_EXPLOSION);
+            }).Schedule(6500ms, [this](TaskContext /*context*/)
+            {
+                me->GetThreatMgr().ResetAllThreat();
+                DoCastSelf(SPELL_ARCANE_BUBBLE, true);
```
Comment (Tereneckla) [inline src/server/scripts/Outland/Auchindoun/SethekkHalls/boss_talon_king_ikiss.cpp:143]: Put this in line 136
Bubble is at the same time as teleport

**Review by Tereneckla — APPROVED** [review]
Don't think I'm the best reviewer for coding style
But it works now

**Review by Nyeriah — APPROVED** [review]
