### PR TITLE
fix(Scripts/ObsidianSanctum): Code revamp [1/2]

### LINKED ISSUE #3633: Sartharion OS10 / 25 Not Pull Dragons
Sartharion OS10 / 25 Not Pull Dragons

SMALL DESCRIPTION:

When you pull sartharion https://www.wowhead.com/npc=28860/sartharion without killing the 3 dragons they should come down and attack, but at no time does.

 EXPECTED BLIZZLIKE BEHAVIOUR:

the dragons must come down to fight

##### STEPS TO REPRODUCE THE PROBLEM:
1.  Go to Sartharion OS 
2.  the battle begins
3.  Slowly come to life at no time the dragons come down. 

BRANCH(ES):
master

AC HASH/COMMIT:
OPERATING SYSTEM:
Ubuntu

MODULES:
None

OTHER CUSTOMIZATIONS:
None

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/94006009-sartharion-os10-25-not-pull-dragons?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sanctum32**
## CHANGES PROPOSED:
- Cleaned up code
- Implemented boss states handling (gms can handle each boss state)
- Fixed exploit which allowed players to enter to dungeon while mini boss is engaged
- Fixed dragons calls and flame waves

## ISSUES ADDRESSED:
- Closes #3633

## TESTS PERFORMED:
- Tested combat encounters with 3D fight and non 3D fight
- Mini boss combat encounters (NO 3D)
- GM command .instance setBossState

## HOW TO TEST THE CHANGES:

- Test combat encounters with mini bosses and Sartharion (3D.
- Do non 3D tests with rotation like: 2 dragons and sartharion, 1 dragon and sartharion.
- Do non 3D tests with no drakes alive

## KNOWN ISSUES AND TODO LIST:

- [x] Sartharion applies [Pyrobuffet/ Spell # 57557] to players within any portal during the encounter, this should happen only out of range of phasemask 1
Maybe at the moment of changing phase, it takes it like "out of range" when players are not in phasemask 1 ? feels an additional check required. This is not used in the script, could be related.:

SPELL_SARTHARION_PYROBUFFET_TRIGGER         = 57557,

- [x] Sartharion's immune [Gift of Twilight / spell # 58766] does not make him immune to certain Melee abilities (example: [Heroic Strike / 47450])
https://db.rising-gods.de/?spell=58766

- [x] When entering Vesperon's portal, to kill his disciple [npc id 31219], which applies [Twilight Torment / spell # 57935] to all players outside, the players inside the portal still have the effect which is incorrect, only players outside should have the debuff.

    Maybe a constant check of phasemask to remove aura while players are in the portal fighting the disciple? idk

- [x] If you try to reset Sartharion by leaving its area while there are [Twilight Whelp / npc id 30890], these npcs do not disappear at the time of resetting the encounter even though there is a

summons.DespawnAll();

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

File: src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp [hunk 1]
```diff
@@ -190,377 +205,415 @@ class boss_sartharion : public CreatureScript
...
+                ++dragonsCount;
+                me->AddLootMode(1 << dragonsCount);
+
+                dragon->SetFullHealth();
+                switch (dragons.at(i))
+                {
+                    case DATA_TENEBRON:
+                    {
+                        dragon->CastSpell(dragon, SPELL_POWER_OF_TENEBRON, true);
+                        extraEvents.ScheduleEvent(EVENT_SARTHARION_CALL_TENEBRON, 10000);
```
Comment (FrancescoBorzi) [inline src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp:273]: shall we wrap numbers such as `10000` into constants?

File: src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp [hunk 2]
```diff
@@ -190,377 +205,415 @@ class boss_sartharion : public CreatureScript
...
+            while (uint32 const eventId = extraEvents.ExecuteEvent())
             {
-                case EVENT_SARTHARION_BOUNDARY:
-                    if (me->GetPositionX() < 3218.86f || me->GetPositionX() > 3275.69f || me->GetPositionY() < 484.68f || me->GetPositionY() > 572.4f) // https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/instance_obsidian_sanctum.cpp#L31
-                        EnterEvadeMode();
+                switch (eventId)
+                {
+                    case EVENT_SARTHARION_BOUNDARY:
+                    {
+                        if (me->GetPositionX() < 3218.86f || me->GetPositionX() > 3275.69f || me->GetPositionY() < 484.68f || me->GetPositionY() > 572.4f) // https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/instance_obsidian_sanctum.cpp#L31
```
Comment (FrancescoBorzi) [inline src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp:375]: what about moving these coordinate numbers into constants?

File: src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp [hunk 3]
```diff
@@ -190,377 +205,415 @@ class boss_sartharion : public CreatureScript
...
-            HandleDrakeAbilities();
+            while (uint32 const eventId = events.ExecuteEvent())
+            {
+                switch (eventId)
+                {
+                    case EVENT_SARTHARION_CAST_CLEAVE:
+                    {
+                        DoCastVictim(SPELL_SARTHARION_CLEAVE, false);
+                        events.RepeatEvent(10000);
+                    }break;
```
Comment (FrancescoBorzi) [inline src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp:453]: why this codestyle? `}break;` ? why not either avoiding braces or keeping the `break` inside the braces? is there any specific reason?

File: src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp [hunk 4]
```diff
@@ -190,377 +205,415 @@ class boss_sartharion : public CreatureScript
...
+                    {
+                        if (!urand(0, 2))
+                            Talk(SAY_SARTHARION_SPECIAL_4);
 
-            DoMeleeAttackIfReady();
-        }
-    };
-};
+                        summons.RemoveNotExisting();
+                        uint8 rand = urand(0, 4); // 5 - numer of cyclones
```
Comment (FrancescoBorzi) [inline src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp:470]: we could use a constant `CYCLONES_COUNT`, have it set to 5 and then use `urand(0, CYCLONES_COUNT - 1)`

File: src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp [hunk 5]
```diff
@@ -190,377 +205,415 @@ class boss_sartharion : public CreatureScript
...
+
+    private:
+        EventMap extraEvents;
+        std::list<uint32> volcanoBlows;
+        uint8 dragonsCount;
+        bool usedBerserk;
+
+        void SummonStartingTriggers()
+        {
+            for (uint8 i = 0; i < 5; ++i)
```
Comment (FrancescoBorzi) [inline src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp:537]: `CYCLONES_COUNT` can then be reused here

File: src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp [hunk 6]
```diff
@@ -190,377 +205,415 @@ class boss_sartharion : public CreatureScript
...
-            if (Creature* vesperon = ObjectAccessor::GetCreature(*me, dragons[DRAGON_VESPERON]))
-                vesperon->AI()->DoAction(ACTION_CALL_DRAGON);
-            
-            break;
-    }
-}
+        void SendLavaWaves(bool start)
+        {
+            if (summons.empty())
+                return;
```
Comment (FrancescoBorzi) [inline src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp:576]: same as above

File: src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp [hunk 7]
```diff
@@ -190,377 +205,415 @@ class boss_sartharion : public CreatureScript
...
+            for (uint64 const guid : summons)
+            {
+                Creature* tsunami = ObjectAccessor::GetCreature(*me, guid);
+                if (!tsunami || tsunami->GetEntry() != NPC_FLAME_TSUNAMI)
+                    continue;
+
+                if (start)
+                    tsunami->GetMotionMaster()->MovePoint(0, ((tsunami->GetPositionX() < 3250.0f) ? 3283.44f : 3208.44f), tsunami->GetPositionY(), tsunami->GetPositionZ());
+                else
+                    tsunami->SetObjectScale(0.1f);
```
Comment (FrancescoBorzi) [inline src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp:587]: same as above

**Review by FrancescoBorzi — COMMENTED** [review]
@sanctum32 I don't have enough time now to look at the whole PR changes. But I've checked the first part and left some comments so you can apply the same strategy to the whole PR :)

File: src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp (hunk 1 above)
Comment (sanctum32) [reply src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp:273]: Thats not necessary i think

File: src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp (hunk 3 above)
Comment (sanctum32) [reply src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp:453]: well, its my codestyle which i used to be sure that i not missed to add break after code block since in huge code block "base operator" can be misswatched. I'm commonly using this in javascript and php. Will correct in next commit

File: src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp (hunk 2 above)
Comment (sanctum32) [reply src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp:375]: its copy/pasted old code

**Comment by sanctum32** [comment]
This pull request is ready for review

**Comment by Si1ker** [comment]
@sanctum32  There are some issues on SO that could be great to sort in order to leave SO finally perfect with this revamp.

1- Sartharion applies [Pyrobuffet/  Spell # 57557] to players within any portal during the encounter, this should happen only out of range of phasemask 1
Maybe at the moment of changing phase, it takes it like "out of range" when players are not in phasemask 1 ? feels an additional check required. This is not used in the script, could be related.:
```cpp
SPELL_SARTHARION_PYROBUFFET_TRIGGER         = 57557,
```


= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
2- Sartharion's immune [Gift of Twilight / spell # 58766] does not make him immune to certain Melee abilities (example: [Heroic Strike / 47450])
https://db.rising-gods.de/?spell=58766


= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
3- When entering Vesperon's portal, to kill his disciple [npc id 31219], which applies [Twilight Torment / spell # 57935] to all players outside, the players inside the portal still have the effect which is incorrect, only players outside should have the debuff.
- There should be a constant check to remove aura while players are in the portal fighting the disciple? is the only idea I could think of..


= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
4- If you try to reset Sartharion by leaving its area while there are [Twilight Whelp / npc id 30890], these npcs do not disappear at the time of resetting the encounter even though there is a
```cpp
summons.DespawnAll();
```


-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
* If you need this on a 'reported issue' first, then let me know. I am adding those here to take the same threat of how awful is SO currently.

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers can anyone please test this?

**Comment by sanctum32** [comment]
ok, i will try to fix these issues

**Comment by FrancescoBorzi** [comment]
thanks for the feedback @Si1ker !

@sanctum32 please let us know when it's ready again to be tested, keep up the good work!

**Comment by sanctum32** [comment]
@Si1ker can you review this once again? i pretty much followed your reports, added some necessary checks for few spells for phase masks

**Comment by Si1ker** [comment]
@sanctum32 what about pyrobuffed? shouldn't it has a condition similar like 
```sql
(17, 0, 57935, 0, 0, 26, 1, 1, 0, 0, 0, 0, 0, '', 'Twilight Torment - Target players which has phase mask 1');
```
in order to hit only in Phase 1? 🤔

**Comment by Si1ker** [comment]
I'll gonna avoid the "enter gm and check", Im gonna have a test this weekend with full raid, will update soon.
Good job ~ 🐱

File: src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp [hunk 8]
```diff
@@ -395,6 +395,10 @@ class boss_sartharion : public CreatureScript
 
         void DamageTaken(Unit* /*attacker*/, uint32& damage, DamageEffectType /*dmgType*/, SpellSchoolMask /*school*/) override
         {
+            // Temporal hack, by some case some melee spells can bypass this aura damage reduction
+            if (me->HasAura(SPELL_GIFT_OF_TWILIGHT_FIRE) || me->HasAura(SPELL_GIFT_OF_TWILIGHT_SHADOW))
+                damage = 0;
```
Comment (FrancescoBorzi) [inline src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp:401]: brackets please

**Comment by Racknar0** [comment]
Good day.

I do not know if it is correct to post this here, but I just applied the pull and when the Tenebron dragon is killed when someone in the group dies, he cannot re-enter and cannot be resurrected
Attached video of evidence.

[https://youtu.be/j5ucQYoaFSs](url)

**Comment by Racknar0** [comment]
Good day.

I do not know if it is correct to post this here, but I just applied the pull and when the Tenebron dragon is killed when someone in the group dies, he cannot re-enter and cannot be resurrected
Attached video of evidence.

https://youtu.be/j5ucQYoaFSs

**Comment by FrancescoBorzi** [comment]
thanks @Racknar0 for your feedback! @sanctum32 please take a look when you are back :)

**Comment by sanctum32** [comment]
Mini bosses, same aš rs mini bosses are supposed to lock dungeon and previous behaviour was just an another exploit

File: data/sql/updates/pending_db_world/rev_1604614793984918900.sql [hunk 9]
```diff
@@ -0,0 +1,16 @@
...
+(13, 7, 57557, 0, 0, 26, 0, 1, 0, 0, 0, 0, 0, '', 'Pyrobuffet - Target players which has phase mask 1');
+
+-- Twilight Torment (57935)
+DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=13 AND `SourceGroup`=7 AND `SourceEntry`=57935 AND `SourceId`=0 AND `ElseGroup`=0 AND `ConditionTypeOrReference`=26 AND `ConditionTarget`=0 AND `ConditionValue1`=1 AND `ConditionValue2`=0 AND `ConditionValue3`=0;
+DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=17 AND `SourceGroup`=0 AND `SourceEntry`=57935 AND `SourceId`=0 AND `ElseGroup`=0 AND `ConditionTypeOrReference`=26 AND `ConditionTarget`=1 AND `ConditionValue1`=1 AND `ConditionValue2`=0 AND `ConditionValue3`=0;
+INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
+(17, 0, 57935, 0, 0, 26, 1, 1, 0, 0, 0, 0, 0, '', 'Twilight Torment - Target players which has phase mask 1');
```
Comment (Kitzunu) [inline data/sql/updates/pending_db_world/rev_1604614793984918900.sql:11]: Is the first delete necessary since you don't insert anything with it?
Also you could combine the two deletes to this 

```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` IN (13,17) AND `SourceGroup` IN (0,7) AND `SourceEntry`=57935 AND `SourceId`=0 AND `ElseGroup`=0 AND `ConditionTypeOrReference`=26 AND `ConditionTarget` IN (0,1) AND `ConditionValue1`=1 AND `ConditionValue2`=0 AND `ConditionValue3`=0;
```

Comment (Racknar0) [reply data/sql/updates/pending_db_world/rev_1604614793984918900.sql:11]: > Mini bosses, same as rs mini bosses are supposed to lock dungeon and previous behaviour was just an another exploit which allowed char dupping during encounter. I made dungeon locking while mini boss is pulled

but even after killing the mini boss and someone dies when he releases and tries to get in, you can't
It is a problem because when it is band 25 many off-raids die since not many can enter.
The curious thing is that the people who killed the miniboss are not left in combat

Psdata: Excuse my English as a translator

https://ibb.co/7zvcRNR

**Comment by Racknar0** [comment]
> Mini bosses, same as rs mini bosses are supposed to lock dungeon and previous behaviour was just an another exploit which allowed char dupping during encounter. I made dungeon locking while mini boss is pulled

but even after killing the mini boss and someone dies when he releases and tries to get in, you can't
It is a problem because when it is band 25 many off-raids die since not many can enter.
The curious thing is that the people who killed the miniboss are not left in combat

Psdata: Excuse my English as a translator

https://ibb.co/7zvcRNR

**Comment by Racknar0** [comment]
when you are in the cobate with sartharion you reach a point of instance, when you go back and return to the initial point there is a time out in which your life is not restored

this lends itself to making the 25j instance among very few people since dragon and mechanical events are not activated

this downtime between the arrival at the starting point and its initial restoration is not healed.

Video: 

[https://youtu.be/ANLCf0ym-w4](url)

**Comment by sanctum32** [comment]
that combat issue actually existed even before my rewrite, what i mean, it was timed boundaries check, but we can make timer wayy shorter to make it more frequant

**Comment by Si1ker** [comment]
Hello @sanctum32 any update on this? 🐱

File: src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp [hunk 10]
```diff
@@ -673,6 +674,17 @@ class boss_sartharion : public CreatureScript
...
+        bool IsTargetInBounds(Unit const* victim) const
+        {
+            if (!victim || victim->GetPositionX() < SartharionBoundary[0] || victim->GetPositionX() > SartharionBoundary[1] || victim->GetPositionY() < SartharionBoundary[2] || victim->GetPositionY() > SartharionBoundary[3])
+            {
+                return false;
+            }
+
+            return true;
+
+        }
```
Comment (Helias) [inline src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp]:
```suggestion
        bool IsTargetInBounds(Unit const* victim) const
        {
            return !(!victim ||
            victim->GetPositionX() < SartharionBoundary[0] ||
            victim->GetPositionX() > SartharionBoundary[1] ||
            victim->GetPositionY() < SartharionBoundary[2] ||
            victim->GetPositionY() > SartharionBoundary[3])
        }
```

Comment (sanctum32) [reply src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp]: in further code i added exception for big island, this code would work for older version  and wont work for that exception but anyways thanks

**Review by Si1ker — APPROVED** [review]
First part of the revamp is ready, issues remaining will be addressed on part [2/2]
