### PR TITLE
fix(DB/Loot): corrects the drop rate of Winterfall Firewater

### LINKED ISSUE #7920: Winterfall Firewater - Incorrect Drop Rates
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1738

Firewater drop rates are half of what they should be (except the High chief) 

image

Tester: checked the above with my own query, confirmed it's accurate. 

### Expected Blizzlike Behaviour

Closer adherence to the known drop rates.

image

### Source

https://tbc.wowhead.com/item=12820/winterfall-firewater

### Steps to reproduce the problem

Query the following:
```SQL
SELECT ct.entry, ct.name, clt.chance
FROM `creature_template` ct
JOIN `creature_loot_template` clt ON ct.lootid = clt.Entry
WHERE clt.Item = 12820
```

### Extra Notes

The rates are consistent in classic and tbc. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by jamadaha**
## Changes Proposed:
-  Sets the drop rate of the Firewater in accordance of the addressed issue.

## Issues Addressed:

- Closes #7920
- Closes https://github.com/chromiecraft/chromiecraft/issues/1738

## Tests Performed:

- Done as below

## How to Test the Changes:

1. Run SQL — Should change 7 rows
2. Check DB/Keira that the drop rate is changed to be in accordance with the addressed issue

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1632235858441614200.sql [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+	`Chance` = 
+	(CASE 
+		WHEN `Entry` = 7438 THEN 7
+		WHEN `Entry` = 7439 THEN 7
+		WHEN `Entry` = 7440 THEN 8
+		WHEN `Entry` = 7441 THEN 8
+		WHEN `Entry` = 7442 THEN 8
+		WHEN `Entry` = 10199 THEN 7
+		WHEN `Entry` = 10916 THEN 6
+	END)
```
Comment (Helias) [inline data/sql/updates/pending_db_world/rev_1632235858441614200.sql:15]: what are the advantages to add this case-when instead of mulitple UPDATE lines?

Comment (jamadaha) [reply data/sql/updates/pending_db_world/rev_1632235858441614200.sql:15]: I don't know whether it is necessarily better, but my understanding is that a single query is easier to optimize for the query optimizer.
