### PR TITLE
fix(Core/Spells): Send proper caster's guid in SMSG_SPELL_START/SMSG_…

### LINKED ISSUE #11275: [BWL] Visual improvements
### Current Behaviour

- There are any lazer blue between the boss and the player that control the orb (only with Grethok before the fight. Not specify in the initial issue from #10832)
- When suppression device cast  suppression aura, there is a fire aura visual

### Expected Blizzlike Behaviour

- The lazer blue between Grethok and Razorgore should be apply if a player take the control of the boss with orb.
- Suppression aura shouldn't have a visual. We should only see the steam effect from the suppression device.

### Source

Razorgore lazer -  https://youtu.be/UJnJw5rBUSo?t=67
Suppression aura - https://youtu.be/t2n3xrwGJts?t=415

### Steps to reproduce the problem

1. Take the control of razorgore with orb
2. Go to the suppression room

### Extra Notes

_No response_

### AC rev. hash/commit

0e5f6ef

### Operating system

Windows 11

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
…SPELL_GO packets in case of spells casted originally by gameobjects.

Added visual channeling when mind controlling Razorgore by player.
Fixes #11275

## Issues Addressed:

- Closes #11275

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

Take the control of razorgore with orb
Go to the suppression room

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_razorgore.cpp [hunk 1]
```diff
@@ -23,48 +23,49 @@
...
+    EMOTE_TROOPS_RETREAT        = 0
 };
 
 enum Spells
 {
-    SPELL_MINDCONTROL       = 19832,
-    SPELL_EGG_DESTROY       = 19873,
-    SPELL_MIND_EXHAUSTION   = 23958,
+    SPELL_MINDCONTROL           = 19832,
+    SPELL_MINDCONTROL_VISUAL    = 45537,
```
Comment (pklloveyou) [inline src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_razorgore.cpp:37]: SPELL_MINDCONTROL_VISUAL    = 23014,

Comment (pklloveyou) [reply src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_razorgore.cpp:37]: Wrong spell 45537, correct should be 23014

Comment (UltraNix) [reply src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_razorgore.cpp:37]: It's the same spell as Grethok casts.

**Review by IntelligentQuantum — APPROVED** [review]
