### PR TITLE
fix(Core/Spells): Fixed Master's Call used on rooted pet.

### LINKED ISSUE #7239: Master's Call not removing Roots if the pet is rooted aswell
### Current Behaviour

Hunter ability Master's Call is not removing freeze effects such as frost nova, entangling roots if both the Hunter and the Pet are frozen. The pet gets out of nova and ''charges'' to the hunter, but does not remove the hunter freeze.

It, however, removes the Hunter freeze effect if only the Hunter is being affected by a root effect.

### Expected Blizzlike Behaviour

Master's Call should always remove Hunter's nova if both the pet and the hunter are affected by Freeze/root spells.

### Source

_No response_

### Steps to reproduce the problem

Step 1. Create a mage and get near a hunter and his pet
Step 2. Cast Frost Nova
Step 3. Use Master's Call

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3067662b70bf

### Operating system

Windows 10 x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixed #7239

## Changes Proposed:
-  Added an exception fro Master's Call - do not check if pet is rooted.

## Issues Addressed:

- Closes #7239

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

1. Create a mage and get near a hunter and his pet
2. Cast Frost Nova
3. Use Master's Call

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by lineagedr** [comment]
What about?

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Spells/spell_hunter.cpp#L715
```c++
else if (pet->isInRoots())
    result = SPELL_FAILED_ROOTED;
```

File: src/server/game/Spells/Spell.cpp [hunk 1]
```diff
@@ -5665,7 +5665,13 @@ SpellCastResult Spell::CheckCast(bool strict)
                             m_caster->RemoveMovementImpairingAuras(true);
                     }
                     if (m_caster->HasUnitState(UNIT_STATE_ROOT))
-                        return SPELL_FAILED_ROOTED;
+                    {
+                        // Exception for Master's Call
+                        if (m_spellInfo->Id != 54216)
```
Comment (Kitzunu) [inline src/server/game/Spells/Spell.cpp:5670]: I'd really appreciate if you turn this into a constexpr or something readable

**Comment by pklloveyou** [comment]
image
No thawing

**Comment by laasker** [comment]
The PR works, now the hunter receives Master's Call if both pet and hunter are rooted.
I also tested if only the pet or hunter are rooted, and all them works fine.

Thanks very much 👍 :-)

**Review by FrancescoBorzi — APPROVED** [review]
