### PR TITLE
fix(DB/SAI): "Attack on the Tower" Quest - Incorrect NPC Spawn Behaviour

### LINKED ISSUE #6944: Arathi Highlands - "Attack on the Tower" Quest - Incorrect NPC Spawn Behaviour
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/1187

Quest [Attack on the Tower ](https://tbc.wowhead.com/quest=696/attack-on-the-tower) missing scripts after open [Trelane's Footlocker](https://tbc.wowhead.com/object=2717/trelanes-footlocker), [Trelane's Chest](https://tbc.wowhead.com/object=2716/trelanes-chest), [Trelane's Lockbox](https://tbc.wowhead.com/object=2718/trelanes-lockbox). Mobs don't attack players.

Tester: Confirmed. The ogre spawns should be rather more aggressive.

https://user-images.githubusercontent.com/81782124/125635784-5a9eefb3-3faf-48f9-ad97-23210aba853c.mp4

also note: Atm these boxes are abusable. You can delete quest item and get loot from boxes again. Confirmed this too, boxes will respawn with a fresh loot table.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mobs should run to the players and attack.

##### SOURCE:

Spawns for:
Trelane's Footlocker (2717) - 16611 - https://www.youtube.com/watch?v=oFdLPHn4w7E&t=731s
Trelane's Lockbox (2718) - 16610 - https://youtu.be/oFdLPHn4w7E?t=951
Trelane's Chest (2716) - 16617 - https://youtu.be/oFdLPHn4w7E?t=2166

##### STEPS TO REPRODUCE THE PROBLEM:

1. .q add 696
2. .go o 16611 - loot and observe
3. .go o 16610 - loot and observe
4. .go o 16617 - loot and observe

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7c21d567d59153b37978756a5bf02daf6998e665

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99900381-arathi-highlands-attack-on-the-tower-quest-incorrect-npc-spawn-behaviour?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Zenslash**
## Changes Proposed:
-  Mobs now run to the player and attack

## Issues Addressed:
- Closes #6944
- Closes chromiecraft/chromiecraft#1187

## SOURCE:
- Trelane's Footlocker (2717) - 16611 - https://www.youtube.com/watch?v=oFdLPHn4w7E&t=731s
- Trelane's Lockbox (2718) - 16610 - https://youtu.be/oFdLPHn4w7E?t=951
- Trelane's Chest (2716) - 16617 - https://youtu.be/oFdLPHn4w7E?t=2166

## Tests Performed:
- Tested on local server

## How to Test the Changes:
1. .q add 696
2. .go o 16611 - loot and observe
3. .go o 16610 - loot and observe
4. .go o 16617 - loot and observe

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1626358725875698500.sql [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+(2569, 0, 2, 0, 54, 0, 100, 0, 0, 0, 0, 0, 0, 49, 100, 0, 0, 0, 0, 0, 21, 30, 0, 0, 0, 0, 0, 0, 0, 'Boulderfist Mauler - Just Summoned - Attack Start');
+
+UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 2570;
+
+DELETE FROM `smart_scripts` WHERE (`entryorguid` = 2570) AND (`source_type` = 0) AND (`id` IN (4));
+INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
+(2570, 0, 4, 0, 54, 0, 100, 0, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, 0, 21, 30, 0, 0, 0, 0, 0, 0, 0, 'Boulderfist Shaman - Just Summoned - Attack Start');
+
```
Comment (Kitzunu) [inline data/sql/updates/pending_db_world/rev_1626358725875698500.sql:14]:
```suggestion
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` IN (2569, 2570);

DELETE FROM `smart_scripts` WHERE (`entryorguid` = 2569) AND (`source_type` = 0) AND (`id` IN (2));
DELETE FROM `smart_scripts` WHERE (`entryorguid` = 2570) AND (`source_type` = 0) AND (`id` IN (4));
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(2569, 0, 2, 0, 54, 0, 100, 0, 0, 0, 0, 0, 0, 49, 100, 0, 0, 0, 0, 0, 21, 30, 0, 0, 0, 0, 0, 0, 0, 'Boulderfist Mauler - Just Summoned - Attack Start'),
(2570, 0, 4, 0, 54, 0, 100, 0, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, 0, 21, 30, 0, 0, 0, 0, 0, 0, 0, 'Boulderfist Shaman - Just Summoned - Attack Start');
```

**Review by LukasVolgger — APPROVED** [review]

**Comment by Asthalor** [comment]
TEST

When i opicked the item the ogres jumped on me, so OK

(Videos  were too big, so i uploaded them to streamable)
https://streamable.com/zk5an5

Same when opening the second box

https://streamable.com/gx60l3

Same when opening the last box

https://streamable.com/fmn8u6

ALL GOOD!

**Comment by LukasVolgger** [comment]
Thx @Zenslash for the fix and @Asthalor for testing!
