### PR TITLE
fix(Core/Spells): Implement Honor Among Thieves spell scripts

### LINKED ISSUE #9058: Honor Among Thieves not giving Combo Points
### Current Behaviour

It seems the Honor Among Thieves talent in the Subtlety talent tree is not working as intended.  When an ally in the party with the rogue scores a critical hit and the rogue with Honor Among Thieves talent that is maxed out 3/3 is targeting a legal target for generating combo points, no combo points are being given.

I have also seen on occasion that even when the rogue scores a critical hit with an ability that the extra combo point is not generated on the target.

### Expected Behaviour

Typically.  When a rogue with Honor Among Thieves talent is maxed out 3/3, we should be able to generate a combo point on our target that is a legal target for generate combo points whenever anyone in the party scores a crit with a spell or ability, once per second.  This should include the rogue's critical strikes with abilities, still only activating once per second.

### Source

It is very difficult for me to show that my ally is critting while I am targeting.  I appologize.

### Steps to reproduce the problem

1. Have a Rogue be high enough level to have 3/3 in Honor Among Thieves Talent
2. Have another player in your party.
3. Have the Rogue target an eligible target that has the potential to generate combo points against.
4. Have the other player in your party use spells or abilities on the target or nearby targets until they get a crit.
5. Rogue will not generate a combo point from Honor Among Thieves Talent.

### Extra Notes

_No response_

### Customizations

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/686aafd57be6f1594a99634bade3756643fbf6f3

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-chromiecraft-smartstone](https://github.com/chromiecraft/mod-chromiecraft-smartstone)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-evade-logging](https://github.com/heyitsbench/mod-evade-logging)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-quests](https://github.com/azerothcore/mod-pvp-quests)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by blinkysc**
## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

### Description

Port TrinityCore's 3-class approach for Honor Among Thieves (51698/51700/51701):

- **`spell_rog_honor_among_thieves`** (AuraScript for 51698/51700/51701): Handles the talent area aura proc. `CheckProc` enforces the 1-second ICD by checking for the 51699 aura on the rogue. `HandleProc` uses `PreventDefaultAction()` and manually triggers spell 52916 with the rogue's GUID as the original caster, ensuring the combo point is routed back to the correct player.
- **`spell_rog_honor_among_thieves_proc`** (SpellScript for 52916): `FilterTargets` clears the default area party targets and redirects the spell to only hit `GetOriginalCaster()` (the rogue who owns the talent).
- **`spell_rog_honor_among_thieves_proc_aura`** (AuraScript for 52916): On aura apply, the rogue casts 51699 (Add Combo Point) on their current target.

Additionally:
- **Removed** the old `SpellInfoCorrection` hack that replaced TriggerSpell from 52916 to 51699, which bypassed the intermediate spell entirely and broke the targeting chain.
- **Added** `SPELL_ATTR3_DOT_STACKING_RULE` to 51698/51700/51701 so that area auras from different rogues with Honor Among Thieves can coexist on the same party member (the `CanStackWith` check in `UpdateTargetMap` otherwise blocks same-rank area auras from different casters).
- **Added** `spell_script_names` DB entries for 51698/51700/51701/52916.

### AI-assisted Pull Requests

> [!IMPORTANT]
> While the use of AI tools when preparing pull requests is not prohibited, contributors must clearly disclose when such tools have been used and specify the model involved.
> 
> Contributors are also expected to fully understand the changes they are submitting and must be able to explain and justify those changes when requested by maintainers.

- [x] AI tools (e.g. ChatGPT, Claude, or similar) were used entirely or partially in preparing this pull request. Claude Code with azerothMCP were used.

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/9058

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [x] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

TrinityCore commit: https://github.com/TrinityCore/TrinityCore/commit/7672ca194552704eacf0fa49c7c28e91ade64399

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [x] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [x] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Create two characters in a party (at least one must be a Rogue with Honor Among Thieves rank 3).
2. Have the non-rogue (or second rogue) critically hit a target with a spell or ability.
3. Verify the rogue with HoAT gains a combo point on their current target.
4. For multi-rogue testing: both rogues should have HoAT, verify each rogue gains combo points from the other's crits.
5. Verify the 1-second ICD is respected (rapid crits should not grant more than 1 CP per second).

## Known Issues and TODO List:

- [ ] Melee auto-attack crits do not proc HoAT (matches DBC ProcFlags which exclude `PROC_FLAG_DONE_MELEE_AUTO_ATTACK` — needs verification against retail behavior)

### CODE REVIEW

File: src/server/scripts/Spells/spell_rogue.cpp [hunk 1]
```diff
@@ -932,6 +934,91 @@ class spell_rog_setup : public AuraScript
...
+class spell_rog_honor_among_thieves : public AuraScript
+{
+    PrepareAuraScript(spell_rog_honor_among_thieves);
+
+    bool Validate(SpellInfo const* spellInfo) override
+    {
+        return ValidateSpellInfo(
+        {
+            SPELL_ROGUE_HONOR_AMONG_THIEVES_TRIGGERED,
+            spellInfo->Effects[EFFECT_0].TriggerSpell
```
Comment (Nyeriah) [inline src/server/scripts/Spells/spell_rogue.cpp]: Not necessary if its part of the own spell info

**Review by Nyeriah — APPROVED** [review]
