### PR TITLE
fix(Core/GameEvents): Added new game event: Darkmoon Faire Building (…

### LINKED ISSUE #9592: Darkmoon Faire is missing Darkmoon Faire Building (Terrokar Forest) event
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Darkmoon Faire is missing `Darkmoon Faire Building (Terrokar Forest)`

| eventEntry | occurence | length | holiday | description | 
| ---: | ---: | ---: | ---: | --- | 
| 3 | 131040 | 10079 | 376 | Darkmoon Faire (Terokkar Forest) | 
| 4 | 131040 | 10079 | 374 | Darkmoon Faire (Elwynn Forest) | 
| 5 | 131040 | 10079 | 375 | Darkmoon Faire (Mulgore) | 
| 23 | 131040 | 4320 | 374 | Darkmoon Faire Building (Elwynn Forest) | 
| 71 | 131040 | 8639 | 0 | Darkmoon Faire Building (Mulgore) | 

### Expected Blizzlike Behaviour

Probably there is should be bulding event like for Elwynn or Mulgore

### Source

X

### Steps to reproduce the problem

```sql
SELECT ge.eventEntry, ge.occurence, ge.length, ge.holiday, ge.description
FROM `game_event` ge
WHERE description LIKE '%darkmoon%'
```

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…Terokkar Forest). Source: TrinityCore.

Fixes #9592

## Issues Addressed:

- Closes #9592

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.go creature 2000000`
`.event start 77`

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1639254662548269400.sql [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+
+UPDATE `game_event` SET `holiday`=375, `length`=4320, `holidayStage`=1 WHERE `eventEntry`=71;
+
+DELETE FROM `game_event` WHERE `eventEntry`=77;
+INSERT INTO `game_event` VALUES
+(77,'2016-11-06 02:01:00','2030-12-31 07:00:00',131040,4320,376,1,'Darkmoon Faire Building (Terokkar Forest)',0,2);
+
+DELETE FROM `creature` WHERE `guid` IN (2000000,2000001,2000002,2000003,2000004,2000005,2000006,2000007);
+INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`) VALUES
+(2000000, 14849, 530, 1, 1, 0, 1, -2250.29, 5245.24, -9.85045, 5.03122, 300, 0, 0, 699, 0, 0),
```
Comment (Kitzunu) [inline data/sql/updates/pending_db_world/rev_1639254662548269400.sql:11]: these GUID's are high af. Please make them lower.

Comment (UltraNix) [reply data/sql/updates/pending_db_world/rev_1639254662548269400.sql:11]: I don't want to use lower guids, because these might be used by other TC cherry picks.

Comment (Kitzunu) [reply data/sql/updates/pending_db_world/rev_1639254662548269400.sql:11]: Use the guids TC are using?

Comment (UltraNix) [reply data/sql/updates/pending_db_world/rev_1639254662548269400.sql:11]: Already used in our DB. That's why I want to prevent from conflicts.

Comment (Kitzunu) [reply data/sql/updates/pending_db_world/rev_1639254662548269400.sql:11]: Also it doesnt matter if other have higher GUIDs, we shouldn't ever need to reach these guid's

Comment (UltraNix) [reply data/sql/updates/pending_db_world/rev_1639254662548269400.sql:11]: I used guids that I'm sure TC will never use (because the same reason as you do), so it is safe to use them to prevent DB guids conficts. It's a rare situation. The guids used by TC are already in use in our DB - now we have confict. If I use something different (lower) guids, in future again might be some conflicts. And recently we are cherry-picking commits from TC very frequently.

**Comment by Nyeriah** [comment]
About guids: it's probably better if we assign our own guids and don't aim to follow tc ones in cherry-picks. We will end up running into conflicts regardless and too high guids are bound to cause us problems in the future

**Comment by acidmanifesto** [comment]
Creature_addon is missing visibilityDistanceType collumn from past merge PR: https://github.com/azerothcore/azerothcore-wotlk/pull/9180/files

File: data/sql/updates/pending_db_world/rev_1639254662548269400.sql [hunk 2]
```diff
@@ -0,0 +1,132 @@
...
+(2000001, 14849, 530, 1, 1, 0, 1, -2257.19, 5234.82, -9.89205, 0.06712, 300, 0, 0, 699, 0, 0),
+(2000002, 14849, 530, 1, 1, 0, 1, -2258.29, 5215.98, -9.90446, 1.4558, 300, 0, 0, 699, 0, 0),
+(2000003, 14849, 530, 1, 1, 0, 1, -2247.18, 5219.25, -9.90328, 1.04846, 300, 0, 0, 699, 0, 0),
+(2000004, 14849, 530, 1, 1, 0, 1, -2273.24, 5210.8, -9.89171, 2.57128, 300, 0, 0, 699, 0, 0),
+(2000005, 14849, 530, 1, 1, 0, 1, -2264.64, 5202.15, -9.9045, 3.226, 300, 0, 0, 699, 0, 0),
+(2000006, 14849, 530, 1, 1, 0, 1, -2233.39, 5223.75, -9.91236, 2.31678, 300, 0, 0, 699, 0, 0),
+(2000007, 14849, 530, 1, 1, 0, 1, -2281.47, 5212.95, -9.86383, 5.90235, 300, 0, 0, 699, 0, 0);
+
+DELETE FROM `creature_addon` WHERE guid IN (2000000,2000001,2000002,2000003,2000004,2000005,2000006,2000007);
+INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
```
Comment (acidmanifesto) [inline data/sql/updates/pending_db_world/rev_1639254662548269400.sql:21]:
```
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `visibilityDistanceType`, `auras`) VALUES 
(2000000, 0, 0, 0, 4097, 69, 3, ""),
(2000001, 0, 0, 0, 4097, 234, 3, ""),
(2000002, 0, 0, 0, 4097, 234, 3, ""),
(2000003, 0, 0, 0, 4097, 234, 3, ""),
(2000004, 0, 0, 0, 4097, 234, 3, ""),
(2000005, 0, 0, 0, 4097, 234, 3, ""),
(2000006, 0, 0, 0, 4097, 69, 3, ""),
(2000007, 0, 0, 0, 4097, 69, 3, "");
```

**Review by acidmanifesto — CHANGES_REQUESTED** [review]

File: data/sql/updates/pending_db_world/rev_1639254662548269400.sql (hunk 2 above)
Comment (UltraNix) [reply data/sql/updates/pending_db_world/rev_1639254662548269400.sql:21]: Fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/9658

**Review by acidmanifesto — APPROVED** [review]
