### PR TITLE
Core/PetAI: Fix aggro and movement IMP Warlock

### LINKED ISSUE #2242: warlock imp bug
warlock imp bug

##### SMALL DESCRIPTION:
When you send the IMP out without the active fireball, it goes around the target

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When you send the IMP out without the active fireball, should not take any action

##### CURRENT BEHAVIOUR:
When you send the IMP out without the active fireball, it goes around the target

##### STEPS TO REPRODUCE THE PROBLEM:
1. Crete a warlock 
2.  Summon imp pet
3.  send it to atack

##### EXTRA NOTES:
AzerothCore rev. a35725712e04+ 2019-08-02 09:05:33 +0000 

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
51e54da6379f42eef504531a298e654278527311

##### OPERATING SYSTEM:
Windows 10 64bit

##### MODULES:
anticheat

##### OTHER CUSTOMIZATIONS:

sorry about my english

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/79462009-warlock-imp-bug?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Nightprince**
Closes #2242

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
### How to test:

- Make sure this bug has been fixed: https://github.com/azerothcore/azerothcore-wotlk/issues/2242
- Make sure no collateral effects have been introduced (by testing other pets, melee and non-melee)

**Comment by Stoabrogga** [comment]
Tested and it's not working well. With this PR the imp will not attack anymore if you command it to, only if you stand in range of the autocast firebolt. But if commanded to attack from a greater distance it should run in range of the enemy and cast firebolt.

**Comment by LichKing255** [comment]
> Tested and it's not working well. With this PR the imp will not attack anymore if you command it to, only if you stand in range of the autocast firebolt. But if commanded to attack from a greater distance it should run in range of the enemy and cast firebolt.

Confirm. But better than the previous one.

**Comment by Stoabrogga** [comment]
Sorry, but it is not better to fix a previous issue and introduce a new one.

**Comment by Stoabrogga** [comment]
@Nightprince @LichKing255 
I'll go through the patch file you originally posted on the issue, try to understand what is changed there, adapt it to AC, test it and create a new PR, but I need a few days for this.

**Comment by LichKing255** [comment]
> Tested and it's not working well. With this PR the imp will not attack anymore if you command it to, only if you stand in range of the autocast firebolt. But if commanded to attack from a greater distance it should run in range of the enemy and cast firebolt.

check with this :

bool PetAI::_canMeleeAttack() const
{
    return (me->GetEntry() != 416 /*ENTRY_IMP*/ &&
        me->GetEntry() != 510 /*ENTRY_WATER_ELEMENTAL*/ &&
        me->GetEntry() != 37994 /*ENTRY_WATER_ELEMENTAL_PERM*/) || me->GetPetAutoSpellSize() > 0;    
}

**Comment by Nightprince** [comment]
> > Tested and it's not working well. With this PR the imp will not attack anymore if you command it to, only if you stand in range of the autocast firebolt. But if commanded to attack from a greater distance it should run in range of the enemy and cast firebolt.
> 
> @Nightprince send this, check with :
> 
> bool PetAI::_canMeleeAttack() const
> {
> return (me->GetEntry() != 416 /_ENTRY_IMP_/ &&
> me->GetEntry() != 510 /_ENTRY_WATER_ELEMENTAL_/ &&
> me->GetEntry() != 37994 /_ENTRY_WATER_ELEMENTAL_PERM_/) || me->GetPetAutoSpellSize() > 0;
> }

but i think this better working, @Stoabrogga check this:

```
bool PetAI::_canMeleeAttack() const
{
    bool canAttack = true;
    switch (me->GetEntry())
    {
        case 416:
        case 510:
        case 37994:
        {
            canAttack = false;
            for (uint8 i = 0; i < me->GetPetAutoSpellSize(); ++i)
            {
                uint32 spellID = me->GetPetAutoSpellOnPos(i);
                if (spellID && ((me->GetEntry() == 416 && (spellID == 3110 || spellID != 7799 || spellID != 7800 || spellID != 7801 || spellID != 7802 ||
                    spellID != 11762 || spellID != 11763 || spellID != 27267 || spellID != 47964)) || (me->GetEntry() == 510 && spellID == 31707) ||
                    (me->GetEntry() == 37994 && spellID == 72898)))
                    canAttack = true;
            }
            break;
        }
        default:
            break;
    }

    return canAttack;
}
```

**Comment by Nightprince** [comment]
> Tested and it's not working well. With this PR the imp will not attack anymore if you command it to, only if you stand in range of the autocast firebolt. But if commanded to attack from a greater distance it should run in range of the enemy and cast firebolt.

@Stoabrogga again check please.

**Comment by Stoabrogga** [comment]
@Nightprince 
It is much worse now: If the Firebolt autocast is disabled the Imp will now enter melee combat with the victim and starts normal attacks. Also Hunter pets will now not enter melee combat anymore, they just wait at a distance until the enemy comes to them.

Like I wrote above, please let me analyze the patch you provided and check if the TC version can be adapted to AC without too much impact.

**Comment by Nightprince** [comment]
> @Nightprince
> It is much worse now: If the Firebolt autocast is disabled the Imp will now enter melee combat with the victim and starts normal attacks. Also Hunter pets will now not enter melee combat anymore, they just wait at a distance until the enemy comes to them.
> 
> Like I wrote above, please let me analyze the patch you provided and check if the TC version can be adapted to AC without too much impact.

I don't agree with your words if disabled go to melee combat.
IMP just stay and see .
Video:

https://mega.nz/#!i58FXaBC!fYgmASrL3eXR1eU0zH1JfDvJFOP6SrazQKHUfjavQzQ

and for hunters and other pet recheck again.

**Comment by LichKing255** [comment]
It works successfully

**Comment by Stoabrogga** [comment]
I pushed a commit in order to use an enum for the spell/entry numbers (please always try to avoid magic numbers and use enum instead). Also did some testing and it looks good so far:

**Without PR:**
- Imp / Water Elemental / Permanent Water Elemental:
  - aggressive, Firebolt/Waterbolt on autocast: Casts spell if in range
  - aggressive, Firebolt/Waterbolt not on autocast: Runs to enemies if in range, moves around in 20 yards distance
  - defensive, Firebolt/Waterbolt on autocast: If the player attacks an enemy, casts spell
  - defensive, Firebolt/Waterbolt not on autocast: If the player attacks an enemy, moves around in 20 yards distance
  - passive, Firebolt/Waterbolt on autocast, command attack: Runs to the enemy and casts spell
  - passive, Firebolt/Waterbolt not on autocast, command attack: Runs to the enemy and moves around in 20 yards distance

- Hunter pet:
  - aggressive: Attacks automatically if enemies are in range, goes into melee
  - defensive: Attack only if the player attacks an enemy, goes into melee
  - passive: Attack only if the player commands, goes into melee


**With PR:**
- Imp / Water Elemental / Permanent Water Elemental:
  - aggressive, Firebolt/Waterbolt on autocast: Casts spell if in range
  - aggressive, Firebolt/Waterbolt not on autocast: Stays with the player and does nothing
  - defensive, Firebolt/Waterbolt on autocast: If the player attacks an enemy, casts spell
  - defensive, Firebolt/Waterbolt not on autocast: If the player attacks an enemy, stays with the player and does nothing
  - passive, Firebolt/Waterbolt on autocast, command attack: Runs to the enemy and casts spell
  - passive, Firebolt/Waterbolt not on autocast, command attack: stays with the player and does nothing

- Hunter pet:
  - aggressive: Attacks automatically if enemies are in range, goes into melee
  - defensive: Attack only if the player attacks an enemy, goes into melee
  - passive: Attack only if the player commands, goes into melee

File: src/server/game/AI/CoreAI/PetAI.cpp [hunk 1]
```diff
@@ -89,9 +89,43 @@ void PetAI::_doMeleeAttack()
...
+                    case IMP_FIREBOLT_RANK_4:
+                    case IMP_FIREBOLT_RANK_5:
+                    case IMP_FIREBOLT_RANK_6:
+                    case IMP_FIREBOLT_RANK_7:
+                    case IMP_FIREBOLT_RANK_8:
+                    case IMP_FIREBOLT_RANK_9:
+                    case WATER_ELEMENTAL_WATERBOLT_1:
+                    case WATER_ELEMENTAL_WATERBOLT_2:
+                        canAttack = true;
+                        break;
```
Comment (FrancescoBorzi) [inline src/server/game/AI/CoreAI/PetAI.cpp]: why don't we just `return true;` here?

Comment (LichKing255) [reply src/server/game/AI/CoreAI/PetAI.cpp]: Because you don't need to change it from true to false.

Comment (Nightprince) [reply src/server/game/AI/CoreAI/PetAI.cpp]: When creatures equal entries IMP or water elemental default change to false and when equal true auto spell size pet>0
When again pet want to attack , this again check and if auto spells change to disable (default is false) when check spells, auto spell = 0 and can't attack.

Comment (Nightprince) [reply src/server/game/AI/CoreAI/PetAI.cpp]: I'm sorry my English is poor.

Comment (FrancescoBorzi) [reply src/server/game/AI/CoreAI/PetAI.cpp]: yes, but inside the `for` loop I don't see any other assignment to `canAttack` other than `true` on line 116

Comment (Nightprince) [reply src/server/game/AI/CoreAI/PetAI.cpp]: You mean to delete the variable?

Comment (Nightprince) [reply src/server/game/AI/CoreAI/PetAI.cpp]: You mean to delete variable?

Comment (FrancescoBorzi) [reply src/server/game/AI/CoreAI/PetAI.cpp]: @Nightprince yes, and replace line 116 with `return true;` and line 128 with `return false;`.

It should work, shouldn't it? and it would be more efficient

Comment (Nightprince) [reply src/server/game/AI/CoreAI/PetAI.cpp]: > @Nightprince yes, and replace line 116 with `return true;` and line 128 with `return false;`.
> 
> It should work, shouldn't it? and it would be more efficient

finish.

Comment (Nightprince) [reply src/server/game/AI/CoreAI/PetAI.cpp]: > @Nightprince yes, and replace line 116 with `return true;` and line 128 with `return false;`.
> 
> It should work, shouldn't it? and it would be more efficient

Thank you for your accuracy

File: src/server/game/AI/CoreAI/PetAI.cpp [hunk 2]
```diff
@@ -113,19 +111,20 @@ bool PetAI::_canMeleeAttack() const
...
             }
+            return false;
             break;
         }
         default:
             break;
     }
 
-    return canAttack;
+    return true;
```
Comment (FrancescoBorzi) [inline src/server/game/AI/CoreAI/PetAI.cpp]: this should be false...

Comment (Stoabrogga) [reply src/server/game/AI/CoreAI/PetAI.cpp]: No, this is correct, the default is "true". The function should only return false if either the Imp or the Water Elemental is used and autocast for the appropriate combat spell (Firebolt / Waterbolt) is disabled. Those two pets are special as they must not use melee attacks if autocast for their combat spells is disabled.

Comment (FrancescoBorzi) [reply src/server/game/AI/CoreAI/PetAI.cpp]: oh ok, my bad. I confused with line 120.

**Comment by Stoabrogga** [comment]
@Nightprince 
While retesting this I found a bug: If the Imp is OOM it runs to the enemy and starts normal attacks. Could you please look into this?

**Comment by Nightprince** [comment]
> @Nightprince
> While retesting this I found a bug: If the Imp is OOM it runs to the enemy and starts normal attacks. Could you please look into this?

what is "OOM" ?

**Comment by Stoabrogga** [comment]
Out Of Mana

**Comment by Helias** [comment]
I tested this PR with warlock and imp:
- aggressive, Firebolt/Waterbolt on autocast: Casts spell if in range
- aggressive, Firebolt/Waterbolt not on autocast: Stays with the player and does nothing
- defensive, Firebolt/Waterbolt on autocast: If the player attacks an enemy, casts spell
- defensive, Firebolt/Waterbolt not on autocast: If the player attacks an enemy, stays with the player and does nothing
- passive, Firebolt/Waterbolt on autocast, command attack: Runs to the enemy and casts spell
- passive, Firebolt/Waterbolt not on autocast, command attack: stays with the player and does nothing

**Comment by Nightprince** [comment]
> Out Of Mana

For happy you , plz test this , if work tell me to commit it:

```
bool PetAI::_canMeleeAttack() const
{
    switch (me->GetEntry())
    {
        case ENTRY_IMP:
        case ENTRY_WATER_ELEMENTAL:
        case ENTRY_WATER_ELEMENTAL_PERM:
        {
            for (uint8 i = 0; i < me->GetPetAutoSpellSize(); ++i)
            {
                uint32 spellID = me->GetPetAutoSpellOnPos(i);
                switch (spellID)
                {
                    case IMP_FIREBOLT_RANK_1:
                    case IMP_FIREBOLT_RANK_2:
                    case IMP_FIREBOLT_RANK_3:
                    case IMP_FIREBOLT_RANK_4:
                    case IMP_FIREBOLT_RANK_5:
                    case IMP_FIREBOLT_RANK_6:
                    case IMP_FIREBOLT_RANK_7:
                    case IMP_FIREBOLT_RANK_8:
                    case IMP_FIREBOLT_RANK_9:
                    case WATER_ELEMENTAL_WATERBOLT_1:
                    case WATER_ELEMENTAL_WATERBOLT_2:
                    {
                        SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spellID);
                        int32 mana = me->GetPower(POWER_MANA);

                        if (mana >= spellInfo->CalcPowerCost(me, spellInfo->GetSchoolMask()))
                            return true;
                    }
                    default:
                        break;
                }
            }
            return false;
        }
        default:
            break;
    }

    return true;
}
```

**Comment by Stoabrogga** [comment]
Tested your suggestion and although the Imp is not using normal attacks anymore when it's out of mana it is still running to the enemy, so not quite solved yet in my opinion. It should stay near the player until it has enough mana for the next cast.

**Comment by Nightprince** [comment]
> Tested your suggestion and although the Imp is not using normal attacks anymore when it's out of mana it is still running to the enemy, so not quite solved yet in my opinion. It should stay near the player until it has enough mana for the next cast.

@Stoabrogga i don't know what you say. You say for example if target have many hp and pet just can attack 1 spell fire and with this cast target not die , pet must stay near player ?

Do you have video blizzlike this ?

**Comment by Stoabrogga** [comment]
No, I don't have a video (perhaps @LichKing255 has one). In fact, I don't care about the original issue at all, just wanted to provide help by testing this (which I slowly regret). But it looks wrong to me if the Imp runs close to the enemy, it should always either stay at a distance or by the player.

Here's a small description about the Imp and autocast Firebolt:
https://wow.gamepedia.com/Imp_(warlock_minion)#Imp_tips
*"A common mistake some warlocks make is to tell their Imp to attack when Firebolt isn't set to auto-cast. Since Firebolt is the Imp's only attack form, this gives it nothing to do; right-click on the Firebolt button to fix it. An Imp will also not attack if it is out of energy; it will also refuse to attack mobs that are immune to fire."*

**Comment by Nightprince** [comment]
> No, I don't have a video (perhaps @LichKing255 has one). In fact, I don't care about the original issue at all, just wanted to provide help by testing this (which I slowly regret). But it looks wrong to me if the Imp runs close to the enemy, it should always either stay at a distance or by the player.
> 
> Here's a small description about the Imp and autocast Firebolt:
> https://wow.gamepedia.com/Imp_(warlock_minion)#Imp_tips
> _"A common mistake some warlocks make is to tell their Imp to attack when Firebolt isn't set to auto-cast. Since Firebolt is the Imp's only attack form, this gives it nothing to do; right-click on the Firebolt button to fix it. An Imp will also not attack if it is out of energy; it will also refuse to attack mobs that are immune to fire."_

Now know what you say , but now what good suggestion do you have for this issue?

**Comment by pklloveyou** [comment]
Anyway, it's a lot better than before RP, isn't it?

**Comment by Nightprince** [comment]
> Anyway, it's a lot better than before RP, isn't it?

yes

**Comment by pklloveyou** [comment]
My project has merged with this RP ：）

**Comment by Stoabrogga** [comment]
I tried yesterday to fix this final issue, but sadly to no avail. But you're right, it's much better already.

@Nightprince 
Could you please add your suggestion about the mana calculation to the PR? I'll then test the whole of this one last time later.

**Comment by pklloveyou** [comment]
Calculating Mana may be a good solution for the moment.

**Comment by Nightprince** [comment]
There are 2 solutions:

1. Pet if doesn't have enough mana for next cast spell don't move (doesn't look right because the player might kill the target himself)
2. If mana runs out, go back to near player.

**Comment by pklloveyou** [comment]
Let me try.

**Comment by pklloveyou** [comment]
image
No force value after it will run to the target, so right?

**Comment by Nightprince** [comment]
@Stoabrogga can send pm in discord for me ? user : Nightprince#3343

**Comment by Nightprince** [comment]
@Stoabrogga @pklloveyou recheck plz.

**Comment by pklloveyou** [comment]
All right.，NICE
image

**Comment by LichKing255** [comment]
Good working. This better working than TC. You are good developer @Nightprince

**Comment by Stoabrogga** [comment]
Successfully tested everything I mentioned in this comment:
https://github.com/azerothcore/azerothcore-wotlk/pull/2379#issuecomment-546639782

Additionally tested the Imp without mana and it works really well now. Could not test the Water Elemental as I was not able to drain it's mana. Nevertheless, good work @Nightprince and thanks for testing @LichKing255 @pklloveyou.

@diluh 
Sorry, but I have no idea what you're talking about.
