### PR TITLE
fix(DB/gameobject): Band-aid fix for Malygos platform

### LINKED ISSUE #1948: [Item in Dungeon] If use Saronite Bomb in Malygos  the platform is destroy - Video
If use Saronite Bomb in Malygos the platform is destroy

Item: Saronite Bomb
https://www.wowhead.com/item=41119
Where:
Eye of Eternity - Malygos Raid 10/25

Possible gameobject related entry 193958 and 193960 
"The Focusing Iris"
tipe 10 GAMEOBJECT_TYPE_GOOBER
data0: open (LockId from Lock.dbc)
data2: eventID (event_script id)
data3: Time in ms before the initial state is restored
ScriptName: go_the_focusing_iris

STEPS TO REPRODUCE THE PROBLEM:
CHeck video

Test in last master
with and without modules
Ubuntu 16.04

Video
https://www.youtube.com/watch?v=1n7MmaWs2O8

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/75139981-item-in-dungeon-if-use-saronite-bomb-in-malygos-the-platform-is-destroy-video?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by zabustak**
Co-authored-by: Andrei-UPB Andrei-UPB@users.noreply.github.com
Co-authored-by: GMKyle GMKyle@users.noreply.github.com

Nexus Raid Platform no longer collapses on the first Saronite Bomb use

CHANGES PROPOSED:
Modify Nexus Raid Platform's health from 100 to 6.000.000, thus making it way harder to break

ISSUES ADDRESSED:
Closes #1948

TESTS PERFORMED:
Tested, the platform now breaks upon taking 6.000.000 damage ( an unreachable ammount by normal standards) rather than on 100 damage.

A saronite bomb does 150 siege damage, 25 players using Saronite Bombs on cooldown and considering 11 saronite bombs can be used before Malygos enters berserk mode (10 min), the maximum damage that will be dealt to the platform will be 41.250, if we add in Global Thermal Sapper Charges -250 siege damage per use, it will still take an unimaginable amount of pulls to actually break the platform if the platform does not recover hp between pulls (not tested yet, i'll keep working on it).
The fix is not perfect and is a band-aid solution , I will probably return with the proper one once I figure a way to make the platform immune to siege damage caused by bombs, Global Thermal Sapper Charge and the likes.

HOW TO TEST THE CHANGES:
Enter the Eye of Eternity on 10 or 25 man modes.
`.tele nexus` or `.go creature id 28859` with `.gm fly on` enabled (you might fall to your death otherwise)
`.learn 61766` - Saronite Bomb or `.learn 56488` Global Thermal Sapper Charge
Use the learned spell on the platform, notice that it does take damage but no longer breaks due to the way higher HP threshold.

KNOWN ISSUES AND TODO LIST:
  Make the platform unable to be broken by players accidentally in the first place.

Thanks to @Andei-UPB

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1560396171418694700.sql [hunk 1]
```diff
@@ -0,0 +1,4 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1560396171418694700');
+
+-- Nexus Raid Platform has a lot more hp in order not to break in case any siege damage is taken, initial value was 100
+UPDATE `gameobject_template_addon` SET `Data0`='6000000' WHERE  `entry`=193070;
```
Comment (poszer) [inline data/sql/updates/pending_db_world/rev_1560396171418694700.sql]: Maybe like this?
```suggestion
UPDATE `gameobject_template` SET `Data0`='6000000' WHERE `entry`=193070;
```

Comment (zabustak) [reply data/sql/updates/pending_db_world/rev_1560396171418694700.sql]: I'm sorry for that, I'm tired now I've changed and it's okay now

**Comment by GMKyle** [comment]
lol @poszer this should be close :P 
just read the comments https://github.com/azerothcore/azerothcore-wotlk/pull/2072

**Comment by Stoabrogga** [comment]
I'm really confused now, there are 3 PRs open for this issue: #1964, #2072, and this one, #2085. Which PR is the correct one?

**Comment by GMKyle** [comment]
@Stoabrogga ALL PRs "fix" some issue in his particular own way, it's a long history.

Little summary
PR https://github.com/azerothcore/azerothcore-wotlk/pull/1964
@Andrei-UPB propose platform life increase and change faction to 35

PR https://github.com/azerothcore/azerothcore-wotlk/pull/2072
@Vaex propose disable saronite spell 

this one https://github.com/azerothcore/azerothcore-wotlk/pull/2085
@zabustak propose platform life increase.

Please check https://github.com/azerothcore/azerothcore-wotlk/pull/2072 comments and my conclusions about this topic https://github.com/azerothcore/azerothcore-wotlk/pull/2072#issuecomment-510586094
wich is the correct? https://github.com/azerothcore/azerothcore-wotlk/pull/1964 it's more close to the light :) ,adding the faction change of Argent Coliseum Floor something like this:
```SQL
UPDATE `gameobject_template_addon` SET `faction`='35' WHERE  `entry` IN (193070,195527); -- Nexus Raid Platform and Argent Coliseum Floor change faction to 35(friendly to all) from 0
UPDATE `gameobject_template` SET `Data0`='10000000' WHERE  `entry`=193070; -- Nexus Raid Platform has a lot more hp in order not to break in case any siege damage is taken, initial value was 100. (double safety)
```
Life increase it's not needed, but Argent Coliseum Floor(195527) has a big hp (10000000) to, so if any player has success damaging any platform they won't break so easily.

File: data/sql/updates/pending_db_world/rev_1560396171418694700.sql [hunk 2]
```diff
@@ -0,0 +1,4 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1560396171418694700');
+
+-- Nexus Raid Platform has a lot more hp in order not to break in case any siege damage is taken, initial value was 100
+UPDATE `gameobject_template` SET `Data0`='6000000' WHERE  `entry`=193070;
```
Comment (Stoabrogga) [inline data/sql/updates/pending_db_world/rev_1560396171418694700.sql]: Please add this change:
```suggestion
UPDATE `gameobject_template` SET `Data0`='6000000' WHERE `entry`=193070;

-- Nexus Raid Platform now has faction 35, instead of 0 and is friendly to players.
UPDATE `gameobject_template_addon` SET `faction`='35' WHERE `entry`=193070;
```
Taken from here: https://github.com/azerothcore/azerothcore-wotlk/pull/1964/files

**Comment by Stoabrogga** [comment]
I'd say we add the faction change, too, and stick to this PR.

**Comment by Stoabrogga** [comment]
I added this to the first comment:
```
Co-authored-by: Andrei-UPB Andrei-UPB@users.noreply.github.com
Co-authored-by: GMKyle GMKyle@users.noreply.github.com
```
@Andrei-UPB created #1964 and @GMKyle had the idea about changing the faction. This PR #2085 added a change to the InstanceScript concerning the damage to the platform which was missing in #1964.

File: data/sql/updates/pending_db_world/rev_1560396171418694700.sql (hunk 2 above)
Comment (zabustak) [reply data/sql/updates/pending_db_world/rev_1560396171418694700.sql]: Done with force-push

**Comment by zabustak** [comment]
I updated the SQL file, now the platform has 35 faction and 6 million HP

**Comment by Stoabrogga** [comment]
Updated the SQL script (numeric values should not be treated as strings). Will test this PR later.

**Comment by Stoabrogga** [comment]
Successfully tested. The player is not able to break the platform. After the scripted event it breaks correctly.

**Comment by poszer** [comment]
Thank you for PR :+1:
