### PR TITLE
fix(Scripts/ShadowLabirynth): Ambassador Hellmaw:

### LINKED ISSUE #15638: [Shadow Labyrinth] Ambassador Hellmaw
### Current Behaviour

.

### Expected Blizzlike Behaviour

- Ambassador Hellmaw should not be invisible. He should have the Banish visual effect. Something is making him invisible. Removing the Banish Aura and re-adding it applies it correctly.

- Ambassadow Hellmaw can attack while casting Corrosive Acid. See: https://github.com/azerothcore/azerothcore-wotlk/pull/12095/files

- Needs flags_extra 33554432 to avoid repeated aggro which is calling the Reset function endlessly. He does **not** have unit_flags 768... go figure

## Unbanish

Only gets unbanished after all 18 Ritualists die. See: https://github.com/azerothcore/azerothcore-wotlk/pull/15536

https://github.com/azerothcore/azerothcore-wotlk/pull/15565 Adds DO_ACTION with ActionId 1 to all Ritualists on death
There's 18 Total

## After Unbanish

Lose Banish
Emote ID: 15 (OneShotRoar)
SoundKitID: 9349 (9349)
Flags: 32832
Wait 1000ms
Start PATH 1:

```
(@PATH,1,-159.51387,-2.139098,8.073091,NULL,0,0,0,100,0),
(@PATH,2,-163.44856,-7.553354,8.073133,NULL,0,0,0,100,0),
(@PATH,3,-168.17548,-9.746803,8.073169,NULL,0,0,0,100,0),
(@PATH,4,-171.3253,-13.198364,8.073106,NULL,0,0,0,100,0),
(@PATH,5,-172.78348,-25.986193,8.073088,NULL,0,0,0,100,0),
(@PATH,6,-173.66841,-54.100628,8.073081,NULL,0,0,0,100,0),
(@PATH,7,-168.93939,-66.52654,8.073219,NULL,0,0,0,100,0),
(@PATH,8,-157.49812,-73.04389,8.077904,NULL,0,0,0,100,0),
(@PATH,9,-145.8215,-67.855865,8.063689,NULL,0,0,0,100,0),
(@PATH,10,-141.28224,-56.002922,8.073066,NULL,0,0,0,100,0),
(@PATH,11,-142.33768,-25.135996,8.073035,NULL,0,0,0,100,0),
(@PATH,12,-143.23366,-14.373271,8.073031,NULL,0,0,0,100,0),
(@PATH,13,-147.05266,-10.097949,8.0730295,NULL,0,0,0,100,0),
(@PATH,14,-152.87035,-5.490992,8.073108,NULL,0,0,0,100,0),
(@PATH,15,-156.7587,4.856207,8.073061,4.660028934478759765,0,0,0,100,0),
```

Wait 20s

Start PATH 2:
```
(@PATH,16,-156.31073,24.4289,8.072962,NULL,0,0,0,100,0),
(@PATH,17,-153.34592,40.90819,6.877141,NULL,0,0,0,100,0),
(@PATH,18,-144.48116,52.74748,5.6318674,NULL,0,0,0,100,0),
(@PATH,19,-130.80013,60.605686,4.2999473,NULL,0,0,0,100,0),
(@PATH,20,-91.258835,61.131367,3.2408845,NULL,0,0,0,100,0),
(@PATH,22,-73.11457,51.921284,1.4783795,2.705260276794433593,30000,0,0,100,0),
(@PATH,23,-89.108116,61.20221,3.026778,NULL,0,0,0,100,0),
(@PATH,24,-108.00966,63.536663,3.4476438,NULL,0,0,0,100,0),
(@PATH,25,-130.86102,60.57378,4.3055944,NULL,0,0,0,100,0),
(@PATH,26,-143.99977,52.971825,5.5921054,NULL,0,0,0,100,0),
(@PATH,27,-152.94989,41.38679,6.888551,NULL,0,0,0,100,0),
(@PATH,28,-156.86404,25.838596,8.125509,NULL,30000,0,0,100,0),
(@PATH,29,-156.68945,2.408526,8.073063,NULL,20000,0,0,100,0);
```

Repeat PATH 2

### Source

_No response_

### Steps to reproduce the problem

.go c id 18731
Kill all nearby Cabal Ritualists (there's 18)

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/03495b773735d68566460b4b665bb6b36e5cf4b3

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Properly handle Banish intro event.
Ambassadow Hellmaw can attack while casting Corrosive Acid. Added missing paths.
Fixes #15638

## Issues Addressed:

- Closes #15638

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.go c id 18731`
Kill all nearby Cabal Ritualists (there's 18)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_ambassador_hellmaw.cpp [hunk 1]
```diff
@@ -59,64 +63,102 @@ class boss_ambassador_hellmaw : public CreatureScript
...
+            Reset();
 
-            me->RemoveAurasDueToSpell(SPELL_BANISH);
-            Talk(SAY_INTRO);
-            Start(true, false, ObjectGuid::Empty, nullptr, false, true);
-            isBanished = false;
+            if (instance && instance->GetData(TYPE_RITUALISTS) != DONE)
+            {
+                isBanished = true;
+                me->SetImmuneToAll(true);
```
Comment (Gultask) [inline src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_ambassador_hellmaw.cpp:73]: > He does not have unit_flags 768... go figure

**Review by Nyeriah — APPROVED** [review]
