### PR TITLE
Fix (DB/Quest) A Necessary Distraction from TrinityCore

### LINKED ISSUE #1159: [Quest] A Necessary Distraction
##### SMALL DESCRIPTION:

While doing quest, and killing these Sunfury Warlocks or Summoners, the Azaloth attacking you too, which is wrong. Also while banished he should be immune, not attackable ( The Banish state is wrong too, doesn't apply Visual on Azaloth)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Azaloth can be found south side of the Black Temple. He's currently being held "banished" by several Sunfury blood elves. Players will need to kill Sunfury Warlocks or Summoners (not necessarily the ones holding Azaloth) until one drops a  [Scroll of Demonic Unbanishing]. Use the scroll on the demon to release him. You do not need to defeat Azaloth, but he will attack you ( After you use Scroll on him ).
Until that he should be Immune while Banished
[Here is link of video](https://youtu.be/1pTminRkW68?t=29)

##### STEPS TO REPRODUCE THE PROBLEM:

1.  .quest add 10688  and .quest add 10637
2.  .go xyz -3878.602783 364.436432 129.075577 530
3. Try to attack Summoners ( Sunfury Warlocks )
4. The Azaloth will attack you too when you get near him which is wrong (He should be immune)
5. Also the Visaul on on him is wrong ( While Banished )
6. After using the Scoll on him, the look is same ( Which is wrong )
PS. Quest can be done, SAI need to be updated

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

585d293

##### OPERATING SYSTEM:

Windows Server 2012 R2

##### OTHER CUSTOMIZATIONS:

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/68069248-quest-a-necessary-distraction?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Branel**
## Changes Proposed:
-  He will now be banished
-  He will have the proper visuals

## Issues Addressed:

- Closes #1159

## SOURCE:

Port from TrinityCore https://github.com/TrinityCore/TrinityCore/issues/23857
I believe @dr-j is the original author of this SmartAI, thanks!
## Tests Performed:

Tested on local Windows 10 server.

## How to Test the Changes:

1. .quest add 10688 and .quest add 10637
2. .go xyz -3878.602783 364.436432 129.075577 530

## Known Issues and TODO List:

N/A

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1620888636790704800.sql [hunk 1]
```diff
@@ -0,0 +1,38 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1620888636790704800');
+
+UPDATE `creature_template_addon` SET `auras`='' WHERE `entry` = 21506;
+DELETE FROM `creature_addon` WHERE `guid` = 75420;
+UPDATE `creature_template` SET `unit_flags`=32768 WHERE `entry` = 21506;
+
+DELETE FROM `smart_scripts` WHERE `entryorguid` = 21503;
```
Comment (FrancescoBorzi) [inline data/sql/updates/pending_db_world/rev_1620888636790704800.sql:7]: missing `source_type` in the delete clause

**Review by FrancescoBorzi — APPROVED** [review]
