### PR TITLE
fix(Core/Spell): Remove delay from Flare activation

### LINKED ISSUE #5908: Flare debuff/effect doesn't work as blizzard intended
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/650

##### CURRENT BEHAVIOUR:

Flare currently will remove stealthers from stealth and prevent re-stealth only after the animation of the flare itself is done, in other words only when the flare travels through the entire vector to the selected area.

Flare [Spell](https://wowgaming.altervista.org/aowow/?spell=1543)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

This behavior is incorrect as the flare debuff is applied IMMEDIATELY as it is launched, this appears to be a common issue on WOTLK private servers as I've found 2 more github issues from 2011 and 2014 with associated proof from blizzard retail WOTLK live realms and blizzard official Arena Tournament realm from the same period.

https://github.com/TrinityCore/TrinityCore/issues/1331
https://github.com/TrinityCore/TrinityCore/issues/1331

Videos & comment taken from the last github report:

> How it should work:
> The effect of the spell should start on use, not when it lands. The landing of the flare is only visual. It should reveal stealthed units while flying and when landed and break stealth.
> 
> http://www.warcraftmovies.com/movieview.php?id=163895
> Stop the movie at 1:20, and watch rogues debufs. Flare is used, but not landed and he has the debuf already.
> At 3:22 you can see the same thing, flare has not landed, but the mage has the debuf.
> At 13:27 you can see rogue has been revealed by the flare which is in the air.
> 
> This one is taken from blizz TournamentRealm: http://www.youtube.com/watch?v=a74AeUDLwQI
> Stop the movie at 7:42. You can see that rogue, warlock and shaman gets the debuf before flare lands.

##### STEPS TO REPRODUCE THE PROBLEM:

Simply find an hostile target and shoot flare on it's feet, you will see the debuff will be applied only after the entire animation is done rather than instantly.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8dd58ebb5bea6a8aada54c830d06974d3ecd1353

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 1b6c200):

WoWScrnShot_051721_163057
WoWScrnShot_051721_163108
WoWScrnShot_051721_163114
WoWScrnShot_051721_163134
WoWScrnShot_051721_163149
WoWScrnShot_051721_163155

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98542589-flare-debuff-effect-doesn-t-work-as-blizzard-intended?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by anguaive**
The activation of the Flare (spell id: 1543) AoE aura was delayed
until the projectile hit the ground, which takes 5 seconds. Apparently
this is not blizzlike and the area should be activated instantly
when casting the spell.

New behavior: 

https://user-images.githubusercontent.com/39011611/118653254-9d573a80-b7e7-11eb-8171-b60c833db194.mp4

## Changes Proposed:
- Update `Speed` column of Flare spell from `5` to `0`

## Issues Addressed:

- Closes #5908
- Closes https://github.com/chromiecraft/chromiecraft/issues/650

## SOURCE:

https://youtu.be/TXedpA8iVRk?t=752
http://www.youtube.com/watch?v=a74AeUDLwQI&t=462

## Tests Performed:

- Tested on d0a259d

## How to Test the Changes:

1. Cast Flare on a stealthed target
2. The stealthed target should be revealed immediately when casting the spell

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1621339467730285597.sql [hunk 1]
```diff
@@ -0,0 +1,8 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1621339467730285597');
+
+DELETE FROM `spell_dbc` WHERE `ID` = 1543;
```
Comment (FrancescoBorzi) [inline data/sql/updates/pending_db_world/rev_1621339467730285597.sql:3]: please remove the `DELETE` in case of `spell_dbc` (or other DBC tables) we use only `INSERT IGNORE`

**Comment by FrancescoBorzi** [comment]
thanks for your contribution, almost ready :)

File: data/sql/updates/pending_db_world/rev_1621339467730285597.sql (hunk 1 above)
Comment (anguaive) [reply data/sql/updates/pending_db_world/rev_1621339467730285597.sql]: Alrighty, done

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@anguaive I'm having a second thought on this as it feels a bit wrong to me. Indeed the videos you posted prove that on WoW classic it worked like that, but are we sure this is the expected behaviour in 3.3.5a as well?

I'd say this needs a second opinion.

**Comment by Knindzagxg** [comment]
Animation from Flare is there so other people can actually see effect on the ground and avoid it if need.

Spell it self is not really instant, and if i remember good, from old Arena Tournaments there is supper small delay for it to be activated.
It's the same duration as spell queuing, but can't remember was it 0.2 or 0.4sec.

That's why rogues still had chance to do openers on people if they are super quick.

**Comment by Knindzagxg** [comment]
And @FrancescoBorzi -> Spell didn't had any big changes from Classic till Cata.
f727d02aef1524eb36ebdc43eb751cc9

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
> And @FrancescoBorzi -> Spell didn't had any big changes from Classic till Cata.
> f727d02aef1524eb36ebdc43eb751cc9

ok, thanks for your feedback. I did more research as well and this looks definitely right.

Thanks @anguaive !

**Comment by Knindzagxg** [comment]
Tho, i would check what's default spell queue for WOTLK (0.2 or 0.4) and set to that xP

**Comment by Goatform** [comment]
Can't you just set the `Speed` value using SpellMgr.cpp , if so I'd say it is far better to hold "hotfix" like that there than having it in DB

**Comment by anguaive** [comment]
@Goatform I'm still familiarizing myself with the code so I wasn't aware of that possibility. The SpellMgr solution does look cleaner to me too. If this ends up being the consensus then I'd gladly look into it

**Comment by Goatform** [comment]
@anguaive no problem, we all learn new stuff every day.

Here is the solution in C++ way. Haven't tested it myself but that should be an identical one unless it is overridden somewhere.

``` cpp
// Flare
ApplySpellFix({ 1543 }, [](SpellEntry* spellInfo)
{
    spellInfo->Speed = 0.0f;
});
```

**Comment by anguaive** [comment]
Tried the above solution with a low non-zero value as @Knindzagxg recommended and the spell behaved abnormally - the flare aura sometimes wouldn't activate at all, or only if the caster moved closer to it. Setting `speed` to `0` worked fine, but the aura activated instantly. I guess this has to do with `HandleMissileEffects` getting skipped if the value is 0 (https://wowdev.wiki/DB/Spell#3.3.5.12340). 

I left it at 0 for now. Since 0 is closer to the desired 0.2-0.4 value than 5.0, I guess this could serve as a temporary workaround until someone 'fluent in spells' comes around with the proper/idiomatic solution.
