### PR TITLE
fix(scripts/Ulduar): Two fixes to Algalon encounter

### LINKED ISSUE #2825: [Ulduar] Algalon incorrect scripting (Big Bang Mechanics/P2 Add Spawns) [$25]
**##### CURRENT BEHAVIOR:**
Algalon does not cast Ascend to the Heavens when there is no one else in the room. However, he does cast Ascend to the Heavens if Big Bang doesn't hit any targets. Additionally, the Unleashed Dark Matter sit in their spawns and don't move to attack those in the room. Video 1, entering the Black Hole as the tank, and coming back to an Algalon that didn't realize I was gone: https://youtu.be/-JD03PnsxEU / Video 2, Unleashed Dark Matter sitting in their spawn: https://youtu.be/jFq1xu9osi0

**##### EXPECTED BLIZZLIKE BEHAVIOR:**
Unfortunately, I wasn't able to find video proof of this, however Algalon is supposed to cast Ascend to the Heavens when there are no targets present in his main realm, in addition to when no one is hit by Big Bang. A snippet from Wowpedia:

>  If everyone enters the Black Holes and Algalon has no player in the normal realm to target, he kills the raid with Ascend to the Heavens.

Lastly, the Unleashed Dark Matter spawned during Phase 2 Algalon simply sit there unless you move close. They should be moving to anyone present in the room at random: https://youtu.be/uv_b1-bsN5o?t=387

**##### STEPS TO REPRODUCE THE PROBLEM:**
1.  Pull Algalon, wait until he spawns Collapsing Stars. Kill one, and step into black hole.
2.  Side step a little and wait to return to the main realm. Algalon will be there waiting, instead of murdering you.
3.  Phase Algalon to 20% HP, and move to a corner of the room or the dead middle. Unleashed Dark Matter will not move.

**##### EXTRA NOTES:**

**##### AC HASH/COMMIT:**
32da0eeb9e39

**##### OPERATING SYSTEM:**
Win10

**##### MODULES:**
No

**##### OTHER CUSTOMIZATIONS:**
Increased HP on bosses

---

There is a [$10](https://www.bountysource.com/issues/90852805-ulduar-raid-flame-leviathan-xt-algalon-errors) open bounty on this issue. Add to the bounty at Bountysource.

<bountysource-plugin>

---
There is a **[$25 open bounty](https://www.bountysource.com/issues/90852805-ulduar-algalon-incorrect-scripting-big-bang-mechanics-p2-add-spawns?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
Dark Matter mobs should be considered as the Algalon summon.
Algalon should cast Ascend of the Heavens if pulled from out of platform or no one left in normal realm.
Fixed #2825.

## Changes Proposed:
-  
-  

## Issues Addressed:
- Closes #2825.

## Tests Performed:
-
-

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

File: src/server/scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp [hunk 1]
```diff
@@ -1026,6 +1026,13 @@ class npc_algalon_worm_hole : public CreatureScript
             _summonTimer = urand(22000, 24000);
         }
 
+        void JustSummoned(Creature* summon) override
+        {
+            if (TempSummon* summ = me->ToTempSummon())
+                if (Creature* algalon = ObjectAccessor::GetCreature(*me, summ->GetSummonerGUID()))
+                    algalon->AI()->JustSummoned(summon);
+        }
+
```
Comment (FrancescoBorzi) [inline src/server/scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp:1035]:
```suggestion
        void JustSummoned(Creature* summon) override
        {
            if (auto summ = me->ToTempSummon())
            {
                if (auto algalon = ObjectAccessor::GetCreature(*me, summ->GetSummonerGUID()))
                {
                    algalon->AI()->JustSummoned(summon);
                }
            }
        }
```

Comment (UltraNix) [reply src/server/scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp:1035]: Why auto? I don't get it.

Comment (FrancescoBorzi) [reply src/server/scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp:1035]: the `auto` is just a suggestion to save some typing, not mandatory. Please add the brackets though. It may sound too strict but I've seen many mistakes happening because of the lack of those. Including in AC.

**Comment by pklloveyou** [comment]
This PR fixed the error

**Comment by Voxstrasza** [comment]
@UltraNix any plans on adding the check for no players on the platform to initiate the ascend to the heavens cast?

**Comment by UltraNix** [comment]
Yes.

**Comment by pklloveyou** [comment]
image
This can also be fixed heavens

**Comment by Voxstrasza** [comment]
@UltraNix are you going to make a new PR or add it to this one?

@FrancescoBorzi we can label it WIP if that's the case as the issue covers two things

**Comment by UltraNix** [comment]
I will add it here as this is in the same issue ticket.

**Comment by UltraNix** [comment]
@Voxstrasza There you go :)
Ready to review/merge.

File: src/server/game/AI/ScriptedAI/ScriptedCreature.cpp [hunk 2]
```diff
@@ -473,7 +473,7 @@ Player* ScriptedAI::SelectTargetFromPlayerList(float maxdist, uint32 excludeAura
     std::vector<Player*> tList;
     for(Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
     {
-        if (me->GetDistance(itr->GetSource()) > maxdist || !itr->GetSource()->IsAlive() || itr->GetSource()->IsGameMaster())
+        if (!me->IsWithinDistInMap(itr->GetSource(), maxdist) || !itr->GetSource()->IsAlive() || itr->GetSource()->IsGameMaster())
```
Comment (pklloveyou) [inline src/server/game/AI/ScriptedAI/ScriptedCreature.cpp:476]: Will this break some other code?

Comment (UltraNix) [reply src/server/game/AI/ScriptedAI/ScriptedCreature.cpp:476]: `GetDistance` checks only distance. `IsWithinDistInMap` checks distance, same map and same phase. I looked at other calls of this function and this change should not break anything. It ensures that the selected targets in the same phase as source. This function is used mainly to select victim to be attacked by source, so this is just improvement.

Comment (pklloveyou) [reply src/server/game/AI/ScriptedAI/ScriptedCreature.cpp:476]: Will it be safer to do so?
image

Comment (pklloveyou) [reply src/server/game/AI/ScriptedAI/ScriptedCreature.cpp:476]: OK

**Review by Si1ker — APPROVED** [review]
