### PR TITLE
Fix(DB): Backbiter movement and some missing texts in Dalaran

### LINKED ISSUE #980: Could not find text for creature
PROBLEM

2018-07-17 06:42:51 CreatureTextMgr: Could not find Text for Creature(Disidra Stormglory) Entry 32718 in 'creature_text' table. Ignoring.
2018-07-17 06:43:55 CreatureTextMgr: Could not find Text for Creature(Moon Priestess Nici) Entry 32714 in 'creature_text' table. Ignoring.
2018-07-17 06:44:08 CreatureTextMgr: Could not find Text for Creature(Warp-Huntress Kula) Entry 32711 in 'creature_text' table. Ignoring.
2018-07-17 06:44:13 CreatureTextMgr: Could not find Text for Creature(Orland Schaeffer) Entry 29506 in 'creature_text' table. Ignoring.
2018-07-17 06:44:52 CreatureTextMgr: Could not find Text for Creature(Warp-Huntress Kula) Entry 32711 in 'creature_text' table. Ignoring.
2018-07-17 06:45:01 CreatureTextMgr: Could not find Text for Creature(Invisible Stalker (Floating Only)) Entry 27047 in 'creature_text' table. Ignoring.
2018-07-17 08:53:26 SmartScript::ProcessAction: Entry 20071 SourceType 0, Event 0, Link Event 1 not found or invalid, skipped.
2018-07-17 09:11:51 CreatureTextMgr: Could not find Text for Creature(Great Hexer Ohodo) Entry 32719 in 'creature_text' table. Ignoring.
2018-07-17 09:12:38 CreatureTextMgr: Could not find Text for Creature(Orland Schaeffer) Entry 29506 in 'creature_text' table. Ignoring.

Someone who can solve this problem? appears directly in worldserver.exe

AC HASH / COMMIT:
8767372

OPERATIONAL SYSTEM:
Windonws R2 2008

MODULES:
NO

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/61036661-could-not-find-text-for-creature?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #1379: Backbiter movement bug
DESCRIPTION:

NPC Backbiter "dance" on site.

EXPECTED BLIZZLIKE BEHAVIOUR:

Backbiter is the warp stalker pet of Warp-Huntress Kula and follow her.

CURRENT BEHAVIOUR:

Backbiter "dance" on site. It does not follow Kula (https://wowgaming.altervista.org/aowow/?npc=32751)

STEPS TO REPRODUCE THE PROBLEM:

.go 5838.9 600.7 650.8 571

BRANCH(ES):
staging

AC HASH/COMMIT:
commit 987095e

OPERATING SYSTEM:
linux

MODULES:
OTHER CUSTOMIZATIONS:

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
Fix Backbiter following Warp-Huntress Kula in Dalaran. Instead of summoning Backbiter via spell "Summon Backbiter" by Kula it is inserted as regular creature following Kula in close formation. Also fixed some missing texts for the following creature IDs in order to get rid of the errors in the server log:
27047: Invisible Stalker (Floating Only)
32711: Warp-Huntress Kula
29506: Orland Schaeffer

I used the inserts proposed by Knindzagxg in #980.

###### ISSUES ADDRESSED:
Closes #980
Closes #1379

##### TESTS PERFORMED:
tested in-game on Ubuntu 16.04 using AC commit 9af2a461f65316ce4c21c9668dd62515b8e4f370

##### HOW TO TEST THE CHANGES:
- ```.go creature id 32711```
- follow Kula around
- check server log for error messages concerning the texts for the creature IDs mentioned above

##### KNOWN ISSUES AND TODO LIST:
None

##### Target branch(es):
Master

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1548778743987887239.sql [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+DELETE FROM `creature_formations` WHERE `leaderGUID` = 114764;
+INSERT INTO `creature_formations` (`leaderGUID`, `memberGUID`, `dist`, `angle`, `groupAI`, `point_1`, `point_2`)
+VALUES
+(114764,114764,0,0,515,0,0),
+(114764,2023271,2,270,515,0,0);
+
+DELETE FROM `creature_text` WHERE `CreatureID` IN (27047,32711,29506);
+INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`)
+VALUES
+(27047, 0, 0, '', 12, 0, -1, 0, 0, 0, 0, 0, 'Invisible Stalker (Floating Only)'),
```
Comment (wetbrownsauce) [inline data/sql/updates/pending_db_world/rev_1548778743987887239.sql]: Probability is an unsigned column and can't be set to -1.

Comment (wetbrownsauce) [reply data/sql/updates/pending_db_world/rev_1548778743987887239.sql]: From commit b34bc28e5b02514fca3519beac420c58faa89cad:
```
ALTER TABLE `creature_text` CHANGE `probability` `Probability` FLOAT UNSIGNED NOT NULL DEFAULT '0';
```

Prior to the above commit, the column was signed.

Comment (FrancescoBorzi) [reply data/sql/updates/pending_db_world/rev_1548778743987887239.sql]: @Stoabrogga were you using latest AC version when you made this fix?

Comment (Stoabrogga) [reply data/sql/updates/pending_db_world/rev_1548778743987887239.sql]: Thanks for pointing this out, I did indeed miss the warning. As mentioned in the PR, I'm using commit 9af2a461f65316ce4c21c9668dd62515b8e4f370. Pushed a new commit to fix this.

**Comment by wetbrownsauce** [comment]
Tested with the new change. 

So I followed the NPC around Dalaran for one entire cycle of her waypoints. (fun fact: that takes 10 min and 50 sec)

- Backbiter correctly follows with improved pathing. No longer walks onto walls, no longer gets stuck, no longer walks the wrong way. 

- No more errors in worldserver

However, I am getting this in chat now:
npc

**Comment by Stoabrogga** [comment]
@wetbrownsauce 
I pushed another commit now effectively silencing the Invisible Stalkers.

**Comment by Stoabrogga** [comment]
By the way, you don't need to move around, just stand a few minutes inside "The Hunter's Reach" to test the Invisible Stalker text:

```.go 5776.69 553.448 651.639 571```

I don't know what purpose these creatures have, but I also don't want to just delete them, only remove the errore message from the log.

**Comment by FrancescoBorzi** [comment]
Good job @Stoabrogga 

thanks @wetbrownsauce for testing, please feel free to change the label when you think a PR can be merged

**Comment by BarbzYHOOL** [comment]
thank you guys! merged
