### PR TITLE
fix(Core/Command): Fix issue with waypoint show off

### LINKED ISSUE #10779: Command : .wp show off drop all creature table
### Current Behaviour

I don't know why but this command just erase the entire `creature` table in the database `acore_world`.

### Expected Blizzlike Behaviour

Only delete waypoints helping creature

### Source

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Commands/cs_wp.cpp#L1051-L1108

### Steps to reproduce the problem

1. I've targeted the creature
2. I just write `.wp show off`

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/400caec7099addf7329396800341c0f9070da734

### Operating system

Ubuntu 21.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by malcrom**
## Changes Proposed:
-  Add code to core provided by Winfidonarleyan to prevent removal of creature table when doing GM command .wp show off

## Issues Addressed:
- Closes #10779

## SOURCE:
Winfidonarleyan

## Tests Performed:
- tested in game and creatures remain in table

## How to Test the Changes:
1. show wp for a creature then select creature and do .wp show off

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

File: src/server/scripts/Commands/cs_wp.cpp [hunk 1]
```diff
@@ -1052,6 +1052,8 @@ class wp_commandscript : public CommandScript
         {
             WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_SEL_CREATURE_BY_ID);
             stmt->SetData(0, 1);
+            stmt->SetData(1, 1);
+            stmt->SetData(2, 1);
```
Comment (Winfidonarleyan) [inline src/server/scripts/Commands/cs_wp.cpp:1056]:
```suggestion
            stmt->SetArguments(1, 1, 1);
```

Comment (Winfidonarleyan) [inline src/server/scripts/Commands/cs_wp.cpp:1056]:
```suggestion
            stmt->SetArguments(1, 1, 1);
```
