### PR TITLE
fix(Scripts/AhnQiraj): Implemented General Andorov event.

### LINKED ISSUE #12173: [AQ20] Andorov event doesn't present after the Kurinnaxx death
### Current Behaviour

When Kruinnaxx die, nothing happend.

### Expected Blizzlike Behaviour

After the Kurinnaxx death, [Lieutenant General Andorov](https://classic.wowhead.com/npc=15471/lieutenant-general-andorov) and four [Kaldorei Elite](https://classic.wowhead.com/npc=15473/kaldorei-elite) should come from the entrance until the gate before General Rajaxx.

When the event is done, players can speak with Andorov for start the boss event with General Rajaxx.

### Source

https://youtu.be/tu99VfdupMg?t=247

https://classic.wowhead.com/guides/general-rajaxx-ruins-of-ahnqiraj-strategy

### Steps to reproduce the problem

1. Kill Kurinnaxx
2. Look if NPC come or not

### Extra Notes

_No response_

### AC rev. hash/commit

[37c1ce5](https://github.com/azerothcore/azerothcore-wotlk/commit/37c1ce5e36c9749bc9a063f0621bb1f02e47a6f1)

### Operating system

Windows 11

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Original author: @Rushor
Fixes #12173

## Issues Addressed:

- Closes #12173

## Tests Performed:

- Not tested.

## How to Test the Changes:

Kill Kurinnaxx
Look if NPC come or not

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
- [ ] They spawn immediately in Kurinnaxx's arena, and not at the start of the raid.
- [ ] They engage in combat with nearby trash around Kurinnaxx's arena.
- [ ] There's no gossip menu, right clicking on Andorov will immediately start the event.
- [ ] There's a vendor mouse icon when hovering over Andorov, even before the encounter with Rajaxx starts or ends.
- [ ] The Kaldorei Elite are all standing on top of each other.

File: data/sql/updates/pending_db_world/rev_1659801375917048100.sql [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+(@ENTRY,0,0,0,0,0,100,0,6000,9000,6000,9000,11,26350,0,0,0,0,0,2,0,0,0,0,0,0,0,"Kaldorei Elite - In Combat - Cast 'Cleave'"),
+(@ENTRY,0,1,0,0,0,100,0,9000,13000,9000,13000,11,16856,0,0,0,0,0,2,0,0,0,0,0,0,0,"Kaldorei Elite - In Combat - Cast 'Mortal Strike'");
+
+-- Swarmguard Needler SAI
+SET @ENTRY := 15344;
+UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
+DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
+INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
+(@ENTRY,0,0,0,0,0,100,0,5000,9000,5000,9000,11,40504,0,0,0,0,0,2,0,0,0,0,0,0,0,"Swarmguard Needler - In Combat - Cast 'Cleave'");
```
Comment (Nefertumm) [inline data/sql/updates/pending_db_world/rev_1659801375917048100.sql:40]: This one is already present on the core and it is sniffed, this doesn't match the values we got from sniff, remove it, please :)

File: data/sql/updates/pending_db_world/rev_1659801375917048100.sql [hunk 2]
```diff
@@ -0,0 +1,40 @@
+--
+UPDATE `creature_template` SET `ScriptName`='npc_general_andronov' WHERE `entry`=15471;
+UPDATE `creature_template` SET `npcflag`=129, `speed_walk`=1.4, `speed_run`=1.4, `gossip_menu_id`=7047 WHERE  `entry`=15471;
+
+DELETE FROM `script_waypoint` WHERE `entry`=15471;
+INSERT INTO `script_waypoint` (`entry`, `pointid`, `location_x`, `location_y`, `location_z`, `waittime`, `point_comment`) VALUES 
+(15471, 0, -8876.79, 1634.59, 21.3864, 0, 'Andronov'),
```
Comment (Nefertumm) [inline data/sql/updates/pending_db_world/rev_1659801375917048100.sql:7]: minimal but the comment is wrong, is Andorov.

**Comment by Nyeriah** [comment]
I already implemented the waves...
We just need to spawn andorov

**Comment by UltraNix** [comment]
@Nyeriah So why this report was not assigned to anybody nor any info that somebody is already working on it?

**Comment by Nyeriah** [comment]
Because Andorov isn't related to Rajaxx waves and I didnt do anything with Andorov.

You can pull Rajaxx by talking to Andorov but they are not connected, you can skip the Andorov thing on retail altogether

I checked the code and the way the TC guys did it also doesn't match our research:
1) the timer should be two minutes (they set it to 1 min)
2) Rajaxx doesnt say anything during the waves if they get pulled by the timer (it is some sort of dps check)
3) Waves are pulled in successesion as soon as all members are dead, not on timer only

All of the above works

What was missing:
- Andorov spawn at the start of the entrance
- Talking to Andorov initiates a sequence where he walks to the arena and taunts Rajaxx and they trade a few lines
- The waves target Andorov it seems when they are pulled

So the alternative start (through gossip) was missing

**Comment by UltraNix** [comment]
Okay.

**Comment by Maelthyrr** [comment]
@UltraNix since the last commit is it always in WIP ? I've just tested against and I got the same issue than Gultask.

**Comment by UltraNix** [comment]
It is in WIP because still waiting for proper spawn position and waypoints.

**Comment by Gultask** [comment]
Ah, sorry for the delay. Here are the spawn sniffs:

<details>
 <summary>Details</summary>

ServerToClient: SMSG_UPDATE_OBJECT (0x27BA) Length: 3344 ConnIdx: 1 Time: 07/24/2022 22:57:58.490 Number: 4981
NumObjUpdates: 5
MapID: 509 (509)
HasRemovedObjects: False
Data size: 3333
[0] UpdateType: CreateObject2
[0] Object Guid: Full: 0x2030F43FA00F1BC00068F700005DF8A6 Creature/0 R3133/S26871 Map: 509 Entry: 15471 Low: 6158502
[0] Object Type: 5 (Unit)
[0] NoBirthAnim: False
[0] EnablePortals: False
[0] PlayHoverAnim: False
[0] HasMovementUpdate: True
[0] HasMovementTransport: False
[0] Stationary: False
[0] HasCombatVictim: False
[0] HasServerTime: False
[0] HasVehicleCreate: False
[0] HasAnimKitCreate: False
[0] HasRotation: False
[0] HasAreaTrigger: False
[0] HasGameObject: False
[0] HasSmoothPhasing: False
[0] ThisIsYou: False
[0] SceneObjCreate: False
[0] HasPlayerCreateData: False
[0] HasConversation: False
[0] MoverGUID: Full: 0x2030F43FA00F1BC00068F700005DF8A6 Creature/0 R3133/S26871 Map: 509 Entry: 15471 Low: 6158502
[0] MovementFlags: 1 (Forward)
[0] MovementFlags2: 0 (None)
[0] MovementFlags3: 0 (None)
[0] MoveTime: 856902151
[0] Position: X: -8538.177 Y: 1486.0956 Z: 32.39054
[0] Orientation: 3.763865470886230468
[0] Pitch: 0
[0] StepUpStartElevation: 0
[0] MoveIndex: 0
[0] Has Transport Data: False
[0] Has Fall Data: False
[0] HasSpline: True
[0] HeightChangeFailed: False
[0] RemoteTimeValid: False
[0] HasInertia: False
[0] WalkSpeed: 2.5
[0] RunSpeed: 8
[0] RunBackSpeed: 4.5
[0] SwimSpeed: 4.72221994400024414
[0] SwimBackSpeed: 2.5
[0] FlightSpeed: 7
[0] FlightBackSpeed: 4.5
[0] TurnRate: 3.141592741012573242
[0] PitchRate: 3.141592741012573242
[0] MovementForceCount: 0
[0] MovementForcesModMagnitude: 1
[0] HasMovementSpline: True
[0] ID: 4260
[0] Destination: X: -8583.434 Y: 1453.6205 Z: 32.032005
[0] MovementSplineMove: True
[0] SplineFlags: 2434793472 (CanSwim, Unknown5, Steering, Unknown10)
[0] Elapsed: 1
[0] Duration: 6967
[0] DurationModifier: 1
[0] NextDurationModifier: 1
[0] Face: 0
[0] HasSpecialTime: False
[0] PointsCount: 7
[0] HasSplineFilterKey: False
[0] HasSpellEffectExtraData: False
[0] HasJumpExtraData: False
[0] HasAnimationTierTransition: False
[0] Unknown901: False
[0] [0] Points: X: -8534.113 Y: 1489.0105 Z: 32.62407
[0] [1] Points: X: -8538.177 Y: 1486.0956 Z: 32.39054
[0] [2] Points: X: -8542.24 Y: 1483.1807 Z: 32.157013
[0] [3] Points: X: -8575.553 Y: 1459.2773 Z: 32.407005
[0] [4] Points: X: -8582.865 Y: 1454.0303 Z: 32.032005
[0] [5] Points: X: -8583.434 Y: 1453.6205 Z: 32.032005
[0] [6] Points: X: -8583.434 Y: 1453.6205 Z: 32.032005
[0] PauseTimesCount: 0
[0] FieldFlags: 4 (UnitAll)
[0] EntryID: 15471
[0] DynamicFlags: 0
[0] Scale: 1
[0] DisplayID: 15688
[0] [0] NpcFlags: 1
[0] [1] NpcFlags: 0
[0] StateSpellVisualID: 0
[0] StateAnimID: 1716
[0] StateAnimKitID: 0
[0] StateWorldEffectsQuestObjectiveID: 0
[0] SpellOverrideNameID: 0
[0] Charm: Full: 0x0
[0] Summon: Full: 0x0
[0] CharmedBy: Full: 0x0
[0] SummonedBy: Full: 0x0
[0] CreatedBy: Full: 0x0
[0] DemonCreator: Full: 0x0
[0] LookAtControllerTarget: Full: 0x0
[0] Target: Full: 0x0
[0] BattlePetCompanionGUID: Full: 0x0
[0] BattlePetDBID: 0
[0] (ChannelData) SpellID: 0
[0] (ChannelData) (SpellVisual) SpellXSpellVisualID: 0
[0] (ChannelData) (SpellVisual) ScriptVisualID: 0
[0] SummonedByHomeRealm: 0
[0] Race: 0
[0] ClassId: 2
[0] PlayerClassId: 0
[0] Sex: 0
[0] DisplayPower: 0
[0] OverrideDisplayPowerID: 0
[0] Health: 5873
[0] [0] Power: 38428
[0] [0] MaxPower: 38428
[0] [1] Power: 0
[0] [1] MaxPower: 0
[0] [2] Power: 0
[0] [2] MaxPower: 219
[0] [3] Power: 0
[0] [3] MaxPower: 0
[0] [4] Power: 0
[0] [4] MaxPower: 0
[0] [5] Power: 0
[0] [5] MaxPower: 0
[0] [6] Power: 0
[0] [6] MaxPower: 0
[0] [0] PowerRegenFlatModifier: 0
[0] [0] PowerRegenInterruptedFlatModifier: 0
[0] [1] PowerRegenFlatModifier: 0
[0] [1] PowerRegenInterruptedFlatModifier: 0
[0] [2] PowerRegenFlatModifier: 0
[0] [2] PowerRegenInterruptedFlatModifier: 0
[0] [3] PowerRegenFlatModifier: 0
[0] [3] PowerRegenInterruptedFlatModifier: 0
[0] [4] PowerRegenFlatModifier: 0
[0] [4] PowerRegenInterruptedFlatModifier: 0
[0] [5] PowerRegenFlatModifier: 0
[0] [5] PowerRegenInterruptedFlatModifier: 0
[0] [6] PowerRegenFlatModifier: 0
[0] [6] PowerRegenInterruptedFlatModifier: 0
[0] MaxHealth: 5873
[0] Level: 31
[0] EffectiveLevel: 0
[0] ContentTuningID: 1006
[0] ScalingLevelMin: 30
[0] ScalingLevelMax: 30
[0] ScalingLevelDelta: 1
[0] ScalingFactionGroup: 0
[0] ScalingHealthItemLevelCurveID: 0
[0] ScalingDamageItemLevelCurveID: 0
[0] FactionTemplate: 1608
[0] (VirtualItems) [0] ItemID: 21465
[0] (VirtualItems) [0] SecondaryItemModifiedAppearanceID: 0
[0] (VirtualItems) [0] ItemAppearanceModID: 0
[0] (VirtualItems) [0] ItemVisual: 0
[0] (VirtualItems) [1] ItemID: 21465
[0] (VirtualItems) [1] SecondaryItemModifiedAppearanceID: 0
[0] (VirtualItems) [1] ItemAppearanceModID: 0
[0] (VirtualItems) [1] ItemVisual: 0
[0] (VirtualItems) [2] ItemID: 0
[0] (VirtualItems) [2] SecondaryItemModifiedAppearanceID: 0
[0] (VirtualItems) [2] ItemAppearanceModID: 0
[0] (VirtualItems) [2] ItemVisual: 0
[0] Flags: 33280
[0] Flags2: 2097152
[0] Flags3: 0
[0] AuraState: 13631488
[0] [0] AttackRoundBaseTime: 2000
[0] [1] AttackRoundBaseTime: 2000
[0] BoundingRadius: 0.305999994277954101
[0] CombatReach: 1.5
[0] DisplayScale: 1
[0] CreatureFamily: 0
[0] CreatureType: 0
[0] NativeDisplayID: 15688
[0] NativeXDisplayScale: 1
[0] MountDisplayID: 0
[0] CosmeticMountDisplayID: 0
[0] StandState: 0
[0] PetTalentPoints: 0
[0] VisFlags: 0
[0] AnimTier: 0
[0] PetNumber: 0
[0] PetNameTimestamp: 0
[0] PetExperience: 0
[0] PetNextLevelExperience: 2147483647
[0] ModCastingSpeed: 1
[0] ModCastingSpeedNeg: 1
[0] ModSpellHaste: 1
[0] ModHaste: 1
[0] ModRangedHaste: 1
[0] ModHasteRegen: 1
[0] ModTimeRate: 1
[0] CreatedBySpell: 0
[0] EmoteState: 0
[0] BaseMana: 433
[0] SheatheState: 1
[0] PvpFlags: 1
[0] PetFlags: 0
[0] ShapeshiftForm: 0
[0] HoverHeight: 1
[0] MinItemLevelCutoff: 0
[0] MinItemLevel: 0
[0] MaxItemLevel: 0
[0] AzeriteItemLevel: 0
[0] WildBattlePetLevel: 0
[0] BattlePetCompanionExperience: 0
[0] BattlePetCompanionNameTimestamp: 0
[0] InteractSpellID: 0
[0] ScaleDuration: 100
[0] LooksLikeMountID: 0
[0] LooksLikeCreatureID: 0
[0] LookAtControllerID: -1
[0] TaxiNodesID: 0
[0] GuildGUID: Full: 0x0
[0] SilencedSchoolMask: 0
[0] NameplateAttachToGUID: Full: 0x0
[1] UpdateType: CreateObject2
[1] Object Guid: Full: 0x2030F43FA00F1C400068F700005DF8A6 Creature/0 R3133/S26871 Map: 509 Entry: 15473 Low: 6158502
[1] Object Type: 5 (Unit)
[1] NoBirthAnim: False
[1] EnablePortals: False
[1] PlayHoverAnim: False
[1] HasMovementUpdate: True
[1] HasMovementTransport: False
[1] Stationary: False
[1] HasCombatVictim: False
[1] HasServerTime: False
[1] HasVehicleCreate: False
[1] HasAnimKitCreate: False
[1] HasRotation: False
[1] HasAreaTrigger: False
[1] HasGameObject: False
[1] HasSmoothPhasing: False
[1] ThisIsYou: False
[1] SceneObjCreate: False
[1] HasPlayerCreateData: False
[1] HasConversation: False
[1] MoverGUID: Full: 0x2030F43FA00F1C400068F700005DF8A6 Creature/0 R3133/S26871 Map: 509 Entry: 15473 Low: 6158502
[1] MovementFlags: 0 (None)
[1] MovementFlags2: 0 (None)
[1] MovementFlags3: 0 (None)
[1] MoveTime: 856902151
[1] Position: X: -8538.09 Y: 1488.2867 Z: 32.484314
[1] Orientation: 4.118977069854736328
[1] Pitch: 0
[1] StepUpStartElevation: 0
[1] MoveIndex: 0
[1] Has Transport Data: False
[1] Has Fall Data: False
[1] HasSpline: False
[1] HeightChangeFailed: False
[1] RemoteTimeValid: False
[1] HasInertia: False
[1] WalkSpeed: 2.5
[1] RunSpeed: 8
[1] RunBackSpeed: 4.5
[1] SwimSpeed: 4.72221994400024414
[1] SwimBackSpeed: 2.5
[1] FlightSpeed: 7
[1] FlightBackSpeed: 4.5
[1] TurnRate: 3.141592741012573242
[1] PitchRate: 3.141592741012573242
[1] MovementForceCount: 0
[1] MovementForcesModMagnitude: 1
[1] HasMovementSpline: False
[1] PauseTimesCount: 0
[1] FieldFlags: 4 (UnitAll)
[1] EntryID: 15473
[1] DynamicFlags: 0
[1] Scale: 1
[1] DisplayID: 15691
[1] [0] NpcFlags: 0
[1] [1] NpcFlags: 0
[1] StateSpellVisualID: 0
[1] StateAnimID: 1716
[1] StateAnimKitID: 0
[1] StateWorldEffectsQuestObjectiveID: 0
[1] SpellOverrideNameID: 0
[1] Charm: Full: 0x0
[1] Summon: Full: 0x0
[1] CharmedBy: Full: 0x0
[1] SummonedBy: Full: 0x0
[1] CreatedBy: Full: 0x0
[1] DemonCreator: Full: 0x0
[1] LookAtControllerTarget: Full: 0x0
[1] Target: Full: 0x0
[1] BattlePetCompanionGUID: Full: 0x0
[1] BattlePetDBID: 0
[1] (ChannelData) SpellID: 0
[1] (ChannelData) (SpellVisual) SpellXSpellVisualID: 0
[1] (ChannelData) (SpellVisual) ScriptVisualID: 0
[1] SummonedByHomeRealm: 0
[1] Race: 0
[1] ClassId: 1
[1] PlayerClassId: 0
[1] Sex: 0
[1] DisplayPower: 1
[1] OverrideDisplayPowerID: 0
[1] Health: 2406
[1] [0] Power: 0
[1] [0] MaxPower: 0
[1] [1] Power: 0
[1] [1] MaxPower: 0
[1] [2] Power: 0
[1] [2] MaxPower: 5
[1] [3] Power: 0
[1] [3] MaxPower: 0
[1] [4] Power: 0
[1] [4] MaxPower: 0
[1] [5] Power: 0
[1] [5] MaxPower: 0
[1] [6] Power: 0
[1] [6] MaxPower: 0
[1] [0] PowerRegenFlatModifier: 0
[1] [0] PowerRegenInterruptedFlatModifier: 0
[1] [1] PowerRegenFlatModifier: 0
[1] [1] PowerRegenInterruptedFlatModifier: 0
[1] [2] PowerRegenFlatModifier: 0
[1] [2] PowerRegenInterruptedFlatModifier: 0
[1] [3] PowerRegenFlatModifier: 0
[1] [3] PowerRegenInterruptedFlatModifier: 0
[1] [4] PowerRegenFlatModifier: 0
[1] [4] PowerRegenInterruptedFlatModifier: 0
[1] [5] PowerRegenFlatModifier: 0
[1] [5] PowerRegenInterruptedFlatModifier: 0
[1] [6] PowerRegenFlatModifier: 0
[1] [6] PowerRegenInterruptedFlatModifier: 0
[1] MaxHealth: 2406
[1] Level: 30
[1] EffectiveLevel: 0
[1] ContentTuningID: 1006
[1] ScalingLevelMin: 30
[1] ScalingLevelMax: 30
[1] ScalingLevelDelta: 0
[1] ScalingFactionGroup: 0
[1] ScalingHealthItemLevelCurveID: 0
[1] ScalingDamageItemLevelCurveID: 0
[1] FactionTemplate: 1608
[1] (VirtualItems) [0] ItemID: 4991
[1] (VirtualItems) [0] SecondaryItemModifiedAppearanceID: 0
[1] (VirtualItems) [0] ItemAppearanceModID: 0
[1] (VirtualItems) [0] ItemVisual: 0
[1] (VirtualItems) [1] ItemID: 0
[1] (VirtualItems) [1] SecondaryItemModifiedAppearanceID: 0
[1] (VirtualItems) [1] ItemAppearanceModID: 0
[1] (VirtualItems) [1] ItemVisual: 0
[1] (VirtualItems) [2] ItemID: 0
[1] (VirtualItems) [2] SecondaryItemModifiedAppearanceID: 0
[1] (VirtualItems) [2] ItemAppearanceModID: 0
[1] (VirtualItems) [2] ItemVisual: 0
[1] Flags: 33280
[1] Flags2: 2097152
[1] Flags3: 0
[1] AuraState: 13631488
[1] [0] AttackRoundBaseTime: 2700
[1] [1] AttackRoundBaseTime: 2700
[1] BoundingRadius: 0.388999998569488525
[1] CombatReach: 1.5
[1] DisplayScale: 1
[1] CreatureFamily: 0
[1] CreatureType: 0
[1] NativeDisplayID: 15691
[1] NativeXDisplayScale: 1
[1] MountDisplayID: 0
[1] CosmeticMountDisplayID: 0
[1] StandState: 0
[1] PetTalentPoints: 0
[1] VisFlags: 0
[1] AnimTier: 0
[1] PetNumber: 0
[1] PetNameTimestamp: 0
[1] PetExperience: 0
[1] PetNextLevelExperience: 2147483647
[1] ModCastingSpeed: 1
[1] ModCastingSpeedNeg: 1
[1] ModSpellHaste: 1
[1] ModHaste: 1
[1] ModRangedHaste: 1
[1] ModHasteRegen: 1
[1] ModTimeRate: 1
[1] CreatedBySpell: 0
[1] EmoteState: 0
[1] BaseMana: 0
[1] SheatheState: 1
[1] PvpFlags: 1
[1] PetFlags: 0
[1] ShapeshiftForm: 0
[1] HoverHeight: 1
[1] MinItemLevelCutoff: 0
[1] MinItemLevel: 0
[1] MaxItemLevel: 0
[1] AzeriteItemLevel: 0
[1] WildBattlePetLevel: 0
[1] BattlePetCompanionExperience: 0
[1] BattlePetCompanionNameTimestamp: 0
[1] InteractSpellID: 0
[1] ScaleDuration: 100
[1] LooksLikeMountID: 0
[1] LooksLikeCreatureID: 0
[1] LookAtControllerID: -1
[1] TaxiNodesID: 0
[1] GuildGUID: Full: 0x0
[1] SilencedSchoolMask: 0
[1] NameplateAttachToGUID: Full: 0x0
[2] UpdateType: CreateObject2
[2] Object Guid: Full: 0x2030F43FA00F1C400068F70000DDF8A6 Creature/0 R3133/S26871 Map: 509 Entry: 15473 Low: 14547110
[2] Object Type: 5 (Unit)
[2] NoBirthAnim: False
[2] EnablePortals: False
[2] PlayHoverAnim: False
[2] HasMovementUpdate: True
[2] HasMovementTransport: False
[2] Stationary: False
[2] HasCombatVictim: False
[2] HasServerTime: False
[2] HasVehicleCreate: False
[2] HasAnimKitCreate: False
[2] HasRotation: False
[2] HasAreaTrigger: False
[2] HasGameObject: False
[2] HasSmoothPhasing: False
[2] ThisIsYou: False
[2] SceneObjCreate: False
[2] HasPlayerCreateData: False
[2] HasConversation: False
[2] MoverGUID: Full: 0x2030F43FA00F1C400068F70000DDF8A6 Creature/0 R3133/S26871 Map: 509 Entry: 15473 Low: 14547110
[2] MovementFlags: 0 (None)
[2] MovementFlags2: 0 (None)
[2] MovementFlags3: 0 (None)
[2] MoveTime: 856902151
[2] Position: X: -8540.537 Y: 1488.1968 Z: 32.43361
[2] Orientation: 4.310963153839111328
[2] Pitch: 0
[2] StepUpStartElevation: 0
[2] MoveIndex: 0
[2] Has Transport Data: False
[2] Has Fall Data: False
[2] HasSpline: False
[2] HeightChangeFailed: False
[2] RemoteTimeValid: False
[2] HasInertia: False
[2] WalkSpeed: 2.5
[2] RunSpeed: 8
[2] RunBackSpeed: 4.5
[2] SwimSpeed: 4.72221994400024414
[2] SwimBackSpeed: 2.5
[2] FlightSpeed: 7
[2] FlightBackSpeed: 4.5
[2] TurnRate: 3.141592741012573242
[2] PitchRate: 3.141592741012573242
[2] MovementForceCount: 0
[2] MovementForcesModMagnitude: 1
[2] HasMovementSpline: False
[2] PauseTimesCount: 0
[2] FieldFlags: 4 (UnitAll)
[2] EntryID: 15473
[2] DynamicFlags: 0
[2] Scale: 1
[2] DisplayID: 15692
[2] [0] NpcFlags: 0
[2] [1] NpcFlags: 0
[2] StateSpellVisualID: 0
[2] StateAnimID: 1716
[2] StateAnimKitID: 0
[2] StateWorldEffectsQuestObjectiveID: 0
[2] SpellOverrideNameID: 0
[2] Charm: Full: 0x0
[2] Summon: Full: 0x0
[2] CharmedBy: Full: 0x0
[2] SummonedBy: Full: 0x0
[2] CreatedBy: Full: 0x0
[2] DemonCreator: Full: 0x0
[2] LookAtControllerTarget: Full: 0x0
[2] Target: Full: 0x0
[2] BattlePetCompanionGUID: Full: 0x0
[2] BattlePetDBID: 0
[2] (ChannelData) SpellID: 0
[2] (ChannelData) (SpellVisual) SpellXSpellVisualID: 0
[2] (ChannelData) (SpellVisual) ScriptVisualID: 0
[2] SummonedByHomeRealm: 0
[2] Race: 0
[2] ClassId: 1
[2] PlayerClassId: 0
[2] Sex: 0
[2] DisplayPower: 1
[2] OverrideDisplayPowerID: 0
[2] Health: 2406
[2] [0] Power: 0
[2] [0] MaxPower: 0
[2] [1] Power: 0
[2] [1] MaxPower: 0
[2] [2] Power: 0
[2] [2] MaxPower: 5
[2] [3] Power: 0
[2] [3] MaxPower: 0
[2] [4] Power: 0
[2] [4] MaxPower: 0
[2] [5] Power: 0
[2] [5] MaxPower: 0
[2] [6] Power: 0
[2] [6] MaxPower: 0
[2] [0] PowerRegenFlatModifier: 0
[2] [0] PowerRegenInterruptedFlatModifier: 0
[2] [1] PowerRegenFlatModifier: 0
[2] [1] PowerRegenInterruptedFlatModifier: 0
[2] [2] PowerRegenFlatModifier: 0
[2] [2] PowerRegenInterruptedFlatModifier: 0
[2] [3] PowerRegenFlatModifier: 0
[2] [3] PowerRegenInterruptedFlatModifier: 0
[2] [4] PowerRegenFlatModifier: 0
[2] [4] PowerRegenInterruptedFlatModifier: 0
[2] [5] PowerRegenFlatModifier: 0
[2] [5] PowerRegenInterruptedFlatModifier: 0
[2] [6] PowerRegenFlatModifier: 0
[2] [6] PowerRegenInterruptedFlatModifier: 0
[2] MaxHealth: 2406
[2] Level: 30
[2] EffectiveLevel: 0
[2] ContentTuningID: 1006
[2] ScalingLevelMin: 30
[2] ScalingLevelMax: 30
[2] ScalingLevelDelta: 0
[2] ScalingFactionGroup: 0
[2] ScalingHealthItemLevelCurveID: 0
[2] ScalingDamageItemLevelCurveID: 0
[2] FactionTemplate: 1608
[2] (VirtualItems) [0] ItemID: 4991
[2] (VirtualItems) [0] SecondaryItemModifiedAppearanceID: 0
[2] (VirtualItems) [0] ItemAppearanceModID: 0
[2] (VirtualItems) [0] ItemVisual: 0
[2] (VirtualItems) [1] ItemID: 0
[2] (VirtualItems) [1] SecondaryItemModifiedAppearanceID: 0
[2] (VirtualItems) [1] ItemAppearanceModID: 0
[2] (VirtualItems) [1] ItemVisual: 0
[2] (VirtualItems) [2] ItemID: 0
[2] (VirtualItems) [2] SecondaryItemModifiedAppearanceID: 0
[2] (VirtualItems) [2] ItemAppearanceModID: 0
[2] (VirtualItems) [2] ItemVisual: 0
[2] Flags: 33280
[2] Flags2: 2097152
[2] Flags3: 0
[2] AuraState: 13631488
[2] [0] AttackRoundBaseTime: 2700
[2] [1] AttackRoundBaseTime: 2700
[2] BoundingRadius: 0.388999998569488525
[2] CombatReach: 1.5
[2] DisplayScale: 1
[2] CreatureFamily: 0
[2] CreatureType: 0
[2] NativeDisplayID: 15692
[2] NativeXDisplayScale: 1
[2] MountDisplayID: 0
[2] CosmeticMountDisplayID: 0
[2] StandState: 0
[2] PetTalentPoints: 0
[2] VisFlags: 0
[2] AnimTier: 0
[2] PetNumber: 0
[2] PetNameTimestamp: 0
[2] PetExperience: 0
[2] PetNextLevelExperience: 2147483647
[2] ModCastingSpeed: 1
[2] ModCastingSpeedNeg: 1
[2] ModSpellHaste: 1
[2] ModHaste: 1
[2] ModRangedHaste: 1
[2] ModHasteRegen: 1
[2] ModTimeRate: 1
[2] CreatedBySpell: 0
[2] EmoteState: 0
[2] BaseMana: 0
[2] SheatheState: 1
[2] PvpFlags: 1
[2] PetFlags: 0
[2] ShapeshiftForm: 0
[2] HoverHeight: 1
[2] MinItemLevelCutoff: 0
[2] MinItemLevel: 0
[2] MaxItemLevel: 0
[2] AzeriteItemLevel: 0
[2] WildBattlePetLevel: 0
[2] BattlePetCompanionExperience: 0
[2] BattlePetCompanionNameTimestamp: 0
[2] InteractSpellID: 0
[2] ScaleDuration: 100
[2] LooksLikeMountID: 0
[2] LooksLikeCreatureID: 0
[2] LookAtControllerID: -1
[2] TaxiNodesID: 0
[2] GuildGUID: Full: 0x0
[2] SilencedSchoolMask: 0
[2] NameplateAttachToGUID: Full: 0x0
[3] UpdateType: CreateObject2
[3] Object Guid: Full: 0x2030F43FA00F1C400068F700015DF8A6 Creature/0 R3133/S26871 Map: 509 Entry: 15473 Low: 22935718
[3] Object Type: 5 (Unit)
[3] NoBirthAnim: False
[3] EnablePortals: False
[3] PlayHoverAnim: False
[3] HasMovementUpdate: True
[3] HasMovementTransport: False
[3] Stationary: False
[3] HasCombatVictim: False
[3] HasServerTime: False
[3] HasVehicleCreate: False
[3] HasAnimKitCreate: False
[3] HasRotation: False
[3] HasAreaTrigger: False
[3] HasGameObject: False
[3] HasSmoothPhasing: False
[3] ThisIsYou: False
[3] SceneObjCreate: False
[3] HasPlayerCreateData: False
[3] HasConversation: False
[3] MoverGUID: Full: 0x2030F43FA00F1C400068F700015DF8A6 Creature/0 R3133/S26871 Map: 509 Entry: 15473 Low: 22935718
[3] MovementFlags: 0 (None)
[3] MovementFlags2: 0 (None)
[3] MovementFlags3: 0 (None)
[3] MoveTime: 856902151
[3] Position: X: -8536.235 Y: 1486.573 Z: 32.432724
[3] Orientation: 3.926990747451782226
[3] Pitch: 0
[3] StepUpStartElevation: 0
[3] MoveIndex: 0
[3] Has Transport Data: False
[3] Has Fall Data: False
[3] HasSpline: False
[3] HeightChangeFailed: False
[3] RemoteTimeValid: False
[3] HasInertia: False
[3] WalkSpeed: 2.5
[3] RunSpeed: 8
[3] RunBackSpeed: 4.5
[3] SwimSpeed: 4.72221994400024414
[3] SwimBackSpeed: 2.5
[3] FlightSpeed: 7
[3] FlightBackSpeed: 4.5
[3] TurnRate: 3.141592741012573242
[3] PitchRate: 3.141592741012573242
[3] MovementForceCount: 0
[3] MovementForcesModMagnitude: 1
[3] HasMovementSpline: False
[3] PauseTimesCount: 0
[3] FieldFlags: 4 (UnitAll)
[3] EntryID: 15473
[3] DynamicFlags: 0
[3] Scale: 1
[3] DisplayID: 15689
[3] [0] NpcFlags: 0
[3] [1] NpcFlags: 0
[3] StateSpellVisualID: 0
[3] StateAnimID: 1716
[3] StateAnimKitID: 0
[3] StateWorldEffectsQuestObjectiveID: 0
[3] SpellOverrideNameID: 0
[3] Charm: Full: 0x0
[3] Summon: Full: 0x0
[3] CharmedBy: Full: 0x0
[3] SummonedBy: Full: 0x0
[3] CreatedBy: Full: 0x0
[3] DemonCreator: Full: 0x0
[3] LookAtControllerTarget: Full: 0x0
[3] Target: Full: 0x0
[3] BattlePetCompanionGUID: Full: 0x0
[3] BattlePetDBID: 0
[3] (ChannelData) SpellID: 0
[3] (ChannelData) (SpellVisual) SpellXSpellVisualID: 0
[3] (ChannelData) (SpellVisual) ScriptVisualID: 0
[3] SummonedByHomeRealm: 0
[3] Race: 0
[3] ClassId: 1
[3] PlayerClassId: 0
[3] Sex: 0
[3] DisplayPower: 1
[3] OverrideDisplayPowerID: 0
[3] Health: 2406
[3] [0] Power: 0
[3] [0] MaxPower: 0
[3] [1] Power: 0
[3] [1] MaxPower: 0
[3] [2] Power: 0
[3] [2] MaxPower: 5
[3] [3] Power: 0
[3] [3] MaxPower: 0
[3] [4] Power: 0
[3] [4] MaxPower: 0
[3] [5] Power: 0
[3] [5] MaxPower: 0
[3] [6] Power: 0
[3] [6] MaxPower: 0
[3] [0] PowerRegenFlatModifier: 0
[3] [0] PowerRegenInterruptedFlatModifier: 0
[3] [1] PowerRegenFlatModifier: 0
[3] [1] PowerRegenInterruptedFlatModifier: 0
[3] [2] PowerRegenFlatModifier: 0
[3] [2] PowerRegenInterruptedFlatModifier: 0
[3] [3] PowerRegenFlatModifier: 0
[3] [3] PowerRegenInterruptedFlatModifier: 0
[3] [4] PowerRegenFlatModifier: 0
[3] [4] PowerRegenInterruptedFlatModifier: 0
[3] [5] PowerRegenFlatModifier: 0
[3] [5] PowerRegenInterruptedFlatModifier: 0
[3] [6] PowerRegenFlatModifier: 0
[3] [6] PowerRegenInterruptedFlatModifier: 0
[3] MaxHealth: 2406
[3] Level: 30
[3] EffectiveLevel: 0
[3] ContentTuningID: 1006
[3] ScalingLevelMin: 30
[3] ScalingLevelMax: 30
[3] ScalingLevelDelta: 0
[3] ScalingFactionGroup: 0
[3] ScalingHealthItemLevelCurveID: 0
[3] ScalingDamageItemLevelCurveID: 0
[3] FactionTemplate: 1608
[3] (VirtualItems) [0] ItemID: 4991
[3] (VirtualItems) [0] SecondaryItemModifiedAppearanceID: 0
[3] (VirtualItems) [0] ItemAppearanceModID: 0
[3] (VirtualItems) [0] ItemVisual: 0
[3] (VirtualItems) [1] ItemID: 0
[3] (VirtualItems) [1] SecondaryItemModifiedAppearanceID: 0
[3] (VirtualItems) [1] ItemAppearanceModID: 0
[3] (VirtualItems) [1] ItemVisual: 0
[3] (VirtualItems) [2] ItemID: 0
[3] (VirtualItems) [2] SecondaryItemModifiedAppearanceID: 0
[3] (VirtualItems) [2] ItemAppearanceModID: 0
[3] (VirtualItems) [2] ItemVisual: 0
[3] Flags: 33280
[3] Flags2: 2097152
[3] Flags3: 0
[3] AuraState: 13631488
[3] [0] AttackRoundBaseTime: 2700
[3] [1] AttackRoundBaseTime: 2700
[3] BoundingRadius: 0.388999998569488525
[3] CombatReach: 1.5
[3] DisplayScale: 1
[3] CreatureFamily: 0
[3] CreatureType: 0
[3] NativeDisplayID: 15689
[3] NativeXDisplayScale: 1
[3] MountDisplayID: 0
[3] CosmeticMountDisplayID: 0
[3] StandState: 0
[3] PetTalentPoints: 0
[3] VisFlags: 0
[3] AnimTier: 0
[3] PetNumber: 0
[3] PetNameTimestamp: 0
[3] PetExperience: 0
[3] PetNextLevelExperience: 2147483647
[3] ModCastingSpeed: 1
[3] ModCastingSpeedNeg: 1
[3] ModSpellHaste: 1
[3] ModHaste: 1
[3] ModRangedHaste: 1
[3] ModHasteRegen: 1
[3] ModTimeRate: 1
[3] CreatedBySpell: 0
[3] EmoteState: 0
[3] BaseMana: 0
[3] SheatheState: 1
[3] PvpFlags: 1
[3] PetFlags: 0
[3] ShapeshiftForm: 0
[3] HoverHeight: 1
[3] MinItemLevelCutoff: 0
[3] MinItemLevel: 0
[3] MaxItemLevel: 0
[3] AzeriteItemLevel: 0
[3] WildBattlePetLevel: 0
[3] BattlePetCompanionExperience: 0
[3] BattlePetCompanionNameTimestamp: 0
[3] InteractSpellID: 0
[3] ScaleDuration: 100
[3] LooksLikeMountID: 0
[3] LooksLikeCreatureID: 0
[3] LookAtControllerID: -1
[3] TaxiNodesID: 0
[3] GuildGUID: Full: 0x0
[3] SilencedSchoolMask: 0
[3] NameplateAttachToGUID: Full: 0x0
[4] UpdateType: CreateObject2
[4] Object Guid: Full: 0x2030F43FA00F1C400068F70001DDF8A6 Creature/0 R3133/S26871 Map: 509 Entry: 15473 Low: 31324326
[4] Object Type: 5 (Unit)
[4] NoBirthAnim: False
[4] EnablePortals: False
[4] PlayHoverAnim: False
[4] HasMovementUpdate: True
[4] HasMovementTransport: False
[4] Stationary: False
[4] HasCombatVictim: False
[4] HasServerTime: False
[4] HasVehicleCreate: False
[4] HasAnimKitCreate: False
[4] HasRotation: False
[4] HasAreaTrigger: False
[4] HasGameObject: False
[4] HasSmoothPhasing: False
[4] ThisIsYou: False
[4] SceneObjCreate: False
[4] HasPlayerCreateData: False
[4] HasConversation: False
[4] MoverGUID: Full: 0x2030F43FA00F1C400068F70001DDF8A6 Creature/0 R3133/S26871 Map: 509 Entry: 15473 Low: 31324326
[4] MovementFlags: 0 (None)
[4] MovementFlags2: 0 (None)
[4] MovementFlags3: 0 (None)
[4] MoveTime: 856902151
[4] Position: X: -8535.949 Y: 1484.2108 Z: 32.336636
[4] Orientation: 4.066617012023925781
[4] Pitch: 0
[4] StepUpStartElevation: 0
[4] MoveIndex: 0
[4] Has Transport Data: False
[4] Has Fall Data: False
[4] HasSpline: False
[4] HeightChangeFailed: False
[4] RemoteTimeValid: False
[4] HasInertia: False
[4] WalkSpeed: 2.5
[4] RunSpeed: 8
[4] RunBackSpeed: 4.5
[4] SwimSpeed: 4.72221994400024414
[4] SwimBackSpeed: 2.5
[4] FlightSpeed: 7
[4] FlightBackSpeed: 4.5
[4] TurnRate: 3.141592741012573242
[4] PitchRate: 3.141592741012573242
[4] MovementForceCount: 0
[4] MovementForcesModMagnitude: 1
[4] HasMovementSpline: False
[4] PauseTimesCount: 0
[4] FieldFlags: 4 (UnitAll)
[4] EntryID: 15473
[4] DynamicFlags: 0
[4] Scale: 1
[4] DisplayID: 15690
[4] [0] NpcFlags: 0
[4] [1] NpcFlags: 0
[4] StateSpellVisualID: 0
[4] StateAnimID: 1716
[4] StateAnimKitID: 0
[4] StateWorldEffectsQuestObjectiveID: 0
[4] SpellOverrideNameID: 0
[4] Charm: Full: 0x0
[4] Summon: Full: 0x0
[4] CharmedBy: Full: 0x0
[4] SummonedBy: Full: 0x0
[4] CreatedBy: Full: 0x0
[4] DemonCreator: Full: 0x0
[4] LookAtControllerTarget: Full: 0x0
[4] Target: Full: 0x0
[4] BattlePetCompanionGUID: Full: 0x0
[4] BattlePetDBID: 0
[4] (ChannelData) SpellID: 0
[4] (ChannelData) (SpellVisual) SpellXSpellVisualID: 0
[4] (ChannelData) (SpellVisual) ScriptVisualID: 0
[4] SummonedByHomeRealm: 0
[4] Race: 0
[4] ClassId: 1
[4] PlayerClassId: 0
[4] Sex: 0
[4] DisplayPower: 1
[4] OverrideDisplayPowerID: 0
[4] Health: 2406
[4] [0] Power: 0
[4] [0] MaxPower: 0
[4] [1] Power: 0
[4] [1] MaxPower: 0
[4] [2] Power: 0
[4] [2] MaxPower: 5
[4] [3] Power: 0
[4] [3] MaxPower: 0
[4] [4] Power: 0
[4] [4] MaxPower: 0
[4] [5] Power: 0
[4] [5] MaxPower: 0
[4] [6] Power: 0
[4] [6] MaxPower: 0
[4] [0] PowerRegenFlatModifier: 0
[4] [0] PowerRegenInterruptedFlatModifier: 0
[4] [1] PowerRegenFlatModifier: 0
[4] [1] PowerRegenInterruptedFlatModifier: 0
[4] [2] PowerRegenFlatModifier: 0
[4] [2] PowerRegenInterruptedFlatModifier: 0
[4] [3] PowerRegenFlatModifier: 0
[4] [3] PowerRegenInterruptedFlatModifier: 0
[4] [4] PowerRegenFlatModifier: 0
[4] [4] PowerRegenInterruptedFlatModifier: 0
[4] [5] PowerRegenFlatModifier: 0
[4] [5] PowerRegenInterruptedFlatModifier: 0
[4] [6] PowerRegenFlatModifier: 0
[4] [6] PowerRegenInterruptedFlatModifier: 0
[4] MaxHealth: 2406
[4] Level: 30
[4] EffectiveLevel: 0
[4] ContentTuningID: 1006
[4] ScalingLevelMin: 30
[4] ScalingLevelMax: 30
[4] ScalingLevelDelta: 0
[4] ScalingFactionGroup: 0
[4] ScalingHealthItemLevelCurveID: 0
[4] ScalingDamageItemLevelCurveID: 0
[4] FactionTemplate: 1608
[4] (VirtualItems) [0] ItemID: 4991
[4] (VirtualItems) [0] SecondaryItemModifiedAppearanceID: 0
[4] (VirtualItems) [0] ItemAppearanceModID: 0
[4] (VirtualItems) [0] ItemVisual: 0
[4] (VirtualItems) [1] ItemID: 0
[4] (VirtualItems) [1] SecondaryItemModifiedAppearanceID: 0
[4] (VirtualItems) [1] ItemAppearanceModID: 0
[4] (VirtualItems) [1] ItemVisual: 0
[4] (VirtualItems) [2] ItemID: 0
[4] (VirtualItems) [2] SecondaryItemModifiedAppearanceID: 0
[4] (VirtualItems) [2] ItemAppearanceModID: 0
[4] (VirtualItems) [2] ItemVisual: 0
[4] Flags: 33280
[4] Flags2: 2097152
[4] Flags3: 0
[4] AuraState: 13631488
[4] [0] AttackRoundBaseTime: 2700
[4] [1] AttackRoundBaseTime: 2700
[4] BoundingRadius: 0.388999998569488525
[4] CombatReach: 1.5
[4] DisplayScale: 1
[4] CreatureFamily: 0
[4] CreatureType: 0
[4] NativeDisplayID: 15690
[4] NativeXDisplayScale: 1
[4] MountDisplayID: 0
[4] CosmeticMountDisplayID: 0
[4] StandState: 0
[4] PetTalentPoints: 0
[4] VisFlags: 0
[4] AnimTier: 0
[4] PetNumber: 0
[4] PetNameTimestamp: 0
[4] PetExperience: 0
[4] PetNextLevelExperience: 2147483647
[4] ModCastingSpeed: 1
[4] ModCastingSpeedNeg: 1
[4] ModSpellHaste: 1
[4] ModHaste: 1
[4] ModRangedHaste: 1
[4] ModHasteRegen: 1
[4] ModTimeRate: 1
[4] CreatedBySpell: 0
[4] EmoteState: 0
[4] BaseMana: 0
[4] SheatheState: 1
[4] PvpFlags: 1
[4] PetFlags: 0
[4] ShapeshiftForm: 0
[4] HoverHeight: 1
[4] MinItemLevelCutoff: 0
[4] MinItemLevel: 0
[4] MaxItemLevel: 0
[4] AzeriteItemLevel: 0
[4] WildBattlePetLevel: 0
[4] BattlePetCompanionExperience: 0
[4] BattlePetCompanionNameTimestamp: 0
[4] InteractSpellID: 0
[4] ScaleDuration: 100
[4] LooksLikeMountID: 0
[4] LooksLikeCreatureID: 0
[4] LookAtControllerID: -1
[4] TaxiNodesID: 0
[4] GuildGUID: Full: 0x0
[4] SilencedSchoolMask: 0
[4] NameplateAttachToGUID: Full: 0x0

</details>

And Andorov's waypoints:

```
-- Pathing for Lieutenant General Andorov Entry: 15471
SET @NPC := XXXXXX;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `wander_distance`=0,`MovementType`=2,`position_x`=-8538.177,`position_y`=1486.0956,`position_z`=32.39054 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`visibilityDistanceType`,`auras`) VALUES (@NPC,@PATH,0,0,1,0,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,-8623.171,1470.4077,32.006413,0,0,0,0,100,0),
(@PATH,2,-8657.297,1506.1847,32.586697,0,0,0,0,100,0),
(@PATH,3,-8679.187,1535.1178,31.96736,0,0,0,0,100,0),
(@PATH,4,-8701.477,1561.7574,32.17472,0,0,0,0,100,0),
(@PATH,5,-8720.072,1580.9626,21.511324,0,0,0,0,100,0),
(@PATH,6,-8746.162,1603.494,21.613367,0,0,0,0,100,0),
(@PATH,7,-8780.431,1617.8787,21.455776,0,0,0,0,100,0),
(@PATH,8,-8823.478,1624.6688,19.80574,0,0,0,0,100,0),
(@PATH,9,-8855.329,1637.9473,19.790516,0,0,0,0,100,0),
(@PATH,10,-8870.721,1648.4009,21.511328,0,0,0,0,100,0),
(@PATH,11,-8870.721,1648.4009,21.511328,5.637413501739501953,0,0,0,100,0),
(@PATH+1,12,-8886.095,1598.713,21.4053,0,0,0,0,100,0),
(@PATH+1,13,-8904.383,1578.6167,21.511332,0,0,0,0,100,0),
(@PATH+1,14,-8920.576,1551.9479,21.407932,0,0,0,0,100,0),
(@PATH+1,15,-8939.951,1551.127,21.566868,0,0,0,0,100,0),
(@PATH+1,16,-8914.426,1546.6278,21.342258,0,0,0,0,100,0),
(@PATH+1,17,-8914.426,1546.6278,21.342258,3.029468297958374023,0,0,0,100,0),
(@PATH+1,18,-8939.951,1551.127,21.566868,2.877213954925537109,0,0,0,100,0);

```

**Comment by UltraNix** [comment]
@Maelthyrr @Gultask You can tets it again now.

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
image

**Comment by Maelthyrr** [comment]
Now Andorov start the entrance but he stop in the arena of Kurinaxx and start immediatly the event. So waves come until him.

WoWScrnShot_080722_233935

I'm also not sure about the formation. Andorov seems very far from these Kaldorei. @Gultask is it like this on retail ?

WoWScrnShot_080722_233853

**Comment by Gultask** [comment]
No, they should be nearby each other at all times. They also only attack enemies if you've started the event with him.
Here are some retail recordings (excuse the quality, I had to lower it)

https://user-images.githubusercontent.com/100873791/183319677-b9c1f1fe-a0ef-403b-9f56-0f681e4a75ad.mp4


https://user-images.githubusercontent.com/100873791/183319686-31df8a76-29ad-40ac-8943-cf0695bf3e31.mp4

I didn't include the end because he actually glitched out and didn't "end" the event and never offered to sell me supplies. I believe it's because I killed Rajaxx far away from him 😛

**Comment by UltraNix** [comment]
@acidmanifesto Should be okay.
@Gultask Please, test it again.

File: data/sql/updates/pending_db_world/rev_1659801375917048100.sql [hunk 3]
```diff
@@ -0,0 +1,48 @@
+--
+UPDATE `creature_template` SET `ScriptName`='npc_general_andorov' WHERE `entry`=15471;
+UPDATE `creature_template` SET `npcflag`=129, `speed_walk`=1.4, `speed_run`=1.4, `gossip_menu_id`=7047, `type_flags`=`type_flags`|0x08000000 WHERE  `entry`=15471;
+UPDATE `creature_template` SET `speed_walk`=1.4, `speed_run`=1.4 `entry`=15473;
```
Comment (Nefertumm) [inline data/sql/updates/pending_db_world/rev_1659801375917048100.sql:4]: missing where

**Comment by balleny** [comment]
> Because Andorov isn't related to Rajaxx waves (it is just an alternate start) and I didnt do anything with Andorov.
> 
> You can pull Rajaxx by talking to Andorov but they are not connected, you can skip the Andorov thing on retail altogether
> 
> I checked the code and the way the TC guys did it also doesn't match our research:
> 
> 1. the timer should be two minutes (they set it to 1 min)
> 2. Rajaxx doesnt say anything during the waves if they get pulled by the timer (it is some sort of dps check)
> 3. Waves are pulled in succession as soon as all members are dead, not on timer only
> 4. Rajaxx should only say stuff after the wave is defeated
> 
> All of the above works
> 
> What was missing:
> 
> * Andorov spawn at the start of the entrance after Kurinaxx dies
> * Talking to Andorov initiates a sequence where he walks to the arena and taunts Rajaxx and they trade a few lines
> * The waves target Andorov it seems when they are pulled
> 
> So the alternative start (through gossip) was missing

the timer should be 3 mins as of
https://wowwiki-archive.fandom.com/wiki/General_Rajaxx
and
https://classic.wowhead.com/guides/general-rajaxx-ruins-of-ahnqiraj-strategy

**Comment by Maelthyrr** [comment]
> > Because Andorov isn't related to Rajaxx waves (it is just an alternate start) and I didnt do anything with Andorov.
> > You can pull Rajaxx by talking to Andorov but they are not connected, you can skip the Andorov thing on retail altogether
> > I checked the code and the way the TC guys did it also doesn't match our research:
> > 
> > 1. the timer should be two minutes (they set it to 1 min)
> > 2. Rajaxx doesnt say anything during the waves if they get pulled by the timer (it is some sort of dps check)
> > 3. Waves are pulled in succession as soon as all members are dead, not on timer only
> > 4. Rajaxx should only say stuff after the wave is defeated
> > 
> > All of the above works
> > What was missing:
> > 
> > * Andorov spawn at the start of the entrance after Kurinaxx dies
> > * Talking to Andorov initiates a sequence where he walks to the arena and taunts Rajaxx and they trade a few lines
> > * The waves target Andorov it seems when they are pulled
> > 
> > So the alternative start (through gossip) was missing
> 
> the timer should be 3 mins as of https://wowwiki-archive.fandom.com/wiki/General_Rajaxx and https://classic.wowhead.com/guides/general-rajaxx-ruins-of-ahnqiraj-strategy

It's wrong. Tested on classic PTR.

**Comment by Maelthyrr** [comment]
@UltraNix when andorov reach the arena, I can't talk with him to start event with Rajaxx waves.

**Comment by balleny** [comment]
> > > Because Andorov isn't related to Rajaxx waves (it is just an alternate start) and I didnt do anything with Andorov.
> > > You can pull Rajaxx by talking to Andorov but they are not connected, you can skip the Andorov thing on retail altogether
> > > I checked the code and the way the TC guys did it also doesn't match our research:
> > > 
> > > 1. the timer should be two minutes (they set it to 1 min)
> > > 2. Rajaxx doesnt say anything during the waves if they get pulled by the timer (it is some sort of dps check)
> > > 3. Waves are pulled in succession as soon as all members are dead, not on timer only
> > > 4. Rajaxx should only say stuff after the wave is defeated
> > > 
> > > All of the above works
> > > What was missing:
> > > 
> > > * Andorov spawn at the start of the entrance after Kurinaxx dies
> > > * Talking to Andorov initiates a sequence where he walks to the arena and taunts Rajaxx and they trade a few lines
> > > * The waves target Andorov it seems when they are pulled
> > > 
> > > So the alternative start (through gossip) was missing
> > 
> > 
> > the timer should be 3 mins as of https://wowwiki-archive.fandom.com/wiki/General_Rajaxx and https://classic.wowhead.com/guides/general-rajaxx-ruins-of-ahnqiraj-strategy
> 
> It's wrong. Tested on classic PTR.

Classic PTR, which is very likely Season of Mastery - which is increased vanilla with increased difficulty.

**Comment by Maelthyrr** [comment]
> > > > Because Andorov isn't related to Rajaxx waves (it is just an alternate start) and I didnt do anything with Andorov.
> > > > You can pull Rajaxx by talking to Andorov but they are not connected, you can skip the Andorov thing on retail altogether
> > > > I checked the code and the way the TC guys did it also doesn't match our research:
> > > > 
> > > > 1. the timer should be two minutes (they set it to 1 min)
> > > > 2. Rajaxx doesnt say anything during the waves if they get pulled by the timer (it is some sort of dps check)
> > > > 3. Waves are pulled in succession as soon as all members are dead, not on timer only
> > > > 4. Rajaxx should only say stuff after the wave is defeated
> > > > 
> > > > All of the above works
> > > > What was missing:
> > > > 
> > > > * Andorov spawn at the start of the entrance after Kurinaxx dies
> > > > * Talking to Andorov initiates a sequence where he walks to the arena and taunts Rajaxx and they trade a few lines
> > > > * The waves target Andorov it seems when they are pulled
> > > > 
> > > > So the alternative start (through gossip) was missing
> > > 
> > > 
> > > the timer should be 3 mins as of https://wowwiki-archive.fandom.com/wiki/General_Rajaxx and https://classic.wowhead.com/guides/general-rajaxx-ruins-of-ahnqiraj-strategy
> > 
> > 
> > It's wrong. Tested on classic PTR.
> 
> Classic PTR, which is very likely Season of Mastery - which is vanilla with increased difficulty.

Mb, it's not on classic sorry, TBC classic and Shadowlands if I did no error. Check by @Nyeriah. Don't trust always guides and wiki. They can contain errors.

**Comment by UltraNix** [comment]
@Maelthyrr Should be okay now.

**Comment by Gultask** [comment]
Wrong Icon & Gossip text here, this is before starting the event:

image

Clicking the option also doesn't start the event.

He also seems like he didn't complete the waypoints? He's looking at the wall when he should actually be facing the other way:

image

**Comment by UltraNix** [comment]
@Maelthyrr Try now.

**Comment by Maelthyrr** [comment]
@UltraNix work now, but new issue:

- [ ] When the event with Rajaxx start. The first waves is pull automaticaly, and when the first is done, the second waves doesn't come.
- [ ] When Andorov come to Rajax gate, he does a short return on the way. Is it normal?

WoWScrnShot_081422_092614

**Comment by UltraNix** [comment]
@Maelthyrr Pathing corrected.
About waves - it works okay to me. After Quezz death, another pack of mobs are coming.

**Comment by Maelthyrr** [comment]
Will ask to another tester because to me, Queez reset and broke waves. Even with a DB clean.

**Comment by Gultask** [comment]
Same result as Maelthyrr.

1. Kill Kurinnaxx
2. start event, wait for Qeez to aggro to Andorov.
3. kill Qeez
4. Event resets, Qeez respawns, Andorov is uninteractable.

Kaldorei Elite aren't helping in the fight

Gossip option is wrong. It should actually be "Let's find out." instead of "I'd be happy to support you in the fight." ([source](https://youtu.be/5dQ1aaxtze8?t=1375))

**Review by acidmanifesto — APPROVED** [review]

**Comment by UltraNix** [comment]
@Gultask @Maelthyrr Should be okay now.

**Comment by Maelthyrr** [comment]
Everything work fine now. Big thanks @UltraNix :D 

- [X] Andorov and Kaldorei formation/pathway work without issues
- [X] Andorov wait in Kurinaxx arena
- [X] Player can launch Rajaxx event by talking with Andorov
- [X] Rajaxx waves work properly
- [X] At the ends, you can buy items from Andorov
- [X] Aura of commands work fine
- [X] If Andorov and Kaldorei are kill, it's cause any issues
