### PR TITLE
fix(Core/Spell): "Taming the Beast" hunter quests

### LINKED ISSUE #1073: Taming The Beast Quest line
##### EXPECTED BLIZZLIKE BEHAVIOUR:
When turning in the quest after using the taming rod the creature should despawn but does not.

##### CURRENT BEHAVIOUR:
When turning in the quest after using the taming rod the creature should despawn but does not. 
This causes new players doing the quest to get confused on why they can not tame the 2nd beast or 3rd one. This happened as a Tauren Hunter in the 2nd town. 
If the pet gets stuck some where it does not despawn breaking the quest for the player until he finds where the npc has gotten stuck then it returns to his side when found.

I am unsure if this happens to all the quest for hunters as there are multiple quests for this.

##### STEPS TO REPRODUCE THE PROBLEM:
Create Tauren Hunter
Quest till 2nd Town
Easiest way to get this to happen or see the issue is to turn on modify speed 5-10 while you do the quest.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/65982050-taming-the-beast-quest-line?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
- Ensure that the creature is only charmed after channeling the spell for the full time (as it was before it was charmed even when interrupting the spell).
- Force despawn after the creature is dismissed (either manually or when the spell runs out or when the creature is out of range). This ensures that it is correctly reset by respawning it at it's home position after 5 minutes.
- The creature should not despawn after the quest is turned in. Instead the player gets a qualified error message when trying to tame a new creature while still having the old one.

##### ISSUES ADDRESSED:
Closes #1073

##### TESTS PERFORMED:
- tested build on Ubuntu 16.04 / clang 7
- tested successfully in-game

##### HOW TO TEST THE CHANGES:
- Dwarf quests
  ```
  .q a 6085
  .go c id 1196
  
  .q a 6064
  .go c id 1126
  
  .q a 6084
  .go c id 1201
  ```

- Tauren quests
  ```
  .q a 6061
  .go c id 2956
  
  .q a 6087
  .go c id 2959
  
  .q a 6088
  .go c id 2970
  ```

- Orc / Troll quests
  ```
  .q a 6062
  .go c id 3099
  
  .q a 6083
  .go c id 3107
  
  .q a 6082
  .go c id 3126
  ```

- Night Elf quests
  ```
  .q a 6063
  .go c id 1998
  
  .q a 6101
  .go c id 2043
  
  .q a 6102
  .go c id 1996
  ```

- Draenei quests
  ```
  .q a 9591
  .go c id 17217
  
  .q a 9592
  .go c id 17374
  
  .q a 9593
  .go c id 17203
  ```

- Blood Elf quests
  ```
  .q a 9484
  .go c id 15650
  
  .q a 9486
  .go c id 15652
  
  .q a 9485
  .go c id 16353
  ```

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
Master
 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
All tested, perfect

File: src/server/game/Spells/Auras/SpellAuraEffects.cpp [hunk 1]
```diff
@@ -4997,7 +4997,7 @@ void AuraEffect::HandleAuraDummy(AuraApplication const* aurApp, uint8 mode, bool
         // AT REMOVE
         else
         {
-            if ((GetSpellInfo()->IsQuestTame()) && caster && caster->IsAlive() && target->IsAlive())
+            if ((GetSpellInfo()->IsQuestTame()) && caster && caster->IsAlive() && target->IsAlive() && aurApp->GetRemoveMode() != AURA_REMOVE_BY_CANCEL)
```
Comment (FrancescoBorzi) [inline src/server/game/Spells/Auras/SpellAuraEffects.cpp]: are we sure that this does not have side-effects on other spells? just wondering

Comment (Stoabrogga) [reply src/server/game/Spells/Auras/SpellAuraEffects.cpp]: yes, I'm sure, because this part of the code handles only those 18 different taming spells used for these quests:
https://github.com/azerothcore/azerothcore-wotlk/blob/0b3c5a434ac2cb001ffd59b4ee80f337aeb8189b/src/server/game/Spells/Auras/SpellAuraEffects.cpp#L5000-L5027

Comment (FrancescoBorzi) [reply src/server/game/Spells/Auras/SpellAuraEffects.cpp]: ok, very well then

**Comment by Mitradis** [comment]
stop using GM comands for test, just take normal quest! NOT WORKING!
https://i4.imageban.ru/out/2019/09/07/611fd5514202f2b607ea8034e52ceff9.jpg

**Comment by Stoabrogga** [comment]
GM commands have to be used to test issue fast. It is just important to always turn off GM mode, which I always do. And if you read my comments you would have learned that I did not implement the despawn (the creatures should not despawn!) but an appropriate error message for the player which also shows on your screenshot. Just dismiss the creature and everything's well.

**Comment by Mitradis** [comment]
this is called manual dispawn?
https://i.ibb.co/3Ndn8nG/image.png
this is a murder...

**Comment by Stoabrogga** [comment]
Sorry, but this happens if you despawn existing creatures via function call "DespawnOrUnsummon". If you find a better solution feel free to create a new PR, but this is the best I can offer, and it is definitely an improvement to the way it was before (creatures getting stuck where they are dismissed).

**Comment by Mitradis** [comment]
you work perfect, sory me.
you need just this:
creature->DespawnOrUnsummon(**1**);

**Comment by Stoabrogga** [comment]
Great, thanks! If you want, just create a PR for this, otherwise I can also create one tomorrow.

**Comment by Mitradis** [comment]
I do not know how, better you =)

**Comment by FrancescoBorzi** [comment]
@Mitradis it's quite easy actually: https://www.azerothcore.org/wiki/How-to-create-a-PR

**Comment by Stoabrogga** [comment]
Done. @Mitradis : Would be great if you could test PR #2271.
