### PR TITLE
fix(DB/EversongWoods): Remove sprint action from tigers

### LINKED ISSUE #12679: [Eversong Woods] <Springpaw Tigers> and <Elder Springpaw> using sprint wrongly
https://github.com/chromiecraft/chromiecraft/issues/3602

### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

They use sprint 

### Expected Blizzlike Behaviour

they shouldnt use sprint

See also the wow-head screenshots

### Source

TBCC PTR

### Steps to reproduce the problem

1. Go to Eversong woods.
2. Find the Springpaw Tigers and Springpaw Elders.
3. Listen to the sound they make when they aggro.

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c0ab2ab08e001ffce3c688eaf54301608af109a8

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by SoglaHash**
Tigers were using sprint. Expected tigers should not use sprint.

Closes #12679

## Changes Proposed:
-  Remove smartAI script action 22863 from the tigers that use it.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12679

## How to Test the Changes:

```
.go c 55919
.go c 55988
```
1. Use above listed commands to go to mobs
2. Aggro and see if they cast sprint on aggro

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1660252072288200163.sql [hunk 1]
```diff
@@ -0,0 +1,2 @@
+UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` IN (15651, 15652);
```
Comment (Nefertumm) [inline data/sql/updates/pending_db_world/rev_1660252072288200163.sql:1]: If these creatures already have smartai it's not needed.

File: data/sql/updates/pending_db_world/rev_1660252072288200163.sql [hunk 2]
```diff
@@ -0,0 +1,2 @@
...
+DELETE FROM `smart_scripts` WHERE (`entryorguid` IN (15651, 15652)) AND (`action_param1` = 22863);
```
Comment (Nefertumm) [inline data/sql/updates/pending_db_world/rev_1660252072288200163.sql:2]: Please add source_type to the condition or you could delete areatriggers or gob SAIs.

**Review by Nefertumm — CHANGES_REQUESTED** [review]

**Comment by Maelthyrr** [comment]
Hi, thanks for the PR. Work fine :)

**Review by Nefertumm — APPROVED** [review]
