### PR TITLE
fix(Core/Spells): fix PPM proc chance calculation for healing spells

### LINKED ISSUE #9028: Healing spells don't trigger Soul preserver or Omen of clarity procs
### Current Behaviour

Both clearcasting options from Soul Preserver or from the resto talent Omen of Clarity does not proc with healing spells at all.
OoC works with damage spells in moonkin. 

### Expected Behaviour

Healing spells should trigger both sources of clearcasting. 

### Source

Is it really necessary to provide the evidence? Both OoC and soul preserver confirmed by several other healers on the server. 

### Steps to reproduce the problem

1)Equip soul preserver or have a talent of Omen of Clarity active
2) try healing spells to proc

### Extra Notes

_No response_

### Customizations

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/686aafd57be6f1594a99634bade3756643fbf6f3

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-chromiecraft-smartstone](https://github.com/chromiecraft/mod-chromiecraft-smartstone)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-evade-logging](https://github.com/heyitsbench/mod-evade-logging)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-quests](https://github.com/azerothcore/mod-pvp-quests)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by blinkysc**
## Changes Proposed:
This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).

`CalcProcChance` only checked `GetDamageInfo()` to enter the PPM branch. Healing events only have `HealInfo`, so the PPM calculation was skipped and chance fell through to the base `Chance` field. For Omen of Clarity (PPM=3.5, Chance=0), this meant 0% proc rate on all healing spells.

Fix: also check `GetHealInfo()` to enter the PPM branch, guard `GetAttackTime()` since `DamageInfo` can be null for heals.

### AI-assisted Pull Requests

- [x] AI tools (e.g. ChatGPT, Claude, or similar) were used entirely or partially in preparing this pull request. Please specify which tools were used, if any.

Claude Code with AzerothMCP.

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/9028

## SOURCE:
The changes have been validated through:

## Tests Performed:
This PR has been:
- [x] Tested in-game by the author.

## How to Test the Changes:

1. Create a druid with Omen of Clarity talent
2. Cast healing spells (Healing Touch, Rejuvenation, etc.)
3. Verify Clearcasting (16870) procs at ~3.5 PPM rate
4. Verify melee OoC procs still work in feral forms

### CODE REVIEW

**Review by Gultask — APPROVED** [review]

File: src/server/game/Spells/Auras/SpellAuras.cpp [hunk 1]
```diff
@@ -2280,13 +2280,14 @@ float Aura::CalcProcChance(SpellProcEntry const& procEntry, ProcEventInfo& event
...
-        if (eventInfo.GetDamageInfo() && procEntry.ProcsPerMinute != 0)
+        if ((eventInfo.GetDamageInfo() || eventInfo.GetHealInfo()) && procEntry.ProcsPerMinute != 0)
         {
             SpellInfo const* procSpell = eventInfo.GetSpellInfo();
             uint32 attackSpeed = 0;
             if (!procSpell || procSpell->DmgClass == SPELL_DAMAGE_CLASS_MELEE || procSpell->IsRangedWeaponSpell())
             {
-                attackSpeed = caster->GetAttackTime(eventInfo.GetDamageInfo()->GetAttackType());
+                if (eventInfo.GetDamageInfo())
+                    attackSpeed = caster->GetAttackTime(eventInfo.GetDamageInfo()->GetAttackType());
```
Comment (Tereneckla) [inline src/server/game/Spells/Auras/SpellAuras.cpp:2290]: Is there a way for healing effects to not be spells or be a melee or ranged weapon spell?
If so, then this causes those effects to calc ppm with 0 chance (never happening)

If not, then this is not needed

Comment (blinkysc) [reply src/server/game/Spells/Auras/SpellAuras.cpp:2290]: Agreed think if (eventInfo.GetDamageInfo()) wasted line of code lol
