### PR TITLE
fix(Core): Correct fishing catch calculations

### LINKED ISSUE #22977: Fishing zone skill applied incorrectly
### Current Behaviour

Fishing success is being governed by the old (pre 3.1) 'minimum' fishing skill, but with that treated as the 'no-junk' fishing skill (i.e. 95 skill points too low).

### Expected Behaviour

Fishing success should only reach 100% at the minimum skill + 95 points, see e.g. [El's Anglin from after the 3.3.5 patch](https://web.archive.org/web/20100727193732/http://www.elsanglin.com/zone_base_fishing_skill.html) - you can see that the `skill_fishing_base_level` does match the 'base skill requirement' values there, but it's then used in the code as if it were the 'no-junk skill' level.

### Source

in GameObject.cpp the two 'zone_skill' checks here should instead be `(zone_skill + 95)` (parentheses only necessary on the second one)
```
                            if (skill < zone_skill)
                            {
                                chance = int32(pow((double)skill / zone_skill, 2) * 100);
                                if (chance < 1)
                                    chance = 1;
                            }
                            else
                                chance = 100;
```

### Steps to reproduce the problem

1. Set fishing to 1: .setskill 356 1
2. Give a basic Fishing Pole if needed: .additem 6256
3. Go to any fishing spot where the `skill_fishing_base_level` is -20 and the 'no-junk' level is 75 ([The Barrens (except Oasis), Blackfathom Deeps, Bloodmyst Isle, Darkshore, Darnassus, The Deadmines, Ghostlands, Ironforge, Loch Modan, Orgrimmar, Silverpine Forest, Stormwind City, Thunder Bluff, Undercity, The Wailing Caverns and Westfall](https://web.archive.org/web/20100727193732/http://www.elsanglin.com/zone_base_fishing_skill.html))
4. Fish: your non-junk catch rate will be much, much higher than the one expected by the formula [(current fishing skill as % of area's no-junk skill) ^ 2](https://web.archive.org/web/20100728110202/http://www.elsanglin.com/the_role_of_skill.html) (close to 0% at skill level 1, >50% at skill level 54)

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/d58d8692b11dee6d8b98ddf4ddc700355bbb8c28 2025-09-17 08:00:35 +0000 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 11

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by grace-of-hainaut**
## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #22977 
- I didn't raise this as an issue, but this change also makes fishing pools behave correctly for 3.3.0 and after (i.e. 100% catch rate)

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

[Fishing pools became 100% success rate in 3.3.0](https://warcraft.wiki.gg/wiki/Patch_3.3.0_(undocumented_changes)#Fishing)
[To fish without catching junk, you add 95 to the base skill requirement](https://web.archive.org/web/20100727193732/http://www.elsanglin.com/zone_base_fishing_skill.html)

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [x] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

The `no_miss_skill` fix is covered in the linked issue. For the fishing pools:
1. Set fishing to 1: .setskill 356 1
2. Give a basic Fishing Pole if needed: .additem 6256
3. Teleport to any high level area with fishing pools (I tested in Borean Tundra)
4. Verify that you always succeed when fishing in a pool

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by sudlud** [comment]
Following the source of the source link you provided:

https://web.archive.org/web/20091031133520/http://blue.mmo-champion.com:80/1/11155811788-2610-northrends-new-kaluak-fishing-derby.html

"Don't forget, in patch 3.3.0 you never catch trash from fishing pools, regardless of skill."

File: src/server/game/Entities/GameObject/GameObject.cpp [hunk 1]
```diff
@@ -1739,12 +1739,19 @@ void GameObject::Use(Unit* user)
                             if (!zone_skill)
                                 LOG_ERROR("sql.sql", "Fishable areaId {} are not properly defined in `skill_fishing_base_level`.", subzone);
 
+                            const int32 no_miss_skill = zone_skill + 95;
```
Comment (sudlud) [inline src/server/game/Entities/GameObject/GameObject.cpp]: const after type, also id like to have a comment here telling where the 95 comes from, e.g. which patch. Also variables should be named e.g. noMissSkill

**Comment by grace-of-hainaut** [comment]
> Following the source of the source link you provided:
> 
> https://web.archive.org/web/20091031133520/http://blue.mmo-champion.com:80/1/11155811788-2610-northrends-new-kaluak-fishing-derby.html
> 
> "Don't forget, in patch 3.3.0 you never catch trash from fishing pools, regardless of skill."

That's one of the things that this change is attempting to correct - at the moment in AC fishing pools are just treated the same as open water :)

File: src/server/game/Entities/GameObject/GameObject.cpp [hunk 2]
```diff
@@ -1739,12 +1739,19 @@ void GameObject::Use(Unit* user)
...
+
                             int32 skill = player->GetSkillValue(SKILL_FISHING);
 
                             int32 chance;
-                            if (skill < zone_skill)
+                            // fishing pool catches are 100%
+                            //TODO: find reasonable value for fishing hole search
+                            GameObject* ok = LookupFishingHoleAround(20.0f + CONTACT_DISTANCE);
```
Comment (sudlud) [inline src/server/game/Entities/GameObject/GameObject.cpp]: Should probably rename this now to fishingHole or something for better readability

File: src/server/game/Entities/GameObject/GameObject.cpp [hunk 3]
```diff
@@ -1753,7 +1760,7 @@ void GameObject::Use(Unit* user)
 
                             int32 roll = irand(1, 100);
 
-                            LOG_DEBUG("entities.gameobject", "Fishing check (skill: {} zone min skill: {} chance {} roll: {}", skill, zone_skill, chance, roll);
+                            LOG_DEBUG("entities.gameobject", "Fishing check (skill: {} zone min skill: {} chance {} roll: {})", skill, zone_skill, chance, roll);
```
Comment (sudlud) [inline src/server/game/Entities/GameObject/GameObject.cpp]: could add the noMissSkill here maybe

**Comment by sudlud** [comment]
Feel free to update the whole section to code standard (e.g. no braces on single line if) / correct variable naming if you want

File: src/server/game/Entities/GameObject/GameObject.cpp (hunk 1 above)
Comment (grace-of-hainaut) [reply src/server/game/Entities/GameObject/GameObject.cpp]: As regards the 95, I think it's been forever at far as I can tell. El's [pre 3.1 investigation](https://web.archive.org/web/20100920122347/http://elsanglin.com/the_role_of_skill_original.html) which mention being done "before patch 2.1" still gave 95 over base.

Comment (sudlud) [reply src/server/game/Entities/GameObject/GameObject.cpp]: Was just a thought, in the end it's pretty clear without a comment

**Comment by sudlud** [comment]
This will be a great improvement for fishing

File: src/server/game/Entities/GameObject/GameObject.cpp [hunk 4]
```diff
@@ -1731,20 +1731,28 @@ void GameObject::Use(Unit* user)
...
 
                             //provide error, no fishable zone or area should be 0
-                            if (!zone_skill)
+                            if (!zoneSkill)
                                 LOG_ERROR("sql.sql", "Fishable areaId {} are not properly defined in `skill_fishing_base_level`.", subzone);
 
+                            // no miss skill is zone skill + 95 since at least patch 2.1
+                            int32 const noMissSkill = zoneSkill + 95;
+
                             int32 skill = player->GetSkillValue(SKILL_FISHING);
```
Comment (sudlud) [inline src/server/game/Entities/GameObject/GameObject.cpp]:
```suggestion
                            int32 const skill = player->GetSkillValue(SKILL_FISHING);
```

**Comment by sudlud** [comment]
am i wrong or is the base skill requirement not present on ac as stated in the source from the issue https://web.archive.org/web/20100727193732/http://www.elsanglin.com/zone_base_fishing_skill.html ?

like beeing unable to cast the line at all if fishing skill is too low for an area

**Comment by heyitsbench** [comment]
> like beeing unable to cast the line at all if fishing skill is too low for an area

That isn't the case for Wrath. Being too low skill level will guarantee trash fishing loot, but you will never be unable to cast regardless of where you are. From your link:

> [Patch 3.1](https://web.archive.org/web/20100727193732/http://www.elsanglin.com/3_1_changes.html) changed the [role of skill](https://web.archive.org/web/20100727193732/http://www.elsanglin.com/the_role_of_skill.html). Every area of water now requires just fishing skill 1 to cast. However, there is still a certain skill required to fish without catching junk items.

**Comment by sudlud** [comment]
so you can fish any fishing hole anywhere in the map without getting trash at fishing level 1?

**Comment by heyitsbench** [comment]
> so you can fish any fishing hole anywhere in the map without getting trash at fishing level 1?

If you are fishing level 1, you can cast anywhere, but you're guaranteed to get trash in most places. As you level up, your chance to get actual non-trash loot increases (dependent on location). This not considering fishing pools, from the sound of this PR, it sounds like pools will always guarantee non-trash loot if I understand correctly.

**Comment by grace-of-hainaut** [comment]
> > so you can fish any fishing hole anywhere in the map without getting trash at fishing level 1?
> 
> If you are fishing level 1, you can cast anywhere, but you're guaranteed to get trash in most places. As you level up, your chance to get actual non-trash loot increases (dependent on location). This not considering fishing pools, from the sound of this PR, it sounds like pools will always guarantee non-trash loot if I understand correctly.

Just a slight correction - you're never actually guaranteed to get trash, it's just overwhelmingly likely in a lot of cases. The math AC uses is already correct for this, and means that for example in The Frozen Sea, with a no-miss skill of 575, at 100 you'd have a 3% chance of a successful catch.

File: src/server/game/Entities/GameObject/GameObject.cpp [hunk 5]
```diff
@@ -1731,34 +1731,40 @@ void GameObject::Use(Unit* user)
...
                                     chance = 1;
                             }
                             else
                                 chance = 100;
 
-                            int32 roll = irand(1, 100);
+                            int32 const roll = irand(1, 100);
 
-                            LOG_DEBUG("entities.gameobject", "Fishing check (skill: {} zone min skill: {} chance {} roll: {}", skill, zone_skill, chance, roll);
+                            LOG_DEBUG("entities.gameobject", "Fishing check (skill: {} zone min skill: {} no-miss skill: {}, chance {} roll: {})", skill, zoneSkill, noMissSkill, chance, roll);
```
Comment (sudlud) [inline src/server/game/Entities/GameObject/GameObject.cpp]:
```suggestion
                            LOG_DEBUG("entities.gameobject", "Fishing check (skill: {} zone min skill: {} no-miss skill: {} chance {} roll: {})", skill, zoneSkill, noMissSkill, chance, roll);
```

Comment (sudlud) [reply src/server/game/Entities/GameObject/GameObject.cpp]: last nitpick then it's good for merge
