### PR TITLE
fix(Core/Quests): Do not save queststatus for autocomplete quests . S…

### LINKED ISSUE #9150: Unacceptable quests appear in quest log after relog
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2313

You can accept cloth donation quests in capital cities. It seems that these quests get auto-accepted and appear in quest log after relog. See video.

https://user-images.githubusercontent.com/62797536/141462038-bd64d20f-9acc-4219-bd90-3a8317dade2b.mp4

Tester:

The issue is confirmed. If you will press `continue` button on unacceptable quest(you have to pass requirements to do it) and then will do relog - quest will appear in quest log

https://user-images.githubusercontent.com/85256266/141466451-9ea568c4-f28a-4de3-94f6-04d17e0d1913.mp4

### Expected Blizzlike Behaviour

Unacceptable quests should not appear in quest log

### Source

_No response_

### Steps to reproduce the problem

.go c 3422
.additem 14047 60 - runecloth
talk to npc
press continue
do relog

### Extra Notes

X

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/12e92b58082dfda8b73b50aa97b98b9479bb7629

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…ource: TrinityCore.

Fixes #9150

## Issues Addressed:

- Closes #9150
- Closes https://github.com/chromiecraft/chromiecraft/issues/2313

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

.go c 3422
.additem 14047 60 - runecloth
talk to npc
press continue
do relog

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/game/Entities/Player/PlayerQuest.cpp [hunk 1]
```diff
@@ -1447,10 +1447,12 @@ bool Player::CanShareQuest(uint32 quest_id) const
...
 void Player::SetQuestStatus(uint32 questId, QuestStatus status, bool update /*= true*/)
 {
-    if (sObjectMgr->GetQuestTemplate(questId))
+    if (Quest const* quest = sObjectMgr->GetQuestTemplate(questId))
     {
         m_QuestStatus[questId].Status = status;
-        m_QuestStatusSave[questId] = true;
+
+        if (quest->GetQuestMethod() && !quest->IsAutoComplete())
+            m_QuestStatusSave[questId] = true;
```
Comment (Nyeriah) [inline src/server/game/Entities/Player/PlayerQuest.cpp:1455]:
```suggestion
        if (quest->GetQuestMethod() && !quest->IsAutoComplete())
        {
            m_QuestStatusSave[questId] = true;
        }
```

**Review by Nyeriah — APPROVED** [review]
