### PR TITLE
fix(DB/Quest): prerequisites for Convert Ops quests

### LINKED ISSUE #6554: [Quest availaibility] Covert Ops - Alpha and Beta wrongfully available without Special Delivery for Gaxim
**Originally reported https://github.com/chromiecraft/chromiecraft/issues/996**

#### WHAT CLIENT DO YOU PLAY ON?
* [ ]  enGB
* [x]  enUS
* [ ]  other (specify)

##### FACTION
* [x]  Alliance
* [ ]  Horde

##### CONTENT PHASE:
* [ ]  Generic
* [x]  1-19
* [ ]  20-29
* [ ]  30-39
* [ ]  40-49
* [ ]  50-59

##### CURRENT BEHAVIOUR:
The quests "Covert Ops - Alpha" and "Covert Ops - Beta" are wrongly available after "Ineptitude + Chemicals = Fun" alone.
image

##### EXPECTED BLIZZLIKE BEHAVIOUR:
You should need both "Ineptitude + Chemicals = Fun" and "Special Delivery for Gaxim" completed in order to get these two quests.

##### SOURCE:
Both Alpha and Beta on wowhead says it requires both quests.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Have both "Ineptitude + Chemicals = Fun" and "Special Delivery for Gaxim".
2. Hand-in "Ineptitude + Chemicals = Fun" only.
3. Notice "Covert Ops - Alpha" and "Covert Ops - Beta" are available.

##### EXTRA NOTES:
Quest "Ineptitude + Chemicals = Fun": https://tbc.wowhead.com/quest=1074/ineptitude-chemicals-fun
Quest "Special Delivery for Gaxim": https://tbc.wowhead.com/quest=1077/special-delivery-for-gaxim
Quest "Covert Ops - Alpha": https://tbc.wowhead.com/quest=1079/covert-ops-alpha
Quest "Covert Ops - Beta": https://tbc.wowhead.com/quest=1080/covert-ops-beta

##### AC HASH/COMMIT:
[chromiecraft/azerothcore-wotlk@34da0cd](https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb)

##### OPERATING SYSTEM:
Ubuntu 20.04

##### MODULES:
* [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
* [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
* [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
* [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
* [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
* [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
* [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
* [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
* [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
* [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
* [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
* [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
* [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
* [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
* [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
* [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
* [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:
Client HD ground textures "Texturen_0.96"

##### SERVER:
ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99451423-quest-availaibility-covert-ops-alpha-and-beta-wrongfully-available-without-special-delivery-for-gaxim?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Efymer**
## Changes Proposed:
-  Adding `Ineptitude + Chemicals = Fun [1074]` and `Special Delivery for Gaxim [1077]`  as requisites in order to get `Covert Ops - Beta [1080]` and `Covert Ops - Alpha [1079]`

## Issues Addressed:

- Closes #6554
- Closes https://github.com/chromiecraft/chromiecraft/issues/996

## SOURCE:

- https://tbc.wowhead.com/quest=1079/covert-ops-alpha
- https://tbc.wowhead.com/quest=1080/covert-ops-beta

## Tests Performed:

- Adding and completing both quests needed in order to get both Convert Ops

## How to Test the Changes:

1. Check that you only get both Convert Ops if you completed `Ineptitude + Chemicals = Fun [1074]` AND `Special Delivery for Gaxim [1077]`

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Helias — APPROVED** [review]

File: data/sql/updates/pending_db_world/rev_1624549962929118300.sql [hunk 1]
```diff
@@ -0,0 +1,4 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1624549962929118300');
+
+UPDATE `quest_template_addon` SET `ExclusiveGroup` = -1074 WHERE (`ID` = 1074); -- Ineptitude + Chemicals = Fun [1074]
+UPDATE `quest_template_addon` SET `ExclusiveGroup` = -1074 WHERE (`ID` = 1077); -- Special Delivery for Gaxim [1077]
```
Comment (Helias) [inline data/sql/updates/pending_db_world/rev_1624549962929118300.sql:4]: you can even write 
```suggestion
UPDATE `quest_template_addon` SET `ExclusiveGroup` = -1074 WHERE `ID` IN (1074, 1077); -- Ineptitude + Chemicals = Fun [1074], Special Delivery for Gaxim [1077]
```

**Review by FrancescoBorzi — APPROVED** [review]
