### PR TITLE
Core/Spell: Add Dual Wield skill dependency to Dual Wield effect, sho…

### LINKED ISSUE #8882: Relog restore Shaman's Dual Wield talent
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2214

When equipping a 1-Handed Weapon as a Shaman you can equip that weapon into the Off-Hand Slot, even
without having any points in Dual Wield Talent from the Enhancement Tree. This works for all kinds of One-Handed Weapons as long as they are not Main-Hand specific.
upZbdjI

Tester:
The issue is confirmed. If you have one spec with Dual Wilde after respec you can do relog and tallent will apply to 2nd spec. 

https://user-images.githubusercontent.com/85256266/139756458-9100bc62-1d9c-4bc9-bf54-0efe496a3465.mp4

Fun part of this issue: even talents reset doesn't stop it.

https://user-images.githubusercontent.com/85256266/139759033-65488e43-a076-444b-a56e-34a5bd106843.mp4

### Expected Blizzlike Behaviour

Shamans should only be able to dual-wield while being specced into the Dual Wield Talent.

### Source

X

### Steps to reproduce the problem

.cast 63624 - add dual spec
apply Dual Wield in enhancemet tree
respec
relog

### Extra Notes

Checked also warrior with their Titan's grip tallent. Can't repeat this bug there.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…uld remove the skill properly when unlearning spell. Source: TrinityCore.

Fixes #8882

## Issues Addressed:

- Closes #8882
- Closes https://github.com/chromiecraft/chromiecraft/issues/2214

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

1. .cast 63624 - add dual spec
2. apply Dual Wield in enhancemet tree
3. respec
4. relog

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nefertumm — APPROVED** [review]

File: src/server/game/Spells/SpellMgr.cpp [hunk 1]
```diff
@@ -1473,20 +1473,31 @@ void SpellMgr::LoadSpellLearnSkills()
...
-                dbc_node.skill = entry->Effects[i].MiscValue;
-                dbc_node.step  = entry->Effects[i].CalcValue();
-                if (dbc_node.skill != SKILL_RIDING)
+                case SPELL_EFFECT_SKILL:
+                    dbc_node.skill = entry->Effects[i].MiscValue;
+                    dbc_node.step  = entry->Effects[i].CalcValue();
+                    if (dbc_node.skill != SKILL_RIDING)
+                        dbc_node.value = 1;
+                    else
+                        dbc_node.value = dbc_node.step * 75;
```
Comment (Nefertumm) [inline src/server/game/Spells/SpellMgr.cpp:1485]: Add brackets please

**Comment by Nefertumm** [comment]
Tested and working

File: src/server/game/Spells/SpellMgr.cpp (hunk 1 above)
Comment (Nyeriah) [inline src/server/game/Spells/SpellMgr.cpp:1485]:
```suggestion
                    if (dbc_node.skill != SKILL_RIDING)
                    {
                        dbc_node.value = 1;
                    }
                    else
                    {
                        dbc_node.value = dbc_node.step * 75;
                    }
```
