### PR TITLE
fix(Core/Spells): Glyph of Freezing Trap Applying Slow Incorrectly

### LINKED ISSUE #7183: Glyph of Freezing Trap Applying Slow Incorrectly
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1313

Glyph of Freezing Trap applies the slowing effect to the target upon activation.

Tester: confirmed. Applying the slow when the target is already frozen solid is of course entirely pointless. 

WoWScrnShot_073121_133413

### Expected Blizzlike Behaviour

The slow effect should be applied to the target when the Freezing Trap effect breaks.

This is confirmed by the glyph's tooltip: 

WoWScrnShot_073121_133253

### Source

As above.

### Steps to reproduce the problem

1. Inscribe "Glyph of Freezing Trap"
2. Apply Freezing Trap to a target
3. Observe that the slow effect from "Glyph of Freezing trap" applies instantly.
4. It should really apply after the trap breaks
5. ???
6. Profit.

### Extra Notes

I am Faravid the Tauren Hunter. Moo.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by ErnestoGonzalezC**
## Changes Proposed:
-  Activate slow effect only if trap effect is broken

## Issues Addressed:

- Closes #7183
- Closes https://github.com/chromiecraft/chromiecraft/issues/1313

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

1 - Inscribe "Glyph of Freezing Trap"
2 - Apply Freezing Trap to a target
3 - Wait for the trap effect to end
4 - Check that the slow effect is applied.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Is it possible to convert into a spellscript instead?

**Comment by pklloveyou** [comment]
Tested

**Comment by pklloveyou** [comment]
Tested

**Comment by ErnestoGonzalezC** [comment]
@Kitzunu I do not think that it's necessary

**Comment by Kitzunu** [comment]
Always better with scripts than core stuff

**Comment by ErnestoGonzalezC** [comment]
I have other things to do 😄

**Comment by ErnestoGonzalezC** [comment]
@Helias miss click

File: src/server/game/Spells/Auras/SpellAuras.cpp [hunk 1]
```diff
@@ -1742,6 +1742,12 @@ void Aura::HandleAuraSpecificMods(AuraApplication const* aurApp, Unit* caster, b
                 if (GetId() == 25771 && target->HasAura(61988) && !target->HasAura(61987))
                     target->RemoveAura(61988);
                 break;
+            case SPELLFAMILY_HUNTER:
+                // Glyph of Freezing Trap
+                if (GetSpellInfo()->SpellFamilyFlags[0] & 0x00000008)
+                    if (caster && caster->HasAura(56845))
+                        target->CastSpell(target, 61394, true);
```
Comment (FrancescoBorzi) [inline src/server/game/Spells/Auras/SpellAuras.cpp:1749]:
```suggestion
                if ((GetSpellInfo()->SpellFamilyFlags[0] & 0x00000008) && caster && caster->HasAura(56845))
                {
                    target->CastSpell(target, 61394, true);
                }
```

**Comment by pklloveyou** [comment]
tested

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
Approving as this is already an improvement, but I do agree with @Kitzunu . Scripts should always be preferred to core modifications.
