### PR TITLE
fix(Scripts/Achievement: Fixed Flirt With Disaster achievement. Sourc…

### LINKED ISSUE #10585: [Love is in the Air] Flirt With Disaster achievement not working
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2987

I got drunk and smashed, i use a perfume "Enchantress" Perfume from the event vendor, i throught a Handful of Rose Petals on Sraaz, then i kiss him and the achievement is not completed

Edit (@ishidinho): Same problem with the Horde achievement, too.

WoWScrnShot_020822_100438

### Expected Blizzlike Behaviour

Should i got the achievement completed if i follow all the steps i said before.

### Source

_No response_

### Steps to reproduce the problem

First i found the npc Sraaz walking around the center of Ironforge, then I got drunk and smashed, i used a perfume "Enchantress" Perfume from the event vendor, i throught a Handful of Rose Petals on Sraaz, then i kiss him and the achievement is not completed

Edit (@ishidinho):
1. `.go creature 31804`
2. Used [[Flagon of Mead]](https://wowgaming.altervista.org/aowow/?item=2594) three times until I got smashed
3. Put on [["Enchantress" Perfume]](https://wowgaming.altervista.org/aowow/?item=49857).
4. Used [[Handful of Rose Petals]](https://wowgaming.altervista.org/aowow/?item=22218) on [Jeremiah Payson](https://wowgaming.altervista.org/aowow/?npc=8403)
5. `/kiss` on Jeremiah Payson

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…e: TrinityCore.

Fixes #10585

## Issues Addressed:

- Closes #10585
- Closes https://github.com/chromiecraft/chromiecraft/issues/2987

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.event start 8`
`.go creature 31804`
`.mod drunk 100`
Put on [["Enchantress" Perfume]](https://wowgaming.altervista.org/aowow/?item=49857).
Used [[Handful of Rose Petals]](https://wowgaming.altervista.org/aowow/?item=22218) on [Jeremiah Payson](https://wowgaming.altervista.org/aowow/?npc=8403)
/kiss on Jeremiah Payson

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pklloveyou** [comment]
Tested

File: src/server/scripts/World/achievement_scripts.cpp [hunk 1]
```diff
@@ -251,6 +251,31 @@ class achievement_killed_exp_or_honor_target : public AchievementCriteriaScript
...
+    AURA_PERFUME_ENCHANTRESS       = 70234,
+    AURA_PERFUME_VICTORY           = 70233,
+};
+
+class achievement_flirt_with_disaster_perf_check : public AchievementCriteriaScript
+{
+    public:
+        achievement_flirt_with_disaster_perf_check() : AchievementCriteriaScript("achievement_flirt_with_disaster_perf_check") { }
+
+        bool OnCheck(Player* player, Unit* target, uint32 /*criteria_id*/) override
```
Comment (Nyeriah) [inline src/server/scripts/World/achievement_scripts.cpp:266]:
```suggestion
        bool OnCheck(Player* player, Unit* /*target*/, uint32 /*criteria_id*/) override
```

File: src/server/scripts/World/achievement_scripts.cpp [hunk 2]
```diff
@@ -251,6 +251,31 @@ class achievement_killed_exp_or_honor_target : public AchievementCriteriaScript
...
+                return false;
+
+            if (player->HasAura(AURA_PERFUME_FOREVER) || player->HasAura(AURA_PERFUME_ENCHANTRESS) || player->HasAura(AURA_PERFUME_VICTORY))
+                return true;
+
+            return false;
+        }
+};
+
+
```
Comment (Nyeriah) [inline src/server/scripts/World/achievement_scripts.cpp:278]:
```suggestion
```

**Review by Nyeriah — APPROVED** [review]
