### PR TITLE
fix(DB/Quest): Take No Chances

### LINKED ISSUE #2930: Quest Take No Chances
https://www.wowhead.com/quest=11913/take-no-chances

##### SMALL DESCRIPTION:

You can burn multiple times the same grain

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I guess each grain should be burned only once

##### CURRENT BEHAVIOUR:

You can finish he quest by burning the same grain multiple times

##### AC VERSION

https://github.com/azerothcore/azerothcore-wotlk/commit/5f2f68c500ea435348cd269d23da3a906eb0c388

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/91333906-quest-take-no-chances?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by vhiperdev**
## CHANGES PROPOSED:
- Grain should be burned only once
-  

## ISSUES ADDRESSED:
- Closes #2930 

## TESTS PERFORMED:
- Tested in game
-

## HOW TO TEST THE CHANGES:

- .go cre 97893
- .q add 11913
- use the quest item [Wendy's Torch] for burning and see that you won't be able to burn it endlessly

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1587846457474224200.sql [hunk 1]
```diff
@@ -1,8 +1,6 @@
 INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1587846457474224200');
 
 UPDATE `gameobject_template` SET `Data0`=1505 WHERE `entry`=188112;
-DELETE FROM `gameobject_template` WHERE `entry`=300184;
```
Comment (Kitzunu) [inline data/sql/updates/pending_db_world/rev_1587846457474224200.sql]: Why not remove these?
Do you play any part in the quest?

Comment (vhiperdev) [reply data/sql/updates/pending_db_world/rev_1587846457474224200.sql]: @Kitzunu Has been removed there is no such ID

Comment (Kitzunu) [reply data/sql/updates/pending_db_world/rev_1587846457474224200.sql]: image

The error you got was because those that you removed had an entry in gameobject_template_addon that did not get removed

Comment (vhiperdev) [reply data/sql/updates/pending_db_world/rev_1587846457474224200.sql]: @Kitzunu Correct now that I realize I'll update Thanks!

Comment (Kitzunu) [reply data/sql/updates/pending_db_world/rev_1587846457474224200.sql]: 👏

**Comment by merdlin** [comment]
I did the test, it works.

**Comment by Kitzunu** [comment]
Ty for the PR!
