### PR TITLE
fix(Core/GameObjects): Lockpicking timer on gameobjects should reset …

### LINKED ISSUE #8936: World doors doesn't have reset of lockpick(skill up) timer or this timer is too long
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2256

Currently the Armory Door's <https://wowgaming.altervista.org/aowow/?object=101851> Pick Lock <https://wowgaming.altervista.org/aowow/?spell=1804> level up is not resetting properly.

Tester:

The issue is confirmed. Regardless of time when door was lockpick rogues can't get skill up. Waited atleast 30 minutes. 

### Expected Blizzlike Behaviour

Doors should have comparable to boxes timers. As will be mention below something around 5m.

### Source

Wowwiki [Lockpicking (leveling)](https://wowwiki-archive.fandom.com/wiki/Lockpicking_(leveling)?oldid=2473900#Pickable_locks)
>Skill gains on doors not inside an instance are on a timer. They cannot be picked repeatedly for skill. A certain amount of time (about 5 min) must elapse before skill gains may be realized again. As of 5 August 2008, doors within instances must also be given time to cool down before getting another skill point, even if you reset the instance

[Youtube](https://youtu.be/XMKCTfAqgOg?t=129). Old video saying you while timer is resetting you can pickpocket 3 NPCs. It's taking definitely less than 30 min.

### Steps to reproduce the problem

.go c 45195 - tele to scarlet guard near doors
.setskill 633 175

### Extra Notes

Idk. Do you need all objects ids? Let me know.  Huge list tbh. Don't wanna do it without reason.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…after 10 minutes.

Fixes #8936

## Issues Addressed:

- Closes #8936
- Closes https://github.com/chromiecraft/chromiecraft/issues/2256

## Tests Performed:

- Not tested

## How to Test the Changes:

`.go c 45195` - tele to scarlet guard near doors
`.setskill 633 175`

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/game/Entities/GameObject/GameObject.cpp [hunk 1]
```diff
@@ -2846,3 +2862,18 @@ SpellInfo const* GameObject::GetSpellForLock(Player const* player) const
...
+{
+    int32 timer = GetMap()->IsDungeon() ? -1 : World::GetGameTimeMS() + 10 * MINUTE * IN_MILLISECONDS;
+    m_SkillupList[playerGuid] = timer;
+}
+
+bool GameObject::IsInSkillupList(ObjectGuid playerGuid) const
+{
+    for (auto const& itr : m_SkillupList)
+        if (itr.first == playerGuid)
+            return true;
```
Comment (Nefertumm) [inline src/server/game/Entities/GameObject/GameObject.cpp:2876]: brackets

File: src/server/game/Entities/GameObject/GameObject.h [hunk 2]
```diff
@@ -991,7 +983,7 @@ class GameObject : public WorldObject, public GridObject<GameObject>, public Mov
     bool        m_spawnedByDefault;
     uint32       m_cooldownTime;                         // used as internal reaction delay time store (not state change reaction).
     // For traps this: spell casting cooldown, for doors/buttons: reset time.
-    GuidList m_SkillupList;
+    std::unordered_map<ObjectGuid, int32> m_SkillupList;
```
Comment (Nefertumm) [inline src/server/game/Entities/GameObject/GameObject.h:986]: Why using int32 instead of uint32, so we don't have to static cast every time? Or are you using int32 for other reason?

**Review by Nefertumm — APPROVED** [review]

File: src/server/game/Entities/GameObject/GameObject.h (hunk 2 above)
Comment (UltraNix) [reply src/server/game/Entities/GameObject/GameObject.h:986]: Yes - look here https://github.com/azerothcore/azerothcore-wotlk/pull/9203/files#diff-386f154bdfb8cad4f9313fa7fb926ed996adbe1449933d53c01f88a666c7ff82R2868

**Comment by Nefertumm** [comment]
Tested but I couldn't get it working.
image

I lockpicked the door, waited 10+ minutes and tried again, but I didn't receive any skill up. You can see the timestamp on the picture.

**Comment by UltraNix** [comment]
@Nefertumm Please test again.

**Comment by Nefertumm** [comment]
Testing right now, updates shortly

**Comment by Nefertumm** [comment]
image
All good now!
