### PR TITLE
fix(DB/Gobject): Fixed Lever Spawn Position

### LINKED ISSUE #25586: Shadowfang Keep prison door switch is positioned incorrectly.
### Current Behaviour

The switch should be on the wall, but it's currently on the ground, and after operating it, the lever clips into the ground.

Image

### Expected Behaviour

The switch should be on the wall.

### Source

_No response_

### Steps to reproduce the problem

1.Enter the Shadowfang Keep instance.

2.Turn right, go upstairs, then go down the platform to the prison.

### Extra Notes

_No response_

### AC rev. hash/commit

commit 42c23a05a0654257597988d992b57292e45a8ec2

### Operating system

ubuntu22.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by EricksOliveira**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

### AI-assisted Pull Requests

> [!IMPORTANT]
> While the use of AI tools when preparing pull requests is not prohibited, contributors must clearly disclose when such tools have been used and specify the model involved.
> 
> Contributors are also expected to fully understand the changes they are submitting and must be able to explain and justify those changes when requested by maintainers.

- [ ] AI tools (e.g. ChatGPT, Claude, or similar) were used entirely or partially in preparing this pull request. Please specify which tools were used, if any.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/25586

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1777384200135224600.sql [hunk 1]
```diff
@@ -0,0 +1,8 @@
+--
+DELETE FROM `gameobject` WHERE (`id` = 18901) AND (`guid` IN (34006));
+INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`, `Comment`) VALUES
+(34006, 18901, 33, 0, 0, 1, 1, -249.213, 2123.05, 82.5795, 4.71239, -0.131892, -0.694697, -0.131892, 0.694697, 0, 100, 1, '', 0, NULL);
+
+DELETE FROM `gameobject` WHERE (`id` = 18900) AND (`guid` IN (32442));
+INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`, `Comment`) VALUES
+(32442, 18900, 33, 0, 0, 1, 1, -252.834, 2113.87, 82.5795, 4.71239, -0.131892, -0.694697, -0.131892, 0.694697, 0, 100, 1, '', 0, NULL);
```
Comment (heyitsbench) [inline data/sql/updates/pending_db_world/rev_1777384200135224600.sql]:
```suggestion
DELETE FROM `gameobject` WHERE (`id` = 18901) AND (`guid` IN (34006));
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`, `Comment`) VALUES
(34006, 18901, 33, 0, 0, 1, 1, -249.22014, 2123.1018, 82.80518, 6.0923543, -0.1318922, -0.6946964, -0.1318922, 0.69469833, 0, 100, 1, '', 43400, NULL);

DELETE FROM `gameobject` WHERE (`id` = 18900) AND (`guid` IN (32442));
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`, `Comment`) VALUES
(32442, 18900, 33, 0, 0, 1, 1, -252.69586, 2114.2246, 82.80518, 6.0923543, -0.1318922, -0.6946964, -0.1318922, 0.69469833, 0, 100, 1, '', 43400, NULL);

DELETE FROM `gameobject_addon` WHERE `guid` IN (32442, 34006);
INSERT INTO `gameobject_addon` (`guid`, `parent_rotation0`, `parent_rotation1`, `parent_rotation2`, `parent_rotation3`, `invisibilityType`, `invisibilityValue`) VALUES
(32442, 0, 0, -0.82658964, 0.56280506, 0, 0),
(34006, 0, 0, -0.82658964, 0.56280506, 0, 0);
```

**Comment by EricksOliveira** [comment]
There's another Lever. I hadn't seen the GUID 32444.

**Comment by heyitsbench** [comment]
> There's another Lever. I hadn't seen the GUID 32444.

```sql
DELETE FROM `gameobject` WHERE (`id` = 101811) AND (`guid` IN (32444));
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`, `Comment`) VALUES
(32444, 101811, 33, 0, 0, 1, 1, -245.59846, 2132.319, 82.80518, 6.0923543, -0.1318922, -0.6946964, -0.1318922, 0.69469833, 0, 100, 1, '', 43400, NULL);

DELETE FROM `gameobject_addon` WHERE `guid` = 32444;
INSERT INTO `gameobject_addon` (`guid`, `parent_rotation0`, `parent_rotation1`, `parent_rotation2`, `parent_rotation3`, `invisibilityType`, `invisibilityValue`) VALUES
(32444, 0, 0, -0.82658964, 0.56280506, 0, 0);
```

**Review by Nyeriah — APPROVED** [review]
