### PR TITLE
fix(Core/Socket): `CMSG_WARDEN_DATA` should not reset idle connections.

### LINKED ISSUE #14790: [server] Configuration does not work
### Current Behaviour

```
#
#    CloseIdleConnections
#        Description: Automatically close idle connections.
#                     SocketTimeOutTime and SocketTimeOutTimeActive determine when a connection is considered as idle.
#        Default:     1 - (enable, Automatically close idle connections)
#                     0 - (disable, Do not close idle connections)

CloseIdleConnections = 1

#
#    SocketTimeOutTime
#        Description: Time (in milliseconds) after which a connection being idle on the character
#                     selection screen is disconnected.
#        Default:     900000 - (15 minutes)

SocketTimeOutTime = 60000

#
#    SocketTimeOutTimeActive
#        Description: Time (in milliseconds) after which an idle connection is dropped while
#                     logged into the world.
#                     The client sends keepalive packets every 30 seconds. Values <= 30s are not recommended.
#        Default:     60000 - (1 minute)

SocketTimeOutTimeActive = 60000
```

According to the above settings, if you do not operate the game for 1 minute, you will automatically return to the role selection interface, but as long as the server is not closed, it will remain in the role selection interface forever and will not be disconnected
Maybe `SocketTimeOutTimeActive`  doesn't work

### Expected Blizzlike Behaviour

none

### Source

_No response_

### Steps to reproduce the problem

none

### Extra Notes

_No response_

### AC rev. hash/commit

484cb1d01b2c9b762881a50544dc8c807ad99b70

### Operating system

Ubuntu20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #14790

## Issues Addressed:

- Closes #14790

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

Set `SocketTimeOutTime` and `SocketTimeOutTimeActive` to `60000` in `worldserver.conf`
Login with your username and password, but do not login into the game (stay at character selection screen)
Wait 1 minute until got disconnected

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/game/Server/WorldSocket.cpp [hunk 1]
```diff
@@ -385,7 +385,10 @@ WorldSocket::ReadDataHandlerResult WorldSocket::ReadDataHandler()
     }
 
     // Our Idle timer will reset on any non PING opcodes on login screen, allowing us to catch people idling.
-    _worldSession->ResetTimeOutTime(false);
+    if (packetToQueue->GetOpcode() != CMSG_WARDEN_DATA)
```
Comment (Kitzunu) [inline src/server/game/Server/WorldSocket.cpp:388]: is this not better set within ResetTimeOutTime()?

Comment (Kitzunu) [reply src/server/game/Server/WorldSocket.cpp:388]: to catch every instance where we call ResetTimeOutTime

Comment (UltraNix) [reply src/server/game/Server/WorldSocket.cpp:388]: ?? I don't understand.

Comment (Kitzunu) [reply src/server/game/Server/WorldSocket.cpp:388]: dont worry, I was wrong anyways!

**Review by Kitzunu — APPROVED** [review]
