### PR TITLE
fix(DB/Creature): Set respawn to 15s for Soul Fragments in the Shrine of Lost Souls

### LINKED ISSUE #20991: Soul Fragments in the Shrine of Lost Souls do not seem to respawn.
### Current Behaviour

The Angered, Suffering, and Hungering Soul Fragments in the Shrine of Lost Souls in Black Temple do not respawn.

### Expected Blizzlike Behaviour

They should respawn and quite fast until the Reliquary of Souls is defeated.

### Source

TBC strategy guides

### Steps to reproduce the problem

1. Black Temple.  .go xyz 533.50 41.4 113.5 564
2. Clear up to Reliquary.
3. Enter their hallway.
4. Kill mobs.
5. Observe they stay dead.

### Extra Notes

https://github.com/chromiecraft/chromiecraft/issues/7411

_No response_

### AC rev. hash/commit

[ceefd89a06a0](https://github.com/azerothcore/azerothcore-wotlk/commit/08d5861a519a0dc85269f76458b55dbcb77bcda0)

### Operating system

Win 10 x64

### Custom changes or Modules

None

### PR DESCRIPTION
**Pull request by Exitare**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/7411
- Closes #20991

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

[Video1](https://www.youtube.com/watch?v=_BD0vhuWbVc )  2:00 minutes in. (says 20-30 secs)
[Video2](https://www.youtube.com/watch?v=19UA_Ae5hbU) 7:30 minutes in (says 15 seconds)
[Guide](https://www.icy-veins.com/tbc-classic/reliquary-of-souls-reliquary-of-the-lost-guide-strategy-abilities-loot?utm_source=chatgpt.com) States 15 seconds

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by TheSCREWEDSoftware — CHANGES_REQUESTED** [review]
When updating or deleting creatures make sure you're being specifc what's being changed. 

You can check the [SQL Standards](https://www.azerothcore.org/wiki/sql-standards).

Since you're updating 3 creatures. Make sure you're checking for group of GUIDS AND ID1.



Don't forget to add 1 newline at the end.

File: data/sql/updates/pending_db_world/rev_1734751988808151700.sql [hunk 1]
```diff
@@ -0,0 +1,14 @@
+-- Angered, Suffering & Hungering Soul Fragment respawn
+UPDATE `creature` SET `spawntimesecs` = 15 WHERE guid IN (
```
Comment (sudlud) [inline data/sql/updates/pending_db_world/rev_1734751988808151700.sql]: Missing backticks on guid and id1.
Missing new line at end of file.

Comment (Exitare) [reply data/sql/updates/pending_db_world/rev_1734751988808151700.sql]: I am not even done...

**Comment by sudlud** [comment]
In this special case where all guids are sequential you can optimize the guid part to:

```sql
WHERE (`guid` BETWEEN 148424 AND 148488)
```

**Review by sudlud — CHANGES_REQUESTED** [review]
Please update the pr according to my last comment.

**Review by sudlud — APPROVED** [review]

**Comment by TheSCREWEDSoftware** [comment]
Running 

```sql
SELECT * FROM `creature` WHERE (`guid` BETWEEN 148424 AND 148488) and `id1` in (23398, 23399, 23401);
```

I get the result  the 65 results below @Exitare these are the ones you trying to change correct? If yes, than is also good @sudlud. I ran the query of his SQL and they are all respawning at 15 seconds.

<details>

<summary>Click me to see GUIDs and ID1</summary>

| guid   | id1   |
|--------|-------|
| 148424 | 23398 |
| 148425 | 23398 |
| 148426 | 23398 |
| 148427 | 23399 |
| 148428 | 23398 |
| 148429 | 23398 |
| 148430 | 23401 |
| 148431 | 23398 |
| 148432 | 23398 |
| 148433 | 23398 |
| 148434 | 23398 |
| 148435 | 23401 |
| 148436 | 23401 |
| 148437 | 23398 |
| 148438 | 23401 |
| 148439 | 23398 |
| 148440 | 23398 |
| 148441 | 23398 |
| 148442 | 23398 |
| 148443 | 23398 |
| 148444 | 23398 |
| 148445 | 23398 |
| 148446 | 23398 |
| 148447 | 23399 |
| 148448 | 23398 |
| 148449 | 23399 |
| 148450 | 23398 |
| 148451 | 23398 |
| 148452 | 23398 |
| 148453 | 23398 |
| 148454 | 23398 |
| 148455 | 23398 |
| 148456 | 23398 |
| 148457 | 23398 |
| 148458 | 23401 |
| 148459 | 23398 |
| 148460 | 23398 |
| 148461 | 23398 |
| 148462 | 23401 |
| 148463 | 23401 |
| 148464 | 23401 |
| 148465 | 23398 |
| 148466 | 23398 |
| 148467 | 23398 |
| 148468 | 23398 |
| 148469 | 23398 |
| 148470 | 23398 |
| 148471 | 23398 |
| 148472 | 23398 |
| 148473 | 23399 |
| 148474 | 23401 |
| 148475 | 23398 |
| 148476 | 23398 |
| 148477 | 23398 |
| 148478 | 23398 |
| 148479 | 23398 |
| 148480 | 23398 |
| 148481 | 23399 |
| 148482 | 23398 |
| 148483 | 23398 |
| 148484 | 23398 |
| 148485 | 23398 |
| 148486 | 23401 |
| 148487 | 23398 |
| 148488 | 23398 |

</details>

**Review by TheSCREWEDSoftware — APPROVED** [review]
