### PR TITLE
fix(Scripts/MagistersTerrace) Add 5s Vexallus Pure Energy

### LINKED ISSUE #21236: [Magisters Terrace] Vexallus doesn't summon Pure Energy at 25%
### Current Behaviour

[Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744) doesn't summon [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) at 25%

### Expected Blizzlike Behaviour

[Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744) should summon [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) at 25%

### Source

[TBC Classic Normal Duo](https://youtu.be/F9HoLnDjYXA?t=575) Starting from 9:38, you can see [Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744) shrink 5 times and summons [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) at 85,70,55,40,25% at 9:40, 9:53, 10:02, 10:10 and 10:15.

[TBC Classic Heroic](https://youtu.be/i3XUDMpyBqM?t=500) Starting from 8:22 , [Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744) shrink 5 times and summons [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) each time.

### Steps to reproduce the problem

1. .go c id 24744
2. .damage 21600 (in Normal mode) or .damage 29300 (in Heroic Mode) on [Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744)
3. repeat step 2 until you reach 25%

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. 7725610ff3e6 2025-01-21 10:44:39 +0100 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 11 x64

### Custom changes or Modules

_No response_

### LINKED ISSUE #21237: [Magisters Terrace] Vexallus doesn't have cooldown between each Pure Energy summoning phase
### Current Behaviour

[Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744) doesn't have cooldown between each [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) summoning phase.

### Expected Blizzlike Behaviour

[Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744) should have ~5s cooldown between each [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) summoning phase.

### Source

[TBC Classic Heroic](https://youtu.be/i3XUDMpyBqM?t=500) Starting from 8:22, you can see even if [Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744) reaches the next threshold, he doesn't summon [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) unless 5s has passed.

[Wotlk Classic](https://youtu.be/DP1ky6f_VJ0) at 0:31 , [Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744) summon 2 [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) for reaching 70% then at 0:37 he summons [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) for reaching 55%, at 0:42 he summons [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) for reaching 40% threshold even while he is already at 31%, at 0;44 he reaches the 25% threshold but he summons [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) at 0:47 as he had to wait ~5 seconds.

### Steps to reproduce the problem

1. .go c id 24744
2. .damage 21600 (in Normal mode) or .damage 29300 (in Heroic Mode) on [Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744)
3. Use .damage again on [Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744) after 1 second from him summoning [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745).

### Extra Notes

Should also make sure that [Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744) does not skip summoning [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) for any phase  if the next threshold was reached while the previous summoning was waiting for the cooldown to go off.

I hope someone can verify this behavior more in Cata Classic and check if [Overload](https://wowgaming.altervista.org/aowow/?spell=44353) has some kind of CD before starting casting at after reaching 20?% health

### AC rev. hash/commit

AzerothCore rev. 7725610ff3e6 2025-01-21 10:44:39 +0100 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 11 x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by blinkysc**
Add 5s between NPC_PURE_ENERGY

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #21237
- Closes #21236

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. .go c id 24744
2. .damage 21600 (in Normal mode) or .damage 29300 (in Heroic Mode) on [Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744)
3. Use .damage again on [Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744) after 1 second from him summoning [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745).

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Use the scheduler instead and check if the group is scheduled

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 1]
```diff
@@ -51,24 +51,34 @@ enum Misc
...
-    boss_vexallus(Creature* creature) : BossAI(creature, DATA_VEXALLUS) { }
+    boss_vexallus(Creature* creature) : BossAI(creature, DATA_VEXALLUS), _energyCooldown(false) { }
 
     void Reset() override
     {
         _Reset();
+        _energyCooldown = false;
 
-        ScheduleHealthCheckEvent({ 85, 70, 55, 40 }, [&]
+        ScheduleHealthCheckEvent({ 85, 70, 55, 40 , 25}, [&]
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:61]:
```suggestion
        ScheduleHealthCheckEvent({ 85, 70, 55, 40 , 25 }, [&]
```

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 2]
```diff
@@ -51,24 +51,34 @@ enum Misc
...
-    boss_vexallus(Creature* creature) : BossAI(creature, DATA_VEXALLUS) { }
+    boss_vexallus(Creature* creature) : BossAI(creature, DATA_VEXALLUS), _energyCooldown(false) { }
 
     void Reset() override
     {
         _Reset();
+        _energyCooldown = false;
 
-        ScheduleHealthCheckEvent({ 85, 70, 55, 40 }, [&]
+        ScheduleHealthCheckEvent({ 85, 70, 55, 40 , 25 }, [&]
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:61]:
```suggestion
        ScheduleHealthCheckEvent({ 85, 70, 55, 40, 25 }, [&]
```

**Review by Nyeriah — APPROVED** [review]

**Comment by amed80** [comment]
If Vexallus reaches the next threshold while still during the 5 seconds cooldown , he will not spawn [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) after the 5 seconds are over, he should.
