### PR TITLE
fix(Scripts/Spells): Raise Ally now properly handles target check

### LINKED ISSUE #23358: [Spells/DK] Raise Ally does not allow targeting
### Current Behaviour

Raise Ally, when used on a non-ghost, dead friendly player, reports "Invalid target"

### Expected Behaviour

Raise Ally shoud work on a non-ghost, dead friendly player

### Source

_No response_

### Steps to reproduce the problem

1. Create DK char
2. .levelup 80
3. learn all spells from trainer
4. Create another char on another account
5. group 2nd char
6. .die on 2nd char
7. cast Raise Ally spell on 2nd char

### Extra Notes

_No response_

### AC rev. hash/commit

 AzerothCore rev. 2a78a1788fe6 2025-10-22 18:49:08 +0200 (master branch) (Unix, Release, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 1.
Server uptime: 21 minute(s) 37 second(s)
Update time diff: 1ms. Last 500 diffs summary:
|- Mean: 3ms
|- Median: 1ms
|- Percentiles (95, 99, max): 8ms, 9ms, 16ms
Using SSL version: OpenSSL 3.5.1 1 Jul 2025 (library: OpenSSL 3.5.1 1 Jul 2025)
Using Boost version: 1.83.0
Using CMake version: 3.31.6
Using MySQL version: 80406
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.12.48+deb13-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in ./data/maps. Total size: 291014951 bytes
vmaps directory located in ./data/vmaps. Total size: 658130721 bytes
mmaps directory located in ./data/mmaps. Total size: 2191333640 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.14-dev
Latest LoginDatabase update: acore_cms_subscriptions.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: z_filter_disabled_and_trash.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-account-achievements
|- mod-account-mounts
|- mod-account-vanity-pets
|- mod-ah-bot
|- mod-anticheat
|- mod-solo-lfg
|- mod-solocraft
|- mod-transmog

### Operating system

Linux

### Custom changes or Modules

|- mod-account-achievements
|- mod-account-mounts
|- mod-account-vanity-pets
|- mod-ah-bot
|- mod-anticheat
|- mod-solo-lfg
|- mod-solocraft
|- mod-transmog

### PR DESCRIPTION
**Pull request by lucafolloni**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #23358

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [x] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by lucafolloni** [comment]
Screenshot 2025-10-16 175056

**Comment by Nyeriah** [comment]
Your IDE is adding lots of random formatting changes, please remove them and keep just the code to be merged

**Comment by lucafolloni** [comment]
Do you have a linter I can use?

**Comment by lucafolloni** [comment]
Should be ok, now

File: src/server/scripts/Spells/spell_dk.cpp [hunk 1]
```diff
@@ -152,7 +152,12 @@ class spell_dk_raise_ally : public SpellScript
...
     {
-        Player* unitTarget = GetHitPlayer();
+        ObjectGuid targetGuid = GetSpell()->m_targets.GetUnitTargetGUID();
+        if (!targetGuid)
+            return SPELL_FAILED_BAD_TARGETS;
+
+        Unit* target = ObjectAccessor::GetUnit(*(GetSpell()->GetCaster()), targetGuid);
+        Player* unitTarget = target ? target->ToPlayer() : nullptr;
         if (!unitTarget)
             return SPELL_FAILED_BAD_TARGETS;
```
Comment (sogladev) [inline src/server/scripts/Spells/spell_dk.cpp]:
```suggestion
        Unit* unitTarget = GetExplTargetUnit();
        if (!unitTarget)
            return SPELL_FAILED_BAD_TARGETS;

```

File: src/server/scripts/Spells/spell_dk.cpp [hunk 2]
```diff
@@ -152,7 +152,12 @@ class spell_dk_raise_ally : public SpellScript
 
     SpellCastResult CheckCast()
     {
-        Player* unitTarget = GetHitPlayer();
+        ObjectGuid targetGuid = GetSpell()->m_targets.GetUnitTargetGUID();
+        if (!targetGuid)
+            return SPELL_FAILED_BAD_TARGETS;
+
+        Unit* target = ObjectAccessor::GetUnit(*(GetSpell()->GetCaster()), targetGuid);
+        Player* unitTarget = target ? target->ToPlayer() : nullptr;
```
Comment (sogladev) [inline src/server/scripts/Spells/spell_dk.cpp]:
```suggestion
        Unit* unitTarget = GetExplTargetUnit();
```

Comment (sogladev) [reply src/server/scripts/Spells/spell_dk.cpp]: This can be simplified

`GetExplTargetUnit()` to get the target ptr directly. Set here: https://github.com/lucafolloni/azerothcore-wotlk/blob/21145903f56d8d6e6f433a896e6c5f614a3791ca/src/server/game/Spells/Spell.cpp#L239

from spell DBC `Effect 0: Id 3 (SPELL_EFFECT_DUMMY)
BasePoints = 46619
Targets (57, 0) (TARGET_UNIT_TARGET_RAID, NO_TARGET)` and `SPELL_ATTR3_ONLY_ON_PLAYER` This will alway be a player here

Comment (lucafolloni) [reply src/server/scripts/Spells/spell_dk.cpp]: @sogladev thanks!
