### PR TITLE
fix(Scripts/Temple of Ahn Qiraj): Skeram should cast True Fulfillment…

### LINKED ISSUE #12713: [AQ40] Prophet Skeram - True Fulfillment
### Current Behaviour

1. Spell is cast even if the player is running solo.
2. Targets random players.

### Expected Blizzlike Behaviour

1. It should not be cast if the player is running solo.
Warlock & Hunter pets being present will allow the boss to cast True Fulfillment

2. It should target the closest player instead of a random one.

### Source

https://youtu.be/jj7NRJoMAVs solo run
https://youtu.be/bVFt9VraT58?t=38 hunter gets MC'd regardless of running solo
https://youtu.be/xLm4Joa5Roc?t=42 the targeted player is inside the boss' circle

>The rogues should also stand inside Skeram in front of the tank. The rogues will always be mind-controlled before the tank if this is done correctly. ([source](https://wowpedia.fandom.com/wiki/The_Prophet_Skeram))

### Steps to reproduce the problem

1. `.go xyz -8295.55 2102.6 118.2 531 3.6` with 1 character
2. engage boss, see if True Fulfillment is being cast
3. `.go xyz -8295.55 2102.6 118.2 531 3.6` with 2 characters
4. see if the player closest to the boss is mind controlled

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/3771a7120d962bbe7cca70a1c1440b4acba440a5

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
… on closest non-tank player.

Fixes #12713

## Issues Addressed:

- Closes #12713

## Tests Performed:

- Not tested.

## How to Test the Changes:

`.go xyz -8295.55 2102.6 118.2 531 3.6` with 1 character
engage boss, see if True Fulfillment is being cast
`.go xyz -8295.55 2102.6 118.2 531 3.6` with 2 characters
see if the player closest to the boss is mind controlled

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
It works 👍

**Review by IntelligentQuantum — APPROVED** [review]

**Review by Nyeriah — APPROVED** [review]

File: src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_skeram.cpp [hunk 1]
```diff
@@ -146,9 +146,7 @@ struct boss_skeram : public BossAI
                     events.ScheduleEvent(EVENT_ARCANE_EXPLOSION, 8s, 18s);
                     break;
                 case EVENT_FULLFILMENT:
-                    /// @todo For some weird reason boss does not cast this
-                    // Spell actually works, tested in duel
-                    DoCast(SelectTarget(SelectTargetMethod::Random, 0, 0.0f, true), SPELL_TRUE_FULFILLMENT, true);
+                    DoCast(SelectTarget(SelectTargetMethod::MinDistance, 1, 0.0f, true), SPELL_TRUE_FULFILLMENT, true);
```
Comment (Si1ker) [inline src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_skeram.cpp:149]:
```suggestion
                    DoCast(SelectTarget(SelectTargetMethod::MinDistance, 1, 0.0f, true), SPELL_TRUE_FULFILLMENT, false);
```

from #12736

**Comment by UltraNix** [comment]
@Si1ker Done
@IntelligentQuantum @Nyeriah Please, merge it.
