### PR TITLE
fix(Scripts): Victory rush killing blow

### LINKED ISSUE #5156: [Warrior] Victory Rush does not allow for use if Victory Rush was used as the Killing blow
## CURRENT BEHAVIOUR:
 If Victory Rush is used as the killing blow on a target it is not available for use afterwards.

## EXPECTED BLIZZLIKE BEHAVIOUR:
 Victory Rush should always be available for use after a target dies, even if Victory Rush was used as the killing blow.

## SOURCE:
Proof from Classic TBC beta: https://youtu.be/imySyB3cOO0?t=209

## AC HASH/COMMIT:
  AzerothCore rev. ee1918a3e9bc

## CUSTOMIZATIONS:
 ChromieCraft customizations.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/97679107-warrior-victory-rush-does-not-allow-for-use-if-victory-rush-was-used-as-the-killing-blow?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:
-  Made Victory Rush killing blows reset the spell.

## Issues Addressed:

- Closes #5156

## Tests Performed:

- Compile and tested on Windows 10

## How to Test the Changes:

1. Learn victory rush
2. Do a killing blow with victory rush
3. You can re-use the spell again.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1623660631649831200.sql [hunk 1]
```diff
@@ -0,0 +1,4 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1623660631649831200');
+
+DELETE FROM `spell_script_names` WHERE `spell_id` = '34428';
+INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('34428', 'spell_warr_victory_rush');
```
Comment (Kitzunu) [inline data/sql/updates/pending_db_world/rev_1623660631649831200.sql:4]: https://www.azerothcore.org/wiki/sql-standards#general-standards

Remove `''` from spellid

**Review by Kitzunu — CHANGES_REQUESTED** [review]
Just this, rest looks good

**Review by FrancescoBorzi — APPROVED** [review]
