### PR TITLE
fix(cpp): Druid ability Starfall now will no longer try to hit outside line of sight targets

### LINKED ISSUE #21567: Druid ability Starfall sometimes does not hit when there are other targets not in Line of Sight
### Triage

Original CC Report: https://github.com/chromiecraft/chromiecraft/issues/7813
Video in IF in the same location -- Notice only 6 starfall hits in 10 seconds, 3 targets in range, 2 are LoS
https://www.youtube.com/watch?v=nN9Z5LywLV0

Same spot, but with only 1 target in range -- Notice all 10 stars hit
https://www.youtube.com/watch?v=o70NVXCtWUY

### Current Behaviour

The druid ability Starfall (https://wowgaming.altervista.org/aowow/?spell=48505) is supposed to 
shoot 2 stars per second on max 2 targets which are in range and in line of sight. However, currently Starfall first calculates 
1) which targets are in range, 
2) then it selects 2 targets and 
3) then it does the line of sight check. 
The 2 targets selected at step 2 could be outside of line of sight and therefore none or only 1 Starfall hits instead of 2 per second if there are 2 valid targets.

What is expected is that Starfall should calculate
1) which targets are in range AND in Line of Sight
2) then select 2 targets
So if there are 2 targets in range and within Line of Sight, it should always have 2 valid targets instead of trying to hit a target which is outside line of sight and failing to hit with starfall.

For example, standing in Ironforge at loc 60.3 74.8. You are in range of 2 Grandmaster's Training Dummies and 1 Heroic Training dummy (3 targets)
Image

Only 2 targets are in Line of Sight (1 Grandmaster on the left and 1 Heroic on the right, the other Grandmaster on the left is around the corner). This can be confirmed with a moonfire or Faerie Fire.
Image

When casting Starfall, every second, sometimes only 1 target gets hit.
Image

Especially in crowded areas such as the beginning of Magister's Terrace, there are a lot of mobs on the lower level which are not in line of sight. When you press Starfall there, lots of times Starfall will fail to hit any mobs because it tries to hit the mobs on the level below.

Here is an example of 1 mob in range and in LoS, other mobs are outside LoS
Image
Some ticks, starfall fails to find a target, even though there is 1 mob always in range and inside LoS

Image

### Expected Blizzlike Behaviour

If there are 2 mobs in range and within line of sight and more mobs in range but not in light of sight, starfall should always connect with the 2 valid targets.

### Source

https://youtu.be/KfFv_GMOCmE?si=rbhDvm-9JRgQtQIk&t=30
Starfall with 2 packs
1 pack is behind a wall, 1 pack is inside LoS and range
During Starfall, every second there are 2 stars coming down and connecting with the pack close by, there are no times a starfall does not hit

### Steps to reproduce the problem

1. Go to location 60.3 74.8 in Ironforge
2. Cast faerie fire on the 3 target dummies in range. Confirm they are in range
3. Confirm that 1 of the target dummies is around the corner and not in line of sight
4. hit starfall as a druid, see that sometimes there is only 1 starfall hit per second, indicating that the other starfall hit tried to hit the LoS target.

Other:
1. Go to Beginning of Magisters' Terrace
2. pull 1 mob (and kill the others), keep this mob alive and in melee range (within Starfall range and within Line of Sight
3. stand at the edge where other mobs below are in range, but not in line of sigh (can't cast moonfire on them)
4. see that starfall sometimes does not hit any target at all, even though there is a valid target

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee69a569c404594ab52304e78a13682662538470

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by eusss**
...ide line of sight targets.

- Before this commit, the Druid ability Starfall would also take outside LOS targets as valid targets and try to hit them with the stars. But because they are outside LOS, these hits would not connect, however they will consume a Starfall star. This would cause Starfall not hitting mobs even if there were valid within LOS targets available
- Closes #21567

## Changes Proposed:

How the Druid spell Starfall was implemented before this change is that it takes 2 targets at random from all targets in range. However if there are lots of targets behind a wall (outside of line of sight), these targets would also be considered as targets for starfall. But because they are outside of line of sight, starfall would not hit these targets. However, it would still consume a Starfall star. This led to starfall hitting next to no targets in crowded places such as dungeons if there were mobs behind walls or in other rooms. Video evidence from WotLK suggests this is not correct behavior. If there are valid targets within line of sight, Starfall should choose to hit those.
See for more information the Chromiecraft Issue (https://github.com/chromiecraft/chromiecraft/issues/7813)

The proposed change is to filter the list of targets and remove outside LOS targets before choosing 2 random targets.

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [X] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #21567 (Druid ability Starfall sometimes does not hit when there are other targets not in Line of Sight)

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [X] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**
https://youtu.be/KfFv_GMOCmE?si=rbhDvm-9JRgQtQIk&t=30
Starfall with 2 packs
1 pack is behind a wall, 1 pack is inside LoS and range
During Starfall, every second there are 2 stars coming down and connecting with the pack close by, there are no times a starfall does not hit

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.
Tested in-game:
In Ironforge at the target dummies I stood with 2 target dummies in range and within LOS. 2 other target dummies were outside of LOS but within range(behind the wall/pillar).
Tested that the 2 targets which are within LOS always get hit each second with both stars from Starfall

## How to Test the Changes:

- [X] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

Test in Ironforge as mentioned above:
1. Make a druid and learn Starfall
2. Go to Ironforge
3. Stand in the corner with 2 target dummies in line of sight, and 2 target dummies behind the wall (this is the left wall if you go to the target dummies coming from the big forge room
4. Cast Starfall
5. Observe that Starfall always hits the 2 in line of sight target dummies each with a star, so 2 stars per second always on the 2 targets. Before the fix, sometimes there was only 1 or 0 stars per second because it was trying to hit the outside of LOS target dummies

Test in Magister's Terrace:
1. Make a druid and learn Starfall
2. Go to Magister's Terrace dungeon
3. Modify health of druid to survive hits
4. pull 1 mob to the first open area, the bridge near the entrance of Magister's Terrace. There are a lot of mobs 1 level down (see https://github.com/chromiecraft/chromiecraft/issues/7813). Turn on nameplates to see the mobs below.
5. Cast Starfall
6. Observe that Starfall always hits the pulled mob every second. Before the fix, Starfall would be trying to hit all the mobs below. This led to the pulled mob being hit by Starfall only occasionally or not at all, because the number of mobs below is much greater.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
The only Starfall cast I'm seeing in that video is at ~0:31, and the AOI reticle does seem to have some possible leeway to be considered out of range of the pack behind the wall. I personally would like some additional evidence if at all possible.

**Comment by eusss** [comment]
> The only Starfall cast I'm seeing in that video is at ~0:31, and the AOI reticle does seem to have some possible leeway to be considered out of range of the pack behind the wall. I personally would like some additional evidence if at all possible.

Thanks for your review! I will look for more video evidence. The one I linked is the most clear example I could find of 2 groups of mobs in range (nameplates visible and they are practically next to each other, I estimate within 15 yards range of the caster), with 1 group behind a wall and 1 group within line of sight. Also where it is clear the starfall stars only hit the within line of sight group and also hits each second with 2 stars.

Could you clarify what you mean with AOI reticle? Is that the Area of Effect targeting reticle on the ground? I believe that is from Hurricane.
Starfall acts within the range of the caster 30-36 yards around the caster (or 15-18 yards with Glyphs of Focus) without targeting reticle.

I'll go sift through some recorded streams of boomies.

**Comment by eusss** [comment]
> The only Starfall cast I'm seeing in that video is at ~0:31, and the AOI reticle does seem to have some possible leeway to be considered out of range of the pack behind the wall. I personally would like some additional evidence if at all possible.

**Evidence 1**
Trying to get more evidence, here is a video I found from WotLK Classic
Situation is pulling 5 mobs within line of sight and standing on top of the barricade. There are 3 mobs downstairs which are outside line of sight but in range (see the WotLK classic video below after the starfall ends and the player pans the camera @ 56:44)

WotLK Classic:
https://youtu.be/UzkoorNepus?si=wkZVBkUQYs56Yt_j&t=3386, slow down to 0.25 speed
- 56:38 - Starfall casted
- 56:39 - 2 Starfall stars hit for 933 and 933 damage
- 56:40 - 2 Starfall stars hit for 905 and 910
- 56:41 - 2 Starfall stars hit for 916 and 919
- 56:42 - 2 Starfall stars hit for 924 and 927
fight ends
ignore these damage numbers
damage numbers close to 513 = insect swarm
damage numbers close to 81 = thorns
damage numbers close to 299 and 597 crit (2x crit multiplier) = starfall AoE damage
damage numbers close to 723 and 1085 crit (1.5x crit multiplier) = hurricane
**Starfall always hits the within line of sight mobs 2 times per second**

On CC PTR:
https://youtu.be/kKMZBMToGxU, slow down to 0.25 speed
Tried to replicate the situation as much as possible on CC PTR
See the combat log for proof
- 00:16 - Starfall casted
- 00:17 - 2 Starfall stars hit for 184 and 169 damage
- 00:18 - 1 Starfall star hits for 305 (crit)
- 00:19 - 1 Starfall star hits for 184
- 00:20 - 1 Starfall star hits for 175 
- 00:21 - 1 Starfall star hits for 162
- 00:22 - 1 Starfall star hits for 181
- 00:23 - 2 Starfall stars hit for 170 and 339 (crit)
- 00:24 - 2 Starfall stars hit for 170 and 173
- 00:25 - 2 Starfall stars hit for 346 (crit) and 163
- 00:26 - 2 Starfall stars hit for 168 and 331 (crit)
**So sometimes there's only 1 Starfall star, I don't see this behavior elsewhere**

The problem is that there's a bit of RNG involved, I'll try to collect more evidence. It's hard because this is not really a situation you show in guides or boss highlights, but happens more during normal gameplay.

I asked chatgpt and the chance that in the WotLK Classic video only the 5 pulled mobs were hit with Starfall and not the 3 down the barricade is 1.63%. So it is very unlikely that the issue is in WotLK Classic. 

image

**Evidence 2**
https://youtu.be/UzkoorNepus?si=0MvpqH4Mi9kJp4F9&t=7300
Starfall on 3 pulled mobs with 1 other mob in range but outside line of sight (see screenshot)

5 double hits on the 3 mobs
1 single hit on only surviving mob (of the 3 pulled mobs)
There's always a double hit if available
Chance that Starfall didn't hit the mob below purely by chance is 1.56%

On CC PTR:
proof that the mob below is in range (within range 36, see mouse over range indicator 30-36)
Screenshot 2025-07-07 at 16 31 11

The mob down there should be outside line of sight because otherwise it would have pulled in the remaining 4 seconds of Starfall in the WotLK video

P.S. Druid in evidence 1 and 2 is NOT using Glyph of Focus (https://youtu.be/UzkoorNepus?si=ERGwrYRZJv9RP91v&t=545)

**Comment by eusss** [comment]
**Evidence 3:**

Source: WotLK Classic
https://youtu.be/kP_FO9InGps?si=n4VQeHILZKoDLK-s&t=15, slowed down to 0.25x speed
Druid is not using Glyph of Focus: at 3:18 the druid swaps Glyph of Monsoon with Glyph of Focus so he/she didn't have Glyph of Focus before at the first mob pack at 0:15

- 0:30 - Starfall casted
- 0:31 - 2 stars *
- 0:32 - 2 stars right
- 0:33 - 2 stars, left and right
- 0:34 - 2 stars right
- 0:35 - 2 stars right
- 0:36 - 2 stars right
- 0:37 - 2 stars left and right
- 0:38 - 2 stars left and right
- 0:39 - 2 stars middle and right
- 0:40 - 1 star right, because only 1 mob remaining.

\* 0:31 hard to see because they are bunched up but you see the following damage numbers:
171= thorns
524 = Starfall AoE splash damage
1096 = Starfall AoE splash crit (2x normale AoE splash damage)
1618 = Starfall hit
1610 = Starfall hit
Hurricane has not fired yet
image

During this, Starfall again always hits with 2 stars each second if there are mobs in range and in line of sight.
The mobs at the entrance of the room (seen @ 0:17 of the video https://youtu.be/kP_FO9InGps?si=ASvuO4lGKiTm4c3r&t=17) are in range but outside line of sight but don't lead to Starfall trying to hit those.

In the CC PTR this happens:
https://www.youtube.com/watch?v=6bSS-XH2DN4

- 0:23 - Starfall casted
- 0:24 - 2 stars 168 and 171 damage
- 0:25 - 2 stars 177 and 169
- 0:26 - 2 stars 173 and 315 (crit)
- 0:27 - 1 stars 154 
- 0:28 - 1 stars 170 
- 0:29 - 1 stars 160
- 0:30 - 2 stars 174 and 173
- 0:31 - 2 stars 167 and 166
- 0:32 - 2 stars 154 and 177
- 0:33 - NO stars

As you can see, the outside line of sight mobs at the entrance to the door lead to 1 or 0 stars 

To test that outside line of sight mobs are causing this issue I went and killed all the mobs in surrounding rooms which are not part of the pull

https://www.youtube.com/watch?v=UvqKoZGqI_s

If you follow the combat log, now you see that starfall stars hits 2 mobs each second, showing this is due to mobs in range but outside of line of sight.

1:32 - Starfall casted

- 1:33 - 2 stars 156 and 166 damage
- 1:34 - 2 stars 160 and 153
- 1:35 - 2 stars 161 and 156
- 1:36 - 2 stars 170 and 153
- 1:37 - 2 stars 154 and 156
- 1:38 - 2 stars 158 and 174
- 1:39 - 2 stars 177 and 164
- 1:40 - 2 stars 177 and 156
- 1:41 - 2 stars 163 and 171
- 1:42 - 2 stars 158 and 155

**Conclusion: within range but outside line of sight mobs are causing Starfall stars on CC/AC to not hit. On WotLK Classic this is not the case. Hence the proposed changes to make AC and WotLK in line.**

File: src/server/scripts/Spells/spell_druid.cpp [hunk 1]
```diff
@@ -922,7 +922,23 @@ class spell_dru_starfall_dummy : public SpellScript
 
     void FilterTargets(std::list<WorldObject*>& targets)
     {
+        // Get caster object
+        Unit* caster = GetCaster();
+        if (!caster)
+            return; // If caster is null, exit early
```
Comment (heyitsbench) [inline src/server/scripts/Spells/spell_druid.cpp]:
```suggestion
            return;
```
Comment is noting something fairly obvious and used often throughout the codebase. AI has a habit of adding comments that I at least would argue are unnecessary/redundant.

File: src/server/scripts/Spells/spell_druid.cpp [hunk 2]
```diff
@@ -922,7 +922,23 @@ class spell_dru_starfall_dummy : public SpellScript
...
+        // Remove targets if they are outside line of sight with respect to caster
+        targets.remove_if([caster](WorldObject const* target)
+            {
+                if (Unit const* unitTarget = target->ToUnit())
```
Comment (heyitsbench) [inline src/server/scripts/Spells/spell_druid.cpp]:
```suggestion
                if (target)
```
Is there a reason this isn't an option?

File: src/server/scripts/Spells/spell_druid.cpp (hunk 1 above)
Comment (eusss) [reply src/server/scripts/Spells/spell_druid.cpp]: Agreed

File: src/server/scripts/Spells/spell_druid.cpp (hunk 2 above)
Comment (eusss) [reply src/server/scripts/Spells/spell_druid.cpp]: Agreed, this also made the check fail. I will correct

**Comment by eusss** [comment]
If there are any issues, happy to hear them, thanks!

File: src/server/scripts/Spells/spell_druid.cpp [hunk 3]
```diff
@@ -922,6 +922,23 @@ class spell_dru_starfall_dummy : public SpellScript
...
+        // Remove targets if they are outside line of sight with respect to caster
+        targets.remove_if([caster](WorldObject const* target)
+            {
+                if (target)
+                {
+                    if (!caster->IsWithinLOS(target->GetPositionX(), target->GetPositionY(), target->GetPositionZ()))
+                        return true;
+                }
+                return false;
+            });
```
Comment (Tereneckla) [inline src/server/scripts/Spells/spell_druid.cpp]:
```suggestion
          {
              if (target)
              {
                  if (!caster->IsWithinLOS(target->GetPositionX(), target->GetPositionY(), target->GetPositionZ()))
                      return true;
              }
              return false;
          });
```

File: src/server/scripts/Spells/spell_druid.cpp [hunk 4]
```diff
@@ -922,6 +922,23 @@ class spell_dru_starfall_dummy : public SpellScript
 
     void FilterTargets(std::list<WorldObject*>& targets)
     {
+        // Get caster object
+        Unit* caster = GetCaster();
+        if (!caster)
+            return;
```
Comment (Tereneckla) [inline src/server/scripts/Spells/spell_druid.cpp]:
```suggestion
```
caster always exists in the script

File: src/server/scripts/Spells/spell_druid.cpp (hunk 3 above)
Comment (eusss) [reply src/server/scripts/Spells/spell_druid.cpp]: Accepted

File: src/server/scripts/Spells/spell_druid.cpp (hunk 4 above)
Comment (eusss) [reply src/server/scripts/Spells/spell_druid.cpp]: Accepted

**Review by Tereneckla — APPROVED** [review]

**Comment by eusss** [comment]
@heyitsbench Did I accidentally block the approval process by requesting a re-review? Sorry if I messed up 😅

**Comment by heyitsbench** [comment]
> Did I accidentally block the approval process by requesting a re-review? Sorry if I messed up 😅

You did not, rest assured! I gave my two cents to this review, but I'm not really familiar enough with scripts like this to confidently give it an approval, so I leave it to other maintainers to look at. Sometimes PRs just take a bit to get to, only so many hands and all that.

Sidenote: You don't need to merge commits from master into your branch so often, really only if there are conflicts do you *have* to.

**Comment by eusss** [comment]
> > Did I accidentally block the approval process by requesting a re-review? Sorry if I messed up 😅
> 
> You did not, rest assured! I gave my two cents to this review, but I'm not really familiar enough with scripts like this to confidently give it an approval, so I leave it to other maintainers to look at. Sometimes PRs just take a bit to get to, only so many hands and all that.
> 
> Sidenote: You don't need to merge commits from master into your branch so often, really only if there are conflicts do you _have_ to.

Thanks Bench! This is my first time, appreciate all the tips! Also no hurries :) <3

**Comment by eusss** [comment]
@Tereneckla hi, sorry to ping, is there any update on this pull request or can it be merged?

**Comment by Tereneckla** [comment]
I do not have any merge rights or does my review count for that
