### PR TITLE
Karazhan rework

### LINKED ISSUE #173: Karazhan The opera house Script Bug
**Description**:
The scene can't trigger
http://www.wowhead.com/npc=16812/barnes
**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
1. Click on the NPC after didn't open the option.

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  
WIN7/X64
**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

##

### PR DESCRIPTION
**Pull request by talamortis**
Changes proposed:
**Opera Event**

- [ ] Fix loot tables for Opera event (RAJ)
- [x]     Opera events working correctly
- [x]     The crone cyclone will now move instead of stood in 1 place.
- [x]     The Crone chain lightning will now cast more often

**Nightbane**

- [ ]     Change Intro path of Nightbane
- [x]     Nightbane will now correctly work

**Shade of Aran**

- [x]     Shade of Aran will now summon water elementals in the correct place.

**Moroes**

- [x] Moroes will attack as he comes out of Vanish

**Illhoof**

- [x]     Illhoof will now spawn back his Imp after 45 seconds

**Prince Malcazhaar**

- [x]    Prince will now spawn only 1 axe instead of two.
- [x]    Prince axe will now attack with both weapons instead of just one.
- [x]    Prince Axe will now change target onto random, instead of focusing one player (fix on next push)
- [x]    Fix Enfeeble for Prince.
- [x]    Rescript Prince Malcazhaar
- [x]     Make Infernal Relay Cast infernal

Target branch(es): master

Issues addressed: Closes #173 #172 #174 #39

Tests performed: (Does it build, tested in-game, etc)
Tested in game all working correctly.

NOTE You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1483918476110152000.sql [hunk 1]
```diff
@@ -0,0 +1,14 @@
+INSERT INTO version_db_world (`sql_rev`) VALUES ('1483918476110152000');
+
+DELETE FROM `creature` WHERE `ID` = "17644";
+
+UPDATE `creature_template` SET `ScriptName` = "prince_axes" WHERE `entry` = "17650";
+
+INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (30843, 41624, 0, 'Prince Enfeelble');
```
Comment (ShinDarth) [inline data/sql/updates/pending_db_world/rev_1483918476110152000.sql]: please use DELETE before INSERT

File: src/scripts/EasternKingdoms/Karazhan/boss_prince_malchezaar.cpp [hunk 2]
```diff
@@ -2,27 +2,55 @@
...
+    SPELL_ENFEEBLE_EFFECT = 41624,
+    SPELL_SHADOWNOVA = 30852,                       //Shadownova used during all phases
+    SPELL_SW_PAIN = 30854,                       //Shadow word pain during phase 1 and 3 (different targeting rules though)
+    SPELL_THRASH_PASSIVE = 12787,                       //Extra attack chance during phase 2
+    SPELL_SUNDER_ARMOR = 30901,                       //Sunder armor during phase 2
+    SPELL_THRASH_AURA = 12787,                       //Passive proc chance for thrash
+    SPELL_EQUIP_AXES = 30857,                       //Visual for axe equiping
+    SPELL_AMPLIFY_DAMAGE = 39095,                       //Amplifiy during phase 3
+    SPELL_CLEAVE = 30131,                       //Same as Nightbane.
+    SPELL_HELLFIRE = 30859,                       //Infenals' hellfire aura
```
Comment (ShinDarth) [inline src/scripts/EasternKingdoms/Karazhan/boss_prince_malchezaar.cpp]: it would be nice to align those comments

File: src/scripts/EasternKingdoms/Karazhan/boss_prince_malchezaar.cpp [hunk 3]
```diff
@@ -176,117 +167,80 @@ class boss_malchezaar : public CreatureScript
         boss_malchezaarAI(Creature* creature) : ScriptedAI(creature)
         {
             instance = creature->GetInstanceScript();
-            memset(axes, 0, sizeof(axes));
         }
 
+
```
Comment (ShinDarth) [inline src/scripts/EasternKingdoms/Karazhan/boss_prince_malchezaar.cpp]: unneeded empty line

File: src/scripts/EasternKingdoms/Karazhan/boss_prince_malchezaar.cpp [hunk 4]
```diff
@@ -337,38 +291,62 @@ class boss_malchezaar : public CreatureScript
...
+             if ((me->GetMapId() == 532))
+             {
+                 me->GetRandomNearPosition(pos, 40.0);
+             }
+             else
+             {
+                 point = Trinity::Containers::SelectRandomContainerElement(positions);
+                 pos.Relocate(point->x, point->y, INFERNAL_Z, frand(0.0f, float(M_PI * 2)));
+
```
Comment (ShinDarth) [inline src/scripts/EasternKingdoms/Karazhan/boss_prince_malchezaar.cpp]: unneeded extra line

File: src/scripts/EasternKingdoms/Karazhan/boss_prince_malchezaar.cpp [hunk 5]
```diff
@@ -538,56 +440,83 @@ class boss_malchezaar : public CreatureScript
...
-    
-}
-
 void AddSC_boss_malchezaar()
 {
     new boss_malchezaar();
+    new prince_axes();
     new netherspite_infernal();
-}
+}
```
Comment (ShinDarth) [inline src/scripts/EasternKingdoms/Karazhan/boss_prince_malchezaar.cpp]: please add a new line at the end of file

**Comment by talamortis** [comment]
@ShinDarth some of thoese comments are just being picky :P but ill sort it 👍

**Comment by ShinDarth** [comment]
@talamortis I know, but while I was there I told you xD

**Comment by talamortis** [comment]
well anyways its been sorted :) hopefully people will now test 👍

**Comment by talamortis** [comment]
@ShinDarth  please dont delete the branch as i still got a few updates to do 👍

**Comment by ShinDarth** [comment]
@talamortis ok, for me it's not a problem, but just FYI you can simply create a new one (since this is merged, it's equivalent to master)

**Comment by talamortis** [comment]
i know i can but i know where abouts i am and it saves me from altering my git

**Comment by ShinDarth** [comment]
ok, no problem 👍
