### PR TITLE
Core/ICC: Lady Deathwhisper

### LINKED ISSUE #761: Lady Deathwhisper Major Bugs
**Description**: Lady Deathwhisper currently has many Bugs during both Phases.

**Current behaviour**: 
Phase 1
- Empowered Cult Adherents are NOT immune to interrupt effects.
- You can "interrupt" Dark Martyrdom casts with Stuns and with knockback effects such as Thunderstorm / Typhoon.
- If Dark Martyrdom cast is successful, the Reanimated add spawns with a many seconds delay.

Phase 2
- Adds dying from Dark Martyrdom in Phase 2 are NOT reviving as Reanimated.

**Expected behaviour**: 
- Empowered Cult Adherents definitely should be immune to interrupts.
- The only way to "interrupt" Dark Martyrdom is killing the mob before the cast is over. That means they should be immune to Stuns, and not suffering knockbacks.
- Adds dying from Dark Martyrdom should almost istantly spawn as Reanimated, even during Phase 2.

**Steps to reproduce the problem**:

1. Try to interrupt Empowered Cult Adherents and notice it actually works.
2. Try to stun adds during Dark Martyrdom cast and see it actually stuns them.
3. Notice how adds who could successfully cast Dark Martyrdom may take many seconds to spawn as Reanimated.
4. During Phase 2 adds are not spawning as Reanimated AT ALL.

**Branch(es)**: Master

**AC hash/commit**:  29f4a1e090338bc033ebdecb0d71ee45cde6f66f

**Operating system**:  Linux

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/54023773-lady-deathwhisper-major-bugs?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #1538: [ICCMOB][PVE][SPELL] Lady Deathwhisper- Second Phase "Dark Martyrdom"
##### SMALL DESCRIPTION:
During the second phase of the Boss of Icc:
The Lady Deathwisper ( https://www.wowhead.com/npc=36855/lady-deathwhisper ) adds that spawn
( https://www.wowhead.com/npc=37949/cult-adherent -https://www.wowhead.com/npc=37890/cult-fanatic ) during the second phase should not use the spell Dark Martyrdom
( https://www.wowhead.com/spell=70903/dark-martyrdom#used-by-npc ADHERENT )
( https://www.wowhead.com/spell=71236/dark-martyrdom FANATIC )

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The Lady Deathwisper ( https://www.wowhead.com/npc=36855/lady-deathwhisper ) adds that spawn
( https://www.wowhead.com/npc=37949/cult-adherent -https://www.wowhead.com/npc=37890/cult-fanatic ) during the second phase should not use the spell Dark Martyrdom
( https://www.wowhead.com/spell=70903/dark-martyrdom#used-by-npc ADHERENT )
( https://www.wowhead.com/spell=71236/dark-martyrdom FANATIC )

Tankspot Offy raid - same behaviour 10h and 25 h  https://youtu.be/W64bCmigL1Q 

##### CURRENT BEHAVIOUR:
During the First Phase this adds ( THE SAME ADDS) works but during the second phase when the Lady Deathwhisper have no more the mana shield this adds don't works as intended

##### STEPS TO REPRODUCE THE PROBLEM:
1. Go Inside Icc  ( 10h-25h) and after have cleaned all the room of the Lady Deathwhisper start the fight
2. see that in the first phase this adds works correctly and use the Dark Martyrdom how should be 
3. see that in the second phase this adds use that spell the Dark Martyrdom that they should not use 

##### EXTRA NOTES:
HIGH PRIO !

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/44272f169c49f20c79b78aeea634f3bc7c2dafd1

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/70722310-iccmob-pve-spell-lady-deathwhisper-second-phase-dark-martyrdom?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Nefertumm**
##### CHANGES PROPOSED:

-  Added missing overrides and changed NULL for nullptr.
-  Fix timers (this needs atention, it might be wrong)
-  No more Dark Martyrdom being casted in phase 2.
-  Added temporal immunities to certain spell mechanics to avoid interrupt Dark Martyrdom cast.
-  Added the correct auras to reanimated cultists (fanatic's/adherent's determination).
-  Avoid spam of Dark Martyrdom.
-  Lady Deathwhisper should be immune to taunt on heroic.
-  Don't do the intro in combat (this can happen if the server crash or restart and there's people in front of the boss, when they login again and they don't activate the areatrigger, this can happen, so avoid this).
-  Indentation correction.

###### ISSUES ADDRESSED:

Closes #1538 
Closes #761 

##### TESTS PERFORMED:

Compiled and tested. Need more tests though.

##### HOW TO TEST THE CHANGES:

Go to icc, kill Lord Marrowgar and go to Lady Deathwhisper. Play with mobs during first phase, make sure you can't interrupt Dark Martyrdom's cast, etc... Detailed above.

##### Target branch(es):

Master

This is a continuation of #1544

### CODE REVIEW

**Comment by Nefertumm** [comment]
comix1988:
> today I tested the lady at 10 normal icc:
> 
> https://youtu.be/lUeNRXXAKNQ
> 
> - sometimes when the npc cult adherent gets stunned it freezes (0:45 min) ----> to fix
> - no NPC spawned in phase 2; ----> GOOD
> - reanimated cultists have a correct aura; ----> GOOD
> - interrupt Dark Martyrdom cast is not possible; ----> GOOD
> -timer of adds weaves work perfectly until the third,then delay a few seconds(3:06 and 4:08 mins)-> to fix
> - when the cast of Dark Martyrdom is completed the npc explosion isn't seen --> fix visual
> 
> tomorrow i test other difficulties
> @heisenberg520 see other bugs?
> 
> tested on Ubuntu 18.04.2 LTS
> 
> **on behalf of @maelstromserver**

**Comment by Nefertumm** [comment]
comix1988:
> Lady 10H:
> 
> https://youtu.be/sGOuKUBK54Q
> 
> - the spawn time of the add should be fixed (the second wave anticipates 10 sec);
> - when the cast of Dark Martyrdom is completed the npc explosion isn't seen --> fix visual
> - everything else is OK
> 
> tested on Ubuntu 18.04.2 LTS
> 
> **on behalf of @MaelstromServer**

**Comment by Nefertumm** [comment]
comix1988:

> lady 25n:
> 
> https://youtu.be/UOo3RNzp79U
> 
> - timer of adds weaves work perfectly until the third,then delay a few seconds(3:06 and 4:08 mins)-> to fix
> - when the cast of Dark Martyrdom is completed the npc explosion isn't seen --> fix visual
>

**Comment by Nefertumm** [comment]
comix1988:
> lady 25h:
> 
> https://youtu.be/_E2oIv13GrQ
> 
> - the spawn time of the add should be fixed (the second wave anticipates 10 sec);
> - when the cast of Dark Martyrdom is completed the npc explosion isn't seen --> fix visual

**Comment by Nefertumm** [comment]
comix1988:
> definitely: @Nefertumm 
> 
> - in every difficulties fix the visual bug of the explosion of the mob that has cast "dark martyrdom";
> - check why sometimes the npc "cult adherent" freezes;
> - fix the add waves: in normal mode from the third wave they delay by 2 sec;
>                                 in hero mode anticipate by about 12 seconds from the second wave;
> 
> everything else is ok for me. I hope I was precise in the explanation.
> 
> P.S: in the videos of the hero mode the vangeful spirits are not seen but they work, I tested them with 5 pg instead of 2 pg.
> 
> tested on Ubuntu 18.04.2 LTS
> 
> **on behalf of @MaelstromServer**

**Comment by Nefertumm** [comment]
Well, timers are fine now, but i don't know why summon's timer gets delayed.

**Comment by GitVerge** [comment]
Check the part where AI is not updated while casting

**Comment by Nefertumm** [comment]
@comix1988 Were the summon's timers delaying before this pull request? Or is it just my commit?

**Comment by comix1988** [comment]
I tested the timers only with your commit. I'm checking them on the master branch tonight.

**Comment by comix1988** [comment]
@Nefertumm I tested the 25h timers on the master branch, and they're wrong there, too.

**Comment by Nefertumm** [comment]
Well, i figured out that timers are not delayed but dbm is showing the normal difficulty timer (on HC, summon's timer is 45s, while on normal is 60s). So, if

File: src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp [hunk 1]
```diff
@@ -247,9 +271,9 @@ class boss_lady_deathwhisper : public CreatureScript
                 events.ScheduleEvent(EVENT_SPELL_DEATH_AND_DECAY, 10000);
                 if (GetDifficulty() != RAID_DIFFICULTY_10MAN_NORMAL)
                     events.ScheduleEvent(EVENT_SPELL_DOMINATE_MIND_25, 27000);
-                events.ScheduleEvent(EVENT_SPELL_SHADOW_BOLT, urand(5500, 6000), 0, PHASE_ONE);
+                events.ScheduleEvent(EVENT_SPELL_SHADOW_BOLT, 2000, 0, PHASE_ONE);
```
Comment (pklloveyou) [inline src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp]: Because this event"EVENT_SPELL_SHADOW_BOLT" is too dense, the summoning event"EVENT_SUMMON_WAVE_P1" is delayed

Comment (pklloveyou) [reply src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp]: If this event“EVENT_SPELL_SHADOW_BOLT” is fixed, the start time of the summoning event“EVENT_SUMMON_WAVE_P1” will be 7000，DBM is like this <7000>

Comment (pklloveyou) [reply src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp]: All BOSS events have this problem

**Comment by pklloveyou** [comment]
TIM截图20190404025230
TIM截图20190404025158
This solves the problem  @Nefertumm

File: src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp [hunk 2]
```diff
@@ -247,9 +271,9 @@ class boss_lady_deathwhisper : public CreatureScript
...
                 events.ScheduleEvent(EVENT_SUMMON_WAVE_P1, 5000, 0, PHASE_ONE);
```
Comment (pklloveyou) [inline src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp]: events.ScheduleEvent(EVENT_SUMMON_WAVE_P1, 5000+2000, 0, PHASE_ONE);

**Comment by Nefertumm** [comment]
If nobody is against this, i will merge it tonight.

**Comment by comix1988** [comment]
I didn't find any information about the 45 second spawn timer in the heroic. I only found the 60 seconds.

**Comment by Nefertumm** [comment]
On wow wiki there's information about that.

**Comment by comix1988** [comment]
Ok to merge for me
