### PR TITLE
fix(Scripts/GruulsLair): Fixed Ground Slam.

### LINKED ISSUE #14713: [Gruul's Lair] Ground Slam event is hacked
### Current Behaviour

When Gruul uses [ground slam](https://www.wowhead.com/tbc/spell=33525/ground-slam) all players are knocked **back** towards the wall.

### Expected Blizzlike Behaviour

~~When Gruul uses ground slam all players must be knocked in **random** direction towards the wall.~~

Gultask: See here: https://github.com/Gultask/Research-Wotlk/issues/3
This mechanic is the most complicated one of the instance.

In short:
The knock back from Ground Slam is actually the summoning of several 'Invisible Tractor Beam Source' creatures, casting Tractor Beam (33497) at their designated player.

### Source

https://www.icy-veins.com/tbc-classic/gruuls-lair-guide-strategy-abilities-loot
https://wowpedia.fandom.com/wiki/Gruul_the_Dragonkiller_(tactics)

[Classic Raid Encounter](https://youtu.be/9ISO0QjRWeo?t=1029)
[Classic Raid Encounter 2](https://youtu.be/9ISO0QjRWeo?t=1116)

### Steps to reproduce the problem

1. Engage Gruul;
2. Survive for about half a minute till ability [Ground Slam](https://www.wowhead.com/tbc/spell=33525/ground-slam) is used;

### Extra Notes

Being knocked in random direction adds an additional layer of complexity to the fight.
Currently players can effectively spread preemptively, greatly reducing damage taken from shatter.

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/4808

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/592a26cb8c46a9db92a70c275f1d8625f8949c1d

### Operating system

Windows 10.

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #14713

 

## Issues Addressed:

- Closes #14713
- Closes https://github.com/chromiecraft/chromiecraft/issues/4808

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

Engage Gruul;
Survive for about half a minute till ability [Ground Slam](https://www.wowhead.com/tbc/spell=33525/ground-slam) is used;

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/scripts/Outland/GruulsLair/boss_gruul.cpp [hunk 1]
```diff
@@ -55,241 +69,253 @@ enum Events
...
+
+        events.ScheduleEvent(EVENT_GROWTH, 30000);
+        events.ScheduleEvent(EVENT_CAVE_IN, _caveInTimer);
+        events.ScheduleEvent(EVENT_REVERBERATION, 20000);
+        events.ScheduleEvent(EVENT_HURTFUL_STRIKE, 10000);
+        events.ScheduleEvent(EVENT_GROUND_SLAM, 35000);
+    }
 
-        void EnterCombat(Unit* /*who*/) override
+    void KilledUnit(Unit*  /*who*/) override
```
Comment (Kitzunu) [inline src/server/scripts/Outland/GruulsLair/boss_gruul.cpp:94]:
```suggestion
    void KilledUnit(Unit* /*who*/) override
```

**Review by Kitzunu — APPROVED** [review]

**Comment by Maelthyrr** [comment]
compile  errors

Screenshot 2023-02-04 160946

**Comment by Maelthyrr** [comment]
Tested and work fine. Thanks.
