### PR TITLE
fix(Creature/Core): Boss phased reset

### LINKED ISSUE #7795: (Creature): Bosses do not reset correctly [phase+respawn]
### Current Behaviour

All bosses run back to their spawn point once a reset is called

### Expected Blizzlike Behaviour

There are some bosses that do a simple reset and other "more complex" bosses do a "phased reset" and then respawn.
**Seems** there is a pattern for which bosses do a simple or phased reset as I will describe below:

### What bosses should run back to the spawn point at reset?
Simple bosses.
image

- No environmental changes
- No transformations
- No transportations from/to high ground
Examples: Sapphiron & Patchwerk

### What bosses should disappear and respawn at reset?

- Transformations like Professor Putricide in Icecrown Citadel
- Special teleports to a balcony or other movements to large areas like Gothik in Naxxramas
- Mechanics that change the environment like Mimiron in Ulduar

All other bosses with transformations, high ground teleports, and with mechanics that change environment should disappear (phasing) and respawn after some time (amount of time is unknown)

### Source

All sources from retail *

= Simple reset =
https://youtu.be/C5UzzD8SfPo?t=140
https://youtu.be/PMYg2cxS9bA?t=200
https://youtu.be/oX0PnQrjF0A?t=305
https://youtu.be/kjFabmZSsPw?t=50
https://youtu.be/fN_GElMn__k?t=105

= Phased reset =
https://youtu.be/3kvpRJPGx8c?t=204
https://youtu.be/-jWBa33m8FE?t=180
https://youtu.be/j3KvFCmmsqM?t=376
https://youtu.be/54ynIY7Ntwo?t=106
https://youtu.be/yULPhV2qcgA?t=340
https://youtu.be/g2JEnecZD5w?t=42
https://youtu.be/DTBT-55ZHbk?t=265
- This is from Forge of Souls - so it **also applies to dungeons**: https://youtu.be/4MysXz8EY4I?t=195
- This is from Pit of Saron, on Scourgelord Tyrannus : https://youtu.be/qnDRFToSspw?t=70

### Steps to reproduce the problem

1. Engage a boss
2. Reset by dying or using ".gm on"
3. Boss will run back to the spawn point

### Extra Notes

_No response_

### AC rev. hash/commit

efdb64a

### Operating system

Windows 10

### Custom changes or Modules

None

### PR DESCRIPTION
**Pull request by Si1ker**
## Changes Proposed:
-  Reset on EnterEvadeMode with blizzlike behavior

## Issues Addressed:

- Closes #7795

## SOURCE:

The following bosses have confirmed sources for this behaviour, only confirmed bosses on sources will be added to this reset behaviour, if you find additional bosses and a good source on video, please add it to this PR.

-- Raids --
Algalon -> https://youtu.be/Kc4nvDrAqmM?t=100
Halion -> https://youtu.be/HaTvKgjSlVE?t=32
Razorscale -> https://youtu.be/3kvpRJPGx8c?t=204
Festergut -> https://youtu.be/-jWBa33m8FE?t=180
Assembly of Iron -> https://youtu.be/j3KvFCmmsqM?t=376
Mimiron -> https://youtu.be/54ynIY7Ntwo?t=106
Gothik The Harvester -> https://youtu.be/yULPhV2qcgA?t=340
Professor Putricide -> https://youtu.be/g2JEnecZD5w?t=42
Kel'Thuzad -> https://youtu.be/DTBT-55ZHbk?t=265
Emalon the Storm Watcher -> https://youtu.be/RNRmg-r7Cd0?t=196
Magtheridon -> https://www.youtube.com/watch?v=JyZOeIIaXfI&t=2345s
Kill'jaeden -> https://www.youtube.com/watch?v=HYabDkWSNZQ&t=406s
Thaddius -> https://youtu.be/deDF_Sj6xzg?t=15
Kologarn -> https://youtu.be/5E0oW3Z8cFU?t=128
Freya -> https://youtu.be/7Pp_ANMmD4k?t=268
Lich King -> https://youtu.be/ocuTx3kBY3Q?t=19
Sindragosa -> https://youtu.be/aDCNKIetnO4?t=76
Lady Deathwhisper -> https://youtu.be/R3B-VF2wCWo?t=510
Blood-Queen Lana'thel -> https://youtu.be/3QBlzFSaAl4?t=316

-- Dungeons --
Krik'thir the Gatewatcher -> https://youtu.be/9mvsB1tqQhU?t=116
Devourer of Souls -> https://youtu.be/4MysXz8EY4I?t=196
Scourgelord Tyrannus : https://youtu.be/qnDRFToSspw?t=70

## Tests Performed:

- Tested in-game

## How to Test the Changes:

1. Go to a boss
2. Die or go out of the room
3. Boss will -> Disappear, die by itself (this won't trigger achievements/doors/etc), respawn, Appear

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Si1ker** [comment]
PENDING: Still trying to find a way to prevent boss' minions at respawn 🐱

**Comment by Footman** [comment]
Lich King also: https://youtu.be/ocuTx3kBY3Q?t=19

**Comment by Si1ker** [comment]
Not all @Footman , see the issue linked for reference.
Thanks for the additional 2 sources, added!

**Comment by Footman** [comment]
> Not all @Footman , see the issue linked for reference.
> Thanks for the additional 2 sources, added!

i think its different per instance than and not per boss. seems all icc bosses reset with visibility.

**Comment by Si1ker** [comment]
> > Not all @Footman , see the issue linked for reference.
> > Thanks for the additional 2 sources, added!
> 
> i think its different per instance than and not per boss. seems all icc bosses reset with visibility.

Nop, is per boss. again, read sources in issue, for example Thaddius does that while patchwerk does not, for example.

**Comment by Footman** [comment]
> > > Not all @Footman , see the issue linked for reference.
> > > Thanks for the additional 2 sources, added!
> > 
> > 
> > i think its different per instance than and not per boss. seems all icc bosses reset with visibility.
> 
> Nop, is per boss. again, read sources in issue for reference, for example Thaddius does that while patchwerk does not, for example.

ok I think than good solution would do it with flag_extra in SQL instead of hard code

**Comment by Si1ker** [comment]
> > > > Not all @Footman , see the issue linked for reference.
> > > > Thanks for the additional 2 sources, added!
> > > 
> > > 
> > > i think its different per instance than and not per boss. seems all icc bosses reset with visibility.
> > 
> > 
> > Nop, is per boss. again, read sources in issue for reference, for example Thaddius does that while patchwerk does not, for example.
> 
> ok I think than good solution would do it with flag_extra in SQL instead of hard code

Well, nobody has done that solution in years... years! plenty of time... meaning nobody cared, I wouldn't expect somebody coming up with that solution now even less probable in SQL.

I'm doing it now in code (again, nobody gave a fuc...), and is working.
The same principle we have with "stacking spells from all sources" which are [added into a specific file one by one](https://github.com/azerothcore/azerothcore-wotlk/pull/4299/files), the same thing with my changes once finished, bosses **with GOOD source** will be added as new lines at the end for this reset behavior.

**Comment by lineagedr** [comment]
```c++
static constexpr std::array<uint32, 23> bosses = 
{
    /* dungeons */
    28684, /* Krik'thir the Gatewatcher */
    36502, /* Devourer of Souls */
    36658, /* Scourgelord Tyrannus */
    /* raids */
    32871, /* Algalon */
    39863, /* Halion */
    33186, /* Razorscale */
    36626, /* Festergut */
    32867, /* Steelbreaker - Assembly of Iron */
    32927, /* Runemaster Molgeim - Assembly of Iron */
    32857, /* Stormcaller Brundir - Assembly of Iron */
    33350, /* Mimiron */
    16060, /* Gothik the Harvester */
    36678, /* Professor Putricide */
    15990, /* Kel'Thuzad */
    33993, /* Emalon the Storm Watcher */
    17257, /* Magtheridon */
    25315, /* Kil'jaeden */
    15928, /* Thaddius */
    32930, /* Kologarn */
    32906, /* Freya */
    36597, /* The Lich King */
    36853, /* Sindragosa */
    36855  /* Lady Deathwhisper */
};

// despawn bosses at reset - only verified tbc/woltk bosses with this reset type - add bosses in last line respectively (dungeon/raid)
if (std::find(std::begin(bosses), std::end(bosses), me->GetEntry()) != std::end(bosses))
{
    me->SetVisible(false);
    me->m_Events.AddEvent(new PhasedReset(*me), me->m_Events.CalculateTime(20000));
}
else // bosses will run back to the spawnpoint at reset
{
    Reset();
    if (me->IsVehicle()) // use the same sequence of addtoworld, aireset may remove all summons!
    {
        me->GetVehicleKit()->Reset(true);
    }
}
```

if you don't want to type `|| me->GetEntry() ==` for every new boss id

Just a random suggestion

**Comment by Si1ker** [comment]
- Pending: I'm stuck on this until I find a way to despawn summons right after the first reset at PhasedReset
- Reason: When the first Reset() is called , the bosses that have pre-spawned minions (Thaddius, Razuvious, Anub'Rehkan, etc) will disappear as intended but the minions will just respawn instantly because there is a call for it at the Reset() of each boss.

I was thinking about something like _SummonList::DespawnAll();_ but seems not an option.
Open to suggestions. @lineagedr @UltraNix

File: src/server/game/AI/CreatureAI.cpp [hunk 1]
```diff
@@ -170,10 +207,50 @@ void CreatureAI::EnterEvadeMode()
         }
     }
 
-    Reset();
-
-    if (me->IsVehicle()) // use the same sequence of addtoworld, aireset may remove all summons!
-        me->GetVehicleKit()->Reset(true);
+    // despawn bosses at reset - only verified tbc/woltk bosses with this reset type - add bosses in last line respectively (dungeon/raid) and increase array limit
+    static constexpr std::array<uint32, 24> bosses = {
```
Comment (Kitzunu) [inline src/server/game/AI/CreatureAI.cpp:211]: Could you add a `//@todo: Turn into a flags_extra in creature_template` so that we in the future can remove the hardcoded stuff?

Comment (Si1ker) [reply src/server/game/AI/CreatureAI.cpp:211]: Will do

**Comment by UltraNix** [comment]
> * Pending: I'm stuck on this until I find a way to despawn summons right after the first Reset() at PhasedReset, the second Reset() at PhasedRespawn will spawn them for the normal encounter.
> * Reason: When the first Reset() is called, the bosses that have pre-spawned minions (Thaddius, Razuvious, Anub'Rehkan, etc) will disappear as intended but the minions will just respawn instantly because there is a call for it at the Reset() of each boss.
> 
> I was thinking about something like _SummonList::DespawnAll();_ but seems not an option.
> Open to suggestions. @lineagedr @UltraNix

Because `Reset` is called in two scenarios: On spawn/respawn and on evade mode.

**Comment by Si1ker** [comment]
Currently just need a way to despawn summons from there, ty n.n

**Comment by UltraNix** [comment]
If bosses handle them by summonlist, you could after that Reset call use `_summons.DespawnAll`

**Comment by Footman** [comment]
why not call Evade and PhasedReset after?

**Comment by Si1ker** [comment]
@UltraNix yes, they all use SummonList to handle their summons, but don't know how to apply your idea.

@Footman PhasedReset is already at the end of EnterEvadeMode , so....

**Comment by Footman** [comment]
can you explain please why Reset() is not allowed to call on this phased reset? A lot of bosses like for example Halion override this function to reset parameters. If this is not called than there will be bugs on next tries after wipe.

**Comment by Footman** [comment]
sorry i see that reset is used there. one thing is missing is JustReachedHome that is used in scripts

**Comment by Footman** [comment]
ok solution would be to 
1. add bool parameter to Respawn and not to call reset after respawn
2. call summons.DespawnAll(); on despawn
3. call JustReachedHome on PhasedRespawn

**Comment by Footman** [comment]
`
---
 src/server/game/AI/CreatureAI.cpp             | 10 ++----
 src/server/game/AI/CreatureAI.h               |  1 +
 .../game/AI/ScriptedAI/ScriptedCreature.cpp   |  5 +++
 .../game/AI/ScriptedAI/ScriptedCreature.h     |  1 +
 .../game/Entities/Creature/Creature.cpp       | 31 +++++++++++++++++++
 src/server/game/Entities/Creature/Creature.h  |  2 ++
 6 files changed, 42 insertions(+), 8 deletions(-)

diff --git a/src/server/game/AI/CreaturaeAI.cpp b/src/server/game/AI/CreatureAI.cpp
index a1604ffb4..c7382f725 100644
--- a/src/server/game/AI/CreatureAI.cpp
+++ b/src/server/game/AI/CreatureAI.cpp
@@ -21,12 +21,7 @@ public:
 
     bool Execute(uint64 /*eventTime*/, uint32 /*updateTime*/) override
     {
-        _owner.DespawnOrUnsummon();
-        _owner.Respawn();
-        if (_owner.IsVehicle()) // use the same sequence of addtoworld, aireset may remove all summons!
-        {
-            _owner.GetVehicleKit()->Reset(true);
-        }
+        _owner.DespawnOnEvade();
         return true;
     }
 
@@ -41,8 +36,7 @@ public:
 
     bool Execute(uint64 /*eventTime*/, uint32 /*updateTime*/) override
     {
-        _owner.SetVisible(true);
-        _owner.AI()->Reset(); // avoids issues with triggers/stalkers by visibility
+        _owner.RespawnOnEvade();
         return true;
     }
 
diff --git a/src/server/game/AI/CreatureAI.h b/src/server/game/AI/CreatureAI.h
index 848a58502..e485ca73c 100644
--- a/src/server/game/AI/CreatureAI.h
+++ b/src/server/game/AI/CreatureAI.h
@@ -103,6 +103,7 @@ public:
 
     virtual void SummonedCreatureDespawn(Creature* /*summon*/) {}
     virtual void SummonedCreatureDies(Creature* /*summon*/, Unit* /*killer*/) {}
+    virtual void SummonedCreatureDespawnAll() {}
 
     // Called when hit by a spell
     virtual void SpellHit(Unit* /*caster*/, SpellInfo const* /*spell*/) {}
diff --git a/src/server/game/AI/ScriptedAI/ScriptedCreature.cpp b/src/server/game/AI/ScriptedAI/ScriptedCreature.cpp
index 6f560e864..c0d226a14 100644
--- a/src/server/game/AI/ScriptedAI/ScriptedCreature.cpp
+++ b/src/server/game/AI/ScriptedAI/ScriptedCreature.cpp
@@ -604,6 +604,11 @@ void BossAI::SummonedCreatureDespawn(Creature* summon)
     summons.Despawn(summon);
 }
 
+void BossAI::SummonedCreatureDespawnAll()
+{
+    summons.DespawnAll();
+}
+
 void BossAI::UpdateAI(uint32 diff)
 {
     if (!UpdateVictim())
diff --git a/src/server/game/AI/ScriptedAI/ScriptedCreature.h b/src/server/game/AI/ScriptedAI/ScriptedCreature.h
index 5b689afed..6968b459d 100644
--- a/src/server/game/AI/ScriptedAI/ScriptedCreature.h
+++ b/src/server/game/AI/ScriptedAI/ScriptedCreature.h
@@ -419,6 +419,7 @@ public:
 
     void JustSummoned(Creature* summon) override;
     void SummonedCreatureDespawn(Creature* summon) override;
+    void SummonedCreatureDespawnAll() override;
 
     void UpdateAI(uint32 diff) override;
 
diff --git a/src/server/game/Entities/Creature/Creature.cpp b/src/server/game/Entities/Creature/Creature.cpp
index 87b115008..1af6fcc5d 100644
--- a/src/server/game/Entities/Creature/Creature.cpp
+++ b/src/server/game/Entities/Creature/Creature.cpp
@@ -1976,6 +1976,37 @@ void Creature::DespawnOrUnsummon(uint32 msTimeToDespawn /*= 0*/)
         ForcedDespawn(msTimeToDespawn);
 }
 
+void Creature::DespawnOnEvade()
+{
+    SetVisible(false);
+    AI()->SummonedCreatureDespawnAll();
+    RemoveEvadeAuras();
+
+    float x, y, z, o;
+    GetRespawnPosition(x, y, z, &o);
+    SetHomePosition(x, y, z, o);
+    SetPosition(x, y, z, o);
+
+    if (IsFalling())
+    {
+        RemoveUnitMovementFlag(MOVEMENTFLAG_FALLING);
+    }
+
+    StopMoving();
+}
+
+void Creature::RespawnOnEvade()
+{
+    SetVisible(true);
+    UpdateMovementFlags();
+    AI()->Reset();
+    AI()->JustReachedHome();
+
+    if (IsVehicle()) // use the same sequence of addtoworld, aireset may remove all summons!
+    {
+        GetVehicleKit()->Reset(true);
+    }
+}
 void Creature::InitializeReactState()
 {
     if ((IsTotem() || IsTrigger() || IsCritter() || IsSpiritService()) && GetAIName() != "SmartAI" && !GetScriptId())
diff --git a/src/server/game/Entities/Creature/Creature.h b/src/server/game/Entities/Creature/Creature.h
index 725b22ff4..4f7611bd7 100644
--- a/src/server/game/Entities/Creature/Creature.h
+++ b/src/server/game/Entities/Creature/Creature.h
@@ -258,6 +258,8 @@ public:
     void RemoveCorpse(bool setSpawnTime = true, bool skipVisibility = false);
 
     void DespawnOrUnsummon(uint32 msTimeToDespawn = 0);
+    void DespawnOnEvade();
+    void RespawnOnEvade();
 
     [[nodiscard]] time_t const& GetRespawnTime() const { return m_respawnTime; }
     [[nodiscard]] time_t GetRespawnTimeEx() const;
-- 

`

**Comment by Footman** [comment]
```
---
 src/server/game/AI/CreatureAI.cpp             | 10 ++----
 src/server/game/AI/CreatureAI.h               |  1 +
 .../game/AI/ScriptedAI/ScriptedCreature.cpp   |  5 +++
 .../game/AI/ScriptedAI/ScriptedCreature.h     |  1 +
 .../game/Entities/Creature/Creature.cpp       | 31 +++++++++++++++++++
 src/server/game/Entities/Creature/Creature.h  |  2 ++
 6 files changed, 42 insertions(+), 8 deletions(-)

diff --git a/src/server/game/AI/CreaturaeAI.cpp b/src/server/game/AI/CreatureAI.cpp
index a1604ffb4..c7382f725 100644
--- a/src/server/game/AI/CreatureAI.cpp
+++ b/src/server/game/AI/CreatureAI.cpp
@@ -21,12 +21,7 @@ public:
 
     bool Execute(uint64 /*eventTime*/, uint32 /*updateTime*/) override
     {
-        _owner.DespawnOrUnsummon();
-        _owner.Respawn();
-        if (_owner.IsVehicle()) // use the same sequence of addtoworld, aireset may remove all summons!
-        {
-            _owner.GetVehicleKit()->Reset(true);
-        }
+        _owner.DespawnOnEvade();
         return true;
     }
 
@@ -41,8 +36,7 @@ public:
 
     bool Execute(uint64 /*eventTime*/, uint32 /*updateTime*/) override
     {
-        _owner.SetVisible(true);
-        _owner.AI()->Reset(); // avoids issues with triggers/stalkers by visibility
+        _owner.RespawnOnEvade();
         return true;
     }
 
diff --git a/src/server/game/AI/CreatureAI.h b/src/server/game/AI/CreatureAI.h
index 848a58502..e485ca73c 100644
--- a/src/server/game/AI/CreatureAI.h
+++ b/src/server/game/AI/CreatureAI.h
@@ -103,6 +103,7 @@ public:
 
     virtual void SummonedCreatureDespawn(Creature* /*summon*/) {}
     virtual void SummonedCreatureDies(Creature* /*summon*/, Unit* /*killer*/) {}
+    virtual void SummonedCreatureDespawnAll() {}
 
     // Called when hit by a spell
     virtual void SpellHit(Unit* /*caster*/, SpellInfo const* /*spell*/) {}
diff --git a/src/server/game/AI/ScriptedAI/ScriptedCreature.cpp b/src/server/game/AI/ScriptedAI/ScriptedCreature.cpp
index 6f560e864..c0d226a14 100644
--- a/src/server/game/AI/ScriptedAI/ScriptedCreature.cpp
+++ b/src/server/game/AI/ScriptedAI/ScriptedCreature.cpp
@@ -604,6 +604,11 @@ void BossAI::SummonedCreatureDespawn(Creature* summon)
     summons.Despawn(summon);
 }
 
+void BossAI::SummonedCreatureDespawnAll()
+{
+    summons.DespawnAll();
+}
+
 void BossAI::UpdateAI(uint32 diff)
 {
     if (!UpdateVictim())
diff --git a/src/server/game/AI/ScriptedAI/ScriptedCreature.h b/src/server/game/AI/ScriptedAI/ScriptedCreature.h
index 5b689afed..6968b459d 100644
--- a/src/server/game/AI/ScriptedAI/ScriptedCreature.h
+++ b/src/server/game/AI/ScriptedAI/ScriptedCreature.h
@@ -419,6 +419,7 @@ public:
 
     void JustSummoned(Creature* summon) override;
     void SummonedCreatureDespawn(Creature* summon) override;
+    void SummonedCreatureDespawnAll() override;
 
     void UpdateAI(uint32 diff) override;
 
diff --git a/src/server/game/Entities/Creature/Creature.cpp b/src/server/game/Entities/Creature/Creature.cpp
index 87b115008..1af6fcc5d 100644
--- a/src/server/game/Entities/Creature/Creature.cpp
+++ b/src/server/game/Entities/Creature/Creature.cpp
@@ -1976,6 +1976,37 @@ void Creature::DespawnOrUnsummon(uint32 msTimeToDespawn /*= 0*/)
         ForcedDespawn(msTimeToDespawn);
 }
 
+void Creature::DespawnOnEvade()
+{
+    SetVisible(false);
+    AI()->SummonedCreatureDespawnAll();
+    RemoveEvadeAuras();
+
+    float x, y, z, o;
+    GetRespawnPosition(x, y, z, &o);
+    SetHomePosition(x, y, z, o);
+    SetPosition(x, y, z, o);
+
+    if (IsFalling())
+    {
+        RemoveUnitMovementFlag(MOVEMENTFLAG_FALLING);
+    }
+
+    StopMoving();
+}
+
+void Creature::RespawnOnEvade()
+{
+    SetVisible(true);
+    UpdateMovementFlags();
+    AI()->Reset();
+    AI()->JustReachedHome();
+
+    if (IsVehicle()) // use the same sequence of addtoworld, aireset may remove all summons!
+    {
+        GetVehicleKit()->Reset(true);
+    }
+}
 void Creature::InitializeReactState()
 {
     if ((IsTotem() || IsTrigger() || IsCritter() || IsSpiritService()) && GetAIName() != "SmartAI" && !GetScriptId())
diff --git a/src/server/game/Entities/Creature/Creature.h b/src/server/game/Entities/Creature/Creature.h
index 725b22ff4..4f7611bd7 100644
--- a/src/server/game/Entities/Creature/Creature.h
+++ b/src/server/game/Entities/Creature/Creature.h
@@ -258,6 +258,8 @@ public:
     void RemoveCorpse(bool setSpawnTime = true, bool skipVisibility = false);
 
     void DespawnOrUnsummon(uint32 msTimeToDespawn = 0);
+    void DespawnOnEvade();
+    void RespawnOnEvade();
 
     [[nodiscard]] time_t const& GetRespawnTime() const { return m_respawnTime; }
     [[nodiscard]] time_t GetRespawnTimeEx() const;
-- 


```

**Comment by Si1ker** [comment]
@Footman  Did you got the build running?

```txt
3>scripts.lib(cs_misc.obj) : error LNK2019: unresolved external symbol "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl Player::GetPlayerName(void)" (?GetPlayerName@Player@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function "public: static bool __cdecl misc_commandscript::HandleGearStatsCommand(class ChatHandler *,char const *)" (?HandleGearStatsCommand@misc_commandscript@@SA_NPEAVChatHandler@@PEBD@Z)
3>scripts.lib(boss_ingvar_the_plunderer.obj) : error LNK2019: unresolved external symbol "public: void __cdecl Creature::_AddCreatureSpellCooldown(unsigned int,unsigned short,unsigned int)" (?_AddCreatureSpellCooldown@Creature@@QEAAXIGI@Z) referenced in function "public: virtual void __cdecl boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::UpdateAI(unsigned int)" (?UpdateAI@boss_ingvar_the_plundererAI@boss_ingvar_the_plunderer@@UEAAXI@Z)
3>scripts.lib(boss_icecrown_gunship_battle.obj) : error LNK2001: unresolved external symbol "public: void __cdecl Creature::_AddCreatureSpellCooldown(unsigned int,unsigned short,unsigned int)" (?_AddCreatureSpellCooldown@Creature@@QEAAXIGI@Z)
3>scripts.lib(boss_emerald_dragons.obj) : error LNK2001: unresolved external symbol "public: virtual void __cdecl WorldBossAI::SummonedCreatureDespawnAll(void)" (?SummonedCreatureDespawnAll@WorldBossAI@@UEAAXXZ)
```

**Comment by Si1ker** [comment]
@Footman Summons thing working, thanks for that!
I only have one question left before marking this as ready.

Do you have any strong reason to not use these?
```cpp
DespawnOrUnsummon();
Respawn(true);
```

I started the PR with those, in order to make it easier to implement this #6379 in the future. It won't trigger death and players will have always a new/fresh version of the boss, not the same one as per your proposal.

**Comment by Footman** [comment]
> @Footman Summons thing working, thanks for that!
> I only have one question: Do you have any strong reason to not use these?
> 
> ```c++
> DespawnOrUnsummon();
> Respawn(true);
> ```
> 
> I started the PR with those, in order to make it easier to implement this #6379 in the future. (it was reverted)
> It won't trigger death and players will have always a new/fresh version of the boss, not the same one, as per your proposal.
> 
> Note: Tested locally and working. Respawn is not required at the moment -> Putricide is getting the stalkers correctly each try

I replaces it with new functions void DespawnOnEvade(); void RespawnOnEvade();
normal despawn and respawn have functions that should not be called at this stage like removing completely all auras. So I cherry-picked only required functions for this part.

**Review by Footman — APPROVED** [review]
