### PR TITLE
fix(DB/gameobjects): Improve ZG Mining Spawns

### LINKED ISSUE #12122: ZG: Missing herb and Veins
### Current Behaviour

There are too few herbs and vein spots

### Expected Blizzlike Behaviour

need more herbs and vein spots

### Source

_No response_

### Steps to reproduce the problem

1. go to zg and look around to barely see any veins or herbs

### Extra Notes

_No response_

### AC rev. hash/commit

713cddc1ba534cd29b5d62c3f2fb4ed2626003c9

### Operating system

Manjaro x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by neifion-00000000**
Simiar to #12307 except with mining nodes

## Changes Proposed:
- Remove all existing ZG Thorium nodes (they should only exist in ZG anyway, and these are believed to be a complete set)
- Insert all ZG Thorium nodes (from sniff data)
- Pool them based on number seen

## Issues Addressed:

- Together with #12307 closes #12122

## SOURCE:
sniffed objects over 2 dozen runs

## Tests Performed:

- Checked to see 4 up in ZG 

## How to Test the Changes:

1. Goto ZG with mining and look for 4 mining nodes
2.  This can be tested at the same time as #12307 and are not meant to conflict

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by Gultask** [comment]
Saw no issues besides the one bad spawn that has been fixed in the last commit. So it's all good.

File: data/sql/updates/pending_db_world/rev_1657160513357568200.sql [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+(@OGUID+12, 180215, 309, 1977, 0, 1, 1, -11549.494140625, -1489.06103515625, 73.21334075927734375, 3.717553615570068359, 0, 0, -0.95881938934326171, 0.284016460180282592, 259200, 255, 1, 0), -- 180215 (Area: 0 - Difficulty: 148)
+(@OGUID+13, 180215, 309, 1977, 3380, 1, 1, -12145.384765625, -1941.7357177734375, 134.8932342529296875, 1.867502212524414062, 0, 0, 0.803856849670410156, 0.594822824001312255, 259200, 255, 1, 0), -- 180215 (Area: 3380 - Difficulty: 148)
+(@OGUID+14, 180215, 309, 1977, 0, 1, 1, -12063.4775390625, -1437.3966064453125, 130.2297821044921875, 1.256635904312133789, 0, 0, 0.587784767150878906, 0.809017360210418701, 259200, 255, 1, 0), -- 180215 (Area: 0 - Difficulty: 148)
+(@OGUID+15, 180215, 309, 1977, 3447, 1, 1, -11927.7021484375, -1756.9566650390625, 50.15846633911132812, 3.141592741012573242, 0, 0, -1, 0, 259200, 255, 1, 0); -- 180215 (Area: 3447 - Difficulty: 148)
+
+DELETE FROM `pool_gameobject` WHERE `guid` BETWEEN @OGUID+0 AND @OGUID+15;
+DELETE FROM `pool_template` WHERE `entry` IN (447);
+
+INSERT INTO `pool_template` (`entry`, `max_limit`, `description`) VALUES
+(447, 4, 'ZG Hakkari Throium Vein');
```
Comment (Nefertumm) [inline data/sql/updates/pending_db_world/rev_1657160513357568200.sql:30]:
```suggestion
(447, 4, 'ZG Hakkari Thorium Vein');
```

File: data/sql/updates/pending_db_world/rev_1657160513357568200.sql [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+(@OGUID+6, 447, 0, 'ZG Hakkari Throium Vein 7/16'),
+(@OGUID+7, 447, 0, 'ZG Hakkari Throium Vein 8/16'),
+(@OGUID+8, 447, 0, 'ZG Hakkari Throium Vein 9/16'),
+(@OGUID+9, 447, 0, 'ZG Hakkari Throium Vein 10/16'),
+(@OGUID+10, 447, 0, 'ZG Hakkari Throium Vein 11/16'),
+(@OGUID+11, 447, 0, 'ZG Hakkari Throium Vein 12/16'),
+(@OGUID+12, 447, 0, 'ZG Hakkari Throium Vein 13/16'),
+(@OGUID+13, 447, 0, 'ZG Hakkari Throium Vein 14/16'),
+(@OGUID+14, 447, 0, 'ZG Hakkari Throium Vein 15/16'),
+(@OGUID+15, 447, 0, 'ZG Hakkari Throium Vein 16/16');
```
Comment (Nefertumm) [inline data/sql/updates/pending_db_world/rev_1657160513357568200.sql:47]:
```suggestion
(@OGUID+0, 447, 0, 'ZG Hakkari Thorium Vein 1/16'),
(@OGUID+1, 447, 0, 'ZG Hakkari Thorium Vein 2/16'),
(@OGUID+2, 447, 0, 'ZG Hakkari Thorium Vein 3/16'),
(@OGUID+3, 447, 0, 'ZG Hakkari Thorium Vein 4/16'),
(@OGUID+4, 447, 0, 'ZG Hakkari Thorium Vein 5/16'),
(@OGUID+5, 447, 0, 'ZG Hakkari Thorium Vein 6/16'),
(@OGUID+6, 447, 0, 'ZG Hakkari Thorium Vein 7/16'),
(@OGUID+7, 447, 0, 'ZG Hakkari Thorium Vein 8/16'),
(@OGUID+8, 447, 0, 'ZG Hakkari Thorium Vein 9/16'),
(@OGUID+9, 447, 0, 'ZG Hakkari Thorium Vein 10/16'),
(@OGUID+10, 447, 0, 'ZG Hakkari Thorium Vein 11/16'),
(@OGUID+11, 447, 0, 'ZG Hakkari Thorium Vein 12/16'),
(@OGUID+12, 447, 0, 'ZG Hakkari Thorium Vein 13/16'),
(@OGUID+13, 447, 0, 'ZG Hakkari Thorium Vein 14/16'),
(@OGUID+14, 447, 0, 'ZG Hakkari Thorium Vein 15/16'),
(@OGUID+15, 447, 0, 'ZG Hakkari Thorium Vein 16/16');
```
