### PR TITLE
fix(Core/DB):Fix Missing Diplomat Quests Part 11,14,16 and Minor Guard Tower Fixes

### LINKED ISSUE #4725: The Missing Diplomat - A specific part does not trigger the Npc RP Event
related to https://github.com/chromiecraft/chromiecraft/issues/132
possible fix https://github.com/TrinityCore/TrinityCore/commit/49e40f48c9326ce55f2f1f0b7e9ed2768d055b47

 ISSUE: FACTION SIDE: Alliance

________________________________________________________________________________________________________________________________________
________________________________________________________________________________________________________________________________________

Alliance

##### CONTENT PHASE:

20-29

##### SMALL DESCRIPTION:
The Missing Diplomat quest - Theramore phase does not trigger the RP event (https://wowgaming.altervista.org/aowow/?quest=1324)
________________________________________________________________________________________________________________________________________

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Once you subdue Private Hendel, an RP event should start with Archmage Tervosh and Lady Jaina Proudmoore at the location of Private Hendel that allows you to advance / complete the quest.

##### CURRENT BEHAVIOUR:

The RP event does not start. 

Workaround for completing the quest -> move to the Theramore Magic tower and interact with the NPC there

##### STEPS TO REPRODUCE THE PROBLEM:

1. Advance with the quest line up to https://wowgaming.altervista.org/aowow/?quest=1324 
2. Subdue the NPC (note that during the time i performed the steps the NPC guards assisted me with lowering the target HP)
3. Once Private Hendel is subdued - the NPC RP event should start

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

### PR DESCRIPTION
**Pull request by LannyE**
## Changes Proposed:
-  This fixes the The Missing Diplomat quest chain to include Quest: 1250 and
add the end event.  
- Also converts Private Hendel, Archmage Tervosh, Mikhail,
and Tapoke Jahn to smart scripts from C++ scripts.
- Note: Core code zone_wetlands.cpp is no longer being used.  Commented out all calls in ScriptLoader.cpp

## Issues Addressed:

- Quests: 1249,1265,1324 (The Missing Diplomat) are missing important parts
of the quests including the end of the quest chain event.
- Fix some minor Guard orientations and add missing waypoints to Dustwallow Marsh
guard towers.

Closes #4725
Closes chromiecraft/chromiecraft#132

## Tests Performed:
- Ran through The Missing Diplomat quest chain starting at Quest: 1248
- Was able to see the end event and turn in quests near Private Hendel

Built without errors.

## How to Test the Changes:

- .go creature Mikhail
- .quest add 1248
- Go through the rest of the Missing Diplomat quest chain
- Give Slim Jahn a beat down and he should now have emotes and working texts
- Slim Jahn should only have one friend with texts
- Look for quest 1250 which was missing from Slim Jahn
- Guards should salute Archmage Tervosh upon teleporting in to Sentry Point Tower
- Hendel should have emotes when offering quest 1324
- Hendel should get help from surrounding guards who run when Theramore leadership arrives
- After defeating Hendel the Theramore leadership should arrive to save the day after you did all the work and take him away
- Theramore leadership should stay long enough for you to complete your quests
- Dustwallow Marsh - Sentry Point and North Point Tower should have more waypoint activity by the guards. 

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by pklloveyou** [comment]
```
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 496300 SourceType 9 EventType 60 TargetType 1 using non-existent Text id 0 for talker 4963, ignored.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 4962 SourceType 0 EventType 4 TargetType 1 using non-existent Text id 0 for talker 4962, ignored.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 497100 SourceType 9 EventType 60 TargetType 1 using non-existent Text id 0 for talker 4971, ignored.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 496200 SourceType 9 EventType 60 TargetType 1 using non-existent Text id 1 for talker 4962, ignored.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 496200 SourceType 9 EventType 60 TargetType 1 using non-existent Text id 2 for talker 4962, ignored.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 496300 SourceType 9 EventType 60 TargetType 1 using non-existent Text id 0 for talker 4963, ignored.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 518401 SourceType 9 EventType 60 TargetType 1 using non-existent Text id 1 for talker 5184, ignored.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 496700 SourceType 9 EventType 60 TargetType 1 using non-existent Text id 1 for talker 4967, ignored.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 496700 SourceType 9 EventType 60 TargetType 1 using non-existent Text id 2 for talker 4967, ignored.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 496700 SourceType 9 EventType 60 TargetType 1 using non-existent Text id 3 for talker 4967, ignored.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 496700 SourceType 9 EventType 60 TargetType 1 using non-existent Text id 4 for talker 4967, ignored.
```

**Comment by Si1ker** [comment]
> ```
> SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 496300 SourceType 9 EventType 60 TargetType 1 using non-existent Text id 0 for talker 4963, ignored.
> SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 4962 SourceType 0 EventType 4 TargetType 1 using non-existent Text id 0 for talker 4962, ignored.
> SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 497100 SourceType 9 EventType 60 TargetType 1 using non-existent Text id 0 for talker 4971, ignored.
> SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 496200 SourceType 9 EventType 60 TargetType 1 using non-existent Text id 1 for talker 4962, ignored.
> SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 496200 SourceType 9 EventType 60 TargetType 1 using non-existent Text id 2 for talker 4962, ignored.
> SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 496300 SourceType 9 EventType 60 TargetType 1 using non-existent Text id 0 for talker 4963, ignored.
> SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 518401 SourceType 9 EventType 60 TargetType 1 using non-existent Text id 1 for talker 5184, ignored.
> SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 496700 SourceType 9 EventType 60 TargetType 1 using non-existent Text id 1 for talker 4967, ignored.
> SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 496700 SourceType 9 EventType 60 TargetType 1 using non-existent Text id 2 for talker 4967, ignored.
> SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 496700 SourceType 9 EventType 60 TargetType 1 using non-existent Text id 3 for talker 4967, ignored.
> SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 496700 SourceType 9 EventType 60 TargetType 1 using non-existent Text id 4 for talker 4967, ignored.
> ```

@LannyE 🔼

**Comment by LannyE** [comment]
Sorry, about that.  I only had Private Hendel as needing Text added to the database.   I added these missing texts to the SQL and tested the quest chain again to make sure they talk correctly.

**Comment by pklloveyou** [comment]
Tested

**Comment by FrancescoBorzi** [comment]
good job @LannyE and thanks @Si1ker @pklloveyou for reviewing/testing this!

File: src/server/scripts/ScriptLoader.cpp [hunk 1]
```diff
@@ -812,7 +812,7 @@ void AddEasternKingdomsScripts()
     AddSC_undercity();
     AddSC_western_plaguelands();
     AddSC_westfall();
-    AddSC_wetlands();
+    //AddSC_wetlands();
```
Comment (Helias) [inline src/server/scripts/ScriptLoader.cpp:815]: why did you remove wetlands?

**Comment by Helias** [comment]
This PR is probably related to https://github.com/azerothcore/azerothcore-wotlk/issues/4725 ( https://github.com/chromiecraft/chromiecraft/issues/132 )

File: src/server/scripts/ScriptLoader.cpp (hunk 1 above)
Comment (LannyE) [reply src/server/scripts/ScriptLoader.cpp:815]: Because everything in that file has been converted to SAI.  It was only the Slim and Mikhail NPCs scripts.  

```SQL
void AddSC_wetlands()
{
    new npc_tapoke_slim_jahn();
    new npc_mikhail();
}
```
I just commented it out because I noticed that is how Alterac Mountains was done above it. 
Do you want me to do it a different way?  Should we just clear out that wetlands file?  I left it untouched.
