### PR TITLE
Fix(DB/CTM) Fix Onyxia float on ground at P2

### LINKED ISSUE #10190: Onyxia Float on ground  at P2
### Current Behaviour

as title

### Expected Blizzlike Behaviour

should float on air

### Source

_No response_

### Steps to reproduce the problem

1. go to Onyxia
2. attack till enter p2
3. watch if she is float on ground but not air

### Extra Notes

_No response_

### AC rev. hash/commit

da7f4da51639+

### Operating system

Ubuntu 20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by betayi**
## Changes Proposed:
-  Fix 10190
-  

## Issues Addressed:

- Closes #10190 

## Tests Performed:

- 
- 

## How to Test the Changes:

1.go c id 10184
2.damage to enter P2
3.watch if float on air but not on ground

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1642220996463864536.sql [hunk 1]
```diff
@@ -0,0 +1,2 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1642220996463864536');
+UPDATE `creature_template_movement` SET `Flight` = 1 WHERE `CreatureId` IN (10184,36538);
```
Comment (acidmanifesto) [inline data/sql/updates/pending_db_world/rev_1642220996463864536.sql:2]: line break

**Review by acidmanifesto — CHANGES_REQUESTED** [review]

**Review by acidmanifesto — APPROVED** [review]

**Comment by Nyeriah** [comment]
Don't forget the workflow labels please
