### PR TITLE
fix(DB/item_template): Add coin loot to fishing trunks

### LINKED ISSUE #5759: Fishing Trunks should not be empty
Original report: https://github.com/chromiecraft/chromiecraft/issues/582 by @Stump876

This issue applies to all trunks caught when fishing:
- Tightly Sealed Trunk (20708)
- Watertight Trunk (21113)
- Iron Bound Trunk (21150)
- Mithril Bound Trunk (21228)

According to video evidence from [Classic](https://www.youtube.com/playlist?list=PLfYbGw3kDf9-bgj8-UWHLkWF4KvrNhS91) and [Cataclysm](https://www.youtube.com/watch?v=QMNpj3NmIss) these trunks should always at least contain coins and have a chance to get additional (multiple) items. But in AC's World DB `minMoneyLoot`and `maxMoneyLoot` are currently zero for all trunks.

#### WHAT CLIENT DO YOU PLAY ON?
- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION
- [x] Alliance
- [x] Horde

##### CONTENT PHASE:
- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:
Watertight chests occasionally are empty. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
It should contain something.
[https://www.wowhead.com/item=21113/watertight-trunk#contains](https://www.wowhead.com/item=21113/watertight-trunk#contains)

##### STEPS TO REPRODUCE THE PROBLEM:
1. .additem 21113 
2. Open boxes and you should get an empty one occasionally
3. 
4.

##### EXTRA NOTES:
Testing on a local server, spawning 16 I had 2 come up empty.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

### PR DESCRIPTION
**Pull request by necropola**
Co-author: @Hacki95 

## Changes Proposed:
- Add coin loot to Fishing Trunks

## Issues Addressed:
- Closes #5759
- Closes https://github.com/chromiecraft/chromiecraft/issues/582

## SOURCE:
- [YT Playlist of Fishing Trunk Unboxing Videos on Classic](https://www.youtube.com/playlist?list=PLfYbGw3kDf9-bgj8-UWHLkWF4KvrNhS91)
- [Fishing Trunk Unboxing Video on Cataclysm](https://www.youtube.com/watch?v=QMNpj3NmIss)

## Tests Performed:
- SQL statements successfully executed
- Tested in game

## How to Test the Changes:
- `.additem 20708 10`
- `.additem 21113 10`
- `.additem 21150 10`
- `.additem 21128 10`
- Loot and observe that the trunks now always contain at least some coins

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

File: data/sql/updates/pending_db_world/rev_1620674399849229322.sql [hunk 1]
```diff
@@ -0,0 +1,5 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1620674399849229322');
+UPDATE `item_template` SET `minMoneyLoot`=50, `maxMoneyLoot`=100 WHERE `entry`=20708; -- Tightly Sealed Trunk
+UPDATE `item_template` SET `minMoneyLoot`=100, `maxMoneyLoot`=200 WHERE `entry`=21113; -- Watertight Trunk
+UPDATE `item_template` SET `minMoneyLoot`=100, `maxMoneyLoot`=200 WHERE `entry`=21150; -- Iron Bound Trunk
+UPDATE `item_template` SET `minMoneyLoot`=100, `maxMoneyLoot`=200 WHERE `entry`=21228; -- Mithril Bound Trunk
```
Comment (Si1ker) [inline data/sql/updates/pending_db_world/rev_1620674399849229322.sql:5]:
```suggestion
UPDATE `item_template` SET `minMoneyLoot`=100, `maxMoneyLoot`=200 WHERE `entry` IN (
21113, -- Watertight Trunk
21150, -- Iron Bound Trunk
21228); -- Mithril Bound Trunk
```

**Review by Si1ker — CHANGES_REQUESTED** [review]

File: data/sql/updates/pending_db_world/rev_1620674399849229322.sql (hunk 1 above)
Comment (necropola) [reply data/sql/updates/pending_db_world/rev_1620674399849229322.sql]: I wonder how long it will take until this optimization saved more cpu cycles than pushing the change through CI did cost. 😼

**Review by necropola — COMMENTED** [review]
The values of those trunks are logically independent from another. Blizzard just happened to choose them identical for 3 of the 4 trunks. Hence I did not merge the update of 3 of them into one statement.  Anyway, As You Like It. Let's have coins in the trunks and thereby make them more blizz-like.

Is there anything more I can do to **address the requested change**?

**Comment by Si1ker** [comment]
@necropola what do you mean? My review was just to merge 3 queries that do the exact same thing with different entry so...

This is less efficient...
```sql
UPDATE `item_template` SET `minMoneyLoot`=100, `maxMoneyLoot`=200 WHERE `entry`=21113; -- Watertight Trunk
UPDATE `item_template` SET `minMoneyLoot`=100, `maxMoneyLoot`=200 WHERE `entry`=21150; -- Iron Bound Trunk
UPDATE `item_template` SET `minMoneyLoot`=100, `maxMoneyLoot`=200 WHERE `entry`=21228; -- Mithril Bound Trunk
```

... than this:
```sql
UPDATE `item_template` SET `minMoneyLoot`=100, `maxMoneyLoot`=200 WHERE `entry` IN (
21113, -- Watertight Trunk
21150, -- Iron Bound Trunk
21228); -- Mithril Bound Trunk
```

Will it do the same and exact thing? Yes.

**Review by Si1ker — APPROVED** [review]

**Comment by necropola** [comment]
@Si1ker I fully understand,why you requested the change and of course it is more efficient to combine the update into one statement. I just wanted to explain why I intentionally did not combine them in the first place, i. e.  a clarity/maintainability over performance assessment.
But since you are much, much more experienced in this, I'm happy to accept the change.
