### PR TITLE
fix(Core/Movement):  Fix multiple creature movement issues

### LINKED ISSUE #4441: The wrong movement in the water
##### CURRENT BEHAVIOUR:
The monster kept moving up and down in the water

##### EXPECTED BLIZZLIKE BEHAVIOUR:
It should be close to the target. Unless the target is moving up and down, the monster will not move

##### STEPS TO REPRODUCE THE PROBLEM:
1. update to https://github.com/azerothcore/azerothcore-wotlk/commit/504a788c63265a85ac730ce5dd6c5a067f25ee67
2.Attack a monster in the water and watch it move

##### EXTRA NOTES:
I think this commit caused the bug
https://github.com/azerothcore/azerothcore-wotlk/commit/c8f43d85849c40e08d0da38913489426a0c35388

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/504a788c63265a85ac730ce5dd6c5a067f25ee67

##### OPERATING SYSTEM:
ubuntu 18.04
##### MODULES:
none

https://user-images.githubusercontent.com/18187177/106883557-193ae480-671b-11eb-8f90-69001e0f75d4.mp4

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/96382393-the-wrong-movement-in-the-water?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #4466: [raid]Icecrown Citadel any difficulty Nerub'ar Broodkeeper evading combat
##### CURRENT BEHAVIOUR:
NPC [Nerub'ar Broodkeeper](https://wotlkdb.com/?npc=36725) Evades combat constantly.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Not evade combat.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Clone [990e494](https://github.com/azerothcore/azerothcore-wotlk/commit/990e4943bad54c5c64e7f6bf0b71c44b43c05211)
2. Follow installation instructions on [AzerothCore bash dashboard](https://www.azerothcore.org/wiki/Install-with-AC-Dashboard)
3. Log in as any character or gm char with .gm off 
4. Go into Icecrown Citadel Raid
5. Try to kill [Nerub'ar Broodkeeper](https://wotlkdb.com/?npc=36725)

##### EXTRA NOTES:
[video demonstration](https://youtu.be/Ws6VQzYgiTc)

##### OPERATING SYSTEM:
Ubuntu 20.04 LTS

##### MODULES:
No modules

##### OTHER CUSTOMIZATIONS:
No customization

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/96426585-raid-icecrown-citadel-any-difficulty-nerub-ar-broodkeeper-evading-combat?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #4661: ICC Bosses stuck in the floor after flying [$15]
Bosses with inhibit type 5 in the floor and not looking correct

##### CURRENT BEHAVIOUR:

currently affecting:

Blood Queen Lanathel
Rimefang
Spinestalker
Sindragosa

https://i.imgur.com/0GOhoTH.jpg
https://cdn.discordapp.com/attachments/813104786043699220/814572752617996348/unknown.png

Not this, they should be ont he ground not half way the flying flag is not being removed.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Not this, they should be ont he ground not half way the flying flag is not being removed.

##### STEPS TO REPRODUCE THE PROBLEM:

clone latest ac:
https://github.com/azerothcore/azerothcore-wotlk/commit/695a7402ad809410f74cef08af5f184ecff84d9c

<bountysource-plugin>

---
There is a **[$15 open bounty](https://www.bountysource.com/issues/96796144-icc-bosses-stuck-in-the-floor-after-flying?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Footman**
## Changes Proposed:
Fix multiple issues connected to creature movement.
- a lot of swimming creatures were on the ground instead of swimming (by SQL file). closes #4441
- summon spells were spawning npcs in wrong / random locations (if used for multiple spawns) in EffectSummonType()
- fix flying bosses wrong animation (flying in earth) by removing SetHover(). closes #4661
- fix Nerub'ar Broodkeeper (by setting UNIT_STATE_NO_ENVIRONMENT_UPD). closes #4466
- fix scale of collision was calculated wrong with scale auras for example https://www.wowhead.com/npc=39751 in SetObjectScale()
- probably fix charging when cant find path to the target in EffectCharge() #4808
- Pet should follow owner at specific angle. So check PositionOkay() needs to remove it.
- Fix default collision height in GetCollisionHeight(). Because of this player collision returned wrong height.
- may close some from #5022.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@Footman the build is failing, please have a look:

```
src/server/game/Movement/MovementGenerators/PointMovementGenerator.cpp:21:59: fatal error: '&&' within '||' [-Wlogical-op-parentheses]
    if (unit->HasUnitState(UNIT_STATE_NOT_MOVE) || cOwner && cOwner->IsMovementPreventedByCasting())
src/server/game/CMakeFiles/game.dir/build.make:2175: recipe for target 'src/server/game/CMakeFiles/game.dir/Movement/MovementGenerators/PointMovementGenerator.cpp.o' failed
                                                ~~ ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/server/game/Movement/MovementGenerators/PointMovementGenerator.cpp:21:59: note: place parentheses around the '&&' expression to silence this warning
    if (unit->HasUnitState(UNIT_STATE_NOT_MOVE) || cOwner && cOwner->IsMovementPreventedByCasting())
                                                          ^
                                                   (                                               )
1 error generated.
```

**Comment by Yehonal** [comment]
Thanks! I'll take a look at it tomorrow

**Comment by Winfidonarleyan** [comment]
Looks good

**Comment by disclosurez** [comment]
same issue with lanathel?

image

**Comment by disclosurez** [comment]
svalna also completely broken.

**Comment by disclosurez** [comment]
sindragosa also seems bugged

File: src/server/game/Entities/Unit/Unit.cpp [hunk 1]
```diff
@@ -3789,7 +3789,7 @@ void Unit::UpdateEnvironmentIfNeeded(const uint8 option)
             {
                 ground_z = (c->CanSwim() && liquidData.level > INVALID_HEIGHT) ? liquidData.level : temp;
                 bool canHover = c->CanHover();
-                isInAir = flyingBarelyInWater || (G3D::fuzzyGt(GetPositionZ(), ground_z + (canHover ? GetFloatValue(UNIT_FIELD_HOVERHEIGHT) : 0.0f) + GROUND_HEIGHT_TOLERANCE) || G3D::fuzzyLt(GetPositionZ(), ground_z - GROUND_HEIGHT_TOLERANCE)); // Can be underground too, prevent the falling
+                isInAir = flyingBarelyInWater || (G3D::fuzzyGt(GetPositionZ(), ground_z + (canHover ? GetFloatValue(UNIT_FIELD_HOVERHEIGHT) : 0.0f) + 0.75f) || G3D::fuzzyLt(GetPositionZ(), ground_z - 1.f)); // Can be underground too, prevent the falling
```
Comment (FrancescoBorzi) [inline src/server/game/Entities/Unit/Unit.cpp:3792]: @Footman  shall we wrap these magic numbers into constants? so they have a name that describes what they are

Comment (Yehonal) [reply src/server/game/Entities/Unit/Unit.cpp:3792]: Indeed, but I'm also curious why those specific values. What 0.75 and 1.f are exactly/practically?

File: src/server/game/Spells/SpellEffects.cpp [hunk 2]
```diff
@@ -5069,7 +5067,7 @@ void Spell::EffectCharge(SpellEffIndex /*effIndex*/)
                 m_caster->GetFirstCollisionPosition(pos, dist, angle);
             }
 
-            m_caster->GetMotionMaster()->MoveCharge(pos.m_positionX, pos.m_positionY, pos.m_positionZ);
+            m_caster->GetMotionMaster()->MoveCharge(pos.m_positionX, pos.m_positionY, pos.m_positionZ + 0.5f);
```
Comment (FrancescoBorzi) [inline src/server/game/Spells/SpellEffects.cpp:5070]: same here

File: src/server/game/Spells/SpellEffects.cpp [hunk 3]
```diff
@@ -2449,12 +2449,10 @@ void Spell::EffectSummonType(SpellEffIndex effIndex)
 
                         TempSummonType summonType = (duration <= 0) ? TEMPSUMMON_DEAD_DESPAWN : TEMPSUMMON_TIMED_DESPAWN;
 
-                        uint32 currMinionsCount = m_caster->m_Controlled.size();
-                        uint32 totalNumGuardians = numSummons + currMinionsCount;
                         for (uint32 count = 0; count < numSummons; ++count)
                         {
                             Position pos;
-                            if (totalNumGuardians == 1)
+                            if (count == 0)
```
Comment (Yehonal) [inline src/server/game/Spells/SpellEffects.cpp:2455]: Doing so will bug the multiple spawn of guardians again, practically: when you summon more than one guardian they will overlap (because this code is called 1 time for every summon and the count will always be 0)

A better logic is needed here

File: src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp [hunk 4]
```diff
@@ -234,7 +233,7 @@ bool FollowMovementGenerator<T>::PositionOkay(T* owner, Unit* target, float rang
     if (owner->GetExactDistSq(target) > G3D::square(owner->GetCombatReach() + target->GetCombatReach() + range))
         return false;
 
-    return !owner->IsPet() || !angle || angle->IsAngleOkay(target->GetRelativeAngle(owner)); // need to check - dont think we need !pet exception here because there are scripts with MoveFollow that require angle
+    return !angle || angle->IsAngleOkay(target->GetRelativeAngle(owner));
```
Comment (Yehonal) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp:236]: we added that `!owner->IsPet()` check to fix something about pet. I don't remember exactly what but why you removed it? what was the bug?

File: src/server/game/Entities/Unit/Unit.cpp (hunk 1 above)
Comment (Footman) [reply src/server/game/Entities/Unit/Unit.cpp:3792]: this part can be reverted. but i found often Z calculattion mistake in range of 1.f and not 0.5

File: src/server/game/Spells/SpellEffects.cpp (hunk 2 above)
Comment (Footman) [reply src/server/game/Spells/SpellEffects.cpp:5070]: this part should fix charge when path was not found but need more tests

File: src/server/game/Entities/Unit/Unit.cpp (hunk 1 above)
Comment (Yehonal) [reply src/server/game/Entities/Unit/Unit.cpp:3792]: Could be it related to the dimension of the unit? maybe we could use a more dynamic value here such as the collisionheight

File: src/server/game/Spells/SpellEffects.cpp (hunk 3 above)
Comment (Footman) [reply src/server/game/Spells/SpellEffects.cpp:2455]: there is specific place for guarding summoning. not this one.
some spells use this code and are broken because of this

File: src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp (hunk 4 above)
Comment (Footman) [reply src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp:236]: i dont know why you added pet check there. pet has to have right angle relative to owner as well. and requires this check

File: src/server/game/Entities/Unit/Unit.cpp (hunk 1 above)
Comment (Footman) [reply src/server/game/Entities/Unit/Unit.cpp:3792]: > Could be it related to the dimension of the unit? maybe we could use a more dynamic value here such as the collisionheight

i dont know this. i just see pathgenerator sometimes placing points too high in the middle of the curve

Comment (Yehonal) [reply src/server/game/Entities/Unit/Unit.cpp:3792]: if you are not sure, please use a constant anyway, we worked a lot to remove all the hardcoded floats and it's not so good to add more of them now

File: src/server/game/Spells/SpellEffects.cpp (hunk 2 above)
Comment (Yehonal) [reply src/server/game/Spells/SpellEffects.cpp:5070]: Same thing, please use a constant to no add further hardcoded values

File: src/server/game/Spells/SpellEffects.cpp (hunk 3 above)
Comment (Yehonal) [reply src/server/game/Spells/SpellEffects.cpp:2455]: we can revert back it for now and improve this logic in future

**Review by Yehonal — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
marking as [To be merged] as @Footman has been testing this with real players and no issues were found
