### PR TITLE
fix(Scripts/BlackrockSpire): Improved Kormok encounter.

### LINKED ISSUE #9101: Boss of D2 set questline Kormok issues
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

[Kormok](https://wowgaming.altervista.org/aowow/?npc=16118) summoned by [Brazier of Beckoning](https://wowgaming.altervista.org/aowow/?item=22052). Current state:
1. After summon Kormok is instantly  start attacking random player in 50y range
2. Despawn timer of Kormok about 30 seconds
3. Kormok doesn't have [Bone Armor](https://wowgaming.altervista.org/aowow/?spell=16431) cast script after summon. Only combat script.
4. [Summon Bone Minions](https://wowgaming.altervista.org/aowow/?spell=27687) doesn't work
5. Incorrect  Bone Mages spawn script.
6. Kormok doesn't have yells

https://user-images.githubusercontent.com/85256266/141074569-ad7104ca-3a5d-4b6f-91a8-81312b010abe.mp4

### Expected Blizzlike Behaviour

1. Kormok should not attack after summon. Only if  someone in agro range
2. Kormok remain until defeated. There is no need to resummon him upon wiping, or even if the brazier holder leaves the instance or group. Only one Kormok per instance
3. Kormok should cast Bone Armor in 5 seconds after summon
4. Summon Bone Minions script's timers is correct(10s after start and repeat every 12s), but it doesn't work. Missing 4x[Bone Minions](https://wowgaming.altervista.org/aowow/?npc=16119)
5. Kormok should spawn 2xBone Mages at 25% adn 50%
6. Kormok should have on summon yell and combat one

### Source

Wowwiki [Kormok](https://wowwiki-archive.fandom.com/wiki/Kormok?oldid=2161724)
>He will summon waves of 4 skeletal warriors every 10–15 seconds. They are non-elite with 1500 life and will go down easy to AoE. At 50% and 25% of life he will summon 2 lvl 60 elite Skeletal Mages. They will focus fire on healer immediately. They also will cast a Fire AoE spell centered on themselves every 5 seconds. The key to the fight is to switch DPS and kill mages as soon as they spawn. If DPS on Kormok continues, it's possible to have 4 of them spawned at same time.

Wowhead [Kormok](https://tbc.wowhead.com/npc=16118/kormok)

https://youtu.be/yp0BskbS3vw?t=3083

### Steps to reproduce the problem

.go c id 10508 - teleport to Ras
.cast 27201

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/12e92b58082dfda8b73b50aa97b98b9479bb7629

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #9101

## Changes Proposed:
- Removed SAI scripts and reimplemented C++ script.
- Added missing texts
- Corrected spells and actions.
- Corrected summon spells.

## Issues Addressed:

- Closes #9101

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

.go c id 10508 - teleport to Ras
.cast 27201

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/scripts/EasternKingdoms/Scholomance/boss_kormok.cpp [hunk 1]
```diff
@@ -0,0 +1,247 @@
...
+ * option) any later version.
+ *
+ * This program is distributed in the hope that it will be useful, but WITHOUT
+ * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
+ * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
+ * more details.
+ *
+ * You should have received a copy of the GNU General Public License along
+ * with this program. If not, see <http://www.gnu.org/licenses/>.
+ */
```
Comment (IntelligentQuantum) [inline src/server/scripts/EasternKingdoms/Scholomance/boss_kormok.cpp:16]:
```suggestion
/*
 * This file is part of the AzerothCore Project. See AUTHORS file for Copyright information
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by the
 * Free Software Foundation; either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */
```

**Review by IntelligentQuantum — CHANGES_REQUESTED** [review]

File: src/server/scripts/EasternKingdoms/Scholomance/boss_kormok.cpp [hunk 2]
```diff
@@ -0,0 +1,247 @@
...
+    TALK_ENRAGE     = 2,
+    TALK_DEATH      = 3
+};
+
+class boss_kormok : public CreatureScript
+{
+public:
+    boss_kormok() : CreatureScript("boss_kormok") { }
+
+    struct boss_kormokAI : public ScriptedAI
```
Comment (Kitzunu) [inline src/server/scripts/EasternKingdoms/Scholomance/boss_kormok.cpp:63]: No. Use new script system

File: src/server/scripts/EasternKingdoms/Scholomance/boss_kormok.cpp [hunk 3]
```diff
@@ -0,0 +1,247 @@
...
+        {
+            return new spell_kormok_summon_bone_minionsSpellScript();
+        }
+};
+
+void AddSC_boss_kormok()
+{
+    new boss_kormok();
+    new spell_kormok_summon_bone_mages();
+    new spell_kormok_summon_bone_minions();
```
Comment (Kitzunu) [inline src/server/scripts/EasternKingdoms/Scholomance/boss_kormok.cpp:246]: .

**Review by Kitzunu — CHANGES_REQUESTED** [review]

File: src/server/scripts/EasternKingdoms/Scholomance/boss_kormok.cpp (hunk 2 above)
Comment (Kitzunu) [reply src/server/scripts/EasternKingdoms/Scholomance/boss_kormok.cpp:63]: https://github.com/azerothcore/azerothcore-wotlk/commit/430fa147fd340223400f6df968d0726510bb1c99

**Comment by IntelligentQuantum** [comment]
Tested

**Comment by UltraNix** [comment]
@Kitzunu Done.

**Review by Kitzunu — APPROVED** [review]

File: src/server/scripts/EasternKingdoms/Scholomance/boss_kormok.cpp [hunk 4]
```diff
@@ -0,0 +1,214 @@
...
+
+enum Says
+{
+    TALK_SUMMON     = 0,
+    TALK_AGGRO      = 1,
+    TALK_ENRAGE     = 2,
+    TALK_DEATH      = 3
+};
+
+struct boss_kormok : public ScriptedAI
```
[the remark this answers is not in the document]
Comment (UltraNix) [reply src/server/scripts/EasternKingdoms/Scholomance/boss_kormok.cpp:58]: No.

[the remark this answers is not in the document]
Comment (Kitzunu) [reply src/server/scripts/EasternKingdoms/Scholomance/boss_kormok.cpp:58]: Okay. I still havent learned the differences

**Review by IntelligentQuantum — APPROVED** [review]
