### PR TITLE
[Core/ Spell] Val'anyr Hammer of Ancient Kings Fix

### LINKED ISSUE #296: Proc Val'anyr, Hammer of Ancient Kings
**Description**: The proc of Val'anyr, Hammer of Ancient Kings is incorrect.

http://www.wowhead.com/item=46017/valanyr-hammer-of-ancient-kings

** ** Current behavior: The buff shield, has a proc when doing any buff, even when someone with Val'anyr enters a istance.

** ** Expected behavior: The Val'anyr should not have a proc in these two cases.

** Steps to reproduce the problem **:

1. Wear the Val'anyr and try to make any buff on your PG, or on another PG.
2. Wear the Val'anyr and try to enter or exit a dungeon several times.

** AC hash / commit **: 068ac593cb2894a16f3bfa78867fd901fc3122ed

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/40487213-proc-val-anyr-hammer-of-ancient-kings?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by talamortis**
##### CHANGES PROPOSED:

-  Fixed Val'anyr Hammer of Ancient Kings
-  

###### ISSUES ADDRESSED:

Closes #296 

##### TESTS PERFORMED:

Tested ingame on a paladin, before applying fix was applying blessing of kings on self to check proc.

after applying fix doing the same.

##### HOW TO TEST THE CHANGES:

1. Before applying the PR, Create a paladin or priest log in on that character
2. Spam cast buff effects on yourself (such as blessing of kings or power word fortitude)
3. See shield was applied.
4. Apply the fix
5. Log back in and do the same.

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

File: src/server/scripts/Spells/spell_item.cpp [hunk 1]
```diff
@@ -1501,6 +1501,39 @@ class spell_item_arcane_shroud : public SpellScriptLoader
         }
 };
 
+// 64415 - Val'anyr Hammer of Ancient Kings - Equip Effect
+class spell_item_valanyr_hammer_of_acient_kings : public SpellScriptLoader
```
Comment (Sdyess) [inline src/server/scripts/Spells/spell_item.cpp]: typo: its ancient

Comment (talamortis) [reply src/server/scripts/Spells/spell_item.cpp]: Thanks for pointing that out 👍  fixed the typo

**Comment by talamortis** [comment]
Thanks for Testing @poszer will merge and thanks for the feedback @Sdyess and correcting my typo :D
