### PR TITLE
[DB/Quest] Fix for quests 10990 10991 10992 #114

### LINKED ISSUE #114: Not work quest id 10990 10991 10992
Description: Quest:The Eagle's Essence	The Falcon's Essence	The Hawk's Essence
Error condition:overlap gameobject location and creature location

Steps to reproduce the problem:
1,	.quest add 10990	.go -2623.51 4564.12 139.95 530	(entry=22993)
2,	.quest add 10991	.go -3160.58 3805.88 60.3 530	(entry=22994)
3,	.quest add 10992	.go -4364 4619 -38.3 530		(entry=22992)

AC hash/commit:
cf9322a

Modules:
Nothing

Operating system: 
Windows 10

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/37267091-not-work-quest-id-10990-10991-10992?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by DantestyleXD**
**Changes proposed:**

-  "Delete" core's code created for GOBs on quest (Comment for tracking a backup)
-  Recreate SAIs for them and improve the event

**Target branch(es):** 
1.x

**Issues addressed:** 
Closes #114 

**Tests performed:** 
Tested and re-tested for improve the AI and all event and work

**Known issues and TODO list:**
Nothing to report (Maybe the fight event and NPCs abilities) 

----------------------------
Server: Local (Repo AzerothCore)
Last commit hash tested: 865e3d0c999059ec2ae7fdfb88bfc146f1ae1122
O.S.: Windows 10
Compiler: MS Visual Studio 2013

### CODE REVIEW

File: data/sql/dbfix/2016_08_27_01.sql [hunk 1]
```diff
@@ -0,0 +1,11 @@
...
+Issue: Not work quest id 10990 10991 10992 #114
+NPCs spawns are inside the Gobjs
+*/
+
+UPDATE gameobject_template SET AIName="SmartGameObjectAI", ScriptName = "" /*go_shrine_of_the_birds*/ WHERE entry IN (185551,185547,185553);
+DELETE FROM smart_scripts WHERE entryorguid IN (185551,185547,185553) AND source_type=1;
+INSERT INTO smart_scripts VALUES
+(185551,1,0,0,70,0,100,0,2,0,0,0,12,22992,7,60000,0,0,0,7,0,0,0,0,0,0,0,"Hawk Shrine - On Activate - Summon Creature 22992"),
+(185547,1,0,0,70,0,100,0,2,0,0,0,12,22993,7,60000,0,0,0,7,0,0,0,0,0,0,0,"Eagle Shrine - On Gossip Hello - Summon Creature 22993"),
+(185553,1,0,0,70,0,100,0,2,0,0,0,12,22994,7,60000,0,0,0,7,0,0,0,0,0,0,0,"Hawk Shrine - On Gossip Hello - Summon Creature 22994");
```
Comment (ShinDarth) [inline data/sql/dbfix/2016_08_27_01.sql]: this file should go under [data/sql/updates/pending_db_world](https://github.com/azerothcore/azerothcore-wotlk/tree/master/data/sql/updates/pending_db_world)

**Comment by Yehonal** [comment]
Ops, i've merged without the squash...sorry

However great work @DantestyleXD !
