### PR TITLE
fix(Scripts/Naxx): Thaddius Ball Lightning should check all players i…

### LINKED ISSUE #24372: [Raid-Naxx] Thaddius' ball lightning is being cast even with melee in range of boss
### Triage

Issue linked from CC: https://github.com/chromiecraft/chromiecraft/issues/8849

Triage Notes: Thaddius should start casting Ball Lightning repeatedly only when no player on his threat list is on his melee range.

On retail it seems that Thaddius occasionally uses Ball Lightning also when players are in his melee range (but I don't know if it is the same thing on wotlk).

Original Post Below: 

---
### Current Behaviour

https://github.com/user-attachments/assets/f97caba3-edbe-4ffd-babf-cf66833e31ab

Thad is casting ball lightning at current target, even though there is a player in melee range attacking him. 

### Expected Behaviour

He should never cast ball lightning if there is at least 1 player in melee range of him (not just the tank). 

### Source

https://warcraft.wiki.gg/wiki/Thaddius?oldid=127160

Image

https://www.warcrafttavern.com/wotlk/guides/thaddius-10/

Image

### Steps to reproduce the problem

1. have 1 player melee, but not main target of thad
2. have 2nd player main target of thad, and walk away
3. thad continues to cast ball lightning

### Extra Notes

Not sure if it checks for pets too, but I think it should include them? As well as any summons (sham guardian, item summons, etc). 

### Customizations

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a4ea6d60a24d1f499aaf8ca62d3f6b1ac857f823

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-chromiecraft-smartstone](https://github.com/chromiecraft/mod-chromiecraft-smartstone)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-evade-logging](https://github.com/heyitsbench/mod-evade-logging)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-quests](https://github.com/azerothcore/mod-pvp-quests)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by xDevICCI**
Ball Lightning was being cast even when melee players (other than the tank) were in range of the boss. Added IsAnyPlayerInMeleeRange() helper function to check if any player on the threat list is within melee range.

Closes #24372

## Changes Proposed:
This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

### AI-assisted Pull Requests

- [x] AI tools (e.g. ChatGPT, Claude, or similar) were used entirely or partially in preparing this pull request. Please specify which tools were used, if any.

Claude was used to help analyze the code and identify the root cause of the issue.

## Issues Addressed:
- Closes #24372

## SOURCE:
The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick).

Sources from the issue:
- https://warcraft.wiki.gg/wiki/Thaddius?oldid=127160
- https://www.warcrafttavern.com/wotlk/guides/thaddius-10/

Both sources confirm Ball Lightning should only be cast when no players are in melee range.

## Tests Performed:
This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [x] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing.

1. Start Thaddius encounter with at least 2 players
2. Have one player (tank) move away from melee range
3. Keep another player in melee range of Thaddius
4. Verify Thaddius does NOT cast Ball Lightning while any player is in melee range
5. Have all players move out of melee range
6. Verify Thaddius now casts Ball Lightning

## Known Issues and TODO List:

- [ ] The issue mentions pets/summons should possibly be checked too - this may need additional testing/confirmation

### CODE REVIEW

File: src/server/scripts/Northrend/Naxxramas/boss_thaddius.cpp [hunk 1]
```diff
@@ -327,7 +340,7 @@ class boss_thaddius : public CreatureScript
                     break;
             }
 
-            if (me->IsWithinMeleeRange(me->GetVictim()))
+            if (IsAnyPlayerInMeleeRange())
```
Comment (sogladev) [inline src/server/scripts/Northrend/Naxxramas/boss_thaddius.cpp:339]: This `IsAnyPlayerInMeleeRange` is better part of the `ballLightningEnabled` check.


```cpp
            else if (ballLightningEnabled && !IsAnyPlayerInMeleeRange)
```

File: src/server/scripts/Northrend/Naxxramas/boss_thaddius.cpp [hunk 2]
```diff
@@ -129,6 +129,19 @@ class boss_thaddius : public CreatureScript
         uint32 resetTimer{};
         bool ballLightningEnabled;
 
+        bool IsAnyPlayerInMeleeRange() const
+        {
+            for (auto const& ref : me->GetThreatMgr().GetThreatList())
+            {
```
Comment (sogladev) [inline src/server/scripts/Northrend/Naxxramas/boss_thaddius.cpp]: extra brackets can be removed

https://www.azerothcore.org/wiki/cpp-code-standards#brackets

**Comment by Nyeriah** [comment]
I faintly remember something like SelectNearestPlayer() existing

File: src/server/scripts/Northrend/Naxxramas/boss_thaddius.cpp (hunk 2 above)
Comment (xDevICCI) [reply src/server/scripts/Northrend/Naxxramas/boss_thaddius.cpp]: I forced pushed commit

File: src/server/scripts/Northrend/Naxxramas/boss_thaddius.cpp [hunk 3]
```diff
@@ -129,6 +129,15 @@ class boss_thaddius : public CreatureScript
...
 
+        bool IsAnyPlayerInMeleeRange() const
+        {
+            for (auto const& ref : me->GetThreatMgr().GetThreatList())
+                if (Unit* target = ref->getTarget())
+                    if (target->IsPlayer() && me->IsWithinMeleeRange(target))
+                        return true;
+            return false;
+        }
+
```
Comment (Kitzunu) [inline src/server/scripts/Northrend/Naxxramas/boss_thaddius.cpp:140]: You could just use SelectNearestTarget() to see if it returns anything within melee range

**Review by Nyeriah — APPROVED** [review]
