### PR TITLE
fix(DB/item_template_locale): Add Spanish translation for 'Wand of Allistarj'

### LINKED ISSUE #11411: (item_locale_template): 'Wand of Allistarj' missing Spanish translation
Originally reported by **Silkarx** at https://github.com/chromiecraft/chromiecraft/issues/3357

### Current Behaviour

Wand of Allistarj missing esES/esMX translation
2022-04-15 12_42_35-World of Warcraft

### Expected Blizzlike Behaviour

Expected "Varita de Allistarj" when using esES/esMX WoW clients

### Source

https://es.classic.wowhead.com/item=13065/varita-de-allistarj

### Steps to reproduce the problem

use Spanish wow client
.add 13065

### Extra Notes

image

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7518a7ccd69369b366f29d314baf3a72a61c3045

### Operating system

Ubuntu 20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by Si1ker**
## Changes Proposed:
-  Add esES/esMX translation for [Wand of Allistarj](https://classic.wowhead.com/item=13065/wand-of-allistarj)

## Issues Addressed:

- Closes #11411
- Closes https://github.com/chromiecraft/chromiecraft/issues/3357

## SOURCE:

https://es.classic.wowhead.com/item=13065/varita-de-allistarj

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1650071065104177600.sql [hunk 1]
```diff
@@ -0,0 +1,7 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1650071065104177600');
+
+DELETE FROM `item_template_locale` WHERE `ID`=13065 AND `locale` IN ('esES','esMX');
+INSERT INTO `item_template_locale` (`ID`, `locale`, `Name`, `Description`, `VerifiedBuild`) VALUES
+(13065, 'esES', 'Varita de Allistarj', '', '0'),
+(13065, 'esMX', 'Varita de Allistarj', '', '0');
```
Comment (Kitzunu) [inline data/sql/updates/pending_db_world/rev_1650071065104177600.sql:6]:
```suggestion
(13065, 'esES', 'Varita de Allistarj', '', 0),
(13065, 'esMX', 'Varita de Allistarj', '', 0);
```

**Review by Kitzunu — CHANGES_REQUESTED** [review]

**Review by Kitzunu — APPROVED** [review]
