### PR TITLE
Fixed Ashbringer visual on Tirion during Dk campaign

### LINKED ISSUE #635: hashbringer
**Description**: in last even of DK

**Current behaviour**: Tell us what happens
Thirion get the ashbringer, but the wrong version.

**Expected behaviour**: Tell us what should happen instead
The animation would have to transform in light version

wowscrnshot_091417_142936

**Steps to reproduce the problem**:

1. do quest 
2. 
3. 

**Branch(es):** Master

**AC hash/commit**: 9d2395e

**Operating system:** Ubuntu server 16.04.03 LTS

**Modules:** Are you using modules? if yes, list them

**Other Customizations:** Are you using any core/db patches or other customizations? If yes please specify them here.

### PR DESCRIPTION
**Pull request by Gargarensis**
**Changes proposed:**

-  Show Ashbringer instead of Corrupted Ashbringer on Tirion during DK campaign

**Issues addressed:** Closes #635  

**Tests performed:** I have not tested it yet, if someone can do it, it would be better (remember to clear the cache)

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1516785669788049600.sql [hunk 1]
```diff
@@ -0,0 +1,4 @@
+INSERT INTO version_db_world (`sql_rev`) VALUES ('1516785669788049600');
+
+-- Correct Ashbringer show on Tirion during DK campaign
+UPDATE `creature_equip_template` SET `ItemID1` = 13262 WHERE `CreatureID` = 29175 AND `ID` = 1;
```
Comment (ShinDarth) [inline data/sql/updates/pending_db_world/rev_1516785669788049600.sql]: please add a new line at the end of the file
