### PR TITLE
fix(Core/Player): Players are allowed to continue melee attacking on …

### LINKED ISSUE #5734: Hunter's auto attack does not stop for bandaging [$30]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Hunter's auto-shot will continue to tick and interrupt bandaging 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Bandage should stop all actions when activated. It is considered a channeled spell.
[https://wowwiki-archive.fandom.com/wiki/Channeling](https://wowwiki-archive.fandom.com/wiki/Channeling)
Testing with wand's auto-shoot works properly

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a hunter
2. Proceed to a training dummy
3. Range attack, and try to bandage
4.

##### EXTRA NOTES:

Original issue from Chiromicraft 
[https://github.com/chromiecraft/chromiecraft/issues/454](https://github.com/chromiecraft/chromiecraft/issues/454)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Did you fix this issue? Go claim the **[$30 bounty](https://www.bountysource.com/issues/98356231-hunter-s-auto-attack-does-not-stop-for-bandaging?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #6248: Difficulty switching from ranged -> melee auto attack on hunter
Original Chrimiecraft report [https://github.com/chromiecraft/chromiecraft/issues/795](https://github.com/chromiecraft/chromiecraft/issues/795)

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Auto shot switching to auto attack allows one melee hit before it stops attacing altogether.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should switch into melee auto attack in melee range (and back to auto shot if out) and continue attacking unless told to do otherwise.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Make sure auto attack/auto shot is checked in the combat tab of the interface
2. R click to start combat with ranged
3. When the mob gets close enough, the hunter does one swing with melee and stops attacking.

##### EXTRA NOTES:

https://user-images.githubusercontent.com/68164076/120938892-fb31c080-c6c9-11eb-941d-9f3a2fbfe38b.mp4

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99020491-difficulty-switching-from-ranged-melee-auto-attack-on-hunter?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
…autoshoot cancel.

Fixed #6248.

## Changes Proposed:
-  Player that is already melee attacking target should not send  `SMSG_CANCEL_COMBAT` packet on autoshoot cancel.

## Issues Addressed:

- Closes #6248.
- Closes #5734
- Closes chromiecraft/chromiecraft#795

## Tests Performed:

- Tested ingame.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by necropola** [comment]
@Ultranix It's a ChromieCraft issue. Please add:
- Closes https://github.com/chromiecraft/chromiecraft/issues/795

File: src/server/game/Entities/Player/Player.cpp [hunk 1]
```diff
@@ -21095,7 +21095,8 @@ void Player::SendAutoRepeatCancel(Unit* target)
     SendMessageToSet(&data, true);
 
     // To properly cancel autoshot done by client
-    SendAttackSwingCancelAttack();
+    if (!HasUnitState(UNIT_STATE_MELEE_ATTACKING))
+        SendAttackSwingCancelAttack();
```
Comment (FrancescoBorzi) [inline src/server/game/Entities/Player/Player.cpp:21099]:
```suggestion
    if (!HasUnitState(UNIT_STATE_MELEE_ATTACKING))
    {
        SendAttackSwingCancelAttack();
    }
```

**Comment by necropola** [comment]
I wonder what (now) happens when the target (or the hunter) moves out of melee range while auto attacking with a melee weapon. It should switch to auto shooting as soon as the target is far enough away (leaves the dead zone). But I fear, it might not.

The call to `SendAttackSwingCancelAttack()` was added to ensure that bandaging stops auto shooting (a minor issue, if you ask me), but it may very well mess up a core Hunter mechanic.

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by UltraNix** [comment]
@necropola Test it again.

**Comment by necropola** [comment]
@Ultranix I'll test it later tonight. This looks like a partial revert of https://github.com/azerothcore/azerothcore-wotlk/commit/5254aec645bd4c9b0a76c4cf37d56370d477fc12

**Comment by UltraNix** [comment]
Yes - it's a partial revert.

**Comment by necropola** [comment]
Cossmetic changes considered harmful. 😸

**Comment by necropola** [comment]
@UltraNix Looks good!
- Move into melee range while auto shooting: Hunter switches to Auto Attack (works!)
- Move out of melee range while auto attacking: Hunter switches to Auto Shot (works!)
- Bandaging while auto shooting: Auto Shot is **paused**, Bandaging is channeled, Auto Shot continues (works!)
- Bandaging while auto attacking: Auto Attack is **paused**, Bandaging is channeled, Auto Attack continues (works!)

We now have found the actual cause of the bandaging issue. :tada:

I guess that @FrancescoBorzi will ask to use braces in the `if`-statement.
I'd even suggest to consider reverting 5254aec entirely, or at least all cosmetic changes of which some are kinda weird like the use of a static local variable to hold the value `75`?
