### PR TITLE
fix(DB/Core) Fix the CLS damage system and update creature_classlevelstats

### LINKED ISSUE #4570: Update the creature damage system to CLS, too many issues currently. [$50]
##### CURRENT BEHAVIOUR:
After days of looking at damages I was able to pinpoint what was wrong. Note : This is mostly for vanilla, as it's what I work on, I don't know the state of the BC/Wrath content.
So this issue is fairly complex and large and many different issues tie together, it all comes to this, currently many creatures damages are completely wrong.
Because there was a damage column in creature_classlevelstats, I tought the CLS(classlevelstats) system was implemented for damages, **but it's not**. It's currently implemented for armor and health but not for damages.
- Currently the core loads hardcoded min and max dmg values from the database unlike trinitycore which has moved to the CLS system for damages in 2013/2014.  https://github.com/TrinityCore/TrinityCore/commit/3018ff4e6cbed7e3270df7727d1a04e28a901954

- This in addition to the current broken attack speeds values, completely changes the dps creatures should have, see https://github.com/azerothcore/azerothcore-wotlk/issues/4524 .Because with this older system attack speed changes the dps of creatures and this was never considered when updating creature damages values. It simply multiplies flat values by attack speed.

- The DamageModifier has some unknown effect or isn't even implemented at all, I talked about some AC devs about it and they don't know how it works, and if it even works, just that it should be avoided and not touch it.
In this CLS system this column would just be used to multiply the base template value instead.

- Some PRs have been done(and closed) to update damages to blizzlike but were rejected because people had no clue how this modifier works and tought values were too high (sometimes also caused by wrong speed)
See : 
https://github.com/azerothcore/azerothcore-wotlk/pull/2742 (this one is interesting, long covnersation)
https://github.com/azerothcore/azerothcore-wotlk/pull/2773
https://github.com/azerothcore/azerothcore-wotlk/pull/2766

- **Another issue with the pre CLS system and hardcoded min/max values is that they don't scale based off level**, a lvl 37 and 38 of the same creature will have the same dmg, while it should be different based on level like the other stats.
Example with beast lore, screenshot from AC, notice that lvl 57 and 59 creatures have the same dmg : 
image

- Finally: Too many creature damages are just completely wrong currently. Blizzard uses generic default damage value for most of their mobs and usualy elites have a simple multiplier like *3, it should be standardized.
- +having to manually fill dmg is just awful for modders and custom content :( 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Update to the new CLS system like trinitycore and cmangos, it should fix most of the ongoing issues with creature damages and heavily modernize it.
Here are some commits for it for TC : https://github.com/TrinityCore/TrinityCore/commit/3018ff4e6cbed7e3270df7727d1a04e28a901954
https://github.com/TrinityCore/TrinityCore/commit/cd76d3290719161db1c10b4c82de191db1cef7e8#diff-52a101f6175cb16c8a3879c92fcad3f9f4a263435ead333466a0f0f9428f00ce

##### AC HASH/COMMIT:
03e77ce66f2ccf55a4958faa4f36991ac4e95e2d

<bountysource-plugin>

---
There is a **[$50 open bounty](https://www.bountysource.com/issues/96556543-update-the-creature-damage-system-to-cls-too-many-issues-currently?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Hacki95**
## Changes Proposed:
-  Reenable the min/max damage CLS system in Creature::SelectLevel in Creature.cpp that has been disabled
-  Fix the underlying calculation issue in Creature::CalculateMinMaxDamage in StatSystem.cpp. AttackMultiplier was wrongfully multiplied with AttackSpeed. I used the reverse engineered CLS calculations TC/vmangos/cmangos use.
- Correct several wrong values in creaure_classlevelstats. Multiple damage_base and attackpower values were wrong before. I imported those values from TC's database.
- Correct several wrong DamageModifier values in creature_template. Using TC values for those aswell. The values we had before were mostly a flat 1 or completly off because they were based on the old system. With the new values the calculations lead to the desired result.
- Drop "mindamage", "maxdamage", "minrangedamage",  "maxrangedamage", "attackpower" and "rangedattackpower" from creature_template as those values aren't needed anymore.
- Fix all code that references those columns.
- Implement BaseVariance and RangeVariance (mostly for custom mobs).

## Issues Addressed:
- Closes #4570 

- While no other issues are open at the moment, using the CLS calculation instead of using fixed min/max values could potentially fix a lot of NPCs which had wrong sniffed data before. This bug existed since Commit 1 of AzerothCore :)

## Tests Performed:
- Tested "reload creature_template".
- Used the Spell "Beast Lore (ID=1462) on around 20 different mobs to check their min/max damage values. Those values now correctly change if a mob is for example Level 35 vs Level 36. All values I tested so far have been ~99% to the pre-calculated min/max values so it seems like the new damage_base values are correct or atleast much better than the values we had before.
- Played for a few hours on my offline realm and everything I tried looks great.

## How to Test the Changes:
 - Download the PR, compile the code and apply the DB update.
 - Make a Hunter or simply learn spell 1462. 
 - Fly around the world and check the mobs min/max attack values.

## Known Issues and TODO List:
- I have no way to confirm the values I took from TC are 100% accurate. BUT they are way better than the precalculated values we used before and every mob I tested has been correct.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@T1ti

File: src/server/game/Entities/Unit/StatSystem.cpp [hunk 1]
```diff
@@ -1075,10 +1075,10 @@ void Creature::CalculateMinMaxDamage(WeaponAttackType attType, bool normalized,
         weaponMaxDamage = 0.0f;
     }
 
-    // pussywizard: subtract value from database till its fixed (the way it worked before creature_levelstats damage implementation)
-    float attackPower      = GetTotalAttackPowerValue(attType) - (attType == RANGED_ATTACK ? GetCreatureTemplate()->rangedattackpower : GetCreatureTemplate()->attackpower);
-    float baseValue        = GetModifierValue(unitMod, BASE_VALUE) + (attackPower * GetAPMultiplier(attType, normalized) / 14.0f);
-    float basePct          = GetModifierValue(unitMod, BASE_PCT);
+    float attackPower      = GetTotalAttackPowerValue(attType);
+    float attackSpeedMulti = GetAPMultiplier(attType, normalized);
```
Comment (claudiodfc) [inline src/server/game/Entities/Unit/StatSystem.cpp:1079]: What is normalized doing here?

**Comment by pklloveyou** [comment]
After the test, I felt the damage value was higher

**Comment by T1ti** [comment]
> After the test, I felt the damage value was higher
> player level 70
> .go c id 17711
> before 10000-15000
> after 15000-20000
> Maybe that's the right damage?

It's still WIP, dmg modifier is not updated yet. This creature yo'ure testing has 35 dmg modifier and modifiers work differently between the two systems

You can try creatures that have x1 dmg modifier for now

File: src/server/scripts/Commands/cs_reload.cpp [hunk 2]
```diff
@@ -436,81 +436,79 @@ class reload_commandscript : public CommandScript
...
-            cInfo->trainer_race       = fields[37].GetUInt8();
-            cInfo->minrangedmg        = fields[38].GetFloat();
-            cInfo->maxrangedmg        = fields[39].GetFloat();
-            cInfo->rangedattackpower  = fields[40].GetUInt16();
-            cInfo->type               = fields[41].GetUInt8();
-            cInfo->type_flags         = fields[42].GetUInt32();
-            cInfo->lootid             = fields[43].GetUInt32();
-            cInfo->pickpocketLootId   = fields[44].GetUInt32();
-            cInfo->SkinLootId         = fields[45].GetUInt32();
+            cInfo->Entry                    = fields[0].GetUInt32();
```
Comment (pklloveyou) [inline src/server/scripts/Commands/cs_reload.cpp:439]: It's wrong. There shouldn't be

Comment (Hacki95) [reply src/server/scripts/Commands/cs_reload.cpp:439]: Ahhh you are right, will update it

File: src/server/game/Entities/Unit/StatSystem.cpp (hunk 1 above)
Comment (Hacki95) [reply src/server/game/Entities/Unit/StatSystem.cpp:1079]: In this case nothing. Its just that GetAPMultiplier expects this bool, and we get it from CalculateMinMaxDamage(). The function was called like that before, its just that it was calculated at the wrong spot.

`if (!normalized || GetTypeId() != TYPEID_PLAYER)
        return float(GetAttackTime(attType)) / 1000.0f;`

Thats how GetAPMultiplier calculates the modifier, so it doesnt matter in this case if normalized is true or false as we aren't a player.

I think this function is for something else when we use GetAPMultiplier on a player instead of a creature.

**Comment by Hacki95** [comment]
Added the missing DamageModifiers for Elite mobs/Bosses etc. And I removed the line from cs_reload()

**Comment by T1ti** [comment]
It's looking good. Different levels have different values as it should
image
image

I have tested some creatures dmg like magmadar which are off (even on TC) and will need to be corrected 
image
But this system makes it VERY easy to find the right values and blizzard most of the time uses a simple number. (since we now use the same system as blizz)
For example, modifier 17 gives the exact correct value for magmadar 
image (I made a sheet formula 
image)



-You need to delete the attack power column in creature_template and load the creature's AP from the CLS
-One column which is not entirely necessary but nice to give some flexibility to users, is to add a "variance" column, to let the users having custom damage range and not always max = min*1.5 (I saw someone complaining about that) TC already has that implemented.

But otherwise it looks pretty good atm, is off hands calculated properly ? TC did several commits for it.

But

**Comment by Hacki95** [comment]
I will take a look at the Attackpower column.
Should I fix the value for Magmadar in this PR?

Also about the variance, I might implement this but I am not sure yet. Mainly because I am not 100% sure how this mechanic is supposed to work, This might be something for a future PR but I will take a look!

About Off-Hands I am tbh not 100% sure, I assumed our calculations are already correct for this. I will double check!

Thanks for the feedback I appreciate it.

File: src/server/scripts/Commands/cs_reload.cpp [hunk 3]
```diff
@@ -436,81 +436,78 @@ class reload_commandscript : public CommandScript
...
-            cInfo->trainer_race       = fields[37].GetUInt8();
-            cInfo->minrangedmg        = fields[38].GetFloat();
-            cInfo->maxrangedmg        = fields[39].GetFloat();
-            cInfo->rangedattackpower  = fields[40].GetUInt16();
-            cInfo->type               = fields[41].GetUInt8();
-            cInfo->type_flags         = fields[42].GetUInt32();
-            cInfo->lootid             = fields[43].GetUInt32();
-            cInfo->pickpocketLootId   = fields[44].GetUInt32();
-            cInfo->SkinLootId         = fields[45].GetUInt32();
+            cInfo->DifficultyEntry[0]       = fields[1].GetUInt32();
```
Comment (pklloveyou) [inline src/server/scripts/Commands/cs_reload.cpp:439]: Or wrong, it should start from 0
```cInfo->DifficultyEntry[0]       = fields[0].GetUInt32();```

**Comment by pklloveyou** [comment]
It's a good damage calculation system, we should finish it anyway

File: src/server/scripts/Commands/cs_reload.cpp (hunk 3 above)
Comment (Hacki95) [reply src/server/scripts/Commands/cs_reload.cpp:439]: You are right I had an error in my thinking here, will update now

**Comment by Hacki95** [comment]
> 
> 
> It's a good damage calculation system, we should finish it anyway

Are you talking about the variance system or in general? I need some input if I should add that or better leave it out for now.

**Comment by pklloveyou** [comment]
I'm talking about current pr

File: src/server/scripts/Commands/cs_reload.cpp [hunk 4]
```diff
@@ -436,81 +436,76 @@ class reload_commandscript : public CommandScript
...
+                cInfo->resistance[i] = fields[40 + i - 1].GetUInt16();
+
+            cInfo->spells[0]                = fields[46].GetUInt32();
+            cInfo->spells[1]                = fields[47].GetUInt32();
+            cInfo->spells[2]                = fields[48].GetUInt32();
+            cInfo->spells[3]                = fields[49].GetUInt32();
+            cInfo->spells[4]                = fields[50].GetUInt32();
+            cInfo->spells[5]                = fields[51].GetUInt32();
+            cInfo->spells[6]                = fields[52].GetUInt32();
+            cInfo->spells[7]                = fields[53].GetUInt32();
```
Comment (pklloveyou) [inline src/server/scripts/Commands/cs_reload.cpp:490]: This can be done here if you have time
```
            for (uint8 i = 0; i < CREATURE_MAX_SPELLS; ++i)
                cInfo->spells[i] = fields[46 + i].GetUInt32();
```

Comment (Hacki95) [reply src/server/scripts/Commands/cs_reload.cpp:490]: Sure will add that

**Comment by pklloveyou** [comment]
If you need to test anything, please let me know

**Comment by Hacki95** [comment]
> 
> 
> If you need to test anything, please let me know

If you know how we could test if the Off-Hand damage is calculated correctly that would be really useful.

**Comment by pklloveyou** [comment]
I'm afraid I can't help you. I'm just a tester. My coding knowledge is too poor

**Comment by Hacki95** [comment]
I meant by testing if the values seem to be correct, I dont even know which NPCs I could check :D But no problem. maybe @T1ti has an idea.

**Comment by pklloveyou** [comment]
I think we should restore all previously changed DamageModifier values

**Comment by pklloveyou** [comment]
I've done it. I'll send you by email?

**Comment by Hacki95** [comment]
Yes please. shrexx.mobile@gmail.com

**Comment by pklloveyou** [comment]
I sent it

**Comment by Hacki95** [comment]
Thank you. Not sure if we should restore all damage modifiers as those worked with different values. I will try to create a diff and see how many of those are actually changed now and seem wrong.

**Comment by Zoidwaffle** [comment]
This is a pretty epic PR if all works out as intended - so just here to show a :+1:

**Comment by Hacki95** [comment]
Added variance to the calculation, thanks to https://github.com/TrinityCore/TrinityCore/commit/ccfa82e7d516c9d280fc7214fcf3672397c741ff

The offhand damage seems to be calculated correctly as far as I can tell. We seem to have a different issue here. Mobs need to be set to be able to dual wield with a script. TC added a new flag for that some time ago. Result is that some NPCs wear two weapons but don't attack with their offhand (example npc id 25437) while others like Van Cleef (ID 639) does use his offhand because he knows the spell dual wielding from his SmartAI script.

What we should do is to take a look at this issue and see if there are other NPCs which should use their offhand but don't.

But I see this as a seperate issue and will probably open an issue for that.


What we need to do now is compare the new damagemodifiers with our old ones and see if we get the expected values. From all my testing so far this implementation seems to be correct so far.

**Comment by T1ti** [comment]
> Thank you. Not sure if we should restore all damage modifiers as those worked with different values. I will try to create a diff and see how many of those are actually changed now and seem wrong.

Hacki is right, those were used for a compeltely different system, the only thing they have in common is the name, but they work diferently.

With the CLS the multiplier will almsot always be a simple number like 3 if it's an elite, or something like 5-25 if it's a boss
With the old systems it was used to correct values 
image

**Comment by Hacki95** [comment]
This needs testing now. I'm pretty sure everything I implemented is done correctly. Every mob I tested looks like they have their correct values.

I have been playing on my offline realm for hours now and encountered nothing out of the ordinary.

**Comment by pklloveyou** [comment]
.go c id 17711

**Comment by T1ti** [comment]
Follow up on Magmadar : He was even more wrong with the current system, he used to have : 
image

Which is almost 4x more than intended ! 

Anyways : I did a full comparison table of the current values, VS the new updated value we will ahve with the CLS : 
They both include their respective modifier from their own version, this is 100% accurate to comapre both.
**The small % differences when valeus are identical is because I rounded to integers, i'm not displaying decimals**

Here's a small preview of the comparison table, because github characters limit.
The full table is available here on google sheet, for vanilla creatures only https://docs.google.com/spreadsheets/d/1WYDYG_fx8FnmCAT17zUdEzeOErgi_2c0Py4mwv8yIzI/edit?usp=sharing 


entry | name | minlevel | OLDmindmg | CLS mindmg | % of old
-- | -- | -- | -- | -- | --
3 | Flesh Eater | 24 | 35 | 34 | 98.5%
6 | Kobold Vermin | 1 | 2 | 2 | 77.5%
25 | Mithril Mechanical Dragonling | 45 | 76 | 76 | 99.5%
29 | Kanrethad | 1 | 2 | 2 | 77.5%
30 | Forest Spider | 5 | 7 | 5 | 75.9%
31 | Furbolg | 1 | 2 | 2 | 77.5%
36 | Harvest Golem | 11 | 17 | 15 | 87.2%
38 | Defias Thug | 3 | 4 | 3 | 74.2%
40 | Kobold Miner | 6 | 9 | 7 | 77.7%
43 | Mine Spider | 8 | 11 | 10 | 94.5%
46 | Murloc Forager | 9 | 13 | 12 | 91.0%
48 | Skeletal Warrior | 21 | 32 | 31 | 95.3%
49 | Lesser Succubus | 20 | 2 | 29 | 1468.2%
54 | Corina Steele | 10 | 13 | 13 | 100.6%
55 | Mean Ed the Blacksmith | 20 | 2 | 29 | 1468.2%
60 | Ruklar the Trapper | 8 | 10 | 10 | 104.0%
61 | Thuros Lightfingers | 11 | 15 | 13 | 84.0%
62 | Gug Fatcandle | 4 | 2 | 4 | 201.5%
65 | Peasant Woman | 1 | 2 | 2 | 77.5%
66 | Tharynn Bouden | 10 | 13 | 10 | 75.4%
68 | Stormwind City Guard | 75 | 342 | 144 | 42.0%
69 | Timber Wolf | 2 | 2 | 2 | 107.5%
71 | Rankist | 5 | 2 | 5 | 265.7%
73 | Veraina the Apothecary | 40 | 2 | 56 | 2801.1%
74 | Kurran Steele | 10 | 13 | 13 | 100.6%
78 | Janos Hammerknuckle | 5 | 5 | 5 | 106.3%
79 | Narg the Taskmaster | 10 | 13 | 13 | 100.6%
80 | Kobold Laborer | 3 | 3 | 3 | 98.9%
82 | Crazy Leonetti | 7 | 2 | 9 | 448.1%
87 | Forest Troll Berserker | 2 | 2 | 2 | 107.5%
92 | Rock Elemental | 39 | 56 | 54 | 97.0%
93 | Centaur | 1 | 2 | 2 | 77.5%
94 | Defias Cutpurse | 5 | 7 | 5 | 75.9%
95 | Defias Smuggler | 11 | 17 | 15 | 87.2%
97 | Riverpaw Runt | 8 | 11 | 10 | 94.5%
98 | Riverpaw Taskmaster | 17 | 26 | 25 | 96.2%
99 | Morgaine the Sly | 10 | 13 | 13 | 100.6%
100 | Gruff Swiftbite | 12 | 17 | 13 | 74.6%
102 | Bronze Dragonspawn | 1 | 2 | 2 | 77.5%
103 | Garrick Padfoot | 5 | 5 | 5 | 106.3%
105 | Tall Strider | 1 | 2 | 2 | 77.5%
106 | Kodo Beast | 1 | 2 | 2 | 77.5%
107 | Raptor | 1 | 2 | 2 | 77.5%
112 | Priestess | 3 | 2 | 3 | 148.3%
113 | Stonetusk Boar | 5 | 7 | 5 | 75.9%
114 | Harvest Watcher | 14 | 22 | 20 | 92.4%
115 | Harvest Reaper | 17 | 26 | 25 | 96.2%
116 | Defias Bandit | 8 | 11 | 10 | 94.5%
117 | Riverpaw Gnoll | 11 | 17 | 15 | 87.2%
118 | Prowler | 9 | 13 | 9 | 68.3%
119 | Longsnout | 10 | 15 | 13 | 87.2%
120 | Forest Stalker | 9 | 13 | 12 | 91.0%
121 | Defias Pathstalker | 16 | 23 | 23 | 101.5%
122 | Defias Highwayman | 17 | 26 | 25 | 96.2%
123 | Riverpaw Mongrel | 14 | 20 | 20 | 101.6%
124 | Riverpaw Brute | 15 | 23 | 22 | 96.1%
125 | Riverpaw Overseer | 19 | 29 | 28 | 95.1%
126 | Murloc Coastrunner | 12 | 18 | 17 | 94.0%
127 | Murloc Tidehunter | 18 | 26 | 26 | 100.9%
128 | Angry Programmer Tweedle Dee | 59 | 102 | 72 | 70.4%
129 | Angry Programmer Tweedle Dum | 50 | 2 | 85 | 4230.4%
130 | Programmer Vendor | 62 | 2 | 108 | 5395.2%
138 | out Captain Lolo Longstriker | 1 | 2 | 2 | 77.5%
151 | Brog Hamfist | 10 | 13 | 10 | 75.4%
152 | Brother Danil | 5 | 5 | 4 | 79.7%
153 | Bethina | 35 | 2 | 49 | 2429.0%
154 | Greater Fleshripper | 16 | 25 | 23 | 93.4%
157 | Goretusk | 14 | 22 | 20 | 92.4%

**Comment by T1ti** [comment]
**Comparison mindmg of some bosses** (note that it is only relevent if the attack speeds are correct)
image
image
image
image
image
image

**Comment by Hacki95** [comment]
> 
> 
> .go c id 17711

Fixed. Had the wrong TBC values

**Comment by T1ti** [comment]
the attack speeds need to be fixed before we can really look at damages btw https://github.com/azerothcore/azerothcore-wotlk/pull/4637
image

**Comment by Hacki95** [comment]
There is a high chance that more bosses need tuning with the new system. I would generally see this as a new PR though because it has nothing to do with the system itself.

**Comment by T1ti** [comment]
Update : I compared the stockade, all of AC's valeus were COMPELTELY wrong by almsot x2 too much, while in TC all of them are right, someone went out of his way in TC to correct them

**Comment by T1ti** [comment]
> > Update : I compared the stockade, all of AC's values were COMPELTELY wrong by almost x2 too much, while in TC all of them are right, someone went out of his way in TC to correct them
> 
> DamageModifier?

nope, the base values were wrong in AC the modifier was only like 1.01 but with an insane base value
All of the creatures in stockade use 1.7x modifier of CLS

**Comment by pklloveyou** [comment]
> > > Update : I compared the stockade, all of AC's values were COMPELTELY wrong by almost x2 too much, while in TC all of them are right, someone went out of his way in TC to correct them
> > 
> > 
> > DamageModifier?
> 
> nope, the base values were wrong in AC the modifier was only like 1.01 but with an insane base value
> All of the creatures in stockade use 1.7x modifier of CLS. Verified from the book

Let me extract them

**Comment by T1ti** [comment]
boss example : (all of the bosses use 1.7 like the trash)
image
image

AC is clsoer for the trash, 10% off. But TC still is exactly 100% accurate with the book with 1.7x modifier 
image
image
image

**Comment by pklloveyou** [comment]
image
Do you need these?They come from TC

**Comment by Hacki95** [comment]
> 
> 
> image
> Do you need these?They come from TC

Already imported those values. Variance is just for custom npcs I think.

**Comment by pklloveyou** [comment]
AC 
image

TC 
After importing TC
image
image

**Comment by pklloveyou** [comment]
I feel the damage is much higher

**Comment by Hacki95** [comment]
> 
> 
> I feel the damage is much higher

You still got the wrong attacktimes. Pull again, the PR that fixes Attackspeeds just got merged. On my server its the same as in your Screenshot with the TC values.

**Comment by pklloveyou** [comment]
image
Now it's normal

**Comment by Hacki95** [comment]
> 
> 
> image
> Now it's normal

Its even more accurate now because it takes the mobs level into account! A level 17 miner makes less damage than a level 18 one.

**Comment by T1ti** [comment]
I spent a few hours checking and  fixing creatures based on the book. I am fixing TC's modifiers.
Note : TCs values were overall  lower than AC's on average(especially for raid bosses), and TC's values were usualy still a lot higher than Blizzard's. So this is gonna a HUGE nerf compared to the current state, yes blizzlike is easy and pservers were overtuned. Most dungeons creature damages have been reduced by **more than half** on average. Raid boss damages have been reduced by ~70%
**All of this is based on the bestiary book.** 
TC was overall much more blizzlike than AC and removed a lot of random bullshit, but it still had a lot of random bullshit.
I also fixed a few attack speeds that were still wrong even after the last update
```
-- Lucifron 35 -> 14.9
UPDATE `creature_template` SET `DamageModifier`='14.9' WHERE  `entry`=12118;
-- magmadar 35-> 17
UPDATE `creature_template` SET `DamageModifier`='17' WHERE  `entry`=11982;
-- golemagg 35-> 20
UPDATE `creature_template` SET `DamageModifier`='20' WHERE  `entry`=11988;
-- gehennas 35-> 14.9
UPDATE `creature_template` SET `DamageModifier`='14.9' WHERE  `entry`=12259;
-- shazzrah 35-> 14.9
UPDATE `creature_template` SET `DamageModifier`='14.9' WHERE  `entry`=12264;
-- baron geddon 35->14
UPDATE `creature_template` SET `DamageModifier`='14' WHERE  `entry`=12056;
-- Garr 35->18
UPDATE `creature_template` SET `DamageModifier`='18' WHERE  `entry`=12057;
-- Sulfuron Harbinger 35->16
UPDATE `creature_template` SET `DamageModifier`='16' WHERE  `entry`=12098;
-- Majordomo 35->14
UPDATE `creature_template` SET `DamageModifier`='14' WHERE  `entry`=12018;
-- Ragnaros 35-> 13 (fire)
UPDATE `creature_template` SET `DamageModifier`='13' WHERE  `entry`=11502;
```
```
-- Blackwing lair
-- Razorgore 35-> 22 
UPDATE `creature_template` SET `DamageModifier`='22' WHERE  `entry`=12435;
-- Vaelastraz aspeed 1600->2000 | 35
UPDATE `creature_template` SET `BaseAttackTime`='2000' WHERE  `entry`=13020;
-- death talon captain aspeed 2000->2400
UPDATE `creature_template` SET `BaseAttackTime`='2400' WHERE  `entry`=12467;
-- broodlord 35 ->25
UPDATE `creature_template` SET `DamageModifier`='25' WHERE  `entry`=12017;
-- firemaw 35->25
UPDATE `creature_template` SET `DamageModifier`='25' WHERE  `entry`=11983;
-- ebonroc 35->25
UPDATE `creature_template` SET `DamageModifier`='25', `BaseAttackTime`='2000' WHERE  `entry`=14601;
-- flamegor 35->25 | aspeed 1600->2000
UPDATE `creature_template` SET `DamageModifier`='25', `BaseAttackTime`='2000' WHERE  `entry`=11981;
-- chromaggus aspeed 1500->200 [ 35-> 30
UPDATE `creature_template` SET `DamageModifier`='30', `BaseAttackTime`='2000' WHERE  `entry`=14020;
-- nefarian 35
```

```
-- checked all creatures by id that have dmgModifier =/= 1, fixed those that were wrong by book values
UPDATE `creature_template` SET `DamageModifier`='3.5' WHERE  `entry`=1492;
UPDATE `creature_template` SET `DamageModifier`='4.25' WHERE  `entry`=1493;
UPDATE `creature_template` SET `DamageModifier`='1.7' WHERE  `entry`=1730;
UPDATE `creature_template` SET `DamageModifier`='1.7' WHERE  `entry`=1805;
UPDATE `creature_template` SET `DamageModifier`='1.7' WHERE  `entry`=1836;
UPDATE `creature_template` SET `DamageModifier`='1.6' WHERE  `entry`=1846;
UPDATE `creature_template` SET `DamageModifier`='1' WHERE  `entry`=1850;
UPDATE `creature_template` SET `DamageModifier`='2' WHERE  `entry`=1852;
UPDATE `creature_template` SET `DamageModifier`='2.3' WHERE  `entry`=1853;
UPDATE `creature_template` SET `DamageModifier`='1.75' WHERE  `entry`=2417;
UPDATE `creature_template` SET `DamageModifier`='2' WHERE  `entry`=2520;
-- also update archaedas speed
UPDATE `creature_template` SET `DamageModifier`='2.7', `BaseAttackTime`='2600' WHERE  `entry`=2748;
-- also update anathemus speed(verified on classic)
UPDATE `creature_template` SET `DamageModifier`='3.75', `BaseAttackTime`='3000' WHERE  `entry`=2754;
-- earthen stonebreaker : 2.5 from 2.7
UPDATE `creature_template` SET `BaseAttackTime`='2500' WHERE  `entry`=7396;
UPDATE `creature_template` SET `DamageModifier`='1.4' WHERE  `entry`=2749;
UPDATE `creature_template` SET `DamageModifier`='2.3' WHERE  `entry`=2937;
UPDATE `creature_template` SET `DamageModifier`='2.25' WHERE  `entry`=3586;
UPDATE `creature_template` SET `DamageModifier`='1.7' WHERE  `entry`=3642;
UPDATE `creature_template` SET `DamageModifier`='2.4' WHERE  `entry`=3654;
UPDATE `creature_template` SET `DamageModifier`='2.3' WHERE  `entry`=3669;
UPDATE `creature_template` SET `DamageModifier`='2.7' WHERE  `entry`=3670;
UPDATE `creature_template` SET `DamageModifier`='2.7' WHERE  `entry`=3673;
UPDATE `creature_template` SET `DamageModifier`='2' WHERE  `entry`=3674;
UPDATE `creature_template` SET `BaseAttackTime`='1500' WHERE  `entry`=3860;
UPDATE `creature_template` SET `DamageModifier`='1.7' WHERE  `entry`=3865;
UPDATE `creature_template` SET `DamageModifier`='1.7' WHERE  `entry`=3876;
UPDATE `creature_template` SET `DamageModifier`='1.7' WHERE  `entry`=3869;
UPDATE `creature_template` SET `DamageModifier`='1.7' WHERE  `entry`=3870;
UPDATE `creature_template` SET `DamageModifier`='2.5' WHERE  `entry`=3886;
UPDATE `creature_template` SET `DamageModifier`='3.3' WHERE  `entry`=3927;
UPDATE `creature_template` SET `DamageModifier`='2.6' WHERE  `entry`=3976;
UPDATE `creature_template` SET `DamageModifier`='2.2' WHERE  `entry`=3977;
UPDATE `creature_template` SET `DamageModifier`='3.8' WHERE  `entry`=3975;
UPDATE `creature_template` SET `DamageModifier`='2' WHERE  `entry`=3983;
UPDATE `creature_template` SET `DamageModifier`='3.3' WHERE  `entry`=4274;
-- archmage arugal
UPDATE `creature_template` SET `DamageModifier`='5.3' WHERE  `entry`=4275;
UPDATE `creature_template` SET `DamageModifier`='2.3' WHERE  `entry`=4278;
UPDATE `creature_template` SET `DamageModifier`='1' WHERE  `entry`=4283;
UPDATE `creature_template` SET `DamageModifier`='1.7' WHERE  `entry`=4286;
UPDATE `creature_template` SET `DamageModifier`='1.7' WHERE  `entry`=4287;
UPDATE `creature_template` SET `DamageModifier`='1.7' WHERE  `entry`=4288;
UPDATE `creature_template` SET `DamageModifier`='1' WHERE  `entry`=4289;
UPDATE `creature_template` SET `DamageModifier`='1' WHERE  `entry`=4291;
UPDATE `creature_template` SET `DamageModifier`='1.6' WHERE  `entry`=4292;
UPDATE `creature_template` SET `DamageModifier`='1' WHERE  `entry`=4293;
UPDATE `creature_template` SET `DamageModifier`='1' WHERE  `entry`=4294;
UPDATE `creature_template` SET `DamageModifier`='2' WHERE  `entry`=4295;
UPDATE `creature_template` SET `DamageModifier`='1' WHERE  `entry`=4296;
UPDATE `creature_template` SET `DamageModifier`='1' WHERE  `entry`=4297;
UPDATE `creature_template` SET `DamageModifier`='1.7' WHERE  `entry`=4298;
UPDATE `creature_template` SET `DamageModifier`='1.6' WHERE  `entry`=4299;
UPDATE `creature_template` SET `DamageModifier`='1.6' WHERE  `entry`=4300;
UPDATE `creature_template` SET `DamageModifier`='2.7' WHERE  `entry`=4301;
UPDATE `creature_template` SET `DamageModifier`='1.9' WHERE  `entry`=4302;
UPDATE `creature_template` SET `DamageModifier`='1.9' WHERE  `entry`=4303;
UPDATE `creature_template` SET `DamageModifier`='2' WHERE  `entry`=4306;
UPDATE `creature_template` SET `DamageModifier`='2.5' WHERE  `entry`=4339;
UPDATE `creature_template` SET `DamageModifier`='4' WHERE  `entry`=4364;
UPDATE `creature_template` SET `DamageModifier`='4.2' WHERE  `entry`=4366;
UPDATE `creature_template` SET `DamageModifier`='3.9' WHERE  `entry`=4370;
UPDATE `creature_template` SET `DamageModifier`='4.2' WHERE  `entry`=4368;
UPDATE `creature_template` SET `DamageModifier`='3.9' WHERE  `entry`=4371;
UPDATE `creature_template` SET `DamageModifier`='4' WHERE  `entry`=4374;
UPDATE `creature_template` SET `DamageModifier`='1' WHERE  `entry`=4416;
UPDATE `creature_template` SET `DamageModifier`='1.2' WHERE  `entry`=4516;
UPDATE `creature_template` SET `DamageModifier`='1.5' WHERE  `entry`=4515;
UPDATE `creature_template` SET `DamageModifier`='1.6' WHERE  `entry`=4517;
UPDATE `creature_template` SET `DamageModifier`='1.6' WHERE  `entry`=4518;
UPDATE `creature_template` SET `DamageModifier`='1.6' WHERE  `entry`=4519;
UPDATE `creature_template` SET `DamageModifier`='1.6' WHERE  `entry`=4520;
UPDATE `creature_template` SET `DamageModifier`='1.6' WHERE  `entry`=4522;
UPDATE `creature_template` SET `DamageModifier`='1.6' WHERE  `entry`=4525;
UPDATE `creature_template` SET `DamageModifier`='2.7' WHERE  `entry`=4542;
UPDATE `creature_template` SET `DamageModifier`='1.6' WHERE  `entry`=4543;
UPDATE `creature_template` SET `DamageModifier`='1' WHERE  `entry`=4625;
-- to continue

```

**Comment by Zoidwaffle** [comment]
@T1ti : if you are interested in some sort of comparison for creatures for DamageModifier with TC/vmangos, maybe I can help out.

**Comment by pklloveyou** [comment]
I think we should merge all the (BaseAttackTime RangeAttackTime DamageModifier creature_classlevelstats) of TC and then make custom changes

**Comment by Hacki95** [comment]
> I think we should merge all the (BaseAttackTime RangeAttackTime DamageModifier creature_classlevelstats) of TC and then make custom changes
> Because the current PR is from TC

There are other PRs already for the RangeAttackTime and BaseAttacktime.

Classlevelstats are already changed and are correct now, no sense in changing them.

The only thing left to do is fixing the DamageModifiers and as you see T1ti is already doing that.

But I don't see a way how we can test every single mob with the new system, there will surely be new bugs but at least they will be very easy to fix with the new system.

**Comment by FrancescoBorzi** [comment]
cc @Knindzagxg

**Comment by Zoidwaffle** [comment]
@Hacki95 : testing everything is a daunting task... So might I suggest we split it up a bit?

We make a PR for creatures 1-20, 21-30 and then either make a giant 31-80 or continue with 10-level segments.

This is made to match the Chromiecraft releases... No matter what, I'm certain some tweaks will be needed later.

I made a script that can do this stuff... Output example:

```
UPDATE `creature_template` SET `DamageModifier`=1.7 WHERE `entry`=598; -- 'Defias Miner', level 18, DamageModifier was 1.03
```

So it's trivial to create some long boring lists with info like that.

**Comment by pklloveyou** [comment]
I also think we should merge it first

**Comment by Zoidwaffle** [comment]
Yep, I agree. It's fine to make a rubber-stamp commit to hopefully sort out the worst crap... And then manually fixing/verifying the main creatures of interest (like bosses) and hope for some bug reports to fix other obvious things that are wrong.

TL;DR: Yes.

**Comment by pklloveyou** [comment]
After the merger, we can get more people's feedback

**Comment by Hacki95** [comment]
I just want to emphasize again: It can't possibly be worse than before even without testing every mob! 

So many PRs have been done that tried to fix the faulty values before but they were all closed because it simply wasn't possible with the old system. #2742 #2773 #2766

This paves the way for other people who are more knowledgable than me in those areas to finally fix that stuff up and get a huge step towards being more accurate and blizzlike :)

**Comment by FrancescoBorzi** [comment]
@Hacki95 thanks for this big work. I see a lot of positive comments here and we definitely want to merge this. I just need more test feedback as this quite a big change and we should not merge it too quick.

@azerothcore/testers @mpfans can you please test this PR?

I know that we can't really test everything, and it's ok to fix any bug that will pop up later. Still, I'd like to have more people test this before merging.

Meanwhile.............
As this PR also will require a change in Keira3, our main DB editor, can @Hacki95 or any other volunteer to do this part of the job? I'm available to give guidance about it. [This](https://www.azerothcore.org/wiki/keira3-internals) is a good starting point. 
Otherwise, I will have to do it, but my schedule is quite full so the Keira3 part of this PR would have to wait.

**Comment by pklloveyou** [comment]
```sql
SELECT entry,DamageModifier,name,(SELECT DamageModifier FROM creature_template_tc WHERE entry = creature_template.entry)
FROM creature_template WHERE entry IN(SELECT entry FROM creature_template_tc WHERE DamageModifier <> creature_template.DamageModifier);
+-------+----------------+------------------+---------------------------------------------------------------------------------------+
| entry | DamageModifier | name             | (SELECT DamageModifier FROM creature_template_ WHERE entry = creature_template.entry) |
+-------+----------------+------------------+---------------------------------------------------------------------------------------+
| 15712 |            7.5 | 甲虫             | 1 |
| 15929 |           1.01 | 斯塔拉格         | 35 |
| 15930 |           1.01 | 费尔根           | 35 |
| 15931 |           1.01 | 格罗布鲁斯       | 35 |
| 15932 |           1.01 | 格拉斯           | 35 |
| 15936 |           1.01 | 肮脏的希尔盖     | 35 |
| 15952 |           1.01 | 迈克斯纳         | 35 |
| 15953 |           1.01 | 黑女巫法琳娜     | 35 |
| 15954 |           1.01 | 药剂师诺斯       | 35 |
| 15956 |           1.01 | 阿努布雷坎       | 35 |
| 15989 |           1.01 | 萨菲隆           | 35 |
| 15990 |           1.01 | 克尔苏加德       | 35 |
| 16011 |           1.01 | 洛欧塞布         | 35 |
| 16028 |           1.01 | 帕奇维克         | 35 |
| 16060 |           1.01 | 收割者戈提克     | 35 |
| 16061 |           1.01 | 教官拉苏维奥斯   | 35 |
| 16063 |           1.01 | 瑟里耶克爵士     | 35 |
| 16064 |           1.01 | 库尔塔兹领主     | 35 |
| 16065 |           1.01 | 女公爵布劳缪克丝 | 35 |
| 16127 |           1.03 | 鬼灵学徒         | 7.5 |
| 16149 |           1.03 | 鬼灵战马         | 7.5 |
| 16290 |           1.03 | 辐射软泥怪       | 7.5 |
| 16441 |           1.03 | 寒冰皇冠卫士     | 7.5 |
| 16505 |           1.03 | 纳克萨玛斯追随者 | 7.5 |
| 16506 |           1.03 | 纳克萨玛斯膜拜者 | 7.5 |
| 16698 |           1.03 | 死尸甲虫         |  1 |
| 16573 |           1.03 | 地穴卫士         | 7.5 |
| 16803 |           1.03 | 死亡骑士学员     | 7.5 |
| 17711 |           32.8 | 末日行者         | 35 |
| 16124 |           1.03 | 冷酷的学徒       |  1 |
| 16125 |           1.03 | 冷酷的死亡骑士   | 7.5 |
| 16126 |           1.03 | 冷酷的骑兵       | 7.5 |
| 16148 |           1.03 | 鬼灵死亡骑士     | 7.5 |
| 16150 |           1.03 | 鬼灵骑兵         | 7.5 |
| 16360 |           1.03 | 肉用僵尸         | 7.5 |
| 16427 |           1.03 | 冰冻废土的士兵   | 7.5 |
| 16428 |           1.03 | 势不可挡的憎恶   | 7.5 |
| 16429 |           1.03 | 织魂者           | 7.5 |
| 16981 |           1.03 | 天灾卫士         | 7.5 |
| 16982 |           1.03 | 天灾构造体       | 7.5 |
| 16983 |           1.03 | 天灾勇士         | 7.5 |
| 16984 |           1.03 | 天灾战士         | 7.5 |
| 17055 |           1.03 | 迈克斯纳的小蜘蛛 |  1 |
| 29249 |           1.01 | 阿努布雷坎       | 70 |
| 29256 |           1.03 | 地穴卫士         | 13 |
| 29267 |           1.03 | 死尸甲虫         |  1 |
| 29268 |           1.01 | 黑女巫法琳娜     | 70 |
| 29273 |           1.03 | 纳克萨玛斯追随者 | 13 |
| 29274 |           1.03 | 纳克萨玛斯膜拜者 | 13 |
| 29278 |           1.01 | 迈克斯纳         | 70 |
| 29279 |           1.03 | 迈克斯纳的小蜘蛛 |  1 |
| 29324 |           1.01 | 帕奇维克         | 70 |
| 29338 |           1.03 | 先锋军黑鸦主教   |  1 |
| 29373 |           1.01 | 格罗布鲁斯       | 70 |
| 29417 |           1.01 | 格拉斯           | 70 |
| 29446 |           1.01 | 斯塔拉格         | 70 |
| 29447 |           1.01 | 费尔根           | 70 |
| 29615 |           1.01 | 瘟疫使者诺斯     | 70 |
| 29632 |           1.03 | 天灾战士         | 13 |
| 29633 |           1.03 | 天灾勇士         | 13 |
| 29634 |           1.03 | 天灾卫士         | 13 |
| 29635 |           1.03 | 瘟疫构造体       | 13 |
| 29701 |           1.01 | 肮脏的希尔盖     | 70 |
| 29718 |           1.01 | 洛欧塞布         | 70 |
| 29940 |           1.01 | 教官拉苏维奥斯   | 70 |
| 29941 |           1.03 | 死亡骑士学员     | 13 |
| 29955 |           1.01 | 收割者戈提克     | 70 |
| 29985 |           1.03 | 冷酷的死亡骑士   | 13 |
| 29986 |           1.03 | 冷酷的骑兵       | 13 |
| 29987 |           1.03 | 冷酷的学徒       |  1 |
| 29988 |           1.03 | 鬼灵骑兵         | 13 |
| 29989 |           1.03 | 鬼灵战马         | 13 |
| 29990 |           1.03 | 鬼灵死亡骑士     | 13 |
| 29991 |           1.01 | 萨菲隆           | 70 |
| 30015 |           1.03 | 冰冻废土的士兵   | 13 |
| 30018 |           1.03 | 织魂者           | 13 |
| 30048 |           1.03 | 势不可挡的憎恶   | 13 |
| 30057 |           1.03 | 寒冰皇冠卫士     | 13 |
| 30061 |           1.01 | 克尔苏加德       | 70 |
| 30264 |           1.03 | 鬼灵学徒         | 13 |
| 30303 |           1.03 | 肉用僵尸         | 13 |
| 30549 |           1.01 | 瑞文戴尔男爵     | 35 |
| 30600 |           1.01 | 瑞文戴尔男爵     | 70 |
| 30601 |           1.01 | 女公爵布劳缪克丝 | 70 |
| 30602 |           1.01 | 瑟里耶克爵士     | 70 |
| 30603 |           1.01 | 库尔塔兹领主     | 70 |
+-------+----------------+------------------+---+
86 rows in set
```

**Comment by pklloveyou** [comment]
```sql
SELECT entry,DamageModifier,name,(SELECT DamageModifier FROM creature_template_tc WHERE entry = creature_template.entry)
FROM creature_template WHERE entry IN(SELECT entry FROM creature_template_tc WHERE DamageModifier <> creature_template.DamageModifier);
+-------+----------------+------------------+---------------------------------------------------------------------------------------+
| entry | DamageModifier | name             | (SELECT DamageModifier FROM creature_template_tc WHERE entry = creature_template.entry) |
+-------+----------------+------------------+---------------------------------------------------------------------------------------+
| 15712 |            7.5 | 甲虫             | 1 |
| 15929 |           1.01 | 斯塔拉格         | 35 |
| 15930 |           1.01 | 费尔根           | 35 |
| 15931 |           1.01 | 格罗布鲁斯       | 35 |
| 15932 |           1.01 | 格拉斯           | 35 |
| 15936 |           1.01 | 肮脏的希尔盖     | 35 |
| 15952 |           1.01 | 迈克斯纳         | 35 |
| 15953 |           1.01 | 黑女巫法琳娜     | 35 |
| 15954 |           1.01 | 药剂师诺斯       | 35 |
| 15956 |           1.01 | 阿努布雷坎       | 35 |
| 15989 |           1.01 | 萨菲隆           | 35 |
| 15990 |           1.01 | 克尔苏加德       | 35 |
| 16011 |           1.01 | 洛欧塞布         | 35 |
| 16028 |           1.01 | 帕奇维克         | 35 |
| 16060 |           1.01 | 收割者戈提克     | 35 |
| 16061 |           1.01 | 教官拉苏维奥斯   | 35 |
| 16063 |           1.01 | 瑟里耶克爵士     | 35 |
| 16064 |           1.01 | 库尔塔兹领主     | 35 |
| 16065 |           1.01 | 女公爵布劳缪克丝 | 35 |
| 16127 |           1.03 | 鬼灵学徒         | 7.5 |
| 16149 |           1.03 | 鬼灵战马         | 7.5 |
| 16290 |           1.03 | 辐射软泥怪       | 7.5 |
| 16441 |           1.03 | 寒冰皇冠卫士     | 7.5 |
| 16505 |           1.03 | 纳克萨玛斯追随者 | 7.5 |
| 16506 |           1.03 | 纳克萨玛斯膜拜者 | 7.5 |
| 16698 |           1.03 | 死尸甲虫         |  1 |
| 16573 |           1.03 | 地穴卫士         | 7.5 |
| 16803 |           1.03 | 死亡骑士学员     | 7.5 |
| 17711 |           32.8 | 末日行者         | 35 |
| 16124 |           1.03 | 冷酷的学徒       |  1 |
| 16125 |           1.03 | 冷酷的死亡骑士   | 7.5 |
| 16126 |           1.03 | 冷酷的骑兵       | 7.5 |
| 16148 |           1.03 | 鬼灵死亡骑士     | 7.5 |
| 16150 |           1.03 | 鬼灵骑兵         | 7.5 |
| 16360 |           1.03 | 肉用僵尸         | 7.5 |
| 16427 |           1.03 | 冰冻废土的士兵   | 7.5 |
| 16428 |           1.03 | 势不可挡的憎恶   | 7.5 |
| 16429 |           1.03 | 织魂者           | 7.5 |
| 16981 |           1.03 | 天灾卫士         | 7.5 |
| 16982 |           1.03 | 天灾构造体       | 7.5 |
| 16983 |           1.03 | 天灾勇士         | 7.5 |
| 16984 |           1.03 | 天灾战士         | 7.5 |
| 17055 |           1.03 | 迈克斯纳的小蜘蛛 |  1 |
| 29249 |           1.01 | 阿努布雷坎       | 70 |
| 29256 |           1.03 | 地穴卫士         | 13 |
| 29267 |           1.03 | 死尸甲虫         |  1 |
| 29268 |           1.01 | 黑女巫法琳娜     | 70 |
| 29273 |           1.03 | 纳克萨玛斯追随者 | 13 |
| 29274 |           1.03 | 纳克萨玛斯膜拜者 | 13 |
| 29278 |           1.01 | 迈克斯纳         | 70 |
| 29279 |           1.03 | 迈克斯纳的小蜘蛛 |  1 |
| 29324 |           1.01 | 帕奇维克         | 70 |
| 29338 |           1.03 | 先锋军黑鸦主教   |  1 |
| 29373 |           1.01 | 格罗布鲁斯       | 70 |
| 29417 |           1.01 | 格拉斯           | 70 |
| 29446 |           1.01 | 斯塔拉格         | 70 |
| 29447 |           1.01 | 费尔根           | 70 |
| 29615 |           1.01 | 瘟疫使者诺斯     | 70 |
| 29632 |           1.03 | 天灾战士         | 13 |
| 29633 |           1.03 | 天灾勇士         | 13 |
| 29634 |           1.03 | 天灾卫士         | 13 |
| 29635 |           1.03 | 瘟疫构造体       | 13 |
| 29701 |           1.01 | 肮脏的希尔盖     | 70 |
| 29718 |           1.01 | 洛欧塞布         | 70 |
| 29940 |           1.01 | 教官拉苏维奥斯   | 70 |
| 29941 |           1.03 | 死亡骑士学员     | 13 |
| 29955 |           1.01 | 收割者戈提克     | 70 |
| 29985 |           1.03 | 冷酷的死亡骑士   | 13 |
| 29986 |           1.03 | 冷酷的骑兵       | 13 |
| 29987 |           1.03 | 冷酷的学徒       |  1 |
| 29988 |           1.03 | 鬼灵骑兵         | 13 |
| 29989 |           1.03 | 鬼灵战马         | 13 |
| 29990 |           1.03 | 鬼灵死亡骑士     | 13 |
| 29991 |           1.01 | 萨菲隆           | 70 |
| 30015 |           1.03 | 冰冻废土的士兵   | 13 |
| 30018 |           1.03 | 织魂者           | 13 |
| 30048 |           1.03 | 势不可挡的憎恶   | 13 |
| 30057 |           1.03 | 寒冰皇冠卫士     | 13 |
| 30061 |           1.01 | 克尔苏加德       | 70 |
| 30264 |           1.03 | 鬼灵学徒         | 13 |
| 30303 |           1.03 | 肉用僵尸         | 13 |
| 30549 |           1.01 | 瑞文戴尔男爵     | 35 |
| 30600 |           1.01 | 瑞文戴尔男爵     | 70 |
| 30601 |           1.01 | 女公爵布劳缪克丝 | 70 |
| 30602 |           1.01 | 瑟里耶克爵士     | 70 |
| 30603 |           1.01 | 库尔塔兹领主     | 70 |
+-------+----------------+------------------+---+
86 rows in set
```

**Comment by T1ti** [comment]
what is this supposed to be ?

**Comment by Hacki95** [comment]
> 
> 
> what is this supposed to be ?

I think those are some of our modified damage values. I think on the left are the old ones and on the right the new.

For example 15929 is Stallag. His damagemodifier before was nonsense. 35 seems legit.

**Comment by T1ti** [comment]
35 is a placeholder used for all raid bosses btw, it's not legit

7.5 and 4.6 are also palceholder that are all over the place

**Comment by pklloveyou** [comment]
image
Yes, the damage is too low

**Comment by T1ti** [comment]
I absolutely don't understand what those values are, Grobbulus had modifier 35(not 1.01), and isn't modified by the PR ?

**Comment by Si1ker** [comment]
> I absolutely don't understand what those values are, Grobbulus had modifier 35(not 1.01), and his modifier isn't changed by the PR ?

The 1.xx DamageModifier is not still in the core, is a pending PR, I think @pklloveyou tested that PR and still have that modifier

The PR: https://github.com/azerothcore/azerothcore-wotlk/pull/4195

**Comment by pklloveyou** [comment]
I changed it in another PR, and it's strange that I can't search it

**Comment by Si1ker** [comment]
> I changed it in another PR, and it's strange that I can't search it

Just linked it above ! 🐱

**Comment by pklloveyou** [comment]
> > I absolutely don't understand what those values are, Grobbulus had modifier 35(not 1.01), and his modifier isn't changed by the PR ?
> 
> The 1.xx DamageModifier is not still in the core, is a pending PR, I think @pklloveyou tested that PR and still have that modifier
> 
> The PR: #4195

yes...............

**Comment by T1ti** [comment]
But that PR is useful ! 
It's just that those values will have to converted to a multiplier for the new system  :)

**Comment by Si1ker** [comment]
> But that PR is useful !
> It's just that those values will have to converted to a multiplier for the new system :)

Probably @Knindzagxg will have to.

**Comment by pklloveyou** [comment]
I've tested too much PR, and I'm sorry

**Comment by pklloveyou** [comment]
I'll update the code again

**Comment by Si1ker** [comment]
> I've tested too much PR, and I'm sorry

No problem with it, that's actually awesome, just restore DB after each PR or back up what you are going to test - this for future PRs & tests ! 🐱

**Comment by Hacki95** [comment]
Yup those PRs that changed min, maxdmg and the modifiers need to be redone now sadly 😄

**Comment by Knindzagxg** [comment]
Will check once i'm back from work today.

This looks really good, and we can finally get really awesome system.
Most of PR's we did for Dungeons use very low damage multiplier and testing it in there will give us a lot info.

**Comment by pklloveyou** [comment]
I put it on my server

**Comment by pklloveyou** [comment]
```sql

UPDATE creature_template SET RangeAttackTime = 2000, BaseAttackTime = 2000 WHERE entry = 15550;
UPDATE creature_template SET RangeAttackTime = 2000, BaseAttackTime = 2000 WHERE entry = 16152;

```
The overall damage value is a little low

**Comment by pklloveyou** [comment]
I'm trying again

**Comment by Knindzagxg** [comment]
Recompiled and gonna do tests during next few days to get best possible results.

**Comment by Hacki95** [comment]
> 
> 
> I'm trying again

If

> 
> 
> Its damage value is too high
> 
> ```sql
> UPDATE creature_template SET RangeAttackTime = 2000, BaseAttackTime = 2000 WHERE entry = 15550;
> UPDATE creature_template SET RangeAttackTime = 2000, BaseAttackTime = 2000 WHERE entry = 16152;
> ```
> 
> The overall damage value is a little low

If its the fault of some AttackTime values then I won't update them here in the PR. There are different PRs working on that.

**Comment by Hacki95** [comment]
I double checked, I may have a mistake on when the game uses exp0 and exp1. Could someone check if for example bosses from vanilla/tbc all have semingly high values? It might be that it doesnt doesnt see the difference between a 63 vanilla mob and a 63 tbc one. I don't have time the next few days but if someone could test it out it would be great.

**Comment by pklloveyou** [comment]
This PR function is very good, he is Blizzard, no matter merge it or not, I am using it.

**Comment by Footman** [comment]
I tested this pull Request on Live server with real player. Seem it breaks some bosses.
Mostly noticeable in heroic 25 mode in ICC. Really good equiped Tanks get oneshoted by sindragosa and lich king. Some other adds produce too large amount of damage.

I did not find out if creature damage is too high or player class system is broken here.

**Comment by FrancescoBorzi** [comment]
thanks for your feedback @Footman 

please @Hacki95 have a look at these issues

**Comment by Hacki95** [comment]
Thank you @Footman 

@FrancescoBorzi I will take a look later today!

**Comment by Hacki95** [comment]
grafik
So those are the old damage values, as we can see the damage for 10hc, 25 and 25hc are actually all the same. Same with a bunch of other bosses.

I can't say if the new values are wrong, but I can definitely say the old ones are.

If somebody could point me to any direction where I could find out which values would be more blizzlike please do. We now have exactly the same damage values as TC has. 

Was the group who got one shotted sufficiently equiped? My thinking is that before this PR a group which was way undergeared could probably kill them but now you need the proper gear to survive their strikes.

**Comment by Footman** [comment]
image
image
I compared damage to values from trinitycore.  Top Screenshot is trinitycore, bottom is ac with this pullrequest. its nearly 3-4 times as much damage

**Comment by Hacki95** [comment]
Thank you I will take a look!

**Comment by Footman** [comment]
ah sorry i tested on tc in non 25h mode. damage values are same. so seems its about characters

**Comment by mpfans** [comment]
tested,I think it can be merged. this PR is more accurate, and it can correctly reduce the damage according to the physical armor

**Comment by Hacki95** [comment]
> 
> 
> tested,I think it can be merged. this PR is more accurate, and it can correctly reduce the damage according to the physical armor

Thanks for the report.

I will have to take a closer look at the issue @Footman posted but it'll take a while. Windows update killed all my virtualboxes for development yesterday so I have to reinstall everything first :) Have to compare if bosses really make different damage on fully equipped characters between tc and az.

**Comment by Footman** [comment]
> > tested,I think it can be merged. this PR is more accurate, and it can correctly reduce the damage according to the physical armor
> 
> Thanks for the report.
> 
> I will have to take a closer look at the issue @Footman posted but it'll take a while. Windows update killed all my virtualboxes for development yesterday so I have to reinstall everything first :) Have to compare if bosses really make different damage on fully equipped characters between tc and az.

Problem may be not with Equip but with auras / talents. I will make tests as well.

**Comment by T1ti** [comment]
anyways what we are testing is the global implementation, not some specific mob damages or if you are waiting for 20.000 mobs to be perfect this PR will never releas
, that would need to be fixed in a different issue

**Comment by Hacki95** [comment]
So I tried some stuff:
--------------------------------------
Old System - Naked vs 5 Piece Armor:
grafik
grafik
--------------------------------------
New System - Naked vs 5 Piece Armor:
grafik
grafik
---------------------------------------
Calculated values for the new system the upper numbers are min damage and max damage
grafik

While the damage looks a little bit higher I can't see how this difference would oneshot your tank while the older values didn't. I also can't see any problems with the armor system or any other factor that calculates the damage.

The new numbers might need some tuning, but I don't see how this breaks those bosses.

Can't confirm any problem with my PR.

**Comment by T1ti** [comment]
The new numbers look more accurate, for some reason Sindragosa had really low HP in AC, about the same as onyxia.
LK is pretty close in both AC and TC tho

**Comment by Footman** [comment]
Like I said I got feedback from top Raid groups in 25 heroic mode. They were very angry. A lot of creatures do too much damage that tanks with top Gear can't keep up anymore. I don't know what is causing this. Just telling facts.

**Comment by Hacki95** [comment]
I'm not saying that what you reported is wrong, after all the damage IS higher than before! I am just trying to say that the new values are the actual values how they should be and the values before were very undertuned, making HC too easy.

https://wowwiki-archive.fandom.com/wiki/Lich_King_(Icecrown_Citadel_tactics) (Lich King in 25Normal hits for around 40k)

With the CLS system: 
grafik

As you can see for 25normal he now does the expected damage. I sadly can't find a single source which states for how much meele damage the Lich King hits for in 25HC, but all other values seem to be correct (10, 10hc, 25). 

It could be that the modificator for 25hc is simply wrong and needs some tuning, but so far I haven't found any information that points to this being the case.

If your players say they never saw such damage before then in my mind, they either only played on other AzerothCore based servers which ofcourse were all undertuned aswell before this PR. 

Or if they were on TC based servers, then they must have manually nerfed bosses in HC. 

Because with this in place we do exactly the same damage as TC. Which makes me think if the damage would have been wrong in TC for years surely there would be a bug report somewhere but there isn't. 

I will try to get into contact with someone who might be able to confirm/deny if the Lich King really does so much damage in HC25.

Until then, this is an issue regarding the the damage_modifier, not the system itself. After this PR gets merged there will probably be quite a handful of mobs which need some sort of tuning.

@Knindzagxg were you able to do some tests yet? No more errors have been found so far.

**Comment by Knindzagxg** [comment]
For now it looks good.

What is really great about whole PR, that we can just change / modify damagemodifier if we need to fix some boss.
When it comes to dungeons that i tested, there is no to much changes and i actually like it - Kinda makes it a little harder due class changes.

What i wasn't able to test due my time are Demo Shouts.

Can someone test what happens with any boss damage when you use Bear or Warrior Demoralizing shout.
We had big issue with that as well, and i wonder will this PR make it work as it should.

**Comment by Hacki95** [comment]
> 
> 
> For now it looks good.
> 
> What is really great about whole PR, that we can just change / modify damagemodifier if we need to fix some boss.
> When it comes to dungeons that i tested, there is no to much changes and i actually like it - Kinda makes it a little harder due class changes.
> 
> What i wasn't able to test due my time are Demo Shouts.
> 
> Can someone test what happens with any boss damage when you use Bear or Warrior Demoralizing shout.
> We had big issue with that as well, and i wonder will this PR make it work as it should.


Expected damage without Demoralizing Shout: 
grafik
Damage done:
grafik

Expected damage with Demoralizing Shout:
grafik
Damage done:
grafik

Looks like its working great!

**Comment by pklloveyou** [comment]
image
Alone, my graduate defense Paladin

**Comment by mpfans** [comment]
> image
> Alone, my graduate defense Paladin 25H ICC
> I don't know if the damage is high or low

ICC老1需要分担伤害.所以这个测试我感觉没实际意义

**Comment by Knindzagxg** [comment]
Awesome, finally Shout working.

@pk will check ICC later tonight or tomorrow.

**Comment by Hacki95** [comment]
> 
> 
> image
> Alone, my graduate defense Paladin 25H ICC
> I don't know if the damage is high or low

It looks about right for HC

**Comment by Knindzagxg** [comment]
Damage looks fine pk.

Also, if possible when checking those, can u add small ss of your tanking stats, so we can see how it would work on lower geared / not defense capped and things like.

**Comment by Hacki95** [comment]
@Knindzagxg Can this be marked as "to be merged" now? Things like wrong damage_modifiers will be much easier to correct when the general public can get their hands on it and report if something is wrong. The system works great.

**Comment by Knindzagxg** [comment]
Give it few more days, if not problem.

I wanna do few cross checking and to make few files about damage in raids mostly.
In case we gonna need to change some values i will have it ready.

**Review by Knindzagxg — APPROVED** [review]

**Comment by Knindzagxg** [comment]
Had some extra time today so files are ready in case we gonna need them.

This should improve overall damage -> Not much, but looks much better.

PS: In case there is an issue with some Boss, pretty please provide a bit more extra information (SS of your gear, defense, recount or etc - Will help a lot.)

**Comment by mpfans** [comment]
My server has 1500 + online players and has been tested for about 2 weeks. I think this PR can be merged. If you encounter incorrect damage, you can repair it separately

**Comment by Footman** [comment]
> My server has 1500 + online players and has been tested for about 2 weeks. I think this PR can be merged. If you encounter incorrect damage, can fix it separately

but you dont have them playing wotlk with ICC

**Comment by Hacki95** [comment]
> > My server has 1500 + online players and has been tested for about 2 weeks. I think this PR can be merged. If you encounter incorrect damage, can fix it separately
> 
> but you dont have them playing wotlk with ICC

There is nothing pointing to ICC HC being broken, yes it was easier before but it also wasn't right.

If you want to make 25HC easier for your players simply tune down the damage_modifier of the offending bosses, but it also won't be blizzlike that way.
