### PR TITLE
fix(DB/creature_loot_template,conditions): Cracked Silithid Carapace (5877)

### LINKED ISSUE #6280: Cracked Silithid Carapace (5877) should drop at 100% only while on The Swarm Grows (1147)
Original report https://github.com/chromiecraft/chromiecraft/issues/815 by @formiclol

Additional info by @necropola:
I did some further research and it looks like the item should indeed drop at 100% from the first Silithid you kill while on the quest **The Swarm Grows (1147)**:

https://wowpedia.fandom.com/wiki/Cracked_Silithid_Carapace?oldid=2026412
> This item drops from Silithid Searchers, Silithid Hive Drones, and Silithid Invaders at the Rustmaul Digsite in the Shimmering Flats, Thousand Needles. If you are eligible for the drop, it will drop from the first Silithid you kill here.

https://www.wowhead.com/item=5877/cracked-silithid-carapace#comments:id=243225
> Actually, I think you need to have the "The Swarm Grows" quest to find this drop. I killed 100+ of them and didn't find any but as soon as I got the quest I found the drop. On the first kill.

#### WHAT CLIENT DO YOU PLAY ON?
- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION
- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:
- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:
A quest start item [Cracked Silithid Carapace](https://wotlkdb.com/?item=5877) is supposed to drop from the Silithid mobs in southwest Shimmering Flats ([1](https://wotlkdb.com/?npc=4133), [2](https://wotlkdb.com/?npc=4131), [3](https://wotlkdb.com/?npc=4130), [4, rare](https://wotlkdb.com/?npc=4132)).  It is supposed to be a guaranteed drop for Horde players only.  I have done the quest [The Swarm Grows](https://wotlkdb.com/?quest=1147) on two characters and have not received the drop.  [Wowhead comments](https://classic.wowhead.com/item=5877/cracked-silithid-carapace#comments) suggests that players need to be on The Swarm Grows for the item to drop.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The item in question drops when players are on The Swarm Grows (3rd quest in chain).

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be horde
2. Be on quest [The Swarm Grows](https://wotlkdb.com/?quest=1147)
3. Kill any of the required quest mobs (linked above)
4. [Cracked Silithid Carapace](https://wotlkdb.com/?item=5877) should drop on first kill, but doesn't

##### EXTRA NOTES:

Should be a 100% drop rate on first kill.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99055304-cracked-silithid-carapace-5877-should-drop-at-100-while-on-the-swarm-grows-1147?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by necropola**
## Changes Proposed:
Drop item **Cracked Silithid Carapace (5877)** at 100% only while on the quest **The Swarm Grows (1147)**

## Issues Addressed:
- Closes #6280
- Closes https://github.com/chromiecraft/chromiecraft/issues/815

## SOURCE:
https://wowpedia.fandom.com/wiki/Cracked_Silithid_Carapace?oldid=2026412
> This item drops from Silithid Searchers, Silithid Hive Drones, and Silithid Invaders at the Rustmaul Digsite in the Shimmering Flats, Thousand Needles. If you are eligible for the drop, it will drop from the first Silithid you kill here.

https://www.wowhead.com/item=5877/cracked-silithid-carapace#comments:id=243225
> Actually, I think you need to have the "The Swarm Grows" quest to find this drop. I killed 100+ of them and didn't find any but as soon as I got the quest I found the drop. On the first kill.

## Tests Performed:
- SQL statements successfully executed
- Tested in game

## How to Test the Changes:
- Kill and loot **Silithid Searcher, Ravager, Invader, Hive Drone**  at the **Rustmaul Digsite** in the **Shimmering Flats / Thousand Needles** while **not** on the quest **The Swarm Grows (1147)** and observe that the quest item does not drop
- `.add quest 1147`
- Kill some more and observe that the quest item is dropped on first kill but no longer after accepting the quest **Parts of the Swarm (1148)** from it.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1623236925695171584.sql [hunk 1]
```diff
@@ -0,0 +1,9 @@
...
+INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2` , `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES (1, 4132, 5877, 0, 0, 9, 0, 1147, 0, 0, 0, 0, 0, '', 'Cracked Silithid Carapace (5877) only drops from Silithid Ravager (4132) while on The Swarm Grows (1147) ');
+INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2` , `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES (1, 4133, 5877, 0, 0, 9, 0, 1147, 0, 0, 0, 0, 0, '', 'Cracked Silithid Carapace (5877) only drops from Silithid Hive Drone (4133) while on The Swarm Grows (1147) ');
```
Comment (Helias) [inline data/sql/updates/pending_db_world/rev_1623236925695171584.sql:8]:
```suggestion
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2` , `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(1, 4130, 5877, 0, 0, 9, 0, 1147, 0, 0, 0, 0, 0, '', 'Cracked Silithid Carapace (5877) only drops from Silithid Searcher (4130) while on The Swarm Grows (1147) '),
(1, 4131, 5877, 0, 0, 9, 0, 1147, 0, 0, 0, 0, 0, '', 'Cracked Silithid Carapace (5877) only drops from Silithid Invader (4131) while on The Swarm Grows (1147) '),
(1, 4132, 5877, 0, 0, 9, 0, 1147, 0, 0, 0, 0, 0, '', 'Cracked Silithid Carapace (5877) only drops from Silithid Ravager (4132) while on The Swarm Grows (1147) '),
(1, 4133, 5877, 0, 0, 9, 0, 1147, 0, 0, 0, 0, 0, '', 'Cracked Silithid Carapace (5877) only drops from Silithid Hive Drone (4133) while on The Swarm Grows (1147) ');
```

Comment (Helias) [reply data/sql/updates/pending_db_world/rev_1623236925695171584.sql:8]: you can group all these `insert into` in one

**Review by FrancescoBorzi — APPROVED** [review]

**Review by Helias — APPROVED** [review]
