### PR TITLE
fix(DB/creature): Fix Sunscale Lashtails movement

### LINKED ISSUE #5940: Sunscale Lashtail group not wandering when idle
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde 

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original CC report [https://github.com/chromiecraft/chromiecraft/issues/673](https://github.com/chromiecraft/chromiecraft/issues/673)
3 (marked) Sunscale Lashtail mobs just southeast of Crossroads are fixed in place and not exhibiting normal wandering behavior for their mob type. There is a 4th (unmarked) member of the group that is wandering as normal.
WoWScrnShot_051821_194935

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The mobs that are fixed in place should wander around while not in combat

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go creature 40493, 40495, and 40496
2. Observe 

##### EXTRA NOTES:

When aggro'd and then running out of combat the skull will start to wander as intended. The other two go right back to spawn points.
image

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ed3a575ba4ba3eff9d218d018de6a20b6e29db

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98576157-sunscale-lashtail-group-not-wandering-when-idle?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by anguaive**
Sunscale Lashtails (guid: 40489 - 40496) were standing still and their
respawn time was significantly lower compared to their wandering
brethren (guid: 19809 - 19817). I modified the immobile creatures'
attributes to match with the moving ones.

## Changes Proposed:
- Adjust the affected creatures' respawn time, spawn health, movement type and wander distance 

## Issues Addressed:

- Closes #5940
- Closes chromiecraft/chromiecraft#673

## SOURCE:

I checked creatures of similar type in the database (Sunscale Scytheclaws and Screechers). All of them share the 275 respawn time and all but a select few wander around randomly. The fact that there's a big gap between the moving Lashtails' guids and the immobile ones makes me think that they were added in much later and their attributes weren't set properly.

## Tests Performed:

- Tested in-game
- Made sure the updated creature entries were correct

## How to Test the Changes:

1. `go c` 40489 - 40496
2. Observe the creature moving

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1621501368347745883.sql [hunk 1]
```diff
@@ -0,0 +1,5 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1621501368347745883');
+
+UPDATE `creature`
+SET `modelid` = 1744, `spawntimesecs` = 275, `wander_distance` = 5, `curhealth` = 178, `movementtype` = 1
+WHERE `guid` BETWEEN 40489 AND 40496;
```
Comment (Kitzunu) [inline data/sql/updates/pending_db_world/rev_1621501368347745883.sql:5]: AND id =

Comment (anguaive) [reply data/sql/updates/pending_db_world/rev_1621501368347745883.sql:5]: is that actually needed? `id` isn't primary key on `creature`

Comment (Kitzunu) [reply data/sql/updates/pending_db_world/rev_1621501368347745883.sql:5]: It is preferred just in case someone did some custom thing.

This way you know you will only make changes to the correct creature as `id` can't be a primary or it would be wild :D

Comment (anguaive) [reply data/sql/updates/pending_db_world/rev_1621501368347745883.sql:5]: ah alright. that makes sense

File: data/sql/updates/pending_db_world/rev_1621501368347745883.sql [hunk 2]
```diff
@@ -0,0 +1,5 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1621501368347745883');
+
+UPDATE `creature`
+SET `modelid` = 1744, `spawntimesecs` = 275, `wander_distance` = 5, `curhealth` = 178, `movementtype` = 1
```
Comment (Kitzunu) [inline data/sql/updates/pending_db_world/rev_1621501368347745883.sql:4]: Why was modelid changed? You didnt mention it in the description so just want to check

Comment (anguaive) [reply data/sql/updates/pending_db_world/rev_1621501368347745883.sql:4]: This was set to 0 before, but since this type of creature only has 1 modelid assigned to it (1744), it would end up being 1744 anyway. I explicitly set it to 1744 to be uniform with the other mobs of the same type

**Comment by claudiodfc** [comment]
@FrancescoBorzi could you review this please?

**Review by FrancescoBorzi — APPROVED** [review]
