### PR TITLE
fix(DB/Creature): Removed duplicated creatures from Midsummer event.

### LINKED ISSUE #6469: Midsummer fest double spawning NPC's
Chromiecraft report https://github.com/chromiecraft/chromiecraft/issues/928

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

There are a lot of NPC's double spawning for the fire festival event. Anyone can feel free to add to this as they encounter more. 
Additionally some humans are labeled as "Goblin Commoner" and have beer mugs and talk about gathering colored eggs. as well as goblins with human masks with beer mugs saying the same thing. I don't think these should be spawned at all. This is all kinds of incorrect. (second screenshot)
image
image

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Should not be doubled up. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Wild shore Area, Stranglethorn Vale: .go creature: 96711, 23791, 16412, 94603, 94550, 94555, 94551, 16433, 94553, 94552, 94786, 94781, 94694, 94653, 94656, 94693, 94489, 94518, 94654, 94711, 94710, 94655
2. Booty Bay (these are general "Goblin commoner" with mugs and talking about gathering eggs, sometimes there are three: .go creature: 93646, 93762, 93763, 93652, 725, 93587, 93913, 724, 93764, 16433, 727, 93734, 93639, 726, 93610, 
3. Burning Steppes: .go creature: 245649, 248581

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99363467-midsummer-fest-double-spawning-npc-s?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #6469

## Issues Addressed:

- Closes #6469
- Closes https://github.com/chromiecraft/chromiecraft/issues/928
- Closes https://github.com/chromiecraft/chromiecraft/issues/935
- Closes https://github.com/chromiecraft/chromiecraft/issues/936
- Closes https://github.com/chromiecraft/chromiecraft/issues/937

## Tests Performed:

- Not tested.

## How to Test the Changes:

More info[here](https://github.com/azerothcore/azerothcore-wotlk/issues/6469)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by temperrr** [comment]
tested

Checked several locations and haven't seen double spawns.

**Review by Nefertumm — APPROVED** [review]

File: data/sql/updates/pending_db_world/rev_1639519249292727400.sql [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+94934,94934,94934,94935,94935,94935,94936,94936,94936,94937,94937,94937,94950,94956,202858,202859,202860,202861,248565,248566,248567,248568,248569,248570,248571,
+248573,248574,248576,248577,248578,248579,248580,248583);
+
+DELETE FROM `game_event_creature` WHERE `guid` IN (86249,86258,86264,86265,86716,86898,90490,94518,94553,94555,94603,94604,94634,94635,94637,94649,94693,94694,
+94699,94700,94704,94710,94711,94738,94747,94753,94760,94761,94762,94765,94773,94786,94796,94803,94805,94808,94814,94831,94839,94840,94862,94862,94862,94863,94863,
+94863,94920,94920,94921,94921,94922,94923,94924,94925,94926,94927,94928,94929,94930,94930,94930,94930,94931,94931,94931,94931,94932,94932,94932,94932,94933,94933,
+94933,94933,94934,94934,94934,94935,94935,94935,94936,94936,94936,94937,94937,94937,94950,94956,202858,202859,202860,202861,248565,248566,248567,248568,248569,
+248570,248571,248573,248574,248576,248577,248578,248579,248580,248583);
+
+DELETE FROM `creature_addon` WHERE `guid ` IN (86249,86258,86264,86265,86716,86898,90490,94518,94553,94555,94603,94604,94634,94635,94637,94649,94693,94694,94699,94700,
```
Comment (acidmanifesto) [inline data/sql/updates/pending_db_world/rev_1639519249292727400.sql:15]: you have a space after guid. Please Change to
```
DELETE FROM `creature_addon` WHERE `guid` IN (86249,86258,86264,86265,86716,86898,90490,94518,94553,94555,94603,94604,94634,94635,94637,94649,94693,94694,94699,94700,
94704,94710,94711,94738,94747,94753,94760,94761,94762,94765,94773,94786,94796,94803,94805,94808,94814,94831,94839,94840,94862,94862,94862,94863,94863,94863,94920,
94920,94921,94921,94922,94923,94924,94925,94926,94927,94928,94929,94930,94930,94930,94930,94931,94931,94931,94931,94932,94932,94932,94932,94933,94933,94933,94933,
94934,94934,94934,94935,94935,94935,94936,94936,94936,94937,94937,94937,94950,94956,202858,202859,202860,202861,248565,248566,248567,248568,248569,248570,248571,
248573,248574,248576,248577,248578,248579,248580,248583);
```

**Review by acidmanifesto — CHANGES_REQUESTED** [review]

**Review by acidmanifesto — APPROVED** [review]
