### PR TITLE
fix(Core/Loot): Fix Master Loot visibility and assignment for quest i…

### LINKED ISSUE #16653: (BUG ) ICC loot template RequeridQuest Rotface's and Festergut's Acidic Blood and Shadowfrost Shard
### Current Behaviour

-only a player can see these items although more people have the mission

-the rest of the raid cannot see these articles even though they have the mission

Screenshot_12
Screenshot_13

### Expected Blizzlike Behaviour

all people who have the quest should see the item in the loot

### Source

_No response_

### Steps to reproduce the problem

1- 3 player with mission https://www.wowhead.com/wotlk/es/quest=24548/el-trono-astillado
2- loot in free mode or ML
2-kill any boss Example my test was in : Rotface's , Festergut's and valanar
3- only one player can see the loot : Rotface's and Festergut's Acidic Blood and Shadowfrost Shard 

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/cd01453b6c1d54aea5f447c43213d36df7db09f0

Last Rev

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by EricksOliveira**
…tems

Fix Master Loot handling for quest items.

Master Looter can see quest items without the quest but cannot loot them. Only players with the quest are added as allowed looters, fixing ICC quest item distribution (Acidic Blood, Shadowfrost Shard).

## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

### AI-assisted Pull Requests

> [!IMPORTANT]
> While the use of AI tools when preparing pull requests is not prohibited, contributors must clearly disclose when such tools have been used and specify the model involved.
> 
> Contributors are also expected to fully understand the changes they are submitting and must be able to explain and justify those changes when requested by maintainers.

- [x] AI tools (e.g. ChatGPT, Claude, or similar) were used entirely or partially in preparing this pull request. Please specify which tools were used, if any.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16653

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by lakxas** [comment]
Tested and everything works fine.
People with the quest can see the item and can roll the dice if the loot is in free mode or group.
If the loot is on masterloot mode, the masterlooter can see the item (even if he doesnt have the quest) and can give it to the players that have the quest in their quest log, If the player do not have it, the masterlooter can't assing the item to them, so it works perfectly.

Great job Ericks

File: src/server/game/Loot/LootMgr.cpp [hunk 1]
```diff
@@ -418,83 +418,34 @@ bool LootItem::AllowedForPlayer(Player const* player, ObjectGuid source) const
...
-        if (pProto->StartQuest)
-        {
-            // Don't drop the item if the player has already finished the quest OR player already has the item in their inventory, and that item is unique OR the player has not finished a prerequisite quest
-            uint32 prevQuestId = sObjectMgr->GetQuestTemplate(pProto->StartQuest) ? sObjectMgr->GetQuestTemplate(pProto->StartQuest)->GetPrevQuestId() : 0;
-            if (player->GetQuestStatus(pProto->StartQuest) != QUEST_STATUS_NONE || (player->HasItemCount(itemid, pProto->MaxCount) && pProto->MaxCount) || (prevQuestId && !player->GetQuestRewardStatus(prevQuestId)))
-                return false;
-        }
-    }
+    // QUEST RULE (real rule — NEVER bypass)
+    if (needs_quest && !player->HasQuestForItem(itemid))
```
Comment (sogladev) [inline src/server/game/Loot/LootMgr.cpp]:
```suggestion
    if (needs_quest && !pProto->HasFlagCu(ITEM_FLAGS_CU_IGNORE_QUEST_STATUS) && !player->HasQuestForItem(itemid))
```

Handling of `ITEM_FLAGS_CU_IGNORE_QUEST_STATUS` needs to be re-added

**Review by sogladev — CHANGES_REQUESTED** [review]
Some parts of the previous logic were removed, that may cause regressions.


>  // Quest item is not free for all and is already assigned to another player
        // or player doesn't need it

Must be careful to not re-introduce a bug that was fixed by:
- https://github.com/azerothcore/azerothcore-wotlk/pull/13720

Also needs testing for:

> // Don't drop the item if the player has already finished the quest OR player already has the item in their inventory, and that item is unique OR the player has not finished a prerequisite quest

File: src/server/game/Loot/LootMgr.cpp (hunk 1 above)
Comment (EricksOliveira) [reply src/server/game/Loot/LootMgr.cpp]: Ok. Ty

**Comment by EricksOliveira** [comment]
> Some parts of the previous logic were removed, that may cause regressions.
> 
> > // Quest item is not free for all and is already assigned to another player
> > // or player doesn't need it
> 
> Must be careful to not re-introduce a bug that was fixed by:
> 
> * #13720
> 
> Also needs testing for:
> 
> > // Don't drop the item if the player has already finished the quest OR player already has the item in their inventory, and that item is unique OR the player has not finished a prerequisite quest

I tested it and it worked well for me. Even if the player has the quest item, it doesn't reappear in the loot.

**Review by sogladev — APPROVED** [review]
works ✅

I tested related quests for Marrowgar and Festergut following https://github.com/azerothcore/azerothcore-wotlk/pull/21001#issuecomment-2585240410

**Comment by Nyeriah** [comment]
This bugged quest loot for items that should drop for every party member
they now only drop for 1 player

**Comment by lakxas** [comment]
While reviewing the loot system, I've noticed a potential crash that might be worth checking out.

In group.cpp, within the NeedBeforeGreed() function, the code doesn't check whether the item exists. If the item doesn't exist, “item->Quality >= uint32(m_lootThreshold)” will return a null pointer.

image

GroupLoot() function does it right

image

I didn't check if it's necessary somewhere else

**Comment by Nyeriah** [comment]
I'm fairly sure it is an impossible crash because item template is already validated elsewhere when loot tables are loaded, so you would need to go out of your way to deliberately force a crash here

**Comment by sogladev** [comment]
> While reviewing the loot system, I've noticed a potential crash that might be worth checking out.
> 
> In group.cpp, within the NeedBeforeGreed() function, the code doesn't check whether the item exists. If the item doesn't exist, “item->Quality >= uint32(m_lootThreshold)” will return a null pointer.
> 

`ASSERT(item, "message")` may be more appropriate than the if `!item` checks. This is something you could open a PR for
