### PR TITLE
fix(DB/Quest):BlackKnight‘Order npc required credit count 

### LINKED ISSUE #11843: Quest: The Black Knight's Orders no completion after flying with the griffin
### Current Behaviour

Use the questitem on the griffin and fly to the island when u arrive u do not get a quest completion.

### Expected Blizzlike Behaviour

Use the questitem on the griffin and fly to the island when u arrive u should get a quest completion, but ur not getting it

### Source

https://www.youtube.com/watch?v=xShQmMQSa1k | **Time: 1:43**

### Steps to reproduce the problem

1. .q a 13663
2. .tele argent
3. go behind u to the griffin
4. use questitem
5. see what happens

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/f7674acb58001a72dccfa3d60f63cb3bd0daeed6

### Operating system

Windows

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by betayi**
## Changes Proposed:
-  fix #11843
-  

## Issues Addressed:

- Closes #11843

## Tests Performed:

- Tested, works, quest can complete
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Maelthyrr** [comment]
Thanks for the PR, it's work fine :)

File: data/sql/updates/pending_db_world/fix_blackkngihtorder.sql [hunk 1]
```diff
@@ -0,0 +1,2 @@
+
+UPDATE `smart_scripts` SET target_type = 23 WHERE (`entryorguid` = 33519) AND (`source_type` = 0) AND (`id` IN (1));
```
Comment (Nefertumm) [inline data/sql/updates/pending_db_world/fix_blackkngihtorder.sql:2]:
```suggestion
UPDATE `smart_scripts` SET `target_type` = 23 WHERE (`entryorguid` = 33519) AND (`source_type` = 0) AND (`id` IN (1));
```

**Review by Nefertumm — APPROVED** [review]
