### PR TITLE
fix(Scripts/BWL): drakes in Blackwing Lair can't attack

### LINKED ISSUE #7246: Drakes in Blackwing Lair can't attack
### Current Behaviour

- Flamegor, Ebonroc and Firemaw in blackwing lair are stuck and can't fight back when attacked https://i.gyazo.com/6f1ff8f1cbc78b7342907201757e6a52.mp4
- they seem to instantly reset because they repeatidly make aggro sounds when hit and don't evade hits
- Going in melee doesn't let them attack the player either

### Expected Blizzlike Behaviour

They should be able to move and attack the players...

### Source

https://www.youtube.com/watch?v=FgMAbpD1Faw random video

### Steps to reproduce the problem

1. `.gm on` to tele in the instance
2.  `.go creature 85783`
3.  turn gm off `.gm off`
4. try attacking the drakes and see how they react

### Extra Notes

_No response_

### AC rev. hash/commit

8ca9da6421d1777f5f7ae911a385c7d99fe5d0e1

### Operating system

Windows 10 x64

### Custom changes or Modules

None

### PR DESCRIPTION
**Pull request by Zenslash**
## Changes Proposed:
-  I commented out a condition in ```CheckRequiredBosses```, which in fact we do not need. Now Drakes works fine

## Issues Addressed:
- Closes #7246

## SOURCE:
https://www.youtube.com/watch?v=FgMAbpD1Faw random video

## Tests Performed:
- Tested on local server

## How to Test the Changes:
1. ```.gm on``` to tele in the instance
2. ```.go creature 85783```
3. turn gm off ```.gm off```
4. try attacking the drakes and see how they react

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/instance_blackwing_lair.cpp [hunk 1]
```diff
@@ -143,8 +143,8 @@ class instance_blackwing_lair : public InstanceMapScript
                 case DATA_FIREMAW:
                 case DATA_EBONROC:
                 case DATA_FLAMEGOR:
-                    if (GetBossState(DATA_BROODLORD_LASHLAYER) != DONE)
-                        return false;
+                    //if (GetBossState(DATA_BROODLORD_LASHLAYER) != DONE)
+                    //   return false;
```
Comment (Kitzunu) [inline src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/instance_blackwing_lair.cpp:147]: if we dont need it, remove it

**Review by Helias — APPROVED** [review]

**Comment by Shybuia** [comment]
Hi there, I tested it and here are results:
Pre-PR : https://youtu.be/w1FH4IECWr4
Post-PR: https://youtu.be/KaFHwmtGtiw
Conclusion: Drakes are now attackable and encounter can be done.

**Comment by Zenslash** [comment]
@Shybuia Thanks for testing
