### PR TITLE
fix(DB/Quest): deeprun rat roundup

### LINKED ISSUE #19572: (DB/Quest) Deeprun Rat Roundup
### Current Behaviour

* Accept the quest and get the provided item 'Rat Catcher's Flute'
* Kill the 5 rats and the quest is completed
* Turn in the quest

### Expected Blizzlike Behaviour

* Accept the quest and receive the quest item "Rat Catcher's Flute"
* Use the flute on the rats
  * The rats get friendly and following you
  * The rats gets counted as quest objective
* If you catched 5 rats the quest is complete
* Turn in the quest,  "Rat Catcher's Flute" is removed from inventory and the rats despawn.

### Source

https://www.youtube.com/watch?v=4Phvjninx_s

### Steps to reproduce the problem

Be level 10 or higher a do the quest as described above

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. f5e44cd8a65a+ 2024-08-01 15:41:23 +0800 (Playerbot branch) (Win64, RelWithDebInfo, Static)
Connected players: 1. Characters in world: 0.
Connection peak: 1.
Server uptime: 6 minute(s) 17 second(s)
Update time diff: 1ms. Last 500 diffs summary:
|- Mean: 1ms
|- Median: 1ms
|- Percentiles (95, 99, max): 3ms, 4ms, 4ms
Using SSL version: OpenSSL 3.3.1 4 Jun 2024 (library: OpenSSL 3.3.1 4 Jun 2024)
Using Boost version: 1.85.0
Using CMake version: 3.30.1
Using MySQL version: 80039
Found MySQL Executable: D:/Programme/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows 10.0.22631
Worldserver listening connections on port %hu
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in D:/WoW/AzerothCorePlayerBotsBuild/bin/RelWithDebInfo/Data/maps. Total size: 291014951 bytes
vmaps directory located in D:/WoW/AzerothCorePlayerBotsBuild/bin/RelWithDebInfo/Data/vmaps. Total size: 658130721 bytes
mmaps directory located in D:/WoW/AzerothCorePlayerBotsBuild/bin/RelWithDebInfo/Data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Using Playerbots DB Revision:
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: playerbots_names.sql
Latest WorldDatabase update: zz_optional_aq_quest_nerf.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
PlayerbotsDatabase queue size: 0
List of enabled modules:
|- mod-individual-progression
|- mod-playerbots

### Operating system

Windows 11 x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by Blackbird102**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #19572

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Accept the quest
2. use the flute on the rats
3. turn in the quest if you catched 5

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1722804930814975200.sql [hunk 1]
```diff
@@ -0,0 +1,5 @@
+-- Set RequiredNpcOrGo1 of quest 6661 Deeprun Rat Roundup to 13017
+UPDATE `quest_template` SET `RequiredNpcOrGo1`=13017 WHERE `ID`=6661;
```
Comment (heyitsbench) [inline data/sql/updates/pending_db_world/rev_1722804930814975200.sql:2]: This appears to match a 51831 sniff.

**Review by heyitsbench — APPROVED** [review]

**Comment by Grimdhex** [comment]
Can you fix the tittle please ? You can use : fix(DB/Quest): deeprun rat roundup

**Review by elthehablo — APPROVED** [review]
