### PR TITLE
fix(Core/Server): Improvements to antidos opcode handling

### LINKED ISSUE #21140: Rework auctionhouse Update causes people to be kicked if buy to many items at once
Issue linked from CC: https://github.com/chromiecraft/chromiecraft/issues/7657

Triage Notes: https://github.com/chromiecraft/chromiecraft/issues/7657#issuecomment-2585396150

- I tested this with 2 different accounts.
- Made sure the "buyer" account had [auctionator](https://felbite.com/addon/4868-auctionator/)
- The "seller" account would have 40 linen clothes (.additem 2589 40) and would make 40 stacks of 1 auctions with 10 copper for bid and 20 bid for buyout (you will need to .modify money 100g)
- With the buyer try buying 11 linen clothes, you will be kicked but the items will be in your mail still (no error on the the worldserver)

Original Post Below: 

---

### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Buying 10 or more items at the same time from AH using Auctionator disconnects the player. Items are succesfully bought and can be found in mailbox after relog.

This problem started happening on Chromiecraft within the last month or so. For some reason server kicks the player. I did the same tests on other 3.3.5a servers with the same addon and there's no such issue.

### Expected Blizzlike Behaviour

Server shouldn't kick the player.

### Source

No source required.

### Steps to reproduce the problem

1. Install Auctionator addon (from Felbite or somewhere else)
2. Login to chromiecraft live server
3. On "Buy" tab, search for an item of which you can buy 10 or more (eg. Light Armor Kit, any potion etc.). It has to be 10 x 1 (10 stacks of 1) and not 1 x 10 (1 stack of 10) (Screenshot: https://imgur.com/a/CGKe6Py)
4. Enter the amount to buy (10+) and click buy.
5. You are disconnected.

### Extra Notes

There are different working versions of Auctionator but it doesn't matter which one you are using for this test. I will put 2 links below for easy downloading:
1- https://forum.warmane.com/showthread.php?t=412904&p=3030654&viewfull=1#post3030654
2- https://felbite.com/addon/4868-auctionator/

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5f020de5466e3894914fe424229c4b9f3d138b2f

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by Takenbacon**
Couple changes to antidos opcode handling:

- Moves hardcoded list to database, allowing individual handling policies per opcode and run time reloading
- Implements BlockingThrottle & DropPacket policy types
- Changes AH search requests to BlockingThrottle policy type
- Not specifically related to this change but adds a WorldGlobals file to prevent adding more clutter in World class and for future use with moving around other global storages

**Implementation note**: BlockingThrottle isn't an ideal solution as it temporarily prevents processing of remaining packets in queue (hence the name "blocking") and as such should only be used in careful and very specific cases. In an ideal world we'd have multiple packet processing queues with different properties however that would be a much more involved change. I can attest from experience that using a simple queue block to throttle AH searches works sufficiently enough without noticeable effects.

## Changes Proposed:

This PR proposes changes to:
-  [X] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [X] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #21140 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Takenbacon** [comment]
@skelUA Try this

File: src/server/game/Globals/WorldGlobals.cpp [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+
+    uint32 count = 0;
+
+    do
+    {
+        Field* fields = result->Fetch();
+
+        uint16 opcode = fields[0].Get<uint16>();
+        if (opcode >= NUM_OPCODE_HANDLERS)
+            continue;
```
Comment (Kitzunu) [inline src/server/game/Globals/WorldGlobals.cpp:49]: throw error like
```cpp
LOG_ERROR("server.loading", "Unkown opcode {} in antidos_opcode_policies, skipping.", opcode);

File: src/server/game/World/World.cpp [hunk 2]
```diff
@@ -1952,6 +1952,9 @@ void World::SetInitialWorldSettings()
     LOG_INFO("server.loading", "Load Channels...");
     ChannelMgr::LoadChannels();
 
+    LOG_INFO("server.loading", "Loading AntiDos opcode policies");
```
Comment (Kitzunu) [inline src/server/game/World/World.cpp:1955]: shouldnt it be "AntiDDoS? o.o

File: src/server/game/Globals/WorldGlobals.cpp [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+        std::unique_ptr<AntiDosOpcodePolicy> policy = std::make_unique<AntiDosOpcodePolicy>();
+        policy->Policy = fields[1].Get<uint8>();
+        policy->MaxAllowedCount = fields[2].Get<uint16>();
+
+        _antiDosOpcodePolicies[opcode] = std::move(policy);
+
+        ++count;
+    } while (result->NextRow());
+
+    LOG_INFO("server.loading", ">> Loaded {} AntiDos Opcode Policies in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
```
Comment (Kitzunu) [inline src/server/game/Globals/WorldGlobals.cpp:60]: Could use _antiDosOpcodePolicies.size() instead of count.

Also for reload case we need to clear _antiDosOpcodePolicies before loading into it?

**Comment by Kitzunu** [comment]
Codestyle / SQL (pull_request) can be ignored

File: data/sql/updates/pending_db_world/rev_1739897580268046640.sql [hunk 4]
```diff
@@ -0,0 +1,110 @@
+DROP TABLE IF EXISTS `antidos_opcode_policies`;
+CREATE TABLE `antidos_opcode_policies` (
+  `Opcode` smallint unsigned NOT NULL,
+  `Policy` tinyint unsigned NOT NULL,
+  `MaxAllowedCount` smallint unsigned NOT NULL
+) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
```
Comment (Kitzunu) [inline data/sql/updates/pending_db_world/rev_1739897580268046640.sql:6]:
```suggestion
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

Comment (Kitzunu) [reply data/sql/updates/pending_db_world/rev_1739897580268046640.sql:6]: Should opcode be able to have several entries here?
If not I suggest setting it as primary key. If you can have more than one policy I would suggest PRI Opcode and Policy.

Alternative make policy a bitmask to only have one opcode entry

File: src/server/game/Globals/WorldGlobals.cpp (hunk 1 above)
Comment (Takenbacon) [reply src/server/game/Globals/WorldGlobals.cpp:53]: Done

File: src/server/game/World/World.cpp (hunk 2 above)
Comment (Takenbacon) [reply src/server/game/World/World.cpp:1955]: Technically speaking, no. The first "D" in DDoS is "Distributed", which these policies are per-session, thus not distributed.

File: src/server/game/Globals/WorldGlobals.cpp (hunk 3 above)
Comment (Takenbacon) [reply src/server/game/Globals/WorldGlobals.cpp:65]: It's an array for O(1) lookup speed, size would return the full length of the array rather than the amount of non-null elements.

But yes, you're right with needing to clear it (or in this case, default nullptr init the full array)

File: data/sql/updates/pending_db_world/rev_1739897580268046640.sql (hunk 4 above)
Comment (Takenbacon) [reply data/sql/updates/pending_db_world/rev_1739897580268046640.sql]: Shouldn't be several entries no, it would make no sense (and not properly handled) to have multiple policies either. I've added the primary key to Opcode.

File: src/server/game/World/World.cpp (hunk 2 above)
Comment (Kitzunu) [reply src/server/game/World/World.cpp:1955]: I see

File: src/server/game/Globals/WorldGlobals.cpp (hunk 3 above)
Comment (Kitzunu) [reply src/server/game/Globals/WorldGlobals.cpp:65]: Alright!

**Review by Kitzunu — APPROVED** [review]

File: src/server/game/Globals/WorldGlobals.cpp [hunk 5]
```diff
@@ -0,0 +1,75 @@
...
+{
+    static WorldGlobals instance;
+    return &instance;
+}
+
+void WorldGlobals::LoadAntiDosOpcodePolicies()
+{
+    uint32 oldMSTime = getMSTime();
+
+    _antiDosOpcodePolicies.fill(nullptr);
```
Comment (Kitzunu) [inline src/server/game/Globals/WorldGlobals.cpp:33]: Would _antiDosOpcodePolicies = {} work here to just reinitialize it?

Comment (Takenbacon) [reply src/server/game/Globals/WorldGlobals.cpp]: Yeah, I forgot it was a unique_ptr. I guess I deserve that one for committing just before falling asleep.

**Comment by Nyeriah** [comment]
https://gist.github.com/Nyeriah/c2fe3652e36cf315f8b721f939c5d698

CMSG_CONTACT_LIST seems to be haywire, flagging many players per sec, I moved the policy from kick to warn to observe it so its spamming a lot as the logs show (very high packet counts per player, e.g over 700, while the policy expects 200 max)

**Comment by Takenbacon** [comment]
@Nyeriah That's strange, is that the only problematic opcode? And it affects more than a couple different accounts? I'll check tonight if there's any strange logic flaws. 800 packets of CMSG_CONTACT_LIST per second would be pretty crazy.

**Comment by Nyeriah** [comment]
Yep, no logs from other opcodes so far, but sitting on over 50k lines of this one, from multiple accounts. The vast majority of them with no character (entering world I assume), with rare exceptions

**Comment by Takenbacon** [comment]
> Yep, no logs from other opcodes so far, but sitting on over 50k lines of this one, from multiple accounts. The vast majority of them with no character (entering world I assume), with rare exceptions

So far I am unable to reproduce, my client doesn't even request CMSG_CONTACT_LIST unless I click the social tab while already in game (and only one opcode is sent). I suspect there may be an addon causing this and may be caused by server requeuing packets while not in world leading to a loop of repeatedly trying to process the same packet over and over but I am not certain yet. Ultimately, the server should never be attempting to requeue up packets, I removed that quite a few years ago on Warmane and never had any noticeable side effects but I'd like to do some testing and confirm first.

Any way to reach out to some of these particular players by chance and ask them if they have any addons in common?

**Comment by amed80** [comment]
@Takenbacon using [TSM](https://felbite.com/addon/3303-tsm/) for example

**Comment by Takenbacon** [comment]
> @Takenbacon using [TSM](https://felbite.com/addon/3303-tsm/) for example

Wow, you're right. That does cause it, what a garbage addon (and looks like it's back ported? - not even designed for 3.3.5....). It is indeed caused by packet requeuing. I'll see about just removing that.
