### PR TITLE
Fix (DB\Quest\SmartScript): Quest 9540 Totem of Tiki

### LINKED ISSUE #7338: Azuremyst Isle - "Totem of Tikti" Quest Accept Script Fails If Player Is Mounted
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1404

When you accept the quest [Totem of Tikti](https://wotlkdb.com/?quest=9540) from its [quest giver](https://wotlkdb.com/?npc=17361) if your character is mounted up, quest won't trigger it's scripts to spawn [Stillpine Ancestor Coo](https://wotlkdb.com/?npc=17391) which should cast [Ghost Walk](https://wotlkdb.com/?spell=30424) on the player.

Link for video: https://youtu.be/Dq-r46IfYNk

Tester: Confirmed. The video above shows it all, but ran through it again and replicated it. The Totem of Coo has SmartAI set to cast an invoker, the Stillpine Ancestor Coo, ID 17391. (It in turn has a long timed script that end up casting Ghost Walk on the player, but when the player is mounted this is failing before it gets that far.)

Mounted: no summons
WoWScrnShot_081421_210003

Dismounted: invoker appears:
WoWScrnShot_081421_210120

### Expected Blizzlike Behaviour

Quest script should trigger no matter whether if the player is mounted or not.

### Source

https://youtu.be/xazVLN272Ac
There was lack of videos from classic tbc which includes mounted players.

### Steps to reproduce the problem

1. .go c 62735 and talk to the Totem of Coo.
2. Accept [Totem of Tikti](https://wotlkdb.com/?quest=9540) while being mounted
3. Then wait for scripts to trigger

### Extra Notes

I know that video linked in source text box is exactly from TBC or WOTLK but considering that quest giver is counted as a NPC and not as an object like for [example](https://wotlkdb.com/?object=68) the very least it should dismount you.

Also i didn't exactly tried to return the quest without having the Ghost Walk buff on me but it would probably worked out.
Anyway the issue is it doesn't trigger properly while player's character is mounted up.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by TheDdraig**
## Changes Proposed:
-  Missing entire script for last part of chain so added this, waypoints and correct walk/run values from sniffer
-  

## Issues Addressed:

- Added missing script issue mentions cant start while mounting, but didnt mention Totem Yor part has no script, just a simple spell cast.
- Also corrected all npc walk/run speeds all values taken from sniffer and added waypoints for last part also from sniffer
- Closes #7338

## SOURCE:
Sniffer Team

## Tests Performed:
- Build
- Performed

## How to Test the Changes:
1. Do chain quest https://tbc.wowhead.com/quest=9538/learning-the-language
2. Totem of Yor part was missing the entire script, this adds the script and the waypoints from sniff
3. The only issue is when he casts Shadow of the Forest on the player you have to move or you wont see Stillpine Ancestor Yor, this is a visual state issue within the core
4. This is the spell for reference: https://tbc.wowhead.com/spell=30448/shadow-of-the-forest

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1641421027611299094.sql [hunk 1]
```diff
@@ -0,0 +1,226 @@
...
+DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=@SOURCETYPE;
+UPDATE creature_template SET AIName="SmartAI" WHERE entry=@ENTRY LIMIT 1;
+INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES 
+(@ENTRY,@SOURCETYPE,0,0,19,0,100,0,9541,0,0,0,85,30443,2,16384,0,0,0,7,0,0,0,0.0,0.0,0.0,0.0,"Totem of Tikti - Quest accepted - Cast Spell on player");
+
+-- Stillpine Ancestor Tikti
+SET @ENTRY := 17392;
+SET @SOURCETYPE := 0;
+
+
```
Comment (acidmanifesto) [inline data/sql/updates/pending_db_world/rev_1641421027611299094.sql:96]: reduce to one line break inbetween not two.

File: data/sql/updates/pending_db_world/rev_1641421027611299094.sql [hunk 2]
```diff
@@ -0,0 +1,226 @@
...
+UPDATE `creature_template` SET `speed_walk`='0.6666', `speed_run`='0.8571' WHERE `entry`='17391';
+UPDATE `creature_template` SET `speed_walk`='0.6666', `speed_run`='0.8571' WHERE `entry`='17392';
+UPDATE `creature_template` SET `speed_walk`='1', `speed_run`='0.8571' WHERE `entry`='17393';
+UPDATE `creature_template` SET `speed_walk`='0.6666', `speed_run`='0.8571' WHERE `entry`='17410';
+
+-- Corrected timer to work with the new speed values
+
+-- Entire Quest Chain for: https://tbc.wowhead.com/quest=9538/learning-the-language
+
+
```
Comment (acidmanifesto) [inline data/sql/updates/pending_db_world/rev_1641421027611299094.sql:14]: reduce to one line break, not two.

**Review by acidmanifesto — CHANGES_REQUESTED** [review]

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
Thank you for the PR
