### PR TITLE
Fix(DB/Creature) Stonemaul spirit from TrinityCore

### LINKED ISSUE #5805: Stonemaul Spirits Not Attacking/Missing Text
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/617

Stonemaul Spirit (https://wowgaming.altervista.org/aowow/?npc=23786) for quest Spirits of Stonemaul Hold (https://wowgaming.altervista.org/aowow/?quest=11159) is missing the quote texts when he is attacking and does not aggro/attack the player when summoned if player does not move or attack him.

nodanger

https://user-images.githubusercontent.com/81782124/117977637-31e91500-b370-11eb-91e4-2b16b876c491.mp4

Tester's notes: this is another of the 'summoned mob isn't hostile' glitches like https://github.com/azerothcore/azerothcore-wotlk/issues/5610

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Stonemaul Spirit should auto aggro/attack player once summoned even if the player stands still, and they should be using their text quotes while attacking.

Quotes are:
- "You leave Stonemaul lands now!"
- "Me crush puny friend of dragons!"
- "Raaar!!! Me smash %racename"
- "Why you wake ghost? Where other Stonemauls?!

Source is https://youtu.be/jHpHWzHj42s?t=65

##### STEPS TO REPRODUCE THE PROBLEM:

1. .quest add 11159
2. .additem [energized totem]
3. .go c 33904 - takes you to a nearby mob. Teleporting direcyly to the ogre bones is a bad idea because you tend to get stuck in them.
4. Find a quest target and use the quest item on it
5. Do not move when you summon the ogre and see that he does not attack unless you move or attack him
6. When he is attacking see that he is not using his text quotes

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

### PR DESCRIPTION
**Pull request by Branel**
## Changes Proposed:
-  It will now attack after being summoned
-  It will now broadcast text while attacking

## Issues Addressed:

- Closes #5805

## SOURCE:

Thanks to @zenox92, @Killyana and @Aokromes for their original work on this fix. (Serveral commits)

## Tests Performed:

Tested on local windows 10 server

## How to Test the Changes:

1. .quest add 11159
2. .additem [energized totem]
3. .go c 33904 - takes you to a nearby mob. Teleporting direcyly to the ogre bones is a bad idea because you tend to get stuck in them.
4. Find a quest target and use the quest item on it

## Known Issues and TODO List:

 N/A

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1620836710197850400.sql [hunk 1]
```diff
@@ -0,0 +1,18 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1620836710197850400');
+UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=23786;
```
Comment (pangolp) [inline data/sql/updates/pending_db_world/rev_1620836710197850400.sql:2]: Maybe it would be good to verify that it doesn't have a C++ script or it would not be necessary?

```sql
UPDATE `creature_template` SET `AIName`="SmartAI", `ScriptName`="" WHERE `entry`=23786;
```

Or maybe it's not necessary, but just to make sure it doesn't have anything.

**Comment by arielcami** [comment]
Before executing the script it didn't show any dialogs, 
after running the script it only shows the text when spawns, 
but it doesn't show text when it's pulled.

https://youtu.be/jHpHWzHj42s?t=150

File: data/sql/updates/pending_db_world/rev_1620836710197850400.sql (hunk 1 above)
Comment (Branel) [reply data/sql/updates/pending_db_world/rev_1620836710197850400.sql:2]: Couldn't find any C++ script, those are mostly reserved for creatures with many tasks mostly within dungeons and raids. It's always good to make sure though!

**Comment by Branel** [comment]
> Before executing the script it didn't show any dialogs,
> after running the script it only shows the text when spawns,
> but it doesn't show text when it's pulled.
> 
> https://youtu.be/jHpHWzHj42s?t=150

Thank you for testing! I have now updated the conditions which should make sure that the ogre says his line after he is in combat.

File: data/sql/updates/pending_db_world/rev_1620836710197850400.sql (hunk 1 above)
Comment (pangolp) [reply data/sql/updates/pending_db_world/rev_1620836710197850400.sql:2]: > Couldn't find any C++ script, those are mostly reserved for creatures with many tasks mostly within dungeons and raids. It's always good to make sure though!

Correct. Just in case. Because in case I had it, I think C++ has priority. But anyway, it was a doubt, it was not a statement. I usually leave it empty.

**Comment by Azcobu** [comment]
Tested, it's 99% there:

- Ogres immediately turn hostile and attack when spawned
- They say most of their lines correctly

The only problem is that one of the lines is incorrect:

WoWScrnShot_051721_233709

A similar problem in another ticket on TC was solved by adding the missing target name 'caster' to the Talk() call arguments, but I don't know enough to say if that applies here.

**Comment by Branel** [comment]
Thank you for your spotless testing! I have now made sure the ogre correctly specifies the race! 
image

**Review by FrancescoBorzi — APPROVED** [review]

**Review by pangolp — APPROVED** [review]
