### PR TITLE
fix(Core/Unit): fixed issue with ranged auto-attack having a weird sound issue if a player is attempting to attack a target who's not in the line of sight

### LINKED ISSUE #3431: Target not in line of sight bug
^
Target not in line of sight bug

##### CURRENT BEHAVIOUR:

When I try to attack a target which is not in line of sight with a ranged weapon. I get this incredible annoying "Aim sound" multiple times. It only goes away when I get in line of sight with the target.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You shouldnt be able to get in gun target mode at all when you are not in side.

This behaviour doesnt happen on Warmane.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Take a gun 
2.  Target a mob which is not in line of sight.
3.  Et voila.

##### EXTRA NOTES:

No

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/03bd4fafe65d7662b0b1fd3e1614b32b20da40ca

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/92874332-target-not-in-line-of-sight-bug?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Goatform**
## CHANGES PROPOSED:
- Added null check for spellInfo (autoattack)
- Added missing check for autoattack interrupt
- Some cosmetic code adjustments.

## ISSUES ADDRESSED:
- Closes #3431

## TESTS PERFORMED:
- Build
- Test in-game
- Tested all types of ranged weapons such as gun, bow, crossbow, including wand

## HOW TO TEST THE CHANGES:
- Create hunter
- Find attackable target
- Hide behind the tree / wall / building
- Attempt to auto-attack

RESULT: You will see that there's no longer weird sound / animation.

## KNOWN ISSUES AND TODO LIST:
- None that I am aware of

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Akimboss** [comment]
Tested, works fine thank you

File: src/server/game/Entities/Unit/Unit.cpp [hunk 1]
```diff
@@ -3213,36 +3213,44 @@ void Unit::_UpdateSpells(uint32 time)
...
 void Unit::_UpdateAutoRepeatSpell()
 {
-    // check "realtime" interrupts
-    if ((GetTypeId() == TYPEID_PLAYER && ToPlayer()->isMoving()) || IsNonMeleeSpellCast(false, false, true, m_currentSpells[CURRENT_AUTOREPEAT_SPELL]->m_spellInfo->Id == 75))
+    SpellInfo const* spellProto = nullptr;
+    if (m_currentSpells[CURRENT_AUTOREPEAT_SPELL])
+        spellProto = m_currentSpells[CURRENT_AUTOREPEAT_SPELL]->m_spellInfo;
+
+    if (!spellProto)
+        return;
```
Comment (FrancescoBorzi) [inline src/server/game/Entities/Unit/Unit.cpp:3221]: please use brackets on `if` blocks, even when it's 1-line

File: src/server/game/Entities/Unit/Unit.cpp [hunk 2]
```diff
@@ -3213,36 +3213,44 @@ void Unit::_UpdateSpells(uint32 time)
...
+
+    // Check "realtime" interrupts
+    if ((GetTypeId() == TYPEID_PLAYER && ToPlayer()->isMoving() && spellProto->Id != 75) || IsNonMeleeSpellCast(false, false, true, spellProto->Id == 75))
```
Comment (FrancescoBorzi) [inline src/server/game/Entities/Unit/Unit.cpp:3224]: it would be nice to avoid magic numbers like "75" and wrap them into constants instead

File: src/server/game/Entities/Unit/Unit.cpp [hunk 3]
```diff
@@ -3213,36 +3213,44 @@ void Unit::_UpdateSpells(uint32 time)
...
-            InterruptSpell(CURRENT_AUTOREPEAT_SPELL);
+        InterruptSpell(CURRENT_AUTOREPEAT_SPELL);
         m_AutoRepeatFirstCast = true;
         return;
     }
 
-    // apply delay (Auto Shot (spellID 75) not affected)
-    if (m_AutoRepeatFirstCast && getAttackTimer(RANGED_ATTACK) < 500 && m_currentSpells[CURRENT_AUTOREPEAT_SPELL]->m_spellInfo->Id != 75)
+    // Apply delay (Auto Shot (spellID 75) not affected)
+    if (m_AutoRepeatFirstCast && getAttackTimer(RANGED_ATTACK) < 500 && spellProto->Id != 75)
```
Comment (FrancescoBorzi) [inline src/server/game/Entities/Unit/Unit.cpp:3232]: same as above

File: src/server/game/Entities/Unit/Unit.cpp [hunk 4]
```diff
@@ -3213,36 +3213,44 @@ void Unit::_UpdateSpells(uint32 time)
...
     if (isAttackReady(RANGED_ATTACK))
     {
-        // Check if able to cast
-        if (m_currentSpells[CURRENT_AUTOREPEAT_SPELL]->CheckCast(true) != SPELL_CAST_OK)
+        SpellCastResult result = m_currentSpells[CURRENT_AUTOREPEAT_SPELL]->CheckCast(true);
+        if (result != SPELL_CAST_OK)
         {
-            InterruptSpell(CURRENT_AUTOREPEAT_SPELL);
+            if (spellProto->Id != 75)
+                InterruptSpell(CURRENT_AUTOREPEAT_SPELL);
```
Comment (FrancescoBorzi) [inline src/server/game/Entities/Unit/Unit.cpp:3244]: same as above

File: src/server/game/Entities/Unit/Unit.cpp (hunk 1 above)
Comment (Goatform) [reply src/server/game/Entities/Unit/Unit.cpp:3221]: That's scary looking but okay, if you guys prefer that code-style 👍

File: src/server/game/Entities/Unit/Unit.cpp (hunk 2 above)
Comment (Goatform) [reply src/server/game/Entities/Unit/Unit.cpp:3224]: Where do you want me to put it exactly? In this function or to move it to some other file?

File: src/server/game/Entities/Unit/Unit.cpp (hunk 1 above)
Comment (Goatform) [reply src/server/game/Entities/Unit/Unit.cpp:3221]: Oh and which approach?

```
    if (!spellProto) {
        return;
    }
```
OR
```
    if (!spellProto)
    {
        return;
    }
```

Comment (Helias) [reply src/server/game/Entities/Unit/Unit.cpp:3224]: this project uses the second one :wink:

File: src/server/game/Entities/Unit/Unit.cpp (hunk 2 above)
Comment (Goatform) [reply src/server/game/Entities/Unit/Unit.cpp:3228]: @FrancescoBorzi maybe something like this?

Screenshot_8

**Review by FrancescoBorzi — APPROVED** [review]

File: src/server/game/Entities/Unit/Unit.cpp [hunk 5]
```diff
@@ -3213,36 +3213,55 @@ void Unit::_UpdateSpells(uint32 time)
...
+    {
+        spellProto = m_currentSpells[CURRENT_AUTOREPEAT_SPELL]->m_spellInfo;
+    }
+
+    if (!spellProto)
+    {
+        return;
+    }
+    
+    static uint32 const HUNTER_AUTOSHOOT = 75;
```
Comment (Winfidonarleyan) [inline src/server/game/Entities/Unit/Unit.cpp:3227]: Why static?

Comment (FrancescoBorzi) [reply src/server/game/Entities/Unit/Unit.cpp:3227]: I guess it's because we don't need a different `HUNTER_AUTOSHOOT` per every unit?
