### PR TITLE
Fix(Core/DB/Ulduar): Assembly of Iron

### LINKED ISSUE #1612: [Ulduar] Runemaster Molgeim - Rune of Summoning [$10]
[Ulduar] Runemaster Molgeim - Rune of Summoning

##### SMALL DESCRIPTION:
Spell Rune of summoning of Runemaster Molgeim doesn't work on 25 raid Mode

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When Runemaster Molgeim is the last alive boss in the encounter , he should use the spell Rune of summoning in 10 and 25 players raid mode

##### CURRENT BEHAVIOUR:
Actually , Runemaster Molgeim use this ability only in 10 players mode and not in 25 players mode.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Move to Ulduar
2. Start Assembly of iron encounter and kill the 2 other boss : Steelbreaker and Stormcaller Brundir
3. When only Molgeim is alive , he use the Rune of summoning in 10 players mode but not in 25 players mode.

##### BRANCH(ES):

master

##### OPERATING SYSTEM: Debian 9

<bountysource-plugin>

---
There is a **[$10 open bounty](https://www.bountysource.com/issues/71802327-ulduar-runemaster-molgeim-rune-of-summoning?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Nefertumm**
##### CHANGES PROPOSED:

-  Remove hardcoded text.
-  Add creature_template_addon for rune of summoning entry (25 difficulty).
-  Remove rand()% and use urand instead.
-  Remove hardcoded summon, use the right spell for it. (Trinity tweeked) 
-  Added missing overrides. 

###### ISSUES ADDRESSED:

Closes #1612 

##### TESTS PERFORMED:

Compiled and tested.

##### HOW TO TEST THE CHANGES:

Go to Assembly of Iron and verify that all works as intended now.

##### Target branch(es):

Master

### CODE REVIEW

File: src/server/scripts/Northrend/Ulduar/Ulduar/boss_assembly_of_iron.cpp [hunk 1]
```diff
@@ -986,18 +916,24 @@ class spell_assembly_rune_of_summoning : public SpellScriptLoader
 
             void OnPeriodic(AuraEffect const* aurEff)
             {
-                if (Unit* caster = GetCaster())
-                    if (aurEff->GetTickNumber() % 2 == 0)
-                        caster->SummonCreature(CREATURE_LIGHTNING_ELEMENTAL, caster->GetPositionX(), caster->GetPositionY(), caster->GetPositionZ(), 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 2000);
+                PreventDefaultAction();
+                GetTarget()->CastSpell(GetTarget(), SPELL_RUNE_OF_SUMMONING_SUMMON, true, nullptr, aurEff, GetTarget()->IsSummon() ? GetTarget()->ToTempSummon()->GetSummonerGUID() : 0);
```
Comment (pklloveyou) [inline src/server/scripts/Northrend/Ulduar/Ulduar/boss_assembly_of_iron.cpp]: `if (aurEff->GetTickNumber() % 2 == 0)`

Comment (pklloveyou) [reply src/server/scripts/Northrend/Ulduar/Ulduar/boss_assembly_of_iron.cpp]: Add the “if (aurEff->GetTickNumber() % 2 == 0)”
Otherwise the frequency is too high

File: data/sql/updates/pending_db_world/rev_1553372596303652700.sql [hunk 2]
```diff
@@ -0,0 +1,4 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1553372596303652700');
+INSERT INTO `creature_template_addon` (`entry`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES
+(33691,0,0,0,0,0,'62019'); -- Rune of Summoning
```
Comment (FrancescoBorzi) [inline data/sql/updates/pending_db_world/rev_1553372596303652700.sql]: please always use `DELETE` before `INSERT` (even if this value is not present on a clean AC)

Comment (FrancescoBorzi) [reply data/sql/updates/pending_db_world/rev_1553372596303652700.sql]: I mean for the `creature_template_addon`, no need for the `version_db_world`

Comment (Nefertumm) [reply data/sql/updates/pending_db_world/rev_1553372596303652700.sql]: Lol, i thought about it and i forgot to add it.
