### PR TITLE
fix(Core/scripts): Blackwing Lair overhaul

### LINKED ISSUE #25: bwl boss bug
well done azerothcore team !  in blackwing lair the second boss bugged ! boss_vaelastrasz she should a dialog you could trigger a battle with she by click this dialog! kill the boss_vaelastrasz the second floor door open and you could enter into and go on next boss!

and the last boss also bug i use gm character and go to the last boss but the boss have no dialog to trigger the last battle ! not script

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/36287804-bwl-boss-bug?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #785: Core/Script: Razorgore the Untamed
**Description**: Currently there are a number of bugs with the Razorgore encounter, some are minor but others prevent the encounter from being winnable.

**Current behaviour**: 

- [ ] There should be a beam between the orb of domination and Razorgore all the times (at the moment it only shows when the orb is used).
- [ ] Grethok the Controller should be doing a channeling animation before he's engaged.
- [x] The eggs should not be clickable (at the moment they show as clickable but don't do anything).
- [x] Grethok the controller should shout "Intruders have breached the hatchery.." when engaged, not killed.
- [ ] When Grethok is engaged Razegore should start attacking the party.
- [ ] Engaging Grethok should close the entrance gate (at the moment you can click it to close but it doesn't close automatically).
- [ ] At the moment there are two exit gates. There should only be one and it should open when the encounter is over. One is usable by players (called Portcullis) the other is only usable by GM's (Doodad_BOSSGATE01). At the moment both are open before the fight start and close when Grethok is engaged.
- [ ] When you use the orb to control Razorgore you should get the Mind Exhaustion debuff. This actually looks to be a bug on the blizzard WotLK server, in vanilla the debuff is added when the channel ends, so you can't control him twice in a row.
- [ ] Using the orb should also be a channeled ability, it currently has no time limit, from the video it looks to be 90 seconds.
- [ ] Currently using the orb gives a QAE Charm buff (cog icon), the icon should probably be hidden, I think it's just used to set the player's animation?
- [ ] The destroy egg spell on Razorgore should destroy the closest egg in range. Currently it does nothing.
- [ ] Razorgore doesn't seem to take damage normally, he's also immune to .die. He heals to full each time you use the orb I think.
- [ ] The encounter doesn't reset if all party members leave the room/die.

Because I couldn't kill him I couldn't tell if he kills all engaged players if he dies during the egg phase and because the eggs couldn't be destroyed I couldn't test that he moves into phase 2 when they're all gone (a standard tank and spank).

Some id's and things in case it helps..
Creatures:
Grethok the Controller - 12557
Razegore the Untamed - 12435
Objects:
Orb of Domination - 177808
Black Dragon Egg - 177807
Spells:
Destroy Egg - 19873
Mind Exhaustion - 23958
QAE Charm - 42013 (I think)

**Expected behaviour**:
Here's a video I found of him being killed in WotLK - https://www.youtube.com/watch?v=vxSICGXkcjU

**Steps to reproduce the problem**:

1. Go to Black wing lair and fight Razegore.
2. 
3. 

**Branch(es)**: master 

**AC hash/commit**:  7bc6b57

**Operating system**: Windows 10

**Modules**:  None

**Other Customizations**: None

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/54690293-core-script-razorgore-the-untamed?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #3042: Blackwing Lair Issues [$45]
##### SMALL DESCRIPTION: 
A report on issues inside Blackwing Lair

**Razoregore the Untamed** (12435)
a) should destroy (19873) the eggs (177807) when mind controlled using the Orb of Domination (177808)
b) should aggro raid after last egg has been destroyed, using Fireball Volley (22425)
c) adds should have abilities, like the Blackwing Mage (12420) should cast Fireball (17290), and use Arcane Explosion (22271) if engaged by melee)

There's an existing issue for this boss from a year ago #785 . I think for now we should just enable the portcullis to remain open and bypass this boss until a proper fix is implemented.

**Vaelastrasz the Corrupt** (13020)
a) should have a dialogue with Nefarian upon entering his room. Maybe it's scripted already and didn't trigger because previous boss is bugged?
b) should cast Burning Adrenaline (18173) every 15 seconds (1 mana user, 1 mana user, MT; 1 mana user, 1 mana user, MT; etc.)

**Broodlord Lashlayer** (12017)
a) Suppression Room should have workable Suppression Devices (179784) casting Suppression Aura (22247) if not disarmed by rogues

**Firemaw** (11983)
a) should be patrolling from Alchemy room to stairs
b) Death Talon Overseers (12461) should also be patrolling back and forth
c) Shadowflame should apply a DoT (22682) if you're not wearing Onyxia Scale Cloak (15138)

**Ebonroc** (14601)
a) should be patrolling around the platform he's on
b) Shadowflame should apply a DoT (22682) if you're not wearing Onyxia Scale Cloak (15138)

**Flamegor** (11981)
a) should be patrolling around the platform he's on
b) Shadowflame should apply a DoT (22682) if you're not wearing Onyxia Scale Cloak (15138)

**Chromaggus** (14020)
a) the lever should open the portcullis, you shouldn't interact with the portcullis directly

**Nefarian**
a) Only in here by myself, so hard to test properly
b) Nefarian should be walking randomly amid the raid, rather than targeting the tank and running up to him (easy fix is to just have him follow a set path around the pillar)
c) Class calls should be benefiting Nefarian, not the player (paladins should not receive Improved Blessing of Protection (23415) on themselves, but onto Nefarian)
d) at 20% mobs should respawn as Bone Constructs (14605)
e) Shadowflame should apply a DoT (22682) if you're not wearing Onyxia Scale Cloak (15138)

##### BRANCH(ES):
I'm not sure what this means. I presume it's master? It's a vanilla raid.
master

##### AC HASH/COMMIT:
Not 100% sure what this means either. Most recent commit is from Kitzunu on Fri May 15 10:56:54 2020 commit f0cb99746642e8dc93f215d0742cbc362e611d04

##### OPERATING SYSTEM:
Windows 10 Pro

##### MODULES:
No other modules

##### OTHER CUSTOMIZATIONS:
No other customizations

<bountysource-plugin>

---
There is a **[$45 open bounty](https://www.bountysource.com/issues/91466608-blackwing-lair-issues?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by FALL1N1**
## CHANGES PROPOSED:

# Razoregore the Untamed (12435)
- [x] a) should destroy (19873) the eggs (177807) when mind controlled using the Orb of Domination (177808)
- [x] b) should aggro raid after last egg has been destroyed, using Fireball Volley (22425)
- [x] c) adds should have abilities, like the Blackwing Mage (12420) should cast Fireball (17290), and use Arcane Explosion (22271) if engaged by melee)
 - [x] (**NEW**) Should talk upon broken egg

# Vaelastrasz the Corrupt (13020)
- [x] a) should have a dialogue with Nefarian upon entering his room. Maybe it's scripted already and didn't trigger because previous boss is bugged?
- [x] b) should cast Burning Adrenaline (18173) every 15 seconds (1 mana user, 1 mana user, MT; 1 mana user, 1 mana user, MT; etc.)
(@FALL1N1: 15s cooldown for mana users, 45s for tanks, inf range)
 - [x] (**NEW**) Fixed tail swipe, so you should NOT stay behind the boss.
 - [x] (**NEW**) Backported Blackwing Technicians event

# Broodlord Lashlayer (12017)
- [x] a) Suppression Room should have workable Suppression Devices (179784) casting Suppression Aura (22247) if not disarmed by rogues

# Firemaw (11983)
- [x] a) should be patrolling from Alchemy room to stairs
- [x] b) Death Talon Overseers (12461) should also be patrolling back and forth
- [x] c) Shadowflame should apply a DoT (22682) if you're not wearing Onyxia Scale Cloak (15138)

# Ebonroc (14601)
- [x] a) should be patrolling around the platform he's on
- [x] b) Shadowflame should apply a DoT (22682) if you're not wearing Onyxia Scale Cloak (15138)

# Flamegor (11981)
- [x] a) should be patrolling around the platform he's on
- [x] b) Shadowflame should apply a DoT (22682) if you're not wearing Onyxia Scale Cloak (15138)
- [x] **NEW** Now the gate opens when he's killed.

# Chromaggus (14020)
- [x] a) the lever should open the portcullis, you shouldn't interact with the portcullis directly
- [x] **NEW** Clicking the lever will automatically pull/aggro the boss - as intended.

# Nefarian 
- [x] b) Nefarian should be walking randomly amid the raid, rather than targeting the tank and running up to him (easy fix is to just have him follow a set path around the pillar)
- [x] c) Class calls should be benefiting Nefarian, not the player (paladins should not receive Improved Blessing of Protection (23415) on themselves, but onto Nefarian)
- [x] d) at 20% mobs should respawn as Bone Constructs (14605)
- [x] e) Shadowflame should apply a DoT (22682) if you're not wearing Onyxia Scale Cloak (15138)

# Others
- [x] Door handling rewritten and removed old crappy/unused doors / gates.

## ISSUES ADDRESSED:
- Closes #3042
- Closes #785
- Closes #25
- probably more...

## TESTS PERFORMED:
- none

## HOW TO TEST THE CHANGES:
- grab a snack 'n drink and suit yourself

## KNOWN ISSUES AND TODO LIST:
- none that I know of

## Target branch(es):
- [x] Master

 
 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FALL1N1** [comment]
reserved

**Comment by FALL1N1** [comment]
please do not merge with master, I will merge it when it's ready..

**Comment by Gierlappen** [comment]
Awesome! Thx for that!

**Comment by FALL1N1** [comment]
Ooookay, so... I have cleaned up everything I saw, fixed everything that was reported, merged with master and here we are in testing phase.

Any voulenteers that'd like to test that shiet out? @cts17 maybe you can give us a hand?

File: data/sql/updates/db_world/0000_00_00_00.sql [hunk 1]
```diff
@@ -0,0 +1,303 @@
...
+
+-- scriptname for the bwl shadowflame
+SET @SHADOWFLAME_BWL = 22539;
+DELETE FROM `spell_script_names` WHERE `spell_id` = @SHADOWFLAME_BWL;
+INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (@SHADOWFLAME_BWL, 'spell_bwl_shadowflame');
+
+-- attaching lever script to gob
+UPDATE `gameobject_template` SET `ScriptName`='go_chromaggus_lever' WHERE  `entry`=179148;
+
+DELETE FROM `gameobject` WHERE `guid` IN(75160,75163,7228,7227,);
```
Comment (locus313) [inline data/sql/updates/db_world/0000_00_00_00.sql:294]: looks like this line is causing the db import to fail on the build tests.

Comment (FALL1N1) [reply data/sql/updates/db_world/0000_00_00_00.sql:294]: fuck me.. lol, thank you for the catch

**Comment by FALL1N1** [comment]
feel free to test without the conditions, Im done with this shit for today.. will read the conditions doc tomorrow

**Comment by FrancescoBorzi** [comment]
@FALL1N1 looks like the build is now passing, however we got 2 warnings from Codacy:

image

**Comment by FALL1N1** [comment]
ikr, it's still wip, @FrancescoBorzi, I still have to cleanup everything and reorder it

**Comment by JamesGent** [comment]
90% of my screenshots were sent to you directly in PMs on discord but here are my concluding thoughts;

in conclusion:

better than it was
working events and dialogues (one typo in aren't having a \ )
better mechanics for the onyxia cloaks
some nice patrolling units you did

although;
possible mob tagging issues where you'd hit 1 mob and 500 would clip through walls to come hunt you down, apparently this is a sunwellcore inherited issue
possible pathing issues where things you wanted to patrol dont patrol

https://cdn.discordapp.com/attachments/776855103222054972/776877618955026502/unknown.png

https://cdn.discordapp.com/attachments/776855103222054972/776876721570971679/unknown.png

https://cdn.discordapp.com/attachments/776855103222054972/776875800183439390/unknown.png

https://cdn.discordapp.com/attachments/776855103222054972/776874870302441482/unknown.png

https://cdn.discordapp.com/attachments/776855103222054972/776869568391151656/unknown.png

**Comment by FrancescoBorzi** [comment]
many thanks @JamesGent for your feedback. As long as this doesn't cause any regression, I'd be glad to merge this

**Comment by FALL1N1** [comment]
I'll remove the creature relation so the "blizzlike" fix do not pull half of the raid's trash until that core issue is found and fixed.. maybe we can add a custom label for that, e.g "Pending another fix" or something like that? @FrancescoBorzi 

With it only:
- the doors for Chromaggus
- typo in the texts from the sniffs for Vaelastrasz

those two has to be fixed (will be done later today) and it can be merged afterwards.

This PR covers everything in the mentioned issue together with some extra features/scritps that improve it.

**Comment by FrancescoBorzi** [comment]
@FALL1N1 we don't have such a label, WIP would be fine I guess. We can speed up the merge of the other PR once it's tested.

**Comment by FALL1N1** [comment]
Merged with master, if everything is green we are good to go.

File: data/sql/updates/db_world/0000_00_00_00.sql [hunk 2]
```diff
@@ -0,0 +1,325 @@
+
```
Comment (FrancescoBorzi) [inline data/sql/updates/db_world/0000_00_00_00.sql:1]: the SQL file should be moved, please read: https://www.azerothcore.org/wiki/Dealing-with-SQL-files#how-to-create-an-sql-update-file

Comment (FALL1N1) [reply data/sql/updates/db_world/0000_00_00_00.sql]: done as requested

File: data/sql/updates/pending_db_world/rev_1607274868483442300.sql [hunk 3]
```diff
@@ -0,0 +1,326 @@
...
+(84538, 85611, 0, 0, 3, 0, 0),
+(84538, 85616, 0, 0, 3, 0, 0),
+(84538, 85622, 0, 0, 3, 0, 0),
+(84538, 85612, 0, 0, 3, 0, 0),
+(84538, 85609, 0, 0, 3, 0, 0),
+(84538, 85620, 0, 0, 3, 0, 0),
+(84538, 85613, 0, 0, 3, 0, 0),
+(84538, 85621, 0, 0, 3, 0, 0),
+(84538, 85623, 0, 0, 3, 0, 0);
+*/
```
Comment (FrancescoBorzi) [inline data/sql/updates/pending_db_world/rev_1607274868483442300.sql:260]: shall we remove the commented code?

Comment (FALL1N1) [reply data/sql/updates/pending_db_world/rev_1607274868483442300.sql]: Removed, will open a new issue for it later, because it's unrelated to this PR/initial issue. It's global.

**Comment by FALL1N1** [comment]
hopefully I did not miss something, we will see in a couple of minutes after the build

**Comment by FALL1N1** [comment]
updated, merged and good to go

File: data/sql/updates/pending_db_world/rev_1607274868483442300.sql [hunk 4]
```diff
@@ -0,0 +1,146 @@
...
+DELETE FROM `spell_script_names` WHERE `spell_id` = @SHADOWFLAME_BWL;
+INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (@SHADOWFLAME_BWL, 'spell_bwl_shadowflame');
+
+-- attaching lever script to gob
+UPDATE `gameobject_template` SET `ScriptName`='go_chromaggus_lever' WHERE `entry` = 179148;
+DELETE FROM `gameobject` WHERE `guid` IN (75160, 75163, 7228, 7227);
+
+DELETE FROM `broadcast_text` WHERE `ID` = 100003;
+INSERT INTO `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) VALUES
+(100003, 0, 'Ah...the heroes. You are persistent, aren\'t you? Your ally here attempted to match his power against mine - and paid the price. Now he shall serve me...by slaughtering you. Get up little Red Wyrm, and destroy them!', 'Ah...the heroes. You are persistent, aren\'t you? Your ally here attempted to match his power against mine - and paid the price. Now he shall serve me...by slaughtering you. Get up little Red Wyrm, and destroy them!', 0, 0, 0, 0, 0, 0, 8279, 0, 0, 0);
```
Comment (Si1ker) [inline data/sql/updates/pending_db_world/rev_1607274868483442300.sql:146]:
```suggestion
(100003, 0, 'Ah...the heroes. You are persistent, aren\'t you? Your ally here attempted to match his power against mine - and paid the price. Now he shall serve me...by slaughtering you. Get up little Red Wyrm, and destroy them!', 'Ah...the heroes. You are persistent, aren\'t you? Your ally here attempted to match his power against mine - and paid the price. Now he shall serve me...by slaughtering you. Get up little Red Wyrm, and destroy them!', 0, 0, 0, 0, 0, 0, 8279, 0, 0, 0);


```

**Review by Si1ker — APPROVED** [review]

**Comment by Si1ker** [comment]
Based on the test done by @JamesGent :
"the portcullises can trap you in or out of the instance and dont work as you hoped :("

@FALL1N1 , already addressed?

**Comment by FALL1N1** [comment]
@Si1ker , those are blizzlike as stupid as it sounds, the players should not click them. Or maybe they should close once the encounter is in progress, sadly I have zero knowlege with this raid so any info/vid is welcome.

**Comment by FALL1N1** [comment]
merged with master, should also build fine (hopefully), will fix codestyle crap after

**Comment by FALL1N1** [comment]
@Kitzunu can you give it a look, anything missing or you'd like to see changed?

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers please have a look at this

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers @azerothcore/testers @Si1ker @LukasVolgger @mpfans @pklloveyou anyone?

please, we need to test this :)

**Comment by BarbzYHOOL** [comment]
@locus313 @JamesGent @Knindzagxg maybe you too would be down for it :P

**Comment by Knindzagxg** [comment]
Ill check once im home today

**Comment by Knindzagxg** [comment]
Looks good man.
Im happy that we finally have working Razorgore.

@FALL1N1  
When it comes to gates, they should be down once you start raid fight, which will lock inside specific "room" and wont be able to reset boss. Most of fights work like that, if there is a gate.

**Comment by BarbzYHOOL** [comment]
@Knindzagxg so you put your seal of approval on this? :) to be merged?

**Comment by Knindzagxg** [comment]
Yeah, everything seems fine and haven't found any issue on boss fights.

**Comment by BarbzYHOOL** [comment]
thank you fall1n and knindza!!

**Comment by Kitzunu** [comment]
Thanks for the work =)

**Comment by LannyE** [comment]
I just updated my core -> 3.0 -> latest master which includes this change.  This PR  Now I see this:
image


At first I thought it was the ValidateSpellInfo PR but @Kitzunu checked and didn't find any issues.  I wasn't getting this error before the update.  Is anyone else seeing this?

**Comment by locus313** [comment]
@LannyE when you look at your version_db_world table in your world database. what does it show in the third column?
 
image

**Comment by LannyE** [comment]
image
653 rows returned.

**Comment by locus313** [comment]
ok, could you open a new issue for this? I will check it in a little bit and confirm it on the new issue.

**Comment by FALL1N1** [comment]
@LannyE did any errors occur when you imported it?

**Comment by LannyE** [comment]
No.  Everything went fine.  This is the only issue I am having.

**Comment by locus313** [comment]
@FALL1N1 I just tested, I am seeing the same message:
```
2021-02-01 14:56:43 Loading Scripts...
2021-02-01 14:56:43 TSCR: Loading Script Waypoints for 72 creature(s)...
2021-02-01 14:56:43 >> Loaded 2656 Script Waypoint nodes in 14 ms
2021-02-01 14:56:43 >> Loaded 2694 C++ scripts in 68 ms
2021-02-01 14:56:43
2021-02-01 14:56:43 Validating spell scripts...
2021-02-01 14:56:43 ERROR: TSCR: Spell `22539` Effect `Index: EFFECT_0 Name: 77` of script `spell_bwl_shadowflame` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
2021-02-01 14:56:43 >> Validated 2240 scripts in 5 ms
```
There was no errors when doing the import:
```
[root@centos-wow-dev azerothcore-wotlk]# bash ./apps/db_assembler/db_assembler.sh
1) all: Assemble all
2) bases: Assemble only bases
3) updates: Assemble only updates
4) customs: Assemble only customs
5) import-all: Assemble & Import all
6) import-bases: Assemble & Import only bases
7) import-updates: Assemble & Import only updates
8) import-customs:  Assemble & Import only customs
9) quit: Exit from this menu
[Please enter your choice]: 7
=====     DB ASSEMBLER MENU     =====
===== STARTING ASSEMBLY PROCESS =====
Generating /usr/local/src/azerothcore-wotlk/env/dist/sql/auth_updates ...
Searching on /usr/local/src/azerothcore-wotlk/data/sql/updates/db_auth/ ...
Searching on /usr/local/src/azerothcore-wotlk/data/sql/updates/pending_db_auth/ ...
Generating /usr/local/src/azerothcore-wotlk/env/dist/sql/characters_updates ...
Searching on /usr/local/src/azerothcore-wotlk/data/sql/updates/db_characters/ ...
Searching on /usr/local/src/azerothcore-wotlk/data/sql/updates/pending_db_characters/ ...
Generating /usr/local/src/azerothcore-wotlk/env/dist/sql/world_updates ...
Searching on /usr/local/src/azerothcore-wotlk/data/sql/updates/db_world/ ...
Searching on /usr/local/src/azerothcore-wotlk/data/sql/updates/pending_db_world/ ...
=====           DONE            =====
=====       CHECKING DBs        =====
acore_auth database exists
acore_characters database exists
acore_world database exists
=====           DONE            =====
===== STARTING IMPORTING PROCESS =====
importing AUTH - updates ...
importing CHARACTERS - updates ...
importing WORLD - updates ...
=====           DONE            =====
1) --skip-column-names
2) bases: Assemble only bases
3) updates: Assemble only updates
4) customs: Assemble only customs
5) import-all: Assemble & Import all
6) import-bases: Assemble & Import only bases
7) import-updates: Assemble & Import only updates
8) import-customs:  Assemble & Import only customs
9) quit: Exit from this menu
[Please enter your choice]: 9
=====     DB ASSEMBLER MENU     =====
Goodbye!
```

**Comment by LannyE** [comment]
Created issue #4412

**Comment by FALL1N1** [comment]
Thank you, will push a fix tomorrow.
