### PR TITLE
fix(Core/Scripts): Fix multiple ICC encounter regressions after threat system port

### LINKED ISSUE #25296: [ICC] Problem with GunshipBattle
### Current Behaviour

Gunship battle: if you start firing your cannon before the battle begins, your friendly ship will explode at the beginning of the battle.

### Expected Behaviour

The friendly ship should not be destroyed when the battle starts.

### Source

_No response_

### Steps to reproduce the problem

1. Start the battle
2. Use a gun
3. You ship is dead

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. 0246faa95a39+ 2026-03-29 01:20:27 +0100 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu

### Custom changes or Modules

_No response_

### LINKED ISSUE #25297: [ICC] Problem with Svalna's sister - don't start battle
### Current Behaviour

Svalna's sister, the Valkyrie who appears before Valitria, does not start the battle; instead, she hovers in the air and cannot be attacked.

### Expected Behaviour

The Valkyrie (Svalna's sister) should start the battle

### Source

_No response_

### Steps to reproduce the problem

1. Go in frost way
2. Try to start combat with Svalna's sister

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/0246faa95a39ab92a294cf69fe7aecfeff1d77c2+ 2026-03-29 01:20:27 +0100 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu

### Custom changes or Modules

_No response_

### LINKED ISSUE #25298: [ICC] Valithria Dreamwalker disappears after a few seconds, when combat start.
### Current Behaviour

Valithria Dreamwalker disappears after a few seconds of combat, and the battle is considered lost, forcing you to start over.

### Expected Behaviour

The Valithria Dreamwalker should not disappear a few seconds after the battle starts.

### Source

_No response_

### Steps to reproduce the problem

1. Go in frost way
2. Try to start combat with Valithria Dreamwalker

### Extra Notes

_No response_

### AC rev. hash/commit

 AzerothCore rev. 0246faa95a39+ 2026-03-29 01:20:27 +0100 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu

### Custom changes or Modules

_No response_

### LINKED ISSUE #25299: [ICC] Lich King stop combat
### Current Behaviour

At the end of the battle, when the Lich King kills all the players according to the script, he simply returns to his throne as if the combat had been lost, and there is no resurrection.

### Expected Behaviour

Players should respawn and continue the battle with Lich King

### Source

_No response_

### Steps to reproduce the problem

1. Start combat with Lich King
2. Reach the death phase
3. Combat will stop

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/0246faa95a39ab92a294cf69fe7aecfeff1d77c2+ 2026-03-29 01:20:27 +0100 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by blinkysc**
## Changes Proposed:
This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

### AI-assisted Pull Requests

> [!IMPORTANT]
> While the use of AI tools when preparing pull requests is not prohibited, contributors must clearly disclose when such tools have been used and specify the model involved.
> 
> Contributors are also expected to fully understand the changes they are submitting and must be able to explain and justify those changes when requested by maintainers.

- [x] AI tools (e.g. ChatGPT, Claude, or similar) were used entirely or partially in preparing this pull request. Claude Code with azerothMCP were used to research TrinityCore reference implementations, diagnose root causes, and implement fixes.

## Issues Addressed:
- Closes #25296 — [ICC] Gunship Battle: friendly ship explodes when players are in cannons at battle start
- Closes #25297 — [ICC] Sister Svalna doesn't start battle, hovers in air
- Closes #25298 — [ICC] Valithria Dreamwalker disappears after a few seconds of combat
- Closes #25299 — [ICC] Lich King stops combat during outro RP phase

## Summary of Changes:

**Gunship Battle (#25296):** The wipe check in `npc_gunship::UpdateAI` excluded players in vehicles (cannons) from the "on deck" count. If all alive players were in cannons when the battle started, the wipe check fired immediately and killed the friendly ship. Fix: count all alive players regardless of vehicle state.

**Sister Svalna (#25297):** Two issues:
1. `FrostwingGauntletRespawner` called `SetRespawnTime()` after `DespawnOrUnsummon()`, so gauntlet trash never respawned after a wipe. Ported TC's pattern of setting `SetCorpseDelay(1)` / `SetRespawnDelay(2)` before despawn.
2. A global GM area trigger skip (commit 3da6e301) prevented GMs from triggering the frostwing gauntlet AT. Reverted the global skip since encounter ATs should fire for GMs.

**Valithria Dreamwalker (#25298):** The wipe check used `SetInCombatWithZone()` + threat list iteration. After the threat system port, the threat list stays empty for friendly NPCs (combat refs don't create threat entries for allies). Replaced with a direct `AnyPlayerInObjectRangeCheck` player proximity search, matching the pattern used elsewhere. TC has no such wipe check at all.

**Lich King (#25299):** When Fury of Frostmourne kills all players, the CombatManager clears combat refs and triggers `EnterEvadeMode()` through the combat system — bypassing the `PHASE_MASK_NO_VICTIM` check in `UpdateAI`. Fix: block `EnterEvadeMode` during `PHASE_OUTRO` and `PHASE_FROSTMOURNE`. Also disable health regen during outro to prevent LK healing to full.

## SOURCE:
The changes have been validated through:
- [x] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)

TrinityCore's `boss_sister_svalna.cpp` and `boss_valithria_dreamwalker.cpp` were used as reference for the respawner fix and wipe check patterns.

## Tests Performed:
This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [x] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [x] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

**Gunship Battle (#25296):**
1. Enter ICC, board a cannon before the gunship battle starts
2. Start the encounter
3. Verify the friendly ship does NOT explode

**Sister Svalna (#25297):**
1. Enter ICC, walk to the frostwing gauntlet area trigger (AT 5617)
2. Wait for Crok's 37s intro, let him walk through the gauntlet
3. Verify Svalna lands and becomes attackable after captains are resurrected

**Valithria Dreamwalker (#25298):**
1. Enter ICC, start the Valithria encounter
2. Verify she does NOT disappear/evade after a few seconds

**Lich King (#25299):**
1. Enter ICC, fight the Lich King
2. Get him below 10% HP to trigger Fury of Frostmourne
3. Verify he stays in place for the outro RP (does not walk back to throne)
4. Verify Tirion resurrects players and the fight continues

## Known Issues and TODO List:

### CODE REVIEW

File: src/server/game/Handlers/MiscHandler.cpp [hunk 1]
```diff
@@ -732,8 +732,7 @@ void WorldSession::HandleAreaTriggerOpcode(WorldPacket& recv_data)
     if (player->isDebugAreaTriggers)
         ChatHandler(this).PSendSysMessage(LANG_DEBUG_AREATRIGGER_REACHED, triggerId);
 
-    // Skip areatrigger scripts for GMs unless debug areatriggers is enabled
-    if ((!player->IsGameMaster() || player->isDebugAreaTriggers) && sScriptMgr->OnAreaTrigger(player, atEntry))
+    if (sScriptMgr->OnAreaTrigger(player, atEntry))
```
Comment (Nyeriah) [inline src/server/game/Handlers/MiscHandler.cpp]: 🤔

Comment (blinkysc) [reply src/server/game/Handlers/MiscHandler.cpp]: Oh crap debugging I need to set that back

**Comment by staf4d** [comment]
**First of all, I thank you immensely**
1. Gunship Battle - Fixed, works fine.
2. Sister Svalna - Not fixed.
3. Valithria Dreamwalker - It only works the second time.
4. Lich King - Fixed, works fine.

**Comment by blinkysc** [comment]
Tested Sister, and seems to work. Did you trigger all area triggers? Best to .debug areatrigger and .go trigger 5616

Now ill checkout Dream

**Comment by blinkysc** [comment]
image

dream seems to be working? I might be missing something that you tried?

**Comment by staf4d** [comment]
@blinkysc 
About sister: The trigger is triggered, and Crock and his team run through the hall, and then, after killing all the mobs, he says that reinforcements will arrive, and that's it. Nothing happens after that, and everyone just stands there.

**Comment by staf4d** [comment]
@blinkysc 
About Valithria Dreamwalker: The problem has changed. I didn't express myself correctly. If you start a battle, after a few seconds (about 10) it loses all hp and the battle ends with a loss, and then restarts.

**Comment by blinkysc** [comment]
> @blinkysc About sister: The trigger is triggered, and Crock and his team run through the hall, and then, after killing all the mobs, he says that reinforcements will arrive, and that's it. Nothing happens after that, and everyone just stands there.

Kk I'll keep iterating and see if I can get it. What about Dream?

**Comment by staf4d** [comment]
It turns out that the Dreamwalker needs to be cured twice, and only the second cure counts

**Comment by staf4d** [comment]
And about my sister. She's always standing in an unnatural position, not moving. It's like she's standing in the air. Maybe that will help.

**Comment by blinkysc** [comment]
> And about my sister. She's always standing in an unnatural position, not moving. It's like she's standing in the air. Maybe that will help.

This is a pre existing issue, not anything with threat system creates. At least as far as my memory servers this has been the case for quite awhile

**Comment by staf4d** [comment]
@blinkysc 
I understand, thank you. I will look for an earlier solution. This may be due to the fact that I manually updated the database from a rather old version. The automatic update did not work.

**Comment by blinkysc** [comment]
@staf4d Please when you get a chance give it another go

File: src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp [hunk 2]
```diff
@@ -691,7 +691,7 @@ class npc_gunship : public CreatureScript
             bool playerOnDeck = false;
             me->GetMap()->DoForAllPlayers([&](Player* player)
                 {
-                    if (!player->GetVehicle() && player->IsAlive())
```
Comment (Nyeriah) [inline src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp:694]: I'd look this up more carefully, there's something about being on the guns that I can't remember

Comment (Nyeriah) [reply src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp:694]: https://github.com/azerothcore/azerothcore-wotlk/pull/17856

Comment (blinkysc) [reply src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp:694]: Kk let me look at commit history for it. Maybe that will reveal

Comment (blinkysc) [reply src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp:694]: fixed! Thanks =D

**Review by Nyeriah — APPROVED** [review]

**Comment by staf4d** [comment]
@blinkysc
Just tested your new fixes! You're absolutely amazing! Thank you so much!
Sister Svalna is working as expected, everything works flawlessly!
Valithria Dreamwalker - it's improved, but still doesn't work as expected. I don't understand why, but after she's healed, an explosion occurs, all the mobs die, but she falls back to her starting position and lies there. The corruption isn't removed, but she lies there with full health, and she needs to be healed again to complete the challenge and for the chest to appear. Previously, she would fall back to her starting position with half her health.

**Comment by staf4d** [comment]
@blinkysc 
Sorry, a new BIG problem has arisen. After finishing the fight with Valitria, the gate won't open now. Even after healing her a second time. Neither the elevator nor the back gate. This has never happened before

**Comment by Ben19882** [comment]
Crok is twisting. See: https://github.com/azerothcore/azerothcore-wotlk/issues/25317
