### PR TITLE
fix(DB/quest_template): Fix Incorrect 'On Complete' Text

### LINKED ISSUE #8898: The Madness Within quest has incorrect POI
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2226

Upon completing quest [The Madness Within](https://classic.wowhead.com/quest=7461/the-madness-within) we are instructed to turn it in at the Shen'dralar Ancient. If we choose to show the map where to turn quest, we are clearly pointed to a spot in Dalaran Crater, at Alterac Mountains. Not only the marker is wrong, but even the description on it is obviously mistaken.

2021-11-01 at 10 03 25
2021-11-01 at 10 03 38

Tester:

The issue is confirmed. Quest [The Madness Within](https://wowgaming.altervista.org/aowow/?quest=7461) shows Alterac POI and also open Silverpine map on "Show Quest Map"

WoWScrnShot_110221_172707

### Expected Blizzlike Behaviour

1. As dungeons quest The Madness Within should open player's current map without any marks.
2. On complete quest tracker should send player back to Shen'dralar Ancient

### Source

Wowwiki [Quest:The Madness Within](https://wowwiki-archive.fandom.com/wiki/Quest:The_Madness_Within)
Wowhead [https://www.wowhead.com/quest=7461/the-madness-within](https://classic.wowhead.com/quest=7461/the-madness-within)

### Steps to reproduce the problem

.q a 7461
right click in objectives
show quets map

### Extra Notes

Due to https://github.com/chromiecraft/chromiecraft/issues/2226#issuecomment-956264565 this is need fix regardless of wowwiki [notes](https://wowwiki-archive.fandom.com/wiki/Quest:The_Madness_Within#Notes):
>The quest tracker incorrectly displays that the quest must be turned in the Dalaran Crater in Alterac Mountains.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### LINKED ISSUE #9248: Quest "Hameya's Plea" has incorrect on complete text
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2352

After looting [Hameya's Key] to complete the quest "Hameya's Plea" the quest tracker says that you have to go to The Hinterlands to finish the quest. Compare quest description in the quest log and the quest tracking text on the right hand side.
WoWScrnShot_111821_161429

Tester:

The issue is confirmed. Complete text of quest [Hameya's Plea](https://wowgaming.altervista.org/aowow/?quest=6024) pointing to Hinterlands while location is Eastern Plaguelands.

image

### Expected Blizzlike Behaviour

The quest tracker has to suggest that you have to return to The Undercroft in Eastern Plaguelands

### Source

It's blizzlike issue [wowhead](https://www.wowhead.com/quest=6024/hameyas-plea#comments)
> By 696294 on 2010/11/05 (Patch 4.0.1)
After Killing Hameya the quest log says to return to grave in HINTERLAND. it is not in hinterland look at your map, you will see the ? go back to the Mausoleum and go behind it (not down the stairs again).

> By 336631 on 2010/01/05 (Patch 3.3.0)
Apparently the new Quest Helper interface option is bugged on this quest. After having retrieved the key from Hameya, it told me to hand the quest in at the Mound of Dirt in The HINTERLANDS(although it did show the correct position on the map)

### Steps to reproduce the problem

.q a 6024
.q c 6024

### Extra Notes

Policy of blizzlike's bugs: https://github.com/chromiecraft/chromiecraft/issues/2226#issuecomment-956264565

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/00dc369cb627d728c520cd597b31e9edf2c75eed

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### LINKED ISSUE #9295: Various Talvash del Kissel's quests has incorrect on complete text.
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2373

For quest “lore for a price”, the quest tracker points players to “Talvash del Kissel” in “Wetlands”, while this male gnome is in the Mystic Ward in IronForge.

Tester:

The issue is confirmed. [Incoming Gumdrop](https://wowgaming.altervista.org/aowow/?quest=8355), [Lore for a Price](https://wowgaming.altervista.org/aowow/?quest=2199), [Restoring the Necklace](https://wowgaming.altervista.org/aowow/?quest=2204) are showing `Returnt to Talvash del Kissel in Wetlands`.

image

### Expected Blizzlike Behaviour

Should be something like in quest [Replacement Phial](https://wowgaming.altervista.org/aowow/?quest=3375) `at the Mystic Ward in Ironforge`.

### Source

_No response_

### Steps to reproduce the problem

.q a 8355
.q c 8355
.q a 2204
.q c 2204
.q a 2199
.q c 2199
checkout `on complete` text

### Extra Notes

Policy of blizzlike's bugs: https://github.com/chromiecraft/chromiecraft/issues/2226#issuecomment-956264565

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/00dc369cb627d728c520cd597b31e9edf2c75eed

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by Voxstrasza**
## Changes Proposed:
-  Correct blizzlike bugs in line with AC policy of fixing obvious blizzlike bugs
-  Update 'On Complete Text' in quest tracker
- Remove incorrect question mark on wrong map for quest completion for dungeon quest

## Issues Addressed:
- Closes #9248
- Closes #9295
- Closes #8898
- Closes chromiecraft/chromiecraft#2373
- Closes chromiecraft/chromiecraft#2226
- Closes chromiecraft/chromiecraft#2352

## Tests Performed:

[After SQL](https://i.imgur.com/3pIfQuh.jpg)

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1638933646064544700.sql [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+UPDATE `quest_template` SET `QuestCompletionLog`='Return to Mound of Dirt in The Eastern Plaguelands' WHERE  `ID`=6024;
+UPDATE `quest_template` SET `QuestCompletionLog`='Return to Talvash del Kissel at the Mystic Ward in Ironforge.' WHERE  `ID`=2199;
+UPDATE `quest_template` SET `QuestCompletionLog`='Return to Talvash del Kissel at the Mystic Ward in Ironforge.' WHERE  `ID`=2204;
+UPDATE `quest_template` SET `QuestCompletionLog`='Return to Talvash del Kissel at the Mystic Ward in Ironforge.' WHERE  `ID`=8355;
+UPDATE `quest_template` SET `QuestCompletionLog`='Return to Shen\'dralar Ancient in Dire Maul.' WHERE  `ID`=7461;
+
+/* Remove quest completion question mark off of map
+*/
+
+UPDATE `quest_poi` SET `ObjectiveIndex`='0' WHERE  `QuestID`=7461 AND `id`=2;
```
Comment (IntelligentQuantum) [inline data/sql/updates/pending_db_world/rev_1638933646064544700.sql:15]:
```suggestion
UPDATE `quest_poi` SET `ObjectiveIndex`=0 WHERE  `QuestID`=7461 AND `id`=2;
```

**Review by IntelligentQuantum — CHANGES_REQUESTED** [review]

**Review by IntelligentQuantum — APPROVED** [review]
