### PR TITLE
fix(Scripts/BT) Fix Gurtogg will not use acidic wound in phase 2

### LINKED ISSUE #21204: [Black Temple] Boss: Gurtogg Bloodboil shouldn't apply Acidic Wound in Phase 2
Issue linked from CC: https://github.com/chromiecraft/chromiecraft/issues/7674

Triage Notes: Nothing to add

Original Post Below: 

---

### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Gurtogg Bloodboil applies [Acidic Wound](https://www.wowhead.com/tbc/spell=40481/acidic-wound) in P2 on his [Fel Rage](https://www.wowhead.com/tbc/spell=40604/fel-rage) target

### Expected Blizzlike Behaviour

Should not use it in P2

### Source

- https://www.wowhead.com/tbc/guide/gurtogg-bloodboil-black-temple-bt-strategy-burning-crusade-classic#phase-2
- https://www.icy-veins.com/tbc-classic/gurtogg-bloodboil-guide-strategy-abilities-loot#gurtogg-bloodboil-abilities
- https://classic.warcraftlogs.com/reports/4apG1ckZPdTKD6Hq?translate=true&fight=19&view=events&type=auras&spells=debuffs&ability=40481 -> 0:56.447 > 1:27.885 no one got the debuff
- https://www.youtube.com/watch?v=ix4cumglQmE&t=96s
- https://www.youtube.com/watch?v=PxVL1XQCHEM
- https://www.youtube.com/watch?v=GB4IDJ5Wc28&t=157s

### Steps to reproduce the problem

1. Be the target on Gurtogg's Fel Rage

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5f020de5466e3894914fe424229c4b9f3d138b2f

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by blinkysc**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #21204

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Use bots or other players so no reset during  bewildering strikes
2. .go c id 22948
3. Wait for fel rage and observe no acid wound
4. After fel rage acid wound should be used again

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Ive explained the issue in detail here: https://github.com/azerothcore/azerothcore-wotlk/pull/21208#issuecomment-2600388549

I am not certain how giving him the aura again would be able to address this issue

**Comment by blinkysc** [comment]
> Ive explained the issue in detail here: [#21208 (comment)](https://github.com/azerothcore/azerothcore-wotlk/pull/21208#issuecomment-2600388549)
> 
> I am not certain how giving him the aura again would be able to address this issue

Honestly not sure why that's the case as well, I took this from the original script and applied it to when fel rage happens with 28s timer (based on fel rage instead of checking if any player has it). I have tested and works but I'll keep looking for a more appropriately named function

image

**Comment by blinkysc** [comment]
So apparently DoCastVictim() works the same here ¯\_(ツ)_/¯, I changed the old line of code as well.

**Comment by Nyeriah** [comment]
> So apparently DoCastVictim() works the same here ¯\_(ツ)_/¯, I changed the old line of code as well. Also tested again

Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = I
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)

40484 has TARGET_UNIT_CASTER as target so it has only one valid target, himself. So DoCastSelf() is the appropriate choice here

**Comment by blinkysc** [comment]
> > So apparently DoCastVictim() works the same here ¯_(ツ)_/¯, I changed the old line of code as well. Also tested again
> 
> Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA) BasePoints = I Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
> 
> 40484 has TARGET_UNIT_CASTER as target so it has only one valid target, himself. So DoCastSelf() is the appropriate choice here

DoCastSelf() back

**Comment by amed80** [comment]
Gurtogg still uses acidic wound in phase 2.

**Comment by blinkysc** [comment]
> Gurtogg still uses acidic wound in phase 2.

Tried another 2 times, but I don't ever see Gurtogg apply acidic wound while fel rage. Do you see the same behavior before or any difference?

**Comment by Nyeriah** [comment]
Do you have uncommited changes by any chance?

**Comment by amed80** [comment]
> > Gurtogg still uses acidic wound in phase 2.
> 
> Tried another 2 times, but I don't ever see Gurtogg apply acidic wound while fel rage. Do you see the same behavior before or any difference?

tested again
i see same behavior before and after the PR

<details>

image

</details>

AzerothCore rev. a13c2ff55f53+ 2025-01-23 17:30:31 +0000 (master branch) (Win64, RelWithDebInfo, Static)

No modules are enabled

**Comment by blinkysc** [comment]
> > > Gurtogg still uses acidic wound in phase 2.
> > 
> > 
> > Tried another 2 times, but I don't ever see Gurtogg apply acidic wound while fel rage. Do you see the same behavior before or any difference?
> 
> tested again i see same behavior before and after the PR
> 
> AzerothCore rev. [a13c2ff](https://github.com/azerothcore/azerothcore-wotlk/commit/a13c2ff55f530901838744eef0999942a7a6bde9)+ 2025-01-23 17:30:31 +0000 (master branch) (Win64, RelWithDebInfo, Static)
> 
> No modules are enabled

The acidic wound should stay on the players just not new applications of them right? Do you see new applications during fel rage?

**Comment by blinkysc** [comment]
> > > Gurtogg still uses acidic wound in phase 2.
> > 
> > 
> > Tried another 2 times, but I don't ever see Gurtogg apply acidic wound while fel rage. Do you see the same behavior before or any difference?
> 
> tested again i see same behavior before and after the PR
> 
> AzerothCore rev. [a13c2ff](https://github.com/azerothcore/azerothcore-wotlk/commit/a13c2ff55f530901838744eef0999942a7a6bde9)+ 2025-01-23 17:30:31 +0000 (master branch) (Win64, RelWithDebInfo, Static)
> 
> No modules are enabled

You'll have to checkout the PR before testing

https://graphite.dev/guides/git-checkout-pr

**Comment by Nyeriah** [comment]
Remove the aura at start of p2

**Comment by blinkysc** [comment]
> Remove the aura at start of p2

Acidic Wound shouldn't be removed from players if I'm not mistaken just that new applications should not be applied?
https://www.youtube.com/watch?v=yPaj1Wpd6cE -> around 1:33 you can see player still has debuff with fel rage

**Comment by Nyeriah** [comment]
yes... I mean.. from the boss..

**Comment by amed80** [comment]
> You'll have to checkout the PR before testing, unless of course you just copy pasta?
> 
> https://graphite.dev/guides/git-checkout-pr

usually do it manually but tried again

AzerothCore rev. dffb89bbede1 2025-01-23 20:57:24 -0600 (pr-21253 branch) (Win64, RelWithDebInfo, Static)

<details>

https://github.com/user-attachments/assets/8f0729f3-0d2f-496f-8311-18d4cf01f673

</details>

**Comment by blinkysc** [comment]
> yes... I mean.. from the boss..

Boss never has the Aura, that was the confusion with DoCastSelf() even though its an offensive ability (from Gurtogg's perspective)

**Comment by blinkysc** [comment]
> > You'll have to checkout the PR before testing, unless of course you just copy pasta?
> > https://graphite.dev/guides/git-checkout-pr
> 
> usually do it manually but tried again
> 
> AzerothCore rev. [dffb89b](https://github.com/azerothcore/azerothcore-wotlk/commit/dffb89bbede1d18c8592d217863a70ff02c32926) 2025-01-23 20:57:24 -0600 (pr-21253 branch) (Win64, RelWithDebInfo, Static)
> Acidic.mp4

Oh I see, maybe weird timing issue. Maybe what I can do is something like 100-300ms before fel rage he stops acidic wound and maybe 100ms after?

**Comment by amed80** [comment]
it keeps applying for the whole phase 2
image

**Comment by blinkysc** [comment]
> it keeps applying for the whole phase 2 image

Mind trying again with this commit?

**Comment by Nyeriah** [comment]
Gurtogg casts the aura (SPELL_ACIDIC_WOUND) on himself on pull, the aura then triggers the application as long as he has the aura. 

image

image

**Comment by blinkysc** [comment]
https://studio.youtube.com/video/KMdWe9CWn7s/edit

Might take a sec for youtube to make hd

**Comment by blinkysc** [comment]
> Gurtogg casts the aura (SPELL_ACIDIC_WOUND) on himself on pull, the aura then triggers the application as long as he has the aura.
> 
> image
> 
> image

I see ok let me fix that

File: src/server/scripts/Outland/BlackTemple/boss_bloodboil.cpp [hunk 1]
```diff
@@ -103,6 +102,7 @@ struct boss_gurtogg_bloodboil : public BossAI
             if (Unit* target = SelectTarget(SelectTargetMethod::Random, 1, 40.0f, true))
             {
                 me->RemoveAurasByType(SPELL_AURA_MOD_TAUNT);
+                me->RemoveAura(SPELL_ACIDIC_WOUND);
```
Comment (Nyeriah) [inline src/server/scripts/Outland/BlackTemple/boss_bloodboil.cpp:105]:
```suggestion
                me->RemoveAuraDueToSpell(SPELL_ACIDIC_WOUND);
```

File: src/server/scripts/Outland/BlackTemple/boss_bloodboil.cpp [hunk 2]
```diff
@@ -80,7 +79,7 @@ struct boss_gurtogg_bloodboil : public BossAI
         BossAI::JustEngagedWith(who);
         Talk(SAY_AGGRO);
 
-        DoCastSelf(SPELL_ACIDIC_WOUND, true);
+        DoCastVictim(SPELL_ACIDIC_WOUND, true);
```
Comment (Nyeriah) [inline src/server/scripts/Outland/BlackTemple/boss_bloodboil.cpp:82]:
```suggestion
        DoCastSelf(SPELL_ACIDIC_WOUND, true);
```

File: src/server/scripts/Outland/BlackTemple/boss_bloodboil.cpp [hunk 3]
```diff
@@ -118,6 +118,10 @@ struct boss_gurtogg_bloodboil : public BossAI
                     DoCastVictim(SPELL_CHARGE);
                 }, 2s);
 
+                me->m_Events.AddEventAtOffset([&] {
+                    DoCastVictim(SPELL_ACIDIC_WOUND, true);
```
Comment (Nyeriah) [inline src/server/scripts/Outland/BlackTemple/boss_bloodboil.cpp:122]:
```suggestion
                    DoCastSelf(SPELL_ACIDIC_WOUND, true);
```

File: src/server/scripts/Outland/BlackTemple/boss_bloodboil.cpp (hunk 1 above)
Comment (blinkysc) [reply src/server/scripts/Outland/BlackTemple/boss_bloodboil.cpp:105]: Yeah was scratching my head too because line 88 has me->RemoveAura(SPELL_ACIDIC_WOUND);

**Comment by EricksOliveira** [comment]
This problem is quite intriguing. I haven't had time to fix my commit, but I believe the best way to fix this problem is to create phases on the boss. I'll be looking into this tomorrow, when I'm less busy at work.

**Comment by blinkysc** [comment]
image

I've tried and tried but from what I see acid wound isn't happening to players in Phase 2 with latest commit

**Comment by blinkysc** [comment]
@amed80 if you woundn't mind trying again when you have a chance

**Comment by amed80** [comment]
Yes , tested 3 Fel Rage phases.
He doesn't apply it during p2 and he applies it again after going back to p1.

**Review by Nyeriah — APPROVED** [review]

**Comment by EricksOliveira** [comment]
Strange. I tested it and it didn't turn out as expected.

**Comment by amed80** [comment]
Just tested it after this got merged, it seems fine to me?

AzerothCore rev. d297030a086e 2025-01-25 19:06:21 -0300 (master branch) (Win64, RelWithDebInfo, Static)

<details>

https://github.com/user-attachments/assets/a2145920-9324-431c-b1d7-e62cdfa57f79

</details>
