### PR TITLE
fix(Core/Raid): Reworked Archimonde fight

### LINKED ISSUE #896: Mount Hyjal: Archimonde Unkillable (without cheating)
**Description**:
Archimonde is casting Hand of Death in phase 2 (after 10% hp), wiping the raid.

**Current behaviour**: Tell us what happens
At the moment Archimonde (id 17968) can not be killed normally. At 10% he casts Protection of Elune (38528) correctly on the raid but also enrages, spam casting Hand of Death (35354) on the raid. The damage from this goes through the protection and wipes the raid before the wisps can kill him.

**Expected behaviour**: Tell us what should happen instead
He should start casting Finger of Death (31984) which looks flashy but doesn't get through the protection. 60 seconds after he enters phase 2 the wisps kill him.

What seems to be happening is that he's enraging at the start of phase 2 (which causes the Hand of Death). Commenting out that "Enraged = true;" makes him killable, though ideally he should be casting Finger of Death instead.

boss_archimonde.cpp - Line 545
```
            if (BelowTenPercent)
            {
                if (!HasProtected)
                {
                    me->GetMotionMaster()->Clear(false);
                    me->GetMotionMaster()->MoveIdle();

                    //all members of raid must get this buff
                    DoCastVictim(SPELL_PROTECTION_OF_ELUNE, true);
                    HasProtected = true;
                    Enraged = true;
                }
```

**Steps to reproduce the problem**:

1. Engage Archimonde (I'm afraid I don't know a way to get him to turn visible without doing all the waves in the rest of the dungeon).
2. Get him to 10% and see Protection of Elune is on.
3. Die to Hand of Death

**Branch(es)**: master

**AC hash/commit**:  825a62b

**Operating system**:  Windows 10

**Modules**:  VAS Autobalance

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/59009785-mount-hyjal-archimonde-unkillable-without-cheating?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Pondaveia**
##### CHANGES PROPOSED:

Fixed Archimonde enraging when party enters phase 2 (When they get Elune buff).
Had to open up a new PR due to my database and core being not up to date.

[Old PR](https://github.com/azerothcore/azerothcore-wotlk/pull/1036)

###### ISSUES ADDRESSED:

Closes 
#896 

##### TESTS PERFORMED:

Compiles without errors and tested on Windows.

##### HOW TO TEST THE CHANGES:

1 - .tele hyjal
2 - Complete the raid. I know I'm sorry...

For people who don't know you go through the first left entrace, complete Jaina event, then Thrall's and then go kill Archimonde. I suggest binding a kill command into your 1 and using tab to shift nps...

##### KNOWN ISSUES AND TODO LIST:

- [x] Must be reworked, swapping old diff timers for events.
- [x] Hand of death and Finger of death red color spell effect working (Being Immune to the dmg is nullifying the spell effect)
- [x] Changing his AI to BossAI and fixing Travis

##### Target branch(es):

Master

### CODE REVIEW

**Comment by Nefertumm** [comment]
Add `SpellScript.h`. Please, add overrides for the methods :D

File: data/sql/updates/pending_db_world/rev_1554524766481187700.sql [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+INSERT INTO `spell_script_names` VALUES
+(32111, 'spell_red_sky_effect');
+
+DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_finger_of_death';
+INSERT INTO `spell_script_names` VALUES
+(31984, 'spell_finger_of_death');
+
+DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_hand_of_death';
+INSERT INTO `spell_script_names` VALUES
+(35354, 'spell_hand_of_death');
```
Comment (FrancescoBorzi) [inline data/sql/updates/pending_db_world/rev_1554524766481187700.sql]: please use [compact SQL code](http://www.azerothcore.org/wiki/Dealing-with-SQL-files#write-compact-code)

File: data/sql/updates/pending_db_world/rev_1554524766481187700.sql [hunk 2]
```diff
@@ -0,0 +1,8 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1554524766481187700');
+
+DELETE FROM `spell_script_names` WHERE `entry` IN ('spell_red_sky_effect', 'spell_finger_of_death', 'spell_hand_of_death');
```
Comment (Nefertumm) [inline data/sql/updates/pending_db_world/rev_1554524766481187700.sql]:
```suggestion
DELETE FROM `spell_script_names` WHERE `spell_id` IN ('spell_red_sky_effect', 'spell_finger_of_death', 'spell_hand_of_death');
```

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp [hunk 3]
```diff
@@ -4,65 +4,87 @@
...
-    SPELL_DOOMFIRE_SPAWN        = 32074,
-    SPELL_DOOMFIRE              = 31945,
-    SPELL_SOUL_CHARGE_YELLOW    = 32045,
-    SPELL_SOUL_CHARGE_GREEN     = 32051,
-    SPELL_SOUL_CHARGE_RED       = 32052,
-    SPELL_UNLEASH_SOUL_YELLOW   = 32054,
-    SPELL_UNLEASH_SOUL_GREEN    = 32057,
-    SPELL_UNLEASH_SOUL_RED      = 32053,
-    SPELL_FEAR                  = 31970,
+    SPELL_DENOUEMENT_WISP = 32124,
```
[the remark this answers is not in the document]
Comment (Pondaveia) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp]: You're right, my dumb ass forgot to update this...

**Comment by comix1988** [comment]
I tested this pr but once brought the boss to 10% of hp dies alone without the whisps arrive. @Pondaveia

**Comment by Pondaveia** [comment]
strange, I need to check what's going on.

**Comment by Pondaveia** [comment]
@comix1988 if you have time give it a try again 👍

**Comment by Pondaveia** [comment]
@comix1988 I added a modification so you don't need to do the whole raid to attack Archimonde. He will look blinking but you just gotta aggro. When he is working I'll remove the lines. Also I had been testing and I the only issue I saw was when he respawn, the wisps are already there and the counter was more than 30 wisps thus triggering the event when he dies.

**Comment by comix1988** [comment]
now it works correctly. https://www.youtube.com/watch?v=tO9FJ0pxtr0

good job @Pondaveia 

remember to delete the lines

**Comment by Pondaveia** [comment]
Wohoo, Thanks @comix1988 🚀

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp [hunk 4]
```diff
@@ -461,170 +538,229 @@ class boss_archimonde : public CreatureScript
...
+                    }
+                    events.ScheduleEvent(EVENT_SPELL_FINGER_OF_DEATH, 3500);
+                    break;
+                case EVENT_SPELL_GRIP_OF_THE_LEGION:
+                    DoCast(SelectTarget(SELECT_TARGET_RANDOM, 0), SPELL_GRIP_OF_THE_LEGION);
+                    events.ScheduleEvent(EVENT_SPELL_GRIP_OF_THE_LEGION, urand(5000, 25000));
+                    break;
+                case EVENT_SPELL_AIR_BURST:
+                    Talk(SAY_AIR_BURST);
+                    DoCast(SelectTarget(SELECT_TARGET_RANDOM, 1), SPELL_AIR_BURST); // Not on tank
```
Comment (Deku) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp]: It can be casted on tank 

> At a point in our first attempt, the tank was Air Bursted while no one else was near the boss, causing us quite a silly wipe.

https://www.wowhead.com/npc=17968/archimonde#comments:id=1114086

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp [hunk 5]
```diff
@@ -4,19 +4,20 @@
...
+ /* ScriptData
+ SDName: Boss_Archimonde
+ SD%Complete: 85
+ SDComment: Doomfires not completely offlike due to core limitations for random moving. Tyrande and second phase not fully implemented.
+ SDCategory: Caverns of Time, Mount Hyjal
+ EndScriptData */
 
 #include "ScriptMgr.h"
 #include "ScriptedCreature.h"
 #include "hyjal.h"
```
Comment (Pondaveia) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp]: You mean combine them?

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp [hunk 6]
```diff
@@ -336,41 +387,54 @@ class boss_archimonde : public CreatureScript
...
-                if (!me->IsWithinDistInMap(target, me->GetAggroRange(target)))
-                    return true;                                // Cast Finger of Death
-                else                                            // This target is closest, he is our new tank
-                    me->AddThreat(target, me->getThreatManager().getThreat(me->GetVictim()));
-            }
+                ThreatContainer::StorageType::const_iterator itr = threatlist.begin();
+                for (; itr != threatlist.end(); ++itr)
+                {
+                    Unit* unit = ObjectAccessor::GetUnit(*me, (*itr)->getUnitGuid());
+                    if (unit && unit->IsAlive() && unit->IsCharmedOwnedByPlayerOrPlayer())
```
Comment (Pondaveia) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp]: ```IsWithinDistInMap()``` checks for targets in meele range?

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp [hunk 7]
```diff
@@ -336,41 +387,54 @@ class boss_archimonde : public CreatureScript
...
+                    return false;
+
+                targets.sort(Trinity::ObjectDistanceOrderPred(me));
+                Unit* target = targets.front();
+                if (target)
+                {
+                    if (!me->IsWithinDistInMap(target, me->GetAggroRange(target)))
+                        return true;                                // Cast Finger of Death
+                    else                                            // This target is closest, he is our new tank
+                        me->AddThreat(target, me->getThreatManager().getThreat(me->GetVictim()));
```
Comment (Pondaveia) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp]: Should I remove the else?

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp (hunk 5 above)
Comment (Deku) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp]: Yes, I think they could be combined. But if you want to keep that out of scope, just resolve this item. Totally up to you :smile:

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp (hunk 6 above)
Comment (Deku) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp]: Derp, it was `IsWithinMeleeRange()`

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp (hunk 5 above)
Comment (Pondaveia) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp]: An issue for another time! 🙂

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp (hunk 7 above)
Comment (Deku) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp]: Yes, the `AddThreat()` line at least. If you do the above review, you could easily just remove this whole closure.

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp (hunk 5 above)
Comment (Deku) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp]: I know is not part of your PR, but could you rename or reorganize these files please?
`hyjal.h`
`hyjal_trash.h`

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp (hunk 6 above)
Comment (Deku) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp]: You could add the `IsWithinDistInMap()` check here, then later if `targets` is empty (no targets in melee) return true to cast *Finger of Death*. This way you could avoid an extra iteration.

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp (hunk 7 above)
Comment (Deku) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp]: If this method is just to check if Archimonde *can cast Finger of Death* you shouldn't be handling the threat list here.

**Comment by Pondaveia** [comment]
summoning @comix1988 to re-test if possible 🙏

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp [hunk 8]
```diff
@@ -237,55 +261,77 @@ class boss_archimonde : public CreatureScript
...
         uint8 WispCount;
-        uint32 EnrageTimer;
-        uint32 CheckDistanceTimer;
 
         bool Enraged;
         bool BelowTenPercent;
         bool HasProtected;
         bool IsChanneling;
 
+        std::list<Unit*> targets;
```
Comment (Deku) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp]: Why is this list scoped at class level? It could introduce bugs since it's being used by different functions for different events (and is not being cleared).

**Comment by Pondaveia** [comment]
@FrancescoBorzi Can you approve or request changes please?

**Comment by Maurowin** [comment]
Normaly, wipers shall arrive all around Archimonde

Official Retail video:
https://www.youtube.com/watch?v=AlhqW4RG_0M

**Comment by Pondaveia** [comment]
@Maurowin I'm having issues mimicking this behavior. I think it could be another issue to look at. The boss is currently broken and needs to be merged as soon as @FrancescoBorzi approves it or @poszer

**Comment by FrancescoBorzi** [comment]
Sorry for being late, but I've been travelling
