### PR TITLE
fix(Scripts/HOR): Fix leader walking during escape

### LINKED ISSUE #13080: Halls of Reflection Sylvanas & lich king movement so fast !
### Current Behaviour

porblem for dungeons halls of reflection lastt boss the lich king
really problem is movement the lich king
He starts by moving very fast and damaged to Sylvanas
https://files.fm/f/mm5j97nvw 
watch this video and you understand

### Expected Blizzlike Behaviour

Wrath of the Lich King is actually a gauntlet event where you must escape from the Lich King himself. It serves as the third boss encounter in the Halls of Reflection. It is tied to the achievement 
We're Not Retreating; We're Advancing in a Different Direction
just like video
https://www.youtube.com/watch?v=QonHbWafJ5Q
time started 9:05 finished 9:25

### Source

https://www.wowhead.com/wotlk/npc=36954/the-lich-king

### Steps to reproduce the problem

Start Sylvanas
You notice that the Lich King is moving very fast and is hurting Sylvanas

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/d5f839a4be933f944c0df46c233066e37966c263

### Operating system

windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by Traesh**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [X] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #13080

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [X] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Tele into Halls of Reflection
2. You can skip the first scene by opening the door & killing the general in GM on
3. Start the escape, see that Sylvanas or Jaina is running

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Rorschach91** [comment]
Is this the issue? https://github.com/azerothcore/azerothcore-wotlk/issues/13080

File: src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.cpp [hunk 1]
```diff
@@ -1950,14 +1950,14 @@ class npc_hor_leader_second : public CreatureScript
...
-        void DoAction(int32 actionId) override
 
+        void DoAction(int32 actionId) override
         {
             switch (actionId)
             {
                 case ACTION_START_INTRO:
                     events.ScheduleEvent(EVENT_LK_SAY_AGGRO, 0ms);
-                    events.ScheduleEvent(EVENT_LK_BATTLE_1, 2s +500ms);
+                    events.ScheduleEvent(EVENT_LK_BATTLE_1, 2s, 500ms);
```
Comment (Nyeriah) [inline src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.cpp]: this line looks wrong, upper end of urand is higher than lower end, crash possible

Comment (Traesh) [reply src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.cpp]: My bad indeed, typo here, I fixed it
