### PR TITLE
fix(Core/Spells): Fix Lock and Load procs

### LINKED ISSUE #9055: Hunter Explosive Trap VS Lock and Load
### Current Behaviour

Explosive Trap dont triggered Lock and Load on boss and trash

### Expected Behaviour

Explosive Trap triggered Lock and Load on boss and trash

### Source

wow offy

### Steps to reproduce the problem

use Explosive Trap on boss and Lock and Load dont triggered

### Extra Notes

_No response_

### Customizations

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/686aafd57be6f1594a99634bade3756643fbf6f3

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-chromiecraft-smartstone](https://github.com/chromiecraft/mod-chromiecraft-smartstone)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-evade-logging](https://github.com/heyitsbench/mod-evade-logging)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-quests](https://github.com/azerothcore/mod-pvp-quests)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by blinkysc**
## Changes Proposed:
This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

### AI-assisted Pull Requests

> [!IMPORTANT]
> While the use of AI tools when preparing pull requests is not prohibited, contributors must clearly disclose when such tools have been used and specify the model involved.
> 
> Contributors are also expected to fully understand the changes they are submitting and must be able to explain and justify those changes when requested by maintainers.

- [x] AI tools (e.g. ChatGPT, Claude, or similar) were used entirely or partially in preparing this pull request. **Claude Code with azerothMCP** was used.

## Issues Addressed:
- Progress https://github.com/chromiecraft/chromiecraft/issues/9053
- Ref https://github.com/chromiecraft/chromiecraft/issues/9054
- Closes https://github.com/chromiecraft/chromiecraft/issues/9055

## SOURCE:
The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick).

## Description

**SpellPhaseMask fix (SQL):** `spell_proc` for Lock and Load had `SpellPhaseMask=4` (`PROC_SPELL_PHASE_FINISH`), which only allowed trap activation procs. Periodic damage ticks from Black Arrow and Explosive Trap fire with `PROC_SPELL_PHASE_HIT` (2) and were blocked. Changed to `SpellPhaseMask=6` (HIT | FINISH).

**Boss immunity check (C++/Core):** Frost Trap should not proc Lock and Load on targets immune to its snare (e.g. bosses with `mechanic_immune_mask` including `MECHANIC_SNARE`). The proc target is null for persistent area aura spells at `PROC_SPELL_PHASE_FINISH` because the explicit unit target is stripped by `Spell::InitExplicitTargets`. Added `Spell::GetOriginalTarget()` which preserves the original unit target GUID before it is stripped, allowing the Lock and Load script to check immunity.

**Scope of SpellFamilyMask:** Verified that only the intended spells match the proc mask `[0x18, 0x8000000, 0x24000]`:
- Frost Trap Aura (13810) via Mask0 bit 4
- Explosive Trap Effect (49065) via Mask2 bit 14
- Black Arrow (3674) via Mask1 bit 27
- Immolation Trap Effect (51740) does **not** match

## Tests Performed:
This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Create a hunter with Lock and Load talent (rank 3, Survival tree)
2. `.npc add temp 9938` (Magmus — boss, snare immune) and `.npc add temp 26829` (Frenzied Worgen — no immunities)
3. Test Frost Trap on both: should proc LnL on Worgen (100% at rank 3, 22s ICD), should NOT proc on Magmus
4. Test Explosive Trap periodic damage: should proc LnL from ticks
5. Test Black Arrow periodic damage: should proc LnL from ticks

## Known Issues and TODO List:

### CODE REVIEW

**Comment by blinkysc** [comment]
hilariously this is the monstrosity Claude suggested to begin with...
image

**Review by Gultask — APPROVED** [review]

File: src/server/scripts/Spells/spell_hunter.cpp [hunk 1]
```diff
@@ -1193,10 +1195,17 @@ class spell_hun_lock_and_load : public AuraScript
...
+        // Do not proc on traps for immolation/explosive trap
         SpellInfo const* spellInfo = eventInfo.GetSpellInfo();
-        if (!spellInfo || !(spellInfo->GetSchoolMask() & (SPELL_SCHOOL_MASK_FROST | SPELL_SCHOOL_MASK_FIRE)))
+        if (!spellInfo || !(spellInfo->GetSchoolMask() & SPELL_SCHOOL_MASK_FROST))
             return false;
 
+        // Do not proc on targets immune to Frost Trap slow (bosses)
+        if (Spell const* procSpell = eventInfo.GetProcSpell())
+            if (Unit* target = procSpell->GetOriginalTarget())
+                if (target->IsImmunedToSpell(sSpellMgr->GetSpellInfo(SPELL_FROST_TRAP_SLOW)))
```
Comment (Nyeriah) [inline src/server/scripts/Spells/spell_hunter.cpp]: I think this is backwards, it should still proc if the target is immune

Comment (Gultask) [reply src/server/scripts/Spells/spell_hunter.cpp]: I can only confirm that this is correct for MoP and Cata where Frost Trap and Freezing Trap would only proc if if the effect was successful. So we would look out for fights where there were slowable adds to use it on and get a proc

Comment (blinkysc) [reply src/server/scripts/Spells/spell_hunter.cpp]: .npc add temp 9938 worked with it, let me test some more real quick

Comment (blinkysc) [reply src/server/scripts/Spells/spell_hunter.cpp]: Tested with these too and didn't proc:

Herod .npc add temp 3975
Ironaya .npc add temp 7228
High Inquisitor Whitemane .npc add temp 3977 
Onyxia .npc add temp 10184
Grobbulus .npc add temp 15931
Maexxna    .npc add temp 15952

Comment (Nyeriah) [reply src/server/scripts/Spells/spell_hunter.cpp]: Well the original report I closed a couple of years back was about it not procing if the target was immune, and checking that was the old code behaviour. So I'm not sure

Comment (blinkysc) [reply src/server/scripts/Spells/spell_hunter.cpp]: I commented it out for more research so just the other important parts remain.

Comment (Nyeriah) [reply src/server/scripts/Spells/spell_hunter.cpp]: I had a brain fart, sorry, this was the issue I closed https://github.com/azerothcore/azerothcore-wotlk/issues/8011
It is in agreement with the changes here
