### PR TITLE
fix(Core/Spells): Far Sight auras are supposed to extend view distance and…

### LINKED ISSUE #5793: Ornate Spyglass Not Extending Resource Tracking Distance
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/607

Engineering Item: Ornate Spyglass is supposed to extend view distance and show mobs and players at a further distance, and gathering nodes at a further distance on the minimap when used

Tester's notes: tried this by running to away from a resource node until it just barely disappeared, then looking at it with the Spyglass. The node did not reappear on the minimap.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Ornate Spyglass is supposed to extend view distance and show mobs and players at a further distance, and gathering nodes at a further distance on the minimap when used.

**SOURCE:**

One example of it loading players at a longer view distance https://youtu.be/TJnCIeWIBrc?t=70

"Out of battlegrounds, it does load in extra players and objects."

"very useful item, extends the range of all tracking abilities. so zoom out you mini map to max range, use the spyglass and all nodes herbs and what not show up."

"Your track abilities/professions will see FURTHER on minimap, i use this all the time to see inside mines without ever going close, just look in direction and clicky, you can track things about twice as far as normal, in direction you are facing."

"I find it extremely useful for mining. If you zoom in with it, you can look for minerals much better. Under normal circumstances, you can only "see" minerals near you. When you use the spyglass, you field of vision increases, and you can detect minearals much further away." (all from https://classicdb.ch/?item=5507#comments)

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Find a gather node,,, 
2.  Run away from it until it disappears from your minimap
3.  Look in it's direction with the Spyglass
4. It should appear on the minimap. It does not because its broken.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98393252-ornate-spyglass-not-extending-resource-tracking-distance?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
… allows seeing objects from further distance.

Fixed #5793.

## Changes Proposed:
-  Added serverside implementation of SPELL_AURA_FAR_SGITH spells.

## Issues Addressed:

- Closes #5793
- Closes https://github.com/chromiecraft/chromiecraft/issues/607

## Tests Performed:

- Tested ingame with Ornate Spyglass.

## How to Test the Changes:

More info: #5793.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/game/Spells/Auras/SpellAuraEffects.cpp [hunk 1]
```diff
@@ -5476,6 +5476,35 @@ void AuraEffect::HandleBindSight(AuraApplication const* aurApp, uint8 mode, bool
...
+    if (!caster || caster->GetTypeId() != TYPEID_PLAYER)
+        return;
+
+    if (apply)
+    {
+        float radius = m_spellInfo->GetMaxRange();
+        int32 duration = m_spellInfo->GetDuration();
+
+        DynamicObject* dynObj = new DynamicObject(true);
+        Position pos = caster->GetFirstCollisionPosition(radius, 0.f);
```
Comment (pklloveyou) [inline src/server/game/Spells/Auras/SpellAuraEffects.cpp:5494]:
```
        Position pos;
        caster->GetFirstCollisionPosition(pos, radius, caster->GetOrientation());
```
Is that right?

Comment (UltraNix) [reply src/server/game/Spells/Auras/SpellAuraEffects.cpp:5494]: No. 0.f means forward.

**Comment by FrancescoBorzi** [comment]
build fails

**Comment by pklloveyou** [comment]
Tested

**Comment by robbie018** [comment]
<h2>Before fix</h2>
When you used Ornate Spyglass (5507) you could look in the distance but the minimap isn't updating the resource nodes.

https://user-images.githubusercontent.com/65018032/126826481-0861f736-cf9c-4235-9b3b-d6ee47ab946e.mp4

<h2>After first fix</h2>
So you can see the resource nodes appear on the minimap when you use the Ornate Spyglass. But it looks like the arrow of you character is jumping forward on the minimap. Also when you move left or right you don't see the cursor rotate to right or left on the minimap.

https://user-images.githubusercontent.com/65018032/126826882-3d3b1372-f5b9-4a31-823d-3f3328823aeb.mp4

<h2>What to change</h2>
The cursor in the minimap needs to stay where it is.
when you rotate you need to see the cursor in the minimap rotate to.
Also when you start walking the effect will disappear. In the reference video's you can see that this isn't the case.


<h2>Reference</h2>
https://youtu.be/faePasAfu6E?t=21
https://youtu.be/TJnCIeWIBrc?t=70

**Comment by UltraNix** [comment]
```
Also when you start walking the effect will disappear.
```
It's a channel so any movement will interrupt it. You can see it in the second video.

**Comment by robbie018** [comment]
> ```
> Also when you start walking the effect will disappear.
> ```
> 
> It's a channel so any movement will interrupt it. You can see it in the second video.

Ah yea I see, thanks! I will edit my post :)

**Comment by UltraNix** [comment]
As I understand I have to look at the specific direction to see an object?

**Comment by robbie018** [comment]
Yea it looks like you can also look in the distance to the direction your looking at :P (if you look at the minimap)

**Comment by UltraNix** [comment]
@robbie018 Test it again.

**Comment by pklloveyou** [comment]
Now you can turn the angle of view and look far at the same time

**Comment by robbie018** [comment]
<h1>After second fix</h1>
The pointer on the minimap isn't jumping forward when you use the item. Also you can rotate and you see the cursor also rotating. You can also see the resource nodes appear only in front of you, just like the reference video's.

https://user-images.githubusercontent.com/65018032/126881418-dbf312f5-0635-44e2-9db4-495990521f80.mp4



<h1>Conclusion</h1>
It works perfect like the referance video's.
Ready to push to the master branch :)

File: src/server/game/Spells/Auras/SpellAuraEffects.cpp [hunk 2]
```diff
@@ -5476,6 +5476,32 @@ void AuraEffect::HandleBindSight(AuraApplication const* aurApp, uint8 mode, bool
...
+    }
+
+    Unit* caster = GetCaster();
+    if (!caster || caster->GetTypeId() != TYPEID_PLAYER)
+    {
+        return;
+    }
+
+    Player* player = caster->ToPlayer();
+    if (apply)
```
Comment (Helias) [inline src/server/game/Spells/Auras/SpellAuraEffects.cpp:5493]: if player can be null I would suggest adding a null check, what do you think?

Comment (UltraNix) [reply src/server/game/Spells/Auras/SpellAuraEffects.cpp:5493]: No, it can't be.
```
if (!caster || caster->GetTypeId() != TYPEID_PLAYER)
    {
        return;
    }
 ````

**Review by FrancescoBorzi — APPROVED** [review]
