### PR TITLE
fix(DB/spell): Feral Spells are not gated at trainers

### LINKED ISSUE #1666: [Druid] Feral Spells are not gated at trainers
SMALL DESCRIPTION:

Feral spells (Bear and Cat form) can be learned without obtaining the required forms. You should be able to only learn those spells if you have the associated form.

Can be seen here: https://youtu.be/DYTHaE2XyJ4?t=343 (you can see he is lvl 10 but no Demo Roar present, while on the server right now you can learn that spell at lvl 10 even tho you don't have Bear Form.)

In this video: https://youtu.be/XPCmIWXUQmY?t=303 you can see when he goes to learn Demo Roar, under the spell name it says: Requires: Level 10, Bear Form(Shapeshift). It's in white letters cause he just obtained Bear Form but if he didn't have it, the letters would be red and he would not be able to learn that spell.

Bear Spells:
-Demoralizing Roar spell=99
-Enrage - spell=5229
-Bash - spell=5211
-Swipe(Bear)  spell=779
-Challenging Roar  spell=5209
-Frenzied Regeneration =22842
-Savage Defense - spell=62600
-Lacerate - spell=33745

Cat Spells:
-Claw  spell=1082
-Prowl  spell=5215
-Rip  spell=1079
-Shred  spell=5221
-Rake  spell=1822
-Pounce  spell=9005
-Feline Grace spell=20719
-Tiger's Fury spell=5217
-Dash - spell=1850
-Cower spell=8998
-Ferocious Bite spell=22568
-Ravage spell=6785
-Track Humanoids spell=5225
-Maim spell=22570
-Swipe(Cat)  spell=62078
-Savage Roar spell=52610

EXTRA NOTES:

BRANCH(ES):
master

AC HASH/COMMIT:
AzerothCore rev. 0f174eff0142+ 2019-03-30 15:44:35 +0000 (master branch) (Win64, Release)

OPERATING SYSTEM:
Win10

MODULES:
transmog

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/72241584-druid-feral-spells-are-not-gated-at-trainers?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by dillyns**
## Changes Proposed:
-  Made feral spells require their respective forms in order to train.

## Issues Addressed:

- Closes #1666

## Tests Performed:

- Created a druid and levelled it to 80 via `.levelup`
- Went to a druid trainer to ensure I could not train any feral abilities without first learning bear or cat form.

## How to Test the Changes:

1.  Create a druid and level it to 80 via `.levelup`
2. Go to a druid trainer (https://wowgaming.altervista.org/aowow/?npc=12042)
3. Feral spells should be unavailable to learn until you train their required shapeshift forms.

## Known Issues and TODO List:

- [Feral Faerie Fire could not be included because it requires Bear OR Cat form, which the spell_required db does not support]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1622610877406607900.sql [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+SET @FEROCIOUS_BITE = 22568;
+SET @RAVAGE = 6785;
+SET @TRACK_HUMANOIDS = 5225;
+SET @POUNCE = 9005;
+SET @FELINE_GRACE = 20719;
+SET @MAIM = 22570;
+SET @SWIPE_CAT = 62078;
+SET @SAVAGE_ROAR = 52610;
+
+INSERT INTO `spell_required` VALUES
```
Comment (FrancescoBorzi) [inline data/sql/updates/pending_db_world/rev_1622610877406607900.sql:31]: thanks for your contribution, please use `DELETE` before `INSERT`

see https://www.azerothcore.org/wiki/sql-standards

Comment (dillyns) [reply data/sql/updates/pending_db_world/rev_1622610877406607900.sql:39]: Fixed it. Should follow SQL standards now.

**Review by Helias — APPROVED** [review]

**Comment by Helias** [comment]
LGTM;
