### PR TITLE
fix(Core/Item): Meta gems sometimes ignore added sockets

### LINKED ISSUE #3598: Gems in [Eternal Belt Bucket] socket not counting towards meta gem requirements.
##### CURRENT BEHAVIOUR:
While the prerequesites show as fulfilled for a meta gem, the gems in a prismatic slot, which was created by an [Eternal Belt Buckle](https://wowgaming.altervista.org/aowow/?item=41611), still do not count towards the activation. Tested with Austere [Earthsiege Diamond](https://wowgaming.altervista.org/aowow/?item=41380).

##### EXPECTED BLIZZLIKE BEHAVIOUR:
All gems in all slots should count towards the activation for real, instead of only showing as fulfilling the requirement but not providing the meta gems stats.

##### STEPS TO REPRODUCE THE PROBLEM:
1.) Create a paladin, make it level 80, teach it plate and have it wear [Thane's Tainted Greathelm](https://wowgaming.altervista.org/aowow/?item=39395). Attach an [Austere Earthsiege Diamond](https://wowgaming.altervista.org/aowow/?item=41380)
.level 80
.learn 750
.additem 39395
.additem 41380

2.) Wear another item with 2 sockets to cover one part of the Meta gems requirements, like [Chestguard of the Exhausted](https://wowgaming.altervista.org/aowow/?item=40279) and fill it with 2 blue gems like [Lustrous Chalcedony](https://wowgaming.altervista.org/aowow/?item=39927)
.additem 40279
.additem 39927 2

3.) Wear a Belt like [Ancient Aligned Girdle](https://wowgaming.altervista.org/aowow/?item=37241) and attach an [Eternal belt Buckle](https://wowgaming.altervista.org/aowow/?item=41611) creating a Prismatic Socket.
.additem 37241
.additem 41611

4.) Check the Meta gems requirements with only the above items equipped which should be unfulfilled. Also remember the armor value and stamina value. Then attach a gem like [Regal Twilight Opal](https://wowgaming.altervista.org/aowow/?item=40031), which counts as a red one to the belt. 
.additem 40031

5.) Again look at the Meta gems requirements. They show up as fulfilled. Also look at the armor and stamina. Even though the meta shows as activated, the bonusses do not apply.

##### EXTRA NOTES:
A blacksmiths "Socket Bracer" / "Socket Gloves" prismatic sockets are not affected by this.

##### AC HASH/COMMIT:
c208a1219b54fa52501d86446a4a30edb51d0d2d
from June 3rd

##### OPERATING SYSTEM:
OS: Ubuntu Server 20.04

##### MODULES:
none

##### OTHER CUSTOMIZATIONS:
No customizations at all

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/93554097-gems-in-eternal-belt-bucket-socket-not-counting-towards-meta-gem-requirements?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by placemolle**
Fix #3598

For optimization's sake, the code handling meta gems only consider items with sockets.
However, the check is incomplete and only look at built-in sockets and not those added by upgrades.
Therefore, added sockets are considered by meta gems only in the event that the item already had a built-in socket.

## CHANGES PROPOSED:
-  Add a method on `Entities.Item` that checks if the item has sockets

## ISSUES ADDRESSED:
- Closes #3598

## TESTS PERFORMED:
- Tested in-game on a Windows server

## HOW TO TEST THE CHANGES:

1. Create a Human Paladin
2. `.level 79`
3. Learn plate `.learn 750`
3. Socket `.additem [Austere Earthsiege Diamond]`  
   into `.additem 39395`
4. Socket `.additem [Lustrous Chalcedony] 2`  
   into `.additem [Chestguard of the Exhausted]`
5. Apply `.additem [Eternal Belt Buckle]`  
  to `.additem [Ancient Aligned Girdle]`  
  and socket `.additem [Regal Twilight Opal]`
6. Wear the helm, chest, and belt.  
   You now have 540 stamina vs. 508 before this patch.

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

File: src/server/game/Entities/Item/Item.cpp [hunk 1]
```diff
@@ -962,6 +962,17 @@ bool Item::GemsFitSockets() const
     return true;
 }
 
+bool Item::HasAnySocket() const
```
Comment (Kitzunu) [inline src/server/game/Entities/Item/Item.cpp:965]: Personally I'd name it HasSocket
Why I don't know, just feel like the "any" is kinda useless :D

Comment (Winfidonarleyan) [reply src/server/game/Entities/Item/Item.cpp:965]: I agree with @Kitzunu

Comment (Si1ker) [reply src/server/game/Entities/Item/Item.cpp:965]: Agree 🐱 
IsAlive();
IsPet();
HasAura();
IsHeroic();
etc etc etc.. already on core.

File: src/server/game/Entities/Item/Item.cpp [hunk 2]
```diff
@@ -962,6 +962,17 @@ bool Item::GemsFitSockets() const
...
+{
+    return
+        // Built-in sockets.
+        this->GetTemplate()->Socket[0].Color
+
+        // Socket from upgrade.
+        // There can only be one socket added, and it's always in slot `PRISMATIC_ENCHANTMENT_SLOT`.
+        || this->GetEnchantmentId(EnchantmentSlot(PRISMATIC_ENCHANTMENT_SLOT));
```
Comment (Kitzunu) [inline src/server/game/Entities/Item/Item.cpp:973]: Also this I'd rather see the code altogether and the comments above instead of dragging the comments and code onto 6 lines.
Something like this
```cpp
// There can only be one socket added, and it's always in slot `PRISMATIC_ENCHANTMENT_SLOT`.
// Built-in sockets                      Socket from upgrade          
this->GetTemplate()->Socket[0].Color || this->GetEnchantmentId(EnchantmentSlot(PRISMATIC_ENCHANTMENT_SLOT));

**Review by zqgmzq — APPROVED** [review]
this pr fixed issue

**Comment by Voxstrasza** [comment]
good fix! thanks

**Comment by BarbzYHOOL** [comment]
nice!

Is it mandatory to hardcode force the check on first slot etc? in case someone makes client edits (no idea what i'm talking about), it could be adaptative already, no? (if too much work, then it's overkill)

File: src/server/game/Entities/Item/Item.cpp [hunk 3]
```diff
@@ -962,6 +962,13 @@ bool Item::GemsFitSockets() const
     return true;
 }
 
+bool Item::HasSocket() const
+{
+    // There can only be one socket added, and it's always in slot `PRISMATIC_ENCHANTMENT_SLOT`.
+    //     Built-in sockets                        Socket from upgrade
+    return this->GetTemplate()->Socket[0].Color || this->GetEnchantmentId(EnchantmentSlot(PRISMATIC_ENCHANTMENT_SLOT));
```
Comment (FrancescoBorzi) [inline src/server/game/Entities/Item/Item.cpp:969]: shouldn't we check that `Socket[0]` is not null before accessing `.Color` ?

**Comment by 55Honey** [comment]
Thanks for the fix! That was quick :-)

File: src/server/game/Entities/Item/Item.cpp (hunk 3 above)
Comment (placemolle) [reply src/server/game/Entities/Item/Item.cpp:969]: - `GetTemplate()` Can't be null, an item always have a template
- `->Socket` Can't be null, every template is created with 3 socket
- `Socket[0].Color` Can't dereference `nullptr` because `Socket[0]` is a value, not a pointer

**Comment by placemolle** [comment]
> Is it mandatory to hardcode force the check on first slot etc? in case someone makes client edits (no idea what i'm talking about), it could be adaptative already, no? (if too much work, then it's overkill)

It checks the item's template's first socket's color. This is server-side static data. The only reason I see where it would be relevant is if someone adds a new item (in table `item_template`), and sets column `socketColor_[2|3]` without setting `socketColor_1`.

**Review by Si1ker — APPROVED** [review]

**Comment by BarbzYHOOL** [comment]
ty for this, feel free to join our discord
