### PR TITLE
fix(Core/Movement): Teleport pet when pathfinding returns PATHFIND_NOT_USING_PATH

### LINKED ISSUE #23493: [Core] Orbs of Translocation don't include pets
### Current Behaviour

When you use orbs of translocation the pet will not teleport directly with you

### Expected Behaviour

Pet should teleport with you

### Source

https://youtu.be/4tof9x0Zqr0?t=7494 at ~2:05:21 the hunter takes the orb and the pet is teleported with him

### Steps to reproduce the problem

1. Create horde hunter
2. .levelup 9
3. .learn 1515
4. .npc add 3100 and tame
5. .go xyz 9336.16 -7883.44 74.9095 530
6. use orb and observe pet doesn't xfer with you

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. 675135e19bf7+ 2025-10-31 11:09:38 -0300 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Debian 13

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by blinkysc**
## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/23493

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. same as issue
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Not sure if this is right, would be cool if sources could be provided

**Comment by blinkysc** [comment]
https://youtu.be/4tof9x0Zqr0?t=7494 at ~2:05:21 the hunter takes the orb and the pet is teleported with him. Added this to source in issue

**Comment by sogladev** [comment]
> https://youtu.be/4tof9x0Zqr0?t=7494 at ~2:05:21 the hunter takes the orb and the pet is teleported with him. Added this to source in issue

You propose changes on map change, but the issue and source are for same map teleports where the flag you mention is already handled here: 

https://github.com/azerothcore/azerothcore-wotlk/blob/639ee028fd44d35b1993baee95d6d124af9fd9a0/src/server/game/Entities/Player/Player.cpp#L1471

When testing on AC, the pet climbs through the air from (see picture) to the player. My understanding is that the pet is not teleported by the orb, but rather if the pathfinding returns 'invalid' the pet is teleported near the player. This is more of a movement generator issue, maybe FollowMovementGenerator


frame and next frame of source video:
pet

**Comment by EricksOliveira** [comment]
From what I've tested, the problem still persists.

**Comment by blinkysc** [comment]
> When testing on AC, the pet climbs through the air from (see picture) to the player. My understanding is that the pet is not teleported by the orb, but rather if the pathfinding returns 'invalid' the pet is teleported near the player. This is more of a movement generator issue, maybe FollowMovementGenerator

Yeah you're right... Here is some debug logging I created. Can see that it always has pathSuccess and this is wrong...

```Pet 3100 following master: pathSuccess=true, pathType=1, forceDest=true, distance=2.77
  Pet at (9332.91, -7873.98, 74.08), pathing to (9335.37, -7877.90, 74.91)
Pet 3100 following master: pathSuccess=true, pathType=17, forceDest=true, distance=88.27 <-- Teleport
  Pet at (9335.37, -7877.90, 74.91), pathing to (9333.32, -7809.88, 136.57)
Pet 3100 following master: pathSuccess=true, pathType=17, forceDest=true, distance=66.01
  Pet at (9317.23, -7821.00, 70.09), pathing to (9326.17, -7811.03, 137.00)
Pet 3100 following master: pathSuccess=true, pathType=17, forceDest=true, distance=65.12
  Pet at (9317.34, -7820.87, 70.93), pathing to (9325.83, -7811.84, 137.00)
Pet 3100 following master: pathSuccess=true, pathType=17, forceDest=true, distance=64.89
  Pet at (9317.37, -7820.84, 71.15), pathing to (9327.31, -7809.15, 137.00)
Pet 3100 following master: pathSuccess=true, pathType=17, forceDest=true, distance=64.76
  Pet at (9317.39, -7820.82, 71.28), pathing to (9330.38, -7810.51, 136.57)
Pet 3100 following master: pathSuccess=true, pathType=17, forceDest=true, distance=64.36
  Pet at (9317.47, -7820.76, 71.70), pathing to (9330.30, -7810.31, 136.66)
Pet 3100 following master: pathSuccess=true, pathType=17, forceDest=true, distance=63.61
  Pet at (9317.64, -7820.62, 72.54), pathing to (9330.18, -7809.92, 136.85)
Pet 3100 following master: pathSuccess=true, pathType=17, forceDest=true, distance=63.10
  Pet at (9317.78, -7820.51, 73.23), pathing to (9329.99, -7809.59, 137.00)
Pet 3100 following master: pathSuccess=true, pathType=17, forceDest=true, distance=62.90
  Pet at (9317.83, -7820.46, 73.51), pathing to (9329.83, -7809.50, 137.00)
Pet 3100 following master: pathSuccess=true, pathType=17, forceDest=true, distance=61.30
  Pet at (9318.14, -7820.17, 75.17), pathing to (9329.18, -7808.95, 137.00)
Pet 3100 following master: pathSuccess=true, pathType=17, forceDest=true, distance=59.18
  Pet at (9318.50, -7819.80, 77.19), pathing to (9331.19, -7810.34, 136.57)
Pet 3100 following master: pathSuccess=true, pathType=17, forceDest=true, distance=56.66
  Pet at (9319.02, -7819.42, 79.63), pathing to (9325.29, -7807.86, 137.00)
Pet 3100 following master: pathSuccess=true, pathType=17, forceDest=true, distance=56.27
  Pet at (9319.06, -7819.34, 79.98), pathing to (9327.99, -7808.63, 137.00)
Pet 3100 following master: pathSuccess=true, pathType=17, forceDest=true, distance=48.57
  Pet at (9320.22, -7817.95, 87.40), pathing to (9331.81, -7808.18, 137.00)
Pet 3100 following master: pathSuccess=true, pathType=17, forceDest=true, distance=47.91
  Pet at (9320.39, -7817.81, 88.10), pathing to (9331.72, -7807.00, 137.00)
Pet 3100 following master: pathSuccess=true, pathType=17, forceDest=true, distance=47.74
  Pet at (9320.43, -7817.77, 88.28), pathing to (9331.34, -7806.15, 137.00)
Pet 3100 following master: pathSuccess=true, pathType=17, forceDest=true, distance=46.75
  Pet at (9320.66, -7817.53, 89.30), pathing to (9327.55, -7805.62, 137.00)
Pet 3100 following master: pathSuccess=true, pathType=17, forceDest=true, distance=44.76
  Pet at (9321.54, -7816.00, 90.93), pathing to (9330.42, -7804.97, 137.00)
Pet 3100 following master: pathSuccess=true, pathType=17, forceDest=true, distance=41.43
  Pet at (9322.25, -7815.12, 94.62), pathing to (9330.41, -7804.98, 137.00```

**Comment by blinkysc** [comment]
@sogladev I think this is likely a far better solution based on your insights. Also I'd imagine this might fix buggy pets when path "invalid".

**Comment by EricksOliveira** [comment]
I tested it and it seems good to me. The pet's teleportation is working correctly.

File: src/server/game/AI/CoreAI/PetAI.cpp [hunk 1]
```diff
@@ -158,6 +158,15 @@ void PetAI::UpdateAI(uint32 diff)
     else
         m_updateAlliesTimer -= diff;
 
+    if (owner && owner->IsPlayer() && !me->GetVictim() && me->CanNotReachTarget())
+    {
+        if (me->GetDistance(owner) > 20.0f)
```
Comment (sogladev) [inline src/server/game/AI/CoreAI/PetAI.cpp]: The distance threshold seems low. Now, when running around, the pet can be teleported even when I expect the pet to catch up. 

The picture shows the distance from the TP object after TP'ing
distance_tp

Comment (blinkysc) [reply src/server/game/AI/CoreAI/PetAI.cpp]: I tested 50 and that seemed too high; I could jump off cliffs and it not teleport “fast enough”. perhaps 35?

Comment (blinkysc) [reply src/server/game/AI/CoreAI/PetAI.cpp]: Or maybe even 30

Comment (sogladev) [reply src/server/game/AI/CoreAI/PetAI.cpp]: :smile: I tried 40 and that feels OK, but this can be fine-tuned/tested

Comment (blinkysc) [reply src/server/game/AI/CoreAI/PetAI.cpp]: Sounds good. I’ll make that change and in the meantime trying to find a good “gauge” of distance based on this video series https://youtube.com/playlist?list=PLf_ZOy0QRT_C2CTKRgdKc1_PLOWx_SfDI&si=Ys0oikASws7_X8MY

**Review by sogladev — APPROVED** [review]

**Comment by PkllonG** [comment]
Pets cannot move underwater
