### PR TITLE
fix(DB/Quest): Krolmir, Hammer of Storms.

### LINKED ISSUE #11637: Refresh NPC repeatedly
### Current Behaviour

`Krolmir, Hammer of Storms` (quest id 13010) ,It will cause repeated refresh of NPC(creature id 30331)

https://youtu.be/N9WrL8Syk1Y

like https://github.com/azerothcore/azerothcore-wotlk/issues/5926

### Expected Blizzlike Behaviour

Whether you have a mount or not, you will be forced to dismount and sit on the king's shoulder

### Source

_No response_

### Steps to reproduce the problem

1. `.quest a 13010 `
2. `.go xyz 7345.899902 -2812.949951 798.488281 571`
3. summon a mount
4.  talk `King Jokkum`(creature id 30105)
5. a new  `King Jokkum` (creature id 30331) will be refreshed ,but you didn't sit on the king's shoulder
6. dismount
7.The former king does not disappear

### Extra Notes

_No response_

### AC rev. hash/commit

59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

ubuntu 20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #11637

## Issues Addressed:

- Closes #11637

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

.quest a 13010
.go xyz 7345.899902 -2812.949951 798.488281 571
summon a mount
talk to King Jokkum(creature id 30105)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/game/Spells/SpellInfoCorrections.cpp [hunk 1]
```diff
@@ -3673,7 +3673,7 @@ void SpellMgr::LoadSpellInfoCorrections()
     });
 
     // Krolmir, Hammer of Storms (13010)
```
Comment (Kitzunu) [inline src/server/game/Spells/SpellInfoCorrections.cpp:3675]: need to remove the comment too.
```suggestion
    // Riding Jokkum
```

**Review by Kitzunu — APPROVED** [review]
