### PR TITLE
fix(Scripts/Spells): Seal of Command cannot be casted on dead targets.

### LINKED ISSUE #5517: [Spell] Kills While Using Seal of Command Often Produce An Invalid Target Error [$5]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:
Original report: https://github.com/chromiecraft/chromiecraft/issues/476

Killing a creature while under the effect of [Seal of Command](https://wotlkdb.com/?spell=20375) often produces the error message **Invalid Target** and an error sound.

WoWScrnShot_042821_213030

##### EXPECTED BLIZZLIKE BEHAVIOUR:
There should not be an error message and/or sound.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Get a **Paladin** to level **20** and pick the **Seal of Command** talent
2. Apply **Seal of Command**
3. Kill stuff

##### EXTRA NOTES:
* Does not happen with [Seal of Righteousness](https://wotlkdb.com/?spell=21084)
* Does also happen on current AC
* Does **not** happen on current TC

It looks like the Seal's proc effect is applied to an already dead target which produces the error. I've checked `src/server/scripts/Spells/spell_paladin.cpp` and while the implementation of the **Seal of Righteousness** aura proc does a `target->IsAlive()` check the implementation of the **Seal of Command** aura does not. 

While testing, took a pally all the way to 80 and it was still doing it.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
There is a **[$5 open bounty](https://www.bountysource.com/issues/98143864-spell-kills-while-using-seal-of-command-often-produce-an-invalid-target-error?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
Fixed #5517

## Changes Proposed:
-  Added check if proc target is alive.

## Issues Addressed:

- Closes #5517
- Closes https://github.com/chromiecraft/chromiecraft/issues/476

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

1. Get a Paladin to level 20 and pick the Seal of Command talent
2. Apply Seal of Command
3. Kill stuff

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/scripts/Spells/spell_paladin.cpp [hunk 1]
```diff
@@ -103,7 +103,9 @@ class spell_pal_seal_of_command : public SpellScriptLoader
                 if (procSpell->IsAffectingArea())
                     targets = 1;
 
-            eventInfo.GetActor()->CastCustomSpell(aurEff->GetSpellInfo()->Effects[EFFECT_0].TriggerSpell, SPELLVALUE_MAX_TARGETS, targets, eventInfo.GetActionTarget(), false, nullptr, aurEff);
+            if (Unit* target = eventInfo.GetActionTarget())
+                if (target->IsAlive())
+                    eventInfo.GetActor()->CastCustomSpell(aurEff->GetSpellInfo()->Effects[EFFECT_0].TriggerSpell, SPELLVALUE_MAX_TARGETS, targets, target, false, nullptr, aurEff);
```
Comment (FrancescoBorzi) [inline src/server/scripts/Spells/spell_paladin.cpp:108]: what about:

```suggestion
            if (Unit* target = eventInfo.GetActionTarget() && target->IsAlive())
            {
                eventInfo.GetActor()->CastCustomSpell(aurEff->GetSpellInfo()->Effects[EFFECT_0].TriggerSpell, SPELLVALUE_MAX_TARGETS, targets, target, false, nullptr, aurEff);
            }
```

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@UltraNix the build is broken

**Comment by UltraNix** [comment]
@FrancescoBorzi Done.

**Comment by FrancescoBorzi** [comment]
thanks @UltraNix . Please not that it's not necessary to squash & force-push your commits, as they would be anyway squashed on PR merge ;)
