### PR TITLE
fix(DB/Loot): Loot Normalization

### LINKED ISSUE #1716: Plans: Lionheart Helm, Drop Chance and droppable mobs appear incorrect on Azeroth Core
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [X] 50-59

### Current Behaviour

Azeroth Core not reflecting proper loot tables for plans: Lionheart Helm compared to classic database on WoWhead.

### Expected Blizzlike Behaviour

classic.wowhead.com/item=12717/plans-lionheart/helm

the comments can be found at the bottom of the page.

My guild and I were comparing Azeroth Core (AC) and classic wow databases (DB) for what proper drop chance and mobs ought to drop the plans for the Lionheart Helm. DB shows Ras Frostwhisper should have a small chance to drop it, but AC is not showing it on his loot table at all, Guildies are saying. (Idk how to check AC myself. I'm just reporting it for us/the server.)

Also the classic DB is showing that it's also droppable from an eternium lockbox (the comments on the DB suggest that MOST people get their plans from these lockboxes.) But, again, guild is telling me that they don't see the lionheart plans in the loot table at all from eternium lockboxes. 

That's it for outside of raiding. We didn't look at the AC to check mobs inside raids as we're sure those will be fine.

Thank you for reading and keep up the good work guys! =D

### Source

Sources:
classic WoWhead loot tables, which i believe is similar to 3.3.5a's.
Azeroth Core loot tables.

### Steps to reproduce the problem

1. Compare Azeroth Core loot table to WoWHead loot table.
2. Correct Azeroth Core Loot table if need be.

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### LINKED ISSUE #5342: 2 enchanting formulas missing from most loottables
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

Enchanting recipes [Formula: Enchant Shield - Shield Block](https://wowgaming.altervista.org/aowow/?item=22540) and [Formula: Enchant Boots - Vitality](https://wowgaming.altervista.org/aowow/?item=22542) are missing from most loottables. 

### Expected Blizzlike Behaviour

Both enchants should have significantly more sources to be acquired from.

### Source

Shield Block: https://www.wowhead.com/wotlk/item=22540/formula-enchant-shield-shield-block

Vitality: https://www.wowhead.com/wotlk/item=22542/formula-enchant-boots-vitality

### Steps to reproduce the problem

-

### Extra Notes

Vitality enchant has also a binds when picked up version from Kael'thas Sunstrider: https://www.wowhead.com/wotlk/item=35298/formula-enchant-boots-vitality

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/37f0b7095f949293c13f1d913f8917407ffe3b1b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### LINKED ISSUE #5732: heroic ramparts some mobs dropping normal loot
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

mobs dropping runecloth like normal version
WoWScrnShot_060723_215056

edit: this also might be happening in blood furnace

### Expected Blizzlike Behaviour

not dropping lower level loot

### Source

https://www.wowhead.com/wotlk/npc=17269/bleeding-hollow-darkcaster#drops;mode:heroic

### Steps to reproduce the problem

go to ramps
kill mobs
see loot

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### LINKED ISSUE #5919: Engineering Recipe (Schematic: Purple Smoke Flare) missing from most loottables
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Similar to [5342](https://github.com/chromiecraft/chromiecraft/issues/5342), I believe the Engineering Recipe, Schematic: Purple Smoke Flare, should be treated as World Drop in Outlands.

### Expected Blizzlike Behaviour

The recipe should have significantly more sources to be acquired from.  I know WoWHead comments are not a perfect source, but we do see several from the pre-Classic era talking about getting this recipe as a BoE drop from multiple Outlands mobs.

https://www.wowhead.com/wotlk/item=25887/schematic-purple-smoke-flare#comments

### Source

I'm not sure if this item is perfectly synced to the aowow database values, but this is what I believe CC currently has for drop rates:

https://wowgaming.altervista.org/aowow/?item=25887#dropped-by

### Steps to reproduce the problem

Check Item ID: 25887 drop rates and mobs, and see that it is missing from the vast majority of mobs it should drop from (world drop in Outlands).

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e4d64ec319b6feac3b6d95734ec292efd25e1bb5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### LINKED ISSUE #6517: "Schematic: Healing Potion Injector" seems to have strangely limited drop sources
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Currently the recipe seems to only drop from a handful of mobs.
https://wowgaming.altervista.org/aowow/?item=23883#dropped-by

### Expected Blizzlike Behaviour

According to wowhead, the recipe should drop from most high level outland mobs, like a world drop.
https://www.wowhead.com/wotlk/item=23883/schematic-healing-potion-injector

### Source

https://wowgaming.altervista.org/aowow/?item=23883#dropped-by
https://www.wowhead.com/wotlk/item=23883/schematic-healing-potion-injector

### Steps to reproduce the problem

Difficult to reproduce as you would have to kill thousands of specific mobs to verify.

### Extra Notes

same issue as https://github.com/chromiecraft/chromiecraft/issues/6514 https://github.com/chromiecraft/chromiecraft/issues/5342 https://github.com/chromiecraft/chromiecraft/issues/5935 etc 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e2ecbf44cc19450109bee1ef7ce6aaa7621c5af4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### LINKED ISSUE #7238: [Loot] Eternium Lockbox faulty drops
### Current Behaviour

Eternium Lockbox has a very inaccurate loot table and is missing multiple important recipes.

### Expected Blizzlike Behaviour

Eternium Lockbox should be able to drop epic recipes such as:
Plans: Lionheart Helm
Plans: Stronghold Gauntlets
Plans: Invulnerable Mail
Plans: Sageblade

--

In addition, it currently only drops 2 different blues as opposed to the around 50 items available on Blizzlike.

Amongst other items.

### Source

image
A list of drops opening 1439 Lootboxes.

https://web.archive.org/web/20111101235508/https://www.wowhead.com/item=5760/eternium-lockbox#contains:0+15+1

WayBack Machine for drops, the list is based on 20,000 opened Lockboxes.

https://classic.wowhead.com/item=5760/eternium-lockbox#contains

Classic wow for drops, the list is based on 3,000 opened lockboxes.

https://www.youtube.com/watch?v=6JyGT5R5RWc

Clip from Classic where Lionheart drops from Lockbox.

### Steps to reproduce the problem

1. `.setskill 633 400 400`
2. `.learn 1804`
3. `.ad 23162 4` (Add 4 large bags)
4. `.ad 5760 159` (in a macro if you want to repeat.)
5. `.cheat casttime`
6. Make a macro with:
 ```#showtooltip
/run LootSlot(1)
/use Eternium Lockbox
/cast Pick Lock
/use Eternium Lockbox
/run LootSlot(1)
```
7. Spam macro to open lockboxes.

--

Extra steps:
`/run for bag=0,4,1 do for slot=1,GetContainerNumSlots(bag),1 do local name=GetContainerItemLink(bag,slot) if name and string.find(name,"") then DEFAULT_CHAT_FRAME:AddMessage("- Selling "..name) UseContainerItem(bag,slot) end end end`
Sell all items to vendor Macro

```!WA:2!nF1tZTrsv8vLQSatcbBZwMLKf2HjOSsRThh5a7btfalBPyhKT0oACCCL1O0ZmT004rDp0Dp(pHSfuQsrTN9hbDMlOpbu5aN7YlN5q(iS34af86zum2rk4avrvmvPr909V3RF973VUN3K7HZiCUR9s23DMEZemtWxS0jiUFDmTRm85Z(spgpaZRG83pGZIJNQse5PpfXdmDzSijjMFuJoDey56)PFRzo2FD9pIF8Oo(5)UV8F832)poOFxojW94ySLZAdZC3QSig)b5YLlF8ujc8ku)qgVjMVnLidxkHhfFZqPmwS8IlEiQlZMWwSbTjz3nFa)4flZr(scJk(ehHeXLgEDiuIi0Oc8N0OVKt62fZf3428rn)9dcWEjD6Odc(6vR3S221RiHhCqjC0s9fX4OOncegVuK4HpatLTa0KJg2E1vA52UL7koUNnutoggYPvZQ1R7qr9WcdN0b8whJIKHvsGOWlocDmMFscDuiym0NfL0J2kg5JZ)veQeZPOOhcXjSu29eeL0dPxvFI6Bw7fyKa3sYt5GVM69Qqzu8PbqSQr0wh5Cb2Nrde91q1RlvHk9qeAn1pemqvqDB1hPkc)F9xVhhuePlTs9Q1C5q(thC54hKfh5haRshCxD21OsedfuZtIIGf3So9sa62WXpcjeZQkBubYA(znipfRBCQ3ivsg9MpF(M5VJ9pUpNjtd8C8SvjoSpq61j9aY2r4d(ppG5WSuJxMcjCq2)vd6IJNU1VobXXM1sIIm3jKiXd4PbPEH)IGJbwG43LZsIhzvliIUsfbJlH0cmWHvwRXoBDIah1PjdY9C3gn1jGrYXnOGEn)GoG7xLW9JWp5LqYfsouznqRX4EoRS2gB3AiktOQDH3Qv3YTQZlY8qMK)B4jW9GuPtz77yFNbsM)O86x)GpZIeep9p4(ykMJISRZyY6eH8e9EJDibYWRoSdhetaRJKO8Fv2mvt3LEr61AvNQv3YrOZrxzPesWWnrpQz916LudTRtKoxE1trjsWOgXP7om84OasI45xBGwPqY6CiH2HXZKAZg)(GsGXXJSOQwfxLZzCXt8aB6q6AmJ)n(I5HmRmIarEJTDRVXwvD8FfbNx9U5upq9lIVvarO18U4JKTZMH202ippo(acq5T7HoA6yZjGkUTK0dp6PCXt5NiKSEAeBhhawQ(aLH6QQRbBmmux3q9TmutD9BRM(pREpVmSQVJ69buFp13x9HQBAOM1qHp6D)7DsOPNtueffbCPelMpDF68222LmmHR0BKoMPDBEV7zAT66R42EZw3VD9gnCTmLHyAki9L(SI2y6b264fCyVyZ7zEFS0fESyPFY44Iasg4tcTlaeX7w(miN1iIbYFtqq3RoHUpatKI3gsf(HfNGNM36zfoAUNTU2KLTx4zH6FpJBvAcU8S5(co9vt28Mw6MpUWc)ScblV3Ct0fBeCjMVCXcbZvAmB9zj6m6LVCmT0H)rfT)4s2J5LdH9wcWl)Mp)Sba26nfoSowLszmZfwWQaYM15J3BupNz(L6cn8jz0ffa4uU)vgUCx4uZIwMzwBdZk4Q9o3QzmAxFHJe4)lMI3A3tdmo)uDXrFtZJXKmh2AMsfMe6Ke3l3nlpAv4qqezgWmLiViSnbovLllMsIZN6GsxWTlSG2XK7vE(BLr0GLXGdLfj22wlBAzBN2)Jj7DrdbcmBGY7LUPDxwI14m2ixLkIl96caktAE2Xcpod0EVbwFmyGGCmu6lri7qyqjpbp)eb4hIODXb)BXeZzD5yHqFQpa0sp3eFRjdwx(H(SLZZMtgjHgGpcGERZwoZvEYiHr93xVRRy2MyGJkxACOF(BHy()JZC)Vn1n2k3oBO5(pkNE(DWNR9fB8Qr4yzcNMMEmG(gM9QX0AfhMgljPVn1Xpe7Vp82YVR6gz1Zko9cV0tnJ6BRmnINwxK9by3SYx3KfG)dVt8nN47VZA4OFTyGYA3(6nN7WrX93zuJkDyuz8u14KNA(PjOaDjoMUUQfYRSnulwtDhD5JQLsVF307)i99joFIrnuf6RDRUuVPNiq6OgEzN2FQiefWo8rzLQLx9tRibWQRK7LqztmDfr(PfIvzf4Xbqj(4ScZE(1gz5Uzw(bVZWZnzEfOlBwqmX6Fgvztmh7tsRUwTRH6Hd39OhGk7(PTA0TC8CVzZgvwBBziiQdzrbhR2uTLQrwTKv2aewQ18Q0W1TXMkN8Qwkx(VciDsNJvZP(LgXF4Lusw4WS11)6JXup2q9zZQ27jQBP)mKx)tjkD5FCXmh8xE0)8```
WeakAura for tracking item drops.

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. 3de7d1462031+

### Operating system

Windows 10

### Custom changes or Modules

None

### LINKED ISSUE #7845: Plans: Lionheart Helm, Drop Chance and droppable mobs appear incorrect on Azeroth Core
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1715 & https://github.com/chromiecraft/chromiecraft/issues/1716

Currently, 16 mobs can drop 'Plans: Lionheart Helm (ID 12717)'.

### Expected Blizzlike Behaviour

Comparing [Wowhead](https://tbc.wowhead.com/item=12717/plans-lionheart-helm#dropped-by) and the [DB](https://wowgaming.altervista.org/aowow/?item=12717) for the item, shows that multiple mobs are missing the chance of dropping the item. Although, Wowhead shows 39 mobs, there are most likely even more mobs, as some of them has only dropped it once.

Tho, as the drop chance seems really low for the missing mobs, this is really a small problem. And on that note, the drop chance might be a bit off, although with these numbers, Wowhead isn't rally the most viable source.

### Source

Wowpedia indicates it can also be dropped by elites 61+
https://wowpedia.fandom.com/wiki/Plans:_Lionheart_Helm

### Steps to reproduce the problem

1. ``SELECT * FROM `creature_loot_template` WHERE `item` = 12717 OR `Reference` = 34002;``

SQL explanation: 12717 is the ID of the item and the reference loot table 34002 contains the item, therefore any row which matches either, can drop the item.

### Extra Notes

This seems to stem from a general issue of the elite drop table.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### LINKED ISSUE #15465: Plans: Adamantite Weapon Chain missing from world drop loot table
https://github.com/chromiecraft/chromiecraft/issues/5184
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

https://www.wowhead.com/wotlk/item=33186/plans-adamantite-weapon-chain#dropped-by
https://wowgaming.altervista.org/aowow/?item=33186#contained-in-item

the plans dont drop from tbc creatures.

### Expected Blizzlike Behaviour

it should also be available as a boe world drop

### Source

https://wowwiki-archive.fandom.com/wiki/Patch_2.3.0

> A new world drop recipe for an [[Adamantite Weapon Chain]](https://wowwiki-archive.fandom.com/wiki/Adamantite_Weapon_Chain) has been added. This new weapon chain both reduces [disarm](https://wowwiki-archive.fandom.com/wiki/Disarm) duration and increases [parry](https://wowwiki-archive.fandom.com/wiki/Parry) rating.

### Steps to reproduce the problem

.

### Extra Notes

There are 2 versions of the plans.
1. the world drop plan i am referring to
2. a soulbound version dropping in magisters terrace

https://wowgaming.altervista.org/aowow/?search=Plans%3A+Adamantite+Weapon+Chain

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ff0c607ecec81e9793d521cc1adfe3883e20ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### LINKED ISSUE #15956: Thorium Lockbox can have nothing in it
Original issue: https://github.com/chromiecraft/chromiecraft/issues/5126

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

When you open lockboxes, there seems to be a chance for some of them to have no loot at all, like Thorium Lockbox.

### Expected Blizzlike Behaviour

Thorium Lockbox and all lockboxes should have a pool of items they can pick from and will always give you exactly one item from said pool.

### Source

Go through comments on any lockbox page on wowhead and you won't find a single one saying they got nothing in it.

### Steps to reproduce the problem

`.additem 43377` Glyph of Pick Lock
`.additem 5759 20`
`.setskill 633 250`

### Extra Notes

I know this is a minor problem, but it's rather annoying going out of my way to find a rogue that has leveled their lockpicking to the skill level required to open lock boxes, then getting nothing from it and would have been better off just vendoring the unopened box itself.

### AC rev. hash/commit

539801377fb9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### LINKED ISSUE #17203: [DB/Item] Pattern: Earthen Netherscale Boots not a possible loot
Original issue: https://github.com/chromiecraft/chromiecraft/issues/5185

### What client do you play on?

enGB - enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Item [Earthen Netherscale Boots](https://wowgaming.altervista.org/aowow/?item=29730) is not possible to drop from ~70 mobs in TBC. 

### Expected Blizzlike Behaviour

The item is supposed to drop various of mobs in TBC, both in dungeons and open world. 
See: https://www.wowhead.com/wotlk/item=29730/pattern-earthen-netherscale-boots

Comment stating a drop from Wyrmcult Poacher: https://www.wowhead.com/wotlk/item=29730/pattern-earthen-netherscale-boots#comments:id=3108034

Sunfury Geologist in Netherstorm: https://www.wowhead.com/wotlk/item=29730/pattern-earthen-netherscale-boots#comments:id=3108032

### Source

https://www.wowhead.com/wotlk/item=29730/pattern-earthen-netherscale-boots

### Steps to reproduce the problem

1. Check in the DB various npc listed in the source

### Extra Notes

_No response_

### AC rev. hash/commit

dd647da913ef

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by Gultask**
Requires: https://github.com/azerothcore/azerothcore-wotlk/pull/24275

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [X] Database (SAI, creatures, etc).

This has been worked on for a while now and it's the proposed new system I explained here: https://github.com/azerothcore/azerothcore-wotlk/pull/24275#issuecomment-3702604662
It would be an evolution of another system, mostly ported from Cmangos, that was implemented in 2024 for Old World creatures.
This system, however, also applies to most instance creatures.

In short, we'd have a tree-like structure for world loot. Items like greys, whites, greens, blues, purples, potions, scrolls, patterns, gems, librams and cards would be located in base references organized by level range.

1 + [Expansion] + [Quality Or Class] + MinLevel + MaxLevel

1021317 = 1 + Vanilla + Greens + 13 - 17 Level Range.

These base tables are then bundled into packages, or Root References, depending on level, rank and humanoid-like qualities of being able to drop scrolls and potions.

A level 52 humanoid-like would have package 1000152, consisting of:
1. Greys of Range 51-63 at 6%
2. 5 References to Greens, covering ranges 48-56 with 0.4% Chance each, grouped to 2% total
3. 4 References to Blues, covering ranges 49-55
4. 4 References to Purples, covering ranges 46-58
5. Potion Reference
6. Scrolls Reference
7. A Miscellaneous Reference with 100% Chance, consisting of nested groups of gems and lockboxes, grouped at 1.5% chance for gems and 0.5% chance for lockboxes
8. A Reference for Bags
9. 2 References to Patterns, covering ranges 40-62
10. A Reference for Librams, Cards and Spell Books, similar in structure to the Miscellaneous group

Creatures that are within the level range of 51-53 then would receive 3 Roots. One for 51, another for 52 and another for 53. These would be grouped into a single group, essentially giving a 33.3% Chance of either dropping gear for each level.

The classification of root references is rather arbitrary, but for this PR:
1 + Exp + 00 + [Modifier] + Level
Modifier being:
0: Beast-like loot, Normal
1: Humanoid-like loot, Normal
2: Beast-like loot, Elite
3: Humanoid-like loot, Elite

This PR should lower row count by about 100k in creature_loot_template and quite a lot in reference_loot_template as well.

### AI-assisted Pull Requests

> [!IMPORTANT]
> While the use of AI tools when preparing pull requests is not prohibited, contributors must clearly disclose when such tools have been used and specify the model involved.
> 
> Contributors are also expected to fully understand the changes they are submitting and must be able to explain and justify those changes when requested by maintainers.

- [X] AI tools (e.g. ChatGPT, Claude, or similar) were used entirely or partially in preparing this pull request. Please specify which tools were used, if any.

Both Gemini and Claude were used to create py scripts and sql statements for automatization, but most of this was done by hand.

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/7920
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/24361
- Closes https://github.com/chromiecraft/chromiecraft/issues/5342
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19985
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15465
- Closes https://github.com/chromiecraft/chromiecraft/issues/6604
- Closes https://github.com/chromiecraft/chromiecraft/issues/6517
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20729
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17203
- Closes https://github.com/chromiecraft/chromiecraft/issues/8779
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/23780
- Closes https://github.com/chromiecraft/chromiecraft/issues/5919
- Closes https://github.com/chromiecraft/chromiecraft/issues/5732
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15956
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7238
- Closes https://github.com/chromiecraft/chromiecraft/issues/1716
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7845
- Closes https://github.com/chromiecraft/chromiecraft/issues/8990

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [X] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [X] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. 

## Known Issues and TODO List:

- [x] Look if there isn't any groupId overlap between root references and loose items
- [x] Remove deprecated references
- [x] Lower chances for loot when HPMult very low for exploit prevention
- [x] TBC Demons vary on if they drop potions and scrolls. Do a search if they drop Cloth, and change the roots of those that do not

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
row count change:
creature_loot_template: 249466 -> 111233
reference_loot_template: 44536 -> 24013

File: data/sql/updates/pending_db_world/vanillaTBC.sql [hunk 1]
```diff
@@ -15439,9 +15439,9 @@ INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `G
 (10408, 4, 1000258, 0, 5, 'Rockwing Gargoyle - World Loot Level 58'),
 (10409, 1, 1000258, 0, 5, 'Rockwing Screecher - World Loot Level 58'),
 (10409, 2, 1000259, 0, 5, 'Rockwing Screecher - World Loot Level 59'),
-(10411, 1, 1000155, 0, 5, 'Eye of Naxxramas - World Loot Level 55'),
-(10411, 2, 1000156, 0, 5, 'Eye of Naxxramas - World Loot Level 56'),
-(10411, 3, 1000157, 0, 5, 'Eye of Naxxramas - World Loot Level 57'),
+(10411, 1, 1000155, 3.34, 5, 'Eye of Naxxramas - World Loot Level 55'),
+(10411, 2, 1000156, 3.34, 5, 'Eye of Naxxramas - World Loot Level 56'),
+(10411, 3, 1000157, 3.34, 5, 'Eye of Naxxramas - World Loot Level 57'),
```
Comment (heyitsbench) [inline data/sql/updates/pending_db_world/vanillaTBC.sql:15460]: Why such specific number?

Comment (Gultask) [reply data/sql/updates/pending_db_world/vanillaTBC.sql:15460]: They have 0.1 HealthModifier so I set it to 10% total :^)

**Comment by Gultask** [comment]
By the way, for testing or to modify the values, I created a little query for it: https://gist.github.com/Gultask/b7fd6ea64bedf5ea1a3f19e744eb4ad0

**Comment by Gultask** [comment]
I retooled late vanilla patterns, as a lot of them were actually missing, like Rare and Epic patterns.

Also remade Lockboxes.

**Comment by Gultask** [comment]
Alright, seems to be working from what I can see. Fixed a bug that I found.

I made another chance modifier file: https://gist.github.com/Gultask/738c7ba17e2e75d84184f1bda6456749
Set the chances to like 50, ran around killing stuff and every loot category dropped at least once.

**Review by Nyeriah — APPROVED** [review]

**Comment by mwc-lord** [comment]
@Gultask, you are using incorrect assumptions that are not blizzlike behavior, which I already mentioned [here](https://github.com/azerothcore/azerothcore-wotlk/pull/24275#issuecomment-3919078229).

> A level 52 humanoid-like would have package XXXXX, consisting of:
5 References to Greens, covering ranges 48-56 with 0.4% Chance each, grouped to 2% total
4 References to Blues, covering ranges 49-55
4 References to Purples, covering ranges 46-58

1. No creature in the game can drop equipment that requires a player level higher than the creature's minimum level. This applies to all items, of any quality, including recipes. This rule applies even to elites and dungeon/raid bosses.
2. Regular creatures cannot even drop equipment what equal to their own level! (But Elites can!) Equipment is always 1 level below their minimum level. The exception is creatures from expansions at levels 58 and 68 — due to insufficient equipment pools for levels 57 and 67, they have been additionally supplemented with level 58/68 equipment.
3. Also, in expansions, creatures drop "green-blue" equipment within a range of 3 levels, not 5 as in Classic.

So, a level 52 humanoid (non-elite!) would drop:

- Green equipment in the range of 47-51
- Blue equipment in the range of 47-51
- Purple equipment in the range of 47-51

Like these guys (pay attention to their maximum level):

https://www.wowhead.com/tbc/npc=8914/twilight-bodyguard#drops;mode:normal;0-4-3+17-20+1
https://www.wowhead.com/tbc/npc=6005/shadowsworn-thug#drops;0-4+17-20+1
https://www.wowhead.com/wotlk/npc=10605/scarlet-medic#drops;0-4+17-20+1

> Creatures that are within the level range of 51-53 then would receive 3 Roots. One for 51, another for 52 and another for 53.

This is a misconception. Only the creature's minimum level matters — maximum level are not have sense. This applies not only to dropped equipment but also to gold.

**Comment by Gultask** [comment]
The ranges are the drop ranges.

14313, 'Celestial Cape' is in the range 51-55, for example, while requiring Level 49 to equip

image

image

They were sorted by itemlevel and required level rather than checked one-by-one, though.

I mostly only checked normal creatures because elites were indeed different. In that case no (or very few) creatures level 50 drop that item, while those level 50-51 ranged do drop it.
Same for the higher bounds.

**Comment by mwc-lord** [comment]
Regarding the Ornate Bronze Lockbox (and others).
I found an interesting [video](https://youtu.be/ffD6MI5FqCs) which shows:

1. A Lockbox can drop 2 items, or even 3.
2. The combination of dropped items can be anything: 2 greens, 2 recipes, green + blue, green + recipe.
3. Blizzard forgot to put money in the Heavy Bronze Lockbox :)

So, based on point 1, we need to either use a single group reference with Min/Max Count set to 1-3 (currently, they are broken because the MinСhance in group references is ignored), or duplicate this reference in item_loot_template three times but with different chances (100/~25/~5).

And based on point 2, all these items should be in the same group reference to have equal drop chances.

**Comment by Gultask** [comment]
That's true.. I'll remove Vanilla lockboxes for now. They are more complex than Khorium and Froststeel.

Again, I'll push the PR because it's better than what we have now, and it makes maintenance easier than changing every single creature individually.

**Comment by mwc-lord** [comment]
> They are more complex than Khorium and Froststeel.

Is it just because there are recipes and gems in the lists?
Because in lockboxes from expansions, multiple items of varying quality can also drop:
https://youtu.be/ZTwHrNRcAk8

**Comment by Gultask** [comment]
I had left for lunch and immediately remembered that this is really easy to fix lol

image

**Comment by Gultask** [comment]
Ultimately there will be future work on this. This is not an end-all solution. And hopefully it won't be a 1year+ wait until the next work done on World Loot system by me.
