### PR TITLE
fix(DB/Conditions) Spirit of the Vale

### LINKED ISSUE #6780: Spirit of the Vale addresses non-shaman characters as shamans
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/1113

This looks wrong, he is addresses my mage as a shaman.
Spirit of the Vale: DB GUID 59483

Screenshot from 2021-07-05 12-50-16

### Expected Blizzlike Behaviour

Please check the npc’s dialogue options:
1. If an option exists for non-shamans, assign that for non-shaman characters.
2. If no option exists, non-shamans should not be able to initiate dialogue with the npc.

### Steps to reproduce the problem

1. Teleport or move to Spirit of the Vale: DB GUID 59483
2. Click NPC to open dialogue window.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

### Operating system

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: dc76e6b) :

WoWScrnShot_070721_043210

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99776007-spirit-of-the-vale-addresses-non-shaman-characters-as-shamans?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by TheDdraig**
## Changes Proposed:
-  Spirit of the Vale was showing the improper text to non shaman players, needed to set conditions as there is 3 texts, 1 for non-shaman players, 1 for shamans and 1 for complete text after doing quest chain
-  

## Issues Addressed:
- Closes #6780

## SOURCE:
Malcrom

## Tests Performed:
Checked ingame where it showed shaman text to non shaman players

## How to Test the Changes:

1. .go c 59483
2. talk to npc as a non shaman and shaman

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

File: data/sql/updates/pending_db_world/rev_1640896254599408944.sql [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+
+-- Condition for source Gossip menu condition type Class
+DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=14 AND `SourceGroup`=7376 AND `SourceEntry`=8824 AND `SourceId`=0;
+INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
+(14, 7376, 8824, 0, 0, 15, 0, 64, 0, 0, 1, 0, 0, '', 'Show gossip menu 7376 text id 8824 if player is not a shaman.');
+
+-- Condition for source Gossip menu condition type Class
+DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=14 AND `SourceGroup`=7376 AND `SourceEntry`=8827 AND `SourceId`=0;
+INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
+(14, 7376, 8827, 0, 0, 15, 0, 64, 0, 0, 0, 0, 0, '', 'Show gossip menu 7376 text id 8824 if player is a Shaman.'),
```
Comment (acidmanifesto) [inline data/sql/updates/pending_db_world/rev_1640896254599408944.sql:18]: reconfirm the text id in your notes portion is different from your sourceid.

File: data/sql/updates/pending_db_world/rev_1640896254599408944.sql [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+(14, 7376, 8827, 0, 0, 47, 0, 9451, 64, 0, 1, 0, 0, '', 'Show gossip menu 7376 text id 8824 if quest Call of Earth is not rewarded.');
```
Comment (acidmanifesto) [inline data/sql/updates/pending_db_world/rev_1640896254599408944.sql:19]: reconfirm the text id in your notes portion is different from your sourceid.

File: data/sql/updates/pending_db_world/rev_1640896254599408944.sql [hunk 3]
```diff
@@ -0,0 +1,19 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1640896254599408944');
+
+-- This fixes: https://github.com/azerothcore/azerothcore-wotlk/issues/6780
+
+-- Condition for source Gossip menu condition type Queststate
+DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=14 AND `SourceGroup`=7376 AND `SourceEntry`=8826 AND `SourceId`=0;
+INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
+(14, 7376, 8826, 0, 0, 47, 0, 9451, 64, 0, 0, 0, 0, '', 'Show gossip menu 7376 text id 8826 if quest Call of Earth is rewarded');
```
Comment (acidmanifesto) [inline data/sql/updates/pending_db_world/rev_1640896254599408944.sql:8]: Error give durning compile testing is:
addToGossipMenus: GossipMenu 7376 not found
Not handled grouped condition, SourceGroup 7376
Please reconfirm the GossipMenu is in the game, if so please include it as it isnt on my local or on the master.

**Review by acidmanifesto — CHANGES_REQUESTED** [review]

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
Thank you for the PR.
