### PR TITLE
fix(DB): #5036 NPC's don't attack the player if he is in water

### LINKED ISSUE #5036: NPCs don't attack the player if he is in water
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

While fighting Venture Co. NPCs in Barrens, noticed if I attack them from Water, either by Taunting or Casting spells NPC get triggered but instantly return to passive state. [Video evidence](https://imgur.com/P8vLRV1)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After taunting or attacking NPC enemy they should engage in fight

##### STEPS TO REPRODUCE THE PROBLEM:

1. Swim in water
2. Taunt or cast ranged ability
3. Enemy will not attack and Evade

##### Extra Info:
Linked Issue: https://github.com/chromiecraft/chromiecraft/issues/306

Might be related to: https://github.com/azerothcore/azerothcore-wotlk/issues/5022

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/97481761-npcs-don-t-attack-the-player-if-he-is-in-water?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Hacki95**
## Changes Proposed:
- Set the inhabitType of the Venture Co NPCs around the waterhole to 3 so they follow the player into the water. Thanks @UltraNix for the info.

## Issues Addressed:
- Closes: #5036
- Closes: https://github.com/chromiecraft/chromiecraft/issues/306

## SOURCE:

- https://youtu.be/-Wix7uoQjfo?t=830 Watch how the player still gets attacked while he is in water.

## Tests Performed:

- Applied SQL
- Tried fighting from the Water, NPCs follow you now.

## How to Test the Changes:

- Apply SQL
- .tele thesludgefen
- Aggro NPCs from the water.

## Known Issues and TODO List:

- /

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1617016392531315494.sql [hunk 1]
```diff
@@ -0,0 +1,8 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1617016392531315494');
+
+UPDATE creature_template SET InhabitType = 3 WHERE (entry = 3282); -- Venture Co. Mercenary
+UPDATE creature_template SET InhabitType = 3 WHERE (entry = 3283); -- Venture Co. Enforcer
+UPDATE creature_template SET InhabitType = 3 WHERE (entry = 3284); -- Venture Co. Drudger
+UPDATE creature_template SET InhabitType = 3 WHERE (entry = 3445); -- Supervisor Lugwizzle
+UPDATE creature_template SET InhabitType = 3 WHERE (entry = 5836); -- Engineer Whirleygig
```
Comment (FrancescoBorzi) [inline data/sql/updates/pending_db_world/rev_1617016392531315494.sql:7]: you can combine them with 
```sql
... WHERE `entry` IN (x, y, z, ...);
```

Comment (Hacki95) [reply data/sql/updates/pending_db_world/rev_1617016392531315494.sql:7]: Yes, I just thought I'd do it this way so its easy for anyone to see which creatures I actually update, saw it like that in other PRs. 

Should I update it?

Comment (FrancescoBorzi) [reply data/sql/updates/pending_db_world/rev_1617016392531315494.sql:7]: yes, you can still have the comments:

```sql
UPDATE creature_template SET InhabitType = 3 WHERE entry IN (
  3282, -- Venture Co. Mercenary
  3283, -- Venture Co. Enforcer
  3284, -- Venture Co. Drudger
  3445, -- Supervisor Lugwizzle
  5836  -- Engineer Whirleygig
); 
```

**Review by FrancescoBorzi — APPROVED** [review]
