### PR TITLE
fix(Core/Spells): Port HandleBreakableCCAuraProc from TrinityCore

### LINKED ISSUE #9052: [QAston] Protection Warrior talent Gag Order not working
### Current Behaviour

Shield Bash and Heroic Throw do not apply [Silenced - Gag Order](https://wowgaming.altervista.org/aowow/?spell=74347wowgaming.altervista.org/aowow/?quest=11574) aura.

### Expected Behaviour

Shield Bash and Heroic Throw apply [Silenced - Gag Order](https://wowgaming.altervista.org/aowow/?spell=74347wowgaming.altervista.org/aowow/?quest=11574) aura.

### Source

[Gag Order](https://wowgaming.altervista.org/aowow/?spell=12958) talent description.

### Steps to reproduce the problem

1. Learn prot warrior talent [Gag Order](https://wowgaming.altervista.org/aowow/?spell=12958) to rank 2.
2. Use Shield Bash or Heroic Throw on an enemy/dummy.

### Extra Notes

_No response_

### Customizations

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/686aafd57be6f1594a99634bade3756643fbf6f3

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-chromiecraft-smartstone](https://github.com/chromiecraft/mod-chromiecraft-smartstone)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-evade-logging](https://github.com/heyitsbench/mod-evade-logging)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-quests](https://github.com/azerothcore/mod-pvp-quests)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by blinkysc**
## Changes Proposed:
This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

CC auras (Fear, Confuse, Stun, Root, Transform) have a damage threshold set in `AuraEffect::CalculateAmount`, and the proc system correctly fires on every damage event with 100% chance — but `HandleProc` fell through to `default: break` and did nothing. The threshold was calculated but never consumed, so CC effects like Fear never broke from accumulated damage via the proc system.

This ports TrinityCore's `HandleBreakableCCAuraProc` which subtracts incoming damage from the threshold and removes the aura when it reaches zero. Also adds the missing `isAlwaysTriggeredAura[SPELL_AURA_MOD_CONFUSE]` entry to match TC.

Note: spells like Polymorph that have `AURA_INTERRUPT_FLAG_TAKE_DAMAGE` break deterministically on any damage via `RemoveAurasWithInterruptFlags` — those are unaffected by this change. This fix targets CC spells (like Fear) that rely on the proc-based damage threshold system.

### AI-assisted Pull Requests

> [!IMPORTANT]
> While the use of AI tools when preparing pull requests is not prohibited, contributors must clearly disclose when such tools have been used and specify the model involved.
> 
> Contributors are also expected to fully understand the changes they are submitting and must be able to explain and justify those changes when requested by maintainers.

- [x] AI tools (e.g. ChatGPT, Claude, or similar) were used entirely or partially in preparing this pull request. Please specify which tools were used, if any.

**Tools used:** Claude Code with azerothMCP

## Issues Addressed:
- Closes https://github.com/chromiecraft/chromiecraft/issues/9052

## SOURCE:
The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [x] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

TrinityCore `HandleBreakableCCAuraProc` from commit [1f8fc55](https://github.com/TrinityCore/TrinityCore/commit/1f8fc55ac9d5b12acc56fa72e4ae61f24b910b0d) 

## Tests Performed:
This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [x] This pull request requires further testing and may have edge cases to be tested.

15 unit tests added covering the CC break logic (threshold depletion, accumulation, proc pipeline integration). All 5411 existing tests pass with no regressions.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [x] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Log in with a Warlock and a second character (or use a friend)
2. Cast Fear on the target
3. Deal damage to the feared target — Fear should break after enough cumulative damage
4. Verify small DoT ticks don't instantly break Fear but accumulate toward the threshold
5. Verify Polymorph still breaks instantly on any damage (uses different mechanism)

## Known Issues and TODO List:

- [ ] Needs in-game testing to verify threshold feels correct for PvP balance
- [ ] Glyph of Fear threshold increase should be verified in-game

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/game/Spells/Auras/SpellAuraEffects.cpp [hunk 1]
```diff
@@ -1254,6 +1254,13 @@ void AuraEffect::HandleProc(AuraApplication* aurApp, ProcEventInfo& eventInfo)
 
     switch (GetAuraType())
     {
+        case SPELL_AURA_MOD_CONFUSE:
+        case SPELL_AURA_MOD_FEAR:
+        case SPELL_AURA_MOD_STUN:
+        case SPELL_AURA_MOD_ROOT:
+        case SPELL_AURA_TRANSFORM:
+            HandleBreakableCCAuraProc(aurApp, eventInfo);
+            break;
```
Comment (sogladev) [inline src/server/game/Spells/Auras/SpellAuraEffects.cpp:1263]:
```suggestion
            break;
        case SPELL_AURA_DUMMY:
```
Is this needed? Missing from the cherrypick

Comment (blinkysc) [reply src/server/game/Spells/Auras/SpellAuraEffects.cpp:1263]: https://github.com/azerothcore/azerothcore-wotlk/pull/24794

Comment (blinkysc) [reply src/server/game/Spells/Auras/SpellAuraEffects.cpp:1263]: Guess can just close the other though lol

**Review by Nyeriah — APPROVED** [review]
