### PR TITLE
fix(Core/Loot): Quest items should not be lootable/visible if already…

### LINKED ISSUE #6442: Quest drops still visible after requirements fulfilled
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/902

##### CURRENT BEHAVIOUR:

After collecting all required quest items from mobs, those items will incorrectly continue to drop (or remain visible) under two circumstances: (a) the player's quest items are in their bank; (b) the player killed multiple mobs before looting.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Once a player has collected all dropped items for a quest (even if they are stored in the bank), they should never see extra copies of these items on mobs. These extra item drops should also not prevent skinning.

##### SOURCE:

I've looked for a while and I'm not sure I can find a source for this one. AoE videos either don't show looting, or they've already completed the relevant quests prior to filming. Most players don't usually store quest items in their bank, but the progressive level cap on ChromieCraft is a unique circumstance. Having played multiple AoE classes (which would encounter this specific situation regularly) throughout various retail expansions including 3.3.5, I can't recall having ever encountered this issue on an official server. This is absolutely a bug, but not an urgent one.

Players with skinning can work around this issue by deleting a quest item from their bag, looting the mob, and then skinning it.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Accept any quest to collect drops from mobs, especially skinnable mobs (e.g. Singing Blue Shards from Crank Fizzlebub in Booty Bay).
2. Collect all but one of the required items (e.g. 9/10).
3. Kill multiple mobs before looting any. You should see extra items, but be unable to loot them after fulfilling the quest requirement (this incorrectly prevents skinning).
4. Put all these quest items in your bank and continue killing the same mobs. You should be able to incorrectly collect additional quest items.

##### EXTRA NOTES:

This appears to affect a large number of quests; although there a handful of specific quest issues listed here on github, I did not see a generic bug report for all quest drops. Apologies if this is a known issue.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 466cdb6) :

WoWScrnShot_062021_053228
WoWScrnShot_062021_053427
WoWScrnShot_062021_053444
WoWScrnShot_062021_053612
WoWScrnShot_062021_053732
WoWScrnShot_062021_053737

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99363487-quest-drops-still-visible-after-requirements-fulfilled?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
… fulfilled quest objective.

Fixes #6442

## Issues Addressed:

- Closes #6442
- Closes https://github.com/chromiecraft/chromiecraft/issues/902

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

1. Accept any quest to collect drops from mobs, especially skinnable mobs (e.g. Singing Blue Shards from Crank Fizzlebub in Booty Bay).
2. Collect all but one of the required items (e.g. 9/10).
3. Kill multiple mobs before looting any. You should see extra items but in red.
4. Put all these quest items in your bank and continue killing the same mobs. You should not be able to see additional quest items.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by stoudtlr** [comment]
**PR resolves issue**

1. Took Singing Blue Shard quest from Booty Bay and then collected 9/10 singing crystal shards.
2. killed 4 more and collected another shard. remaining shards in other basilisk's turned red as intended.
image
3. then went to booty bay bank and deposited 9 of them and destroyed 1 so that I still needed 1 more for quest
4. returned to basilisk cave and killed 4 more
5. 3 of the 4 had shards, but after collecting 1 of them for a total of 10 (1 in inventory and 9 in bank) the others all disappeared.
6. killed a few more basilisks and all of them had unrelated loot or empty loot.  Could not get more than 10 shards.
pr7700

File: src/server/game/Entities/Player/PlayerQuest.cpp [hunk 1]
```diff
@@ -2180,8 +2180,27 @@ bool Player::HasQuestForItem(uint32 itemid, uint32 excludeQuestId /* 0 */, bool
             // This part for ReqItem drop
             for (uint8 j = 0; j < QUEST_ITEM_OBJECTIVES_COUNT; ++j)
             {
-                if ((itemid == qinfo->RequiredItemId[j] && q_status.ItemCount[j] < qinfo->RequiredItemCount[j]) || (turnIn && q_status.ItemCount[j] >= qinfo->RequiredItemCount[j]))
+                if (itemid == qinfo->RequiredItemId[j] && q_status.ItemCount[j] < qinfo->RequiredItemCount[j])
+                {
+                    if (showInLoot)
```
Comment (Helias) [inline src/server/game/Entities/Player/PlayerQuest.cpp:2185]: is this a null-check? if you need to check if the value is true, it should be `if (*showInLoot)`

Comment (UltraNix) [reply src/server/game/Entities/Player/PlayerQuest.cpp:2185]: Yes - it is a pointer check and it's okay.

**Review by Helias — APPROVED** [review]
