### PR TITLE
fix(Core/Group) CF Faction Assign & Leader Instance Faction

### LINKED ISSUE #10672: [ICC] [Gunship battle] Player can talk with Muradin Bronzebeard/High Overlord Saurfang in combat and instance stucked
### Current Behaviour

Muradin Bronzebeard/High Overlord Saurfang in enemy ship can talked by another faction player

### Expected Blizzlike Behaviour

none
only with Allow group joining between factions

### Source

two gunship's leaders gossip flag should remove after player talk to any gunship's leader

### Steps to reproduce the problem

1.start gunship combat
2.use another faction player to talk with enemy gunship's leader(Muradin Bronzebeard/High Overlord Saurfang)
3.enemy ship gone and back,and hard to beat
4.after win,no item loot

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Windows 10 x64

### Custom changes or Modules

_No response_

### LINKED ISSUE #15872: (ICC) bug Gunship Battle not crossfaction ready
### Current Behaviour

If one crossfaction group tries to do icc gunship battle they find several problems.

part of the party cannot kill the mobs before ship, hacking faction forces you to kill all mobs making the "event" more dificult
you cannot hack all mobs because some must have your faction during event.
you need additional people caring about raid instead dedicate to attack the opposite ship.
if you don't hack part of party cannot do nothing.
maybe https://github.com/azerothcore/azerothcore-wotlk/src/server/scrIf one crossfaction group tries to do icc gunship battle they find several problems.

part of the party cannot kill the mobs before ship, hacking faction forces you to kill all mobs making the "event" more dificult
you cannot hack all mobs because some must have your faction during event.
you need additional people caring about raid instead dedicate to attack the opposite ship.
if you don't hack part of party cannot do nothing.
maybe https://github.com/azerothcoIf one crossfaction group tries to do icc gunship battle they find several problems.

part of the party cannot kill the mobs before ship, hacking faction forces you to kill all mobs making the "event" more dificult
you cannot hack all mobs because some must have your faction during event.
you need additional people caring about raid instead dedicate to attack the opposite ship.
if you don't hack part of party cannot do nothing.
maybe https://github.com/azerothcore/azerothcore-wotlk/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_faction_champions.cpp can be used to work properly on crossfaction group.
re/azerothcore-wotlk/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_faction_champions.cpp can be used to work properly on crossfaction group.
ipts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_faction_champions.cpp can be used to work properly on crossfaction group.

### Expected Blizzlike Behaviour

.

### Source

_No response_

### Steps to reproduce the problem

.

### Extra Notes

_No response_

### AC rev. hash/commit

e2cfb5c

https://github.com/azerothcore/azerothcore-wotlk/commit/e2cfb5c5a95a38c278d76db8deecdb2596d543aa

Last rev 

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### LINKED ISSUE #21116: [Core] Predictable Instance Faction
### Current Behaviour

Instances created under `AllowTwoSide.Interaction.Group` should use the group leader's faction rather than assigning the faction based on the first player to enter. This ensures that the instance faction remains predictable and is not randomly determined by the first entrant.

_**Changing the raid difficulty from Normal to Heroic while leader is inside the instance correctly updates the instance faction to match the group leader's faction.**_

### Expected Blizzlike Behaviour

/

### Source

_No response_

### Steps to reproduce the problem

/

### Extra Notes

_No response_

### AC rev. hash/commit

rev. b373df9b3d0d+

### Operating system

Debian 12

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by manstfu**
## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #21116
- Closes #15872
- Closes #10672

[mod-cfpve](https://github.com/pangolp/mod-cfpve) not needed anymore

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [x] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Join two separate factions in ICC, Instance should get group leader faction instead of first to enter faction
2. Both characters will be able to interact with current instance faction
3. Leave instance, disband group, characters will return to original faction and they can attack eachother

## Known Issues and TODO List:

- [Code Refactor self assigned by @Nyeriah]
- [Changing leader and switching raid difficulty will change instance faction based on the new leader faction, which in my opinion is a bug, instance should remain with the original faction]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Kitzunu — CHANGES_REQUESTED** [review]
No way, too much repetitive code.

Make it a function and just call the function

**Comment by manstfu** [comment]
Currently, OnPlayerLeave doesn't work properly. If two players from different factions enter an instance, leave it, and disband their group, they somehow remain unable to attack each other.

**Comment by Exitare** [comment]
There is again a lot of code repetition. I would recommend, like Kitzunu, to create function and call that instead.

File: src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/instance_trial_of_the_champion.cpp [hunk 1]
```diff
@@ -114,7 +114,12 @@ class instance_trial_of_the_champion : public InstanceMapScript
                 Map::PlayerList const& players = instance->GetPlayers();
                 if (!players.IsEmpty())
                     if (Player* pPlayer = players.begin()->GetSource())
-                        TeamIdInInstance = pPlayer->GetTeamId();
+                    {
+                        if (Player* gLeader = ObjectAccessor::FindPlayer(pPlayer->GetGroup()->GetLeaderGUID()))
```
Comment (Nyeriah) [inline src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/instance_trial_of_the_champion.cpp:118]: this will lead to a crash if they are not in a group

Comment (manstfu) [reply src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/instance_trial_of_the_champion.cpp]: Fixed.

File: src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/instance_trial_of_the_champion.cpp [hunk 2]
```diff
@@ -280,8 +285,13 @@ class instance_trial_of_the_champion : public InstanceMapScript
         {
             if (TeamIdInInstance == TEAM_NEUTRAL)
             {
-                if (Player* gleader = ObjectAccessor::FindPlayer(player->GetGroup()->GetLeaderGUID()))
-                    TeamIdInInstance = Player::TeamIdForRace(gleader->getRace());
+                if (Group* group = player->GetGroup())
```
Comment (Exitare) [inline src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/instance_trial_of_the_champion.cpp:288]: Why are you not creating a function for that ?

File: src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/instance_trial_of_the_champion.cpp [hunk 3]
```diff
@@ -114,7 +114,17 @@ class instance_trial_of_the_champion : public InstanceMapScript
...
+                    {
+                        if (Group* group = player->GetGroup())
+                        {
+                            if (Player* gLeader = ObjectAccessor::FindPlayer(pPlayer->GetGroup()->GetLeaderGUID()))
+                                TeamIdInInstance = Player::TeamIdForRace(gLeader->getRace());
+                            else
+                                TeamIdInInstance = pPlayer->GetTeamId();
+                        }
+                        else
+                            TeamIdInInstance = pPlayer->GetTeamId();
```
Comment (Nyeriah) [inline src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/instance_trial_of_the_champion.cpp:126]:
```suggestion
                        if (Group* group = player->GetGroup())
                        {
                            if (Player* gLeader = ObjectAccessor::FindPlayer(group->GetLeaderGUID()))
                                TeamIdInInstance = Player::TeamIdForRace(gLeader->getRace());
                            else
                                TeamIdInInstance = pPlayer->GetTeamId();
                        }
                        else
                            TeamIdInInstance = pPlayer->GetTeamId();
```

Comment (Nyeriah) [reply src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/instance_trial_of_the_champion.cpp:126]: The same for all others

**Comment by manstfu** [comment]
Code refactoring and optimization will be handled by @Nyeriah (self-assigned) after the PR is merged.

**Comment by TheSCREWEDSoftware** [comment]
Your most recent changes are not passing the checks, please check your code outrake

**Comment by manstfu** [comment]
> Your most recent changes are not passing the checks, please check your code outrake

image

**Comment by TheSCREWEDSoftware** [comment]
@manstfu there you go. @Nyeriah or @Kitzunu someone to review <3

**Comment by TheSCREWEDSoftware** [comment]
For to ask @manstfu which section of the wiki requires updating and example of what needs to be added.

**Comment by manstfu** [comment]
> Forgot to ask @manstfu which section of the wiki requires updating and example of what needs to be added.

Doxygen needs `OnPlayerLeave` added in `classInstanceScript` but i think thats automatic, right?

**Review by Nyeriah — APPROVED** [review]
