### PR TITLE
fix(Core/Spell): Apply AURA_STATE_FAERIE_FIRE

### LINKED ISSUE #5702: (Spell): Razormane Thornweaver's Faerie fire does not preven't stealthing
Original report at https://github.com/chromiecraft/chromiecraft/issues/561

==================================================

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Razormane Thornweaver (https://wowgaming.altervista.org/aowow/?npc=3268) spell Faerie Fire (https://wowgaming.altervista.org/aowow/?spell=6950) does not prevent stealthing.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

With the Faerie fire befuff player should be unable to stealth.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be rogue and go to (https://wowgaming.altervista.org/aowow/?npc=3268) Razormane Thornweaver
2. Wait till they cast the spell on you
3. Go out of combat and see it's possible to stealth

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

### PR DESCRIPTION
**Pull request by Si1ker**
## Changes Proposed:
-  Apply AURA_STATE_FAERIE_FIRE on [Faerie fire](https://wowgaming.altervista.org/aowow/?spell=6950)

## Issues Addressed:

- Closes #5702
- Closes https://github.com/chromiecraft/chromiecraft/issues/561

## Tests Performed:

- Tested

image

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/game/Spells/SpellInfo.cpp [hunk 1]
```diff
@@ -2061,6 +2061,7 @@ AuraStateType SpellInfo::LoadAuraState() const
         case 9806:  // Phantom Strike
         case 35325: // Glowing Blood
         case 16498: // Faerie Fire
+        case 6950: // Faerie Fire - Razormane Thornweaver
```
Comment (Kitzunu) [inline src/server/game/Spells/SpellInfo.cpp:2064]: Comment not needed as it is the same as above.

Also this spell is used by more NPCs so "Razormane Thornweaver" not needed

Comment (Si1ker) [reply src/server/game/Spells/SpellInfo.cpp:2064]: Correct 🐱

**Review by Kitzunu — APPROVED** [review]
