### PR TITLE
fix(scripts/TempleOfAhnQiraj): Improve Princess Huhuran

### LINKED ISSUE #12746: Huhuran`s Wyvern Sting triggered damage
### Current Behaviour

Huhuran`s Wyvern Sting always dealing damage, even on expiration.
image

### Expected Blizzlike Behaviour

Damage should only take place if it was cleansed/dispelled via player action. Fixed via linked PR:
image

### Source

https://classic.wowhead.com/npc=15509/princess-huhuran#comments
https://classic.wowhead.com/guides/princess-huhuran-temple-of-ahnqiraj-strategy
https://wowwiki-archive.fandom.com/wiki/Princess_Huhuran

### Steps to reproduce the problem

Go to AQ40
Engage into Huhuran's encounter
Get "Wyvern Sting" from the boss and let it fade

### AC rev. hash/commit

c7a0fa1

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by Si1ker**
## Changes Proposed:
-  Rewrite [Princess Huhuran](https://classic.wowhead.com/npc=15509/princess-huhuran)

## Issues Addressed:

- Closes #12746

## KNOWN ISSUES AND TODO LIST:
- The SpellScript for (26180/Wyvern Sting) requires a distance check to be cast on the 10 closest targets (Players and Pets)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp [hunk 1]
```diff
@@ -15,148 +15,147 @@
...
             {
-                DoCastVictim(SPELL_POISONBOLT);
-                PoisonBolt_Timer = 3000;
+                case EVENT_FRENZY:
+                    DoCastSelf(SPELL_FRENZY, true);
+                    Talk(EMOTE_FRENZY_KILL);
+                    events.RepeatEvent(urand(25000, 35000));
+                    break;
+                case EVENT_WYVERN_STING:
+                    if (Unit* target = SelectTarget(SelectTargetMethod::MinDistance))
```
Comment (Nyeriah) [inline src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp:102]: It's an AoE spell, you will need to filter targets in the spell script so only the closest ones are selected

Comment (Si1ker) [reply src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp]: idk about ::FilterTargets based on distance so I'll leave it with limited targets to at least have the target amount right.
Open for distancePriorityCheck after merge or commit in the branch if you want to do it.

Comment (Nyeriah) [reply src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp]: This is for learning purposes only: expliciting a target to an AoE spell bears no effect because the target selector will ignore it (the spell itself has no target so we cannot specify one, it will still follow the default selector for the spell, which in our case is TARGET_UNIT_SRC_AREA_ENEMY)

**Comment by Si1ker** [comment]
if possible, have this one merged before #12749 (minimal changes on header than that one)

File: src/server/scripts/Kalimdor/TempleOfAhnQiraj/instance_temple_of_ahnqiraj.cpp [hunk 2]
```diff
@@ -108,7 +100,6 @@ class instance_temple_of_ahnqiraj : public InstanceMapScript
                         creature->Respawn();
                     break;
             }
-
```
Comment (Nefertumm) [inline src/server/scripts/Kalimdor/TempleOfAhnQiraj/instance_temple_of_ahnqiraj.cpp:111]: Do not remove this space here.

File: src/server/scripts/Kalimdor/TempleOfAhnQiraj/instance_temple_of_ahnqiraj.cpp [hunk 3]
```diff
@@ -54,27 +47,23 @@ class instance_temple_of_ahnqiraj : public InstanceMapScript
         //If Vem is dead...
         bool IsBossDied[3];
 
-        //Storing Skeram, Vem and Kri.
         ObjectGuid SkeramGUID;
         ObjectGuid VemGUID;
         ObjectGuid KriGUID;
         ObjectGuid YaujGUID;
+        ObjectGuid HuhuranGUID;
```
Comment (Nefertumm) [inline src/server/scripts/Kalimdor/TempleOfAhnQiraj/instance_temple_of_ahnqiraj.cpp:54]: Why is this added? It's not used anywhere (with the code below)

File: src/server/scripts/Kalimdor/TempleOfAhnQiraj/instance_temple_of_ahnqiraj.cpp [hunk 4]
```diff
@@ -164,19 +156,20 @@ class instance_temple_of_ahnqiraj : public InstanceMapScript
             {
                 case DATA_BUG_TRIO_DEATH:
                     if (data != 0)
+                    {
```
Comment (Nefertumm) [inline src/server/scripts/Kalimdor/TempleOfAhnQiraj/instance_temple_of_ahnqiraj.cpp:159]: Don't add unnecessary brackets.

File: src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp [hunk 5]
```diff
@@ -15,148 +15,144 @@
...
-        {
-            me->InterruptNonMeleeSpells(false);
-            Talk(EMOTE_BERSERK);
-            DoCast(me, SPELL_BERSERK);
-            Berserk = true;
-        }
-
         DoMeleeAttackIfReady();
     }
+    private:
```
Comment (Nefertumm) [inline src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp:132]: I'd rather use protected instead of private, but that's more of a personal choice (in this case).

File: src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp [hunk 6]
```diff
@@ -15,148 +15,144 @@
...
+        bool berserk;
+        bool hardEnrage;
```
Comment (Nefertumm) [inline src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp:134]: Classes attributes marked as protected or private should be declared as _variableName.

File: src/server/scripts/Kalimdor/TempleOfAhnQiraj/temple_of_ahnqiraj.h [hunk 7]
```diff
@@ -39,6 +39,7 @@ enum DataTypes
     DATA_OURO               = 13,
     DATA_OURO_SPAWNER       = 14,
     DATA_BUG_TRIO_DEATH     = 15,
+    DATA_HUHURAN            = 16,
```
Comment (Nefertumm) [inline src/server/scripts/Kalimdor/TempleOfAhnQiraj/temple_of_ahnqiraj.h:42]: Define this one below all of them, it will be changed by my pr after all (to minimize merge conflicts)

File: src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp [hunk 8]
```diff
@@ -15,148 +15,144 @@
...
-        if (Wyvern_Timer <= diff)
-        {
-            DoCastAOE(SPELL_WYVERNSTING);
-            Wyvern_Timer = urand(15000, 32000);
-        }
-        else Wyvern_Timer -= diff;
+    void JustDied(Unit* /*killer*/) override
+    {
+        _JustDied();
+    }
```
Comment (Nefertumm) [inline src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp:74]: Remove this, already done by BossAI::JustDied by default.

**Review by Nefertumm — CHANGES_REQUESTED** [review]

File: src/server/scripts/Kalimdor/TempleOfAhnQiraj/instance_temple_of_ahnqiraj.cpp (hunk 3 above)
Comment (Si1ker) [reply src/server/scripts/Kalimdor/TempleOfAhnQiraj/instance_temple_of_ahnqiraj.cpp:54]: @Nefertumm boss_huhuran(Creature* creature) : BossAI(creature, DATA_HUHURAN) { }

:'v

Comment (Nefertumm) [reply src/server/scripts/Kalimdor/TempleOfAhnQiraj/instance_temple_of_ahnqiraj.cpp:54]: In that case, it's not needed

File: src/server/scripts/Kalimdor/TempleOfAhnQiraj/instance_temple_of_ahnqiraj.cpp (hunk 4 above)
Comment (Si1ker) [reply src/server/scripts/Kalimdor/TempleOfAhnQiraj/instance_temple_of_ahnqiraj.cpp:159]: ok

File: src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp (hunk 5 above)
Comment (Si1ker) [reply src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp:132]: skip then.

File: src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp (hunk 6 above)
Comment (Si1ker) [reply src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp:134]: ok

File: src/server/scripts/Kalimdor/TempleOfAhnQiraj/temple_of_ahnqiraj.h (hunk 7 above)
Comment (Si1ker) [reply src/server/scripts/Kalimdor/TempleOfAhnQiraj/temple_of_ahnqiraj.h:42]: sure

File: src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp (hunk 8 above)
Comment (Si1ker) [reply src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp:74]: good to know, ok

File: src/server/scripts/Kalimdor/TempleOfAhnQiraj/instance_temple_of_ahnqiraj.cpp (hunk 2 above)
Comment (Si1ker) [reply src/server/scripts/Kalimdor/TempleOfAhnQiraj/instance_temple_of_ahnqiraj.cpp:111]: idk why but ok

File: src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp [hunk 9]
```diff
@@ -15,148 +15,139 @@
...
+                    break;
+                case EVENT_ACID_SPIT:
+                    DoCastVictim(SPELL_ACID_SPIT);
+                    events.RepeatEvent(urand(5000, 10000));
+                    break;
+                case EVENT_NOXIOUS_POISON:
+                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 100, true))
+                    {
+                        DoCast(target, SPELL_NOXIOUS_POISON);
+                    }
```
Comment (Nefertumm) [inline src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp:108]:
```suggestion
                    DoCastRandomTarget(SPELL_NOXIOUS_POISON, 0, 100);
```
I forgot about this :)

**Review by Nefertumm — APPROVED** [review]

File: src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp (hunk 9 above)
Comment (Si1ker) [reply src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp]: oh sh!t, that's some good stuff

**Comment by Si1ker** [comment]
any merge enjoyer? :u

**Review by Nyeriah — APPROVED** [review]

File: src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp [hunk 10]
```diff
@@ -15,148 +15,136 @@
...
-        //Spit Timer
-        if (Spit_Timer <= diff)
+    void DamageTaken(Unit*, uint32& /*damage*/, DamageEffectType, SpellSchoolMask) override
+    {
+        if (!_berserk && HealthBelowPct(30))
         {
-            DoCastVictim(SPELL_ACIDSPIT);
-            Spit_Timer = urand(5000, 10000);
+            DoCastSelf(SPELL_BERSERK, true);
+            Talk(EMOTE_BERSERK);
```
Comment (Kitzunu) [inline src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp:76]: Use TextEmote() instead

**Comment by Si1ker** [comment]
@Nefertumm @Nyeriah merge?

**Comment by Nyeriah** [comment]
Très bien
