### PR TITLE
fix(Core/Vehicles): Prevent accessory double-install and respawn orphans

### LINKED ISSUE #25475: [NPC] - "Onslaught Knight" [27206] doesn't properly clean up after losing it's mount and/or respawning
### Triage

Issue linked from CC: https://github.com/chromiecraft/chromiecraft/issues/9295

Triage Notes: 

https://wowgaming.altervista.org/aowow/?npc=27206

Source: https://www.youtube.com/watch?v=8LynyEzvaGA from MOP testing

MOP Behaviour:
If the rider dies, horse stops and dispawn after abit.
If the mount dies, rider will fight you, if you reset him (leash/aggro range) they just dispawn)

- `.gm on`
- `.go xyz 2540 -475 1 571`
- Find any `Warhorse` (the easiest to test this) kill them and leave the rider alive.
- `.respawn all`

Repeat the above until you see the result as you wish 

Image

Image

Image

The moment the rider looses their mount, they become a temp spawn with a respawn timer.

Image

Image

Original Post Below: 

---

### Current Behaviour

Onslaught knights are spawning in 1x1, but not despawning, leading to +++ Mob stacks, **Edit** with a bonus 10,000~ mobs

### Expected Behaviour

onslaught knights patrol in, and cap out at the 1-mob per spawn point

### Source

~

### Steps to reproduce the problem

Go to New Hearthglen, in Dragonblight

### Extra Notes

_No response_

### Customizations

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/db2e1325d22324f346272d76177c0c0b38566e20

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-chromiecraft-smartstone](https://github.com/chromiecraft/mod-chromiecraft-smartstone)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-evade-logging](https://github.com/heyitsbench/mod-evade-logging)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-quests](https://github.com/azerothcore/mod-pvp-quests)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-resurrection-scroll](https://github.com/azerothcore/mod-resurrection-scroll)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by blinkysc**
## Changes Proposed:
Collapses the vehicle accessory install path so `Vehicle::Reset()` no longer fires twice during a single spawn. The second Reset previously called `RemoveAllPassengers()`, ejecting the just-seated accessory and firing a spurious `SMART_EVENT_PASSENGER_REMOVED` on the base vehicle. Any SAI reacting to that event (e.g. `Onslaught Warhorse`/`Onslaught Knight` at New Hearthglen) entered its dismounted state at spawn, producing orphaned accessories that accumulated on every respawn.

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

### Context

Two paths were calling `Vehicle::Reset()` during a single spawn:

1. `Creature::AIM_Initialize` — pre-visibility, guarded on `m_spawnId` (DB creatures only).
2. `Map::AddToMap` — post-visibility, unconditional.

The second Reset ran `InstallAllAccessories` → `RemoveAllPassengers`, which ejected the accessory seated by the first Reset, then re-summoned a fresh one. The eject fired a spurious `SMART_EVENT_PASSENGER_REMOVED`. Warhorse SAI reacts to that event by entering its dismounted state (faction 35, pacified, 30s despawn), which then leaves a friendly/pacified vehicle with an orphaned accessory and despawns the Warhorse — but the accessory is `minion=0` in `vehicle_template_accessory`, so it survives and wanders. The `.respawn all` GM tool compounded this by resurrecting dead accessory `TempSummon` corpses as orphans.

### Fix

- Drop the pre-visibility Reset in `Creature::AIM_Initialize`. Accessories now seat only post-visibility, matching Xinef's original comment intent ("accessories have to be added after visibility update so they won't fall off the vehicle").
- Add `_accessoriesInstalled` flag on `Vehicle`. On subsequent non-evade Resets (e.g. compat-mode Update-tick Reset), `RemoveAllPassengers` is skipped; `InstallAccessory` is already idempotent for same-entry seats, so the re-Reset becomes a no-op instead of ejecting and re-summoning. Flag is set **before** the no-accessories early return so it also protects vehicles without accessory entries (WG demolisher / catapult) from re-eviction on subsequent Resets.
- Seat accessories from `GridObjectLoader::LoadCreatures` since grid load bypasses `Map::AddToMap` and would otherwise leave grid-loaded vehicles (Onslaught Warhorses on server startup) without their accessories.
- In `Creature::Respawn`, skip the resurrection branch for `TempSummon` corpses (no `m_spawnId`, not forced). `TempSummon::Update` UnSummons them naturally on the next tick once `deathState` reaches `Dead`. Script-driven `Respawn(true)` still proceeds.

### Why this avoids PR #25486's crash

PR #25486 (which was reverted in #25491) tried to solve the same double-install by deferring Reset to the next `Creature::Update` tick. That opened a window where scripts could `SummonCreature(vehicle)` and immediately seat a real passenger (e.g. Professor Putricide mutated monstrosity with `VEHICLE_SPELL_RIDE_HARDCODED`); the deferred Reset then called `RemoveAllPassengers` and ejected that real passenger.

This fix keeps the post-visibility Reset **synchronous** inside `Map::AddToMap`, so accessories are seated before control returns to any summoning script — no deferred window for real passengers to be ejected.

### AI-assisted Pull Requests

- [x] AI tools (e.g. ChatGPT, Claude, or similar) were used entirely or partially in preparing this pull request. Please specify which tools were used, if any.

Claude Code with azerothMCP was used for investigation, reproduction analysis, TrinityCore comparison, and drafting the patch. All changes were reviewed and tested by the author.

## Issues Addressed:
- Closes #25475

## SOURCE:
The changes have been validated through:
- [x] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

Behaviour compared against TrinityCore: TC's `AIM_Initialize` runs `Reset()` unconditionally pre-visibility and relies on an Update-tick Reset only in compat mode; TC has no post-visibility Reset. AzerothCore's visibility/summon order differs from TC (Xinef's original comment in `Map::AddToMap` documented this). This fix keeps AC's post-visibility model and makes it single-install, rather than adopting TC's pre-visibility model wholesale.

## Tests Performed:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [x] This pull request requires further testing and may have edge cases to be tested.

Vehicle creation paths audited to ensure `Reset()` still fires exactly once per spawn:
- `LoadCreatureFromDB(addToMap=true)` → `Map::AddToMap` (ObjectMgr, PoolMgr, GameEventMgr, respawn)
- `GridObjectLoader::LoadCreatures` (server startup / grid activation) — handled explicitly
- `MotionTransport::CreateNPCPassenger` → `Map::AddToMap` (ICC gunship cannons)
- `Map::SummonCreature` → `Map::AddToMap` (scripted summons, Flame Leviathan, Putricide)
- `Battleground::AddCreature` → `Map::AddToMap` (SotA demolishers, IoC siege)
- `Battlefield::SpawnCreature` → `Map::AddToMap` (Wintergrasp)

Given this change affects every vehicle in the game, further regression testing on other vehicle content is strongly recommended, especially:
- Ulduar (Flame Leviathan and its accessories, Siege Engine / Chopper / Demolisher quest vehicles)
- Icecrown Citadel (Gunship cannons, Professor Putricide mutated monstrosity)
- Mount-with-accessory quests across zones
- Strand of the Ancients / Isle of Conquest / Wintergrasp vehicles

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

### Onslaught Warhorse/Knight (primary repro — `#25475`)

1. `.gm on`
2. `.go xyz 2540 -475 1 571`  (New Hearthglen, Dragonblight)
3. Verify every Warhorse spawn has **exactly one** Knight seated and both are hostile (red nameplates) on a fresh server start.
4. Kill the Warhorse. The Knight exits, stays alive, attacks you (MoP-correct).
5. Kill the Knight. The Warhorse goes into dismounted state (faction 35, pacified) and despawns after 30s.
6. Run `.respawn all` a few times. Verify no orphaned Knights accumulate — each new Warhorse spawn has exactly one seated Knight.

### Wintergrasp vehicles (regression for `_accessoriesInstalled` flag position)

Vehicles without entries in `vehicle_template_accessory` (WG demolisher/catapult) would previously hit the no-accessories early return before the flag was set, causing the driver to be ejected by the compat-mode Update-tick Reset. Test:

1. `.cast 55629`  (grants `SPELL_LIEUTENANT` — bypasses the WG script rank check)
2. `.npc tempadd 27881`  (Catapult, no accessories)
3. `.npc tempadd 28094`  (Demolisher, no accessories)
4. `.npc tempadd 28312`  (Siege Engine, has Turret accessory 28319)
5. Right-click each to mount. Verify you stay seated; the siege engine's turret seat is also occupied by its NPC accessory.

### Summoned-vehicle regression (the crash case from #25486 revert)

1. Pull Professor Putricide in ICC to phase 3. The player that drinks the mutated plague should be transformed into the mutated monstrosity vehicle and retain the ability to cast abilities without being immediately ejected.
2. Alternative quick check: any quest that summons a vehicle and immediately seats the player (Argent Tournament jousting mounts, etc.).

### Grid-load regression (server-start vehicles)

1. Restart worldserver.
2. Before triggering any respawns, approach a grid-loaded vehicle with accessories (Onslaught Warhorse spawnId 102719 is easiest). Accessory should be seated on first sight.

## Known Issues and TODO List:

- [ ]
- [ ]

### CODE REVIEW

**Comment by blinkysc** [comment]
I'm going to be testing this more with vehicles before I set this for review. Super tired atm lol

File: src/server/game/Entities/Vehicle/Vehicle.cpp [hunk 1]
```diff
@@ -97,6 +101,8 @@ void Vehicle::InstallAllAccessories(bool evading)
     for (VehicleAccessoryList::const_iterator itr = accessories->begin(); itr != accessories->end(); ++itr)
         if (!evading || itr->IsMinion)  // only install minions on evade mode
             InstallAccessory(itr->AccessoryEntry, itr->SeatId, itr->IsMinion, itr->SummonedType, itr->SummonTime);
+
+    _accessoriesInstalled = true;
```
Comment (NoxMax) [inline src/server/game/Entities/Vehicle/Vehicle.cpp]: Because of where `_accessoriesInstalled = true;` is, in WG, the siege engine summon now works correctly, but the demolisher and catapult (which don't have an accessory vehicle) still cause driver eviction on summon.

**Comment by NoxMax** [comment]
Did many tests in Wintergrasp. Everything works as expected for all vehicles.

**Review by Nyeriah — APPROVED** [review]
