### PR TITLE
fix(DB/Gameobjects): Fixed one spawn position of Stranglekelp.

### LINKED ISSUE #11397: Stranglekelp (13.9,13.3) from Stranglethorn Vale not obtainable
Originally Reported: https://github.com/chromiecraft/chromiecraft/issues/3191

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The herb is invisible or under the ground, doing it impossible to grab.

### Expected Blizzlike Behaviour

The herb should be visible and grabbable

### Source

_No response_

### Steps to reproduce the problem

I went to coordinates (13.9,13.3) from STV and i tried to gather the Stranglekelp tracked at the minimap
Was not possible

### Extra Notes

https://wowgaming.altervista.org/aowow/?object=2045

WoWScrnShot_041322_211450
When I used `.go xyz` to go to the coordinates it resulted in this:
WoWScrnShot_041322_212113

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0e35b681fb74045953b0babae5273f121dcaa05f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #11397

## Issues Addressed:

- Closes #11397
- Closes https://github.com/chromiecraft/chromiecraft/issues/3191

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.go gameobject 11646`

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1678626418501365600.sql [hunk 1]
```diff
@@ -0,0 +1,2 @@
+--
+UPDATE `gameobject` SET `position_z`=-4.33 WHERE `guid`=11646;
```
Comment (Gultask) [inline data/sql/updates/pending_db_world/rev_1678626418501365600.sql:2]:
```suggestion
UPDATE `gameobject` SET `position_z`=-4.33 WHERE `guid`=11646 AND `id`=2045;
```

Comment (IntelligentQuantum) [reply data/sql/updates/pending_db_world/rev_1678626418501365600.sql:2]: isn't guid unique?

**Review by Gultask — APPROVED** [review]
