### PR TITLE
fix(scripts/ZulGurub): Rewrite Broodlord Mandokir and Ohgan

### LINKED ISSUE #11745: [ZG] Bloodlord Mandokir - Ohgan - Missing Thrash
### Current Behaviour

Ohgan is missing the spell Thrash.

### Expected Blizzlike Behaviour

Ohgan should cast Thrash occasionally.
From what I've observed it's around every 14-22s

### Source

https://user-images.githubusercontent.com/100873791/168452533-cc76e90e-34f0-4416-a7e9-ba4f9fe04792.mp4

At around 0:14 and 0:27

https://user-images.githubusercontent.com/100873791/168452758-a129eb2f-627b-41ce-94fe-ab1350ae4dc6.mp4

At around 0:46

https://youtu.be/UKhgKKN4teU?t=30 First one at 0:36

I've also seen another video showcasing a 20s delay between Thrash, but again, like the last issue, I've lost the link to it. I'll make sure that doesn't happen again, sorry.

### Steps to reproduce the problem

1. `.go xyz -12212 -1959 133 309`
2. Kill the Vilebranch Speaker and start the encounter.
3. Notice that Ohgan does not cast Thrash.

### Extra Notes

Thrash (ID: 3391)

Also, it's not worth making another issue for this but I've observed in several videos that the timer for Sunder Armor (ID: 24317) is 6-12s while in AC it's 10-15s

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/5474b00a3d4f75245068535c26fa44c70f7ca6b4

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### LINKED ISSUE #11746: [ZG] Bloodlord Mandokir - Chained Spirits not resurrecting dead players
### Current Behaviour

~~The Chained Spirits have no AI.~~ fixed by #11854

 - Chained Spirits are chosen seemingly randomly to resurrect a player.
 - Missing resurrection timer between Revives.

### Expected Blizzlike Behaviour

When a player dies, the **closest** Chained Spirit immediately goes to their body and casts Revive (ID: 24341) on them, then the Chained Spirit disappears until combat ends and the boss resets. They do not respawn mid-fight.

There is a ~~1:30~~ 100s timer before the player is allowed to accept the revive, and the "Accept" button is grayed out while the timer is ongoing.
Edit: I think the word cooldown works better here. Sorry for not explaining it correctly.
There cannot be 2 consecutive revives within 100 seconds of each other.

### Source

https://youtu.be/PdvZirl8vls?t=85
https://youtu.be/PdvZirl8vls?t=118 and 7 seconds after that timestamp

Timer:
https://youtu.be/BCfUnfSpDmM?t=315
https://youtu.be/BCfUnfSpDmM?t=416

### Steps to reproduce the problem

1. Create 2 or more characters and add them to a group. Make one easily killable.
2. `.go xyz -12212 -1959 133 309`
3. Kill the Vilebranch Speaker and start the encounter.
4. Let one character die and see that the Chained Spirits do not do anything.

### Extra Notes

Chained Spirit (ID: 15117)
Revive (ID: 24341)

It seems to be a Blizz-like bug in TBC that if a priest with Spirit of Redemption talent dies, then the Chained Spirit does not resurrect them. Proof:
https://www.wowhead.com/npc=11382/bloodlord-mandokir#comments:id=317157
I also had a video showcasing the bug but I lost the link to it, sorry.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/5474b00a3d4f75245068535c26fa44c70f7ca6b4

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### LINKED ISSUE #11747: [ZG] Bloodlord Mandokir - Various issues with melee physical spells
### Current Behaviour

Overpower is not being cast.
~~Mortal Strike is only being used when the main target is below 50% health~~ Fixed by #11854

### Expected Blizzlike Behaviour

Overpower is only used if the main target dodges. It seems to have an internal cooldown of about 6-8s
Mortal Strike can be used whenever within a timer, and the target does not need to be below 50% HP.
Cleave is cast when a certain number of people are near or in front of Mandokir. May need more research to determine conditions for the cast.

### Source

https://youtu.be/XNm7HWagRKs?t=47
shows MS being cast while player has >50% HP and OP being cast only after a dodge, with a short cooldown.

### Steps to reproduce the problem

1. `.go xyz -12212 -1959 133 309`
2. Kill the Vilebranch Speaker and start the encounter.

### Extra Notes

Bloodlord Mandokir (ID: 11382)
Mortal Strike (ID: 16856)
Overpower (ID: 24407)

~~There are some written sources that indicate that a Cleave spell is cast but I've not seen it in video and it is missing in most, if not all, WoW Classic guides.~~ Silker found video evidence from Vanilla and the ID from another core.

My observed timers are:
Mortal Strike 14-28s
Overpower 6-8s Cooldown

In written guides I've seen the existence of a 'Execute' Spell existing, but I've found no good footage of it yet
>Ability  [Execute](https://www.wowhead.com/?spell=7160) — Used when Mandokir's current target falls below 20% health. Deals approximately 5000 physical damage. ([source](https://wowpedia.fandom.com/wiki/Bloodlord_Mandokir_(Classic)))

Execute (ID: 7160)
I contest the existence of Execute until I find a good source, since most attacks when the target is below 20% HP would kill them anyway.
https://youtu.be/BCfUnfSpDmM?t=210 shows normal attack damage for the killing blow
https://youtu.be/PdvZirl8vls?t=85 so does this one.

The only semi-source I found was a comment in a WoW Classic video that was the RL and MT mentioning that Mandokir "hit me for 5k once."

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/5474b00a3d4f75245068535c26fa44c70f7ca6b4

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### LINKED ISSUE #11748: [ZG] Bloodlord Mandokir - Threatening Gaze
### Current Behaviour

Boss casts Threatening Gaze.

~~The debuff has no effect. Nothing happens.~~ fixed by #11854

 - Boss cannot attack while casting.

 - Upon an action the boss charges immediately rather than after the debuff runs out.

 - ~~Charge movement is wonky. Player can move while the boss is charging.~~ Blizzlike ([proof](https://www.youtube.com/watch?v=28EhZvGtf0s))

 - If player is more than 10y away from the boss, Guillotine is not cast.

 - Some spells that do not generate threat are triggering the charge, like using Hearthstone.

Edit, new bugs:

 - Auto-attacks aren't triggering the charge.

 - If the Charge is triggered while the boss is casting Whirlwind, the cast is not cancelled. The charge effects occur but he does not move. I don't know the blizzlike method but this doesn't seem right.

### Expected Blizzlike Behaviour

Boss should cast Threatening Gaze at a random player.

Boss can attack while casting Threatening Gaze.

**After the debuff runs out**, if the player affected did any actions that generate threat and are not movement, HoT ticks or DoT ticks, Mandokir will cast a Charge spell followed by Guillotine, and then return to the main target. I do not know what effects spells such as Feign Death and Vanish have in this mechanic.

Threatening Gaze can be broken by Line of Sight or if there's not a clear path to the target.

### Source

https://user-images.githubusercontent.com/100873791/168453776-9f1a40c1-50e6-4a7d-9c70-10ab3eea9744.mp4

Boss can attack while casting: https://youtu.be/WyaERCgkJBU?t=66

Threatening Gaze Charge can be LoS'd or avoided:
https://youtu.be/PLHmWYmHieg?t=133
https://youtu.be/yQIhi37rlXM?t=69 afterwards the Threatening Gaze does not affect the player
Many times throughout https://youtu.be/R7oje40mu0Q?t=1389 
https://youtu.be/FcFWZJLlLZA?t=52
https://www.youtube.com/watch?v=ltXE4QGeYpU this strategy was famous for a reason, same thing with the 'spear wall' strategy that was broken in following patches after the maps changed.

Threatening Gaze:
[From Wowhead comments](https://tbc.wowhead.com/npc=11382/bloodlord-mandokir#comments:id=2826633):
>If you are being watched you must stop anything that causes aggro; meaning: Healing, debuffing, buffing, potion drinking, bandaging, dealing damage and cleasing. You may move, you may jump, you may pull additional adds (not recommended though) and I think you even may heartstone out.

DoT ticks, HoT ticks and Totems ticks do not count as an action: https://youtu.be/QsC_Xwas01s?t=30

### Steps to reproduce the problem

1. `.go xyz -12212 -1959 133 309`
2. Kill the Vilebranch Speaker and start the encounter.

### Extra Notes

Bloodlord Mandokir (ID: 11382)
Threating Gaze (ID: 24314)
Threating Gaze - Charge (ID: 24315)
Threating Gaze - Guillotine (ID: 24316)

From what I've observed in several videos, the timers seem to be 12-24s for Threatening Gaze.

If the player uses `.learn 24315` and casts it, it seems that it deals damage if the target is close enough.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/5474b00a3d4f75245068535c26fa44c70f7ca6b4

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### LINKED ISSUE #11749: [ZG] Bloodlord Mandokir - Charge, Shout & Threat Wipe
### Current Behaviour

~~Charge is not followed by Intimidating Shout.~~
~~This mechanic does not wipe the tank's threat.~~
Both fixed by #11854

 - The Boss charges a random player.

 - Boss can cast mid-charge (see video in extra notes).

 - Sometimes will not Shout after a Charge (I've also seen him do a Charge -> Whirlwind -> Shout, when the Shout should come immediately after the Charge)

 - Shout is placing 2 auras on the player 19134 and 29544

### Expected Blizzlike Behaviour

The Boss first charges the target farthest away from him for the first charge, and the switches target if possible (probably to the second furthest target). Possibly inconsistent, but comments seem to confirm.

Edit: If there is no other player (like in a solo situation) then he will charge the same player.

After charging, the Boss casts Intimidating Shout and wipes the threat from his main target.

### Source

https://user-images.githubusercontent.com/100873791/168453800-d790aa87-2ca3-4047-95b9-26ec4aa94e5a.mp4

[From Wowhead comments](https://tbc.wowhead.com/npc=11382/bloodlord-mandokir#comments:id=2826633):
>After the boss has charge that person, which is always the one furtest away from him

[From Wowpedia Talk Page](https://wowpedia.fandom.com/wiki/Talk:Bloodlord_Mandokir_(Classic)):
>Does the paladin dummy tactic work still? Mandokir seems to charge the raid at random now.

>Our pally "dummy" or punt pally was getting the initial charge but after one charge, Mandokir would charge a second raider in the group area.

https://youtu.be/-SDNeAQOHJY?t=41 notice that he charges the player farthest away from him, singled out from the rest of the raid. This can be seen in several videos.

Threat Wipe:

>This fight is about managing aggro, when it comes down to it. Seperate from the way he watches people, he'll occasionally charge random people. This charge reduces his aggro on the MT, so the situation we often had was that he'd charge, then make a beeline straight to a mage or a hunter and one-shot them. ([source](https://tbc.wowhead.com/npc=11382/bloodlord-mandokir#comments:id=2826602))

>The main issue in fighting this boss is getting the aggro back on the MT as quickly as possible after he charges. He seems to charge randomly, but in actuality, he charges anyone who is singled out away from the group and DPSing. Thusly, the easiest way to control him is to deliberately give him someone to single out, while the rest of the group huddles. Hunters work well, as they can Feign Death to aid in the MT's recovery of Mandokir. After Mandokir charges, he will move on the next highest aggro, which is not the MT since he partially dumps the threat associated with the highest aggro producer prior to the charge. ([source](https://wowpedia.fandom.com/wiki/Bloodlord_Mandokir_(Classic)?oldid=2287881#Controlling_Mandokir))

https://youtu.be/-SDNeAQOHJY?t=41 
https://youtu.be/yQIhi37rlXM?t=69
https://youtu.be/mEURNWfXusk?t=109
https://youtu.be/AGg9eJXz_vA?t=119
https://youtu.be/qTO85ph8MnM?t=41
https://youtu.be/qTO85ph8MnM?t=70
https://youtu.be/-X5w9olgqAg?t=55

### Steps to reproduce the problem

1. Create at least 2 characters and put them in a group.
2. `.go xyz -12212 -1959 133 309`
3. Kill the Vilebranch Speaker and start the encounter.
4. Place one target closer to Mandokir and the other far from him.

### Extra Notes

https://user-images.githubusercontent.com/100873791/170794452-bbccb694-73a9-4ade-af0e-51ce10a1478c.mp4

Bloodlord Mandokir (ID: 11382)
Charge (ID: 24408)
Intimidating Shout (ID: 19134)

From what I've observed, he seems to charge every 30-40s

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/5474b00a3d4f75245068535c26fa44c70f7ca6b4

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### LINKED ISSUE #11864: [ZG] Bloodlord Mandokir - Issue with reset.
### Current Behaviour

If the raid wipes, and releases spirit, they won't be able to return to the instance, receiving the "Unable to zone in while an encounter is in progress."

If zoned back in, it seems that Mandokir "queues up" his scheduled spells, casting them several times over.

### Expected Blizzlike Behaviour

Proper reset

### Source

_No response_

### Steps to reproduce the problem

1. Use 2 characters to form a raid group
2. .go c 49288
3. Kill the Vilebranch Speaker and start combat
4. Die
5. attempt to return to the instance

### Extra Notes

The encounter can only start when you kill the Vilebranch Speaker (ID: 11391), I think this might be related to the problem.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/a4af1136856604e836a4ed6d9f8a65fbca9357bc

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by Si1ker**
Pull Request by [sílker](https://www.chromiecraft.com/en/armory/?character/ChromieCraft/s%C3%ADlker)

## Changes Proposed:
- Adjust init/cd timer for Sunderer Armor for Ohgan
- Add thrash ability for Ohgan
- Try to fix Overpower spell conditional for Mandokir
- Adjust timers for Mandokir on overpower and mortal strike
- Remove non-blizzlike condition (<50%hp) for mortal strike
- Add execute mechanic on (<20%hp)
- Add aggro wipe on charge mechanic and adjust chained spirit's speed_run | https://youtu.be/lwQWch4YUgE?t=255
- Remove unused fear spell 29321
- Add correct spell for aoe fear (Frightening Shout = 19134)
- Link fear after charge
- Adjust the timer for [Threatening Gaze]
- Adjust timer for charge
- Add Cleave ability
- Implement a check for Cleave
- Fix boss reset
- Script "chained spirits"
- Partially fix the 'Threatening Gaze mechanic'

## Issues Addressed:

- Closes #11745
- Closes #11747
- Closes #11749
- Closes #11864
- Closes #11746
- Closes #11748

## SOURCE:

Check the linked issue's description

## Tests Performed:

- Tested locally with multiple accounts

## How to Test the Changes:

1. Go ZG and engage in this encounter
2. Check and compare timers

## Known Issues and TODO List:

**1- Overpower is inconsistent: Spell seems faulty in order to check dodges on target**
* Solution: Some way to check dodge on the victim linked to a bool under UpdateAI to cast it on each dodge.

**2- Revive from chained spells should have a quick timer due to "diminishing return"**
The first time appears with no CD, the second may appear with no CD or with a quick CD, the third one and beyond appear with 2-5 seconds of CDs. (based on videos)
* Solution: Mod spell attribute on cast or pre-cast, probably.

**3- Guillotine after Charge proc'ed via Threatening Gaze**
It works as intended when targets are <10yrds, however if the target is at 20-40+, boss will only Charge ifWithinLOS and will skip guillotine as the proc is only right after the charge begins & within 10yrds.
* Solution: Some way of check final destination after Charge proc'ed via Threatening Gaze and then cast Guillotine on the same target.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Si1ker** [comment]
@Gultask please test now with the latest changes.

**Comment by Gultask** [comment]
Ok. I haven't seen any more 7-hit combo Thrash 👍 
But, for some reason the timer is a bit wonky. Most of the time it works fine, but sometimes Ohgan will do 2 Thrash consecutively or will take 30s until it does another one.

**Comment by Si1ker** [comment]
> Ok. I haven't seen any more 7-hit combo Thrash, only the 2-hit correct ones 👍 But, for some reason the timer is a bit wonky. Most of the time it works fine, but sometimes Ohgan will do 2 Thrash consecutively or will take 30s until it does another one.

I know that proc spells like this, are the blizzlike way to handle effects like thrash (or trinkets in characters), for the CD, I'd call it luck at this point. Same happens with Anub'Rekhan in Naxxramas, it has a thrash ability and you can get unlucky.

**Comment by Si1ker** [comment]
Execute's sources

image

First comment = https://classic.wowhead.com/npc=11382/bloodlord-mandokir#comments;mode:n
https://wowpedia.fandom.com/wiki/Bloodlord_Mandokir_(Classic)

**Comment by Si1ker** [comment]
Overpower may need a check besides the spell.

Here's some info on similar cases but don't know how to implement it.

https://github.com/azerothcore/azerothcore-wotlk/blob/55720eedd3cfe2485faf84c1eba47c72ffcaaa0e/src/server/game/Spells/Spell.cpp#L2699

https://github.com/azerothcore/azerothcore-wotlk/blob/55720eedd3cfe2485faf84c1eba47c72ffcaaa0e/src/server/game/Spells/Spell.cpp#L2703

https://github.com/azerothcore/azerothcore-wotlk/blob/75439773d0dd3f6f71ab321e03d2a05a14df31f0/src/server/game/Spells/SpellMgr.cpp#L883

https://github.com/azerothcore/azerothcore-wotlk/blob/825d4f91479a488894289d47a5a64f493da08a04/src/server/scripts/Spells/spell_dk.cpp#L696

**Comment by Gultask** [comment]
@Si1ker the Charge & Threat Wipe mechanics are this issue: https://github.com/azerothcore/azerothcore-wotlk/issues/11749
Could you add the "Closes part of" and link to it?

**Comment by Si1ker** [comment]
@Gultask it actually closes the full issue.

AOE fear is separate from the Charge, I've seen videos where AOE fear is cast regardless of charge, let me know if you want them in order to look for them again.

**Comment by Gultask** [comment]
There are 2 charges. One that is followed by fear and the one that is triggered by Threatening Gaze. The first one is cast on a random player and is followed by a Fear and a threat reset on the main threat holder. You can see it in nearly all WotLK-era videos, but iirc I only listed sources that had threat meters enabled. Videos outside WotLK were quite inconsistent with the threat reset.

**Comment by Si1ker** [comment]
> There are 2 charges. One that is followed by fear and the other that is triggered by Threatening Gaze. The first one is cast on a random player and is followed by a Fear and a threat reset on the main threat holder. You can see it in nearly all WotLK-era videos, but iirc I only listed sources that had threat meters enabled. Videos outside WotLK were quite inconsistent with the threat reset.

@Gultask Yep, seems the case.
image

**Comment by Si1ker** [comment]
The video from https://github.com/azerothcore/azerothcore-wotlk/issues/11749
shows the next pattern of CD for Gaze/Watch-player

watch-gaze = 12s-28s
15sec
16sec
19sec
23sec
12sec -min
16sec
12sec
13sec
12sec
28sec -max

**Comment by Si1ker** [comment]
Cleave's source at https://github.com/azerothcore/azerothcore-wotlk/issues/11747
Found [spell](https://wowgaming.altervista.org/aowow/?spell=20691) at [MaNGOS](https://github.com/mangos/ScriptDev3/blob/master/scripts/eastern_kingdoms/zulgurub/boss_mandokir.cpp#L53)
Condition for Cleave based on previous [investigation](https://github.com/azerothcore/azerothcore-wotlk/issues/11747#issuecomment-1136527921)

**Comment by Si1ker** [comment]
Everything was tested from my end so far!

**Comment by Si1ker** [comment]
> * [ ]  Cleave is hitting twice.
> 
> cleave
> 
> * [ ]  The threat wipe is adding 80-100k threat to the second in the table. We don't have confirmation that the threat wipe adds additional threat to the second highest in the threat table. What is your source on that? I have 7 videos in the issue showing how it works.

Both are resolved by now.
Working on spirits atm.

**Comment by Si1ker** [comment]
Update: The vast majority is working so far, there are a couple of exceptions explained in the PR description.
Looking to fix "Gaze-Charge-Guillotine" atm. #11748

**Comment by Si1ker** [comment]
Completed

**Comment by Gultask** [comment]
Thanks 👍 
I'll test it soon.

**Comment by Gultask** [comment]
- [ ] Threatening Gaze is causing a charge upon movement. From what I've gathered it should only cause a charge for the casting of a spell that generates threat and is not a periodic DoT/HoT

- [ ] Threatening Gaze is causing a charge immediately, rather than when the debuff wears off.

- [ ] Mandokir cannot attack or move while casting Threatening Gaze (he should)

- [ ] Threatening Gaze Charge movement seems wrong. (Target can move freely, Mandokir will charge empty space.) see video

- [ ] He is using the Shout twice or is giving the debuff twice.

- [ ] Shout will remove threat from the main threat holder only, but currently can wipe threat from all targets.

- [ ] Sometimes will not Shout after a Charge (I've also seen him do a Charge -> Whirlwind -> Shout, when the Shout should come immediately after the Charge)

- [ ] Mandokir can cast mid-charge. see video

- [ ] Chained Spirits should pick the closest one to ress the downed player, I've seen one come from the other side of the arena.

- [ ] There's no cooldown on resurrection. Where did you see 2-5s? My source has more than 1 minute of CD.

https://user-images.githubusercontent.com/100873791/170794452-bbccb694-73a9-4ade-af0e-51ce10a1478c.mp4

Also, if you got the timer for Threatening Shout from that list you posted in #Testing, then please use the one I provided in the report. I had gathered these timers from several videos: [11, 11, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 15, 16, 16, 16, 17, 18, 19, 19, 20, 20, 21, 22, 22, 23, 23, 24, 24, 25, 27, 28, 29, 37], the average being 17,6s. The minimum I chose 12, and in my logic (min + max)/2 = average so the max is ~24s.
And yes, I know this is wrong. The proper 'timer' would be probably be a chance-based roll every second, and that could be why there seems to be no upper limit and way more 13s and 14s than the others.

**Comment by Si1ker** [comment]
@Gultask 

Threatening Gaze is causing a charge upon movement. From what I've gathered it should only cause a charge for the casting of a spell that generates threat and is not a periodic DoT/HoT
 **- Changed in next commit.**

 Threatening Gaze is causing a charge immediately, rather than when the debuff wears off.
 **- Nothing I can do about it, the second reachable option is to leave it completely useless.**

 Mandokir cannot attack or move while casting Threatening Gaze (he should)
 **- Out of my knowledge.**

 Threatening Gaze Charge movement seems wrong. (Target can move freely, Mandokir will charge empty space.) see video
 **- Some mobs/charges could have that behavior, idk what causes it, really nothing I can do.**

 He is using the Shout twice or is giving the debuff twice.
 **- I think I know the issue, changed in next commit.**

 Shout will remove threat from the main threat holder only, but currently can wipe threat from all targets.
 **- Changed in next commit.**

 Sometimes will not Shout after a Charge (I've also seen him do a Charge -> Whirlwind -> Shout, when the Shout should come immediately after the Charge)
  **- Out of my knowledge. Same situation as where I couldn't figure out a way to link Charge-Guillotine for casters**

 Mandokir can cast mid-charge. see video
  **- Out of my knowledge.**

 Chained Spirits should pick the closest one to ress the downed player, I've seen one come from the other side of the arena.
  **- Out of my knowledge.**

 There's no cooldown on the resurrection. Where did you see 2-5s? My source has more than 1 minute of CD.
 **You literally just read what you wanted from #known-issues. Besides, It can be 1sec, 2-5 sec, 1minute, 100 years, still idk how to.**
 
 Also, if you got the timer for Threatening Shout from that list you posted in #Testing, then please use the one I provided...
 **- Changed in next commit.**
 
 ### Resume
This PR is offered as-is and based on what I can do to improve the boss from it's current broken state.

**Comment by Si1ker** [comment]
idk about that last error.
I can build locally ========== Build: 4 succeeded, 0 failed, 15 up-to-date, 1 skipped ==========

**Comment by Gultask** [comment]
>This PR is offered as-is and based on what I can do to improve the boss from it's current broken state.

It's ok. The boss is working much better than it was before.

Could you change the 'Closes' to 'Closes part of' for everything but the Reset and the Ohgan issues?
I'll modify the reports later and link the completed parts to this PR.

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp [hunk 1]
```diff
@@ -168,17 +188,49 @@ class boss_mandokir : public CreatureScript
...
+
+                for (std::list<Creature*>::iterator itr = creatures.begin(); itr != creatures.end(); ++itr)
+                {
+                    if (Creature* chainedSpirit = ObjectAccessor::GetCreature(*me, (*itr)->GetGUID()))
+                    {
+                        chainedSpirit->AI()->SetGUID(reviveGUID);
+                        chainedSpirit->AI()->DoAction(ACTION_REVIVE);
+                        reviveGUID.Clear();
+                    }
+                }
```
Comment (Nefertumm) [inline src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp:225]:
```suggestion
                for (Creature* chainedSpirit : creatures)
                {
                    chainedSpirit->AI()->SetGUID(reviveGUID);
                    chainedSpirit->AI()->DoAction(ACTION_REVIVE);
                    reviveGUID.Clear();
                }
```

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp [hunk 2]
```diff
@@ -232,13 +286,12 @@ class boss_mandokir : public CreatureScript
                 switch (eventId)
                 {
                     case EVENT_OVERPOWER:
-                        DoCastVictim(SPELL_OVERPOWER, true);
-                        events.ScheduleEvent(EVENT_OVERPOWER, urand(6000, 12000));
+                        DoCastVictim(SPELL_OVERPOWER, false);
```
Comment (Nefertumm) [inline src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp:289]:
```suggestion
                        DoCastVictim(SPELL_OVERPOWER);
```

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp [hunk 3]
```diff
@@ -251,31 +304,74 @@ class boss_mandokir : public CreatureScript
...
+                            std::list<Unit*> meleeRangeTargets;
+                            auto i = me->GetThreatMgr().getThreatList().begin();
+                            for (; i != me->GetThreatMgr().getThreatList().end(); ++i)
+                            {
+                                Unit* target = (*i)->getTarget();
+                                if (me->IsWithinMeleeRange(target))
+                                {
+                                    meleeRangeTargets.push_back(target);
+                                }
+                            }
```
Comment (Nefertumm) [inline src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp:349]:
```suggestion
                            for (auto& ref : me->GetThreatMgr().getThreatList())
                            {
                                Unit* target = ref->getTarget();
                                if (target && me->IsWithinMeleeRange(target))
                                {
                                    meleeRangeTargets.push_back(target);
                                }
                            }
```

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp [hunk 4]
```diff
@@ -251,31 +304,74 @@ class boss_mandokir : public CreatureScript
...
+                            std::list<Unit*, std::allocator<Unit*>>::iterator itr;
+                            for (itr = meleeRangeTargets.begin(); itr != meleeRangeTargets.end(); ++itr)
```
Comment (Nefertumm) [inline src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp:351]: What's the purpose of this loop? It doesn't do anything with itr.

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp [hunk 5]
```diff
@@ -302,11 +399,48 @@ class npc_ohgan : public CreatureScript
...
+
+                for (std::list<Creature*>::iterator itr = creatures.begin(); itr != creatures.end(); ++itr)
+                {
+                    if (Creature* chainedSpirit = ObjectAccessor::GetCreature(*me, (*itr)->GetGUID()))
+                    {
+                        chainedSpirit->AI()->SetGUID(reviveGUID);
+                        chainedSpirit->AI()->DoAction(ACTION_REVIVE);
+                        reviveGUID.Clear();
+                    }
+                }
```
Comment (Nefertumm) [inline src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp:435]:
```suggestion
                for (Creature* chainedSpirit : creatures)
                {
                    chainedSpirit->AI()->SetGUID(reviveGUID);
                    chainedSpirit->AI()->DoAction(ACTION_REVIVE);
                    reviveGUID.Clear();
                }
```

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp [hunk 6]
```diff
@@ -302,11 +399,48 @@ class npc_ohgan : public CreatureScript
 
         void Reset() override
         {
-            SunderArmor_Timer = 5000;
+            SunderArmor_Timer = urand(6000, 12000);
```
Comment (Nefertumm) [inline src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp:402]: No, this is old. Use either TaskScheduler or EventMap.

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp [hunk 7]
```diff
@@ -339,6 +474,85 @@ class npc_ohgan : public CreatureScript
     }
 };
 
+class npc_chained_spirit : public CreatureScript
+{
+public:
+    npc_chained_spirit() : CreatureScript("npc_chained_spirit") { }
```
Comment (Nefertumm) [inline src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp:480]: Change this to the newer system. Define only the ScriptedAI and then, in AddSC_boss_mandokir, use RegisterCreatureScript(npc_chained_spirit);

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp [hunk 8]
```diff
@@ -339,6 +474,85 @@ class npc_ohgan : public CreatureScript
...
+        void SetGUID(ObjectGuid const guid, int32 /*id*/) override
+        {
+            revivePlayerGUID = guid;
+        }
+
+        void DoAction(int32 action) override
+        {
+            if (action == ACTION_REVIVE)
+            {
+                Position pos;
```
Comment (Nefertumm) [inline src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp:505]: Define this variable inside the if below.

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp [hunk 9]
```diff
@@ -339,6 +474,85 @@ class npc_ohgan : public CreatureScript
...
+            }
+        }
+
+        void JustDied(Unit* /*killer*/) override
+        {
+            Player* target = ObjectAccessor::GetPlayer(*me, revivePlayerGUID);
+            if (!target || target->IsAlive())
+                return;
+
+            if (Creature* mandokir = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_MANDOKIR)))
```
Comment (Nefertumm) [inline src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp:535]:
```suggestion
            if (Creature* mandokir = instance->GetCreature(DATA_MANDOKIR))
```

File: data/sql/updates/pending_db_world/rev_1653580726731163907.sql [hunk 10]
```diff
@@ -0,0 +1,3 @@
+
+UPDATE `creature_template` SET `ScriptName`='npc_chained_spirit', `speed_run`=0.4 WHERE `entry`=15117;
```
Comment (Nefertumm) [inline data/sql/updates/pending_db_world/rev_1653580726731163907.sql:2]: source for speed_run change?

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp [hunk 11]
```diff
@@ -42,14 +36,18 @@ enum Says
...
     SPELL_FRENZY              = 24318, // seen
     SPELL_WATCH               = 24314, // seen 24315, 24316
-    SPELL_WATCH_CHARGE        = 24315, // Triggers 24316
-    SPELL_LEVEL_UP            = 24312  //
+    SPELL_WATCH_CHARGE        = 24315, // triggers 24316
+    SPELL_LEVEL_UP            = 24312, // seen
+    SPELL_EXECUTE             = 7160, // seen
+    SPELL_MANDOKIR_CLEAVE     = 20691, // seen
+
+    SPELL_REVIVE              = 24341 // chained spirit - seen
```
Comment (Nefertumm) [inline src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp:50]: "seen" comments are pretty useless. Remove them

**Review by Nefertumm — CHANGES_REQUESTED** [review]

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp (hunk 11 above)
Comment (Si1ker) [reply src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp:50]: @Nefertumm it was a chromiecraft's people think, so I just followed the standard, I also found them useless.
Resolved.

File: data/sql/updates/pending_db_world/rev_1653580726731163907.sql (hunk 10 above)
Comment (Si1ker) [reply data/sql/updates/pending_db_world/rev_1653580726731163907.sql:2]: @Nefertumm https://youtu.be/lwQWch4YUgE?t=255

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp (hunk 4 above)
Comment (Si1ker) [reply src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp:347]: forgot about it while working on other options, removed.

**Comment by UltraNix** [comment]
@Si1ker What about these:
#11748
#11750

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp (hunk 6 above)
Comment (Si1ker) [reply src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp:396]: pending

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp (hunk 7 above)
Comment (Si1ker) [reply src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp:471]: pending

**Comment by Si1ker** [comment]
@UltraNix 

#11748
(copy-paste from pr description under known issues) =
3- Guillotine after Charge proc'ed via Threatening Gaze
It works as intended when targets are <10yrds, **however, if the target is at 20-40+ yards, boss will only Charge ifWithinLOS and will skip guillotine as the proc is only right after the charge begins & within 10yrds.**

Solution: Some way to check final destination after Charge run is completed which was proc'ed via Threatening Gaze and then cast Guillotine on the same target.

In short, **works for melee** <10yrds, **not for casters** as **during the Charge run the guillotine cast fails due to range**.


#11750
This is actually a blizzlike mechanic in a considerable amount of bosses around the game.
https://db.rising-gods.de/?spells&filter=na=summon%20player
I haven't seen tc / ac / sunwell, getting this to work correctly due to pathing. Essentially if you're unreachable for the boss and the main target you're summoned to it. Same thing with [boss phased reset mechanic](https://github.com/azerothcore/azerothcore-wotlk/pull/7828) , some bosses have it and others not.

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp (hunk 11 above)
Comment (Nefertumm) [reply src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp]: Nope, it was not chromiecraft's.

Comment (Si1ker) [reply src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp]: dumb thing resolved, let's move forward.

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp (hunk 6 above)
Comment (Si1ker) [reply src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp]: Done

**Comment by Si1ker** [comment]
```txt
Run source ./apps/ci/ci-error-check.sh
The DBErrors.log file contains startup errors:

Script named 'npc_chained_spirit' is not assigned in the database.

Please solve the startup errors listed above!
```

yeap... that's why there's a DB update file to assign it lol

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp [hunk 12]
```diff
@@ -251,31 +303,70 @@ class boss_mandokir : public CreatureScript
...
+                                {
+                                    meleeRangeTargets.push_back(target);
+                                }
+                            }
+                            if (meleeRangeTargets.size() >= 5)
+                            {
+                                if (Unit* currentTarget = me->GetVictim())
+                                {
+                                    me->CastSpell(currentTarget, SPELL_MANDOKIR_CLEAVE, false);
+                                }
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp:354]:
```suggestion
                                if (Unit* currentTarget = me->GetVictim())
                                {
                                    DoCastVictim(SPELL_MANDOKIR_CLEAVE);
                                }
```

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp [hunk 13]
```diff
@@ -339,6 +479,76 @@ class npc_ohgan : public CreatureScript
...
 };
 
+struct npc_chained_spirit : public ScriptedAI
+{
+public:
+    npc_chained_spirit(Creature* creature) : ScriptedAI(creature)
+    {
+        instance = me->GetInstanceScript();
+        me->AddUnitMovementFlag(MOVEMENTFLAG_HOVER);
+        me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp:489]: this should be added to the DB if it's always suppose to have it 👍

Comment (Si1ker) [reply src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp:489]: will do

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp (hunk 2 above)
Comment (Si1ker) [reply src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp]: it is now.

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp (hunk 12 above)
Comment (Si1ker) [reply src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp:354]: read

Comment (Nyeriah) [reply src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp:354]: image
image

It's exactly the same thing. How about you read it yourself?

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp (hunk 13 above)
Comment (Kitzunu) [reply src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp:489]: (I unresolved because I want to teach a little)

We have helpers, so instead of `SetFlag(UNIT_FIELD_FLAGS` we now have `SetUnitFlags(` :D

**Comment by temperrr** [comment]
@Si1ker 

We want to start public testing of ZG next week. Can you fix this PR before that?

**Review by Nyeriah — APPROVED** [review]
