### PR TITLE
fix(Core/Loot):

### LINKED ISSUE #2104: [3.3.5] Core/loot/exploit the loot is not linked to players inside the dungeon or raid [$15]
Current behaviour: Players outside instance are still entitled to trophies
Expected behaviour: Only the players involved in the battle have the trophies
Steps to reproduce the problem:
Two Player Groups
One of the entry instances
.die boss
Players who do not enter instance enter instance
Players pick up trophies
Players who do not participate in instance can still see the trophy list
ROUND and group or master loot
Another player point does not save instance to leave
Branch: Master.
AC hash/commit: 7b105b7
Operating system: Linux, Ubuntu 14.04 and Windows 7.
Modules: No.
Other Customizations: No.

<bountysource-plugin>

---
There is a **[$15 open bounty](https://www.bountysource.com/issues/77081861-3-3-5-core-loot-exploit-the-loot-is-not-linked-to-players-inside-the-dungeon-or-raid?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
Players that did not participate in killing dungeon boss are not eligible to get loot.
Players that are too far away from the looted object are not eligible to get loot.
Players that released spirit and were outside the dungeon when the loot has been released are eligible to get loot.
Players that have pending bind are not eligible to get loot.

Properly get loot recipient for some chests in dungeons.
All aboved fixes should work in any loot mode (group loot, master loot, etc.)
Fixed #2104.

## Changes Proposed:
-  Added some conditions to loot.

## Issues Addressed:

- Closes #2104

## Tests Performed:

- Not tested

## How to Test the Changes:

`Players that did not participate in killing dungeon boss are not eligible to get loot.`
More info [here](https://github.com/azerothcore/azerothcore-wotlk/issues/2104) and [here](https://github.com/azerothcore/azerothcore-wotlk/issues/7444)

`Players that are too far away from the looted object are not eligible to get loot.`
1. Get group of two players and set loot mode to group loot
2. One of the player should be at least 200 yards awayffrom the other
3. The second player kills mob with some loot (e.g. world boss)
4. Release the loot
5. The "far away" player should not be able to roll on loot items,

`Players that released spirit and were outside the dungeon when the loot has been released are eligible to get loot.`
1. Get group of two, set to group loot and enter some instance/raid
2. Fight with some boss
3. One of the players should die and release spirit.
4. While the player is outside the dungeon, the second guy should kill and release spirit
5. The player that is dead and outside the dungeon should be able to roll on loot items.

`Players that have pending bind are not eligible to get loot.` - **#7448 IS NEEDED TO TEST THIS**
1. Solo enter raid (by `.gm on`) and kill any boss and get perm instance id.
2. Invite to your group other player.
3. Second player should teleport to instance and DO NO ACCEPT instance id.
4. The second player tries to loot the killed boss - you should not be able to loot it

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/game/Entities/Player/Player.cpp [hunk 1]
```diff
@@ -11842,18 +11842,32 @@ void Player::RewardPlayerAndGroupAtEvent(uint32 creature_id, WorldObject* pRewar
...
 {
-    if (!pRewardSource || !IsInMap(pRewardSource))
-        return false;
-    const WorldObject* player = GetCorpse();
+    WorldObject const* player = GetCorpse();
     if (!player || IsAlive())
         player = this;
 
+    if (!pRewardSource || !player->IsInMap(pRewardSource))
+        return false;
```
Comment (lineagedr) [inline src/server/game/Entities/Player/Player.cpp:11850]: braces

File: src/server/game/Entities/Player/Player.cpp [hunk 2]
```diff
@@ -11842,18 +11842,32 @@ void Player::RewardPlayerAndGroupAtEvent(uint32 creature_id, WorldObject* pRewar
...
 
+bool Player::IsAtLootRewardDistance(WorldObject const* pRewardSource) const
+{
+    if (!IsAtGroupRewardDistance(pRewardSource))
+    {
+        return false;
+    }
+
+    if (HasPendingBind())
+        return false;
```
Comment (lineagedr) [inline src/server/game/Entities/Player/Player.cpp:11866]: braces

File: src/server/game/Entities/Creature/Creature.cpp [hunk 3]
```diff
@@ -1139,22 +1139,48 @@ void Creature::SetLootRecipient(Unit* unit, bool withGroup)
...
             m_lootRecipientGroup = group->GetGUID().GetCounter();
+
+            if (map && map->IsDungeon() && (isWorldBoss() || IsDungeonBoss()))
+            {
+                Map::PlayerList const& PlayerList = map->GetPlayers();
+                for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
+                {
+                    if (Player* groupMember = i->GetSource())
+                    {
+                        if (groupMember->IsGameMaster() || groupMember->IsSpectator())
```
Comment (lineagedr) [inline src/server/game/Entities/Creature/Creature.cpp:1171]: Why the spectator check?

File: src/server/game/Entities/GameObject/GameObject.cpp [hunk 4]
```diff
@@ -2305,29 +2305,60 @@ Group* GameObject::GetLootRecipientGroup() const
...
-        return;
+void GameObject::SetLootRecipient(Map* map)
+{
+    Group* group = nullptr;
+    Map::PlayerList const& PlayerList = map->GetPlayers();
+    for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
+    {
+        if (Player* groupMember = i->GetSource())
+        {
+            if (groupMember->IsGameMaster() || groupMember->IsSpectator())
```
Comment (lineagedr) [inline src/server/game/Entities/GameObject/GameObject.cpp:2334]: Why the spectator check?

File: src/server/game/Entities/Creature/Creature.cpp (hunk 3 above)
Comment (Kitzunu) [reply src/server/game/Entities/Creature/Creature.cpp:1171]: Why don't we want GMs to be eligible for loot?

Comment (Bogir) [reply src/server/game/Entities/Creature/Creature.cpp:1171]: Maybe it's time to add permission for GMs to loot items in worldserver.conf ?
Just in case if Administrator have any Gms as stuff

Comment (UltraNix) [reply src/server/game/Entities/Creature/Creature.cpp:1171]: In case of somebody uses the spectator addon - we don't want to include spectators as they are not participating in killing the bosses. The same is for GMs.

File: src/server/game/Entities/GameObject/GameObject.cpp (hunk 4 above)
Comment (UltraNix) [reply src/server/game/Entities/GameObject/GameObject.cpp:2334]: In case of somebody uses the spectator addon - we don't want to include spectators as they are not participating in killing the bosses. The same is for GMs.

File: src/server/game/Entities/Creature/Creature.cpp (hunk 3 above)
Comment (Bogir) [reply src/server/game/Entities/Creature/Creature.cpp:1171]: > The same is for GMs.

It would be more correct to add a check if there are both GM and ordinary players in the group: loot according to the config is prohibited or allowed. To prevent abuse of GMs in favor of players

Comment (lineagedr) [reply src/server/game/Entities/Creature/Creature.cpp:1171]: @UltraNix You get a spectator flag when you enter an arena when you leave the arena it gets removed.

In a dungeon map a player can never be a spectator the IsSpectator is redundant here.
```c++
if (map && map->IsDungeon() && (isWorldBoss() || IsDungeonBoss()))
```

Comment (UltraNix) [reply src/server/game/Entities/Creature/Creature.cpp:1171]: I know there are some servers that use extended addon that enables raid spectating.

Comment (Kitzunu) [reply src/server/game/Entities/Creature/Creature.cpp:1171]: Could you add a //@todo that adding RBAC permission here would be golden once it is implemented

Comment (UltraNix) [reply src/server/game/Entities/Creature/Creature.cpp:1171]: RBAC is completely useless here.

Comment (Kitzunu) [reply src/server/game/Entities/Creature/Creature.cpp:1171]: Not really.

Comment (UltraNix) [reply src/server/game/Entities/Creature/Creature.cpp:1171]: What you mean?

Comment (Kitzunu) [reply src/server/game/Entities/Creature/Creature.cpp:1171]: I mean, I think this could be a good place to use a RBAC perm as then you could choose if only some GMs should be allowed to participate in the loot and some not etc. I could see use for that in a production environment. However, as RBAC isn't implemented we just have to wait anyways

**Comment by iraizo** [comment]
preferably fix the empty title of this pr?

**Comment by UltraNix** [comment]
It's not empty.

**Comment by iraizo** [comment]
weird, for me it is

**Comment by pklloveyou** [comment]
test 1.
If the distance between the player and the picker is greater than 85 yards, there will be no picking permission. There will be picking permission within 85 yards

**Comment by UltraNix** [comment]
@mpfans You can change that distance in config.

**Comment by pklloveyou** [comment]
Test 2.
Tested
Test 3.
Tested

**Comment by pklloveyou** [comment]
All pass the test
