### PR TITLE
fix(DB/creature): Double critter spawns in Dire Maul East

### LINKED ISSUE #10399: Double critter spawns in Dire Maul East
### Current Behaviour

There is an issue in Dire Maul East that somespawn point for [Squirrels](https://wowgaming.altervista.org/aowow/?npc=1412) and [Rabbits](https://wowgaming.altervista.org/aowow/?npc=721) spawns two critters.

Some examples:

WoWScrnShot_012822_160457

diremaul-double-critter3

### Expected Blizzlike Behaviour

Each spawn point for critters should only spawn one critter.

### Source

You can see that there should only spawn one squirrel in [this video](https://youtu.be/GAUSdfLLCl8?t=221) at the given timestamp.

There already was a bugfix https://github.com/azerothcore/azerothcore-wotlk/pull/8582 in the past, but it did not cover all spawn points.

### Steps to reproduce the problem

1. `.go creature 247680`

### Extra Notes

Listings of all affected spawn points and their critter GUIDs.

Squirrels:
* Spawn point 1 - `247680` and `247673`
* Spawn point 2 - `247676` and `247684`
* Spawn point 3 - `247678` and `247688`
* Spawn point 4 - `247687` and `247669`
* Spawn point 5 - `247692` and `247668`
* Spawn point 6 - `247689` and `247667`
* Spawn point 7 - `247681` and `247670`

Rabbits
* Spawn point 8 - `247922` and `247911`
* Spawn point 9 - `247921` and `247912`
* Spawn point 10 - `247916` and `247910`

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d6724e448f35ea981d64aff868ce700ab0cbde3

### Operating system

Ubuntu 20.04

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Fix duplicate critters in Dire Maul East

## Issues Addressed:

- Closes #10399 
- I also find one more duplicate pair (247914 and 247918) that was not in original issue

## SOURCE:

Here are screenshot of each of the duplicate critter before the fix:

## Tests Performed:

- Here are screenshot of each critter after the fix:

## How to Test the Changes:

1. .go creature (guid) for each creature, see now is only one crittter

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
i will get with the sniffers to see if they can clarify if the doubles are suppose to be moving around independently or if they are double due to a bad parse or if they are phase related (i seriously doubt they are phase related).

File: data/sql/updates/pending_db_world/rev_1643745379505594100.sql [hunk 1]
```diff
@@ -0,0 +1,12 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1643745379505594100');
+DELETE FROM `creature` WHERE  `guid` = 247680; # Duplicate of 247673
```
Comment (acidmanifesto) [inline data/sql/updates/pending_db_world/rev_1643745379505594100.sql:2]: instead of using # can you please put them in a commit out such as inbetween /*      */, 
for example ```/* Duplicate of 247673 */```

**Review by acidmanifesto — CHANGES_REQUESTED** [review]

**Comment by acidmanifesto** [comment]
@ZhengPeiRu21 must of been some change with the sql check, if you can , you can either move the notes to above each querey or remove the notes entirely for it to pass.

**Comment by acidmanifesto** [comment]
but just a follow up. sniff teams mention the doubles are infact duplicates so your pr will be marked for merge when you fix the issue with the notes.

File: data/sql/updates/pending_db_world/rev_1643745379505594100.sql [hunk 2]
```diff
@@ -0,0 +1,12 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1643745379505594100');
+DELETE FROM `creature` WHERE  `guid` = 247680; /* Duplicate of 247673 */
```
Comment (acidmanifesto) [inline data/sql/updates/pending_db_world/rev_1643745379505594100.sql:2]: i guess move the notes above or remove them. code style change must of happened at some point i am not aware of.

Comment (ZhengPeiRu21) [reply data/sql/updates/pending_db_world/rev_1643745379505594100.sql]: I think it is useful to know the duplicate IDs so if we can keep them it will be the best. I have moved them to above each line; hopefully this is enough for code style to be happy! Thank you for noticing this issue.

Comment (ZhengPeiRu21) [reply data/sql/updates/pending_db_world/rev_1643745379505594100.sql]: Please kindly let me know if it does not pass and I will remove the comments completely. Thank you!

**Review by acidmanifesto — APPROVED** [review]
