### PR TITLE
fix(DB/creature) Pools of Aggonar ooze aggro linking

### LINKED ISSUE #23410: [Hellfire Peninsula] Blistering Rot and Blistering Oozeling not linked
### Triage

Issue linked from CC:  https://github.com/chromiecraft/chromiecraft/issues/8238

Triage Notes: 

.tele poolsofagg
Pull the oozes

I found this source and a few others but I think this shows it best, of the oozes pulling together
https://youtu.be/baxVCco4zs0?si=g4yiQc7rCWQcVmIs&t=67
At the time stamp he pulls one to him and the smaller ones aggro onto him. 

Original Post Below: 

---

### Current Behaviour

In the Pools of Aggonar in Hellfire Peninsula, currently if you pull a Blistering Oozeling or a Blistering Rot who are in the same pack, they will not pull the other, this applies to both body pulling or pulling with a ranged attack

### Expected Blizzlike Behaviour

When you pull one of them in the same pack, it should pull the other too

### Source

They are part of the same pack, thus group aggro should apply when pulling them.

https://wowpedia.fandom.com/wiki/Aggro_radius

Non-radius-based aggro section explains this

### Steps to reproduce the problem

1. use .teleport Hellfire
2. Fly a bit north until you reach Pools of Aggonar
3. Try to pull one of the mobs and notice how the rest of the pack won't aggro, you can try this with body pulling too, just make sure you're actually not body pulling all of them, but just one of them

### Extra Notes

This has been working as intended for most of TBC and only recently changed/broke

### Customizations

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8a5098861ee1122993baf9250a7133acad18d68a

### Operating system

Ubuntu 20.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by aradep**
## Changes Proposed:
- Linked group aggro using creature_formation
- Added a couple new oozes so all groups are 1 big + 2 small
- Made stationary oozes and terrorfiends wander instead

## Issues Addressed:
- Closes #23410
- Closes https://github.com/chromiecraft/chromiecraft/issues/8238

## Tests Performed:
All individual groups tested in-game

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1761714420819230900.sql [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+(58497, 58497, 3), (58497, 58563, 3), (58497, 58564, 3);
+
+-- Reposition oozes to be closer to group members
+UPDATE `creature` SET `position_x`=381.658, `position_y`=3482.38, `position_z`=61.609, `orientation`=5.43889 WHERE `guid` = 58496 AND `id1` = 16901;
+UPDATE `creature` SET `position_x`=361.194, `position_y`=3460.88, `position_z`=60.7696, `orientation`=1.22522 WHERE `guid` = 58501 AND `id1` = 16903;
+UPDATE `creature` SET `position_x`=363.189, `position_y`=3467.19, `position_z`=60.2405, `orientation`=4.88126 WHERE `guid` = 58503 AND `id1` = 16903;
+
+-- New creatures
+DELETE FROM `creature` WHERE `guid` IN (58786,58787) AND `id1` IN (16901, 16903);
+INSERT INTO `creature` VALUES
```
Comment (sudlud) [inline data/sql/updates/pending_db_world/rev_1761714420819230900.sql]: can you please add the columns to this insert (before `VALUES`)

File: data/sql/updates/pending_db_world/rev_1761714420819230900.sql [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+-- Add 1 big ooze to group of 2 small
+(58786, 16901, 0, 0, 530, 0, 0, 1, 1, 0, 253.959, 3520.59, 64.9662, 4.6574, 300, 0, 0, 4385, 0, 0, 0, 0, 0, '', NULL, 0, NULL),
+-- Add 1 small ooze to group of 1 big/1 small
+(58787, 16903, 0, 0, 530, 0, 0, 1, 1, 0, 280.581, 3430.04, 66.0011, 5.03439, 300, 0, 0, 258, 0, 0, 0, 0, 0, '', NULL, 0, NULL);
+
+-- Make all oozes wander
+UPDATE `creature` SET `MovementType` = 1, `wander_distance` = 5 WHERE `id1` IN (16901,16903);
+
+-- Make all Terrorfiends wander
+UPDATE `creature` SET `MovementType` = 1, `wander_distance` = 5 WHERE `id1` = 16951;
```
Comment (sudlud) [inline data/sql/updates/pending_db_world/rev_1761714420819230900.sql]: i would prefer if these would also have the guid

**Comment by sudlud** [comment]
This was probably a misunderstanding, changes on creature / gameobject table should please always be done by id AND guid

**Comment by aradep** [comment]
Ah, gotcha

**Review by sudlud — APPROVED** [review]
