### PR TITLE
fix(Core/Boss Script): Obsidian Sanctum Bugs Fixed (Cant enter instance while boss in combat , fix HardMode problem with damage drakes before starting boss)

### LINKED ISSUE #2120: [Raid-WotLK] The Obsidian Sanctum - Is possible inside when the boss event is run on
Error 1: When the battle against Satarion starts, if you die it is possible to release and re-enter the event.
Error 2: If you attack another one of the dragons it is possible to move it to the center, lower it a lot the HP, Pull Sartharion and kill blue dragon. This to obtain the achievement of 3 live drakes
How reproduce

EXPECTED BLIZZLIKE BEHAVIOUR:
for 1:  Any player NOT enter in the Sanctum if other players are in combat with a boss.
for 2: If other mini boss move X yards, boss is restart or If Pull Sartharion others 3 dragons Live is restar in espedific locations.

BRANCH(ES):
master

AC HASH/COMMIT:
3b09bd7  - but test others old

OPERATING SYSTEM:
ubuntu 16.04

MODULES:
No

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/77372763-raid-wotlk-the-obsidian-sanctum-is-possible-inside-when-the-boss-event-is-run-on?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ArashGorge**
more Description on : https://github.com/azerothcore/azerothcore-wotlk/issues/2120

##### CHANGES PROPOSED:

-  
-  

###### ISSUES ADDRESSED:

Closes #2120

##### TESTS PERFORMED:

Build on win 10 vs 2017
Tested in game and Working

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

 
 
 
 
 ## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by solidmaxtor** [comment]
Excellent service .jpg
Nice ArashGorge  work fine first test

**Comment by Andrei-UPB** [comment]
Tested as well, seems to work as intended.

File: src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/instance_obsidian_sanctum.cpp [hunk 1]
```diff
@@ -7,6 +7,8 @@
 #include "obsidian_sanctum.h"
 #include "Player.h"
 
+#define MAX_ENCOUNTER     1
```
Comment (pklloveyou) [inline src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/instance_obsidian_sanctum.cpp]: //#define MAX_ENCOUNTER     1

File: src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/instance_obsidian_sanctum.cpp [hunk 2]
```diff
@@ -40,6 +42,15 @@ class instance_obsidian_sanctum : public InstanceMapScript
             memset(&Encounters, 0, sizeof(Encounters));
         };
 
+        bool IsEncounterInProgress() const
+        {
+            for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
```
Comment (pklloveyou) [inline src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/instance_obsidian_sanctum.cpp]: //for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
for (uint8 i = 0; i < MAX_ENCOUNTERS; ++i)

Comment (ArashGorge) [reply src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/instance_obsidian_sanctum.cpp]: it's not blizzlike, because dragons haven't loot, and its not matter

**Comment by ArashGorge** [comment]
> Can three dragons enter the battle and can not enter the instance. ：P

it's not blizzlike, because dragons haven't loot, and its not matter

File: src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/instance_obsidian_sanctum.cpp (hunk 2 above)
Comment (Stoabrogga) [reply src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/instance_obsidian_sanctum.cpp]: @ArashGorge 
What I don't understand here: "MAX_ENCOUNTER" is 1, so the loop will only be executed once for the value "0", why is the loop necessary at all? Wouldn't it suffice to use something like this instead of the loop?
```cpp
if (Encounters[BOSS_SARTHARION_EVENT] == IN_PROGRESS)
    return true;
```

Comment (ArashGorge) [reply src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/instance_obsidian_sanctum.cpp]: I tested it, didn't work
if i remember

Comment (Stoabrogga) [reply src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/instance_obsidian_sanctum.cpp]: Hmm, that's strange, because semantically it is the same. Could you please tell me how to test this?

**Comment by FrancescoBorzi** [comment]
@ArashGorge please check the comment from @Stoabrogga

File: src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/instance_obsidian_sanctum.cpp (hunk 2 above)
Comment (ArashGorge) [reply src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/instance_obsidian_sanctum.cpp]: as i say i don't remember , but it should work (tested and works fine), and your codes maybe i wrong in testing event , I don't think there is a problem with my write's ,but if you want i can test again and i'll told result as both of them

**Comment by Stoabrogga** [comment]
@ArashGorge 
I managed to test my solution and it did work. I was not able to enter the instance again after dying while fighting against Sartharion. I pushed a new commit and think this is now ready to be merged.
