### PR TITLE
fix(Core): prevent movement exploit

### LINKED ISSUE #2327: [Crash][No log][Fix]HandleMovementOpcodes
**This affect current master branch, with latest updates.
AC hash: 9e2bd353d2de485593b384a137cd1f3c9dc9f91a**

Path: src/server/game/Handlers/MovementHandler.cpp

There is possible to crash server.
Who know how to reproduce - can do it, without my instruction. No solution for haxxors.
Ok, building client movement packet wiht forward/backward/strafe left/right without adding guid to packet - crash server.
This can be fast overlooked in MovementHadler.cpp, on HandleMovementOpcodes:
there is no check incomming guid.

Well, just make advanced check, and log it:
```
recvData.readPackGUID(guid);
ASSERT(!guid);
```
or:
```
if (!guid)
return;
```

Sorry for "not templated" post, but no care.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/81421640-crash-no-log-fix-handlemovementopcodes?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #2409: Crash - Exploit hacker
Hello friends
I've been suffering attacks for 2 months

First attack was with macro / rum - Fixed
Second with program AccLeiTo-Crash - Fixed

Now I have a new problem with our log and I have no idea.
https://pastebin.com/bJidXUwC <<<<<
Operation System ***
Windows Server 2012 Server 4.0 (Version 6.2, Build 9200)

If anyone has an idea, it would help me a lot

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/83289840-crash-exploit-hacker?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #2422: [Crash] [$100]
##### CURRENT BEHAVIOUR:
Server crashes for 2 days now, after the newest commit, with crash log.

##### STEPS TO REPRODUCE THE PROBLEM:
 I don't know. 

##### EXTRA NOTES:
 Crashlog:
https://gist.github.com/IceNet/d4aed5961be66e541dbbaa8afa96555b

##### BRANCH(ES):

master

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/0fd565d5573dce91dc87874b6de2ca4b3f884bfa

##### OPERATING SYSTEM:
Windows Server 2016

##### MODULES:
1vs1
Account Mounts
Better Item Reloading
Duel Reset
Individual XP
PvP Titles
Teleporter
Transmog
Weekend XP

<bountysource-plugin>

---
Did you help close this issue? Go claim the **[$100 bounty](https://www.bountysource.com/issues/83501658-crash?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Helias**
I added some checks in `WorldSession::HandleMovementOpcodes()` function to prevent a possible exploit.

##### CHANGES PROPOSED:
-  added some checks for movement opcode inspired by TrinityCore and https://github.com/azerothcore/azerothcore-wotlk/issues/2327
- removed useless Opcodes attribute **isGrouppedMovementOpcode**, related condition which cause the server crash for malformed opcode and fixed indentation in Opcodes.cpp
- added some immutability features about bytebuffer exceptions

##### ISSUES ADDRESSED:
- Close #2409 
- Close #2422 
- Close #2327 

##### TESTS PERFORMED:
I tested the following things:
- MSG_MOVE_HEARTBEAT opcode malformed using WPS
- MSG_MOVE_SET_FACING opcode malformed using WPS
The server skip these malformed packet and prints some logs.
skip byte log

I tested also the normal playing that using (probably) "groupped" movements:
- gryphon mount
- horse mount
- boat movements in SOTA BG (2 players)
- tank movements in SOTA BG (2 players)
- horde movements and attack into SOTA tank
- blink spell

##### HOW TO TEST THE CHANGES:
- @lineagedr [comments](https://github.com/azerothcore/azerothcore-wotlk/pull/2410#issuecomment-552111752) explain which lua scripts use with WPS/Accleito tool to make crash the server.
- playing use all kind of movements that turn on client standard movement opcode

##### Target branch(es):
- [x] Master

### CODE REVIEW

**Comment by avatar789** [comment]
not compile crash
https://pastebin.com/xu9CHBsf

**Comment by Helias** [comment]
it compiles in my machine : /
indeed  `guid` is declared in `WorldSession::HandleMovementOpcodes` function, probably you imported in a wrong way the PR

File: src/server/game/Handlers/MovementHandler.cpp [hunk 1]
```diff
@@ -325,11 +325,14 @@ void WorldSession::HandleMovementOpcodes(WorldPacket & recvData)
...
-    if (!mover || !mover->IsInWorld() || mover->IsDuringRemoveFromWorld() || guid != mover->GetGUID())
+    // prevent tampered movement data
+    if (!guid || guid != mover->GetGUID()) {
         return;
+    }
 
-    if (!movementInfo.pos.IsPositionValid())
+    // pussywizard: typical check for incomming movement packets
+    if (!mover || !(mover->IsInWorld()) || mover->IsDuringRemoveFromWorld() ||
+        !(mover->movespline->Finalized()) || !movementInfo.pos.IsPositionValid())
```
Comment (pklloveyou) [inline src/server/game/Handlers/MovementHandler.cpp]: guid != mover->GetGUID()

File: src/server/game/Chat/ChatLink.cpp [hunk 2]
```diff
@@ -662,6 +662,7 @@ bool LinkExtractor::IsValidMessage()
 
         char commandChar;
         _iss >> commandChar;
```
Comment (LichKing255) [inline src/server/game/Chat/ChatLink.cpp]: this must remove.

Comment (Helias) [reply src/server/game/Chat/ChatLink.cpp]: done, thank you very  much

**Comment by Viste** [comment]
src/server/game/Chat/ChatLink.cpp
this file needs full rework

**Comment by LichKing255** [comment]
> src/server/game/Chat/ChatLink.cpp
> this file needs full rework all chat stuff need fully rework

i rework to last version before change to Hyperlinks and not fix this PR https://github.com/azerothcore/azerothcore-wotlk/issues/2409

**Comment by Viste** [comment]
> > src/server/game/Chat/ChatLink.cpp
> > this file needs full rework all chat stuff need fully rework
> 
> i rework to last version before change to Hyperlinks and not fix this PR #2409

lol It's the feeling that when... someone does what they don't understand and hope for results.

btw #2409 is issue not a MR(PR)

**Comment by LichKing255** [comment]
> > > src/server/game/Chat/ChatLink.cpp
> > > this file needs full rework all chat stuff need fully rework
> > 
> > 
> > i rework to last version before change to Hyperlinks and not fix this PR #2409
> 
> lol It's the feeling that when... someone does what they don't understand and hope for results.
> 
> btw #2409 is issue not a MR(PR)

sorry :D My mind was busy.

**Comment by Viste** [comment]
> > > > src/server/game/Chat/ChatLink.cpp
> > > > this file needs full rework all chat stuff need fully rework
> > > 
> > > 
> > > i rework to last version before change to Hyperlinks and not fix this PR #2409
> > 
> > 
> > lol It's the feeling that when... someone does what they don't understand and hope for results.
> > btw #2409 is issue not a MR(PR)
> 
> sorry :D My mind was busy. I mean issue

it's okay.
About my comment...
Don't think it's rude. It just so happens that you did everything, but what you had to do was not done.

**Comment by LichKing255** [comment]
> > > > > src/server/game/Chat/ChatLink.cpp
> > > > > this file needs full rework all chat stuff need fully rework
> > > > 
> > > > 
> > > > i rework to last version before change to Hyperlinks and not fix this PR #2409
> > > 
> > > 
> > > lol It's the feeling that when... someone does what they don't understand and hope for results.
> > > btw #2409 is issue not a MR(PR)
> > 
> > 
> > sorry :D My mind was busy. I mean issue
> 
> it's okay.
> About my comment...
> Don't think it's rude. It just so happens that you did everything, but what you had to do was not done.

Now I'm trying to update to my latest version Chat and Hyperlinks.

**Comment by lineagedr** [comment]
@Helias You can reproduce it by using WPS for example use the old crash.lua
change the opcode from CMSG_JOIN_CHANNEL to MSG_MOVE_SET_FACING.

This is sniffed data of a normal MSG_MOVE_SET_FACING packet.
```
ClientToServer: MSG_MOVE_SET_FACING (0x00DA) Length: 32 ConnIdx: 0 Time: 11/09/2019 13:31:43.436 Number: 9
Guid: Full: 0x00000008 Type: Player Low: 8
Movement Flags: 0 (None)
Extra Movement Flags: 0 (None)
Time: 1325385
Position: X: 16257.57 Y: 16269.38 Z: 15.77209
Orientation: 1.022893
Fall Time: 0
```

So packet in WPS would look something like this
```
new_packet = wow.create_client_packet()
new_packet:set_opcode(MSG_MOVE_SET_FACING)
new_packet:put_dword(0x8) -- GUID
new_packet:put_dword(0) -- Movement Flags
new_packet:put_dword(0) -- Extra Movement Flags
new_packet:put_dword(0) -- Time
new_packet:put_dword(0) -- PositionX
new_packet:put_dword(0) -- PositionY
new_packet:put_dword(0) -- PositionZ
new_packet:put_dword(0) -- PositionO
new_packet:put_dword(0) -- Fall Time
```

That wouldn't really cause a crash but if we comment out some of the data
```
new_packet = wow.create_client_packet()
new_packet:set_opcode(MSG_MOVE_SET_FACING)
new_packet:put_dword(0x8) -- GUID
new_packet:put_dword(0) -- Movement Flags
new_packet:put_dword(0) -- Extra Movement Flags
new_packet:put_dword(0) -- Time
--new_packet:put_dword(0) -- PositionX
--new_packet:put_dword(0) -- PositionY
--new_packet:put_dword(0) -- PositionZ
--new_packet:put_dword(0) -- PositionO
--new_packet:put_dword(0) -- Fall Time
```

And send the modified packet the server will crash.

**Comment by Helias** [comment]
Perfect, thank you, I will try soon

**Comment by lineagedr** [comment]
@Helias Things to note if you send a empty packet
```
function test_crash()
new_packet = wow.create_client_packet()
new_packet:set_opcode(MSG_MOVE_HEARTBEAT)
wow.make_client_packet(new_packet:get_string(0x3, new_packet:get_size() - 0x2))
end
```
We send MSG_MOVE_HEARTBEAT but without GUID. 
So it throws bytebuffer exception in void readPackGUID(uint64& guid) Just like in https://github.com/azerothcore/azerothcore-wotlk/issues/2409 crash log

It's werid cause in TC the packet gets skipped https://i.imgur.com/75LWHJs.png

**Comment by Helias** [comment]
I'm still working for `MSG_MOVE_SET_FACING`.

**Comment by lineagedr** [comment]
I'm sure there's a lot more opcodes that can be exploited your way of fixing it is hacky we should focus on finding why they're being skipped in TrinityCore and not on AzerothCore.

**Comment by Helias** [comment]
@lineagedr, agree, anyway for now I added that try/catch to save some server crashes :sweat_smile: 

(I just added try-catch also for MSG_MOVE_SET_FACING)

**Comment by Helias** [comment]
@lineagedr apparently, TC use ObjectGuid class and its method "ReadAsPacked()" to get the guid from a packet, and use a reinterpret_cast (which I already tried on AC without success), but I don't know if this is the real way of TC to skip these kind of packet, but I see that the difference is this.

I will investigate tomorrow about how TC exactly skip the packet.

**Comment by lineagedr** [comment]
@Helias Actually there's no need to investigate. I've noticed a patern in Opcodes.cpp. Opcodes that are causing a crash have isGrouppedMovementOpcode value of true

```
    /*0x0B5*/ { "MSG_MOVE_START_FORWARD",                       STATUS_LOGGEDIN, PROCESS_THREADSAFE,   &WorldSession::HandleMovementOpcodes           , true  },
    /*0x0B6*/ { "MSG_MOVE_START_BACKWARD",                      STATUS_LOGGEDIN, PROCESS_THREADSAFE,   &WorldSession::HandleMovementOpcodes           , true  },
    /*0x0B7*/ { "MSG_MOVE_STOP",                                STATUS_LOGGEDIN, PROCESS_THREADSAFE,   &WorldSession::HandleMovementOpcodes           , true  },
    /*0x0B8*/ { "MSG_MOVE_START_STRAFE_LEFT",                   STATUS_LOGGEDIN, PROCESS_THREADSAFE,   &WorldSession::HandleMovementOpcodes           , true  },
    /*0x0B9*/ { "MSG_MOVE_START_STRAFE_RIGHT",                  STATUS_LOGGEDIN, PROCESS_THREADSAFE,   &WorldSession::HandleMovementOpcodes           , true  },
    /*0x0BA*/ { "MSG_MOVE_STOP_STRAFE",                         STATUS_LOGGEDIN, PROCESS_THREADSAFE,   &WorldSession::HandleMovementOpcodes           , true  },
    /*0x0BC*/ { "MSG_MOVE_START_TURN_LEFT",                     STATUS_LOGGEDIN, PROCESS_THREADSAFE,   &WorldSession::HandleMovementOpcodes           , true  },
    /*0x0BD*/ { "MSG_MOVE_START_TURN_RIGHT",                    STATUS_LOGGEDIN, PROCESS_THREADSAFE,   &WorldSession::HandleMovementOpcodes           , true  },
    /*0x0BE*/ { "MSG_MOVE_STOP_TURN",                           STATUS_LOGGEDIN, PROCESS_THREADSAFE,   &WorldSession::HandleMovementOpcodes           , true  },
    /*0x0BF*/ { "MSG_MOVE_START_PITCH_UP",                      STATUS_LOGGEDIN, PROCESS_THREADSAFE,   &WorldSession::HandleMovementOpcodes           , true  },
    /*0x0C0*/ { "MSG_MOVE_START_PITCH_DOWN",                    STATUS_LOGGEDIN, PROCESS_THREADSAFE,   &WorldSession::HandleMovementOpcodes           , true  },
    /*0x0C1*/ { "MSG_MOVE_STOP_PITCH",                          STATUS_LOGGEDIN, PROCESS_THREADSAFE,   &WorldSession::HandleMovementOpcodes           , true  },
    /*0x0CA*/ { "MSG_MOVE_START_SWIM",                          STATUS_LOGGEDIN, PROCESS_THREADSAFE,   &WorldSession::HandleMovementOpcodes           , true  },
    /*0x0CB*/ { "MSG_MOVE_STOP_SWIM",                           STATUS_LOGGEDIN, PROCESS_THREADSAFE,   &WorldSession::HandleMovementOpcodes           , true  },
    /*0x0DB*/ { "MSG_MOVE_SET_PITCH",                           STATUS_LOGGEDIN, PROCESS_THREADSAFE,   &WorldSession::HandleMovementOpcodes           , true  },
    /*0x0EE*/ { "MSG_MOVE_HEARTBEAT",                           STATUS_LOGGEDIN, PROCESS_THREADSAFE,   &WorldSession::HandleMovementOpcodes           , true  },
    /*0x359*/ { "MSG_MOVE_START_ASCEND",                        STATUS_LOGGEDIN, PROCESS_THREADSAFE,   &WorldSession::HandleMovementOpcodes           , true  },
    /*0x35A*/ { "MSG_MOVE_STOP_ASCEND",                         STATUS_LOGGEDIN, PROCESS_THREADSAFE,   &WorldSession::HandleMovementOpcodes           , true  },
    /*0x3A7*/ { "MSG_MOVE_START_DESCEND",                       STATUS_LOGGEDIN, PROCESS_THREADSAFE,   &WorldSession::HandleMovementOpcodes           , true  },
```

Which was implemented by pussywizard

```
bool isGrouppedMovementOpcode; // pussywizard
```

So, after changing them to false or commenting out this statement https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Server/WorldSession.cpp#L304

They get skipped just like in TC: https://i.imgur.com/PFy210j.png

Why was isGrouppedMovementOpcode added? No idea. Maybe to speedup the core idk..

**Comment by Helias** [comment]
It works without try catch ;-)!
immagine

**Comment by Helias** [comment]
I tested the following things:
- **MSG_MOVE_HEARTBEAT** opcode malformed using WPS
- **CMSG_GMTICKET_CREATE** opcode malformed using WPS
The server skip these malformed packet.

I tested also the normal playing that using (probably) "groupped" movements:
- gryphon mount
- horse mount
- boat movements in SOTA BG (2 players)
- tank movements in SOTA BG (2 players)
- horde movements and attack into SOTA tank
- blink spell

Thanks @lineagedr

**Comment by avatar789** [comment]
Works fine no discounts

**Comment by vhiperdev** [comment]
Tested with several opcodes and we really have no crashes anymore

File: src/server/game/Handlers/MovementHandler.cpp [hunk 3]
```diff
@@ -325,11 +325,14 @@ void WorldSession::HandleMovementOpcodes(WorldPacket & recvData)
 
     recvData.rfinish();                         // prevent warnings spam
 
-    // pussywizard: typical check for incomming movement packets
-    if (!mover || !mover->IsInWorld() || mover->IsDuringRemoveFromWorld() || guid != mover->GetGUID())
+    // prevent tampered movement data
```
Comment (Winfidonarleyan) [inline src/server/game/Handlers/MovementHandler.cpp]: Need check guild before `ReadMovementInfo(recvData, &movementInfo);` - #2426 [R322-R331](https://github.com/azerothcore/azerothcore-wotlk/pull/2426/files#diff-649b0ea06820eb06283d1ccc8c83efdbR322-R331)

Comment (Helias) [reply src/server/game/Handlers/MovementHandler.cpp]: Done, thank you.

File: src/server/game/Handlers/MovementHandler.cpp [hunk 4]
```diff
@@ -325,11 +325,14 @@ void WorldSession::HandleMovementOpcodes(WorldPacket & recvData)
...
+    if (!guid || guid != mover->GetGUID()) {
         return;
```
Comment (Winfidonarleyan) [inline src/server/game/Handlers/MovementHandler.cpp]: add `recvData.rfinish();                     // prevent warnings spam` before `return`

Comment (Helias) [reply src/server/game/Handlers/MovementHandler.cpp]: done, thank you :heart:

**Comment by pklloveyou** [comment]
Can we merge?

**Comment by FrancescoBorzi** [comment]
I see 2 people that have tested with positive feedback so I think it can be merged.

**Comment by wowpide** [comment]
This pr is broken can’t work with https://github.com/azerothcore/azerothcore-wotlk/pull/2426 which one better ???

**Comment by Helias** [comment]
This PR has some modificaiton shared with https://github.com/azerothcore/azerothcore-wotlk/pull/2426 , I will solve the merge conflicts, don't worry

File: src/server/game/Handlers/MovementHandler.cpp [hunk 5]
```diff
@@ -319,19 +319,24 @@ void WorldSession::HandleMovementOpcodes(WorldPacket & recvData)
...
 
+    // prevent tampered movement data
+    if (!guid || guid != mover->GetGUID()) {
+        recvData.rfinish();                     // prevent warnings spam
+        return;
+    }
+
     // pussywizard: typical check for incomming movement packets
-    if (!mover || !mover->IsInWorld() || mover->IsDuringRemoveFromWorld() || guid != mover->GetGUID())
+    if (!mover || !(mover->IsInWorld()) || mover->IsDuringRemoveFromWorld() || !(mover->movespline->Finalized()))
```
Comment (Winfidonarleyan) [inline src/server/game/Handlers/MovementHandler.cpp]:
```cpp
if (!mover || !mover->IsInWorld() || mover->IsDuringRemoveFromWorld() || !mover->movespline->Finalized())
```
No need `()`

Comment (Helias) [reply src/server/game/Handlers/MovementHandler.cpp]: I know, but probably I did it for codacy, because codacy read `!mover` and `!mover->...` like the same condition, probably it was a temporary mistake
