### PR TITLE
fix(DB/BlackrockSpire): Spirestone Lord Magus should cast Enlarge and…

### LINKED ISSUE #7361: LBRS rare spawn Spirestone Lord Magus doesn't cast some spells
### Current Behaviour

He appears to only cast `Arcane Bolt` and `Bloodlust` but only on himself once his HP reaches 30%

### Expected Blizzlike Behaviour

He should also cast Enlarge, and Polymorph. He should have the ability to cast bloodlust onto any adds involved in the battle as well. 

### Source

https://www.wowhead.com/npc=9217/spirestone-lord-magus#abilities;mode:normal
https://wowpedia.fandom.com/wiki/Spirestone_Lord_Magus
https://wowwiki-archive.fandom.com/wiki/Spirestone_Lord_Magus
Classic WOW LBRS walkthrough: https://youtu.be/3bKwDcQqINM?t=610

### Steps to reproduce the problem

 `.go c 43521`
If he's not spawned, target his corpse and `.respawn`
Enter into combat and see what he attacks with
Get his health to 30% and watch him self cast Bloodlust
See if he will cast it onto any adds in combat with him

### Extra Notes

_No response_

### AC rev. hash/commit

 faef417d9231

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
… Bloodlust on his allies.

Fixes #7361

 

## Issues Addressed:

- Closes #7361

## Tests Performed:

- Not tested.

## How to Test the Changes:

`.go c 43521`
If he's not spawned, target his corpse and .respawn
Enter into combat and see what he attacks with

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1637093880615871400.sql [hunk 1]
```diff
@@ -0,0 +1,6 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1637093880615871400');
+
+DELETE FROM `smart_scripts` WHERE `entryorguid`=9217 AND `id` IN (5,6);
```
Comment (Nefertumm) [inline data/sql/updates/pending_db_world/rev_1637093880615871400.sql:3]: We always add sourcetype for smart_scripts delete too :)

**Review by Nefertumm — APPROVED** [review]
