### PR TITLE
fix(Scripts/AuchenaiCrypts): Remove debuff on summon death

### LINKED ISSUE #22419: [Auchenai Crypts] Stolen Soul debuff not removed
### Current Behaviour

The Stolen Soul debuff remains for the full 2 minutes, even if the Stolen Soul NPC is killed.

### Expected Behaviour

The debuff is cleared as soon as the NPC dies.

### Source

https://www.youtube.com/watch?v=_HXzV8gU1lU At 15:26, Maladaar casts Steal Soul on the mage. At 15:38, the Stolen Soul is killed, and the debuff is immediately cleared.

The same can be seen here https://www.youtube.com/watch?v=bdwI9xIpisU at 2:49 on the priest, and here https://www.youtube.com/watch?v=haJG2rqqeas at 1:50, though much less clear than on the first video.

### Steps to reproduce the problem

1. .go creature name Exarch Maladaar
2. Let Maladaar cast Steal Soul on you
3. Kill the Stolen Soul, the debuff remains

### Extra Notes

Trying to fix this myself, if and when I find the time. :)

### AC rev. hash/commit

AzerothCore rev. a1a11a7c3800+ 2025-07-05 12:00:08 +0200 (master branch) (Unix, Release, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
Server uptime: 1 minute(s) 16 second(s)
Update time diff: 1ms. Last 500 diffs summary:
|- Mean: 1ms
|- Median: 1ms
|- Percentiles (95, 99, max): 4ms, 6ms, 8ms
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80039
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.10.7-arch1-1
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in /azerothcore/data/maps. Total size: 291014951 bytes
vmaps directory located in /azerothcore/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /azerothcore/data/mmaps. Total size: 2192910800 bytes
Default DBC locale: enUS.
All available DBC locales: enUS 
Using World DB: ACDB 335.13-dev
Latest LoginDatabase update: 2025_07_03_00.sql
Latest CharacterDatabase update: 2025_03_09_00.sql
Latest WorldDatabase update: 2025_07_03_03.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules are enabled

### Operating system

Arch Linux x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by martin-leuner**
Exarch Maladaar debuffs players when casting Stolen Soul, and summons a Stolen Soul mob. When the mob dies, the debuff is supposed to be removed from the player.

To achieve this, keep track of the number of Stolen Souls targeting each player. If that number falls to 0, remove the debuff.

Closes AzerothCore issue #22419

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [X] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #22419 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [X] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [X] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
This approach might be more elaborate than what the problem requires.

**Comment by martin-leuner** [comment]
It might be. I felt that tracking the number of Stolen Souls on a player was necessary so that we wouldn't remove the debuff in case there are two active Stolen Souls, and only one of them dies.

Do you have an idea for a simpler approach?

**Comment by Nyeriah** [comment]
Yes use SetGUID() to send the player info through to the summon and just store the player guid we want the aura removed in the summoned creature script

**Comment by martin-leuner** [comment]
That's a *much* simpler solution, thanks for the hints.

However, it does cause the minor bug I described above: if more than one Stolen Souls are cast on a player, killing just one of them removes the debuff. Do you prefer this solution anyway? (Granted, this bug is relatively unlikely to come up in actual play, and its effects are fairly inconsequential.)

**Review by Nyeriah — APPROVED** [review]

File: src/server/scripts/Outland/Auchindoun/AuchenaiCrypts/boss_exarch_maladaar.cpp [hunk 1]
```diff
@@ -255,8 +260,17 @@ struct npc_stolen_soul : public ScriptedAI
         DoMeleeAttackIfReady();
     }
 
+    void JustDied(Unit* /*killer*/) override
+    {
+        auto target = ObjectAccessor::GetUnit(*me, _targetGuid);
+        if (target)
+            target->RemoveAurasDueToSpell(SPELL_STOLEN_SOUL);
```
Comment (Nyeriah) [inline src/server/scripts/Outland/Auchindoun/AuchenaiCrypts/boss_exarch_maladaar.cpp]:
```suggestion
        if (Unit* target = ObjectAccessor::GetUnit(*me, _targetGuid))
            target->RemoveAurasDueToSpell(SPELL_STOLEN_SOUL);
```

**Comment by Nyeriah** [comment]
Thanks for the PR, I might have an idea to solve that problem but it needs a little more investigation before I can commit to it, I will merge and we can return to it later
