### PR TITLE
fix(scripts/Ulduar): Assembly of Iron - interrupt immune effect

### LINKED ISSUE #3728: [Ulduar] [Assembly of Iron] Stormshield granting immunity to spell interrupt
##### CURRENT BEHAVIOUR:
During the Assembly of Iron (25) encounter [Stormshield](https://wotlkdb.com/?spell=64187), gained from 2 dead, incorrectly gives Brundir immunity to kick in addition to stun. Tested with a warriors [Shield Bash](https://wotlkdb.com/?spell=72).

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Interrupting spells should still be possible, even with [Stormshield](https://wotlkdb.com/?spell=64187) up.

##### STEPS TO REPRODUCE THE PROBLEM:
1.) Take a warrior in GM mode to Ulduar
2.) Start the Assembly of Iron encounter
3.) Take 2 down and leave Brundir alive. He should be buffed with "Stormshield". Try to interrupt one of his casts of [Lightning Whirl](https://wotlkdb.com/?spell=52943) with a [Shield Bash](https://wotlkdb.com/?spell=72).

##### EXTRA NOTES:
On the same topic, even before Stormshield is active it seems like Brundir cant be kicked right away after he starts casting. If you wait for him to get a few bolts off, kicks with [Shield Bash](https://wotlkdb.com/?spell=72) seem to work.

AC HASH/COMMIT:
c208a12
from June 3rd

OPERATING SYSTEM:
OS: Ubuntu Server 20.04

MODULES:
none

OTHER CUSTOMIZATIONS:
No customizations at all

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/94495404-ulduar-assembly-of-iron-stormshield-granting-immunity-to-spell-interrupt?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Si1ker**
This change deletes the immune effect applied by script.

The intention is to remove the immune event which is triggered by the overload event, the immunity is not needed at all, seems it was implemented to prevent players to interrupt the Overload spell:

image

This spell by default cannot be interrupted so the immunity by script is useless and is just generating the issue #3728 

I have tried to interrupt with spell classes such as
[Shield Bash](https://wotlkdb.com/?spell=72)
[Kick](https://wotlkdb.com/?spell=1766)
[Mind Freeze](https://wotlkdb.com/?spell=47528)
none of them interrupted the spell (as expected)

## CHANGES PROPOSED:
-  Delete EVENT_IMMUNE
-  Remove ApplySpellImmune

## ISSUES ADDRESSED:
- Closes #3728 

## TESTS PERFORMED:
- Tested in-game:  Took 2 (big and mid bosses) down and left Brundir (small) alive, when he casts Overload, I tried to interrupt which failed (correct). All attempts to interrupt "Lightning Whirl" are successful

## HOW TO TEST THE CHANGES:

.cheat god
Set raid to 25-normal
.go xyz 1642.31 120.07 427.29 603 3.07
Engage combat
Kill Big and mid bosses, left just the small one
Try to interrupt "Overload" and "Lightning Whirl"

Overload: ❌
Lightning Whirl: ✔️
🐱 

## KNOWN ISSUES AND TODO LIST:

- N/A

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

File: src/server/scripts/Northrend/Ulduar/Ulduar/boss_assembly_of_iron.cpp [hunk 1]
```diff
@@ -89,9 +89,8 @@ enum eEnums
     EVENT_LIGHTNING_TENDRILS    = 24,
     EVENT_LIGHTNING_LAND        = 25,
     EVENT_LAND_LAND             = 26,
-    EVENT_IMMUNE                = 27,
 
-    EVENT_ENRAGE                = 30,
+    EVENT_ENRAGE                = 30
```
Comment (FrancescoBorzi) [inline src/server/scripts/Northrend/Ulduar/Ulduar/boss_assembly_of_iron.cpp:93]: where are these value taken from?

Comment (Si1ker) [reply src/server/scripts/Northrend/Ulduar/Ulduar/boss_assembly_of_iron.cpp:93]: @FrancescoBorzi What values exactly? 🤔  on that part which you've marked, I just deleted the **,**  because that event is the last one so is not needed to have a **,** at the end of it. If you are taking about another thing, let me know exactly 😸

**Review by FrancescoBorzi — APPROVED** [review]
