### PR TITLE
fix(Core/Config): Removed unsued config.

### LINKED ISSUE #4956: missing SetDeprecatedExternalPasswords in .dist
@UltraNix, probably you missed to add this conf in the worldserver.conf.dist, please add it to avoid the startup error "missing conf `SetDeprecatedExternalPasswords`".

##### AC HASH/COMMIT:
b8c2c2311d08b2b6332ce013ecc69d4ce7e33500

##### OPERATING SYSTEM:
Ubuntu 20.04

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/97322627-missing-setdeprecatedexternalpasswords-in-dist?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
## Changes Proposed:
-  Remove unused config introduced here: 485f7e76391a5bbf1af6b3219d27db721af38440
-  

## Issues Addressed:
- Closes #4956.

## Tests Performed:
-
-

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

File: data/sql/updates/pending_db_auth/rev_1615629613255169700.sql [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+    ADD COLUMN `session_key` BINARY(40) DEFAULT NULL AFTER `verifier`;
+
+UPDATE `account` SET `salt`=UNHEX(CONCAT(MD5(RAND()),MD5(RAND()))), `verifier`=UNHEX(CONCAT(MD5(RAND()),MD5(RAND()))) WHERE `salt` IS NULL OR `verifier` IS NULL;
+
+ALTER TABLE `account`
+    DROP COLUMN `s`,
+    DROP COLUMN `v`,
+    DROP COLUMN `sha_pass_hash`,
+    MODIFY COLUMN `salt` BINARY(32) NOT NULL,
+    MODIFY COLUMN `verifier` BINARY(32) NOT NULL;
```
Comment (FrancescoBorzi) [inline data/sql/updates/pending_db_auth/rev_1615629613255169700.sql:27]: are you sure this SQL is intended here?

Comment (UltraNix) [reply data/sql/updates/pending_db_auth/rev_1615629613255169700.sql:27]: Definitely no.

**Review by Kitzunu — APPROVED** [review]

**Review by Helias — APPROVED** [review]
