### PR TITLE
fix(DB/creature_template): Adjust Flameshocker's values

### LINKED ISSUE #16189: (Creature): Flameshockers are the wrong level.
### Current Behaviour

[Flameshockers](https://wowgaming.altervista.org/aowow/?npc=16383) are levels 53-55.

### Expected Blizzlike Behaviour

They should be level 63.

### Source

Wrath Classic, [Wrath (Classic) Wowhead](https://www.wowhead.com/wotlk/npc=16383), [Wowpedia patch changes](https://wowpedia.fandom.com/wiki/Flameshocker#Patch_changes)

### Steps to reproduce the problem

1. `.npc add temp 16383`
2. Observe their level.

### Extra Notes

Original level range I assume came from the Vanilla run of the Scourge invasion, don't know what if anything else is also using the 1.12 data in AC's DB.

### AC rev. hash/commit

d282cce4af69110fa035954b3c81258a1e560b5e

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

### PR DESCRIPTION
**Pull request by Si1ker**
## Issues Addressed:

- Closes #16189

## SOURCE:

[patch 3.0.2](https://wowpedia.fandom.com/wiki/Flameshocker#Patch_changes)
[mangos](https://github.com/cmangos/mangos-tbc/search?q=EVENT_MINION_FLAMESHOCKERS_TOUCH)

## Tests Performed:

- Tested

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1683530792489127900.sql [hunk 1]
```diff
@@ -0,0 +1,12 @@
...
+
+DELETE FROM `creature_template_addon` WHERE entry=16383;
+INSERT INTO `creature_template_addon` (`entry`, `auras`) VALUES (16383, '28330');
+
+DELETE FROM `smart_scripts` WHERE `entryorguid`=16383;
+INSERT INTO `smart_scripts` (`entryorguid`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `target_type`, `comment`) VALUES 
+(16383, 2000, 2000, 30000, 45000, 11, 28314, 2, 'Flameshocker - In Combat - Cast Victim `Flameshocker\'s Touch`');
+INSERT INTO `smart_scripts` (`entryorguid`, `id`, `event_type`, `action_type`, `action_param1`, `action_param2`, `target_type`, `comment`) VALUES 
+(16383, 1, 6, 11, 28323, 2, 1, 'Flameshocker - On Death - Cast Victim `Flameshocker\'s Revenge`');
+
```
Comment (Gultask) [inline data/sql/updates/pending_db_world/rev_1683530792489127900.sql:12]: 1. When deleting, always specify the source_type as well
2. Also this insert is a bit... well, try adding the Keira output instead :P 
```suggestion
DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `entryorguid` = 16383);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(16383, 0, 0, 0, 0, 0, 100, 0, 5000, 10000, 10000, 20000, 0, 11, 28314, 32, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Flameshocker - In Combat - Cast \'Flameshocker`s Touch\''),
(16383, 0, 1, 0, 6, 0, 100, 0, 0, 0, 0, 0, 0, 11, 28323, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Flameshocker - On Just Died - Cast \'Flameshocker`s Revenge\'');
```

File: data/sql/updates/pending_db_world/rev_1683530792489127900.sql [hunk 2]
```diff
@@ -0,0 +1,12 @@
+--
+UPDATE `creature_template` SET `minlevel`=63, `maxlevel`=63, `AIName`='SmartAI' WHERE  `entry`=16383;
+
+DELETE FROM `creature_template_addon` WHERE entry=16383;
+INSERT INTO `creature_template_addon` (`entry`, `auras`) VALUES (16383, '28330');
```
Comment (Gultask) [inline data/sql/updates/pending_db_world/rev_1683530792489127900.sql:5]: backtick
```suggestion
DELETE FROM `creature_template_addon` WHERE `entry`=16383;
INSERT INTO `creature_template_addon` (`entry`, `auras`) VALUES (16383, '28330');
```

File: data/sql/updates/pending_db_world/rev_1683530792489127900.sql (hunk 1 above)
Comment (heyitsbench) [reply data/sql/updates/pending_db_world/rev_1683530792489127900.sql]: `smart_scripts` insert needed adjusting but not `creature_template_addon`? Also, might want to stick whatever the issue is with that insert in the wiki.

**Review by Gultask — APPROVED** [review]
