### PR TITLE
fix(Core/Spells): Always melee attack target when charge is over.

### LINKED ISSUE #7266: Warrior/Druid Charges Occasionally Delaying Autoattacks
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [x] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1358

When you charge your auto attack is delayed by ~2-3sec.

This doesn't seem to always happen though. I changed weapons thinking maybe it might be different with a dagger...
First charge against a critter and I attacked right away as I should. Second charge at the next target and the auto attack was delayed again. Swapped back to my axe and the delay was there the whole time again.

The first two sessions I'd spent leveling this warrior I hadn't noticed any problem at all... So yeah. Inconsistent, but horrible.

https://youtu.be/Gr1AJx5TXIY

Screenshot of the ingame combatlog with timestamps, and then the combatlog text file when i figured it would have better timestamps.

[WoWCombatLog.txt](https://github.com/chromiecraft/chromiecraft/files/6950215/WoWCombatLog.txt)
Chargelog

Tester: confirmed. Oddly enough, it was very rare when tried on a target dummy, but vs low level mobs it was happening quite frequently, every 5-10 pulls or so. It happened with various weapons - 2H sword, 2H axe, 1H dagger, 1H mace, 1H sword. 

https://user-images.githubusercontent.com/81782124/128706680-b72e4a46-97bb-4a8f-938a-d706b7307b5e.mp4

It also happens using druid's bear form charge. Most bear charges work fine, with an immediate autoattack delivered, but a noticeable number pause for a few seconds as well.

I've also tacked on some footage of cat's feral charge, which was even odder, in that it didn't start autoattacks at all - my footage shows attacks on yellow/neutral mobs, but it behaved the same way on red ones too. This is a bit surprising since the charge dazes them, which you'd think would cause hostility. This may be a separate issue altogether, or I may be misunderstanding cat feral charge.

https://user-images.githubusercontent.com/81782124/128706687-25985606-9839-47a4-8f95-1da0423fe5ea.mp4

### Expected Blizzlike Behaviour

An auto attack should happen as soon as you're in range of the target.

### Source

Consistency. The majority of charges are followed by an immediate autoattack as it is, so it's reasonable to assume they all should be.

### Steps to reproduce the problem

1. Be a warrior or a druid.
2. Charge something.
3. It'll either happen or it won't.

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36a1777b99c400484537c358af8fa6b3a42b13c7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Fixed #7266

## Changes Proposed:
-  Sometimes melee attack was not processed because of `UNIT_STATE_CANNOT_ATTACK` state that includes `UNTI_STATE_CHARGING` and that state was not always cleared out correctly.

## Issues Addressed:

- Closes #7266
- Closes https://github.com/chromiecraft/chromiecraft/issues/1358

## Tests Performed:

- Tested ingame

## How to Test the Changes:

1. Be a warrior or a druid.
2. Charge something.
3. When charge is over, warrior/druid should always melee attack target.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/game/Movement/MovementGenerators/PointMovementGenerator.cpp [hunk 1]
```diff
@@ -139,6 +139,9 @@ void PointMovementGenerator<T>::DoFinalize(T* unit)
     if (id == EVENT_CHARGE)
     {
         unit->ClearUnitState(UNIT_STATE_CHARGING);
+
+        if (Unit* target = ObjectAccessor::GetUnit(*unit, _chargeTargetGUID))
+            unit->Attack(target, true);
```
Comment (FrancescoBorzi) [inline src/server/game/Movement/MovementGenerators/PointMovementGenerator.cpp:144]:
```suggestion
        if (Unit* target = ObjectAccessor::GetUnit(*unit, _chargeTargetGUID))
        {
            unit->Attack(target, true);
        }
```

**Review by FrancescoBorzi — APPROVED** [review]
