### PR TITLE
fix(DB/Loot)Add missing heavy stone loot entries

### LINKED ISSUE #20967: Mob Loot Tables - Heavy Stone
What client do you play on?
enUS

Faction
Alliance

Content Phase:
30-39

Current Behaviour
Heavy Stone is not dropping from any of the mobs that you'd normally kill to farm heavy stone
https://www.wowhead.com/wotlk/item=2838/heavy-stone#dropped-by;0-11-3-10+1
https://wowgaming.altervista.org/aowow/?item=2838#dropped-by:0-8+1

Expected Blizzlike Behaviour
https://wowgaming.altervista.org/aowow/?npc=2359
https://wowgaming.altervista.org/aowow/?npc=4120
https://wowgaming.altervista.org/aowow/?npc=6073
should all have a ~25% chance to drop Heavy Stone

Source
https://www.wowhead.com/wotlk/item=2838/heavy-stone#dropped-by;0-11-3-10+1

Steps to reproduce the problem
attempt killing:
.go creature id 2359
.go creature id 4120
.go creature id 6073

Extra Notes

https://wowgaming.altervista.org/aowow/?npc=2359#drops - Does not have "Heavy Stone" in drop tables from source. But according to https://www.wowhead.com/wotlk/npc=2359/elemental-slave#drops tables and comments it does.

DB does not have Heavy Stone 2838 in loot table.

https://www.wowhead.com/wotlk/npc=4120/thundering-boulderkin - per wowhead also has Heavy Stone.
https://www.wowhead.com/wotlk/npc=6073/searing-infernal - Should have Heavy Stone per Wowhead as well.

DB does not show Heavy Stone in either of their loot tables.

AC rev. hash/commit
https://github.com/azerothcore/azerothcore-wotlk/commit/a23b13defea47fa806b85074d108eaf19561ee50

Operating system
Ubuntu 22.04

Modules
[mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
[mod-anticheat](https://github.com/azerothcore/mod-anticheat)
[mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
[mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
[mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
[mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
[mod-cfbg](https://github.com/azerothcore/mod-cfbg)
[mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
[mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
[mod-costumes](https://github.com/azerothcore/mod-costumes)
[mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
[mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
[mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
[mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
[mod-eluna](https://github.com/azerothcore/mod-eluna)
[mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
[mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
[mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
[mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
[mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
[mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
[mod-progression-system](https://github.com/azerothcore/mod-progression-system)
[mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
[mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
[mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
[mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
[mod-transmog](https://github.com/azerothcore/mod-transmog)
[mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
[mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
[lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
[lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
[lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
[lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
[lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
[lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
[lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
[lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
Customizations
None

Server
ChromieCraft
https://github.com/chromiecraft/chromiecraft/issues/7575

### PR DESCRIPTION
**Pull request by Exitare**
Adds missing creature loot entries for Heavy stones and update min and max count for existing entries. 
I did not change drop chances for entries that had pretty specific ones like 2.66 or similar. I assume that these values are from sniffs, otherwise they would be oddly specific.  

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #20967

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. 
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1734571285903931000.sql [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+(623, 2838, 0, 1, 0, 1, 0, 1, 1, 'Heavy Stone -- Skeletal Miner'),
+(674, 2838, 0, 0.9, 0, 1, 0, 1, 3, 'Heavy Stone -- Venture CO Stripminer'),
+(1094, 2838, 0, 0.9, 0, 1, 0, 1, 3, 'Heavy Stone -- Venture CO Miner'),
+(4849, 2838, 0, 0.81, 0, 1, 0, 1, 3, 'Heavy Stone -- Shadowforge Archaeologist'),
+(3586, 2838, 0, 0.8, 0, 1, 0, 1, 1, 'Heavy Stone -- Miner Johnson'),
+(1167, 2838, 0, 0.8, 0, 1, 0, 1, 1, 'Heavy Stone -- Stonesplinter Digger'),
+(1393, 2838, 0, 0.6, 0, 1, 0, 1, 1, 'Heavy Stone -- Beserk Trogg'),
+(14427, 2838, 0, 0.4, 0, 1, 0, 3, 3, 'Heavy Stone -- Gibblesnik');
+
+
```
Comment (Grimdhex) [inline data/sql/updates/pending_db_world/rev_1734571285903931000.sql:25]: 3 extra lines to remove

**Review by Grimdhex — CHANGES_REQUESTED** [review]

File: data/sql/updates/pending_db_world/rev_1734571285903931000.sql [hunk 2]
```diff
@@ -0,0 +1,26 @@
+--
+DELETE FROM `creature_loot_template` WHERE (`Entry` IN (2359, 4120, 6073, 4499, 824, 624, 2450, 4113, 2269, 4844, 4846, 623, 674, 1094, 4849, 3586, 1167, 1393, 14427)) AND (`Item` IN (283));
+
```
Comment (Grimdhex) [inline data/sql/updates/pending_db_world/rev_1734571285903931000.sql:3]: Also another extra lines

**Review by Grimdhex — CHANGES_REQUESTED** [review]

**Review by Grimdhex — APPROVED** [review]
