### PR TITLE
fix(DB/Creature): lowers max level of Fen Dweller

### LINKED ISSUE #8001: [Wetlands] Fen Dweller 5 levels higher than it can be
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1805

WoWScrnShot_091621_064712
)

### Expected Blizzlike Behaviour

Lvl range is 20-21 (as it is for every other mob around them)

### Source

correct: https://tbc.wowhead.com/npc=1039/fen-dweller
incorrect: https://wotlkdb.com/?npc=1039

Testers note:
See current behaviour [here](https://wowgaming.altervista.org/aowow/?npc=1039)

[Wowpedia](https://wowpedia.fandom.com/wiki/Fen_Dweller?oldid=1762015) also mentions lvl range of 20-21

### Steps to reproduce the problem
1. ``` .go c 11128```, ```.go c 10636```

Look around either of those and you should *maybe* see an above level.

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by jamadaha**
## Changes Proposed:
-  Sets max level of Fen Dwellers to 21

## Issues Addressed:

- Closes #8001
- Closes https://github.com/chromiecraft/chromiecraft/issues/1805

## Tests Performed:

- Done as below

## How to Test the Changes:

1. Verify one changed row on running SQL query
2. Check DB for the change ```SELECT * FROM `creature_template` WHERE `entry` = 1039;```
3. Check in game 
     GUIDs: 9961, 9962, 10600, 10602, 10603, 10604...

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by T1ti** [comment]
https://classic.wowhead.com/npc=1041/fen-lord#abilities

They are summoned by level 25/26 creatures, since they are pets and have the owner's level, I guess this explains why they were sniffed as lvl 26

**Comment by T1ti** [comment]
https://web.archive.org/web/20101119065201/https://www.wowhead.com/npc=1039/fen-dweller

I found this archvied version of wowhead in 2010, they were amrked as lvl 21-26

**Comment by jamadaha** [comment]
A note for that archive source is that according to [Wowpedia](https://wowpedia.fandom.com/wiki/Fen_Dweller) the mob was removed 4 days after, with the release of Patch 4.0.3a.
Tho, as said, the removal was after the archive source. So I'm not certain whether that's relevant.

File: data/sql/updates/pending_db_world/rev_1632156508775520500.sql [hunk 1]
```diff
@@ -0,0 +1,3 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1632156508775520500');
+
+UPDATE `creature_template` SET `maxlevel` = 21 WHERE `entry` = 1039 AND `name` LIKE '%Fen Dweller%';
```
Comment (Helias) [inline data/sql/updates/pending_db_world/rev_1632156508775520500.sql:3]: `AND `name` LIKE '%Fen Dweller%'`
I don't think this is necessary, because the entry is already unique

Comment (jamadaha) [reply data/sql/updates/pending_db_world/rev_1632156508775520500.sql]: true, fixed.

**Comment by FrancescoBorzi** [comment]
what's the status of this?

**Comment by jamadaha** [comment]
It is a matter of what source is correct: [wowhead](https://tbc.wowhead.com/npc=1039/fen-dweller)/[wowpedia](https://wowpedia.fandom.com/wiki/Fen_Dweller?oldid=1762015) or [wowhead(waybackmachine)](https://web.archive.org/web/20101119065201/https://www.wowhead.com/npc=1039/fen-dweller)

**Comment by Nyeriah** [comment]
It’s the same issue we had with Moonstalker Hunts and Moonstalker Matriarches. I believe the spell used to summon them should take care of their level assignment, but I don’t have enough information on that. I believe this is PR is fine.
