### PR TITLE
fix(Scripts/Midsummer): correctly despawn gameobjects

### LINKED ISSUE #19268: The CPU usage of the worldserver process is increasing again.
### Current Behaviour

After compiling using the [0c747bc](https://github.com/azerothcore/azerothcore-wotlk/commit/0c747bc92537e80fe21093a3d95af5187223f7d5) version on June 28th, it was found that the CPU usage of the Worldserver process had once again increased.
Under normal circumstances, when there were 5 online users, the CPU usage rate of WorldServer was around 30%, but it has now risen to over 80%.
cpu-2024-07-04-02

At the same time, the last 500 diffs summary value displayed on the console has also significantly increased.
cpu-2024-07-04-01

When normal the last 500 diffs summary value 
mean:12-15
median:11-12
percentiles:18,24,131

### Expected Blizzlike Behaviour

Restore normal CPU usage

### Source

_No response_

### Steps to reproduce the problem

1. Run Worldserver compiled on June 10th and June 28th, respectively,
2. Launch the game and observe the last 500 diffs summary value on the console
3. Run TOP to check the CPU usage difference of the world server process.

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/0c747bc92537e80fe21093a3d95af5187223f7d5

### Operating system

ubuntu 18.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by sudlud**
## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #19268
- Follow-Up to #18860

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/scripts/Events/firework_show/firework_show.cpp [hunk 1]
```diff
@@ -174,6 +174,13 @@ struct go_firework_show : public GameObjectAI
                 _show->spawns.entries[posIdx].rot2,
                 _show->spawns.entries[posIdx].rot3,
                 0);
```
Comment (PkllonG) [inline src/server/scripts/Events/firework_show/firework_show.cpp:176]: 1000);
Isn't it feasible to add time here?

**Review by Nyeriah — APPROVED** [review]
