### PR TITLE
fix(DB/gameobject) Strange lockbox position and add Bubbly Fissure

### LINKED ISSUE #4352: [Horde] Box in fatigue zone for quest Trial of the Sea Lion
##### SMALL DESCRIPTION:
When you try to find [Half Pendant of Aquatic Endurance](https://classic.wowhead.com/item=15882/half-pendant-of-aquatic-endurance), it should be located at Silverpine Forest (30, 29) near to a bubble area. Bubbles spot is missing and the box is forward, after the fatigue limit.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
A bubble area and a loot box containing the item [Half Pendant of Aquatic Endurance](https://classic.wowhead.com/item=15882/half-pendant-of-aquatic-endurance) [Retail video](https://www.youtube.com/watch?v=ahnJOD3NsUE)
No fatigue, bubble spot near the box with coordinates [30, 30])
imagen

##### CURRENT BEHAVIOUR:
Fatigue, no bubble spot and box is in coordinates [26, 30])
imagen

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a druid and take the quest [Trial of the sea lion](https://classic.wowhead.com/quest=30/trial-of-the-sea-lion)
2. Go to Silverpine Forest, at coordinates [30, 29], near the great sea.
3. No box to be looted, just the under sea.

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/9d307c71a6

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/96197962-horde-box-in-fatigue-zone-for-quest-trial-of-the-sea-lion?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nicoaravena**
Fix position of Strange Lockbox for quest https://classic.wowhead.com/quest=30/trial-of-the-sea-lion
Actual position was based on classic content, after TBC the position was moved from fatigue zone and added a Bubbly Fissure.

Closes AzerothCore issue #4352

More info: https://wowwiki-archive.fandom.com/wiki/Quest:Trial_of_the_Sea_Lion_(Horde) and https://www.wowhead.com/quest=30/trial-of-the-sea-lion

## Changes Proposed:
-  Move from fatigue zone the Strange Lockbox
-  Add Bubbly fissure near the lockbox.

## Issues Addressed:
- Closes #4352

## Tests Performed:
- Applied the SQL
- Then `.go o 27813`

## How to Test the Changes:
- Take the quest [Trial of the sea lion](https://www.wowhead.com/quest=30/trial-of-the-sea-lion)
- Then `.go o 27813`
- There should be the Strange Lockbox near a Bubbly Fissure (no fatigue zone).
- Loot the pendant inside.

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1612566366687490200.sql [hunk 1]
```diff
@@ -0,0 +1,9 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1612566366687490200');
+
+-- Relocate Strange Lockbox and add Bubbly Fissure near it.
+
+DELETE FROM `gameobject` WHERE (`id` = 177790) AND (`guid` IN (27813));
+INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`) VALUES
+(27813, 177790, 0, 0, 0, 1, 1, 842.715, 2208.32, -136.765, 1.57, 0, 0, 0.994174, -0.107791, 50, 100, 1, '', 0);
+INSERT INTO `gameobject` (`id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`) VALUES
+(177524, 0, 0, 0, 1, 1, 838.26, 2208.14, -136.906, 0, 0, 0, -0.753998, -0.656877, 300, 0, 1, '', 0);
```
Comment (Kitzunu) [inline data/sql/updates/pending_db_world/rev_1612566366687490200.sql:9]: Fix the sql please

**Review by Kitzunu — CHANGES_REQUESTED** [review]

File: data/sql/updates/pending_db_world/rev_1612566366687490200.sql (hunk 1 above)
Comment (nicoaravena) [reply data/sql/updates/pending_db_world/rev_1612566366687490200.sql:9]: Sure, but what do you need? I used the Keira result to make it so I assume it has something wrong.

File: data/sql/updates/pending_db_world/rev_1612566366687490200.sql [hunk 2]
```diff
@@ -0,0 +1,8 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1612566366687490200');
+
+-- Relocate Strange Lockbox and add Bubbly Fissure near it.
+
+UPDATE `gameobject` SET `position_x` = 842.715, `position_y` = 2208.32, `position_z` = -136.765 WHERE `guid` = 27813;
+INSERT INTO `gameobject` (`id`, `position_x`, `position_y`, `position_z`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`) VALUES
+(177524, 838.26, 2208.14, -136.906, -0.753998, -0.656877, 900, 100, 1);
```
Comment (Kitzunu) [inline data/sql/updates/pending_db_world/rev_1612566366687490200.sql:7]: You need to insert a GUID too. It is a Primary key of creature.
Nothing can be spawned without a spawnid

Comment (Kitzunu) [reply data/sql/updates/pending_db_world/rev_1612566366687490200.sql:7]: And always delete before insert

Comment (nicoaravena) [reply data/sql/updates/pending_db_world/rev_1612566366687490200.sql:7]: I can't delete an object that it never existed, this is a new gameobject for that bubbly. Also this table has auto-increment, so I don't think it is a good idea to create an specific id.

Comment (Kitzunu) [reply data/sql/updates/pending_db_world/rev_1612566366687490200.sql:7]: We always delete before insert, codestyle of AC. Same as we always assign a GUID to a spawn.

Comment (nicoaravena) [reply data/sql/updates/pending_db_world/rev_1612566366687490200.sql:7]: A codestyle can't be inferred by the code/PRs, it is a must to have this documented somewhere (there is nothing related in the wiki). It will help new contributors to just follow that and don't mess up while creating a PR (like me).

Comment (nicoaravena) [reply data/sql/updates/pending_db_world/rev_1612566366687490200.sql:7]: Also for the GUID, there is no info about on how to generate a proper GUID. The one that is generated by Keira is not the one from the auto-increment and not even related to the last GUID.

**Review by FrancescoBorzi — APPROVED** [review]
