### PR TITLE
fix(Scripts/Stormpeaks): Add Oathbound Warder pet abilities

### LINKED ISSUE #8529: Oathbound Warder summons lack their abilities
### Current Behaviour

The [Oathbound Warders](https://www.wowhead.com/wotlk/npc=30270/oathbound-warder) spawned using [Horn of the Peaks](https://www.wowhead.com/wotlk/item=42840/horn-of-the-peaks) provided for [The Earthen Oath](https://www.wowhead.com/wotlk/quest=13005/the-earthen-oath) and [Loken's Lackeys ](https://www.wowhead.com/wotlk/quest=13035/lokens-lackeys) lack any abilities, making these quests much more difficult to complete than they should be.

### Expected Blizzlike Behaviour

The [Oathbound Warder](https://www.wowhead.com/wotlk/npc=30270/oathbound-warder) summons should possess the following abilities:

- [Earth Shield](https://www.wowhead.com/wotlk/spell=56451/earth-shield)
- [Earth Shock](https://www.wowhead.com/wotlk/spell=56506/earth-shock)
- [Earth's Grasp](https://www.wowhead.com/wotlk/spell=56425/earths-grasp)
- [Lava Burst](https://www.wowhead.com/wotlk/spell=56491/lava-burst)

### Source

Here's a video from WotLK classic showing the summons being used and possessing all of their abilities.
https://www.youtube.com/watch?v=Ot6hZqYxhJA

### Steps to reproduce the problem

- Use [Horn of the Peaks](https://www.wowhead.com/wotlk/item=42840/horn-of-the-peaks) at the Terrace of the Makers
- Your [Oathbound Warders](https://www.wowhead.com/wotlk/npc=30270/oathbound-warder) will have no abilities

### Extra Notes

I did check to see if this was reported already and found this issue https://github.com/chromiecraft/chromiecraft/issues/7842 which was closed as resolved, but the issue of the Oathbound Warders lacking their abilities still persists.

### Customizations

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/9429817e82f95eb285b2ac31fa706d464fd0b662

### Operating system

Ubuntu 20.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-chromiecraft-smartstone](https://github.com/chromiecraft/mod-chromiecraft-smartstone)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-evade-logging](https://github.com/heyitsbench/mod-evade-logging)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-quests](https://github.com/azerothcore/mod-pvp-quests)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Server

ChromieCraft

### LINKED ISSUE #24061: [StormPeaks Quest] Oathbound Warder summons lack their abilities
### Current Behaviour

The [Oathbound Warders](https://www.wowhead.com/wotlk/npc=30270/oathbound-warder) spawned using [Horn of the Peaks](https://www.wowhead.com/wotlk/item=42840/horn-of-the-peaks) provided for [The Earthen Oath](https://www.wowhead.com/wotlk/quest=13005/the-earthen-oath) and [Loken's Lackeys ](https://www.wowhead.com/wotlk/quest=13035/lokens-lackeys)lack any abilities, making these quests much more difficult to complete than they should be.

### Expected Behaviour

The [Oathbound Warder](https://www.wowhead.com/wotlk/npc=30270/oathbound-warder) summons should possess the following abilities:

[Earth Shield](https://www.wowhead.com/wotlk/spell=56451/earth-shield)
[Earth Shock](https://www.wowhead.com/wotlk/spell=56506/earth-shock)
[Earth's Grasp](https://www.wowhead.com/wotlk/spell=56425/earths-grasp)
[Lava Burst](https://www.wowhead.com/wotlk/spell=56491/lava-burst)

### Source

https://www.youtube.com/watch?v=Ot6hZqYxhJA
Here's a video from WotLK classic showing the summons being used and possessing all of their abilities.
https://www.youtube.com/watch?v=Ot6hZqYxhJA

### Steps to reproduce the problem

Use [Horn of the Peaks](https://www.wowhead.com/wotlk/item=42840/horn-of-the-peaks) at the Terrace of the Makers
Your [Oathbound Warders](https://www.wowhead.com/wotlk/npc=30270/oathbound-warder) will have no abilities

### Extra Notes

https://github.com/chromiecraft/chromiecraft/issues/8529

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/9429817e82f95eb285b2ac31fa706d464fd0b662

### Operating system

Debian 13

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by blinkysc**
[!] Please Read! This PR comes from AI with [MCP](https://github.com/blinkysc/azerothMCP)

## Changes Proposed:
Adds npc_oathbound_warder script that sets up player-controlled pet action bar spells for Oathbound Warder (30270) summoned by Horn of the Peaks (item 42840).

The pet is fully passive and only casts spells when commanded by the player.

-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/24061
- Closes https://github.com/chromiecraft/chromiecraft/issues/8529

## SOURCE:
The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick).

## Tests Performed:
This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. `.go creature id 30295` (Thorim)
2. `.quest add 13005` (The Earthen Oath)
3. Use Horn of the Peaks item to summon Oathbound Warder
4. Verify pet action bar shows 4 spells: Lava Burst, Earth's Grasp, Earth Shield, Earth Shock
5. Cast spells on a target - pet should cast and remain passive (no auto-attack)

## Known Issues and TODO List:

- [ ] None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1765066149291553835.sql [hunk 1]
```diff
@@ -0,0 +1,9 @@
+--
+UPDATE `creature_template` SET `ScriptName` = 'npc_oathbound_warder' WHERE `entry` = 30270;
+
+DELETE FROM `creature_template_spell` WHERE `CreatureID` = 30270;
+INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES
+(30270, 0, 56491, 12340),
+(30270, 1, 56425, 12340),
+(30270, 2, 56451, 12340),
+(30270, 3, 56506, 12340);
```
Comment (Gultask) [inline data/sql/updates/pending_db_world/rev_1765066149291553835.sql]: VerifiedBuild is 0 unless sniffed
```suggestion
(30270, 0, 56491, 0),
(30270, 1, 56425, 0),
(30270, 2, 56451, 0),
(30270, 3, 56506, 0);
```

**Comment by Gultask** [comment]
Why is the script needed? Seems to work fine with only the changes in creature_template_spell
image

**Comment by blinkysc** [comment]
> Why is the script needed? Seems to work fine with only the changes in creature_template_spell image

They shouldn't attack but only use their abilities when you click them https://www.youtube.com/watch?v=Ot6hZqYxhJA

**Comment by Gultask** [comment]
I got interested and looked a bit further. At this point I'm not sure which approach is better, but it is an alternative.

image

You can achieve the intended behaviour by setting them to NullCreatureAI

image

**Comment by blinkysc** [comment]
> I got interested and looked a bit further. At this point I'm not sure which approach is better, but it is an alternative.
> 
> image
> You can achieve the intended behaviour by setting them to NullCreatureAI
> 
> image

For sure if we can just do it this way I think that would be ideal because less cpp. Testing now and will update here in a bit

**Comment by blinkysc** [comment]
image
Are we able to remove the other abilities as it should be with the template too? It should look like this 
image

**Comment by blinkysc** [comment]
Also seem to get this issue where one will just randomly stand still? I imagine that might be a deeper bug with the template?
 
image

**Review by Nyeriah — APPROVED** [review]
