### PR TITLE
fix(DB/SAI) Clean up event_type in Timed Actionlists

### LINKED ISSUE #2761: Timed Actionlists having event_type different than 0
I run the following query to check what kind of `event_type` our Timed Actionlists have:

```
SELECT  event_type, COUNT(*) FROM smart_scripts WHERE source_type = 9 GROUP BY event_type;
```

The result is:

image

while majority of them have `event_type` set to `0` there are some execptions.

I'm wondering, are all those non-0 timed actionslists a mistake or there is something that I'm missing here?

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/90043705-timed-actionlists-having-event_type-different-than-0?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by malcrom**
## Changes Proposed:
-  Clean up event_type in Timed Actionlists.

## Issues Addressed:
- Closes #2761

### CODE REVIEW

**Review by IntelligentQuantum — APPROVED** [review]

File: data/sql/updates/pending_db_world/rev_1638125279373569035.sql [hunk 1]
```diff
@@ -0,0 +1,4 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1638125279373569035');
+
+-- Fix event_type in Timed Actionlists
+UPDATE `smart_scripts` SET `event_type`=0 WHERE `source_type`=9 AND event_type>0;
```
Comment (Nefertumm) [inline data/sql/updates/pending_db_world/rev_1638125279373569035.sql:4]:
```suggestion
UPDATE `smart_scripts` SET `event_type`=0 WHERE `source_type`=9 AND `event_type`>0;
```

**Review by Nefertumm — APPROVED** [review]
