### PR TITLE
Scripts/Karazhan: Chess Event.

### LINKED ISSUE #779: Core/Script: Karazhan Chess Event [$250]
**Description**:The karazhan chess event does not work

**Current behaviour**: 
If you try to enter and talk to the king of your faction, the event does not start

**Expected behaviour**: Speaking to the king of his own faction, the event should start correctly allowing each player in the raid to take possession of a piece on the board to properly perform the fight.(post a video demonstration of how it should work) https://www.youtube.com/watch?v=b496Mc9A4U0

**Steps to reproduce the problem**:
1. enter karazhan
2. try to start the event by talking to the king of his own faction

**AC hash/commit**: 29f4a1e

**Operating system**: Linux

[Bountysource](https://www.bountysource.com/issues/54545022-bug-chess-event?utm_source=54545022&utm_medium=shield&utm_campaign=ISSUE_BADGE)

<bountysource-plugin>

---
There is a **[$50 open bounty](https://www.bountysource.com/issues/54545022-core-script-karazhan-chess-event?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
## Changes Proposed:
-  Re-taken from #3700
-  Original author is unknown (I will do some research later)

## Issues Addressed:

- Closes #779

## How to test:

- Talk to Medivh.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Curious how/if this works with cross-faction raid groups.

**Comment by acidmanifesto** [comment]
> * Re-taken from [Core/Scripts - Karazhan Init #3700](https://github.com/azerothcore/azerothcore-wotlk/pull/3700)
> * Original author is unknown (I will do some research later)

Original author is Desteny from Oregon Core tbc
https://github.com/OregonCore/OregonCore/commit/c251b9cf4f7d09e5def8cce6f77c8d9b18f9f244

**Comment by heyitsbench** [comment]
[They mentioned it being ported from CMangos, not OregonCore](https://github.com/azerothcore/azerothcore-wotlk/pull/3700#issuecomment-731045480).

**Comment by acidmanifesto** [comment]
> [They mentioned it being ported from CMangos, not OregonCore](https://github.com/azerothcore/azerothcore-wotlk/pull/3700#issuecomment-731045480).

correct. but the files used specifically were a match with oregon core.

**Comment by acidmanifesto** [comment]
Adding Sensitive WIP tag since that means for others with access to NOT UPDATE IT until the author says so.

**Comment by UltraNix** [comment]
It's ready to test.

**Comment by heyitsbench** [comment]
Gave this a quick test. As someone who doesn't entirely know how the chess event should work, it seemed to work pretty well, albeit a very unintelligent Medivh AI. Texts don't seem to all be right, the pieces all say "Greetings [name]", where a TBCC video I looked at showed them having actual text. Medivh gives the text for when he's already been beaten from the start (as in starting a PvP chess match). When pieces are killed, they move to the side of the board and float, don't know if they're supposed to be on the ground or not. AoE/sweep attacks (i.e. from Summoned Daemons) do make a visual connection with those downed pieces. The coffer the player is supposed to receive for winning did spawn once the game was won. Didn't notice any obvious creatures spawned that shouldn't be visible to a player though, so that's good.

**Comment by BeefSteaker** [comment]
.

**Comment by BeefSteaker** [comment]
Building now, will give it a run through.
Would be amazing if we actually have chess working

**Comment by acidmanifesto** [comment]
> Building now, will give it a run through.
> Would be amazing if we actually have chess working

.

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
at current workflow is saying two things:
image
image

**Comment by UltraNix** [comment]
@heyitsbench 
`albeit a very unintelligent Medivh AI`
What do you mean?

`AoE/sweep attacks (i.e. from Summoned Daemons) do make a visual connection with those downed pieces` What "visual connection'?

`The coffer the player is supposed to receive for winning did spawn once the game was won.`
??

**Comment by Maelthyrr** [comment]
Quickly tested. In solo, I was not able to tester another piece than the king. Normally, the king is the only piece available to start the event. But when it starts, the player should be able to leave the king and play another piece. It allows to switch between pieces and play a true game. Otherwise, it seems a really good base.

Here an example: https://youtu.be/KId4O6TlIbs?t=23

But my opinion is maybe to merge the PR like that and go deeper into bugs with news issues based on this PR. What do you think @Nefertumm ?

**Comment by UltraNix** [comment]
`Quickly tested. In solo, I was not able to tester another piece than the king` Maybe because you had debuff, that disallow to use another piece for 8 secs?

**Comment by Maelthyrr** [comment]
> `Quickly tested. In solo, I was not able to tester another piece than the king` Maybe because you had debuff, that disallow to use another piece for 8 secs?

My bad, you're right

**Comment by heyitsbench** [comment]
> heyitsbench What do you mean?

Well playing only as the king, there was nearly no concern of losing the fight, which is not how I've heard it tends to be.

> What "visual connection'?

A visual effect of sweeping damage attacks that appears on afflicted targets.

> ??

The loot that's supposed to spawn when winning (similar to Majordomo's chest) spawned correctly.

**Comment by Gultask** [comment]
Perhaps looking at solo strategies may show a bit on how the Medivh AI is supposed to react in various situations, since these guides will try to provide a consistent strategy.

**Comment by acidmanifesto** [comment]
the oregan core scripts that was used was a mid implemnetation and was not even the final version that the closed pr was attempting to use. it may be best to see what the current script is on mangos or the final revision of oregan core.

**Comment by UltraNix** [comment]
> > `Quickly tested. In solo, I was not able to tester another piece than the king` Maybe because you had debuff, that disallow to use another piece for 8 secs?
> 
> My bad, you're right. I found others problems, do you want a report here or by opening new issues?

Of course report them here as this is a PR.

**Comment by Maelthyrr** [comment]
Ok sorry for the delay, I've check few things on retail to confirm.

- [X] Move system work fine
- [ ] Direction system
- [ ] Some visuals effect seems missing or incorrect (I've sniff a full game)
- [X] No crash, no errors

I didn't check the spell's effects. 

IA (need more  research on retail to see if we can discern a pattern:
- [ ] In the current script, the game look very fast. The piece move one after the other. One retail you have a delay of a few seconds between each medhiv move.
- [ ] Medhiv doesn't cheat
- [ ] Actually, you can't lose. Even if you do nothing

**Review by acidmanifesto — APPROVED** [review]

**Comment by UltraNix** [comment]
`A visual effect of sweeping damage attacks that appears on afflicted targets.`
`Some visuals effect seems missing or incorrect (I've sniff a full game)` Tell me exact spells with missing visuals.

**Comment by UltraNix** [comment]
`Trivial - Direction system: you should be able to got only 4 direction (front, back, left, right). Actually, your piece your person can look diagonally.`
https://youtu.be/sdQgYyq92nk?t=183

**Comment by UltraNix** [comment]
` Medhiv doesn't cheat` Of course he does. You have 3 possible cheats and it's random.

**Comment by Maelthyrr** [comment]
> `Trivial - Direction system: you should be able to got only 4 direction (front, back, left, right). Actually, your piece your person can look diagonally.` https://youtu.be/sdQgYyq92nk?t=183

Hmm... The behavior have probably change during expansions, because during my test on retail. It was not the case.

For spell effects, I need to check sniffs. I will look later. And for cheat, you're right. After a few new games, it happens.

**Comment by Gultask** [comment]
Does this currently have support for cross-faction groups?

**Comment by UltraNix** [comment]
Not yet.

File: src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp [hunk 1]
```diff
@@ -0,0 +1,2081 @@
...
+            }
+        }
+        else
+        {
+            me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
+
+            if (Unit* charmer = ObjectAccessor::GetUnit(*me, _charmerGUID))
+            {
+                charmer->RemoveAurasDueToSpell(SPELL_CONTROL_PIECE);
+                charmer->CastSpell(charmer, SPELL_GAME_IN_SESSION, true);
```
Comment (pklloveyou) [inline src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp:1558]:
```
if (instance->GetData(DATA_CHESS_EVENT) != DONE)
    charmer->CastSpell(charmer, SPELL_GAME_IN_SESSION, true);
```

File: data/sql/updates/pending_db_world/rev_1674333933272138700.sql [hunk 2]
```diff
@@ -0,0 +1,238 @@
...
+(16816,9,1,'No matter.',14,0,100,0,0,0,0,0,'Echo of Medivh - Medivh Loose Pawn 2'),
+(16816,9,2,'Interesting.',14,0,100,0,0,0,0,0,'Echo of Medivh - Medivh Loose Pawn 3'),
+(16816,10,0,'A minor concern.',14,0,100,0,0,0,0,0,'Echo of Medivh - Medivh Loose Rook'),
+(16816,11,0,'Yes...of course.',14,0,100,0,0,0,0,0,'Echo of Medivh - Medivh Loose Knight'),
+(16816,12,0,'A necessary sacrifice.',14,0,100,0,0,0,0,0,'Echo of Medivh - Medivh Loose Bishop'),
+(16816,13,0,'Ahh, I should have known.',14,0,100,0,0,0,0,0,'Echo of Medivh - Medivh Loose Queen'),
+(16816,14,0,'And so, the end draws near',14,0,100,0,0,0,0,0,'Echo of Medivh - Medivh Loose King'),
+(16816,15,0,'Nothing less than perfection will do.',14,0,100,0,0,0,0,0,'Echo of Medivh - Checkmate 1'),
+(16816,15,1,'And so it ends.',14,0,100,0,0,0,0,0,'Echo of Medivh - Checkmate 2'),
+(16816,16,0,'The halls of Karazhan shake, as the curse binding the doors of the Gamesman\'s Hall is lifted.',16,0,100,0,0,0,0,0,'Echo of Medivh - Event Ended');
```
Comment (pklloveyou) [inline data/sql/updates/pending_db_world/rev_1674333933272138700.sql:229]:
```sql
INSERT INTO `creature_text` VALUES
(16816,0,0,'Very well. Let the game begin.',14,0,100,0,0,10338,0,0,'Echo of Medivh - EventBegin'),
(16816,1,0,'Perhaps a change is in order.',14,0,100,0,0,10357,0,0,'Echo of Medivh - Cheat 1'),
(16816,1,1,'Time for an alternative scenario.',14,0,100,0,0,10358,0,0,'Echo of Medivh - Cheat 2'),
(16816,1,2,'One must not become too complacent.',14,0,100,0,0,10359,0,0,'Echo of Medivh - Cheat 3'),
(16816,2,0,'%s cheats',16,0,100,0,0,0,21910,0,'Echo of Medivh - CheatEmote'),
(16816,3,0,'Let us see.',14,0,100,0,0,10340,0,0,'Echo of Medivh - Player Loose Pawn 1'),
(16816,3,1,'A transparent stratagem.',14,0,100,0,0,10339,0,0,'Echo of Medivh - Player Loose Pawn 2'),
(16816,3,2,'Ah, the wheels have begun to turn.',14,0,100,0,0,10341,0,0,'Echo of Medivh - Player Loose Pawn 3'),
(16816,4,0,'Foolish! Very foolish!',14,0,100,0,0,10345,0,0,'Echo of Medivh - Player Loose Rook'),
(16816,5,0,'Yes... all according to plan.',14,0,100,0,0,10349,0,0,'Echo of Medivh - Player Loose Knight'),
(16816,6,0,'The slightest loss of concentration is all it takes.',14,0,100,0,0,10347,0,0,'Echo of Medivh - Player Loose Bishop'),
(16816,7,0,'Now it gets interesting.',14,0,100,0,0,10351,0,0,'Echo of Medivh - Player Loose Queen'),
(16816,8,0,'As it should be.',14,0,100,0,0,10354,0,0,'Echo of Medivh - Player Loose King'),
(16816,9,0,'Hmm.',14,0,100,0,0,10342,0,0,'Echo of Medivh - Medivh Loose Pawn 1'),
(16816,9,1,'No matter.',14,0,100,0,0,10344,0,0,'Echo of Medivh - Medivh Loose Pawn 2'),
(16816,9,2,'Interesting.',14,0,100,0,0,10343,0,0,'Echo of Medivh - Medivh Loose Pawn 3'),
(16816,10,0,'A minor concern.',14,0,100,0,0,10346,0,0,'Echo of Medivh - Medivh Loose Rook'),
(16816,11,0,'Yes...of course.',14,0,100,0,0,10350,0,0,'Echo of Medivh - Medivh Loose Knight'),
(16816,12,0,'A necessary sacrifice.',14,0,100,0,0,10348,0,0,'Echo of Medivh - Medivh Loose Bishop'),
(16816,13,0,'Ahh, I should have known.',14,0,100,0,0,10352,0,0,'Echo of Medivh - Medivh Loose Queen'),
(16816,14,0,'And so, the end draws near',14,0,100,0,0,10353,0,0,'Echo of Medivh - Medivh Loose King'),
(16816,15,0,'Nothing less than perfection will do.',14,0,100,0,0,10356,0,0,'Echo of Medivh - Checkmate 1'),
(16816,15,1,'And so it ends.',14,0,100,0,0,10355,0,0,'Echo of Medivh - Checkmate 2'),
(16816,16,0,'The halls of Karazhan shake, as the curse binding the doors of the Gamesman\'s Hall is lifted.',16,0,100,0,0,0,20430,0,'Echo of Medivh - Event Ended');
```

File: src/server/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp [hunk 3]
```diff
@@ -152,6 +177,82 @@ class instance_karazhan : public InstanceMapScript
...
+                                        piece->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
+                                    }
+                                }
+                            }
+                            break;
+                        }
+                        default:
+                            DoRemoveAurasDueToSpellOnPlayers(SPELL_GAME_IN_SESSION);
+                            break;
+                    }
```
Comment (pklloveyou) [inline src/server/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp:219]:
```
 if (value != SPECIAL)
    SetBossState(DATA_CHESS_EVENT, EncounterState(value));
```

File: src/server/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp [hunk 4]
```diff
@@ -181,10 +282,6 @@ class instance_karazhan : public InstanceMapScript
                         DoRespawnCreature(_barnesGUID, true);
                     }
                     break;
-                case DATA_CHESS:
-                    if (state == DONE)
-                        DoRespawnGameObject(DustCoveredChest, DAY);
-                    break;
                 default:
```
Comment (pklloveyou) [inline src/server/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp:285]:
```
case DATA_CHESS_EVENT:
    if (state == DONE)
        if (Creature* medivh = instance->GetCreature(_echoOfMedivhGUID))
            instance->UpdateEncounterState(ENCOUNTER_CREDIT_KILL_CREATURE, NPC_CHESS_STATUS_BAR, medivh);
    break;
```

File: src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp [hunk 5]
```diff
@@ -0,0 +1,2081 @@
...
+            else
+            {
+                _cheatTimer -= diff;
+            }
+        }
+    }
+
+    void sGossipHello(Player* player) override
+    {
+        uint32 chessPhase = _instance->GetData(DATA_CHESS_GAME_PHASE);
```
Comment (pklloveyou) [inline src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp:1350]:
```
 if (_instance->GetBossState(DATA_CHESS_EVENT) == DONE)
    chessPhase = CHESS_PHASE_PVE_FINISHED;
```

File: src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp [hunk 6]
```diff
@@ -0,0 +1,2081 @@
...
+        switch (chessPhase)
+        {
+            case CHESS_PHASE_NOT_STARTED:
+                AddGossipItemFor(player, GOSSIP_ICON_CHAT, "We want to play a game against you!", GOSSIP_SENDER_MAIN, MEDIVH_GOSSIP_START_PVE);
+                break;
+            case CHESS_PHASE_INPROGRESS_PVE:
+            case CHESS_PHASE_INPROGRESS_PVP:
```
Comment (pklloveyou) [inline src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp:1357]: In PVP, if you reset chess, the event will be reset and loot.
```
//case CHESS_PHASE_INPROGRESS_PVP:
```

File: src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp [hunk 7]
```diff
@@ -0,0 +1,2081 @@
...
+        }
+    }
+
+    void sGossipHello(Player* player) override
+    {
+        uint32 chessPhase = _instance->GetData(DATA_CHESS_GAME_PHASE);
+        switch (chessPhase)
+        {
+            case CHESS_PHASE_NOT_STARTED:
+                AddGossipItemFor(player, GOSSIP_ICON_CHAT, "We want to play a game against you!", GOSSIP_SENDER_MAIN, MEDIVH_GOSSIP_START_PVE);
```
Comment (pklloveyou) [inline src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp:1354]: After the repair server is restarted, the event should be PVP
```
if (_instance->GetBossState(DATA_CHESS_EVENT) == DONE)
    AddGossipItemFor(player, GOSSIP_ICON_CHAT, "PvP", GOSSIP_SENDER_MAIN, MEDIVH_GOSSIP_START_PVP); //We'd like to fight each other
else
    AddGossipItemFor(player, GOSSIP_ICON_CHAT, "We want to play a game against you!", GOSSIP_SENDER_MAIN, MEDIVH_GOSSIP_START_PVE);
```

File: src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp (hunk 1 above)
Comment (UltraNix) [reply src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp:1558]: ?? I don;t understand. Here player casts spell, not removes.
If the game is completed, why is he even trying to posses a piece? Even though, the aura be removed once leave the piece.

File: src/server/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp (hunk 3 above)
Comment (UltraNix) [reply src/server/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp:219]: `DATA_CHESS_EVENT` is not a boss.

File: src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp (hunk 7 above)
Comment (UltraNix) [reply src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp:1354]: Repair server - what does it mean?
No need to check boss state.

File: src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp (hunk 1 above)
Comment (pklloveyou) [reply src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp:1558]: I found in the test that when the chess is finished, it will return to the player again.

File: src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp (hunk 7 above)
Comment (pklloveyou) [reply src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp:1354]: Don't we need to save it in 'instance'?

Comment (pklloveyou) [reply src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp:1354]: My English is very bad. You can try it as I say:
1. "We want to play a game against you!"
2. Chess end
3. "PvP"
4. "Restart"
5. You will find that it appears again "We want to play a game against you!"
6. Can be loots again

File: src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp (hunk 1 above)
Comment (pklloveyou) [reply src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp:1558]: 1. "We want to play a game against you!"
2. Chess end
3. Players still have "SPELL_GAME_IN_ESSION"

**Comment by pklloveyou** [comment]
Another mistake is that if you deliberately lose the game in PVP, you can still loot the box in the next game

**Comment by pklloveyou** [comment]
My English is very bad. You can try it as I say:
1. "We want to play a game against you!"
2. Chess end AND loots.
3. "PvP"
4. "Lose the game"
5. You will find that it appears again "We want to play a game against you!"
6. Can be loots again

**Comment by pklloveyou** [comment]
There is another mistake. When you lose or win, many times the chess pieces will not return to their spawning point

File: src/server/game/Spells/SpellInfoCorrections.cpp [hunk 8]
```diff
@@ -4470,7 +4470,15 @@ void SpellMgr::LoadSpellInfoCorrections()
     {
         spellInfo->AttributesEx2 |= SPELL_ATTR2_IGNORE_LINE_OF_SIGHT;
     });
-
+
```
Comment (Nyeriah) [inline src/server/game/Spells/SpellInfoCorrections.cpp:4473]:
```suggestion

```

**Comment by Nyeriah** [comment]
I would like to thank everyone who took the time to test this. Considering the size of this PR, we will be merging it as it is. Further issues will be addressed in the following PRs.

File: src/server/game/Spells/SpellInfoCorrections.cpp [hunk 9]
```diff
@@ -4470,7 +4470,15 @@ void SpellMgr::LoadSpellInfoCorrections()
...
```
Comment (Nyeriah) [inline src/server/game/Spells/SpellInfoCorrections.cpp:4473]:
```suggestion

```

File: src/server/game/Spells/SpellInfoCorrections.cpp [hunk 10]
```diff
@@ -4470,7 +4470,14 @@ void SpellMgr::LoadSpellInfoCorrections()
...
     });
-
+    // Game In Session
+    ApplySpellFix({ 39331 }, [](SpellInfo* spellInfo)
+    {
+        spellInfo->Effects[EFFECT_0].Effect = SPELL_EFFECT_APPLY_AURA;
+        spellInfo->Attributes |= SPELL_ATTR0_NO_AURA_CANCEL;
+        spellInfo->AuraInterruptFlags |= AURA_INTERRUPT_FLAG_CHANGE_MAP;
+    });
+
```
Comment (Nyeriah) [inline src/server/game/Spells/SpellInfoCorrections.cpp:4480]:
```suggestion

```

**Comment by pklloveyou** [comment]
ok

**Comment by BarbzYHOOL** [comment]
wow gg guys
