### PR TITLE
fix(Core/Spells): Fixed displaying "That Glyph is already inscribed i…

### LINKED ISSUE #6342: Cannot use the same glyph on 2 specs
**CURRENT BEHAVIOUR:**
It is not able to activate the same glyph in the 2 specs, it says it is already active in the other spec. 

**EXPECTED BLIZZLIKE BEHAVIOUR:**
The right thing would be to be able to activate in the 2 specs the same glyph.

**SOURCE:**

**STEPS TO REPRODUCING THE PROBLEM:**
1.Activate a glyph on a spec
2. Try activating the same glyph on the other spec.
3. It won't work, it says it's already active in another spec.

**EXTRA NOTES:**

**AC HASH/COMMIT:**
dafef5bd7859

**OPERATING SYSTEM:**
Windows

**MODULES:**
[mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine) 

**OTHER CUSTOMIZATIONS:**
None.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99233612-cannot-use-the-same-glyph-on-2-specs?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
…n your spellbook" when activating the same glyph in different spec.

Fixed #6342

## Changes Proposed:
-  Set corrected glyph on respec.

## Issues Addressed:

- Closes #6342

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

1.Activate a glyph on a spec
2. Try activating the same glyph on the other spec.
3. It won't work, it says it's already active in another spec.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Helias — APPROVED** [review]

File: src/server/game/Entities/Player/Player.cpp [hunk 1]
```diff
@@ -14122,11 +14122,22 @@ void Player::ActivateSpec(uint8 spec)
     }
 
     // xinef: apply glyphs from second spec
-    if(GetActiveSpec() != oldSpec)
+    if (GetActiveSpec() != oldSpec)
+    {
         for (uint8 slot = 0; slot < MAX_GLYPH_SLOT_INDEX; ++slot)
-            if (uint32 glyphId = m_Glyphs[GetActiveSpec()][slot])
+        {
+            uint32 glyphId = m_Glyphs[GetActiveSpec()][slot];
```
Comment (Helias) [inline src/server/game/Entities/Player/Player.cpp:14129]: if you put this `m_Glyphs[GetActiveSpec()]` outside in another variable you avoid to call at any iteration the `GetActiveSpec()` function, up to you I already approved the PR

Comment (UltraNix) [reply src/server/game/Entities/Player/Player.cpp:14129]:
```
uint32 m_Glyphs[MAX_TALENT_SPECS][MAX_GLYPH_SLOT_INDEX];
```
So no - it's not possible in that way :)

**Comment by pklloveyou** [comment]
Tested
