### PR TITLE
fix(DB/smart_scripts): Add roleplay for the quest Set Them Ablaze!

### LINKED ISSUE #6729: [Searing Gorge] Kalaran Windblade missing scripted event after completing quest Set Them blaze!
**Originally reported:** https://github.com/chromiecraft/chromiecraft/issues/1089

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

After Completing the quest Set them Ablaze and turning it in to Squire Maltrake Kalaran Windblade (https://wotlk.evowow.com/?npc=8479) does not transform into Dragon and say his text lines, and neither does Squire Maltrake do his text.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After Completing the quest, there should be scripted event between Kalaran and Maltrake.

##### SOURCE:

https://youtu.be/XgRMniOXs04?t=124
https://classic.wowhead.com/quest=3481/trinkets#comments

https://classic.wowhead.com/npc=8509/squire-maltrake
https://classic.wowhead.com/npc=8480/kalaran-the-deceiver#screenshots

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Searing Gorge and complete the questline starting from Kalaran Windblade
2. Do the quest Set them Ablaze and turn it in
3. Observe no scripted event

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

### PR DESCRIPTION
**Pull request by Efymer**
## Changes Proposed:
Add roleplay missing for the quest 'Set Them Ablaze!' upon returning the quest

## Issues Addressed:

-  Closes #6729
-  Closes https://github.com/chromiecraft/chromiecraft/issues/1089

## SOURCE:
https://youtu.be/XgRMniOXs04?t=124
https://classic.wowhead.com/quest=3463
https://classic.wowhead.com/npc=8509/squire-maltrake
https://classic.wowhead.com/npc=8480/kalaran-the-deceiver#screenshots

## Tests Performed:

- Test in local AzerothCore environment, performs the RP perfectly.

## How to Test the Changes:

1. `.go c id 8509`
2. `.q a 3463`
3. `.q c 3463`
4. Return the quest and check that the RP is performed

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1625434614739025100.sql [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+(8479, 0, 6, 0, 61, 0, 100, 0, 3454, 0, 0, 0, 0, 50, 149410, 60, 1, 0, 0, 0, 8, 0, 0, 0, 0, -6683.73, -1194.19, 240.02, 0.447678, 'Kalaran Windblade - On Quest \'The Torch of Retribution\' Taken - Summon Gameobject \'Light of Retribution\''),
+(8479, 0, 7, 0, 38, 0, 100, 0, 1, 1, 0, 0, 0, 41, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Kalaran Windblade - On Data Set 1 1 - Despawn Instant'),
+(8479, 0, 8, 0, 38, 0, 100, 0, 1, 1, 0, 0, 0, 12, 8480, 3, 68000, 0, 0, 0, 8, 0, 0, 0, 0, -6680.12, -1194.4, 243.255, 3.00197, 'Kalaran Windblade - On Data Set 1 1 - Summon Creature \'Kalaran the Deceiver\'');
+
+-- Respawn time for Kalaran Windblade lowered to 120 it was 900
+UPDATE `creature` SET `spawntimesecs` = 120 WHERE (`ID` = 8479);
+
+
+-- Kalaran the Deceiver
+UPDATE `creature_template` SET `AIName` = 'SmartAI', `InhabitType` = 4, `unit_flags` = 33555264 WHERE `entry` = 8480;
```
Comment (Kitzunu) [inline data/sql/updates/pending_db_world/rev_1625434614739025100.sql:32]: Would prefer https://www.azerothcore.org/wiki/sql-standards#flags-amp-bits

**Review by FrancescoBorzi — APPROVED** [review]

File: data/sql/updates/pending_db_world/rev_1625434614739025100.sql (hunk 1 above)
Comment (FrancescoBorzi) [reply data/sql/updates/pending_db_world/rev_1625434614739025100.sql:32]: that's indeed preferred but not mandatory, at least not as long as Keira3 does not generate them that way
