### PR TITLE
fix(Scripts/Naxxramas): fixed invalid horseman state on instance init

### LINKED ISSUE #21122: Boss four horsemen - portal bug
### Current Behaviour

When you defeat the four horsemen, a portal opens that teleports you to the beginning of the instance.
In the case of restarting the server or crashing, the portal is not active again, which makes it difficult to encounter the two remaining bosses sapphiron and kelthuzad. Since it does not give access to the next portal it is necessary to overcome the suburbs.

imagen

### Expected Blizzlike Behaviour

You should keep the portal active, to avoid future inconveniences in the next encounter

### Source

id portal 181578
https://www.wowhead.com/es/object=181578/portal-de-naxxramas

### Steps to reproduce the problem

1- go to the naxxramas instance.
2- defeat the military suburb
3- restart the server
4- go to the place where you defeated the four horsemen

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. [373c442](https://github.com/azerothcore/azerothcore-wotlk/commit/373c442a1db317d3a7fa30882b8055afefe0e332) + 2025-01-08 20:09:28 -0500 (main branch) (Win64, Release, Static)
Connected players: 1. Characters in world: 1.
Connection peak: 1.
Tiempo de actividad del servidor: 3 minute(s) 19 second(s)
Update time diff: 1ms. Last 500 diffs summary:
|- Mean: 2ms
|- Median: 1ms
|- Percentiles (95, 99, max): 6ms, 7ms, 18ms
Using SSL version: OpenSSL 3.0.15 3 Sep 2024 (library: OpenSSL 3.0.15 3 Sep 2024)
Using Boost version: 1.78.0
Using CMake version: 3.16.6
Using MySQL version: 80036
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in data/maps. Total size: 291014951 bytes
vmaps directory located in data/vmaps. Total size: 658130721 bytes
mmaps directory located in data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS .
All available DBC locales: enUS 
Using World DB: ACDB 335.13-dev
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: trasm_world_VendorItems.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-cfbg
|- mod-eluna
|- mod-transmog

### Operating system

Windows 10 x64

### Custom changes or Modules

mod-cfbg
mod-eluna
mod-transmog

### PR DESCRIPTION
**Pull request by Razor2142**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #21122 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/scripts/Northrend/Naxxramas/instance_naxxramas.cpp [hunk 1]
```diff
@@ -94,7 +94,6 @@ class instance_naxxramas : public InstanceMapScript
             PatchwerkRoomTrash.clear();
 
             // Controls
-            _horsemanKilled = 0;
```
Comment (sogladev) [inline src/server/scripts/Northrend/Naxxramas/instance_naxxramas.cpp:97]: implicit cast below, change to initialize to 0 instead
`_horsemanLoadDoneState = false;`

File: src/server/scripts/Northrend/Naxxramas/instance_naxxramas.cpp [hunk 2]
```diff
@@ -167,14 +166,13 @@ class instance_naxxramas : public InstanceMapScript
...
         // Controls
-        uint8 _horsemanKilled;
         uint32 _speakTimer;
         uint32 _horsemanTimer;
         uint32 _screamTimer;
         bool _hadThaddiusGreet;
         EventMap events;
         uint8 _currentWingTaunt;
-        bool _horsemanLoadDoneState;
+        uint8_t _horsemanLoadDoneState;
```
Comment (sogladev) [inline src/server/scripts/Northrend/Naxxramas/instance_naxxramas.cpp:175]: uint8; This keeps a count of the loaded horsemen can you update the name to reflect this? e.g., `horsemenLoaded`

File: src/server/scripts/Northrend/Naxxramas/instance_naxxramas.cpp [hunk 3]
```diff
@@ -681,13 +686,25 @@ class instance_naxxramas : public InstanceMapScript
             }
 
             // Horseman handling
-            if (bossId == BOSS_HORSEMAN && !_horsemanLoadDoneState)
+            if (bossId == BOSS_HORSEMAN && _horsemanLoadDoneState == 4)
             {
+                uint8 horsemanKilled {};
```
Comment (sogladev) [inline src/server/scripts/Northrend/Naxxramas/instance_naxxramas.cpp:691]: _horsemanKilled already exists. Do you think this can be used here instead?

**Review by sogladev — CHANGES_REQUESTED** [review]
Tested, it works; needs some minor changes

File: src/server/scripts/Northrend/Naxxramas/instance_naxxramas.cpp [hunk 4]
```diff
@@ -25,6 +25,8 @@
 #include "ScriptedCreature.h"
 #include "naxxramas.h"
 
+static inline constexpr uint8_t HorsemanCount = 4;
```
Comment (Kitzunu) [inline src/server/scripts/Northrend/Naxxramas/instance_naxxramas.cpp:28]: uint8, also constexpr is implicitly inline in c++ so you do not need to specify it here.

File: src/server/scripts/Northrend/Naxxramas/instance_naxxramas.cpp [hunk 5]
```diff
@@ -167,14 +168,13 @@ class instance_naxxramas : public InstanceMapScript
...
         // Controls
-        uint8 _horsemanKilled;
         uint32 _speakTimer;
         uint32 _horsemanTimer;
         uint32 _screamTimer;
         bool _hadThaddiusGreet;
         EventMap events;
         uint8 _currentWingTaunt;
-        bool _horsemanLoadDoneState;
+        uint8_t _horsemanLoaded;
```
Comment (Kitzunu) [inline src/server/scripts/Northrend/Naxxramas/instance_naxxramas.cpp:177]: uint8

**Review by sogladev — APPROVED** [review]
