### PR TITLE
fix(DB): Goblin pit crew's gossip probability

### LINKED ISSUE #5408: Missing text from Goblin Pit Crewman
## CURRENT BEHAVIOUR:

Missing text from Goblin Pit Crewman

"Greetings Lanaya" when you ask "Where is Tirth's Assistant?"

WoWScrnShot_042321_122124

## EXPECTED BLIZZLIKE BEHAVIOUR:

Should be available only during this Mage quest, and direct people to the NPC.

## SOURCE:

https://classic.wowhead.com/quest=1950/get-the-scoop#comments

https://youtu.be/5gFzA3p40vg

## STEPS TO REPRODUCE THE PROBLEM:

1. Go to Mirage Raceway or spawn a Goblin Pit Crewman
2. Speak to them + click dialogue options
3. 

## AC HASH/COMMIT:

AzerothCore rev. b8b5f68f98ff 2021-04-19 06:49:48 +0000 (master branch) 

## CUSTOMIZATIONS:

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98033296-missing-text-from-goblin-pit-crewman?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:
- Since these guys have 5 possible gossip options, setting this to 25
  each option will equal to 100 percentage.
- There are plenty more gossips like this one only have % of 1 to show
  that need to me manually fixed since we don't know how many npc_text
  they may have. A query to count the text_x_x and update the according
  % should be good to go, however this way is safer.

## Issues Addressed:

- Closes #5408

## Tests Performed:

- Not tested

## How to Test the Changes:

1. .go c id 4429
2. Check for several gossip menus and check different texts.

## Known Issues and TODO List:

None.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

File: data/sql/updates/pending_db_world/rev_1640706977785890600.sql [hunk 1]
```diff
@@ -0,0 +1,5 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1640706977785890600');
+
+-- Setting probability to 25% for each of the texts. 5*25 = 100%
+SET @PROBABILITY = 25;
+UPDATE `npc_text` SET Probability0 = @PROBABILITY, Probability1 = @PROBABILITY, Probability2 = @PROBABILITY, Probability3 = @PROBABILITY, Probability4 = @PROBABILITY WHERE `ID` IN (778);
```
Comment (Kitzunu) [inline data/sql/updates/pending_db_world/rev_1640706977785890600.sql:5]: fix sql style

**Review by Kitzunu — CHANGES_REQUESTED** [review]

File: data/sql/updates/pending_db_world/rev_1640706977785890600.sql (hunk 1 above)
Comment (claudiodfc) [reply data/sql/updates/pending_db_world/rev_1640706977785890600.sql]: done

**Review by acidmanifesto — APPROVED** [review]

**Comment by claudiodfc** [comment]
#### Test case - Several Gossip texts

image

image

image

**Review by Kitzunu — APPROVED** [review]
