### PR TITLE
fix(DB/Quest) - Omit deprecated Pledge of Secrecy from Goblin and Gnome Engineering Questlines.

### LINKED ISSUE #19575: (DB/Quest) Pledge of Secrecy Wrong Level Requirement
### Current Behaviour

Currently, unlocking goblin or gnome engineering requires getting the breadcrumb from Ratchet at Level 10, then turning that in to the respective NPC. 

That NPC then gives a quest to Level 30+ players called Pledge of Secrecy, which leads into Show Your Work (the final quest to unlock Gnome/Goblin engineering).

### Expected Blizzlike Behaviour

Pledge of Secrecy either should be removed or require Level 20. At a bare minimum, we know the quests should have required 20 and not 30 as of patch 3.2.2.

### Argument for Removal
However, in the database for patch 3.3.5, all 3 quests called Pledge of Secrecy are flagged as unavailable along with other removed quests such as the membership quests for gnome/goblin engineering (quests that are **_currently_** unavailable in AC) and some other obsolete legacy quests.

We know for a fact that as of patch 4.0.1 at the absolute latest, these quests were officially completely removed from the game and it went straight from the breadcrumb to Show Your Work.

### Argument for Lowering Required Level to 20
We also know that as of patch 3.2.2 at the absolute latest, the level requirement had been lowered from 30 to 20. This coincided with the reduction of respec cost. We have comments from users in patch 3.2.2 dated late 2009 that indicate this, with one completing the quest as low as level 21. 

We also have a discussion of this issue that already happened on ChromieCraft where the inconsistency was also identified and labeled as a bug there, but never addressed. Both the player comments and ChromieCraft thread are provided below for your reference. 

### Source

Player comments on Wowhead:
https://www.wowhead.com/wotlk/quest=3638/the-pledge-of-secrecy#comments:id=907253
https://www.wowhead.com/wotlk/quest=3639/show-your-work#comments:id=852864

Previous discussion from ChromieCraft:
https://github.com/chromiecraft/chromiecraft/issues/443#issuecomment-823997168

Relevant quest IDs:
3638 (Goblin Pledge of Secrecy)
3640 (Gnome Pledge of Secrecy 1)
3642 (Gnome Pledge of Secrecy 2)
All flagged as 16384 - QUEST_FLAGS_UNAVAILABLE

### Steps to reproduce the problem

Step 1:
Level a level 20 player to 225 Engineering

Step 2:
Receive the breadcrumb from Tinkerwiz in Ratchet

Step 3:
Turn into Nixx Sprocketspring in Gadgetzan

Step 4:
Observe that no followup is available to you

Step 5:
Increase your character level to 30

Step 6:
Observe that the followup is now available to you

### Extra Notes

We have opened a pull request with the fix for this issue, setting the required level to 20.

### AC rev. hash/commit

AzerothCore rev. 0d977c986ef5 2024-06-19 21:13:34 -0300 (master branch) (Win64, RelWithDebInfo, Static)                                                                                               Connected players: 1. Characters in world: 1.                                                                                                                                                         Connection peak: 1.                                                                                                                                                                                   Server uptime: 47 minute(s) 43 second(s)                                                                                                                                                              Update time diff: 1ms. Last 500 diffs summary:                                                                                                                                                        - Mean: 1ms                                                                                                                                                                                           - Median: 2ms                                                                                                                                                                                         - Percentiles (95, 99, max): 2ms, 3ms, 3ms                                                                                                                                                            Using SSL version: OpenSSL 3.0.14 4 Jun 2024 (library: OpenSSL 3.0.14 4 Jun 2024)                                                                                                                     Using Boost version: 1.81.0                                                                                                                                                                           Using CMake version: 3.29.6                                                                                                                                                                           Using MySQL version: 80037                                                                                                                                                                            Found MySQL Executable: D:/World Of Warcraft/DevLibraries/mysql-8.0.37-winx64/bin/mysql.exe                                                                                                           Compiled on: Windows 10.0.19045                                                                                                                                                                       Worldserver listening connections on port 8085                                                                                                                                                        Realmlist (Realm Id: 1) configured in port 8085                                                                                                                                                       VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1                                                                                                                                   MMAPs status: Enabled                                                                                                                                                                                 maps directory located in D:/World Of Warcraft/AzerothCore/ac-wotlk-build/bin/RelWithDebInfo/Data/maps. Total size: 291014951 bytes                                                                   vmaps directory located in D:/World Of Warcraft/AzerothCore/ac-wotlk-build/bin/RelWithDebInfo/Data/vmaps. Total size: 658130721 bytes                                                                 mmaps directory located in D:/World Of Warcraft/AzerothCore/ac-wotlk-build/bin/RelWithDebInfo/Data/mmaps. Total size: 2192910844 bytes                                                                Default DBC locale: enUS.                                                                                                                                                                             All available DBC locales: enUS                                                                                                                                                                       Using World DB: ACDB 335.11-dev                                                                                                                                                                       Latest LoginDatabase update: 2024_01_20_00.sql                                                                                                                                                        Latest CharacterDatabase update: 2024_01_20_00.sql                                                                                                                                                    Latest WorldDatabase update: 2024_06_18_06.sql                                                                                                                                                        LoginDatabase queue size: 0                                                                                                                                                                           CharacterDatabase queue size: 0                                                                                                                                                                       WorldDatabase queue size: 0                                                                                                                                                                           No modules enabled

### Operating system

Windows 11 x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by Ceikry**
## Changes Proposed:

Update the goblin and gnome engineering questlines to omit the deprecated/legacy "Pledge of Secrecy" quests.

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #19575 

## SOURCE:

The changes have been validated through:
- [x] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

Specific sources listed in linked issue

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [x] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

Follow the steps provided in the linked issue, with one exception: Pledge of Secrecy should be entirely skipped now, going straight from the breadcrumb to Show Your Work.

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1723083294200919589.sql [hunk 1]
```diff
@@ -0,0 +1,9 @@
+-- Bug Report #19575
+-- Update required levels for:
+-- 3638 (Goblin Engineering - Pledge of Secrecy)
+UPDATE `quest_template_addon` SET `MinLevel`=20 WHERE `ID`=3638;
+-- 3640 (Gnome Engineering - Pledge of Secrecy, Alliance)
+UPDATE `quest_template_addon` SET `MinLevel`=20 WHERE `ID`=3640;
+-- 3642 (Gnome Engineering - Pledge of Secrecy, Horde)
+UPDATE `quest_template_addon` SET `MinLevel`=20 WHERE `ID`=3642;
```
Comment (heyitsbench) [inline data/sql/updates/pending_db_world/rev_1723083294200919589.sql:8]: None of these quests exist in a 51831 brute.

Comment (Ceikry) [reply data/sql/updates/pending_db_world/rev_1723083294200919589.sql:8]: Aye, my friend and I (who discovered the issue) were debating removing the quest or just adjusting the level requirements, as both are arguable from the information we uncovered.

Comment (Ceikry) [reply data/sql/updates/pending_db_world/rev_1723083294200919589.sql]: Updated to remove Pledge of Secrecy from the chain instead

**Review by Nyeriah — APPROVED** [review]

**Review by heyitsbench — APPROVED** [review]
