### PR TITLE
Core: Crashfix.

### LINKED ISSUE #6491: new server crash  [$30]
CURRENT BEHAVIOUR:
server crash

STEPS TO REPRODUCE THE PROBLEM:
I don't know how to reproduce it,It crash in about 4-6 hours

EXTRA NOTES:
[gdb.txt](https://github.com/azerothcore/azerothcore-wotlk/files/6690206/gdb.txt)

AC HASH/COMMIT:
47b09f27671d9d04e86cfc996085207c8b5ac177

OPERATING SYSTEM:
ubuntu 20.04
MODULES:
mod-anticheat
mod-multi-client-check-master

<bountysource-plugin>

---
There is a **[$30 open bounty](https://www.bountysource.com/issues/99383452-new-server-crash?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
Fixed #6491.

## Changes Proposed:
-  This is a temp crashfix. The real cause is not known. Player's seer is an invalid (deleted) object.

## Issues Addressed:

- Closes #6491.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/game/Entities/Player/Player.cpp [hunk 1]
```diff
@@ -23544,9 +23544,16 @@ void Player::UpdateObjectVisibility(bool forced, bool fromUpdate)
 
 void Player::UpdateVisibilityForPlayer(bool mapChange)
 {
+    // After added to map seer must be a player - there is no possibility to still have different seer (all charm auras must be already removed)
+    if (mapChange && m_seer != this)
+    {
+        m_seer = this;
```
Comment (FrancescoBorzi) [inline src/server/game/Entities/Player/Player.cpp:23550]: TODO: add an error log here (I've tried doing it via GitHub but the file `Player.cpp` is too big and it does not work)

Comment (claudiodfc) [inline src/server/game/Entities/Player/Player.cpp:23550]: What is m_seer for?

**Comment by FrancescoBorzi** [comment]
I'll add the log error later
