### PR TITLE
fix(Scripts/Temple of AhnQiraj): Slime Toxin clouds should despawn 10…

### LINKED ISSUE #13420: [AQ40] Viscidus Toxin cloud disappear immediately after boss kill.
https://github.com/chromiecraft/chromiecraft/issues/4221
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

NPC: https://wowgaming.altervista.org/aowow/?npc=15299
Viscidus Toxin cloud disappear after boss kill.

Toxin clouds during fight:
изображение

No clouds after boss death:
изображение

### Expected Blizzlike Behaviour

Viscidus Toxin cloud should stay some time after boss death

### Source

https://youtu.be/-tNMCO7_LiY?t=2073

### Steps to reproduce the problem

1. .go c 87938
3. Wait till he creates some Toxin couds.
4. Kill him.
5. Observe that Toxin clouds dissapeares after death.

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Win10 Pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft PTR - AzerothCore rev. 2e6f6e26da8f 2022-10-12 14:39:02 -0400 (master branch) (Unix, Debug, Static)

### PR DESCRIPTION
**Pull request by UltraNix**
… sec after Viscidus death.

Fixes #13420

## Issues Addressed:

- Closes #13420
- Closes https://github.com/chromiecraft/chromiecraft/issues/4221

## Tests Performed:

- Not tested.

## How to Test the Changes:

`.go c 87938`
Wait till he creates some Toxin couds.
Kill him.
Observe that Toxin clouds dissapeares 10 sec after death.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_viscidus.cpp [hunk 1]
```diff
@@ -133,6 +133,17 @@ struct boss_viscidus : public BossAI
         me->RemoveAurasDueToSpell(SPELL_INVIS_SELF);
     }
 
+    void JustDied(Unit* killer) override
```
Comment (acidmanifesto) [inline src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_viscidus.cpp:136]: unused variable killer

**Review by acidmanifesto — CHANGES_REQUESTED** [review]

**Comment by UltraNix** [comment]
@acidmanifesto Done.

**Review by acidmanifesto — APPROVED** [review]

**Comment by Gultask** [comment]
It works 👍
