### PR TITLE
fix(DB/Instance): Fix teleport locations for Ulduar Teleporter

### LINKED ISSUE #7108: Ulduar Teleporter: Some options teleport the player to the wrong location
image

### Current Behaviour

* The "Teleport to the Spark of Imagination" option incorrectly teleports the player to the Descent into Madness
* The "Teleport to the Descent into Madness" option incorrectly teleports the player to the Spark of Imagination

### Expected Blizzlike Behaviour

* The "Teleport to the Spark of Imagination" option should teleport the player to... the Spark of Imagination
* The "Teleport to the Descent into Madness" option should teleport the player to... the Descent into Madness

### Source
https://wowpedia.fandom.com/wiki/Ulduar_Teleporter

### Steps to reproduce the problem
Unlock the Spark of Imagination and Descent Into Madness teleport options, then try using them
1. Kill Flame Leviathan
    * `.go creature 202501`
    * `/target Flame`
    * `.die`
2. Engage Mimiron. You must *engage him*, don't just kill him immediately or the teleporter option will not unlock
    * `.go creature 137630 Mimiron`
    * `/target Mimiron`
    * `/startattack`
3. Kill General Vezax 
    * `.go creature 137581`
    * `/target General`
    * `.die`
4. Go to any Ulduar Teleporter `.go object 34223`
5. Try using the "Teleport to the Spark of Imagination" option. Look at your map and check what zone you're in
6. Try using the "Teleport to the Descent into Madness" option. Look at your map and check what zone you're in

### Extra Notes
I looked in the `smart_scripts` table and the spells associated with each option are correct, but when I cast the spells manually, they take me to the wrong location. To fix this, I need to swap the teleport locations in the `spell_target_position` table

Here are the spells associated with each option for reference:
  * "Teleport to the Spark of Imagination": [Halls of Invention Teleport](https://www.wowhead.com/spell=64025/halls-of-invention-teleport)
  * "Teleport to the Descent Into Madness": [Prison of Yogg-Saron Teleport](https://www.wowhead.com/spell=65042/prison-of-yogg-saron-teleport)

Here's a SQL script that seems to fix this. I just need to test it against the latest production build + get a PR out
```
-- Fix location for spell: 'Halls of Invention Teleport'
UPDATE spell_target_position
    SET PositionX = 2518.22, PositionY = 2569.11, PositionZ = 412.69, Orientation = 3.10668
    WHERE ID = 64025;

-- Fix location for 'Prison of Yogg-Saron Teleport'
UPDATE spell_target_position
    SET PositionX = 1854.8, PositionY = -11.46, PositionZ = 334.57, Orientation = 4.79266
    WHERE ID = 65042;
```

### AC rev. hash/commit

2e6f78bdddbc

Note: I have an ancient commit, so I need someone to confirm that this is still an issue in production. I'm 99% sure it is as I haven't seen any issues open that seem related, and all the references to the teleport spells in the SQL patches or the `base/db_world/` files use the wrong teleport locations in `spell_target_position`

### Operating system

Windows 10

### Custom changes or Modules

mod-autobalance custom build with role-based scaling
mod-ah-bot (custom build from https://github.com/steenburgh/mod-ah-bot/pull/1)
mod-individualxp
mod-1v1-arena

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/100126408-ulduar-teleporter-some-options-teleport-the-player-to-the-wrong-location?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by steenburgh**
Previously, the Ulduar Teleporter locations for the Spark of Imagination and Descent Into Madness options were swapped. This PR fixes that by swapping them back.

See #7108 for more details about the issue

## Issues Addressed:
* Closes #7108

## SOURCE:
This one is pretty obvious. See issue #7108 for more details

## Tests Performed:
* Built + deployed to local windows docker instance
* Ran all tests from 'how to test the changes' section

### Functional: Test that the fix works
Follow the detailed 'steps to reproduce the problem' on issue #7108 - they even include the exact commands you need to type. Verify that the issue can no longer be reproduced.

### Regression: Test that nothing else was broken accidentally
Unlock several other Ulduar Teleporter locations. Verify that they take you to the correct location.
* Instructions for unlocking each location can be found on the [Wow Wiki page for the Ulduar Teleporter](https://wowpedia.fandom.com/wiki/Ulduar_Teleporter)
* Useful GM Commands for testing: `.die`, `.cheat god`, `.modify speed 10`

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1629787955866471200.sql [hunk 1]
```diff
@@ -0,0 +1,11 @@
...
+
+-- Fix location for spell: 'Halls of Invention Teleport'
+UPDATE spell_target_position
+    SET PositionX = 2518.22, PositionY = 2569.11, PositionZ = 412.69, Orientation = 3.10668
+    WHERE ID = 64025;
+
+-- Fix location for 'Prison of Yogg-Saron Teleport'
+UPDATE spell_target_position
+    SET PositionX = 1854.8, PositionY = -11.46, PositionZ = 334.57, Orientation = 4.79266
+    WHERE ID = 65042;
```
Comment (Kitzunu) [inline data/sql/updates/pending_db_world/rev_1629787955866471200.sql:11]: please use backticks =)
