### PR TITLE
fix(Core/Creature): Move hardcoded text/gossips to DB - boss_general_vezax 

### LINKED ISSUE #4158: Core/Creature: hardcoded text in boss_general_vezax
##### CURRENT BEHAVIOUR:

https://github.com/azerothcore/azerothcore-wotlk/blob/79aa5606547d898542557a01a2150f76e477e9e9/src/server/scripts/Northrend/Ulduar/Ulduar/boss_general_vezax.cpp#L89-L95

Need to convert to DB so locales can make use of it

AC HASH/COMMIT: 79aa560
OPERATING SYSTEM: w10

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/95701916-core-creature-hardcoded-text-in-boss_general_vezax?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by avarishd**
Will do more of https://github.com/azerothcore/azerothcore-wotlk/projects/15 in separate PRs, good practice
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes #4158

## Tests Performed:

- Tested in-game, with sound (just to be sure)
- 

## How to Test the Changes:

1. .go c 137581 
2. Pull (with sound enabled)
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nyeriah — APPROVED** [review]

File: src/server/scripts/Northrend/Ulduar/Ulduar/boss_general_vezax.cpp [hunk 1]
```diff
@@ -429,6 +411,10 @@ class npc_ulduar_saronite_vapors : public CreatureScript
                 if( Creature* vezax = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(TYPE_VEZAX)) )
                     vezax->AI()->DoAction(1);
         }
+        void IsSummonedBy(Unit* /*summoner*/) override
+        {
```
Comment (Nyeriah) [inline src/server/scripts/Northrend/Ulduar/Ulduar/boss_general_vezax.cpp:415]: missing a line here

Comment (avarishd) [reply src/server/scripts/Northrend/Ulduar/Ulduar/boss_general_vezax.cpp:416]: I assume this is what you meant?

**Comment by Nyeriah** [comment]
Thank you for your contribution! 👍
