### PR TITLE
fix(Core/Spells): Spells and auras activated by item use should not b…

### LINKED ISSUE #5124: Electromagnetic Gigaflux Reactivator buff not staying [$15]
https://github.com/chromiecraft/chromiecraft/issues/327

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Item Electromagnetic Gigaflux Reactivator ( https://wowgaming.altervista.org/aowow/?item=9492 ) is a cloth helmet that, when used, damages ennemies in front of the player and provides a 10 min buff.
Currently, the buff ( https://wowgaming.altervista.org/aowow/?spell=11841 ) does not stay if you switch helmets after having used the item.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The buff should stay after switching helmets : a comment from wowhead : https://tbc.wowhead.com/spell=11841/static-barrier#comments

##### STEPS TO REPRODUCE THE PROBLEM:

1. Equip Electromagnetic Gigaflux Reactivator
2. Wait 30s, use the item, watch your buffs
3. Switch helms
4. Watch the buff disappear

##### EXTRA NOTES:

N/A

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/9d4eebc61fec3b9701ae94292e8d40962804b676

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
There is a **[$15 open bounty](https://www.bountysource.com/issues/97679133-electromagnetic-gigaflux-reactivator-buff-not-staying?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
…e removed on unequip.

Fixed #5124

## Changes Proposed:
-  Added condition to all spells/auras activated on item use - they should no be removable on item unequip.

## Issues Addressed:

- Closes #5124 
- Closes chromiecraft/chromiecraft#327

## Tests Performed:

- Not tested.

## How to Test the Changes:

1. Equip Electromagnetic Gigaflux Reactivator
2. Wait 30s, use the item, watch your buffs
3. Switch helms
4. Watch the buff do not disappear anymore.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/game/Entities/Player/Player.cpp [hunk 1]
```diff
@@ -8618,8 +8618,17 @@ void Player::ApplyItemEquipSpell(Item* item, bool apply, bool form_change)
...
+        {
+            if (spellData.SpellTrigger != ITEM_SPELLTRIGGER_ON_EQUIP)
+                continue;
+        }
+        else
+        {
+            // Auras activated by use should not be removed on unequip
+            if (spellData.SpellTrigger == ITEM_SPELLTRIGGER_ON_USE)
+                continue;
+        }
```
Comment (FrancescoBorzi) [inline src/server/game/Entities/Player/Player.cpp:8631]:
```suggestion
        if (apply && spellData.SpellTrigger != ITEM_SPELLTRIGGER_ON_EQUIP)
        {
            continue;
        }
        else if (spellData.SpellTrigger == ITEM_SPELLTRIGGER_ON_USE)
        {
            // Auras activated by use should not be removed on unequip
            continue;
        }
```

**Comment by tkn963** [comment]
Tested 👍

**Review by FrancescoBorzi — APPROVED** [review]
