### PR TITLE
fix(DB/Locale) Minor fix Russian locale of quests

### LINKED ISSUE #14228: (DB/Locale): Vile Familiars
### Current Behaviour

https://www.wowhead.com/wotlk/quest=792/vile-familiars

When passing the quest there is no translation into Russian

Also in the game there is a typo in the word "familiars" in Russian

On wowhead it's "фамильяры", but ingame it "фамилиары". And from the point of view of the correct spelling of words in Russian, at the moment it is written incorrectly in the game.

### Expected Blizzlike Behaviour

Should be multi-language support

### Source

_No response_

### Steps to reproduce the problem

Take this quest, complete it, and when you turn it in, you will find that there is no ruRU localization.

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. 20da358afbd5+ 

### Operating system

Debian 11

### PR DESCRIPTION
**Pull request by zzlyns**
Sorry, it's my first PR.

## Changes Proposed:
**Added Russian locale for quests:**
Quest(4641) - Your Place In The World
Quest(788) - Cutting Teeth

**Fix Russain locale for:**
Quest(783) - A Threat Within (**Russian verison uses Cataclysm text** https://github.com/azerothcore/azerothcore-wotlk/issues/15135)
Quest(792) - Vile Familiars (**(DB/Locale): Vile Familiars** https://github.com/azerothcore/azerothcore-wotlk/issues/14228)

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #14228
- Progress #15135

- Russian translation is missing for some quests
- Error in Russian translation in some quests 

## SOURCE:
The changes have been validated through:
- [x] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [x] Sniffs (remember to share them with the open source community!)

## Tests Performed:
This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:
So, ruRU game client is requred.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

File: data/sql/updates/pending_db_world/fix_quest_ruRU_translate_02022025.sql [hunk 1]
```diff
@@ -0,0 +1,13 @@
+-- Add Russian locale for QuestID: 4641
+INSERT INTO quest_offer_reward_locale(ID,locale,RewardText,VerifiedBuild) VALUES (4641,'ruRU','Очередной рекрут Калтунка?$B$BВидно, плохи наши дела, если у нас нет никого получше. Ну, ничего. К тому времени, как мы решим, что тебе пора покинуть долину, из тебя $c получится бравый воитель Орды!',0);
```
Comment (Rorschach91) [inline data/sql/updates/pending_db_world/fix_quest_ruRU_translate_02022025.sql:2]: From  Codestyle / SQL (pull_request) check:
> INSERT & DELETE safety usage check : Failed


Use DELETE FROM before INSERT INTO

Something like this: 

DELETE FROM quest_offer_reward_locale WHERE ID = 4641;

File: data/sql/updates/pending_db_world/fix_quest_ruRU_translate_02022025.sql [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+
+-- Add Russian locale for QuestID: 788
+INSERT INTO quest_offer_reward_locale(ID,locale,RewardText,VerifiedBuild) VALUES (788,'ruRU','Ну что ж, $N, неплохо. Но не задирай носа: грядут бои с куда более серьезными врагами.$b$bОднако ты показал себя достойным бойцом. В следующем испытании тебе придется встретиться с более опасным противником, так что дополнительная защита не помешает.',0);
```
Comment (Rorschach91) [inline data/sql/updates/pending_db_world/fix_quest_ruRU_translate_02022025.sql:5]: > Use DELETE FROM before INSERT INTO

Same here.

**Review by sudlud — APPROVED** [review]
