### PR TITLE
fix(Core/Movement): Fixed collision calculation returning wrong position.

### LINKED ISSUE #4769: Fear can send you right through walls into out of bounds [$50]
Fear can send you right through walls into out of bounds

##### CURRENT BEHAVIOUR:

Any sort of fear (Warlock Fear, Priest Psychic Scream, Warrior Intimidating Shout, Hunter's Shrapnel Shot, etc).

If you are feared you can and will walk through walls, under floors, and into spots that can get you stuck or leveraged out of bounds in battlegrounds and the overworld.

https://cdn.discordapp.com/attachments/801844176416276500/813924005156225024/WoWScrnShot_022321_220255.jpg

WoWScrnShot_030821_230328

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Fears/controlled movements should not have you phase through solid objects and die.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Enter a BG or Gurubashi Arena or anywhere with walls. The huts in WSG that contain chests are good for this test.
2. Cast any source of fear.
3. Watch as sometimes you will phase through solid objects during the fear.

##### AC HASH/COMMIT:

AzerothCore rev. 6a7155eb7e82 2021-03-07 12:37:07 +0000 (master branch)

##### OTHER CUSTOMIZATIONS:

<bountysource-plugin>

---
There is a **[$50 open bounty](https://www.bountysource.com/issues/97032508-fear-can-send-you-right-through-walls-into-out-of-bounds?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #4782: Ethereal Liquor allows you to phase through BG walls (possibly related to fear bug) [$50]
Ethereal Liquor allows you to phase through BG walls (possibly related to fear bug)

##### CURRENT BEHAVIOUR:

Drink Ethereal Liquor. It turns you into a feared monster. The feared monster will run through walls in BGs.

https://www.wowhead.com/item=38294/ethereal-liqueur

Possibly related;

This might be a fear issue not an ethereal liquor issue, but I don't know.

https://github.com/azerothcore/azerothcore-wotlk/issues/4769

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Not phase through walls.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Warsong Gulch
2. Go inside a hut/building
3. Drink and watch

##### AC HASH/COMMIT:

AzerothCore rev. 6a7155eb7e82 2021-03-07 12:37:07 

##### OTHER CUSTOMIZATIONS:

<bountysource-plugin>

---
There is a **[$50 open bounty](https://www.bountysource.com/issues/97032521-ethereal-liquor-allows-you-to-phase-through-bg-walls-possibly-related-to-fear-bug?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
FleeingMovementGenerator: Improved fleeing movement generator by calculating a new path to collision point.
Fixed #4769.

## Changes Proposed:
- Fixed collision calculations.
-  Improved fleeing movement generator, by calculating a new path to collision point.
-  Fixed copypasta.

## Issues Addressed:
- Closes #4769 

## Tests Performed:
- Tested on battlegrounds (more info in addressed issue)
-

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
cc @Yehonal @Footman

**Comment by UltraNix** [comment]
Don't do anything with PR. I see now where is the problem and I must rewrite it.

**Comment by Yehonal** [comment]
> Don't do anything with this PR. I see now where is the problem and I must rewrite it.

the first change should be done anyway

regarding the generation of path for the fleeing, could not be needed but I think that a generated path for fleeing is fine aswell. 
I know for sure that fleeing characters on retail generate a path in some particular cases.

**Comment by UltraNix** [comment]
You are right - we need to move by path, instead of pushing only 2 points and ignoring everything between them.
 But the main problem (not only with fleeing movement generator) is somewhere else. I will push the commit later.

**Comment by Yehonal** [comment]
Before moving between 2 points we already check if that point is reachable
with the collisionCheck method. So it's not something like "we don't care
about what there is in between". But following a generated path helps with
fixing the Z coord when the terrain is not flat

Il mar 16 mar 2021, 20:00 UltraNix ***@***.***> ha scritto:

**Comment by UltraNix** [comment]
There was a main problem:
```
float tempX=destX, tempY=destY, tempZ=destZ;
    if (!CheckCollisionAndGetValidCoords(source, startX, startY, startZ, destX, destY, destZ, failOnCollision))
    {
        return false;
    }

    destX = tempX, destY = tempY, destZ = tempZ;```
 
 First we calculate new collision coords and then... restored the old one, completely ingoring the whole collision calculations.

**Comment by pklloveyou** [comment]
image
Is it here?

**Comment by UltraNix** [comment]
Yes.

**Comment by pklloveyou** [comment]
.aura 7399 OK?

File: src/server/game/Movement/MovementGenerators/FleeingMovementGenerator.cpp [hunk 1]
```diff
@@ -38,7 +38,7 @@ void FleeingMovementGenerator<T>::_setTargetLocation(T* owner)
     owner->AddUnitState(UNIT_STATE_FLEEING_MOVE);
```
Comment (pklloveyou) [inline src/server/game/Movement/MovementGenerators/FleeingMovementGenerator.cpp:38]:
```
    //Add LOS check for target point
    bool isInLOS = VMAP::VMapFactory::createOrGetVMapManager()->isInLineOfSight(owner->GetMapId(), owner->GetPositionX(), owner->GetPositionY(), owner->GetPositionZ() + 2.0f, x, y, z + 2.0f);
    if (!isInLOS)
    {
        i_nextCheckTime.Reset(500);
        return;
    }
```
This will fix the error

Comment (pklloveyou) [inline src/server/game/Movement/MovementGenerators/FleeingMovementGenerator.cpp:38]: 37 line
```
    //Add LOS check for target point
    bool isInLOS = VMAP::VMapFactory::createOrGetVMapManager()->isInLineOfSight(owner->GetMapId(), owner->GetPositionX(), owner->GetPositionY(), owner->GetPositionZ() + 2.0f, x, y, z + 2.0f);
    if (!isInLOS)
    {
        i_nextCheckTime.Reset(500);
        return;
    }
```
This will fix the error

**Comment by UltraNix** [comment]
Anything with fear.

**Comment by pklloveyou** [comment]
image
Here we can go through in fear.

**Comment by pklloveyou** [comment]
I failed to pass through the wall before and after pr. can someone test it?

**Comment by pklloveyou** [comment]
image
Before and after PR, I can go through here. Is that ok?

**Comment by pklloveyou** [comment]
And
image

**Comment by UltraNix** [comment]
WoWScrnShot_031721_112051
Because Vmaps do not block LoS there. Problems with generated vmaps - out of scope of this PR. Maybe on retail was the same bug?

**Comment by pklloveyou** [comment]
ok

**Comment by claudiodfc** [comment]
Trees on vanilla servers are also not blocking LOS is this blizzlike?

**Comment by UltraNix** [comment]
Yes - it's blizzlike.

**Comment by JamesGent** [comment]
Fear Tests (will be processed in about 5 mins):

https://youtu.be/d4l0oE3u-MA

https://youtu.be/qbVYWjhw_Ms

Feedback:

It's better. We tried for 15 mins and couldn't out of bounds anyone. Needs more time testing to see if anyone out of bounds.

However,

1) If it doesn't know where to fear you, you just stand still motionless. This happened a few times.

2) You can still run through walls, just not out of bounds. E.g inside of the WSG huts, and inside the WSG flagroom.

Verdict: Much better, but not fully fixed.

**Comment by UltraNix** [comment]
> Fear Tests (will be processed in about 5 mins):
> 
> https://youtu.be/d4l0oE3u-MA
> 
> https://youtu.be/qbVYWjhw_Ms
> 
> Feedback:
> 
> It's better. We tried for 15 mins and couldn't out of bounds anyone. Needs more time testing to see if anyone out of bounds.
> 
> However,
> 
> 1. If it doesn't know where to fear you, you just stand still motionless. This happened a few times.
> 2. You can still run through walls, just not out of bounds. E.g inside of the WSG huts, and inside the WSG flagroom.
> 
> Verdict: Much better, but not fully fixed.
> 
> I think you have successfully closed 4769 but I do not think this has affected 4782 or 4666.

Ad 1. Yep - if the core cannot find a proper nad correct path (eg. due to obstacles or holes in the ground), then you cannot move and stand still - this is kind of protection from the problems discribed in the issue ticket
Ad. 2. Already answered in PR and another issue ticket.

The remaining problem is not with collision and fear/movement, but with the generated Vmaps - it's another problem as it can happen in many other situations on the whole open world. But let's decide @FrancescoBorzi what to do with that.

**Review by Yehonal — APPROVED** [review]

**Comment by Yehonal** [comment]
I don't see the needs of removing that method, even though it's not used that can be useful for modules.

Generally: do not remove not used methods because, as a framework, they can be used by modules and scripts

**Comment by Yehonal** [comment]
However, GJ here !

**Comment by FrancescoBorzi** [comment]
@UltraNix just restore that deleted method as indicated from @Yehonal and then this is good to go.

I've been testing this with players for a couple of days and it seems overall better. Good job.

**Comment by UltraNix** [comment]
@FrancescoBorzi I will update all of my opened PRs tonight so they're going to be merged.

**Comment by FrancescoBorzi** [comment]
> @FrancescoBorzi I will update all of my opened PRs tonight so they're going to be ready to be merged.

@UltraNix please let me know when it's done and I'll merge this

**Comment by FrancescoBorzi** [comment]
nevermind, I took care of it

**Comment by UltraNix** [comment]
Sorry, I forgot about it.

**Comment by JamesGent** [comment]
https://github.com/chromiecraft/chromiecraft/issues/271

@UltraNix You fixed fear but can you please have a look at Polymorph thank you. <3

**Comment by UltraNix** [comment]
Polymorph is a different (confused) movement generator from fear (fleeing). But yes - I will look at it.
