### PR TITLE
Fall From Grace

### LINKED ISSUE #1654: [QUEST] Fall From Grace *only horde pg*
DESCRIPTION:

The mission "[Fall From Grace](https://wowgaming.altervista.org/aowow/?quest=2784)" can be completed by only one player.

EXPECTED BLIZZLIKE BEHAVIOUR:

the mission can be completed by all players

CURRENT BEHAVIOUR:

read description

STEPS TO REPRODUCE THE PROBLEM:

- create a horde pg;
- .go c 35237
- take th quest "fall from grace", click on gossip and complete it;
- create another horde pg and repeat the steps;

BRANCH(ES):
staging

AC HASH/COMMIT:
commit https://github.com/azerothcore/azerothcore-wotlk/commit/44272f169c49f20c79b78aeea634f3bc7c2dafd1

OPERATING SYSTEM:
linux

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/72126609-quest-fall-from-grace-only-horde-pg?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Pondaveia**
### Fall From Grace NPC not repeating event

Thank-you Knindzagxg for the fix. I'll open the PR for you
https://github.com/azerothcore/azerothcore-wotlk/issues/1654#issuecomment-478290748

##### CHANGES PROPOSED:

-  Changed the event from not repeat to repeat

###### ISSUES ADDRESSED:

Closes #1654

##### TESTS PERFORMED:

- Tested and works perfectly

##### HOW TO TEST THE CHANGES:

1. create a horde pg
2. .go c 35237
3. take th quest "fall from grace", click on gossip and complete it
4. create another horde pg and repeat the steps

##### Target branch(es):

Master

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1554143974096714000.sql [hunk 1]
```diff
@@ -0,0 +1,4 @@
...
+REPLACE INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (7572, 0, 1, 3, 62, 0, 100, 0, 881, 0, 0, 0, 0, 26, 2801, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'Fallen Hero of the Horde - On Gossip Option 1 Selected - Quest Credit \'A Tale of Sorrow\'');
```
Comment (FrancescoBorzi) [inline data/sql/updates/pending_db_world/rev_1554143974096714000.sql]: please use `DELETE` and `INSERT` instead of `REPLACE`

also don't forget the empty line at the end of the file

Comment (BarbzYHOOL) [reply data/sql/updates/pending_db_world/rev_1554143974096714000.sql]: depends on the change, sometiems replace into is better

In that case, do we need to delete and reinset the whole smart_scripts ? is the code above the whole smart_script for that entry or are there other rows that are untouched ?

**Comment by poszer** [comment]
Tested in game: 
Without this commit, the horde players are able to finish this quest just once ( WIth 1 character ).

With this commit : 
The quest can be completed with more characters ( Correct ).
Thanks @Pondaveia , @Knindzagxg

File: data/sql/updates/pending_db_world/rev_1554143974096714000.sql (hunk 1 above)
Comment (FrancescoBorzi) [reply data/sql/updates/pending_db_world/rev_1554143974096714000.sql]: - we only have to `DELETE` the rows that we are going to `INSERT`. For consistency, we always have been using DELETE/INSERT instead of REPLACE since MaNGOS UDB times. One of the reasons is, it is more intuitive to understand what's going for people who are not familiar to SQL

- whenever we need to **edit** an existing row (without deleting and re-inserting it) then `UPDATE` shall be used

**Comment by poszer** [comment]
INFO : Also, since i already have some queries from old pr imported, this working for me. But actually, this isn't well done, you should use just replace for 2 lines, not deleting anything 
@Pondaveia

**Comment by wizzymore** [comment]
If you want this PR to work, use this query instead. otherwise you will do more damage than repairing.

```sql
DELETE FROM `smart_scripts` WHERE `entryorguid`=7572;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(7572, 0, 0, 2, 62, 0, 100, 0, 842, 0, 0, 0, 0, 26, 2784, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'On gossip action 0 from menu 842 selected - Action invoker: Call event happened from quest 2784 for the whole group // Fallen Hero of the Horde - On Gossip Option 0 Selected - Quest Credit \'Fall From Grace\''),
(7572, 0, 1, 2, 62, 0, 100, 0, 881, 0, 0, 0, 0, 26, 2801, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'On gossip action 0 from menu 881 selected - Action invoker: Call event happened from quest 2801 for the whole group // Fallen Hero of the Horde - On Gossip Option 1 Selected - Quest Credit \'A Tale of Sorrow\''),
(7572, 0, 2, 0, 61, 0, 100, 0, 0, 0, 0, 0, 0, 72, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'On link - Action invoker: Close gossip // Fallen Hero of the Horde - Close Gossip'),
(7572, 0, 3, 0, 19, 0, 100, 0, 2702, 0, 0, 0, 0, 44, 3, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'When player accepts quest 2702 - Action invoker: Set phase id to 3 // '),
(7572, 0, 4, 0, 62, 0, 100, 0, 840, 2, 0, 0, 0, 44, 3, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'On gossip action 2 from menu 840 selected - Action invoker: Set phase id to 3 // ');
```

**Comment by poszer** [comment]
> If you want this PR to work, use this query instead. otherwise you will do more damage than repairing.
> 
> ```sql
> DELETE FROM `smart_scripts` WHERE `entryorguid`=7572;
> INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
> (7572, 0, 0, 2, 62, 0, 100, 0, 842, 0, 0, 0, 0, 26, 2784, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'On gossip action 0 from menu 842 selected - Action invoker: Call event happened from quest 2784 for the whole group // Fallen Hero of the Horde - On Gossip Option 0 Selected - Quest Credit \'Fall From Grace\''),
> (7572, 0, 1, 2, 62, 0, 100, 0, 881, 0, 0, 0, 0, 26, 2801, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'On gossip action 0 from menu 881 selected - Action invoker: Call event happened from quest 2801 for the whole group // Fallen Hero of the Horde - On Gossip Option 1 Selected - Quest Credit \'A Tale of Sorrow\''),
> (7572, 0, 2, 0, 61, 0, 100, 0, 0, 0, 0, 0, 0, 72, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'On link - Action invoker: Close gossip // Fallen Hero of the Horde - Close Gossip'),
> (7572, 0, 3, 0, 19, 0, 100, 0, 2702, 0, 0, 0, 0, 44, 3, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'When player accepts quest 2702 - Action invoker: Set phase id to 3 // '),
> (7572, 0, 4, 0, 62, 0, 100, 0, 840, 2, 0, 0, 0, 44, 3, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'On gossip action 2 from menu 840 selected - Action invoker: Set phase id to 3 // ');
> ```
> 
> Or if you don't want to delete anything, just replace the event_flag to value 0 on id 0 and id 1

Yeap @Pondaveia

**Comment by BarbzYHOOL** [comment]
Or reuse the original with replace into as I said earlier (less codes, cleaner)

**Comment by Pondaveia** [comment]
> If you want this PR to work, use this query instead. otherwise you will do more damage than repairing.
> 
> ```sql
> DELETE FROM `smart_scripts` WHERE `entryorguid`=7572;
> INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
> (7572, 0, 0, 2, 62, 0, 100, 0, 842, 0, 0, 0, 0, 26, 2784, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'On gossip action 0 from menu 842 selected - Action invoker: Call event happened from quest 2784 for the whole group // Fallen Hero of the Horde - On Gossip Option 0 Selected - Quest Credit \'Fall From Grace\''),
> (7572, 0, 1, 2, 62, 0, 100, 0, 881, 0, 0, 0, 0, 26, 2801, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'On gossip action 0 from menu 881 selected - Action invoker: Call event happened from quest 2801 for the whole group // Fallen Hero of the Horde - On Gossip Option 1 Selected - Quest Credit \'A Tale of Sorrow\''),
> (7572, 0, 2, 0, 61, 0, 100, 0, 0, 0, 0, 0, 0, 72, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'On link - Action invoker: Close gossip // Fallen Hero of the Horde - Close Gossip'),
> (7572, 0, 3, 0, 19, 0, 100, 0, 2702, 0, 0, 0, 0, 44, 3, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'When player accepts quest 2702 - Action invoker: Set phase id to 3 // '),
> (7572, 0, 4, 0, 62, 0, 100, 0, 840, 2, 0, 0, 0, 44, 3, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'On gossip action 2 from menu 840 selected - Action invoker: Set phase id to 3 // ');
> ```
> 
> Or if you don't want to delete anything, just replace the event_flag to value 0 on id 0 and id 1

ok i'm confused, that's literally the same thing. What damage do you mean? fix the mob?

**Comment by poszer** [comment]
> > If you want this PR to work, use this query instead. otherwise you will do more damage than repairing.
> > ```sql
> > DELETE FROM `smart_scripts` WHERE `entryorguid`=7572;
> > INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
> > (7572, 0, 0, 2, 62, 0, 100, 0, 842, 0, 0, 0, 0, 26, 2784, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'On gossip action 0 from menu 842 selected - Action invoker: Call event happened from quest 2784 for the whole group // Fallen Hero of the Horde - On Gossip Option 0 Selected - Quest Credit \'Fall From Grace\''),
> > (7572, 0, 1, 2, 62, 0, 100, 0, 881, 0, 0, 0, 0, 26, 2801, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'On gossip action 0 from menu 881 selected - Action invoker: Call event happened from quest 2801 for the whole group // Fallen Hero of the Horde - On Gossip Option 1 Selected - Quest Credit \'A Tale of Sorrow\''),
> > (7572, 0, 2, 0, 61, 0, 100, 0, 0, 0, 0, 0, 0, 72, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'On link - Action invoker: Close gossip // Fallen Hero of the Horde - Close Gossip'),
> > (7572, 0, 3, 0, 19, 0, 100, 0, 2702, 0, 0, 0, 0, 44, 3, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'When player accepts quest 2702 - Action invoker: Set phase id to 3 // '),
> > (7572, 0, 4, 0, 62, 0, 100, 0, 840, 2, 0, 0, 0, 44, 3, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'On gossip action 2 from menu 840 selected - Action invoker: Set phase id to 3 // ');
> > ```
> > 
> > 
> > Or if you don't want to delete anything, just replace the event_flag to value 0 on id 0 and id 1
> 
> ok i'm confused, that's literally the same thing. What damage do you mean? fix the mob?

Take a look here @Pondaveia 
https://github.com/azerothcore/azerothcore-wotlk/blob/812a90568e3af009006a6f393d2457f335b96a99/data/sql/updates/pending_db_world/rev_1553731839786525000.sql#L23

and here ; 
https://github.com/azerothcore/azerothcore-wotlk/blob/812a90568e3af009006a6f393d2457f335b96a99/data/sql/updates/pending_db_world/rev_1553731839786525000.sql#L24

and just replace with this 2 rows : 
```sql
REPLACE INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (7572, 0, 0, 2, 62, 0, 100, 0, 842, 0, 0, 0, 0, 26, 2784, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'Fallen Hero of the Horde - On Gossip Option 0 Selected - Quest Credit \'Fall From Grace\'');

REPLACE INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (7572, 0, 1, 3, 62, 0, 100, 0, 881, 0, 0, 0, 0, 26, 2801, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'Fallen Hero of the Horde - On Gossip Option 1 Selected - Quest Credit \'A Tale of Sorrow\'');
```

**Comment by wizzymore** [comment]
Something else now, good job @Pondaveia
