### PR TITLE
Kurzan Commando Fix and Argent Defender

### LINKED ISSUE #245: Talent Paladin tank [Ardent Defender] not works
**Current Behavior**: The talent of paladin [Ardent Defender] does not activate when you have less than 1% health

**Expected behavior**: The talent [Ardent Defender] should be activated, heal up to 30% health and leave you a debuff of 2 minutes so that the talent does not return activating.

**Link**: http://www.wowhead.com/spell=31850/ardent-defender

**Branch(es)**: 1.x

**AC hash/commit**:  https://github.com/azerothcore/azerothcore-wotlk/commit/cd6209cdb10234201682fd4c15b01964c0fa60ed

**Operating system**:  Windows 2008 R2

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: 
- Transmogrif
- Crossfaction

### PR DESCRIPTION
**Pull request by talamortis**
**Changes proposed:**

-  Fixed Argent Defender for paladin will now heal correctly and will scale on defence
-  Fixed Kurzen Commando will now appear stealthed.
-  

**Target branch(es):** Master

**Issues addressed:** Closes #245  #247 

**Tests performed:** (Does it build, tested in-game, etc)
Tested and working

**Known issues and TODO list:**

- [None ] 
- [ ] 

**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

File: src/scripts/Spells/spell_paladin.cpp [hunk 1]
```diff
@@ -293,82 +293,92 @@ class spell_pal_sacred_shield_base : public SpellScriptLoader
 // 31850 - Ardent Defender
 class spell_pal_ardent_defender : public SpellScriptLoader
 {
-    public:
-        spell_pal_ardent_defender() : SpellScriptLoader("spell_pal_ardent_defender") { }
+public:
+    spell_pal_ardent_defender() : SpellScriptLoader("spell_pal_ardent_defender") { }
```
Comment (ShinDarth) [inline src/scripts/Spells/spell_paladin.cpp]: indentation

**Comment by talamortis** [comment]
Tested and working

**Comment by ShinDarth** [comment]
good job @talamortis
