### PR TITLE
fix(Core/Players): Players should nt able to rest in unfriendly taver…

### LINKED ISSUE #13459: opposite faction taverns count as rested areas
https://github.com/chromiecraft/chromiecraft/issues/4248
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Certain taverns count as rested zones despite belonging to the opposite faction.

this doesnt occur with all, but as far as i can tell it happens with all "Classic" style taverns (Goldshire, lakeshire, southshore)

https://user-images.githubusercontent.com/11332559/196507218-3b0cb72d-e784-49e3-8d05-f872229fceb5.mp4
image

### Expected Blizzlike Behaviour

Taverns of the opposite faction should not count as rested zones

### Source

wrath classic 
image

### Steps to reproduce the problem

**horde**
.tele lakehire
.go xyz -9232 -2156 65

**alliance**
.tele brill
.go xyz 2249 248 35

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…ns. Original author: @Rushor

Fixes #13459

 

## Issues Addressed:

- Closes #13459
- Closes https://github.com/chromiecraft/chromiecraft/issues/4248

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

horde
.tele lakehire
.go xyz -9232 -2156 65

alliance
.tele brill
.go xyz 2249 248 35

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1666450482825467900.sql [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+5164,
+5030,
+4975,
+4976,
+4977,
+4607,
+4608,
+4640,
+4714,
+4847);
```
Comment (acidmanifesto) [inline data/sql/updates/pending_db_world/rev_1666450482825467900.sql:127]: line break

File: data/sql/updates/pending_db_world/rev_1666450482825467900.sql [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+4970,
+4979,
+4868,
+4910,
+5045,
+4861,
+4775,
+4755,
+4595);
+
```
Comment (acidmanifesto) [inline data/sql/updates/pending_db_world/rev_1666450482825467900.sql:92]: white space

**Review by acidmanifesto — CHANGES_REQUESTED** [review]

**Review by acidmanifesto — APPROVED** [review]

**Review by IntelligentQuantum — APPROVED** [review]
