### PR TITLE
fix(DB/Quest): Zapped Giants now behave correctly

### LINKED ISSUE #9639: Zorbin's Ultra-Shrinker item by Zapped Giants quest doesn't work as it should
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2542

During the quests "Zapped Giants" and "Again With the Zapped Giants" in Feralas, the item [Zorbin's Ultra-Shrinker] is usable on non-giant NPCs that are not related to the quest.
WoWScrnShot_121021_185553

Tester:

The issue is confirmed:
1. [Zorbin's Ultra-Shrinker](https://wowgaming.altervista.org/aowow/?item=18904) is not affecting several targets
2. Zorbin's Ultra-Shrinker doesn't change HP of the target after usage
3. Zorbin's Ultra-Shrinker could be used to any creature

https://user-images.githubusercontent.com/85256266/145637018-13a90f5f-3f01-4fed-bfef-2cdbf97eabb6.mp4

### Expected Blizzlike Behaviour

1. Shoudl work as shaman's chain light
2. Giant should have the same `%` of health they had before being zapped
3. Idk how it should work

### Source

Wowhead [Zapped Giants](https://www.wowhead.com/quest=7003/zapped-giants)
> By 66097 on 2007/08/06 (Patch 2.1.3)
Didn't notice if this was mentioned above but the zapper can actually chain, i found it a bit more interesting :D to aggro 2 and then use it, they both get the anti elite effect.

> By 318982 on 2009/02/25 (Patch 3.0.9)
And to Warlocks, or people who forgot to zap them, when you zap them they will retain any debuffs/buffs and have the same % of health they had before being zapped

Wowpedia [Zapped Giants (quest)](https://wowpedia.fandom.com/wiki/Zapped_Giants_(quest)?oldid=2361008)
>Use  [Zorbin's Ultra-Shrinker] provided by Zorbin Fandazzle to shrink any of these giants along the Forgotten Coast in Feralas:
Cliff Giant
Deep Strider
Wave Strider
Shore Strider
Land Walker

https://youtu.be/xeXw9aLyMPM?t=808

### Steps to reproduce the problem

.additem 18904
.go c 51708
agro 2 giants near
use item

### Extra Notes

X

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### LINKED ISSUE #21086: Quest: Zapped Giants minor issues
### Current Behaviour

Currently, when you zap a giant with the device given by the quest giver the "Level up" golden animation is played on the giant as he is shrunken down. However, this doesn't seem to always happen and I can't pinpoint why.

The second issue is that zapping a giant should cause it to become aggressive towards the player doing the zapping.

### Expected Blizzlike Behaviour

No level up animation and giants should become aggressive on zapping.

### Source

YT video of quest (oldest I could find listed as 14 years ago): https://www.youtube.com/watch?v=93nLD7Lcg4w

Wowhead link about becoming aggressive: https://www.wowhead.com/wotlk/quest=7003/zapped-giants#comments:id=2761661

### Steps to reproduce the problem

1) .go c id 14637
2) accept zapped giants quest or manually add quest # 7003
3) shrink nearby giants

### Extra Notes

There is this open issue with the quest also, maybe they should be merged? https://github.com/azerothcore/azerothcore-wotlk/issues/9639 I have confirmed that the bug is still valid.

### AC rev. hash/commit

AzerothCore rev. 0594a8f51807 2025-01-01 20:25:39 -0300 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu 24.04

### Custom changes or Modules

```
List of enabled modules:
|- mod-better-item-reloading
|- mod-eluna
|- mod-individual-xp
|- mod-npc-buffer
|- mod-npc-enchanter
|- mod-npc-services
|- mod-random-enchants
|- mod-solocraft
|- mod-transmog
```

### PR DESCRIPTION
**Pull request by Exitare**
Fix minor visuals and missing aggro for transformed npcs.

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Progress #21086
- Closes #9639

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. .go c 51705
2. .quest add 7003
3. Use the item on the giant. Level up animation should be cast, giant should automatically start attacking the player.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by elthehablo** [comment]
If I understand correctly, this does nothing to fix the issue where you can use this on other creatures, as outlined in the second issue?

**Comment by Exitare** [comment]
@elthehablo Thanks for catchinig that. It does now

File: src/server/scripts/Kalimdor/zone_feralas.cpp [hunk 1]
```diff
@@ -52,7 +52,42 @@ class spell_gordunni_trap : public SpellScript
...
+class spell_transmogrify : public SpellScript
+{
+    PrepareSpellScript(spell_transmogrify);
+
+    SpellCastResult CheckTarget()
+    {
+        Unit* target = GetExplTargetUnit(); // Explicit target selected by the caster
+
+        // List of valid creature IDs
+        std::set<uint32> validCreatureIds = { NPC_SHORE_STRIDER, NPC_DEEP_STRIDER, NPC_LAND_WALKER, NPC_WAVE_STRIDER, NPC_CLIFF_GIANT };
```
Comment (Kitzunu) [inline src/server/scripts/Kalimdor/zone_feralas.cpp:73]: std::unordered_set is more efficient here as the id's doesnt need to be in a specific order

File: src/server/scripts/Kalimdor/zone_feralas.cpp [hunk 2]
```diff
@@ -52,7 +52,42 @@ class spell_gordunni_trap : public SpellScript
...
+
+        // Validate the target
+        if (!target || validCreatureIds.find(target->GetEntry()) == validCreatureIds.end())
```
Comment (Kitzunu) [inline src/server/scripts/Kalimdor/zone_feralas.cpp:76]: using unordered_set you can use var.contains(target->GetEntry())

Comment (Kitzunu) [reply src/server/scripts/Kalimdor/zone_feralas.cpp:76]: and just invert the check

File: src/server/scripts/Kalimdor/zone_feralas.cpp [hunk 3]
```diff
@@ -52,7 +52,42 @@ class spell_gordunni_trap : public SpellScript
...
+            return SPELL_FAILED_BAD_TARGETS; // Prevent the spell cast with an error
+
+        return SPELL_CAST_OK; // Allow the spell cast
+    }
+
+    void Register() override
+    {
+        // Register the check cast hook
```
Comment (Kitzunu) [inline src/server/scripts/Kalimdor/zone_feralas.cpp:84]: also what are all these unnecessary comments

File: src/server/scripts/Kalimdor/zone_feralas.cpp (hunk 2 above)
Comment (Exitare) [reply src/server/scripts/Kalimdor/zone_feralas.cpp:76]: Thank you for these insights! :)

File: src/server/scripts/Kalimdor/zone_feralas.cpp (hunk 3 above)
Comment (Exitare) [reply src/server/scripts/Kalimdor/zone_feralas.cpp:84]: For you they might be unnecessary. This is my very first spell script and having these comments helped me to learn and understand it better.

Comment (Kitzunu) [reply src/server/scripts/Kalimdor/zone_feralas.cpp:84]: yeah, if we were to add comments to all scripts like these it would be very bloated. These comments are good in the base for doxygen for example

File: src/server/scripts/Kalimdor/zone_feralas.cpp [hunk 4]
```diff
@@ -52,7 +52,40 @@ class spell_gordunni_trap : public SpellScript
...
+enum ZAPPED_GIANTS
+{
+    NPC_SHORE_STRIDER = 5359,
+    NPC_DEEP_STRIDER = 5360,
+    NPC_LAND_WALKER = 5357,
+    NPC_WAVE_STRIDER = 5361,
+    NPC_CLIFF_GIANT = 5358
+};
+
+class spell_transmogrify : public SpellScript
```
Comment (sudlud) [inline src/server/scripts/Kalimdor/zone_feralas.cpp:64]: there is no need for a spellscript here. target selection like this can be done with conditions in the database. please update the pr accordingly

**Review by sudlud — CHANGES_REQUESTED** [review]

**Comment by sudlud** [comment]
Looking for someone to update this pr to use db conditions :)

**Comment by sudlud** [comment]
tested.

- can't use the item on non-quest-related mobs anymore
- mobs start attacking correctly after item beeing used
- level-up animation still sometimes does not show correctly - needs further investigation properly, therefore this PR only closes one issue, the other is Progress
