### PR TITLE
Fix(Core/DB): Naxxramas overhaul

### LINKED ISSUE #946: Faerlina Frenzy timer
Description: Faerlina Frenzy timer 

Current behaviour: Faerlina Frenzy timer isn't blizzlike with urand 60000 80000 and wrong delay after the first Frzney

Expected behaviour: During Faerlina fight , Faerlina should become Frenzy after 1 minute of fight and all 1 minute after removal effect

Steps to reproduce the problem:

1. Go to Naxxramas , after Anub'rekhan
2. Engage Faerlina fight
3. See the timer and the delay of the Frenzy

Branch(es): master

AC hash/commit: 7329ad4

Operating system: Linux

Modules: /

Other Customizations: /

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/60088309-faerlina-frenzy-timer?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Nefertumm**
Co-authored-by: Pondaveia <Pondaveia@users.noreply.github.com>
Co-authored-by: FALL1N1 <FALL1N1@users.noreply.github.com>

##### CHANGES PROPOSED:

-  Added a lot of overrides and changed NULL to nullptr.
-  Clean hardcoded text to allow translations.
-  Added screams from Thaddius (spooky af).
-  Added missing texts from Thaddius, Kel'Thuzad, Heigan...
-  Fix Razuvious texts.
-  Added Thaddius areatrigger.
-  5 seconds until he starts casting Ball Lightning to the raid.
-  Shock now should be casted by both Coils if Stalagg and Feugen are away from them and not from just only one.
-  Faerlina now pulls adds if you don't kill them before and fixed frenzy timer. (Thanks @Pondaveia)
-  Grobbulus now pulls his chamber adds if they are not killed when combat begins (Thanks @Pondaveia)
-  Patchwerk now pulls his chamber adds if they are not killed when combat begins (Thanks @Pondaveia and @FALL1N1)
-  Kel'Thuzad now talks after killing main bosses (Thaddius, Maexxna, Four Horsemen and Loatheb).
- [Loatheb] All left spores will now despawn upon boss death or reset.(Thanks @Pondaveia and @FALL1N1)
- [Loatheb] Fixed Necrotic Aura's timer.(Thanks @Pondaveia and @FALL1N1)
- [Loatheb] New method of spawning spores, we don't have to share them with deathbloom as it has different timer.(Thanks @Pondaveia and @FALL1N1)
- [Loatheb] Boss now evades if pulled outside the combat area.(Thanks @Pondaveia and @FALL1N1)

###### ISSUES ADDRESSED:

Closes #946 

##### TESTS PERFORMED:

Compiled, tested in game.

##### HOW TO TEST THE CHANGES:

Apply the PR and go to Naxxramas. Check changes proposed to see what to test.

##### KNOWN ISSUES AND TODO LIST:

- [x] Tesla Coil doesn't want to cast Shock to the other platform. I NEED HELP WITH THIS, I DON'T KNOW WHAT'S HAPPENING. [Crappy draw](https://imgur.com/a/ocOORFZ) (I'll upload a video in order to you can see the issue)

##### Target branch(es):

Master

### CODE REVIEW

**Comment by pklloveyou** [comment]
No polarity conversion BOSS->thaddius

**Comment by Nefertumm** [comment]
What do you mean @pklloveyou ?

**Comment by pklloveyou** [comment]
BOSS reuses the same skill, other skills will not be released
PS:Google Translate

**Comment by pklloveyou** [comment]
case EVENT_ACTIVATE_BALL_LIGHTNING:
				ballLightningEnabled = true;
		+		events.PopEvent();
I am too slow to connect to the international network here.
Sometimes I can't open too many pages, sorry.
PS:Google Translate

**Comment by Nefertumm** [comment]
Ready to be tested :-)

**Comment by Pondaveia** [comment]
Nice overhaul ❤️

**Comment by comix1988** [comment]
I started testing these fixes (for now only the instructor razuvious):
first of all I propose to set the texts in this order:
ravozius
and now when the player dies the boss says nothing
In the DB I can't find the text with ID 8854:

**Comment by Nefertumm** [comment]
I see, the killing player texts are in taunted, i will fix it asap.

**Comment by comix1988** [comment]
for Gothik at Death's Breach( I don't know if you've fixed it) these are the correct texts:
goti
Now divide the first phrase into the 3 phases (aggro - phase 2 - player death)

**Comment by Nefertumm** [comment]
@comix1988 can you find for me where the emote '%s lets loose a triumphant shout' is used for Razuvious fight?

**Comment by comix1988** [comment]
I try tomorrow @nefertumm

**Comment by comix1988** [comment]
https://github.com/Hosq/BigWigs/blob/master/Raids/Naxxramas/Razuvious.lua

Maybe eheh cast distrucpting shout?

File: src/server/game/Maps/Map.cpp [hunk 1]
```diff
@@ -3252,6 +3252,21 @@ void Map::SendZoneDynamicInfo(Player* player)
...
+    Map::PlayerList const& players = GetPlayers();
+    if (!players.isEmpty())
+    {
+        WorldPacket data(SMSG_PLAY_SOUND, 4);
+        data << uint32(soundId);
+
+        for (Map::PlayerList::const_iterator itr = players.begin(); itr != players.end(); ++itr)
+            if (Player* player = itr->GetSource())
+                if (!zoneId || player->GetZoneId() == zoneId)
+                    player->SendDirectMessage(&data);
```
Comment (Pondaveia) [inline src/server/game/Maps/Map.cpp]: Can you explain what does this do? I Don't quite understand it 😕

File: src/server/scripts/Northrend/Naxxramas/boss_gluth.cpp [hunk 2]
```diff
@@ -64,7 +73,7 @@ class boss_gluth : public CreatureScript
         InstanceScript* pInstance;
         uint64 gazeTarget;
         
-        void Reset()
+        void Reset() override
         {
             BossAI::Reset();
             me->ApplySpellImmune(29306, IMMUNITY_ID, 29306, true);
```
Comment (Pondaveia) [inline src/server/scripts/Northrend/Naxxramas/boss_gluth.cpp]: Maybe make 29306 a const?

File: src/server/scripts/Northrend/Naxxramas/boss_gluth.cpp [hunk 3]
```diff
@@ -74,18 +83,18 @@ class boss_gluth : public CreatureScript
             me->SetReactState(REACT_AGGRESSIVE);
         }
 
-        void MoveInLineOfSight(Unit *who)
+        void MoveInLineOfSight(Unit *who) override
         {
             if ((!me->GetVictim() || me->GetVictim()->GetEntry() != NPC_ZOMBIE_CHOW) && who->GetEntry() == NPC_ZOMBIE_CHOW && me->IsWithinDistInMap(who, 6.5f))
```
Comment (Pondaveia) [inline src/server/scripts/Northrend/Naxxramas/boss_gluth.cpp]: Maybe breaking this into 2 Ifs eases readability, what do you think?

File: src/server/game/Maps/Map.cpp (hunk 1 above)
Comment (Nefertumm) [reply src/server/game/Maps/Map.cpp]: Basically it sends a sound to all the players in a certain zone in the map. It just needs a packet to work.

File: src/server/scripts/Northrend/Naxxramas/boss_gluth.cpp (hunk 2 above)
Comment (Nefertumm) [reply src/server/scripts/Northrend/Naxxramas/boss_gluth.cpp]: Yeah, it would be good.

File: src/server/scripts/Northrend/Naxxramas/boss_gluth.cpp (hunk 3 above)
Comment (Nefertumm) [reply src/server/scripts/Northrend/Naxxramas/boss_gluth.cpp]: Sure

**Comment by Nefertumm** [comment]
I fixed Razuvious texts, added Grobbulus fixes from #1704 and added Patchwerk fixes from #1706, both from @Pondaveia !

**Comment by comix1988** [comment]
great ... I'm testing all the text of all the nax bosses. I'm wrong? @Nefertumm

**Comment by Nefertumm** [comment]
That's right. But also, test Thaddius dogs and verify if the coils attacks you.
Then the fixes from Pondaveia if possible, make sure Grobbulus pulls all the living adds and Patchwerk same thing.

**Comment by FALL1N1** [comment]
- Thaddius shouldn't move from his position.

Where did you get this from? I remember back in 3.3.3 / 3.3.5 he could move just fine

**Comment by Pondaveia** [comment]
True 

> Thaddius will become active a few seconds after the group reaches his platform, and should be tanked in the center of the platform where he is, but slightly forward so that there is room for the raid to see where to run on either side of him during the Polarity Shifts. 

Font: https://wow.gamepedia.com/Thaddius

**Comment by Nefertumm** [comment]
Yeah, i missunderstood some texts!!

**Comment by Nefertumm** [comment]
What are you talking about? Thaddius is able to move like ever... 🤣

**Comment by comix1988** [comment]
I tested these fixes in the 10 man version:
- fearlina and his add works well, even the enrage timer;
- patchwerk and its add work well;
- grobbulus and its add work well;
- thaddius stands firm in its position and caste lighting bolt;
- tesla works well, does damage when the two bosses are far from the platforms;
** now report all texts test**
anub'arak
anub

fearlina
fearlina

gothik
gothik

Heigan
heigan

noth the plaguebringer
noth

patchwerk
patchwerk

razuvious
razuvious

sapphiron
sapphiron

Stalagg & feugen
stalaggfeugen

thaddius
thaddius

kel'thuzad
kel
when killing the final bosses of the 4 areas to nax, kel'thuzad should yells the phrases of the image
gf

**Comment by Nefertumm** [comment]
Holy shit, that's testing now...

**Comment by Nefertumm** [comment]
There you go @comix1988 . Thanks for the feedback!

**Comment by comix1988** [comment]
I tested all the nax bosses again and:
- INSTRUCTOR RAZOVIUS: in the aggro phase it only says "show them no mercy", the other 3 sentences are missing;
- HEIGAN: spam the 4 random phrases too quickly (every 10 seconds);(Could we set it every 120 sec?)
- SAPPHIRION DEATH: missing thesound of the last phrase "like, heroes .... by the will of the lich king, you shall be destroyed"
- KEL'THUZAD: miss the phrase to the death of mr. biggesworth.

everything else works perfectly.
good job @Nefertumm

**Comment by disclosurez** [comment]
This breaks thaddius so his spells does not cast

**Comment by BarbzYHOOL** [comment]
And thaddius worked before the PR @disclosurez ?

**Comment by Nefertumm** [comment]
Anyone test this again or I will close this and delete the branch 😃
3 days.

**Comment by Knindzagxg** [comment]
I will test it soon enough mate.

**Comment by Knindzagxg** [comment]
Tested finally.

NPCS sometimes drop little under texture when summoned and coming towards you, but that's mmap issue.

Thaddius was working well, so i can't confirm report above me.

Only thing i forgot to test is Biggesworth phase, so would be nice if someone can do it.

When it comes to whole Raid, found 2 small issues:

https://i.imgur.com/1HAHxHC.jpg

Gargoyle sometimes don't leave "Stone Form" which is visual bug, and attacking like that.

https://i.imgur.com/kItRciN.jpg

Bone, where my mouse point, is not dragged during hes spawning event.

Other than that seems to work great.

**Comment by BarbzYHOOL** [comment]
> Other than that seems to work great.

Ok then we can merge and add new issues in followup issue so Nefertum doesn't have to close it (unless he wants to fix it on this PR) :P

**Comment by FrancescoBorzi** [comment]
I reviewed the changed files with CLion and while I was there I made some small clean-ups. But that will be done in a separate PR since it's just minor changes and this one has already been tested the way it is.

 https://github.com/azerothcore/azerothcore-wotlk/pull/2015

**Comment by FrancescoBorzi** [comment]
@BarbzYHOOL  @Knindzagxg 

> Other than that seems to work great.

> Ok then we can merge and add new issues in followup issue so Nefertum doesn't have to close it (unless he wants to fix it on this PR) :P

were those issues introduced by this PR or they were already there?

**Comment by Nefertumm** [comment]
I didn't really change those creatures, so no, those issues weren't introduced by this PR.

**Comment by FrancescoBorzi** [comment]
then  it's good to go. Good job!
