### PR TITLE
fix(Core/Pathfinding): pets chase & transport

### LINKED ISSUE #4425: Pets bug after Pathfinding improvements
##### CURRENT BEHAVIOUR:
The monster has to face the pet. The pet automatically looks for the back of the monster, so it turns in circles

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Pets will hurt each other face to face with monsters

##### STEPS TO REPRODUCE THE PROBLEM:
1. update to https://github.com/azerothcore/azerothcore-wotlk/commit/504a788c63265a85ac730ce5dd6c5a067f25ee67
2. Take your pet to fight monsters
3. Then let the monster's hatred be on the pet

##### EXTRA NOTES:
I think this commit caused the bug
https://github.com/azerothcore/azerothcore-wotlk/commit/c8f43d85849c40e08d0da38913489426a0c35388

`Improved`` pet following movement. Also, they attack NPC from behind now. Thanks to @Footman

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/504a788c63265a85ac730ce5dd6c5a067f25ee67

##### OPERATING SYSTEM:
ubuntu 18.04
##### MODULES:
none

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/96342766-pets-bug-after-pathfinding-improvements?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Footman**
## Changes Proposed:
-  fix pets and creatures chasing each other in circles. fix #4425
-  fix creatures were not starting chasing when on transport. also removed hack in bool Unit::isInAccessiblePlaceForconst because dont think we still need it with new pathfinding.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Zoidwaffle** [comment]
I tried to compile the server with this PR, but it fails.

```
~/azerothcore_source/src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp:116:58: fatal error: use of undeclared identifier 'hasMoveState'
        if (PositionOkay(owner, target, maxRange, angle) && !hasMoveState)
                                                             ^
    1 error generated.
```

File: src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp [hunk 1]
```diff
@@ -96,8 +96,7 @@ bool ChaseMovementGenerator<T>::DoUpdate(T* owner, uint32 time_diff)
         }
     }
 
-    bool hasMoveState = owner->HasUnitState(UNIT_STATE_CHASE_MOVE) || owner->HasUnitState(UNIT_STATE_FOLLOW_MOVE);
```
Comment (Kitzunu) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp:99]: failing due to this removal as the variable is used on line 117

**Comment by mpfans** [comment]
`azerothcore/src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp:116:58: fatal error: use of undeclared identifier 'hasMoveState'
    if (PositionOkay(owner, target, maxRange, angle) && !hasMoveState)
                                                         ^
1 error generated.
src/server/game/CMakeFiles/game.dir/build.make:3877: recipe for target 'src/server/game/CMakeFiles/game.dir/Movement/MovementGenerators/TargetedMovementGenerator.cpp.o' failed
make[2]: *** [src/server/game/CMakeFiles/game.dir/Movement/MovementGenerators/TargetedMovementGenerator.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....`


Compilation error

**Comment by FrancescoBorzi** [comment]
I'm trying to fix the build of this PR myself as this bug should be fixed asap. However I wasn't involved in the pathfinding/movement rework so I don't know much about it.

**Comment by locus313** [comment]
just tested this looks much better, The pet no longer goes in circles.

**Comment by Footman** [comment]
tested on live. everything fine

**Comment by Footman** [comment]
this PR fixes also #4447

**Comment by Zoidwaffle** [comment]
I just tested the new version as well - all seems fine for my warlock pets <3

**Review by Voxstrasza — APPROVED** [review]

File: src/server/game/Entities/Unit/Unit.cpp [hunk 2]
```diff
@@ -3595,51 +3595,6 @@ bool Unit::isInBackInMap(Unit const* target, float distance, float arc) const
...
-                    return false;
-            }
-        }
-    }
-    else
-    {
-        // pussywizard: prevent any bugs by passengers exiting transports or normal creatures flying away
-        if (c->GetTransport() != this->GetTransport())
-            return false;
-    }
```
Comment (Yehonal) [inline src/server/game/Entities/Unit/Unit.cpp:3641]: Why? I know it's kind of a hack but what are you trying to solve removing them?

File: src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp [hunk 3]
```diff
@@ -237,7 +234,7 @@ bool FollowMovementGenerator<T>::PositionOkay(T* owner, Unit* target, float rang
     if (owner->GetExactDistSq(target) > G3D::square(owner->GetCombatReach() + target->GetCombatReach() + range))
         return false;
 
-    return !owner->IsPet() || !angle || angle->IsAngleOkay(target->GetRelativeAngle(owner));
+    return !owner->IsPet() || !angle || angle->IsAngleOkay(target->GetRelativeAngle(owner)); // need to check - dont think we need !pet exception here because there are scripts with MoveFollow that require angle
```
Comment (Yehonal) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp:237]: As regards the comment, check the 2nd part of this comment: https://github.com/azerothcore/azerothcore-wotlk/pull/4220#issuecomment-755395084

Multiple guardians summoned by quests and such kind of scripts, they should follow you by an angle specified when you summon them. Another solution would be to check here if the position is free and select a free spot otherwise

**Comment by FrancescoBorzi** [comment]
@Footman  Sorry but as this PR needs to be merged asap, I reverted the deletion in `Unit.cpp` as it was under debate (check @Yehonal 's comment). Feel free to create a new PR for that if you think it is needed.
