### PR TITLE
Fix(Core/Spells): Exploit with silithyst aura

### LINKED ISSUE #8873: Silithyst - Infinite Handins
### What client do you play on?

enGB

### Faction

- [x] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2227

I tried to turn in the silithyst into the extractor, but when i did, i didnt lose the silithyst and the horde counter went up by 1.
I tried then to go back and forth like 10 times and it remained attached to me, gaining always a +1.
Logging out and coming back solves the problem about consuming the silithyst.
So, unless u log out, with just 1 silithyst u can do infinite turn ins.

WoWScrnShot_110121_111920
WoWScrnShot_110121_111928

Tester: confirmed for both Horde and Alliance, although interestingly it's broken differently for both. For the Horde handin, as soon as you handin at the station, the silithyst drops and you can pick it up immediately and enter the station again:

https://user-images.githubusercontent.com/81782124/139665868-011b6a78-728b-4432-98a0-5723f09ddebd.mp4

Whereas for the Alliance version, you don't even have to do that, as the silithyst buff persists across handins and you can just walk in and out of the station forever:

https://user-images.githubusercontent.com/81782124/139665944-02b3f2f1-1e78-4a32-939e-2078d6013352.mp4

The stations are: 
- Silithus Flag Stand, Horde (ID 181617) -> casts spell 29785 which doesn't exist in the local spells.dbc file or on WowGaming. The spell_dbc table has it though, and WotLKDB has it too - https://wotlkdb.com/?spell=29785
- ToWoW - Flag Cap Counter, Horde (ID 181619) (of type 6, trap)

- Silithus Flag Stand, Alliance (ID 181603) -> casts spell 29785 as well.
- ToWoW - Flag Cap Counter, Alliance (ID 181618) (trap)

Possibly relevant: recent PR made changes to silithyst behaviour here: https://github.com/azerothcore/azerothcore-wotlk/pull/8656

### Expected Blizzlike Behaviour

https://www.youtube.com/watch?v=nI6VATVpN8Y&ab_channel=rangercolts

After a turn in, silithyst should disappear.

### Source
https://wowpedia.fandom.com/wiki/Silithyst?oldid=2184883
https://wowpedia.fandom.com/wiki/The_Silithyst_Must_Flow?oldid=2364758

### Steps to reproduce the problem

1. The silithyst aura can be added with `.aura 29519`
2. For Horde, `.go c 43204` will get you to a nearby NPC.
3. For Alliance, `.go c 43205`

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by Nefertumm**
## Changes Proposed:
-  Check if the player is mounted before spawning the gobject.

## Issues Addressed:

- Closes #8873
- Closes https://github.com/chromiecraft/chromiecraft/issues/2227

## Tests Performed:

- Build and tested, works

## How to Test the Changes:

1. The silithyst aura can be added with `.aura 29519`
2. For Horde, `.go c 43204` will get you to a nearby NPC.
3. For Alliance, `.go c 43205`

## Known Issues and TODO List:

- [ ] Check another way to exploit the spell.

### CODE REVIEW

**Review by Nyeriah — APPROVED** [review]

File: src/server/scripts/Spells/spell_generic.cpp [hunk 1]
```diff
@@ -5464,7 +5464,10 @@ class spell_silithyst : public SpellScriptLoader
 
         void OnRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
         {
-            GetCaster()->SummonGameObject(181597, GetCaster()->GetPositionX(), GetCaster()->GetPositionY(), GetCaster()->GetPositionZ(), 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 10 * IN_MILLISECONDS * MINUTE);
+            if (GetCaster()->IsMounted())
+            {
+                GetCaster()->SummonGameObject(181597, GetCaster()->GetPositionX(), GetCaster()->GetPositionY(), GetCaster()->GetPositionZ(), 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 10 * IN_MILLISECONDS * MINUTE);
+            }
```
Comment (Kitzunu) [inline src/server/scripts/Spells/spell_generic.cpp:5470]: 181597 magic number...

Comment (Nefertumm) [reply src/server/scripts/Spells/spell_generic.cpp:5470]: not mine hehe
