### PR TITLE
fix(scripts/Commands): Avoid get gm phase when summoning

### LINKED ISSUE #3702: When summoning/teleporting in GM mode, target player gets all phases
##### CURRENT BEHAVIOUR:
When I turn on GM mode and summon a player, their phase mask becomes 0xFFFF_FFFF (all phases).

##### EXPECTED BLIZZLIKE BEHAVIOUR:
This is a GM command, so I'm not sure what blizzlike behavior is, or if there's any public info about that. That said, I personally would not expect a GM summon to modify the player's phase. Perhaps I'm wrong + if I am, let's just close this, and I'll make a PR to add documentation about this behavior to the AzerothCore wiki instead.

##### STEPS TO REPRODUCE THE PROBLEM:
1. On a gm character, turn on gm mode, `.gm on`
2. Run `.pinfo anotherchar` on some other character that's online (and also not in gm mode). Note their phase. Usually it's `1`
2. Summon that character `.summon anotherchar`.
3. Run `.pinfo anotherchar` again.

*Expected*: Their phase has not changed
*Actual*: Their phase is set to `MAX_UNSIGNED_INT`, `4294967295`

A great way to test this is by summoning a player to the bank at undercity. Before you summon them, they'll see the city like normal. If you summon them while you're in GM mode, they'll see the city on fire. I suspect this is because GMs can see all phases, and the summon command is just using the GM's current phase mask.

Before summon
image
image

After summon
image
image

##### EXTRA NOTES:
* ~~The `.teleport name` command also exhibits this behavior~~ Looks like I was mistaken. The `.teleport name` command does not affect player phase.
* The screenshots above show me summoning a character who happens to be on an account with GM level 3. This also happens for characters on regular accounts

##### Workaround
* Reset the player's phase to 1 via `.modify phase 1`.
* Turn off GM mode and summon the player to a *different location*. If you teleport the player to the exact same coordinates, it will not set their phase. I assume this is because of an optimization in the teleport command

*Neither of these workarounds restore the player's phase to what it was before they were summoned, which will be a problem for players like death knights who rely heavily on phasing for their starting quest line.*

##### AC HASH/COMMIT:
27ed629ff5d49dee5e12e7564b52f232dda947b9

##### OPERATING SYSTEM:
Windows 10.0.19041

##### MODULES:
* mod-ah-bot (custom build from https://github.com/steenburgh/mod-ah-bot/pull/1)
* mod-autobalance

##### OTHER CUSTOMIZATIONS:
* I have applied the Brewfest Start Time fix from https://github.com/azerothcore/azerothcore-wotlk/pull/3487

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/94324985-when-summoning-teleporting-in-gm-mode-target-player-gets-all-phases?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Si1ker**
This change avoids setting the same phase as the one the GM has to a player when this is summoned by command

## CHANGES PROPOSED:
-  Remove SetPhaseMask at the end of the command execution

## ISSUES ADDRESSED:
- Closes #3702 

## TESTS PERFORMED:
- Tested in-game in several locations with GM only stuff like the entrance of Undercity, Archerus, Orgrimmar, etc

## HOW TO TEST THE CHANGES:

Get 2 accounts, 1 of them should be GM.

Create a fresh character with your normal account, in this example, we are gonna call it 'human'
with the gm account use: `.tele tirisfal`
move close to the entrance of undercity where you will see tanks and some leaders/npcs
with the gm account use:  `.summon human`

- The GM account can see all the war stuff
- The normal account will only see the normal phase

-> Test in other places.

## KNOWN ISSUES AND TODO LIST:

- N/A

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

File: src/server/scripts/Commands/cs_misc.cpp [hunk 1]
```diff
@@ -723,8 +723,7 @@ class misc_commandscript : public CommandScript
             // before GM
             float x, y, z;
             handler->GetSession()->GetPlayer()->GetClosePoint(x, y, z, target->GetObjectSize());
-            if (target->TeleportTo(handler->GetSession()->GetPlayer()->GetMapId(), x, y, z, target->GetOrientation(), 0, handler->GetSession()->GetPlayer()))
-                target->SetPhaseMask(handler->GetSession()->GetPlayer()->GetPhaseMask(), false);
+            target->TeleportTo(handler->GetSession()->GetPlayer()->GetMapId(), x, y, z, target->GetOrientation(), 0, handler->GetSession()->GetPlayer());
```
Comment (steenburgh) [inline src/server/scripts/Commands/cs_misc.cpp:726]: Interesting, so someone deliberately chose to copy the summoning player's phase mask. This makes it a lot easier to change.

Comment (steenburgh) [reply src/server/scripts/Commands/cs_misc.cpp:726]: Looking at the git history, this line has been here since the Sunwell code, so I can't find any record of why it was added +/or if there was discussion around it. 

https://github.com/azerothcore/azerothcore-wotlk/blob/e8e94a0a663be0a1cefe704d8c6860a526b2d7e9/src/server/scripts/Commands/cs_misc.cpp#L749
https://github.com/Kittnz/Sunwell/blame/master/src/server/scripts/Commands/cs_misc.cpp#L749

Comment (steenburgh) [reply src/server/scripts/Commands/cs_misc.cpp:726]: Ok so I decided to go down the rabbit hole further + found the initial trinity core commit that added this.
https://github.com/TrinityCore/TrinityCore/commit/35c57db00aaaee504baeaa243640eab5f5172f27

My interpretation of this is that they figured that when teleporting to a player you'd want to inherit their phase, and they decided that it naturally followed that teleporting a player to you should also copy their phase. What they didn't think of was that GMs could see all phases, and you wouldn't want this to be applied to a player a GM was moving around. This does assume that GMs seeing all phases was even a thing back in 2009.

Comment (Si1ker) [reply src/server/scripts/Commands/cs_misc.cpp:726]: @steenburgh test if you can and post result in a general comment, thanks for the investigation.

Comment (steenburgh) [reply src/server/scripts/Commands/cs_misc.cpp:726]: I'll test this later today (US Central time) if I can.

**Comment by steenburgh** [comment]
## ✅ All tests passed! 

### Testing procedure
1. Open two wow clients. Login as PlayerA on one and PlayerB on the other
2. Set each player up according to each test case outlined below.
  a. To setup a player's phase, target them and run `.modify phase ###` 
  b. To change GM mode, run `.gm on|off` *as the player you want to put in/take out of GM mode*
  c. Make sure the two players are in different positions. The summon command has an optimization built-in that won't teleport the target player if they're already in the target position. The best way to make sure this isn't an issue is to move one of the players a little bit between test cases
3. On PlayerA, run `.summon PlayerB`
4. On PlayerA, target PlayerB and run run `.pinfo` and write down PlayerB's phase


### Test Cases
PlayerA | PlayerB | Result before change (commit f64d4cee) | Expected result after change | Test Passed? (Actual result matches expected result?)
------------ | ------------- | ------------- | ------------- | -------------
GM mode on | Phase mask 1 | PlayerB gets phase mask FFFF_FFFF (4294967295)| PlayerB retains phase mask 1 | ✅ Yes
GM mode on | Phase mask 65 | PlayerB gets phase mask FFFF_FFFF | PlayerB retains phase mask 65 | ✅ Yes
Phase mask 1 | Phase mask 1 | PlayerB retains phase 1 | PlayerB retains phase mask 1 | ✅ Yes
Phase mask 65 | Phase mask 1 | PlayerB gets phase 65 | PlayerB retains phase mask 1 | ✅ Yes
Phase mask 1 | Phase mask 65 | PlayerB gets phase 1 | PlayerB retains phase mask 65 | ✅ Yes
Phase mask 1 | GM mode on | PlayerB's phase remains -1, GM mode remains on, but they can no longer see all phases. Toggling GM mode fixes this | PlayerB can still see all phases and retains GM mode | ✅ Yes
GM mode on | GM mode on | Nothing of note happens. PlayerB's phase remains -1 and GM mode remains on | PlayerB can still see all phases and retains GM mode | ✅ Yes

### Notes
* I chose Phase 65 because it's the easiest to see the effects of this phase. If a player is in undercity, they'll see the city on fire as shown in in the screenshots in #3702.
* I did not do any exploratory testing outside of the test cases described above
* I did not test any commands other than `.summon`. I think this is fine, but I'd like feedback from others on this.

**Comment by Si1ker** [comment]
@steenburgh woah awesome! really good testing report, you rocks! Very good job 😼

**Comment by FrancescoBorzi** [comment]
@steenburgh good job, cool test report!

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by steenburgh** [comment]
Thanks guys! Software engineering/testing is my day job, so I try to do a good job, even outside of work.

**Comment by FrancescoBorzi** [comment]
@steenburgh very good, we always need good testers at AzerothCore!

**Comment by BarbzYHOOL** [comment]
join us on our discord steenburgh!
