### PR TITLE
fix(DB/SAI): Shaleskin Flayer should cast Shaleskin out of combat

### LINKED ISSUE #15010: [NPC] Shaleskin Flayer - Shaleskin
https://github.com/chromiecraft/chromiecraft/issues/5000
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

65-69

### Current Behaviour

No Shaleskin spell usage

### Expected Blizzlike Behaviour

Keeps up Shaleskin out of combat

### Source

https://youtu.be/dwi2HSu5A4A?t=19

### Steps to reproduce the problem

.go c 71848

### Extra Notes

https://wowgaming.altervista.org/aowow/?npc=20210

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3f2364befeda2fe09fb495e2cb81f2974e6f59e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by Shaitz**
## Changes Proposed:
-  Shaleskin Flayer casts Shaleskin spell out of combat

## Issues Addressed:
- Closes #15010 
- Closes https://github.com/chromiecraft/chromiecraft/issues/5000

## SOURCE:
https://youtu.be/dwi2HSu5A4A?t=19

## Tests Performed:
- Tested in game. They cast the spell while out of combat.

## How to Test the Changes:
1. .go c 71848
2. check if they have cast the spell

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
It seems like that spell has a duration of 600000ms or 10min, so if it only is cast once Out of Combat, then it'd never be replenished if it falls off and no one aggroed it to reset the event.

The safest workaround would be adding a repeat timer to this OOC event, setting it to repeat at 600000ms exactly. That'd also require removing the NOT_REPEATABLE flag (1) from event_flags.

Thanks for the PR, btw 😁

**Comment by Shaitz** [comment]
is it okay now?

File: data/sql/updates/pending_db_world/rev_1680197775441354500.sql [hunk 1]
```diff
@@ -0,0 +1,6 @@
+--
+UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 20210;
+
```
Comment (Gultask) [inline data/sql/updates/pending_db_world/rev_1680197775441354500.sql:3]: One last thing, sorry!
Since they already have SAI you don't need this line

```suggestion
```

**Comment by Gultask** [comment]
Looks good to me, thanks again for the PR! 👍

**Review by Gultask — APPROVED** [review]
