### PR TITLE
fix(Core): Implement ACHIEVEMENT_FLAG_AVERAGE

### LINKED ISSUE #6901: Character Statistics - Average Gold Earned Per Day Incorrect
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/1168

In the statistics tab, the average gold earned per day does not scale with time.

Picture from Chromiecraft:
image

@jamadaha adds:
The same thing occurs on my character. (Unedited Chromiecraft instance on active server)
image

Tester: confirmed, same issue on various characters I checked.

WoWScrnShot_071221_222124
WoWScrnShot_071221_221646

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Average gold earned per day should be total gold aquired divided by the number of days since your character was created.

##### SOURCE:

image
Picture from Retail

##### STEPS TO REPRODUCE THE PROBLEM:

1. Have a character older than 1 day.
2. View statistics -> Wealth.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7c21d567d59153b37978756a5bf02daf6998e665

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99900432-character-statistics-average-gold-earned-per-day-incorrect?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sudlud**
## Changes Proposed:
This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

If your pull request promotes complex changes that require a detailed explanation, please describe them in detail specifying what your solution is and what is it meant to address.

## Issues Addressed:

- Closes #6901 

This PR fixes the following statistics:
- "Average gold earned per day"
- "Average quests completed per day"
- "Average daily quests completed per day"

These average values now get calculated like:
`average = total / (character_age * IN_DAYS)`

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. login to character 
2. observe correct average statistics value

(character age preferrably at least 2 days to get different values of "total" and "average".)

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/game/Entities/Player/Player.h [hunk 1]
```diff
@@ -2949,6 +2952,8 @@ class Player : public Unit, public GridObject<Player>
     bool _wasOutdoor;
 
     PlayerSettingMap m_charSettingsMap;
+
+    time_t m_creationDate;
```
Comment (Kitzunu) [inline src/server/game/Entities/Player/Player.h:2956]: Is there no way to use chrono for this? :(

Comment (sudlud) [reply src/server/game/Entities/Player/Player.h:2956]: The server requires us to send the milliseconds since character creation for the "average" achievement criteria, so I thought I'd be storing the Unix timestamp of character creation as reference. Also I'm not familiar with std::chrono, maybe you've got a suggestion and I can give it a try?

Comment (sudlud) [reply src/server/game/Entities/Player/Player.h:2956]: I will try to change it to using std chrono time_point to store the date if that's what you would prefer?

Comment (Kitzunu) [reply src/server/game/Entities/Player/Player.h:2956]: I don't really have time to look at it right now. But std chrono is always preferred when possible

Comment (sudlud) [reply src/server/game/Entities/Player/Player.h:2956]: Alright I will give it a try and provide an update

**Comment by sudlud** [comment]
@Kitzunu 
I updated the PR for std:chrono and also rearranged the implementation so it should now always work correctly right after applying the PR.
I had missed a second routine that also builds achievement data packets for the client that had to be updated.

File: src/server/game/Entities/Player/Player.cpp [hunk 2]
```diff
@@ -384,7 +384,7 @@ Player::Player(WorldSession* session): Unit(true), m_mover(this)
 
     _activeCheats = CHEAT_NONE;
 
-    m_creationDate = 0;
+    m_creationTime = Seconds(0);
```
Comment (Kitzunu) [inline src/server/game/Entities/Player/Player.cpp:387]:
```suggestion
    m_creationTime = 0s;
```

File: src/server/game/Entities/Player/PlayerStorage.cpp [hunk 3]
```diff
@@ -5027,7 +5027,7 @@ bool Player::LoadFromDB(ObjectGuid playerGuid, CharacterDatabaseQueryHolder cons
     SetFloatValue(UNIT_FIELD_HOVERHEIGHT, 1.0f);
 
     // load character creation date, relevant for achievements of type average
-    SetCreationDate(fields[74].Get<time_t>());
+    SetCreationTime(fields[74].Get<Seconds>());
```
Comment (Kitzunu) [inline src/server/game/Entities/Player/PlayerStorage.cpp:5030]: Unsure if this actually works. `UNIX_TIMESTAMP(creation_date)` is what you get

Comment (sudlud) [reply src/server/game/Entities/Player/PlayerStorage.cpp:5030]: On my windows setup this works as expected, m_creationTime has the correct Unix timestamp in seconds after this call

**Comment by sudlud** [comment]
@Kitzunu 
I just checked this again, m_creationTime has the correct timestamp in Seconds stored and all average statistics are shown correctly.

File: src/server/game/Achievements/AchievementMgr.cpp [hunk 4]
```diff
@@ -758,7 +758,22 @@ void AchievementMgr::SendCriteriaUpdate(AchievementCriteriaEntry const* entry, C
...
+
+    bool isAverageCriteria = false;
+
+    if ((sAchievementStore.LookupEntry(entry->referredAchievement))->flags & ACHIEVEMENT_FLAG_AVERAGE)
+        isAverageCriteria = true;
+
+    if (AchievementEntryList const* achRefList = sAchievementMgr->GetAchievementByReferencedId(entry->referredAchievement))
+        for (AchievementEntryList::const_iterator itr = achRefList->begin(); itr != achRefList->end(); ++itr)
+            if ((*itr)->flags & ACHIEVEMENT_FLAG_AVERAGE)
+                isAverageCriteria = true;
```
Comment (Kitzunu) [inline src/server/game/Achievements/AchievementMgr.cpp:770]: Ideally you move this to a function you can call within SendCriteriaUpdate() and BuildAllDataPacket() as it is the same code being repeated.

Comment (sudlud) [reply src/server/game/Achievements/AchievementMgr.cpp:770]: Yes I tried this but was too stupid to get it working. I'll try again.

Comment (Kitzunu) [reply src/server/game/Achievements/AchievementMgr.cpp:770]: If you need help I can look at it in the weekend

**Review by Kitzunu — APPROVED** [review]
