### PR TITLE
fix(DB): Webbed Creature missing flags

### LINKED ISSUE #6478: Bloodmyst Isle - Webbed Creatures Tauntable and Mobile
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/941

Webbed Creature for quest They're Alive! Maybe... are tauntable and will then move towards you. They will also start hitting you for considerable amount of damage

Tester: confirmed. I'm not sure which speicifc flags should be set to stop them moving around, but setting NO_TAUNT in extra_flags would stop this at least. They are running a script called npc_webbed_creature, but can't find more info on that.

https://user-images.githubusercontent.com/81782124/122769218-883c6280-d2e3-11eb-9616-156a6eb7b1b3.mp4

Note that there are a fair number of other issues raised about Webbed Creatures, but this doesn't seem to be covered by any of them.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Webbed Creature is a stationary unit and should not attack you. See the comments under the [wowhead source](https://tbc.wowhead.com/quest=9670/theyre-alive-maybe#comments). 

> Be warned that hurting the cocoons will leave you in combat unless you finish them off. I accidentally tagged a couple with some AoE's.

which indicates clearly that they are not coming for you to engage in combat or hurt you.

##### SOURCE:

https://tbc.wowhead.com/quest=9670/theyre-alive-maybe#comments
https://tbc.wowhead.com/npc=17680/webbed-creature

##### STEPS TO REPRODUCE THE PROBLEM:

1.  .go c 63403
2.  Use Taunt on a Webbed Creature ( I used bear form Growl)
3.  walk around with a webbed creature following you, and hitting you for twice the amount of damage a normal creature would from that bracket.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99367767-bloodmyst-isle-webbed-creatures-tauntable-and-mobile?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:
-  Added flags to creature

## Issues Addressed:

- Closes #6478

## Tests Performed:

- Tested in-game
Screenshot_1

## How to Test the Changes:

1. .go c id 17680
2. They are immune to taunt
3. They are immobile
4. They don't attack
5. They can't dodge attacks

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: data/sql/updates/pending_db_world/rev_1624283834038071800.sql [hunk 1]
```diff
@@ -0,0 +1,3 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1624283834038071800');
+
+UPDATE `creature_template` SET `unit_flags` = 131076, `flags_extra` = 8388866 WHERE (`entry` = 17680);
```
Comment (Kitzunu) [inline data/sql/updates/pending_db_world/rev_1624283834038071800.sql:3]: https://www.azerothcore.org/wiki/sql-standards#flags-amp-bits

Comment (claudiodfc) [reply data/sql/updates/pending_db_world/rev_1624283834038071800.sql:3]: @FrancescoBorzi you should optimize keira for this :D

**Review by Helias — APPROVED** [review]
