### PR TITLE
fix(Core/Misc): Memleaks fixes. Part I.

### LINKED ISSUE #5535: Server stuck
## CURRENT BEHAVIOUR:
The server will be stuck in about 4-5 hours

After 4 hours of run
image
After 5 hours of run
image

image

## STEPS TO REPRODUCE THE PROBLEM:
1. run worldserver
2. Maybe you need a lot of players online

## AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/28ce1e921921a1d04f718056583c9b62dc219edf

## OPERATING SYSTEM:
ubuntu 20.04

## MODULES:
mod-anticheat
mod-multi-client-check

Maybe it's because of this commit
https://github.com/azerothcore/azerothcore-wotlk/commit/4af4cbd3d966a05c584f4b6c63f69517dad0677d

Because I tested it before https://github.com/azerothcore/azerothcore-wotlk/commit/b2861be1cd623182fd9e900c9ccfe8e063f28d8e For a week, no problem was found

It was upgraded from b9e84d8 to 28ce1e9 that the server stuck

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98170507-server-stuck?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #5544: [PLACEHOLDER] Fix possible memleaks [$25]
Assigned to @UltraNix 

```
==20421== Memcheck, a memory error detector
==20421== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==20421== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==20421== Command: ./worldserver
==20421== Parent PID: 1500
==20421== 
==20421== Thread 22:
==20421== Use of uninitialised value of size 8
==20421==    at 0x6A3092: Creature* ObjectAccessor::GetObjectInMap<Creature>(unsigned long, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xCBAC3C: npc_thrall_bfu::npc_thrall_bfuAI::Reset() (in /home/user/run/bin/worldserver)
==20421==    by 0x4EA8EA: Creature::AddToWorld() (in /home/user/run/bin/worldserver)
==20421==    by 0xB8D934: void AddObjectHelper<Creature>(CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E624: void LoadHelper<Creature>(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&, CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8DFCB: ObjectGridLoader::Visit(GridRefManager<Creature>&) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E3BB: ObjectGridLoader::LoadN() (in /home/user/run/bin/worldserver)
==20421==    by 0x85DDA9: Map::EnsureGridLoaded(Cell const&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85F7C0: Map::VisitNearbyCellsOf(WorldObject*, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85FA7F: Map::Update(unsigned int, unsigned int, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x87512B: MapUpdateRequest::call() (in /home/user/run/bin/worldserver)
==20421==    by 0x874AA9: MapUpdater::WorkerThread() (in /home/user/run/bin/worldserver)
==20421== 
==20421== Use of uninitialised value of size 8
==20421==    at 0x6A3092: Creature* ObjectAccessor::GetObjectInMap<Creature>(unsigned long, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xCBAC66: npc_thrall_bfu::npc_thrall_bfuAI::Reset() (in /home/user/run/bin/worldserver)
==20421==    by 0x4EA8EA: Creature::AddToWorld() (in /home/user/run/bin/worldserver)
==20421==    by 0xB8D934: void AddObjectHelper<Creature>(CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E624: void LoadHelper<Creature>(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&, CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8DFCB: ObjectGridLoader::Visit(GridRefManager<Creature>&) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E3BB: ObjectGridLoader::LoadN() (in /home/user/run/bin/worldserver)
==20421==    by 0x85DDA9: Map::EnsureGridLoaded(Cell const&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85F7C0: Map::VisitNearbyCellsOf(WorldObject*, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85FA7F: Map::Update(unsigned int, unsigned int, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x87512B: MapUpdateRequest::call() (in /home/user/run/bin/worldserver)
==20421==    by 0x874AA9: MapUpdater::WorkerThread() (in /home/user/run/bin/worldserver)
==20421== 
==20421== Use of uninitialised value of size 8
==20421==    at 0x6A3092: Creature* ObjectAccessor::GetObjectInMap<Creature>(unsigned long, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xCBAC90: npc_thrall_bfu::npc_thrall_bfuAI::Reset() (in /home/user/run/bin/worldserver)
==20421==    by 0x4EA8EA: Creature::AddToWorld() (in /home/user/run/bin/worldserver)
==20421==    by 0xB8D934: void AddObjectHelper<Creature>(CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E624: void LoadHelper<Creature>(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&, CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8DFCB: ObjectGridLoader::Visit(GridRefManager<Creature>&) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E3BB: ObjectGridLoader::LoadN() (in /home/user/run/bin/worldserver)
==20421==    by 0x85DDA9: Map::EnsureGridLoaded(Cell const&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85F7C0: Map::VisitNearbyCellsOf(WorldObject*, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85FA7F: Map::Update(unsigned int, unsigned int, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x87512B: MapUpdateRequest::call() (in /home/user/run/bin/worldserver)
==20421==    by 0x874AA9: MapUpdater::WorkerThread() (in /home/user/run/bin/worldserver)
==20421== 
==20421== Use of uninitialised value of size 8
==20421==    at 0x6A3092: Creature* ObjectAccessor::GetObjectInMap<Creature>(unsigned long, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xCBACBA: npc_thrall_bfu::npc_thrall_bfuAI::Reset() (in /home/user/run/bin/worldserver)
==20421==    by 0x4EA8EA: Creature::AddToWorld() (in /home/user/run/bin/worldserver)
==20421==    by 0xB8D934: void AddObjectHelper<Creature>(CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E624: void LoadHelper<Creature>(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&, CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8DFCB: ObjectGridLoader::Visit(GridRefManager<Creature>&) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E3BB: ObjectGridLoader::LoadN() (in /home/user/run/bin/worldserver)
==20421==    by 0x85DDA9: Map::EnsureGridLoaded(Cell const&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85F7C0: Map::VisitNearbyCellsOf(WorldObject*, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85FA7F: Map::Update(unsigned int, unsigned int, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x87512B: MapUpdateRequest::call() (in /home/user/run/bin/worldserver)
==20421==    by 0x874AA9: MapUpdater::WorkerThread() (in /home/user/run/bin/worldserver)
==20421== 
==20421== Use of uninitialised value of size 8
==20421==    at 0x6A3092: Creature* ObjectAccessor::GetObjectInMap<Creature>(unsigned long, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xCBACE4: npc_thrall_bfu::npc_thrall_bfuAI::Reset() (in /home/user/run/bin/worldserver)
==20421==    by 0x4EA8EA: Creature::AddToWorld() (in /home/user/run/bin/worldserver)
==20421==    by 0xB8D934: void AddObjectHelper<Creature>(CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E624: void LoadHelper<Creature>(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&, CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8DFCB: ObjectGridLoader::Visit(GridRefManager<Creature>&) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E3BB: ObjectGridLoader::LoadN() (in /home/user/run/bin/worldserver)
==20421==    by 0x85DDA9: Map::EnsureGridLoaded(Cell const&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85F7C0: Map::VisitNearbyCellsOf(WorldObject*, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85FA7F: Map::Update(unsigned int, unsigned int, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x87512B: MapUpdateRequest::call() (in /home/user/run/bin/worldserver)
==20421==    by 0x874AA9: MapUpdater::WorkerThread() (in /home/user/run/bin/worldserver)
==20421== 
==20421== Thread 23:
==20421== Use of uninitialised value of size 8
==20421==    at 0x6A3092: Creature* ObjectAccessor::GetObjectInMap<Creature>(unsigned long, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xCB483A: npc_varian_wrynn::npc_varian_wrynnAI::Reset() (in /home/user/run/bin/worldserver)
==20421==    by 0x4EA8EA: Creature::AddToWorld() (in /home/user/run/bin/worldserver)
==20421==    by 0xB8D934: void AddObjectHelper<Creature>(CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E624: void LoadHelper<Creature>(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&, CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8DFCB: ObjectGridLoader::Visit(GridRefManager<Creature>&) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E3BB: ObjectGridLoader::LoadN() (in /home/user/run/bin/worldserver)
==20421==    by 0x85DDA9: Map::EnsureGridLoaded(Cell const&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85DF2E: Map::LoadGrid(float, float) (in /home/user/run/bin/worldserver)
==20421==    by 0x5F44AE: MotionTransport::DelayedTeleportTransport() (in /home/user/run/bin/worldserver)
==20421==    by 0x864EB8: Map::DelayedUpdate(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x873A60: MapManager::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421== 
==20421== Use of uninitialised value of size 8
==20421==    at 0x6A3092: Creature* ObjectAccessor::GetObjectInMap<Creature>(unsigned long, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xCB4864: npc_varian_wrynn::npc_varian_wrynnAI::Reset() (in /home/user/run/bin/worldserver)
==20421==    by 0x4EA8EA: Creature::AddToWorld() (in /home/user/run/bin/worldserver)
==20421==    by 0xB8D934: void AddObjectHelper<Creature>(CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E624: void LoadHelper<Creature>(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&, CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8DFCB: ObjectGridLoader::Visit(GridRefManager<Creature>&) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E3BB: ObjectGridLoader::LoadN() (in /home/user/run/bin/worldserver)... (2 MB left)

==20421== Memcheck, a memory error detector
==20421== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==20421== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==20421== Command: ./worldserver
==20421== Parent PID: 1500
==20421== 
==20421== Thread 22:
==20421== Use of uninitialised value of size 8
==20421==    at 0x6A3092: Creature* ObjectAccessor::GetObjectInMap<Creature>(unsigned long, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xCBAC3C: npc_thrall_bfu::npc_thrall_bfuAI::Reset() (in /home/user/run/bin/worldserver)
==20421==    by 0x4EA8EA: Creature::AddToWorld() (in /home/user/run/bin/worldserver)
==20421==    by 0xB8D934: void AddObjectHelper<Creature>(CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E624: void LoadHelper<Creature>(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&, CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8DFCB: ObjectGridLoader::Visit(GridRefManager<Creature>&) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E3BB: ObjectGridLoader::LoadN() (in /home/user/run/bin/worldserver)
==20421==    by 0x85DDA9: Map::EnsureGridLoaded(Cell const&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85F7C0: Map::VisitNearbyCellsOf(WorldObject*, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85FA7F: Map::Update(unsigned int, unsigned int, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x87512B: MapUpdateRequest::call() (in /home/user/run/bin/worldserver)
==20421==    by 0x874AA9: MapUpdater::WorkerThread() (in /home/user/run/bin/worldserver)
==20421== 
==20421== Use of uninitialised value of size 8
==20421==    at 0x6A3092: Creature* ObjectAccessor::GetObjectInMap<Creature>(unsigned long, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xCBAC66: npc_thrall_bfu::npc_thrall_bfuAI::Reset() (in /home/user/run/bin/worldserver)
==20421==    by 0x4EA8EA: Creature::AddToWorld() (in /home/user/run/bin/worldserver)
==20421==    by 0xB8D934: void AddObjectHelper<Creature>(CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E624: void LoadHelper<Creature>(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&, CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8DFCB: ObjectGridLoader::Visit(GridRefManager<Creature>&) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E3BB: ObjectGridLoader::LoadN() (in /home/user/run/bin/worldserver)
==20421==    by 0x85DDA9: Map::EnsureGridLoaded(Cell const&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85F7C0: Map::VisitNearbyCellsOf(WorldObject*, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85FA7F: Map::Update(unsigned int, unsigned int, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x87512B: MapUpdateRequest::call() (in /home/user/run/bin/worldserver)
==20421==    by 0x874AA9: MapUpdater::WorkerThread() (in /home/user/run/bin/worldserver)
==20421== 
==20421== Use of uninitialised value of size 8
==20421==    at 0x6A3092: Creature* ObjectAccessor::GetObjectInMap<Creature>(unsigned long, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xCBAC90: npc_thrall_bfu::npc_thrall_bfuAI::Reset() (in /home/user/run/bin/worldserver)
==20421==    by 0x4EA8EA: Creature::AddToWorld() (in /home/user/run/bin/worldserver)
==20421==    by 0xB8D934: void AddObjectHelper<Creature>(CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E624: void LoadHelper<Creature>(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&, CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8DFCB: ObjectGridLoader::Visit(GridRefManager<Creature>&) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E3BB: ObjectGridLoader::LoadN() (in /home/user/run/bin/worldserver)
==20421==    by 0x85DDA9: Map::EnsureGridLoaded(Cell const&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85F7C0: Map::VisitNearbyCellsOf(WorldObject*, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85FA7F: Map::Update(unsigned int, unsigned int, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x87512B: MapUpdateRequest::call() (in /home/user/run/bin/worldserver)
==20421==    by 0x874AA9: MapUpdater::WorkerThread() (in /home/user/run/bin/worldserver)
==20421== 
==20421== Use of uninitialised value of size 8
==20421==    at 0x6A3092: Creature* ObjectAccessor::GetObjectInMap<Creature>(unsigned long, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xCBACBA: npc_thrall_bfu::npc_thrall_bfuAI::Reset() (in /home/user/run/bin/worldserver)
==20421==    by 0x4EA8EA: Creature::AddToWorld() (in /home/user/run/bin/worldserver)
==20421==    by 0xB8D934: void AddObjectHelper<Creature>(CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E624: void LoadHelper<Creature>(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&, CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8DFCB: ObjectGridLoader::Visit(GridRefManager<Creature>&) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E3BB: ObjectGridLoader::LoadN() (in /home/user/run/bin/worldserver)
==20421==    by 0x85DDA9: Map::EnsureGridLoaded(Cell const&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85F7C0: Map::VisitNearbyCellsOf(WorldObject*, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85FA7F: Map::Update(unsigned int, unsigned int, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x87512B: MapUpdateRequest::call() (in /home/user/run/bin/worldserver)
==20421==    by 0x874AA9: MapUpdater::WorkerThread() (in /home/user/run/bin/worldserver)
==20421== 
==20421== Use of uninitialised value of size 8
==20421==    at 0x6A3092: Creature* ObjectAccessor::GetObjectInMap<Creature>(unsigned long, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xCBACE4: npc_thrall_bfu::npc_thrall_bfuAI::Reset() (in /home/user/run/bin/worldserver)
==20421==    by 0x4EA8EA: Creature::AddToWorld() (in /home/user/run/bin/worldserver)
==20421==    by 0xB8D934: void AddObjectHelper<Creature>(CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E624: void LoadHelper<Creature>(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&, CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8DFCB: ObjectGridLoader::Visit(GridRefManager<Creature>&) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E3BB: ObjectGridLoader::LoadN() (in /home/user/run/bin/worldserver)
==20421==    by 0x85DDA9: Map::EnsureGridLoaded(Cell const&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85F7C0: Map::VisitNearbyCellsOf(WorldObject*, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, TypeContainerVisitor<acore::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85FA7F: Map::Update(unsigned int, unsigned int, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x87512B: MapUpdateRequest::call() (in /home/user/run/bin/worldserver)
==20421==    by 0x874AA9: MapUpdater::WorkerThread() (in /home/user/run/bin/worldserver)
==20421== 
==20421== Thread 23:
==20421== Use of uninitialised value of size 8
==20421==    at 0x6A3092: Creature* ObjectAccessor::GetObjectInMap<Creature>(unsigned long, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xCB483A: npc_varian_wrynn::npc_varian_wrynnAI::Reset() (in /home/user/run/bin/worldserver)
==20421==    by 0x4EA8EA: Creature::AddToWorld() (in /home/user/run/bin/worldserver)
==20421==    by 0xB8D934: void AddObjectHelper<Creature>(CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E624: void LoadHelper<Creature>(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&, CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8DFCB: ObjectGridLoader::Visit(GridRefManager<Creature>&) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E3BB: ObjectGridLoader::LoadN() (in /home/user/run/bin/worldserver)
==20421==    by 0x85DDA9: Map::EnsureGridLoaded(Cell const&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85DF2E: Map::LoadGrid(float, float) (in /home/user/run/bin/worldserver)
==20421==    by 0x5F44AE: MotionTransport::DelayedTeleportTransport() (in /home/user/run/bin/worldserver)
==20421==    by 0x864EB8: Map::DelayedUpdate(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x873A60: MapManager::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421== 
==20421== Use of uninitialised value of size 8
==20421==    at 0x6A3092: Creature* ObjectAccessor::GetObjectInMap<Creature>(unsigned long, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xCB4864: npc_varian_wrynn::npc_varian_wrynnAI::Reset() (in /home/user/run/bin/worldserver)
==20421==    by 0x4EA8EA: Creature::AddToWorld() (in /home/user/run/bin/worldserver)
==20421==    by 0xB8D934: void AddObjectHelper<Creature>(CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E624: void LoadHelper<Creature>(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&, CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8DFCB: ObjectGridLoader::Visit(GridRefManager<Creature>&) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E3BB: ObjectGridLoader::LoadN() (in /home/user/run/bin/worldserver)
==20421==    by 0x85DDA9: Map::EnsureGridLoaded(Cell const&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85DF2E: Map::LoadGrid(float, float) (in /home/user/run/bin/worldserver)
==20421==    by 0x5F44AE: MotionTransport::DelayedTeleportTransport() (in /home/user/run/bin/worldserver)
==20421==    by 0x864EB8: Map::DelayedUpdate(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x873A60: MapManager::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421== 
==20421== Use of uninitialised value of size 8
==20421==    at 0x6A3092: Creature* ObjectAccessor::GetObjectInMap<Creature>(unsigned long, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xCB488E: npc_varian_wrynn::npc_varian_wrynnAI::Reset() (in /home/user/run/bin/worldserver)
==20421==    by 0x4EA8EA: Creature::AddToWorld() (in /home/user/run/bin/worldserver)
==20421==    by 0xB8D934: void AddObjectHelper<Creature>(CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E624: void LoadHelper<Creature>(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&, CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8DFCB: ObjectGridLoader::Visit(GridRefManager<Creature>&) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E3BB: ObjectGridLoader::LoadN() (in /home/user/run/bin/worldserver)
==20421==    by 0x85DDA9: Map::EnsureGridLoaded(Cell const&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85DF2E: Map::LoadGrid(float, float) (in /home/user/run/bin/worldserver)
==20421==    by 0x5F44AE: MotionTransport::DelayedTeleportTransport() (in /home/user/run/bin/worldserver)
==20421==    by 0x864EB8: Map::DelayedUpdate(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x873A60: MapManager::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421== 
==20421== Use of uninitialised value of size 8
==20421==    at 0x6A3092: Creature* ObjectAccessor::GetObjectInMap<Creature>(unsigned long, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xCB48B8: npc_varian_wrynn::npc_varian_wrynnAI::Reset() (in /home/user/run/bin/worldserver)
==20421==    by 0x4EA8EA: Creature::AddToWorld() (in /home/user/run/bin/worldserver)
==20421==    by 0xB8D934: void AddObjectHelper<Creature>(CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E624: void LoadHelper<Creature>(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&, CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8DFCB: ObjectGridLoader::Visit(GridRefManager<Creature>&) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E3BB: ObjectGridLoader::LoadN() (in /home/user/run/bin/worldserver)
==20421==    by 0x85DDA9: Map::EnsureGridLoaded(Cell const&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85DF2E: Map::LoadGrid(float, float) (in /home/user/run/bin/worldserver)
==20421==    by 0x5F44AE: MotionTransport::DelayedTeleportTransport() (in /home/user/run/bin/worldserver)
==20421==    by 0x864EB8: Map::DelayedUpdate(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x873A60: MapManager::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421== 
==20421== Use of uninitialised value of size 8
==20421==    at 0x6A3092: Creature* ObjectAccessor::GetObjectInMap<Creature>(unsigned long, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xCB48E2: npc_varian_wrynn::npc_varian_wrynnAI::Reset() (in /home/user/run/bin/worldserver)
==20421==    by 0x4EA8EA: Creature::AddToWorld() (in /home/user/run/bin/worldserver)
==20421==    by 0xB8D934: void AddObjectHelper<Creature>(CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*, Creature*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E624: void LoadHelper<Creature>(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&, CoordPair<512u>&, GridRefManager<Creature>&, unsigned int&, Map*) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8DFCB: ObjectGridLoader::Visit(GridRefManager<Creature>&) (in /home/user/run/bin/worldserver)
==20421==    by 0xB8E3BB: ObjectGridLoader::LoadN() (in /home/user/run/bin/worldserver)
==20421==    by 0x85DDA9: Map::EnsureGridLoaded(Cell const&) (in /home/user/run/bin/worldserver)
==20421==    by 0x85DF2E: Map::LoadGrid(float, float) (in /home/user/run/bin/worldserver)
==20421==    by 0x5F44AE: MotionTransport::DelayedTeleportTransport() (in /home/user/run/bin/worldserver)
==20421==    by 0x864EB8: Map::DelayedUpdate(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x873A60: MapManager::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421== 
==20421== Thread 22:
==20421== Conditional jump or move depends on uninitialised value(s)
==20421==    at 0x546EAE: Player::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x85FE42: Map::Update(unsigned int, unsigned int, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x87512B: MapUpdateRequest::call() (in /home/user/run/bin/worldserver)
==20421==    by 0x874AA9: MapUpdater::WorkerThread() (in /home/user/run/bin/worldserver)
==20421==    by 0x560CD83: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==20421==    by 0x4E20608: start_thread (pthread_create.c:477)
==20421==    by 0x59A5292: clone (clone.S:95)
==20421== 
==20421== Conditional jump or move depends on uninitialised value(s)
==20421==    at 0x546EBE: Player::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x85FE42: Map::Update(unsigned int, unsigned int, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x87512B: MapUpdateRequest::call() (in /home/user/run/bin/worldserver)
==20421==    by 0x874AA9: MapUpdater::WorkerThread() (in /home/user/run/bin/worldserver)
==20421==    by 0x560CD83: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==20421==    by 0x4E20608: start_thread (pthread_create.c:477)
==20421==    by 0x59A5292: clone (clone.S:95)
==20421== 
==20421== Conditional jump or move depends on uninitialised value(s)
==20421==    at 0x546EAE: Player::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x85FAF8: Map::Update(unsigned int, unsigned int, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x87512B: MapUpdateRequest::call() (in /home/user/run/bin/worldserver)
==20421==    by 0x874AA9: MapUpdater::WorkerThread() (in /home/user/run/bin/worldserver)
==20421==    by 0x560CD83: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==20421==    by 0x4E20608: start_thread (pthread_create.c:477)
==20421==    by 0x59A5292: clone (clone.S:95)
==20421== 
==20421== Conditional jump or move depends on uninitialised value(s)
==20421==    at 0x546EBE: Player::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x85FAF8: Map::Update(unsigned int, unsigned int, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x87512B: MapUpdateRequest::call() (in /home/user/run/bin/worldserver)
==20421==    by 0x874AA9: MapUpdater::WorkerThread() (in /home/user/run/bin/worldserver)
==20421==    by 0x560CD83: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==20421==    by 0x4E20608: start_thread (pthread_create.c:477)
==20421==    by 0x59A5292: clone (clone.S:95)
==20421== 
==20421== Thread 28:
==20421== Syscall param socketcall.sendto(msg) points to uninitialised byte(s)
==20421==    at 0x4E2B7DC: __libc_send (send.c:28)
==20421==    by 0x4E2B7DC: send (send.c:23)
==20421==    by 0x4982594: ACE::send(int, void const*, unsigned long, int, ACE_Time_Value const*) (in /usr/lib/libACE-6.4.5.so)
==20421==    by 0x92E1DE: WorldSocket::handle_output(int) (in /home/user/run/bin/worldserver)
==20421==    by 0x92E133: WorldSocket::Update() (in /home/user/run/bin/worldserver)
==20421==    by 0x49B298E: ACE_Dev_Poll_Reactor::dispatch_io_event(ACE_Dev_Poll_Reactor::Token_Guard&) (in /usr/lib/libACE-6.4.5.so)
==20421==    by 0x49B429A: ACE_Dev_Poll_Reactor::handle_events(ACE_Time_Value*) (in /usr/lib/libACE-6.4.5.so)
==20421==    by 0x4A03251: ACE_Reactor::run_reactor_event_loop(ACE_Time_Value&, int (*)(ACE_Reactor*)) (in /usr/lib/libACE-6.4.5.so)
==20421==    by 0x939CEB: ReactorRunnable::svc() (in /home/user/run/bin/worldserver)
==20421==    by 0x4A20704: ACE_Task_Base::svc_run(void*) (in /usr/lib/libACE-6.4.5.so)
==20421==    by 0x4A21715: ACE_Thread_Adapter::invoke_i() (in /usr/lib/libACE-6.4.5.so)
==20421==    by 0x4A215FE: ACE_Thread_Adapter::invoke() (in /usr/lib/libACE-6.4.5.so)
==20421==    by 0x4E20608: start_thread (pthread_create.c:477)
==20421==  Address 0xed684947 is 8,679 bytes inside a block of size 65,536 alloc'd
==20421==    at 0x483C813: operator new[](unsigned long, std::nothrow_t const&) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==20421==    by 0x49CBDAC: ACE_New_Allocator::malloc(unsigned long) (in /usr/lib/libACE-6.4.5.so)
==20421==    by 0x49CCD1C: ACE_Data_Block::ACE_Data_Block(unsigned long, int, char const*, ACE_Allocator*, ACE_Lock*, unsigned long, ACE_Allocator*) (in /usr/lib/libACE-6.4.5.so)
==20421==    by 0x49CD1BA: ACE_Message_Block::init_i(unsigned long, int, ACE_Message_Block*, char const*, ACE_Allocator*, ACE_Lock*, unsigned long, unsigned long, ACE_Time_Value const&, ACE_Time_Value const&, ACE_Data_Block*, ACE_Allocator*, ACE_Allocator*) (in /usr/lib/libACE-6.4.5.so)
==20421==    by 0x49CD3CF: ACE_Message_Block::ACE_Message_Block(unsigned long, int, ACE_Message_Block*, char const*, ACE_Allocator*, ACE_Lock*, unsigned long, ACE_Time_Value const&, ACE_Time_Value const&, ACE_Allocator*, ACE_Allocator*) (in /usr/lib/libACE-6.4.5.so)
==20421==    by 0x92D2F5: WorldSocket::open(void*) (in /home/user/run/bin/worldserver)
==20421==    by 0x93ACB9: ACE_Acceptor<WorldSocket, ACE_SOCK_Acceptor>::activate_svc_handler(WorldSocket*) (in /home/user/run/bin/worldserver)
==20421==    by 0x93A217: ACE_Acceptor<WorldSocket, ACE_SOCK_Acceptor>::handle_input(int) (in /home/user/run/bin/worldserver)
==20421==    by 0x49B298E: ACE_Dev_Poll_Reactor::dispatch_io_event(ACE_Dev_Poll_Reactor::Token_Guard&) (in /usr/lib/libACE-6.4.5.so)
==20421==    by 0x49B429A: ACE_Dev_Poll_Reactor::handle_events(ACE_Time_Value*) (in /usr/lib/libACE-6.4.5.so)
==20421==    by 0x4A03251: ACE_Reactor::run_reactor_event_loop(ACE_Time_Value&, int (*)(ACE_Reactor*)) (in /usr/lib/libACE-6.4.5.so)
==20421==    by 0x939CEB: ReactorRunnable::svc() (in /home/user/run/bin/worldserver)
==20421== 
==20421== Thread 23:
==20421== Conditional jump or move depends on uninitialised value(s)
==20421==    at 0x5A9535: Player::_LoadMail() (in /home/user/run/bin/worldserver)
==20421==    by 0xBC87F7: WorldSession::HandleGetMailList(WorldPacket&) (in /home/user/run/bin/worldserver)
==20421==    by 0x922899: WorldSession::Update(unsigned int, PacketFilter&) (in /home/user/run/bin/worldserver)
==20421==    by 0xA4BDD0: World::UpdateSessions(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0xA498AC: World::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x44AF20: WorldRunnable::run() (in /home/user/run/bin/worldserver)
==20421==    by 0x560CD83: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==20421==    by 0x4E20608: start_thread (pthread_create.c:477)
==20421==    by 0x59A5292: clone (clone.S:95)
==20421== 
==20421== Conditional jump or move depends on uninitialised value(s)
==20421==    at 0x5A9535: Player::_LoadMail() (in /home/user/run/bin/worldserver)
==20421==    by 0xBCA0F5: WorldSession::HandleQueryNextMailTime(WorldPacket&) (in /home/user/run/bin/worldserver)
==20421==    by 0x922899: WorldSession::Update(unsigned int, PacketFilter&) (in /home/user/run/bin/worldserver)
==20421==    by 0xA4BDD0: World::UpdateSessions(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0xA498AC: World::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x44AF20: WorldRunnable::run() (in /home/user/run/bin/worldserver)
==20421==    by 0x560CD83: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==20421==    by 0x4E20608: start_thread (pthread_create.c:477)
==20421==    by 0x59A5292: clone (clone.S:95)
==20421== 
==20421== Invalid read of size 4
==20421==    at 0x4E247B4: __pthread_mutex_unlock_usercnt (pthread_mutex_unlock.c:41)
==20421==    by 0x4E247B4: pthread_mutex_unlock (pthread_mutex_unlock.c:357)
==20421==    by 0x83A404: InstanceSave::RemovePlayer(unsigned int, InstanceSaveManager*) (in /home/user/run/bin/worldserver)
==20421==    by 0x5B4D42: Player::ResetInstances(unsigned long, unsigned char, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x7BDF2D: Group::Disband(bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x7BD295: Group::RemoveMember(unsigned long, RemoveMethod const&, unsigned long, char const*) (in /home/user/run/bin/worldserver)
==20421==    by 0x555353: Player::RemoveFromGroup(Group*, unsigned long, RemoveMethod, unsigned long, char const*) (in /home/user/run/bin/worldserver)
==20421==    by 0x922899: WorldSession::Update(unsigned int, PacketFilter&) (in /home/user/run/bin/worldserver)
==20421==    by 0xA4BDD0: World::UpdateSessions(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0xA498AC: World::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x44AF20: WorldRunnable::run() (in /home/user/run/bin/worldserver)
==20421==    by 0x560CD83: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==20421==    by 0x4E20608: start_thread (pthread_create.c:477)
==20421==  Address 0x11a7dfc0 is 112 bytes inside a block of size 136 free'd
==20421==    at 0x483CFBF: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==20421==    by 0x83A04B: InstanceSaveManager::DeleteInstanceSaveIfNeeded(InstanceSave*, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x83A3F0: InstanceSave::RemovePlayer(unsigned int, InstanceSaveManager*) (in /home/user/run/bin/worldserver)
==20421==    by 0x5B4D42: Player::ResetInstances(unsigned long, unsigned char, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x7BDF2D: Group::Disband(bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x7BD295: Group::RemoveMember(unsigned long, RemoveMethod const&, unsigned long, char const*) (in /home/user/run/bin/worldserver)
==20421==    by 0x555353: Player::RemoveFromGroup(Group*, unsigned long, RemoveMethod, unsigned long, char const*) (in /home/user/run/bin/worldserver)
==20421==    by 0x922899: WorldSession::Update(unsigned int, PacketFilter&) (in /home/user/run/bin/worldserver)
==20421==    by 0xA4BDD0: World::UpdateSessions(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0xA498AC: World::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x44AF20: WorldRunnable::run() (in /home/user/run/bin/worldserver)
==20421==    by 0x560CD83: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==20421==  Block was alloc'd at
==20421==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==20421==    by 0x839604: InstanceSaveManager::AddInstanceSave(unsigned int, unsigned int, Difficulty, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x83B628: InstanceSaveManager::LoadInstanceSaves() (in /home/user/run/bin/worldserver)
==20421==    by 0x83A518: InstanceSaveManager::LoadInstances() (in /home/user/run/bin/worldserver)
==20421==    by 0xA30B6F: World::SetInitialWorldSettings() (in /home/user/run/bin/worldserver)
==20421==    by 0x434430: Master::Run() (in /home/user/run/bin/worldserver)
==20421==    by 0x425B2E: main (in /home/user/run/bin/worldserver)
==20421== 
==20421== Invalid read of size 4
==20421==    at 0x4E247CB: __pthread_mutex_unlock_usercnt (pthread_mutex_unlock.c:55)
==20421==    by 0x4E247CB: pthread_mutex_unlock (pthread_mutex_unlock.c:357)
==20421==    by 0x83A404: InstanceSave::RemovePlayer(unsigned int, InstanceSaveManager*) (in /home/user/run/bin/worldserver)
==20421==    by 0x5B4D42: Player::ResetInstances(unsigned long, unsigned char, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x7BDF2D: Group::Disband(bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x7BD295: Group::RemoveMember(unsigned long, RemoveMethod const&, unsigned long, char const*) (in /home/user/run/bin/worldserver)
==20421==    by 0x555353: Player::RemoveFromGroup(Group*, unsigned long, RemoveMethod, unsigned long, char const*) (in /home/user/run/bin/worldserver)
==20421==    by 0x922899: WorldSession::Update(unsigned int, PacketFilter&) (in /home/user/run/bin/worldserver)
==20421==    by 0xA4BDD0: World::UpdateSessions(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0xA498AC: World::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x44AF20: WorldRunnable::run() (in /home/user/run/bin/worldserver)
==20421==    by 0x560CD83: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==20421==    by 0x4E20608: start_thread (pthread_create.c:477)
==20421==  Address 0x11a7dfbc is 108 bytes inside a block of size 136 free'd
==20421==    at 0x483CFBF: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==20421==    by 0x83A04B: InstanceSaveManager::DeleteInstanceSaveIfNeeded(InstanceSave*, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x83A3F0: InstanceSave::RemovePlayer(unsigned int, InstanceSaveManager*) (in /home/user/run/bin/worldserver)
==20421==    by 0x5B4D42: Player::ResetInstances(unsigned long, unsigned char, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x7BDF2D: Group::Disband(bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x7BD295: Group::RemoveMember(unsigned long, RemoveMethod const&, unsigned long, char const*) (in /home/user/run/bin/worldserver)
==20421==    by 0x555353: Player::RemoveFromGroup(Group*, unsigned long, RemoveMethod, unsigned long, char const*) (in /home/user/run/bin/worldserver)
==20421==    by 0x922899: WorldSession::Update(unsigned int, PacketFilter&) (in /home/user/run/bin/worldserver)
==20421==    by 0xA4BDD0: World::UpdateSessions(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0xA498AC: World::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x44AF20: WorldRunnable::run() (in /home/user/run/bin/worldserver)
==20421==    by 0x560CD83: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==20421==  Block was alloc'd at
==20421==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==20421==    by 0x839604: InstanceSaveManager::AddInstanceSave(unsigned int, unsigned int, Difficulty, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x83B628: InstanceSaveManager::LoadInstanceSaves() (in /home/user/run/bin/worldserver)
==20421==    by 0x83A518: InstanceSaveManager::LoadInstances() (in /home/user/run/bin/worldserver)
==20421==    by 0xA30B6F: World::SetInitialWorldSettings() (in /home/user/run/bin/worldserver)
==20421==    by 0x434430: Master::Run() (in /home/user/run/bin/worldserver)
==20421==    by 0x425B2E: main (in /home/user/run/bin/worldserver)
==20421== 
==20421== Invalid write of size 4
==20421==    at 0x4E247D1: __pthread_mutex_unlock_usercnt (pthread_mutex_unlock.c:52)
==20421==    by 0x4E247D1: pthread_mutex_unlock (pthread_mutex_unlock.c:357)
==20421==    by 0x83A404: InstanceSave::RemovePlayer(unsigned int, InstanceSaveManager*) (in /home/user/run/bin/worldserver)
==20421==    by 0x5B4D42: Player::ResetInstances(unsigned long, unsigned char, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x7BDF2D: Group::Disband(bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x7BD295: Group::RemoveMember(unsigned long, RemoveMethod const&, unsigned long, char const*) (in /home/user/run/bin/worldserver)
==20421==    by 0x555353: Player::RemoveFromGroup(Group*, unsigned long, RemoveMethod, unsigned long, char const*) (in /home/user/run/bin/worldserver)
==20421==    by 0x922899: WorldSession::Update(unsigned int, PacketFilter&) (in /home/user/run/bin/worldserver)
==20421==    by 0xA4BDD0: World::UpdateSessions(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0xA498AC: World::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x44AF20: WorldRunnable::run() (in /home/user/run/bin/worldserver)
==20421==    by 0x560CD83: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==20421==    by 0x4E20608: start_thread (pthread_create.c:477)
==20421==  Address 0x11a7dfb8 is 104 bytes inside a block of size 136 free'd
==20421==    at 0x483CFBF: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==20421==    by 0x83A04B: InstanceSaveManager::DeleteInstanceSaveIfNeeded(InstanceSave*, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x83A3F0: InstanceSave::RemovePlayer(unsigned int, InstanceSaveManager*) (in /home/user/run/bin/worldserver)
==20421==    by 0x5B4D42: Player::ResetInstances(unsigned long, unsigned char, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x7BDF2D: Group::Disband(bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x7BD295: Group::RemoveMember(unsigned long, RemoveMethod const&, unsigned long, char const*) (in /home/user/run/bin/worldserver)
==20421==    by 0x555353: Player::RemoveFromGroup(Group*, unsigned long, RemoveMethod, unsigned long, char const*) (in /home/user/run/bin/worldserver)
==20421==    by 0x922899: WorldSession::Update(unsigned int, PacketFilter&) (in /home/user/run/bin/worldserver)
==20421==    by 0xA4BDD0: World::UpdateSessions(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0xA498AC: World::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x44AF20: WorldRunnable::run() (in /home/user/run/bin/worldserver)
==20421==    by 0x560CD83: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==20421==  Block was alloc'd at
==20421==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==20421==    by 0x839604: InstanceSaveManager::AddInstanceSave(unsigned int, unsigned int, Difficulty, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x83B628: InstanceSaveManager::LoadInstanceSaves() (in /home/user/run/bin/worldserver)
==20421==    by 0x83A518: InstanceSaveManager::LoadInstances() (in /home/user/run/bin/worldserver)
==20421==    by 0xA30B6F: World::SetInitialWorldSettings() (in /home/user/run/bin/worldserver)
==20421==    by 0x434430: Master::Run() (in /home/user/run/bin/worldserver)
==20421==    by 0x425B2E: main (in /home/user/run/bin/worldserver)
==20421== 
==20421== Invalid read of size 4
==20421==    at 0x4E247D8: __pthread_mutex_unlock_usercnt (pthread_mutex_unlock.c:58)
==20421==    by 0x4E247D8: pthread_mutex_unlock (pthread_mutex_unlock.c:357)
==20421==    by 0x83A404: InstanceSave::RemovePlayer(unsigned int, InstanceSaveManager*) (in /home/user/run/bin/worldserver)
==20421==    by 0x5B4D42: Player::ResetInstances(unsigned long, unsigned char, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x7BDF2D: Group::Disband(bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x7BD295: Group::RemoveMember(unsigned long, RemoveMethod const&, unsigned long, char const*) (in /home/user/run/bin/worldserver)
==20421==    by 0x555353: Player::RemoveFromGroup(Group*, unsigned long, RemoveMethod, unsigned long, char const*) (in /home/user/run/bin/worldserver)
==20421==    by 0x922899: WorldSession::Update(unsigned int, PacketFilter&) (in /home/user/run/bin/worldserver)
==20421==    by 0xA4BDD0: World::UpdateSessions(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0xA498AC: World::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x44AF20: WorldRunnable::run() (in /home/user/run/bin/worldserver)
==20421==    by 0x560CD83: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==20421==    by 0x4E20608: start_thread (pthread_create.c:477)
==20421==  Address 0x11a7dfc0 is 112 bytes inside a block of size 136 free'd
==20421==    at 0x483CFBF: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==20421==    by 0x83A04B: InstanceSaveManager::DeleteInstanceSaveIfNeeded(InstanceSave*, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x83A3F0: InstanceSave::RemovePlayer(unsigned int, InstanceSaveManager*) (in /home/user/run/bin/worldserver)
==20421==    by 0x5B4D42: Player::ResetInstances(unsigned long, unsigned char, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x7BDF2D: Group::Disband(bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x7BD295: Group::RemoveMember(unsigned long, RemoveMethod const&, unsigned long, char const*) (in /home/user/run/bin/worldserver)
==20421==    by 0x555353: Player::RemoveFromGroup(Group*, unsigned long, RemoveMethod, unsigned long, char const*) (in /home/user/run/bin/worldserver)
==20421==    by 0x922899: WorldSession::Update(unsigned int, PacketFilter&) (in /home/user/run/bin/worldserver)
==20421==    by 0xA4BDD0: World::UpdateSessions(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0xA498AC: World::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x44AF20: WorldRunnable::run() (in /home/user/run/bin/worldserver)
==20421==    by 0x560CD83: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==20421==  Block was alloc'd at
==20421==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==20421==    by 0x839604: InstanceSaveManager::AddInstanceSave(unsigned int, unsigned int, Difficulty, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x83B628: InstanceSaveManager::LoadInstanceSaves() (in /home/user/run/bin/worldserver)
==20421==    by 0x83A518: InstanceSaveManager::LoadInstances() (in /home/user/run/bin/worldserver)
==20421==    by 0xA30B6F: World::SetInitialWorldSettings() (in /home/user/run/bin/worldserver)
==20421==    by 0x434430: Master::Run() (in /home/user/run/bin/worldserver)
==20421==    by 0x425B2E: main (in /home/user/run/bin/worldserver)
==20421== 
==20421== Invalid read of size 4
==20421==    at 0x4E247DB: __pthread_mutex_unlock_usercnt (pthread_mutex_unlock.c:58)
==20421==    by 0x4E247DB: pthread_mutex_unlock (pthread_mutex_unlock.c:357)
==20421==    by 0x83A404: InstanceSave::RemovePlayer(unsigned int, InstanceSaveManager*) (in /home/user/run/bin/worldserver)
==20421==    by 0x5B4D42: Player::ResetInstances(unsigned long, unsigned char, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x7BDF2D: Group::Disband(bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x7BD295: Group::RemoveMember(unsigned long, RemoveMethod const&, unsigned long, char const*) (in /home/user/run/bin/worldserver)
==20421==    by 0x555353: Player::RemoveFromGroup(Group*, unsigned long, RemoveMethod, unsigned long, char const*) (in /home/user/run/bin/worldserver)
==20421==    by 0x922899: WorldSession::Update(unsigned int, PacketFilter&) (in /home/user/run/bin/worldserver)
==20421==    by 0xA4BDD0: World::UpdateSessions(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0xA498AC: World::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x44AF20: WorldRunnable::run() (in /home/user/run/bin/worldserver)
==20421==    by 0x560CD83: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==20421==    by 0x4E20608: start_thread (pthread_create.c:477)
==20421==  Address 0x11a7dfb0 is 96 bytes inside a block of size 136 free'd
==20421==    at 0x483CFBF: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==20421==    by 0x83A04B: InstanceSaveManager::DeleteInstanceSaveIfNeeded(InstanceSave*, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x83A3F0: InstanceSave::RemovePlayer(unsigned int, InstanceSaveManager*) (in /home/user/run/bin/worldserver)
==20421==    by 0x5B4D42: Player::ResetInstances(unsigned long, unsigned char, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x7BDF2D: Group::Disband(bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x7BD295: Group::RemoveMember(unsigned long, RemoveMethod const&, unsigned long, char const*) (in /home/user/run/bin/worldserver)
==20421==    by 0x555353: Player::RemoveFromGroup(Group*, unsigned long, RemoveMethod, unsigned long, char const*) (in /home/user/run/bin/worldserver)
==20421==    by 0x922899: WorldSession::Update(unsigned int, PacketFilter&) (in /home/user/run/bin/worldserver)
==20421==    by 0xA4BDD0: World::UpdateSessions(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0xA498AC: World::Update(unsigned int) (in /home/user/run/bin/worldserver)
==20421==    by 0x44AF20: WorldRunnable::run() (in /home/user/run/bin/worldserver)
==20421==    by 0x560CD83: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==20421==  Block was alloc'd at
==20421==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==20421==    by 0x839604: InstanceSaveManager::AddInstanceSave(unsigned int, unsigned int, Difficulty, bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x83B628: InstanceSaveManager::LoadInstanceSaves() (in /home/user/run/bin/worldserver)
==20421==    by 0x83A518: InstanceSaveManager::LoadInstances() (in /home/user/run/bin/worldserver)
==20421==    by 0xA30B6F: World::SetInitialWorldSettings() (in /home/user/run/bin/worldserver)
==20421==    by 0x434430: Master::Run() (in /home/user/run/bin/worldserver)
==20421==    by 0x425B2E: main (in /home/user/run/bin/worldserver)
==20421== 
==20421== Thread 1:
==20421== Conditional jump or move depends on uninitialised value(s)
==20421==    at 0x1171CF2: acore::Thread::~Thread() (in /home/user/run/bin/worldserver)
==20421==    by 0x4353A6: Master::Run() (in /home/user/run/bin/worldserver)
==20421==    by 0x425B2E: main (in /home/user/run/bin/worldserver)
==20421== 
==20421== Conditional jump or move depends on uninitialised value(s)
==20421==    at 0x1171CF2: acore::Thread::~Thread() (in /home/user/run/bin/worldserver)
==20421==    by 0x4353DD: Master::Run() (in /home/user/run/bin/worldserver)
==20421==    by 0x425B2E: main (in /home/user/run/bin/worldserver)
==20421== 
==20421== Conditional jump or move depends on uninitialised value(s)
==20421==    at 0x1171CF2: acore::Thread::~Thread() (in /home/user/run/bin/worldserver)
==20421==    by 0x4353EA: Master::Run() (in /home/user/run/bin/worldserver)
==20421==    by 0x425B2E: main (in /home/user/run/bin/worldserver)
==20421== 
==20421== Conditional jump or move depends on uninitialised value(s)
==20421==    at 0x1171CF2: acore::Thread::~Thread() (in /home/user/run/bin/worldserver)
==20421==    by 0x4353F7: Master::Run() (in /home/user/run/bin/worldserver)
==20421==    by 0x425B2E: main (in /home/user/run/bin/worldserver)
==20421== 
==20421== 
==20421== Process terminating with default action of signal 6 (SIGABRT)
==20421==    at 0x58C918B: raise (raise.c:51)
==20421==    by 0x58A8858: abort (abort.c:79)
==20421==    by 0x55D4950: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==20421==    by 0x55E047B: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==20421==    by 0x55E04E6: std::terminate() (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==20421==    by 0x42670A: __clang_call_terminate (in /home/user/run/bin/worldserver)
==20421== 
==20421== HEAP SUMMARY:
==20421==     in use at exit: 1,968,511,281 bytes in 5,678,718 blocks
==20421==   total heap usage: 372,763,879 allocs, 367,085,161 frees, 112,728,062,554 bytes allocated
==20421== 
==20421== 4 bytes in 1 blocks are possibly lost in loss record 50 of 3,822
==20421==    at 0x483C0F3: operator new(unsigned long, std::nothrow_t const&) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==20421==    by 0x4993640: ??? (in /usr/lib/libACE-6.4.5.so)
==20421==    by 0x4993DFF: ??? (in /usr/lib/libACE-6.4.5.so)
==20421==    by 0x49B4B6C: ACE_Dev_Poll_Reactor::open(unsigned long, bool, ACE_Sig_Handler*, ACE_Abstract_Timer_Queue<ACE_Event_Handler*>*, int, ACE_Reactor_Notify*) (in /usr/lib/libACE-6.4.5.so)
==20421==    by 0x49B4DA5: ACE_Dev_Poll_Reactor::ACE_Dev_Poll_Reactor(ACE_Sig_Handler*, ACE_Abstract_Timer_Queue<ACE_Event_Handler*>*, int, ACE_Reactor_Notify*, int, int) (in /usr/lib/libACE-6.4.5.so)
==20421==    by 0x44087D: RARunnable::RARunnable() (in /home/user/run/bin/worldserver)
==20421==    by 0x4346A4: Master::Run() (in /home/user/run/bin/worldserver)
==20421==    by 0x425B2E: main (in /home/user/run/bin/worldserver)
==20421== 
==20421== 8 bytes in 1 blocks are possibly lost in loss record 72 of 3,822
==20421==    at 0x483C0F3: operator new(unsigned long, std::nothrow_t const&) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==20421==    by 0x49B4B90: ACE_Dev_Poll_Reactor::open(unsigned long, bool, ACE_Sig_Handler*, ACE_Abstract_Timer_Queue<ACE_Event_Handler*>*, int, ACE_Reactor_Notify*) (in /usr/lib/libACE-6.4.5.so)
==20421==    by 0x49B4DA5: ACE_Dev_Poll_Reactor::ACE_Dev_Poll_Reactor(ACE_Sig_Handler*, ACE_Abstract_Timer_Queue<ACE_Event_Handler*>*, int, ACE_Reactor_Notify*, int, int) (in /usr/lib/libACE-6.4.5.so)
==20421==    by 0x44087D: RARunnable::RARunnable() (in /home/user/run/bin/worldserver)
==20421==    by 0x4346A4: Master::Run() (in /home/user/run/bin/worldserver)
==20421==    by 0x425B2E: main (in /home/user/run/bin/worldserver)
==20421== 
==20421== 9 bytes in 1 blocks are possibly lost in loss record 74 of 3,822
==20421==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==20421==    by 0x515E3D: Object::Object() (in /home/user/run/bin/worldserver)
==20421==    by 0xB76F88: Item::Item() (in /home/user/run/bin/worldserver)
==20421==    by 0xADCCF4: AuctionHouseMgr::LoadAuctionItems() (in /home/user/run/bin/worldserver)
==20421==    by 0xA354FF: World::SetInitialWorldSettings() (in /home/user/run/bin/worldserver)
==20421==    by 0x434430: Master::Run() (in /home/user/run/bin/worldserver)
==20421==    by 0x425B2E: main (in /home/user/run/bin/worldserver)
==20421== 
==20421== 9 bytes in 1 blocks are possibly lost in loss record 75 of 3,822
==20421==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==20421==    by 0x515E3D: Object::Object() (in /home/user/run/bin/worldserver)
==20421==    by 0x51D1DC: WorldObject::WorldObject(bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x5FF168: Unit::Unit(bool) (in /home/user/run/bin/worldserver)
==20421==    by 0x4EA1B2: Creature::Creature(bool) (in /home/user/run/bin/worldserver)
==20421==    by 0xAE7AE9: Battlefield::SpawnCreature(unsigned int, float, float, float, float, TeamId) (in /home/user/run/bin/worldserver)
==20421==    by 0xAEF316: BattlefieldWG::SetupBattlefield() (in /home/user/run/bin/worldserver)
==20421==    by 0xAED0CE: BattlefieldMgr::InitBattlefield() (in /home/user/run/bin/worldserver)
==20421==    by 0xA38203: World::SetInitialWorldSettings() (in /home/user/run/bin/worldserver)
==20421==    by 0x434430: Master::Run() (in /home/user/run/bin/worldserver)
==20421==    by 0x425B2E: main (in /home/user/run/bin/worldserver)
==20421== 
==20421== 9 bytes in 1 blocks are possibly lost in loss record 76 of 3,822
==20421==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==20421==  ... (2 MB left)
valgrind.log
2 MB
```

<bountysource-plugin>

---
There is a **[$25 open bounty](https://www.bountysource.com/issues/98171506-placeholder-fix-possible-memleaks?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
Fixed #5535
Fixed #5544

## Issues Addressed:
- Closes #5535 and #5544

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Footman** [comment]
hey @UltraNix  is it possible to contact you regarding this somewhere? i would like to go deeper into this.

**Comment by mpfans** [comment]
Compilation error

`[ 99%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-anticheat-master/src/cs_anticheat.cpp.o
[ 99%] Linking CXX static library libscripts.a
[ 99%] Built target scripts
Scanning dependencies of target worldserver
[ 99%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/cmake_pch.hxx.pch
[ 99%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/RemoteAccess/RASocket.cpp.o
[ 99%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/CommandLine/CliRunnable.cpp.o
[ 99%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/ACSoap/ACSoap.cpp.o
[ 99%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/RemoteAccess/RARunnable.cpp.o
[ 99%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/Main.cpp.o
[ 99%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/Master.cpp.o
[ 99%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/WorldThread/WorldRunnable.cpp.o
[100%] Linking CXX executable worldserver
/usr/bin/ld: ../game/libgame.a(MotionMaster.cpp.o):(.rodata._ZTV23FollowMovementGeneratorI8CreatureE[_ZTV23FollowMovementGeneratorI8CreatureE]+0x10): undefined reference to `FollowMovementGenerator<Creature>::~FollowMovementGenerator()'
/usr/bin/ld: ../game/libgame.a(MotionMaster.cpp.o):(.rodata._ZTV23FollowMovementGeneratorI8CreatureE[_ZTV23FollowMovementGeneratorI8CreatureE]+0x18): undefined reference to `FollowMovementGenerator<Creature>::~FollowMovementGenerator()'
/usr/bin/ld: ../game/libgame.a(MotionMaster.cpp.o):(.rodata._ZTV22ChaseMovementGeneratorI6PlayerE[_ZTV22ChaseMovementGeneratorI6PlayerE]+0x10): undefined reference to `ChaseMovementGenerator<Player>::~ChaseMovementGenerator()'
/usr/bin/ld: ../game/libgame.a(MotionMaster.cpp.o):(.rodata._ZTV22ChaseMovementGeneratorI6PlayerE[_ZTV22ChaseMovementGeneratorI6PlayerE]+0x18): undefined reference to `ChaseMovementGenerator<Player>::~ChaseMovementGenerator()'
/usr/bin/ld: ../game/libgame.a(MotionMaster.cpp.o):(.rodata._ZTV22ChaseMovementGeneratorI8CreatureE[_ZTV22ChaseMovementGeneratorI8CreatureE]+0x10): undefined reference to `ChaseMovementGenerator<Creature>::~ChaseMovementGenerator()'
/usr/bin/ld: ../game/libgame.a(MotionMaster.cpp.o):(.rodata._ZTV22ChaseMovementGeneratorI8CreatureE[_ZTV22ChaseMovementGeneratorI8CreatureE]+0x18): undefined reference to `ChaseMovementGenerator<Creature>::~ChaseMovementGenerator()'
/usr/bin/ld: ../game/libgame.a(MotionMaster.cpp.o):(.rodata._ZTV23FollowMovementGeneratorI6PlayerE[_ZTV23FollowMovementGeneratorI6PlayerE]+0x10): undefined reference to `FollowMovementGenerator<Player>::~FollowMovementGenerator()'
/usr/bin/ld: ../game/libgame.a(MotionMaster.cpp.o):(.rodata._ZTV23FollowMovementGeneratorI6PlayerE[_ZTV23FollowMovementGeneratorI6PlayerE]+0x18): undefined reference to `FollowMovementGenerator<Player>::~FollowMovementGenerator()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/build.make:223: src/server/worldserver/worldserver] Error 1
make[1]: *** [CMakeFiles/Makefile2:1054: src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`

**Comment by UltraNix** [comment]
@Footman Discord.
@mpfans Let me fix it.

File: src/server/game/Entities/Unit/Unit.cpp [hunk 1]
```diff
@@ -2310,17 +2310,19 @@ Position* Unit::GetMeleeAttackPoint(Unit* attacker)
...
 
-        if (!GetMap()->CanReachPositionAndGetValidCoords(this, x, y, z, true, true))
+        if (!GetMap()->CanReachPositionAndGetValidCoords(this, pos->m_positionX, pos->m_positionY, pos->m_positionZ, true, true))
         {
             return nullptr;
         }
     }
 
-    return new Position(x,y,z);
+    return pos.get();
```
Comment (FrancescoBorzi) [inline src/server/game/Entities/Unit/Unit.cpp:2325]:
```
fatal error: address of stack memory associated with local variable 'pos' returned
```

Comment (UltraNix) [reply src/server/game/Entities/Unit/Unit.cpp]: Fixed.

**Comment by mpfans** [comment]
image
tested 7.5 hours ...  There is no memory leak

**Comment by Kitzunu** [comment]
Good job
