### PR TITLE
Death Knight Bone shield charges now have a 2 second delay between uses.

### LINKED ISSUE #22289: [Death Knight] Bone shield charges have no ICD for being used
### Triage

Original CC issue: https://github.com/chromiecraft/chromiecraft/issues/8078

Here, you can see the DK having Bone Shield on them and rogue hitting them frequently, and the stacks are not lost instantly: https://youtu.be/rWfKNiF5efM?t=39

### Current Behaviour

the Death Knight's bone shield charges are lost as frequently as they get hit

### Expected Blizzlike Behaviour

Bone shield charges should have an ICD of 2 seconds before another charge can be lost

### Source

https://www.wowhead.com/wotlk/spell=49222/bone-shield#comments

Image

### Steps to reproduce the problem

Make a Death Knight
Learn the talent bone shield
Pull multiple enemies
Use bone shield
Watch how fast the charges are lost

### Extra Notes

Haven't been able to find if the ICD should be applied when casting the spell to losing the first charge. Since it's not really mentioned it probably isn't

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6de87af4d25c90679971153f8c6bff201dadffe9

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by LuckyLuc96**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #22289

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

https://www.wowhead.com/wotlk/spell=49222/bone-shield#comments

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Have a deathknight that knows bone shield (can use .learn all my class to quickly gain this talent)
2. Get in combat with 3 to 5 mobs so that you are being hit frequently. 
3. Notice that charges now last at least 2 seconds instead of being lost instantly. 

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: src/server/scripts/Spells/spell_dk.cpp [hunk 1]
```diff
@@ -530,11 +530,20 @@ class spell_dk_bone_shield : public AuraScript
 {
     PrepareAuraScript(spell_dk_bone_shield);
 
+    uint32 lastChargeUsedTime = 0;
+    const uint32 ICD_MS = 2000;
+
     void HandleProc(ProcEventInfo& eventInfo)
     {
         PreventDefaultAction();
+        uint32 currentTime = getMSTime();
```
Comment (Tereneckla) [inline src/server/scripts/Spells/spell_dk.cpp:538]: You should use unit->AddSpellCooldown and HasSpellCooldown instead (unsure about which ID to use)

Comment (LuckyLuc96) [reply src/server/scripts/Spells/spell_dk.cpp:538]: > You should use AddSpellCooldown and HasSpellCooldown instead (unsure about which ID to use)

Do charges of a spell count as spells themselves? I was not sure if a function like this would work for this case.

Comment (Tereneckla) [reply src/server/scripts/Spells/spell_dk.cpp:538]: Yes, spell cooldowns can be used for changing stacks.

It would require a serverside spell to be created as the cooldown of 49222 is used.
49221 is free so my guess is that that is blizzards server side spell
That is out of my area of expertise though

Comment (LuckyLuc96) [reply src/server/scripts/Spells/spell_dk.cpp:538]: Server side spell created and utilized to track bone shield charges now

**Comment by LuckyLuc96** [comment]
Please note that the new sql changes adds to the spell_dbc table, but it leaves several values as "Null."

I am not sure if this is problematic or if I need to restructure the script to fill these values in. I don't like it simply because it's ugly.


Screenshot from 2025-06-20 20-49-58

Screenshot from 2025-06-20 20-50-07

I think I'll fill in all these values with 0s or empty strings where relevant

**Comment by LuckyLuc96** [comment]
Current implementation 

https://github.com/user-attachments/assets/19fd55e6-8891-424d-873d-de77a6d7aa20

**Comment by Nyeriah** [comment]
I'm a bit uneasy about this one. We don't have the freedom to create spells at will and I wouldn't say a gap in the spell ids is enough evidence that there is a spell for this purpose

**Comment by LuckyLuc96** [comment]
> I'm a bit uneasy about this one. We don't have the freedom to create spells at will and I wouldn't say a gap in the spell ids is enough evidence that there is a spell for this purpose

I had another version that used more traditional logic rather than making a tool inside the server. Would this version pass the sniff test? The ingame affect was the same.

https://github.com/azerothcore/azerothcore-wotlk/pull/22340/commits/e699b10d152d7a1a54691eb5017a32b73b5ec09e

**Comment by heyitsbench** [comment]
Revert the serverside spell change. There is no evidence for its existence, certainly nothing in a 3.4.3 51943 sniff I've checked.

**Comment by LuckyLuc96** [comment]
Restored to initial version. I'm gonna compile and try my hardest to break it.

File: data/sql/updates/pending_db_world/rev_1750460435239275931.sql [hunk 2]
```diff
@@ -0,0 +1,3 @@
+-- Adds a spell into server to track internal cooldown of DK's Bone Shield charges
+DELETE from `spell_dbc` WHERE `id` = 49221;
+INSERT INTO `spell_dbc` SET `id` = 49221, `Attributes` = 0x100, `DurationIndex` = 21, `Name_Lang_enUS` = 'Bone Shield ICD', `SchoolMask` = 1;
```
Comment (heyitsbench) [inline data/sql/updates/pending_db_world/rev_1750460435239275931.sql]: This file needs to be removed as well.

Comment (LuckyLuc96) [reply data/sql/updates/pending_db_world/rev_1750460435239275931.sql]: Ty! I forgot deleting is not the same as git rm

File: src/server/scripts/Spells/spell_dk.cpp [hunk 3]
```diff
@@ -530,11 +530,22 @@ class spell_dk_bone_shield : public AuraScript
 {
     PrepareAuraScript(spell_dk_bone_shield);
 
+    uint32 lastChargeUsedTime = 0;
+    const uint32 ICD_MS = 2000;
```
Comment (heyitsbench) [inline src/server/scripts/Spells/spell_dk.cpp]: To be honest, I don't know that this variable should be used. Other places (like L498) just use a raw uint value for cooldown stuff, plus you have a comment in the one place it's used anyway. Also, if it is to be kept, its name doesn't fit the lowerCamelCase convention.

Comment (LuckyLuc96) [reply src/server/scripts/Spells/spell_dk.cpp]: That's fair. I'll remove the variable and leave the comment. I just had my own style to always capitalize constants and another being to never use "magic" numbers. But the comment will alleviate that
