### PR TITLE
fix(Scripts/Ulduar): Flame Leviathan first time engage

### LINKED ISSUE #10808: [Ulduar] Flame Leviathan - Incorrect first time engage action sequence
### Current Behaviour

Bugged move forward (goes underground)
Gate breaking is mistimed
Engages in combat too fast

https://user-images.githubusercontent.com/46330494/155524696-d251f442-1c42-4625-976e-2f471fe94cf8.mp4

### Expected Blizzlike Behaviour

Gate breaking should be the exact moment he "charges"
Should engage combat, roughly 2 seconds after the gate has been broken

My local (will do PR later)

https://user-images.githubusercontent.com/46330494/155524988-0fc40998-3d6d-4ded-8fa0-33280301a8df.mp4

### Source

https://www.youtube.com/watch?v=00p_Ni58YGE

### Steps to reproduce the problem

1. .go c 137039 (Steelforged Defender, in front of FL gate)
2. .npc add 33060 (Salvaged Siege Engine)
3. Kill the 2 Ulduar Colossus (While inside the Siege Engine, can .die them)

### Extra Notes

_No response_

### AC rev. hash/commit

3e6424151af4

### Operating system

Windows 10 

### Custom changes or Modules

None

### PR DESCRIPTION
**Pull request by avarishd**
Please, let me know if this is the correct way to do a script PR, thanks!

## Changes Proposed:
-  Fix timing on gate breaking, combat engage and underground pathing.

## Issues Addressed:

- Closes #10808 

## SOURCE:

https://www.youtube.com/watch?v=00p_Ni58YGE (Also in the #10808 issue)

## Tests Performed:

- Tested in-game

https://user-images.githubusercontent.com/46330494/155529534-7b83db6c-8b31-4f18-8d1e-48b738222fd0.mp4

## How to Test the Changes:

1. .go c 137039 (Steelforged Defender, in front of FL gate)
2. .npc add 33060 (Salvaged Siege Engine)
3. Kill the 2 Ulduar Colossus (While inside the Siege Engine, can .die them)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by IntelligentQuantum** [comment]
@Nefertumm Review Please

File: src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp [hunk 1]
```diff
@@ -368,11 +367,12 @@ class boss_flame_leviathan : public CreatureScript
                 else if (_speakTimer > 41000 && _speakTimer < 60000)
                 {
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
-                    me->SendMonsterMove(380.4f, -14.3f, 409.8f, 2000);
-                    me->UpdatePosition(380.4f, -14.3f, 409.8f, me->GetOrientation());
+                    TurnGates(true, false);
+                    me->MonsterMoveWithSpeed(322.39f, -14.5f, 409.8f, 100.0f);
+                    me->UpdatePosition(322.39f, -14.5f, 409.8f, me->GetOrientation());
```
Comment (Nefertumm) [inline src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp:372]: Move the magic numbers to a proper position variable, please.

Comment (avarishd) [reply src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp]: done.
