### PR TITLE
fix(DB/creature): Howling Fjord Rope Swing Invisible Vehicle Stalker visibility

### LINKED ISSUE #24001: [Howling Fjord] Whisper Gulch bunnies visible
### Triage

Issue linked from CC:  https://github.com/chromiecraft/chromiecraft/issues/8638

Triage Notes: 

.go xyz 1634 -3265 72 571 3

That puts you in front of one. The other side of the gorge you can see another.

I haven't found more, but that's not to say there aren't more

Image

Original Post Below: 

---

### Current Behaviour

In several places in Whisper Gulch there are infernals walking around. You can't target them, they don't do anything.

### Expected Blizzlike Behaviour

I am 99% sure they shouldn't be there.

### Source

No mention of infernals in whisper gulch on youtube, and I do not see them in a youtube video I found of a guy questing there:
https://youtu.be/IY4ioRn5Yew?si=UbeGAf6vynpcvxAk&t=124

### Steps to reproduce the problem

1. Go to Whisper Gulch
2. Go around a bit, they walk around in several places.

### Extra Notes

_No response_

### Customizations

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c552158e9916f962a647e41b5f9e66efee538803

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-chromiecraft-smartstone](https://github.com/chromiecraft/mod-chromiecraft-smartstone)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-evade-logging](https://github.com/heyitsbench/mod-evade-logging)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-quests](https://github.com/azerothcore/mod-pvp-quests)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by zackchadwick**
## Changes Proposed:

The Rope Swing Invisible Vehicle Stalker creature/prop/trigger is visible to regular players. 

It appears that this is caused by:

1. The creature template is missing the `128` value for the `flags_extra` field in the database. This appears to be set for similar creature templates such as the `Whisper Gulch Ore Bunnies` that the linked issue originally indicated was the cause of the visible infernals.
2. The secondary model for the Rope Swing Invisible Vehicle Stalker in the `creature_template_model` table differs from the infernal model used for other invisible creatures. While it is an infernal model it is not a non-trigger infernal model, which appears to cause an issue with proper visibility both with `.gm on` and `.gm off`. Updating this secondary infernal to `17612` to match the other invisible creatures in the area solves it.

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [X] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #24001 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [X] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

1. Teleport to creature location, `.go xyz 1634 -3265 72 571 3`
3. Observe they are no longer visible as infernals with `.gm off`
4. Observe they are visible as infernals with `.gm on` the same way that other helper creatures/triggers are

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by TheSCREWEDSoftware** [comment]
Just use the UPDATE to update the Field you wish to update, and for hte models, you need sniffs to validate this.

https://www.azerothcore.org/wiki/sql-standards

**Comment by zackchadwick** [comment]
> Just use the UPDATE to update the Field you wish to update, and for hte models, you need sniffs to validate this.
> 
> https://www.azerothcore.org/wiki/sql-standards

Sorry about that, I think I must have misinterpreted some comments on other PRs I looked at while simultaneously missing the SQL standards page. I think this should follow the project standards now for the SQL.

As far as the sniff goes-- I won't be able to perform that so I'm not sure if this should just stay open until someone helping out has the time and desire to submit for this or if it should just be closed.

**Comment by TheSCREWEDSoftware** [comment]
If you can 't sniff yourself, you will have to wait for someone to validate with it a sniff

File: data/sql/updates/pending_db_world/rev_1765697713697231306.sql [hunk 1]
```diff
@@ -0,0 +1,6 @@
+--
+SET @ENTRY := 24705;
+
+UPDATE `creature_template` SET `flags_extra` = 128 WHERE `entry` = @ENTRY;
```
Comment (TheSCREWEDSoftware) [inline data/sql/updates/pending_db_world/rev_1765697713697231306.sql]:
```suggestion
UPDATE `creature_template` SET `flags_extra` = `flags_extra` | 128 WHERE `entry` = @ENTRY;
```

According to [SQL Standards](https://www.azerothcore.org/wiki/sql-standards) this is the correct way to apply / remkve bitmaks/flags 

Related to the model, until there's someone with a sniff to validate this is or not the correct change

File: data/sql/updates/pending_db_world/rev_1765697713697231306.sql [hunk 2]
```diff
@@ -0,0 +1,6 @@
...
+
+UPDATE `creature_template_model` SET `CreatureDisplayID` = 17612 WHERE `CreatureID` = @ENTRY AND `CreatureDisplayID` = 11686;
```
Comment (heyitsbench) [inline data/sql/updates/pending_db_world/rev_1765697713697231306.sql]:
```suggestion
DELETE FROM `creature_template_model` WHERE `CreatureID` = @ENTRY;
INSERT INTO `creature_template_model` (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`, `VerifiedBuild`) VALUES
(@ENTRY, 0, 1126, 1, 0, 51831),
(@ENTRY, 1, 11686, 1, 1, 51831);
```
