### PR TITLE
fix(Scripts/MagisterTerrace/DB) Vexallus Boss Complete Overhaul

### LINKED ISSUE #21224: [Magister's Terrace] Energy Feedback does not stack from different sources
### Current Behaviour

[Energy Feedback](https://wowgaming.altervista.org/aowow/?spell=44335) does not stack from different sources.

### Expected Blizzlike Behaviour

[Energy Feedback](https://wowgaming.altervista.org/aowow/?spell=44335) should stack from different sources.

### Source

[Wotlk Classic Heroic](https://youtu.be/nKSSYAkpW_s?t=180) Starting from 3:06 , the paladin start killing [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) and each kill will add stack on the same debuff.

[TBC Classic Normal](https://youtu.be/_9wdohQCKRA?t=475) at 7:59 and 8:05 , the warrior kill 2 [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) and each adds stack of [Energy Feedback](https://wowgaming.altervista.org/aowow/?spell=44335) and refresh it.

[TBC Classic Heroic](https://youtu.be/g5oA9_0s8CY?t=798) at 13:21 , the warrior kill [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) and he gets 2nd stack of [Energy Feedback](https://wowgaming.altervista.org/aowow/?spell=44335).

### Steps to reproduce the problem

1. .go c id 24744
2. Deal damage to [Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744) until he start summoning [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) at 85, 70 , 55 and 40% of his health.

### Extra Notes

Killing [Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744) should remove [Energy Feedback](https://wowgaming.altervista.org/aowow/?spell=44335) debuff on the players.

### AC rev. hash/commit

AzerothCore rev. 7725610ff3e6 2025-01-21 10:44:39 +0100 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 11 x64

### Custom changes or Modules

_No response_

### LINKED ISSUE #21228: [Magister's Terrace] Vexallus's Pure energy are not immune to AoE
Bug Triager Notes:

Original CC Report: https://github.com/chromiecraft/chromiecraft/issues/7700#issue-2800538822

Image

Image

### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

The Pure Energy (https://www.wowhead.com/npc=24745/pure-energy) are not immune to AoE (tested with Volley, whirlwind, Hurricane and Starfall).

### Expected Blizzlike Behaviour

The Pure Energy  (https://www.wowhead.com/npc=24745/pure-energy) are supposed to be immune to AoE. You need to manually target them and use single target spells to kill them.

### Source

https://www.wowhead.com/npc=24745/pure-energy#comments -- Multiple comments from back in the day indicating they were immune to AoE
https://youtu.be/B6HMtvWiNCM?t=220

### Steps to reproduce the problem

1. Enter MgT
2. Engage Vexallus
3. Get boss to 85% health to trigger the first Pure Energy Spawn
4. Use AoE to kill them

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/90566589b0349fc31941af6e6ed660d30a0a761e

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### LINKED ISSUE #21258: [Magisters Terrace] Vexallus can skip summoning Pure Energy
### Current Behaviour

After this PR https://github.com/azerothcore/azerothcore-wotlk/pull/21239 , [Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744) started skipping summoning [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) if you reach next threshold while the summoning spell still in cooldown.

### Expected Blizzlike Behaviour

[Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744) should keep count of each threshold he has went through and summon [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) for each threshold with 5 seconds cooldown.

### Source

[Retail Wotlk](https://youtu.be/qXBIe-teMqg?t=97) Starting from 1:37, you can see 5 different spawns for [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745)

[Retail Wotlk](https://youtu.be/vRjgCtDOzo8?t=190) Starting from 3:12 , [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) spawns 5 different times.

[Wotlk Classic](https://youtu.be/DP1ky6f_VJ0) at 0;44 , [Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744) reaches the 25% threshold while still in the 5 seconds cooldown from his previous summons , 3 seconds later he summons [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) that were intended for 25% threshold.

[TBC Classic](https://youtu.be/i3XUDMpyBqM?t=515) at 8:37 , [Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744) summons [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) for reaching 70% threshold , at 8:39 he reaches 55% threshold but wait until 8:42 and summons [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) there were intended for 55% threshold and similar behavior happens with 40% and 25% threshold.

### Steps to reproduce the problem

1. .go c id 24744
2. .damage 21600 (in Normal mode) or .damage 29300 (in Heroic Mode) on [Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744)
3. After [Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744) summons [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745) do another .damage 21600 (29300 in heroic mode) before the 5 seconds cooldown are over.
4. Wait until the cooldown is over > he doesn't summons [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745)

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. a13c2ff55f53 2025-01-23 17:30:31 +0000 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 11 x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by blinkysc**
## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #21258
- Closes #21228
- Closes #21224
- Additionally, Vexallus will now wait for all 5 Pure Energy to spawn before Spell Overload
- Clean up code so that it's more readable

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. .go c id 24744
2. use .damage to get through thresholds
3. use .damage to get under 20% observe pure energy x5 then overload
4. .die to observe proper Reset()

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by blinkysc** [comment]
I see what's going on now with problem with SPELL_OVERLOAD, for some reason UNIT_FLAG_STUNNED is applied to Vex as well... Trying to track that down

**Comment by Nyeriah** [comment]
We can't accept hacks as a viable solution to issues. Please try to figure what is wrong without using hacks.

**Comment by blinkysc** [comment]
> We can't accept hacks as a viable solution to issues. Please try to figure what is wrong without using hacks.

Yeah still trying to track it down, also trying to see why the boss doesn't melee attack as well

**Comment by amed80** [comment]
Looking at this [video](https://youtu.be/i3XUDMpyBqM?t=537) , the boss doesn't auto attack when he is in overload phase.

Also , I am not sure about this but it seems that overload spell can happen only after he reaches <20% but also it looks like it have some other aspect that need to happen first before it start casting , all the Pure energy should have been spawned already (so after the 5 summoning phases?) and it seems to need also 5? seconds after the last spawn before he enter that phase which can probably explain why it's rarely happen in most videos i have seen so far.

I don't know if someone have the ability to test the boss in retail or classic 😅

**Comment by blinkysc** [comment]
> Looking at this [video](https://youtu.be/i3XUDMpyBqM?t=537) , the boss doesn't auto attack when he is in overload phase.
> 
> Also , I am not sure about this but it seems that overload spell can happen only after he reaches <20% but also it looks like it have some other aspect that need to happen first before it start casting , all the Pure energy should have been spawned already (so after the 5 summoning phases?) and it seems to need also 5? seconds after the last spawn before he start using overload which can probably explain why it's rarely happen in most videos i have seen so far.
> 
> I don't know if someone have the ability to test the boss in retail or classic 😅

Guess it makes sense from a "flavor" perspective how the boss works. I can try adding this too.

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 1]
```diff
@@ -49,18 +45,58 @@ enum Misc
     NPC_PURE_ENERGY                 = 24745
 };
 
+struct npc_pure_energy : public ScriptedAI
+{
+    npc_pure_energy(Creature* creature) : ScriptedAI(creature) {}
+
+    void IsSummonedBy(WorldObject* summoner) override
+    {
+         if (Creature* vexallus = dynamic_cast<Creature*>(summoner))
```
Comment (Kitzunu) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:54]:
```cpp
if (!summoner)
    return

if (Creature* vexallus = summoner->ToCreature())

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 2]
```diff
@@ -49,18 +45,58 @@ enum Misc
...
+             }
+         }
+    }
+
+    void DamageTaken(Unit* attacker, uint32& damage, DamageEffectType /*damagetype*/, SpellSchoolMask /*damageSchoolMask*/) override
+    {
+        if (!attacker || !attacker->IsPlayer() || !attacker->GetVictim() || attacker->GetVictim() != me)
+        {
+            damage = 0;
+        }
```
Comment (Kitzunu) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:69]: dont use brackets on one lines

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 3]
```diff
@@ -128,11 +161,40 @@ struct boss_vexallus : public BossAI
...
+        float currentPct = me->GetHealthPct();
+
+        if (!_overloaded && currentPct <= 20.0f && _pureEnergy == 0)
+        {   
+            DoCastSelf(SPELL_OVERLOAD, true);
+            _overloaded = true;
+            me->RemoveUnitFlag(UNIT_FLAG_STUNNED); // This currently is a hack; SPELL_OVERLOAD applies UNIT_FLAG_STUNNED when it shouldn't
+        }
+
+        if (currentPct <= 85.0f && !_thresholdsPassed[0]) { _energyQueue++; _thresholdsPassed[0] = true; }
```
Comment (Kitzunu) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:178]: You can use HealthBelowPct(85)

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 4]
```diff
@@ -128,11 +161,40 @@ struct boss_vexallus : public BossAI
...
+        if (!UpdateVictim())
+            return;
+
+        float currentPct = me->GetHealthPct();
+
+        if (!_overloaded && currentPct <= 20.0f && _pureEnergy == 0)
+        {   
+            DoCastSelf(SPELL_OVERLOAD, true);
+            _overloaded = true;
+            me->RemoveUnitFlag(UNIT_FLAG_STUNNED); // This currently is a hack; SPELL_OVERLOAD applies UNIT_FLAG_STUNNED when it shouldn't
```
Comment (Kitzunu) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:175]: fix the spell in that case

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 5]
```diff
@@ -49,18 +45,58 @@ enum Misc
...
+    npc_pure_energy(Creature* creature) : ScriptedAI(creature) {}
+
+    void IsSummonedBy(WorldObject* summoner) override
+    {
+         if (Creature* vexallus = dynamic_cast<Creature*>(summoner))
+         {
+             if (Unit* target = vexallus->AI()->SelectTarget(SelectTargetMethod::Random, 0))
+             {
+                 AttackStart(target);
+                 me->CastSpell(target, SPELL_ENERGY_FEEDBACK_CHANNEL, false);
```
Comment (Kitzunu) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:59]: it is false by default, no need to specify it

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp (hunk 2 above)
Comment (blinkysc) [reply src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp]: Changed them

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp (hunk 3 above)
Comment (blinkysc) [reply src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp]: I'm dumb lol think I seen this before too...

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp (hunk 4 above)
Comment (blinkysc) [reply src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:169]: Yeah, trying to find it at the moment. Not sure if it's something that's in the DB or something? Don't see in spell fixes or generic

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp (hunk 5 above)
Comment (blinkysc) [reply src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:59]: Fixed

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp (hunk 1 above)
Comment (blinkysc) [reply src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp]: Fixed

**Comment by blinkysc** [comment]
Ok I see, Overload 44352 applies a stun. Guess spell script for boss then
https://www.wowhead.com/wotlk/spell=44352/overload

**Comment by amed80** [comment]
I believe the spell itself is working correctly as the boss shouldn't be doing anything (not casting any other spell or melee attacking = stunned) when he start overload.

**Comment by blinkysc** [comment]
> I believe the spell itself is working correctly as the boss shouldn't be doing anything (not casting any other spell or melee attacking = stunned) when he start overload, it's just when he start using it that is off

Ok cool I'll dumb the spell script then.

**Comment by blinkysc** [comment]
@amed80 Mind giving it a show with this last commit?

**Comment by amed80** [comment]
- Vexallus does not skip summoning Pure Energy ✅ 

- Vexallus wait until all Pure Energy to be summoned before casting Overload ✅  
Atm he start overload almost instantly after the last summoning of Pure Energy but i believe should wait 5 sec 

- Energy Feedback looks like it's stacking but not really , the debuff is adding numbers but it's not refreshing the timer with each stack added , also the effect of the debuff is not stacked , even if it's says deal 3k (10 stacks) per second it's only dealing 300 and the damage increase is still 50% and not 300% and there is no size increase with each stack. ❌ 

<details>

Wow_02%02%01=26-01-2025
image
</details>

**Comment by blinkysc** [comment]
Ok cool I'll take a look at that next then

**Comment by amed80** [comment]
tested with some AOE spells none of them **kill** Pure Energy but they do take damage from AOE spells

<details>

image
Wow_02%57%04=26-01-2025

</details>

**Comment by blinkysc** [comment]
Haha ok I'll see about that dmg... Man this has been really fun so far lmao

**Comment by blinkysc** [comment]
So I think SPELL_ATTR0_CU_SINGLE_AURA_STACK that I added into SpellInfoCorrections is a custom flag so that it stacks but doesn't stack the spell effects in this instance? Also there's the problem of the duration not getting reset. I'm still trying to search but if anyone else happens to know that would be cool. It seems the previous author of Vex likely kept it this way to try and get "some" semblance of how the behavior is though it seems it was pretty far from blizzlike.

Only other reference for the AUTA_STACK is sunder armor but that works as expected?
Screenshot 2025-01-25 at 11 38 21 PM

For the IMMUNE_TO_AOE it might be that is needed as a custom attribute? Though I can't really think of many other use cases other than this fight?

**Comment by amed80** [comment]
For the aoe immunity , there is this in flags_extra
image

for the stacking , i tried something similar to this pr https://github.com/azerothcore/azerothcore-wotlk/pull/20749 but ended up with the same result, idk why it's not stacking normally even though if i use .cast 44335 the stacking work normal 😅

**Comment by blinkysc** [comment]
> For the aoe immunity , there is this in flags_extra image
> 
> for the stacking , i tried something similar to this pr #20749 but ended up with the same result, idk why it's not stacking normally even though if i use .cast 44335 the stacking work normal 😅

Yeah I've tried this but wasn't working for me. Man so confused as to what .cast 44335 works just fine but cast when die makes it wonky

**Comment by blinkysc** [comment]
@amed80 Give this a try

**Comment by amed80** [comment]
Now the stacking working as expect.
Pure Energy still taking damage from AOE but they don't die unless targeted.

The boss for some reason doesn't auto/melee attack at the start after this PR? he should be auto attacking at the start before casting overload.

**Comment by blinkysc** [comment]
> Now the stacking working as expect. Pure Energy still taking damage from AOE but they don't die unless targeted.
> 
> The boss for some reason doesn't auto/melee attack at the start after this PR? he should be auto attacking at the start before casting overload.

Yeah that's why I was confused before, ok let me see what's up. So it attacks but not in overload

**Comment by blinkysc** [comment]
> Now the stacking working as expect. Pure Energy still taking damage from AOE but they don't die unless targeted.
> 
> The boss for some reason doesn't auto/melee attack at the start after this PR? he should be auto attacking at the start before casting overload.

Also it might show damage but it takes 0. Think it doesn't show IMMUNE when AOE so that might be what you expect

**Comment by blinkysc** [comment]
@amed80 give it another go

**Comment by amed80** [comment]
Yup , he auto attack now before overload.

Only left the Pure Energy aoe immunity, i don't know if that is the way to do it (it's still showing in combat log taking damage) or using the flag extra is better? maybe someone else would have better idea about it.

**Comment by blinkysc** [comment]
@amed80 Try again?

**Comment by amed80** [comment]
Pure Energy can auto attack , they should not (were not auto attacking before this PR)

When Vexallus start casting Overload , he should yell and use emote
this is currently missing (i believe it was missing from the start)
opera_21%12%35=26-01-2025

**Comment by blinkysc** [comment]
Fixed the Pure Energy auto attack. Seems the emote is explained by SAY_OVERLOAD not being used in the original script. I tried putting Talk(SAY_OVERLOAD) in the overload sequence but doesn't do anything. 

Looking into SAY_OVERLOAD, though not sure how the yells work atm

**Comment by blinkysc** [comment]
Oh never mind I typo'd it does work... @amed80 One more test ftw

**Comment by amed80** [comment]
Pure Energy still auto attack.

Vexallus does yell "Un...leash" but missing the yellow message under it "Vexallus overloads!"

**Comment by blinkysc** [comment]
@amed80 Good to go. PR Ready for Review

**Comment by amed80** [comment]
image
Pure Energy still use melee attack 😅

I believe everything else is working as expected.

**Comment by blinkysc** [comment]
Ok haha @amed80 Final of the final of the final

**Comment by Nyeriah** [comment]
I think this is being counter productive, please let's wait for a review before asking for further tests. This simply won't work

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 6]
```diff
@@ -15,124 +15,239 @@
...
+    SPELL_SUMMON_PURE_ENERGY_H1     = 46154, // Heroic mode summon 1
+    SPELL_SUMMON_PURE_ENERGY_H2     = 46159  // Heroic mode summon 2
 };
 
-enum Misc
+// Pure energy add AI implementation
+struct npc_pure_energy : public ScriptedAI
 {
-    NPC_PURE_ENERGY                 = 24745
+    explicit npc_pure_energy(Creature* creature) : ScriptedAI(creature) {}
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:49]: why explicit?

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 7]
```diff
@@ -15,124 +15,239 @@
...
+
+    // Initialize on summon
+    void IsSummonedBy(WorldObject* summoner) override
+    {
+        if (Creature* vexallus = summoner ? summoner->ToCreature() : nullptr)
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:54]: No brackets on single line ifs

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 8]
```diff
@@ -15,124 +15,239 @@
...
+        if (killer)
+            killer->CastSpell(killer, SPELL_ENERGY_FEEDBACK, true, nullptr, nullptr, me->GetGUID());
+    }
+
+    // Override to prevent actual melee attacks while still allowing movement
+    void AttackStart(Unit* victim) override 
+    {
+        if (victim)
+        {
+            me->Attack(victim, false); // Set victim but don't allow melee
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:84]: This won't prevent them from auto attacking. Override UpdateAI() instead (auto attacks are called there in DoMeleeAttackIfReady()

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 9]
```diff
@@ -15,124 +15,239 @@
...
 struct boss_vexallus : public BossAI
 {
-    boss_vexallus(Creature* creature) : BossAI(creature, DATA_VEXALLUS), _energyCooldown(false) { }
+    // Configuration constants
+    static constexpr std::array<uint8_t, 5> HEALTH_THRESHOLDS = {85, 70, 55, 40, 25}; // HP % for energy spawns
+    static constexpr Seconds ENERGY_COOLDOWN = 5s;    // Time between energy spawns
+    static constexpr Seconds ABILITY_TIMER = 8s;      // Basic ability cooldown
+    static constexpr uint8_t INITIAL_PURE_ENERGY = 5; // Starting energy count
+
+    explicit boss_vexallus(Creature* creature)
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:99]: Why explicit?

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 10]
```diff
@@ -15,124 +15,239 @@
...
-        ScheduleHealthCheckEvent(20, [&]
-        {
-            scheduler.CancelAll();
-            DoCastSelf(SPELL_OVERLOAD, true);
-        });
+    // Cleanup on death
+    void JustDied(Unit*) override
+    {
+        _JustDied();
+        if (instance)
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:126]: Boss scripts wont execute outside instances, there's no need to check for instance here

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 11]
```diff
@@ -15,124 +15,239 @@
...
-        }, 8s, 8s);
+        }, ABILITY_TIMER, ABILITY_TIMER);
     }
 
-    void JustSummoned(Creature* summon) override
+    // Check for final phase transition
+    void CheckOverload()
     {
-        if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0))
+        if (!_overloaded && _pureEnergy == 0 && !_energyCooldown && HealthBelowPct(20))
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:220]: why is pureEnergy being using direct comparison?

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 12]
```diff
@@ -15,124 +15,239 @@
...
+            }
+        }
     }
 
-private:
-    bool _energyCooldown;
+    // State tracking
+    bool _energyCooldown;     // Energy spawn on cooldown
+    bool _overloaded;         // Final phase active
+    uint8_t _energyQueue;     // Pending energy spawns
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:245]: uint8

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 13]
```diff
@@ -15,124 +15,241 @@
  * with this program. If not, see <http://www.gnu.org/licenses/>.
  */
 
+// Boss encounter script for Vexallus in Magister's Terrace
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:18]: Please avoid redudant comments

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 14]
```diff
@@ -15,124 +15,241 @@
...
 #include "CreatureScript.h"
 #include "ScriptedCreature.h"
 #include "magisters_terrace.h"
 
+// Boss combat text and emotes
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:23]: Redundant comment

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 15]
```diff
@@ -15,124 +15,241 @@
...
-    SAY_KILL                        = 3,
-    EMOTE_DISCHARGE_ENERGY          = 4
+    SAY_AGGRO                       = 0,    // Combat start
+    SAY_ENERGY                      = 1,    // Pure energy spawn
+    SAY_OVERLOAD                    = 2,    // Final phase
+    SAY_KILL                        = 3,    // Player kill
+    EMOTE_DISCHARGE_ENERGY          = 4     // Energy discharge warning
 };
 
+// Combat ability spell IDs
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:33]: Same here

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 16]
```diff
@@ -15,124 +15,241 @@
...
+    SPELL_CHAIN_LIGHTNING           = 44318, // Basic attack
+    SPELL_OVERLOAD                  = 44352, // Enrage ability
+    SPELL_ARCANE_SHOCK              = 44319, // Basic attack
+    SPELL_SUMMON_PURE_ENERGY_N      = 44322, // Normal mode summon
+    SPELL_SUMMON_PURE_ENERGY_H1     = 46154, // Heroic mode summon 1
+    SPELL_SUMMON_PURE_ENERGY_H2     = 46159  // Heroic mode summon 2
 };
 
-enum Misc
+// Pure energy add AI implementation
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:46]: Redundant comment

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 17]
```diff
@@ -15,124 +15,241 @@
...
-    bool _energyCooldown;
+    // State tracking
+    bool _energyCooldown;     // Energy spawn on cooldown
+    bool _overloaded;         // Final phase active
+    uint8_t _energyQueue;     // Pending energy spawns
+    uint8_t _pureEnergy;      // Remaining energy count
+    std::array<bool, 5> _thresholdsPassed; // Health threshold tracking
 };
 
+// Register script
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:250]: Redundant comment

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 18]
```diff
@@ -15,124 +15,241 @@
...
+
+    // Only take damage from players targeting this add
+    void DamageTaken(Unit* attacker, uint32& damage, DamageEffectType, SpellSchoolMask) override
+    {
+        if (!attacker || !attacker->IsPlayer() || attacker->GetVictim() != me)
+            damage = 0;
+    }
+
+    // Apply feedback effect on death
+    void JustDied(Unit* killer) override
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:73]: call this from the boss script instead in SummonedCreatureDies()

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 19]
```diff
@@ -15,124 +15,241 @@
...
+    {
+        _JustDied();
+        if (instance)
+            instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_ENERGY_FEEDBACK);
     }
 
     void KilledUnit(Unit* victim) override
     {
-        if (victim->IsPlayer())
+        if (victim && victim->IsPlayer())
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:132]: victim cant be null here

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 20]
```diff
@@ -15,124 +15,241 @@
...
+        : BossAI(creature, DATA_VEXALLUS)
+        , _energyCooldown(false)
+        , _overloaded(false)
+        , _energyQueue(0)
+        , _pureEnergy(INITIAL_PURE_ENERGY)
+        , _thresholdsPassed({})
+    {
+    }
 
+    // Reset encounter state
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:109]: Redundant comment

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 21]
```diff
@@ -15,124 +15,241 @@
...
+    {
+        if (victim)
+        {
+            me->Attack(victim, false); // Set victim but don't allow melee
+            me->GetMotionMaster()->MoveChase(victim, 0.0f, 0.0f);
+        }
+    }
 };
 
+// Main boss AI implementation
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:90]: Redundant comment

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 22]
```diff
@@ -15,124 +15,241 @@
...
+            if (!summoner)
+                return;
+            if (Unit* target = vexallus->AI()->SelectTarget(SelectTargetMethod::Random, 0))
+            {
+                me->CastSpell(target, SPELL_ENERGY_FEEDBACK_CHANNEL, false);
+            }
+        }
+    }
+
+    // Only take damage from players targeting this add
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:59]: Comment inside the hook, in the line that specifically addresses this

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 23]
```diff
@@ -15,124 +15,241 @@
...
 {
-    NPC_PURE_ENERGY                 = 24745
+    explicit npc_pure_energy(Creature* creature) : ScriptedAI(creature) {}
+
+    // Initialize on summon
+    void IsSummonedBy(WorldObject* summoner) override
+    {
+        if (Creature* vexallus = summoner ? summoner->ToCreature() : nullptr)
+        {
+            if (!summoner)
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:52]: call this as the first thing in the function and return early instead

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 24]
```diff
@@ -21,118 +21,222 @@
...
-        if (victim->IsPlayer())
+        if (victim && victim->IsPlayer())
             Talk(SAY_KILL);
     }
 
-    void JustEngagedWith(Unit* /*who*/) override
+    void JustEngagedWith(Unit* victim) override
     {
         _JustEngagedWith();
+        AttackStart(victim);
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:129]: why do you need this? its already called in MoveInLineOfSight()

File: src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp [hunk 25]
```diff
@@ -21,118 +21,222 @@
...
+    // Check for final phase transition
+    void CheckOverload()
     {
-        if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0))
+        if (!_overloaded && _pureEnergy == 0 && !_energyCooldown && HealthBelowPct(20))
         {
-            summon->GetMotionMaster()->MoveFollow(target, 0.0f, 0.0f);
-            summon->CastSpell(target, SPELL_ENERGY_FEEDBACK_CHANNEL, false);
+            Talk(SAY_OVERLOAD);
+            me->TextEmote("Vexallus overloads!", nullptr, true);
```
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:211]: Use creature_text instead, we can't merge hard coded text

File: data/sql/updates/pending_db_world/rev_1737753927638017570.sql [hunk 26]
```diff
@@ -0,0 +1,9 @@
+-- Add pure energy immune script for Vex
+DELETE FROM `creature_template` WHERE `ScriptName` = 'npc_pure_energy' AND entry = 24745;
+UPDATE `creature_template` SET `ScriptName` = 'npc_pure_energy' WHERE (`entry` = 24745);
+-- AOE_IMMUNE Flag for pure energy
+UPDATE `creature_template` SET `flags_extra` = (`flags_extra` | 4194304) WHERE (`entry` = 24745);
+-- Vexallus (Entry: 24744) Overload Emote
+DELETE FROM `creature_text` WHERE `CreatureID` = 24744 AND `GroupID` = 5 AND `ID` = 0;
+INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
+(24744, 5, 0, 'Vexallus overloads!', 41, 0, 100, 0, 0, 0, 0, 0, 'Vexallus - EMOTE_OVERLOAD');
```
Comment (Nyeriah) [inline data/sql/updates/pending_db_world/rev_1737753927638017570.sql:9]: missing broadcast_text

**Comment by Nyeriah** [comment]
Please fix the remaining issue and I will merge it and do the necessary refactor changes later. Thanks for the PR

**Comment by Nyeriah** [comment]
broadcast_text is a static branch, we don't add, update or remove entries from it

SELECT * FROM broadcast_text WHERE maletext LIKE "%overloads!%";

image

**Comment by blinkysc** [comment]
Ahh ok, I'll change that then to 23781

**Review by Rorschach91 — APPROVED** [review]

File: data/sql/updates/pending_db_world/rev_1737753927638017570.sql [hunk 27]
```diff
@@ -0,0 +1,11 @@
+-- Add pure energy immune script for Vex
+DELETE FROM `creature_template` WHERE `ScriptName` = 'npc_pure_energy' AND entry = 24745;
```
Comment (Nyeriah) [inline data/sql/updates/pending_db_world/rev_1737753927638017570.sql:2]: Never delete from creature_template!
Note to devs: don't edit this file, it will delete the creature if the query is reapplied
