### PR TITLE
fix(DB/Creature): Fix Reanimated Exarch unit_flags after spawn

### LINKED ISSUE #25451: Quest Fallen Exarch bugged invulnerable spawn
### Current Behaviour

When coffin is opened during quest The Fallen Exarch (10915) an enemy is not attackable and follows player character while not attacking.

### Expected Behaviour

The npc should fight the player

### Source

_No response_

### Steps to reproduce the problem

1. Start the quest
2. Open the coffin

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. eff2cac905ac 2026-04-12 07:34:17 -0300 (master branch) (Win64, RelWithDebInfo, Static)
Connected players: 1. Characters in world: 1.
Connection peak: 1.
Server uptime: 28 minute(s) 59 second(s)
Update time diff: 1ms. Last 500 diffs summary:
|- Mean: 2ms
|- Median: 2ms
|- Percentiles (95, 99, max): 4ms, 5ms, 11ms
Using SSL version: OpenSSL 3.6.1 27 Jan 2026 (library: OpenSSL 3.6.1 27 Jan 2026)
Using Boost version: 1.90.0
Using CMake version: 4.3.0
Using MySQL version: 80408
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.4/bin/mysql.exe
Compiled on: Windows 10.0.26200
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in C:/AzerothCore/Build/bin/RelWithDebInfo/Data/maps. Total size: 291014951 bytes
vmaps directory located in C:/AzerothCore/Build/bin/RelWithDebInfo/Data/vmaps. Total size: 657797442 bytes
mmaps directory located in C:/AzerothCore/Build/bin/RelWithDebInfo/Data/mmaps. Total size: 2192760616 bytes
Default DBC locale: enUS.
All available DBC locales: enUS koKR frFR zhCN esES
Using World DB: ACDB 335.16-dev
Latest LoginDatabase update: acore_cms_subscriptions.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: trasm_world_VendorItems.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-ah-bot-plus
|- mod-autobalance
|- mod-transmog

### Operating system

Windows 11

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by XenonR**
## Changes Proposed:
This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:
- Closes #25451

## SOURCE:
The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick).

## Tests Performed:
This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:
1. `.quest add 10915`
2. Attack Reanimated Exarch (id:22452)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Not sure exactly what the current behavior looks like, but it may be that the immunity flag should be removed during the AI scripting rather than from the creature's template.

EDIT: Based on the video in the linked issue, the creature should spawn as immune, give a text line, do a spell cast animation RP thing, and then lose immunity and begin combat.

**Comment by XenonR** [comment]
> Not sure exactly what the current behavior looks like, but it may be that the immunity flag should be removed during the AI scripting rather than from the creature's template.

There is a short dialog so it could be.

I just familiarized myself with the DB. How/where can I find the associated AI script?

**Comment by heyitsbench** [comment]
> How/where can I find the associated AI script?

It is likely to be located in the `smart_scripts` table. Good few users use [Keira](https://www.azerothcore.org/Keira3/) to interact with/modify this table, especially beginners.

**Comment by XenonR** [comment]
It looks highly likely to be indeed in `smart_scripts` since there is already a SMART_ACTION_REMOVE_UNIT_FLAG defined. ~~Is my understanding correct that this is a subtraction field?~~

~~If so everything seems to be configured, but does not have an effect.~~

Also tested with `unit_flags` = 2 and tried removing 2 in the `smart_script`. Then the NPC can attack the player but the player can not attack. So it feels the removal of the unit flag is not working.

Further testing shows that the `smart_script` works as expected when switching the target from `8 - Position` to `1 - Self`.

**Comment by Rorschach91** [comment]
You must set target_o value from row 2 (it must be 0).

I don't know who did this AI in the past, but I suspect that whoever did this duplicated row 1, changed the action_type, but forgot to set target_type on self (in fact, row 1 and 2 have the same value in Target_o).

Anyway, apart from the target_o value in row 2, this PR fixes the issue. If you want I will approve and merge it when you fix the last issue but, if you want to learn something new, I can tell you how to improve it.

**Comment by Nyeriah** [comment]
Please update the PR title so it reflects what's being proposed

**Comment by XenonR** [comment]
> You must set target_o value from row 2 (it must be 0).
> 
> I don't know who did this AI in the past, but I suspect that whoever did this duplicated row 1, changed the action_type, but forgot to set target_type on self (in fact, row 1 and 2 have the same value in Target_o).
> 
> Anyway, apart from the target_o value in row 2, this PR fixes the issue. If you want I will approve and merge it when you fix the last issue but, if you want to learn something new, I can tell you how to improve it.

`target_o` is now 0. But please, elaborate on the mentioned improvements. I'm UTC+2 and also avaialble in Discord as `Xenon`.

**Comment by Rorschach91** [comment]
> `target_o` is now 0. But please, elaborate on the mentioned improvements. I'm UTC+2 and also avaialble in Discord as `Xenon`.

The problem is that there are three different xenon on AC discord.

First of all, let's see what the current AI does:

Row 0: On Update (after 500ms) -> Talk -> Self
Row 1: On Update (after 4500ms) -> Set Orientation -> Position (4,72)
Row 2: On Update (after 5500ms) -> Remove Unit Flags 768 -> Self (with your fix)
Row 3: Link (linked with Row 2) -> Start Attacking -> Closest Player in a Max range of 20 yards
Row 4: In Combat -> Cast Spell 8258 -> Self (No Repeat)

Basically what is this AI doing? It is telling the NPC that, when its AI is initialized, it must talk after 500ms, set orientation after 4500ms, remove unit flags 768 and start attacking the player after 5500ms.

The starting point is when the creature is summoned.

Considering that the event used is On_Update (it is a recurring event that occurs regardless of whether the NPC is in combat or not) whoever created this AI used flags like Don't Reset and Not Repeatable to prevent them from occurring again after the NPC is spawned.

In a few words it is doing a chain of actions that have, as their starting point, when the creature is summoned in the world. The fact is that AzerothCore has a specific method to handle this type of structure. This method is the Timed Action Lists.

The Timed Action List, in practice, is a series of linked actions (where you can set up the timing for each of them) that you can call from a Entry SmartAI or a Guid SmartAI simply using a specified smart action (like CALL_TIMED_ACTIONLIST (80)).

This is an example for Reanimated Exarch: 

On_Respawn -> Call_timed_actionlist -> Self

or

Just_Summoned -> Call_Timed_Actionlist -> Self

In both cases, flags like Dont_Reset and Not_Repeatable are useless, considering that this event only occurs when the npc spawns.

The Action Lists can be created using the npc entry + two final values (for example Reanimated Exarch 2245200, 2245201 etc.)

An example of Action List for this creature:

Timing (500ms - 500ms) -> Say Line 0 -> Self
Timing (4000ms - 4000ms) -> Set Orientation -> Position (4.72)
Timing (1000ms - 1000ms) -> Remove Unit Flags (768) -> Self
Timing (0ms - 0ms) -> Start attacking -> Closest Player in a Max range of 20 yards

Note: The timers are changed because now the starting point is no longer when the creature spawns, but when the action list starts and how much time must pass between one action and another.

Naturally, with this structure, the old Entry SAI rows 0, 1, 2 and 3 become useless. You can set a new row 0 to call the action list, and row 4 can become row 1.

I hope this explanation is helpful to you.

**Comment by XenonR** [comment]
All right. From my perspective I'm done. Please Review.
I also changed the "look at position" to "look at closest player" with the same 20y as the "start attack"  later.

File: data/sql/updates/pending_db_world/npc_22452_quest_10915.sql [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+(2245200, 9, 2, 0, 0, 0, 100, 0, 1000, 1000, 0, 0, 0, 0, 19, 768, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Reanimated Exarch - Actionlist - Remove Flags Immune To Players & Immune To NPC\'s'),
+(2245200, 9, 3, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, 0, 21, 20, 0, 0, 0, 0, 0, 0, 0, 'Reanimated Exarch - Actionlist - Start Attacking');
+
+UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 22452;
+DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `entryorguid` = 22452);
+INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param6`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
+(22452, 0, 0, 0, 60, 0, 100, 0, 500, 500, 0, 0, 0, 0, 80, 2245200, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Reanimated Exarch - On Update - Run Script'),
```
Comment (Rorschach91) [inline data/sql/updates/pending_db_world/npc_22452_quest_10915.sql]: Change Event from On Update to On_Respawn or Just Summoned (The second one probably is the best option). Otherwise it will try to repeat the action list every 500ms if it should go out of combat.

Comment (XenonR) [reply data/sql/updates/pending_db_world/npc_22452_quest_10915.sql]: changed event to 54 (just summoned)

**Review by Rorschach91 — APPROVED** [review]
