### PR TITLE
fix(Core/SAI) Add missing parameters for SMART_ACTION_MOVE_TO_POS

### LINKED ISSUE #1326: [EPIC] Align SmartAI to TrinityCore
This will make easy to exchange SmartAI scripts between AzerothCore and TrinityCore

### Global
- [x] Add missing fields in the table

### Event
- There are some minor difference in Events, shouldn't be an issue. But feel free to investigate.

### Action
- [x] Move `SMART_ACTION_SET_SIGHT_DIST` to `121`
- [x] Move `SMART_ACTION_FLEE` to `122`
- [x] Move `SMART_ACTION_ADD_THREAT` to `123`
- [x] Move `SMART_ACTION_LOAD_EQUIPMENT` to `124`
- [x] Move `SMART_ACTION_TRIGGER_RANDOM_TIMED_EVENT` to `125`
- [x] Move `SMART_ACTION_REMOVE_ALL_GAMEOBJECTS` to `126`

- [x] Remove the remaining extra overlap in enum (after the moves above)

- [x] Reserve missing enums, display proper error if someone tries to use them

- [x] `SMART_ACTION_ADD_QUEST` -> `SMART_ACTION_OFFER_QUEST` https://github.com/TrinityCore/TrinityCore/commit/ba4d6f63936fe3269e6c8b75358bc00a78fd49df
- [x] Add param3 to SMART_ACTION_CAST and SMART_ACTION_INVOKER_CAST (but be careful since we already have a param3 there, so maybe add that as param4 ?) https://github.com/TrinityCore/TrinityCore/commit/9072e0221b39c19fb6be154c623f45d6a9433db0
- [x] Get rid of unused parameter 'storageId' (third) in SMART_ACTION_SUMMON_CREATURE https://github.com/TrinityCore/TrinityCore/commit/a5c248b60ffd4981f6f62bc0640b4fcf1321a8c3
- [x] Reserve smart action 16 https://github.com/TrinityCore/TrinityCore/commit/4e55e797532ca404ce0e1e603762c17ead760f45
- [x] Core/Scripts: Extended SMART_ACTION_SET_INST_DATA to also set BossStates. https://github.com/TrinityCore/TrinityCore/commit/d1d0c64ad11cb3faf986a5332fec6b704fb8026c
- [ ] (Optional) cleaning https://github.com/TrinityCore/TrinityCore/commit/84bff76ba054683ca497b8b758cb86728d5f52a2
- [ ] Solve enum conflict `SMART_ACTION_SET_DATA` vs `SMART_ACTION_MOVE_FORWARD` 
- [ ] Rename `SMART_ACTION_SET_FLY` to `SMART_ACTION_SET_DISABLE_GRAVITY` (part of this big commit of Xinef1 https://github.com/TrinityCore/TrinityCore/commit/b0ae5fadd19fd172ec5154cde4f4fd14aa20ff88)
- [x] Add missing parameters for `SMART_ACTION_MOVE_TO_POS` (this and probably others too: https://github.com/TrinityCore/TrinityCore/commit/60d1c0e20d3f8f32de81bff047531b927e586a97)
- [ ] Solve `SMART_ACTION_ENABLE_TEMP_GOBJ` vs `SMART_ACTION_RESPAWN_TARGET` enum conflict
- [x] Replace `SMART_ACTION_INVOKER_CAST` with `SMART_ACTION_SELF_CAST` in action `85`. `SMART_ACTION_INVOKER_CAST` moves to `134` https://github.com/TrinityCore/TrinityCore/commit/0df3cb5bcc8097070b1f215032d3914d6a577f01
- [ ] Investigate how `SMART_ACTION_JUMP_TO_POS` parameters differ
- [ ] Investigate how `SMART_ACTION_SET_HOME_POS` parameter is different

- [ ] Add missing actions (some of them from the same big commit of Xinef1 mentioned above https://github.com/TrinityCore/TrinityCore/commit/b0ae5fadd19fd172ec5154cde4f4fd14aa20ff88)

### Target
- [x] Move `SMART_TARGET_FARTHEST` to `28`
- [x] Reserve missing enums, display proper error if someone tries to use them
- [x] Implement `SMART_TARGET_LOOT_RECIPIENTS`
- [x] Implement `SMART_TARGET_VEHICLE_PASSENGER`

- There are more minor differences in Targets, feel free to investigate them.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/68927156-epic-align-smartai-to-trinitycore?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Pondaveia**
##### CHANGES PROPOSED:

-  Title

###### ISSUES ADDRESSED:

Closes part of #1326 - Add missing parameters for SMART_ACTION_MOVE_TO_POS

##### TESTS PERFORMED:

- Haven't tested yet

##### Target branch(es):

Master

### CODE REVIEW

File: src/server/game/AI/SmartScripts/SmartScript.cpp [hunk 1]
```diff
@@ -1888,9 +1888,14 @@ void SmartScript::ProcessAction(SmartScriptHolder& e, Unit* unit, uint32 var0, u
...
-        else // Xinef: we can use dest.x, dest.y, dest.z to make offset :)
-            me->GetMotionMaster()->MovePoint(e.action.MoveToPos.pointId, target->GetPositionX() + e.target.x, target->GetPositionY() + e.target.y, target->GetPositionZ() + e.target.z, true, true, e.action.MoveToPos.controlled ? MOTION_SLOT_CONTROLLED : MOTION_SLOT_ACTIVE);
-
+        else
+        {
+            float x, y, z;
+            target->GetPosition(x, y, z);
+            if (e.action.MoveToPos.ContactDistance > 0)
+                target->GetContactPoint(me, x, y, z, e.action.MoveToPos.ContactDistance);
+            me->GetMotionMaster()->MovePoint(e.action.MoveToPos.pointId, x, y, z, e.action.MoveToPos.controlled ? MOTION_SLOT_CONTROLLED : MOTION_SLOT_ACTIVE);
```
Comment (Stoabrogga) [inline src/server/game/AI/SmartScripts/SmartScript.cpp]: I think you should add the AC specific change here (adding an offset by specifying additional x,y,z in the SAI entry, see Xinef's comment above):
```suggestion
            me->GetMotionMaster()->MovePoint(e.action.MoveToPos.pointId, x + e.target.x, y + e.target.y, z + e.target.z, e.action.MoveToPos.controlled ? MOTION_SLOT_CONTROLLED : MOTION_SLOT_ACTIVE);   
```
Some AC scripts could depend on it. It would also be good to preserve Xinef's comment here.

File: src/server/game/AI/SmartScripts/SmartScript.cpp [hunk 2]
```diff
@@ -1888,9 +1888,14 @@ void SmartScript::ProcessAction(SmartScriptHolder& e, Unit* unit, uint32 var0, u
 
             me->GetMotionMaster()->MovePoint(e.action.MoveToPos.pointId, dest.x, dest.y, dest.z, true, true, e.action.MoveToPos.controlled ? MOTION_SLOT_CONTROLLED : MOTION_SLOT_ACTIVE);
         }
-        else // Xinef: we can use dest.x, dest.y, dest.z to make offset :)
-            me->GetMotionMaster()->MovePoint(e.action.MoveToPos.pointId, target->GetPositionX() + e.target.x, target->GetPositionY() + e.target.y, target->GetPositionZ() + e.target.z, true, true, e.action.MoveToPos.controlled ? MOTION_SLOT_CONTROLLED : MOTION_SLOT_ACTIVE);
-
+        else
```
Comment (Pondaveia) [inline src/server/game/AI/SmartScripts/SmartScript.cpp]:
```suggestion
        else // Xinef: we can use dest.x, dest.y, dest.z to make offset
```

**Comment by Stoabrogga** [comment]
@Pondaveia 
Could you please also update the comment here?
https://github.com/azerothcore/azerothcore-wotlk/blob/dc490dd430df3440a8ae14492b2205bdaa4f53d8/src/server/game/AI/SmartScripts/SmartScriptMgr.h#L502
Just to mention the parameters:
```cpp
SMART_ACTION_MOVE_TO_POS = 69, // PointId (optional x,y,z offset), transport, controlled, ContactDistance
```
And we should not forget to update the comment on the wiki concerning the offset for action type 69:
https://github.com/azerothcore/wiki/blob/master/docs/smart_scripts.md#action_type

**Comment by Stoabrogga** [comment]
Oh, one more thing: Please remove the "Closes" in your comment or otherwise the merge will close the issue (this PR is only part of the issue).

**Comment by Pondaveia** [comment]
That should do the trick

**Comment by Stoabrogga** [comment]
I updated your comment, hope It's not a problem. Now it is correctly linked and won't be automatically closed.

**Comment by Stoabrogga** [comment]
Tested successfully both quests "Alien Egg" (PR #1303) and "Lazy Peons" (PR #1348), so this PR should be good to go.

File: src/server/game/AI/SmartScripts/SmartScript.cpp [hunk 3]
```diff
@@ -1888,9 +1888,14 @@ void SmartScript::ProcessAction(SmartScriptHolder& e, Unit* unit, uint32 var0, u
...
-        else // Xinef: we can use dest.x, dest.y, dest.z to make offset :)
-            me->GetMotionMaster()->MovePoint(e.action.MoveToPos.pointId, target->GetPositionX() + e.target.x, target->GetPositionY() + e.target.y, target->GetPositionZ() + e.target.z, true, true, e.action.MoveToPos.controlled ? MOTION_SLOT_CONTROLLED : MOTION_SLOT_ACTIVE);
-
+        else // Xinef: we can use dest.x, dest.y, dest.z to make offset
+        {
+            float x, y, z;
+            target->GetPosition(x, y, z);
+            if (e.action.MoveToPos.ContactDistance > 0)
+                target->GetContactPoint(me, x, y, z, e.action.MoveToPos.ContactDistance);
+            me->GetMotionMaster()->MovePoint(e.action.MoveToPos.pointId, x + e.target.x, y + e.target.y, z + e.target.z, e.action.MoveToPos.controlled ? MOTION_SLOT_CONTROLLED : MOTION_SLOT_ACTIVE);
```
Comment (Stoabrogga) [inline src/server/game/AI/SmartScripts/SmartScript.cpp]: One last thing, please remove the trailing blanks here:
```suggestion
            me->GetMotionMaster()->MovePoint(e.action.MoveToPos.pointId, x + e.target.x, y + e.target.y, z + e.target.z, e.action.MoveToPos.controlled ? MOTION_SLOT_CONTROLLED : MOTION_SLOT_ACTIVE);
```

**Comment by Pondaveia** [comment]
Thanks for the help @Stoabrogga

**Comment by poszer** [comment]
Thank you guys @Pondaveia & @Stoabrogga  :+1:

**Comment by Stoabrogga** [comment]
PR for the wiki concerning the AC specific offset handling: https://github.com/azerothcore/wiki/pull/52
