### PR TITLE
fix(Scripts/The Underbog): Rewritten The Black Stalker's Levitate mec…

### LINKED ISSUE #13988: [The Underbog] NPC - The Black Stalker - Levitate
### Current Behaviour

1. Does not move the levitation target.
2. Also, the second debuff "Suspension" doesn't seem to work correctly. Sometimes the player does not get it (it looks like he is the current target of the boss), and if he does, then the debuff timer does not work like in the video.
https://www.wowhead.com/tbc/spell=31719/suspension
3. If there are several targets, then the target of levitation can be the current target of the boss

### Expected Blizzlike Behaviour

https://youtu.be/sr6ryq4_-74?t=8618 - 2:23:40
1. The Black Stalker moves the levitation target
2. Also pay attention to the "Suspension" timer:
2:23:42 - 19 sec
2:23:43 - 9 sec
2:23:44 - 4 sec
3. I assume levitation should not be used on the boss's current target. Druid fight solo with her and does not get levitation even once for the whole fight
https://youtu.be/84EwSSiXjJ8?t=732 - 12:12

### Source

https://youtu.be/sr6ryq4_-74?t=8618 - 2:23:40
https://youtu.be/84EwSSiXjJ8?t=732 - 12:12
https://www.wowhead.com/tbc/spell=31704/levitate
https://www.wowhead.com/tbc/spell=31719/suspension

### Steps to reproduce the problem

.go cr 138323

### Extra Notes

Rework The Black Stalker (TrinityCore). Maybe fix the problems indicated in the report.
https://github.com/TrinityCore/TrinityCore/pull/28040/commits/36745618356f4742459bbe4cfbabaaa3d9e26369

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/55957fbb6e24f2fb6df57c92b829ad42498afee0

### Operating system

Windows 10 x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
…hanic.
Done by @offl 

Fixes #13988

Levitation duration will be fixed with #14448.

## Issues Addressed:

- Closes #13988

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.go cr 138323`

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by IntelligentQuantum — APPROVED** [review]

File: src/server/scripts/Outland/CoilfangReservoir/underbog/boss_the_black_stalker.cpp [hunk 1]
```diff
@@ -180,8 +164,98 @@ class spell_gen_allergies : public AuraScript
...
+
 void AddSC_boss_the_black_stalker()
 {
     RegisterUnderbogCreatureAI(boss_the_black_stalker);
     RegisterSpellScript(spell_gen_allergies);
+    RegisterSpellScript(spell_the_black_stalker_levitate);
+    RegisterSpellScript(spell_the_black_stalker_levitation_pulse);
+    RegisterSpellScript(spell_the_black_stalker_someone_grab_me);
+    RegisterSpellScript(spell_the_black_stalker_magnetic_pull);
+
```
Comment (Kitzunu) [inline src/server/scripts/Outland/CoilfangReservoir/underbog/boss_the_black_stalker.cpp:260]:
```suggestion
```

**Review by Kitzunu — APPROVED** [review]
