### PR TITLE
fix(DB/Creature) Sunfury Bloodwarder do not intercept anymore

### LINKED ISSUE #21146: Sunfury Bloodwarder in Netherstorm
Linked CC: https://github.com/chromiecraft/chromiecraft/issues/7676

### Current Behaviour

Sunfury Bloodwarders in Netherstorm have intercept. According to wowhead and my past experience , they arent supposed to.

### Expected Blizzlike Behaviour

Sunfury Bloodwarder is supposed to have two ablities, Enrage and Mark of Sunfury.

### Source

https://www.youtube.com/watch?v=cYcjPrZqi24

### Steps to reproduce the problem

1. .go c 67305
2. Creature intercepts

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/03c263f88e0c0f217b40a667fce68b5504f2309c

### Operating system

Win10 x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by Exitare**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/7676
- Closes #21146 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

https://www.youtube.com/watch?v=rNdIKVm2d0U

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by TheSCREWEDSoftware** [comment]
You dont need to open a AC issue if you have a direct fix upon confirming it in CC.

Also did you find any video proving what the author mentioned about not using intercept but using the mark of something? The video you left in the CC issue was video killing a quest npc.

File: data/sql/updates/pending_db_world/rev_1736654302862534200.sql [hunk 1]
```diff
@@ -0,0 +1,2 @@
+-- Remove intercept from smart AI
+DELETE FROM `smart_scripts` WHERE (`entryorguid` = 18853) AND (`source_type` = 0) AND (`id` IN (0));
```
Comment (elthehablo) [inline data/sql/updates/pending_db_world/rev_1736654302862534200.sql:2]: need to update the ids on the other spells. I think in this case it maybe be better to just delete all actions of this creature and insert the two other rows.

**Review by elthehablo — CHANGES_REQUESTED** [review]

File: data/sql/updates/pending_db_world/rev_1736654302862534200.sql (hunk 1 above)
Comment (TheSCREWEDSoftware) [reply data/sql/updates/pending_db_world/rev_1736654302862534200.sql:2]: IDs dont need to be filled in order to my knowledge. In this case assuming he is just deleting intercept.

**Comment by Exitare** [comment]
I updated the source @TheSCREWEDSoftware. my oversight. At around 0:50 seconds (accidental) pull can be observed.

**Comment by TheSCREWEDSoftware** [comment]
Removing the ability that i don't seem to find a source is good but since we are touching the unit we could add the missing ability.

https://youtu.be/i5T9Un0kL_A?si=KAVz4DVF84uKmsju&t=91
being [mark of the sunfury](https://www.wowhead.com/wotlk/spell=35877/mark-of-the-sunfury) (which they have if you mind-control them) [altervista](https://wowgaming.altervista.org/aowow/?spell=35877)

**Comment by Exitare** [comment]
@TheSCREWEDSoftware  your source: https://wowgaming.altervista.org/aowow/?npc=18853 shows that they use Intercepts though. but the videos don't ?

**Comment by TheSCREWEDSoftware** [comment]
The video i provided shows you that the ability (mark of something, im on the phone now) is used by that NPC. Looking at Altervista and wowhead Bloodwarder and Guard something have the same abilities (in the case of altervsita since is our database, it the controler or something abilities) that will show you the 1) mark and 2) enrage and I'm assuming that the guard behaves as the same as the Warder. It's a matter to find sources to prove that (or go on retail and sniff the data). / validate the data.

Recently I had a issue with a bird, birds tend to have "swoop", so when it doesnt have it's a rare case. All videos i found and was intially shared with me only that mob from private server had "swoop" every tbc, wotlk, tbc classic, wotlk classic or retail videos didn't show that mob had swoop. Until there was 1 video out of 30 that had swoop in tbc or wotlk version so we didn't remove it.

So when I tell you (the sql) is fine in deleting the ability we just have to make sure we are deleting and/or adding the correct one(s) if any missing.

**Comment by Exitare** [comment]
I updated the casts  for both npcs but i have no exact timings as to when the spell is cast after the fight started and what the schedule of the spell is.

**Comment by Nyeriah** [comment]
Reasonable timing will do, but please fill the comment field

**Comment by Exitare** [comment]
@Nyeriah  added :)

**Review by Nyeriah — APPROVED** [review]
