### PR TITLE
fix(DB/creature): Adjust creature spawn location at Badlands

### LINKED ISSUE #5696: (DB/creature): Wrong NPC spawn location at Badlands
Original report at https://github.com/chromiecraft/chromiecraft/issues/562

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Mobs spawned inside textures
DB GUID 6947
inside

DB GUID 7614 and DB GUID 6915
inside2

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mobs should not be spawned inside ground.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to provided GUID
2. See spawn points for those mobs

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98327454-db-creature-wrong-npc-spawn-location-at-badlands?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Hacki95**
## Changes Proposed:
- Update x, y, z and orientation of those 3 NPCS

## Issues Addressed:

- Closes #5696
- Closes https://github.com/chromiecraft/chromiecraft/issues/562

## SOURCE:

- https://github.com/brotalnia/database/blob/master/world_full_12_november_2020.7z

## Tests Performed:

- Applied SQL
- Checked ingame

## How to Test the Changes:

1. Apply SQL
2. .go cr guid

## Known Issues and TODO List:

- /

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Review by Si1ker — CHANGES_REQUESTED** [review]
Your fix is making them fall to the void. (7614 and 6915)

image

**Comment by Hacki95** [comment]
Ahh okay this seems to be part of the map problem then, in vmangos they don't.

File: data/sql/updates/pending_db_world/rev_1620466647964636420.sql [hunk 1]
```diff
@@ -0,0 +1,6 @@
+INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1620466647964636420');
+
+UPDATE `creature` SET `position_x`=-7133.56, `position_y`=-3161.51, `position_z`=244.252, `orientation` = 1.04837 WHERE `guid`=6947;
+UPDATE `creature` SET `position_x`=-6650.07, `position_y`=-3484.77, `position_z`=258.771, `orientation` = 1.16804 WHERE `guid`=7614;
+UPDATE `creature` SET `position_x`=-6649.06, `position_y`=-3482.49, `position_z`=259.517, `orientation` = 4.37896 WHERE `guid`=6915;
```
Comment (Si1ker) [inline data/sql/updates/pending_db_world/rev_1620466647964636420.sql:5]:
```suggestion
UPDATE `creature` SET `position_x`=-6649.06, `position_y`=-3482.49, `position_z`=263.517, `orientation` = 4.37896 WHERE `guid`=6915;
```

6947 ✔️ perfect
7614 ✔️ at the server start it falls, after 2 seconds, it always gets the right position above the ground. 
6915 ❌ always fails underground, still needs a small adjustment of 4, 263 always works

@Hacki95 🐱

**Review by Si1ker — APPROVED** [review]
