### PR TITLE
fix(CORE/Achievements) Fix Oh Novos! achievement (#23539)

### LINKED ISSUE #23539: [Drak'Tharon Keep] Oh Novos! achievement problem
### Current Behaviour

It seems that the adds that get summoned by [Summon Minions](https://wowgaming.altervista.org/aowow/?spell=59910) effect [Oh Novos!](https://wowgaming.altervista.org/aowow/?achievement=2057) which make it nearly impossible to get the achievement

### Expected Behaviour

Adds that get summoned by [Summon Minions](https://wowgaming.altervista.org/aowow/?spell=59910) should not have any affect on [Oh Novos!](https://wowgaming.altervista.org/aowow/?achievement=2057)

### Source

[Wotlk Classic Heroic](https://youtu.be/aF7rMGiC4HE?t=116)
- They got the achievement by only now allowing the adds from going down the stairs

### Steps to reproduce the problem

1. .go c id 26631
2. Start the fight with [Novos the Summoner](https://wowgaming.altervista.org/aowow/?npc=26631)
3. Stay at the top of stairs and kill all the adds before reaching the floor while killing all 4 [Crystal Handler](https://wowgaming.altervista.org/aowow/?npc=26627)
4. After killing all 4 [Crystal Handler](https://wowgaming.altervista.org/aowow/?npc=26627), wait for [Novos the Summoner](https://wowgaming.altervista.org/aowow/?npc=26631) to cast [Summon Minions](https://wowgaming.altervista.org/aowow/?spell=59910)
5. Kill [Novos the Summoner](https://wowgaming.altervista.org/aowow/?npc=26631)

### Extra Notes

This might be related to https://github.com/azerothcore/azerothcore-wotlk/issues/23483 and summoned adds from [Summon Minions](https://wowgaming.altervista.org/aowow/?spell=59910) keep running to the stairs?

### AC rev. hash/commit

AzerothCore rev. b74d3dc62be1 2025-11-03 06:50:45 +0000 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 11

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by Traesh**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [X] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #23539

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Teleport to Novos
2. Wait for the 4 crystals to disappear while killing all adds before they touch the ground
3. Wait for the adds to spawn after his shield collapse
4. See that the adds don't go to the bottom of the stair anymore, kill and and get the achievemement

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nyeriah — APPROVED** [review]

File: data/sql/updates/pending_db_world/rev_1763231123319424800.sql [hunk 1]
```diff
@@ -0,0 +1,2 @@
+DELETE FROM `smart_scripts` WHERE `entryorguid` = 27598 AND `source_type` = 0;
+UPDATE `creature_template` SET `scriptname` = '', `AIName` = '' WHERE `entry` = 27598;
```
Comment (Nyeriah) [inline data/sql/updates/pending_db_world/rev_1763231123319424800.sql]:
```suggestion
UPDATE `creature_template` SET `AIName` = '' WHERE `entry` = 27598;
```

Comment (sudlud) [reply data/sql/updates/pending_db_world/rev_1763231123319424800.sql]: was probably just making sure :D
