### PR TITLE
fix(Core/Spells): Implement TrinityCore spell_group and spell_group_stack_rules

### LINKED ISSUE #19324: Drums of Forgotten Kings stacks with Blessing of Kings.
### Current Behaviour

Currently if you cast [Drums of Forgotten Kings](https://wowgaming.altervista.org/aowow/?item=49633) and [Blessing of Kings](https://wowgaming.altervista.org/aowow/?spell=20217), the two will not overwrite each other.

### Expected Blizzlike Behaviour

The two should not stack, I assume Blessing of Kings should take priority given that it gives more stats, but not sure.

### Source

[Wowhead comments](https://www.wowhead.com/wotlk/item=49633#comments:id=848720:reply=123709)

### Steps to reproduce the problem

1. `.additem 49633`, `.learn 20217`
2. Cast the drums.
3. Cast the Blessing.
4. Observe both auras stay applied.

### Extra Notes

_No response_

### AC rev. hash/commit

f85d8433a66e98a97e0969182ecc5a1429a838b6

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

### PR DESCRIPTION
**Pull request by Tereneckla**
## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

https://trinitycore.info/en/database/335/world/spell_group
https://trinitycore.info/en/database/335/world/spell_group_stack_rules

About the removal of `IsNeedModSpellDamagePercent`, `IsNeedModMeleeDamagePercent` and `IsNeedModHealPercent` Hooks.
An alternative proposal is the removal of the `DoneTotalMod` parameter, but I don't see a use case in disabling specific `SPELL_AURA_MOD_DAMAGE_PERCENT_DONE` or `SPELL_AURA_MOD_HEALING_DONE_PERCENT` effects by script.

Originally they were added for modules from MaelstromCore here https://github.com/azerothcore/azerothcore-wotlk/commit/2b3d46bd4f52e8edf23ca77acca82ec51e9add08
But I don't see usage in the mentioned modules 3v3-soloqueue and 1v1 arena.
I am unable to find the mentioned pvestats module or the usage of those hooks in other modules by @Winfidonarleyan

New handling of voidwalker glyph would be in line with [wowhead comments](https://www.wowhead.com/wotlk/item=42473/glyph-of-voidwalker#comments:id=545948).
> This glyph does not have an immediate effect on your voidwalker if he's out when you apply it. If you resummon him, then you'll see the extra health.

Usage of the previous HandleStatModifier with a PCT value (now ApplyStatPctModifier) should be heavily discouraged as that will only be kept until the next time an AuraEffect modifying that stat is removed

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5578
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22619
- Closes #19324 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19691

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [x] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [] https://github.com/azerothcore/mod-ale/pull/335
- [] https://github.com/azerothcore/mod-autobalance/pull/217
- [] https://github.com/azerothcore/mod-solocraft/pull/63
- [] https://github.com/azerothcore/mod-zone-difficulty/pull/72

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
pvestats it was private, now azerothshard

**Comment by Tereneckla** [comment]
> pvestats it was private, now azerothshard

So the purpose of the hook is to dynamically modify the effect value of your timewalking aura so that spells are stronger or weaker dependent on the level of timewalking and the player.

Can I propose to instead do it like mod-zone-difficulty and modify the end result. 
https://github.com/azerothcore/mod-zone-difficulty/blob/da48d07cfa98bee90353d454f032bbcdf9a1c103/src/mod_zone_difficulty_scripts.cpp#L261
It has the same outcome in making spells stronger or weaker, requires less calls on the hook and in my opinion is cleaner

**Comment by MacGuzzler** [comment]
Where is the status of this? Can we give it a bump?

**Comment by Tereneckla** [comment]
waiting to be tested and reviewed
the labels are accurate

File: src/server/game/Entities/Player/PlayerStorage.cpp [hunk 1]
```diff
@@ -4355,13 +4347,12 @@ void Player::ApplyEnchantment(Item* item, EnchantmentSlot slot, bool apply, bool
...
                     break;
                 case ITEM_ENCHANTMENT_TYPE_DAMAGE:
-                    if (item->GetSlot() == EQUIPMENT_SLOT_MAINHAND)
-                        HandleStatModifier(UNIT_MOD_DAMAGE_MAINHAND, TOTAL_VALUE, float(enchant_amount), apply);
-                    else if (item->GetSlot() == EQUIPMENT_SLOT_OFFHAND)
-                        HandleStatModifier(UNIT_MOD_DAMAGE_OFFHAND, TOTAL_VALUE, float(enchant_amount), apply);
-                    else if (item->GetSlot() == EQUIPMENT_SLOT_RANGED)
-                        HandleStatModifier(UNIT_MOD_DAMAGE_RANGED, TOTAL_VALUE, float(enchant_amount), apply);
+                {
+                    WeaponAttackType const attackType = WeaponAttackType(Player::GetAttackBySlot(item->GetSlot()));
```
Comment (sogladev) [inline src/server/game/Entities/Player/PlayerStorage.cpp]:
```suggestion
                    WeaponAttackType const attackType = Player::GetAttackBySlot(item->GetSlot());
```

File: src/server/game/Entities/Player/PlayerStorage.cpp [hunk 2]
```diff
@@ -2931,12 +2932,6 @@ void Player::RemoveItem(uint8 bag, uint8 slot, bool update, bool swap)
             // remove item dependent auras and casts (only weapon and armor slots)
             if (slot < INVENTORY_SLOT_BAG_END && slot < EQUIPMENT_SLOT_END)
             {
-                // Xinef: Ensure that this function is called for places with swap=true
```
Comment (sogladev) [inline src/server/game/Entities/Player/PlayerStorage.cpp:2934]: note: This removal is good, but looks suspicious. ItemDependantAuras are handled differently than TC, may cause something to break :shrug:

File: src/server/game/Entities/Player/Player.cpp [hunk 3]
```diff
@@ -5012,24 +5005,105 @@ void Player::ClearChannelWatch()
...
+    UpdateBaseModGroup(modGroup);
+}
+
+void Player::ApplyBaseModPctValue(BaseModGroup modGroup, float pct)
+{
+    if (modGroup >= BASEMOD_END)
     {
-        case FLAT_MOD:
-            m_auraBaseMod[modGroup][modType] += apply ? amount : -amount;
+        LOG_ERROR("entities.player", "ERROR in ApplyBaseModValue(): non existed BaseModGroup!");
```
Comment (sogladev) [inline src/server/game/Entities/Player/Player.cpp]:
```suggestion
        LOG_ERROR("entities.player", "Player::ApplyBaseModPctValue: Invalid BaseModGroup/BaseModType ({}/{}) for player '{}' ({})",
            modGroup, PCT_MOD, GetName(), GetGUID().ToString());
```

Comment (sogladev) [reply src/server/game/Entities/Player/Player.cpp]: Similar for the above `void Player::HandleBaseModFlatValue(BaseModGroup modGroup, float amount, bool apply)`
```cpp
        LOG_ERROR("entities.player", "Player::HandleBaseModFlatValue: Invalid BaseModGroup/BaseModType ({}/{}) for player '{}' ({})",
            modGroup, FLAT_MOD, GetName(), GetGUID().ToString());
```

File: src/server/game/Entities/Player/PlayerStorage.cpp [hunk 4]
```diff
@@ -4631,20 +4622,9 @@ void Player::ApplyEnchantment(Item* item, EnchantmentSlot slot, bool apply, bool
...
-                            addValue = float(enchant_amount * item->GetTemplate()->Delay / 1000.0f);
-                            HandleStatModifier(UNIT_MOD_DAMAGE_MAINHAND, TOTAL_VALUE, addValue, apply);
-                        }
-                        else if (item->GetSlot() == EQUIPMENT_SLOT_OFFHAND)
-                        {
-                            addValue = float(enchant_amount * item->GetTemplate()->Delay / 1000.0f);
-                            HandleStatModifier(UNIT_MOD_DAMAGE_OFFHAND, TOTAL_VALUE, addValue, apply);
-                        }
-                    }
+                    WeaponAttackType const attackType = WeaponAttackType(Player::GetAttackBySlot(item->GetSlot()));
```
Comment (sogladev) [inline src/server/game/Entities/Player/PlayerStorage.cpp]:
```suggestion
                    WeaponAttackType const attackType = Player::GetAttackBySlot(item->GetSlot());
```

File: src/server/game/Entities/Unit/Unit.cpp [hunk 5]
```diff
@@ -5987,232 +6035,309 @@ uint32 Unit::GetDoTsByCaster(ObjectGuid casterGUID) const
...
-    if (mTotalAuraList.empty())
-        return 0;
-
-    int32 modifier = 0;
-
-    for (AuraEffectList::const_iterator i = mTotalAuraList.begin(); i != mTotalAuraList.end(); ++i)
-        modifier += (*i)->GetAmount();
+    // Add the highest of the Same Effect Stack Rule SpellGroups to the accumulator
+    for (auto itr = sameEffectSpellGroup.begin(); itr != sameEffectSpellGroup.end(); ++itr)
+        modifier += itr->second;
```
Comment (sogladev) [inline src/server/game/Entities/Unit/Unit.cpp]:
```suggestion
    for (auto const& [_, amount] : sameEffectSpellGroup)
        modifier += amount;
```

File: src/server/game/Spells/Auras/SpellAuras.h [hunk 6]
```diff
@@ -188,7 +189,7 @@ class Aura
     void HandleAuraSpecificMods(AuraApplication const* aurApp, Unit* caster, bool apply, bool onReapply);
     bool CanBeAppliedOn(Unit* target);
     bool CheckAreaTarget(Unit* target);
-    bool CanStackWith(Aura const* checkAura, bool remove) const;
+    bool CanStackWith(Aura const* checkAura) const;
```
Comment (sogladev) [inline src/server/game/Spells/Auras/SpellAuras.h]:
```suggestion
    bool CanStackWith(Aura const* existingAura) const;
```

File: src/server/game/Spells/SpellMgr.cpp [hunk 7]
```diff
@@ -1705,32 +1787,132 @@ void SpellMgr::LoadSpellGroupStackRules()
...
+            if (!found)
+                LOG_ERROR("sql.sql", "SpellId {} listed in `spell_group` with stack rule 3 does not share aura assigned for group {}", spellId, group_id);
+        }
+
+        mSpellSameEffectStack[SpellGroup(group_id)] = auraTypes;
+        ++count;
+    }
+
+    LOG_INFO("server.loading", ">> Loaded {} SPELL_GROUP_STACK_RULE_EXCLUSIVE_SAME_EFFECT stack rules in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
```
Comment (sogladev) [inline src/server/game/Spells/SpellMgr.cpp:1916]: `    LOG_INFO("server.loading", " ");
` can be removed?
```suggestion
```

File: src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp [hunk 8]
```diff
@@ -271,12 +271,12 @@ class spell_astromancer_solarian_transform : public AuraScript
...
     void OnApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
     {
-        GetUnitOwner()->HandleStatModifier(UnitMods(UNIT_MOD_ARMOR), TOTAL_PCT, 400.0f, true);
+        GetUnitOwner()->ApplyStatPctModifier(UNIT_MOD_ARMOR, TOTAL_PCT, 400.0f);
     }
 
     void OnRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
     {
-        GetUnitOwner()->HandleStatModifier(UnitMods(UNIT_MOD_ARMOR), TOTAL_PCT, 400.0f, false);
+        GetUnitOwner()->ApplyStatPctModifier(UnitMods(UNIT_MOD_ARMOR), TOTAL_PCT, -80.0f);
```
Comment (sogladev) [inline src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp:279]: This was 400.0f

File: src/server/scripts/Spells/spell_warlock.cpp [hunk 9]
```diff
@@ -317,29 +321,41 @@ class spell_warl_generic_scaling : public AuraScript
         }
     }
 
-    void CalculateAPAmount(AuraEffect const*  /*aurEff*/, int32& amount, bool& /*canBeRecalculated*/)
+    void CalculateAPAmount(AuraEffect const*  aurEff, int32& amount, bool& /*canBeRecalculated*/)
```
Comment (sogladev) [inline src/server/scripts/Spells/spell_warlock.cpp]:
```suggestion
    void CalculateAPAmount(AuraEffect const* aurEff, int32& amount, bool& /*canBeRecalculated*/)
```

File: src/server/game/Entities/Unit/Unit.cpp [hunk 10]
```diff
@@ -4743,23 +4798,16 @@ void Unit::_RemoveNoStackAurasDueToAura(Aura* aura)
     // if (spellProto->IsPassiveStackableWithRanks())
     //    return;
 
-    bool remove = false;
-    for (AuraApplicationMap::iterator i = m_appliedAuras.begin(); i != m_appliedAuras.end(); ++i)
+    if (!IsHighestExclusiveAura(aura))
```
Comment (sogladev) [inline src/server/game/Entities/Unit/Unit.cpp:4803]:
```suggestion
    ASSERT(aura);
    if (!IsHighestExclusiveAura(aura))
```

File: src/server/game/Spells/SpellMgr.cpp [hunk 11]
```diff
@@ -648,87 +645,148 @@ SpellTargetPosition const* SpellMgr::GetSpellTargetPosition(uint32 spell_id, Spe
...
+        return itr->second;
+
+    return SPELL_GROUP_STACK_RULE_DEFAULT;
 }
 
-SpellProcEventEntry const* SpellMgr::GetSpellProcEvent(uint32 spellId) const
+SpellProcEventEntry const* SpellMgr::GetSpellProcEvent(uint32 spell_id) const
 {
-    SpellProcEventMap::const_iterator itr = mSpellProcEventMap.find(spellId);
+    SpellProcEventMap::const_iterator itr = mSpellProcEventMap.find(spell_id);
```
Comment (sogladev) [inline src/server/game/Spells/SpellMgr.cpp]: > 'SpellMgr::GetSpellProcEvent' has a definition with different parameter names

```suggestion
SpellProcEventEntry const* SpellMgr::GetSpellProcEvent(uint32 spellId) const
{
    SpellProcEventMap::const_iterator itr = mSpellProcEventMap.find(spellId);
```

**Review by sogladev — CHANGES_REQUESTED** [review]
I applied SQL codestyle changes. There are some minor cpp codestyle changes I suggested.

I checked with TC335 and the changes look good overall, minus:
  - The value for the astromancer script may be wrong

This issue wasn’t mentioned, but I’ll test the DP + ToW stacking #3790.

File: src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp (hunk 8 above)
Comment (Tereneckla) [reply src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp:279]: 400.0f remove is the same as applying -80.0f

Unlike HandleStatModifier, ApplyStatPctModifier has no apply bool. Not like it should be used in scripts in the first place, less important so with NPCs and in this case Solarian dies when the Aura is removed

File: src/server/game/Entities/Player/PlayerStorage.cpp (hunk 2 above)
Comment (Tereneckla) [reply src/server/game/Entities/Player/PlayerStorage.cpp:2934]: it looked ok in my (admittedly limited) testing

File: src/server/game/Spells/SpellMgr.cpp (hunk 7 above)
Comment (Tereneckla) [reply src/server/game/Spells/SpellMgr.cpp:1916]: It is done like that in a few places so I kept it

**Comment by blinkysc** [comment]
tested https://gist.github.com/blinkysc/299eebffa47b44206fe2dc34b0493f65
